### ISSUE TITLE
Events sent from the React Native SDK, regardless of version, are incorrectly timestamped with varying offsets.

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1004]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [x]  `react-native-sentry` (<= 0.43.2)

**SDK version:** multiple
So far noticed in events sent from `1.6.x`, `1.4.x` and `0.42`

**`react-native` version:** multiple

**Are you using Expo?**
- [x]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

---
**I have following issue:**

Events seem to be incorrectly timestamped with varying degrees of offsets:
<img width="976" alt="Screen Shot 2020-07-27 at 3 47 22 PM" src="https://user-images.githubusercontent.com/30991498/88638918-5415ed00-d0e6-11ea-9927-21560ec37fb9.png">
![88414755-a650c880-cddd-11ea-8ec8-00a1f212c3ab](https://user-images.githubusercontent.com/30991498/88639253-c38bdc80-d0e6-11ea-80b3-ce04d9fa4350.png)

This seems to possibly be linked to this issue on the JS SDK that the React Native SDK wraps: 
https://github.com/getsentry/sentry-javascript/issues/2590

Mentioned in issues
#994 
#951 

**Steps to reproduce:**
Can be seen in a high number of events sent from the SDK lately.

**Actual result:**

They seem to be timestamped incorrectly.

**Expected result:**

Events are timestamped correctly to when they happened.

**Comment by ryanbabbly** [comment]
I am also having this problem

**Comment by StarryFire** [comment]
Same, no solution yet? This is causing breadcrumbs to appear in a random order causing them to become COMPLETELY USELESS!

**Comment by jennmueng** [comment]
https://github.com/getsentry/sentry-javascript/pull/2915 This PR fixes this and we are making a new release ASAP.

**Comment by jennmueng** [comment]
This is fixed in 1.8.1. https://github.com/getsentry/sentry-react-native/releases/tag/1.8.1
