### ISSUE TITLE
iOS Sourcemap Not Working using sentry-cli or sentry-fastlane

### ISSUE THREAD

**Issue by garrett-gottlieb** [getsentry/sentry-react-native#1024]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.7

**`react-native` version:** 0.61.4

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/think-smart-journal/issues/1839835685/?project=5178279&statsPeriod=14d

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'HIDDEN,
  enableAutoSessionTracking: true,
})
const sentryReleaseName = `${DeviceInfo.getBundleId()}-${DeviceInfo.getVersion()}`
const sentryDistName = DeviceInfo.getBuildNumber()
Sentry.setRelease(sentryReleaseName)
Sentry.setDist(sentryDistName)
```

---
**I have following issue:**

The sourcemap and source are uploaded via sentry-cli and are listed under the artifacts of the release, but the issue still says "app:///main.jsbundle in onPress at line 2019:2751"

**Steps to reproduce:**
- Bundle: `react-native bundle --dev false --platform ios --entry-file index.js --bundle-output ios/ios.main.bundle --sourcemap-output ios/ios.main.bundle.map`
- Upload: `cd ios && MARKETING_VERSION=$(xcodebuild -showBuildSettings | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =') && BUILD_VERSION=$(xcodebuild -showBuildSettings | grep CURRENT_PROJECT_VERSION | tr -d 'CURRENT_PROJECT_VERSION =') && env SENTRY_ORG=think-smart-journal SENTRY_LOG_LEVEL=info SENTRY_PROJECT=react-native yarn sentry-cli releases files com.thinksmartjournal-$MARKETING_VERSION upload-sourcemaps --dist $BUILD_VERSION --bundle ios/ios.main.bundle --bundle-sourcemap ios/ios.main.bundle.map`
- `Sentry.captureException('Test error!')`

I have also tried uploading via fastlane:
```ruby
    sentry_upload_sourcemap(
      version: app_identifier + "-" + get_version_number(xcodeproj: xcodeproj),
      dist: get_build_number(xcodeproj: xcodeproj),
      app_identifier: app_identifier,
      sourcemap: "ios.main.bundle.map",
      rewrite: true
    )
```

**Actual result:**

`app:///main.jsbundle in onPress at line 2019:2751`

<img width="835" alt="Screen Shot 2020-08-13 at 11 49 17 PM" src="https://user-images.githubusercontent.com/1219054/90212221-d24de100-ddc0-11ea-9e1f-914fc9dcf179.png">
<img width="472" alt="Screen Shot 2020-08-13 at 11 50 10 PM" src="https://user-images.githubusercontent.com/1219054/90212223-d2e67780-ddc0-11ea-8a5a-57d8571c1610.png">
<img width="418" alt="Screen Shot 2020-08-13 at 11 50 42 PM" src="https://user-images.githubusercontent.com/1219054/90212224-d37f0e00-ddc0-11ea-8448-0b340ac40d97.png">

**Expected result:**

Source map to `.ts` file.

**Comment by jennmueng** [comment]
@garrett-gottlieb You should have a dialog at the top of your error on the Sentry dashboard that says something along the lines of "Source Map not found" correct? So as I see it currently your bundle and source map is called `ios.main.bundle` and `ios.main.bundle.map` and the app is looking for a `app:///main.jsbundle`. The names have the exactly match, try uploading them again but name them `main.jsbundle` and `main.jsbundle.map` and they should work.

Also as a note just in case, the `release` and `dist` have to also exactly match on the error and the source map.

Let me know if this works for you!

**Comment by marandaneto** [comment]
@garrett-gottlieb any update on this? release and dist should match, also the file name as mentioned
