### ISSUE TITLE
setUser is not presisted when app has been closed

### ISSUE THREAD

**Issue by arelstone** [getsentry/sentry-react-native#1029]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** `1.7.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
        dsn: Config.SENTRY_URL,
        enabled: true,
        environment: __DEV__ ? 'development' : 'production',
        release: DeviceInfo.getReadableVersion(),
        enableAutoSessionTracking: true,
        beforeSend: (event: Sentry.Event) => {
            if (event.message) {
                // @ts-ignore
                trackEvent(event.message, {
                    sentryId: event.event_id,
                    level: event.level,
                    data: event.extra,
                    user: event.user,
                });
            }

            return event;
        },
    })
```

---
**I have following issue:**

[Description]
It doesn't seem like the user is presisted on android..
When a user logs into my app i invoke `Sentry.setUser` with the data of the user. When capturing an error the user data is sent. When closing and reopening the app and then capturing a message there is no user data in our sentry logs.

As a fix I am caling `Sentry.setUser` before every `Sentry.captureMessage` but i don't think that this is optimal.

**Actual result:**

#### Capturing an event just when the user has been logged in (without the app has been closed)
<img width="1078" alt="Screenshot 2020-08-17 at 11 39 17" src="https://user-images.githubusercontent.com/1322047/90382008-7ca65c80-e07e-11ea-8493-450aed90a134.png">

#### Capturing an event after the app has been closed and reopened
<img width="1089" alt="Screenshot 2020-08-17 at 11 39 13" src="https://user-images.githubusercontent.com/1322047/90382044-87f98800-e07e-11ea-83ff-28a30aa923dd.png">

**Expected result:**

I would expect that the data send to `Sentry.setUser` was presisted

**Comment by jennmueng** [comment]
Yes, the user is not persisted, along with all other scope properties when the app restarts.

This is the same with all our other SDKs. You should call `setUser` every time the app starts and your user is authenticated.

**Comment by jennmueng** [comment]
Yes it is meant to be like this, in most apps the user state is populated every time the app launches, and wouldn't make sense to persist the user state in the case that for example, the user login expires on a launch, needing a new login.
