### ISSUE TITLE
Cannot set issue title for messages or errors 

### ISSUE THREAD

**Issue by Xesme** [getsentry/sentry-react-native#1033]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.5

**`react-native` version:** 0.60.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
 
N/A this is a configuration issue. All issue titles are '<uknown>' and I cannot for the life of me figure out how to manually set them. 

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
    Sentry.init({ 
      dsn: dsn, 
      release: ---, 
      environment: ---, 
    });
```

---
**I have following issue:**

When error or messages are captured to Sentry the title is set to '<unknown>' this is a regressing from our previous version. I have read through the docs and I cannot find mention of a title property anywhere, however I did find it within the JSON of a reported issue with this <unknown> title. 

Here is an example: 
```
{"value":"Error checking for unprocessed payment"},"received":1597873045.391972,"sdk":{"version":"1.6.1","name":"sentry.javascript.react-native","packages":[{"version":"1.6.1","name":"npm:@sentry/react-native"}],"integrations":["ReactNativeErrorHandlers","Release","InboundFilters","FunctionToString","Breadcrumbs","LinkedErrors","UserAgent","RewriteFrames","DeviceContext"]},"timestamp":1597873044.711,"title":"<unknown>","type":"error","user":{"geo":{"city":"Columbus","region":"United 
```

Maybe I missed it in the documentation somewhere? Any and all help is greatly appreciated. Thanks! 

**Steps to reproduce:**
- Install and report a custom error 

**Actual result:**

Attached is a screenshot of the behavior. 

![Screen Shot 2020-08-20 at 8 03 19 AM](https://user-images.githubusercontent.com/24839005/90789366-b0ba9100-e2bb-11ea-81a3-5cb15efebb34.png)

**Expected result:**

The ability to set titles, so the Sentry logs are easily readable.

**Comment by jennmueng** [comment]
Hmm, which method are you using to capture the messages/errors?. `Sentry.captureMessage` should automatically make that message the title, along with `Sentry.captureException` making the error type the title. There currently isn't a way to directly set the title, but the two above methods should correctly set the title otherwise.

**Comment by Xesme** [comment]
No problem. I looked at our code and Sentry logs again and the issue is not with the captureMessage, it is just within the captureException. We recently upgrade from `react-native-sentry 0.43.2` to `@sentry/react-native 1.4.5` and this just started happening after the upgrade. Our existing code for capturing errors looks like this (with an example): 

```
export const captureException = (error, extra = null) => {
  if (extra) Sentry.setExtras(extra);
  if (error) Sentry.captureException(error);
};
```

`...captureException('Error could not find room(s)');`

![image](https://user-images.githubusercontent.com/24839005/91908678-cedfa400-ec60-11ea-9c5c-0b7bf157999e.png)

The odd thing is the `<unknown>` tag as the title and a subtitle being set with the actual title. Thanks for much for your help. I have been stumped on this for weeks.

**Comment by jennmueng** [comment]
Ah, so `captureException` actually only takes instances of `Error`. If you pass `new Error('Error could not find room(s)')` instead of just the string `'Error could not find room(s)'` to `captureException` it should come out correctly! If you just want to capture the string, you would then use `captureMessage`.

**Comment by jennmueng** [comment]
Closing this on the basis of being more than a year old with no updates. If the issue still persists, feel free to reopen.

**Comment by carlosen14** [comment]
> Ah, so `captureException` actually only takes instances of `Error`. If you pass `new Error('Error could not find room(s)')` instead of just the string `'Error could not find room(s)'` to `captureException` it should come out correctly! If you just want to capture the string, you would then use `captureMessage`.

I know is a bit late, but it is not 100% correct, I'm capturing this
![image](https://github.com/getsentry/sentry-react-native/assets/9368632/dcff69b7-7cf2-48d5-8ebf-feb7c1db9a49)

and it shows  "Error" as the title.. 
<img width="428" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/9368632/0b77e980-eccb-4265-9ec9-378dde79175a">

I thought it suppose to be as you did mention, or did I miss something?, I'll keep searching

**Comment by matheuscouto** [comment]
@carlosen14 if you find any solution please post here

**Comment by matheuscouto** [comment]
Actually, I figured it out. Sentry uses the Error class name as the title of the issue. If you change the error's name property, it should work:

```
const error = new Error("error message here");
error.name = "this is new";
Sentry.captureException(error);
```

<img width="180" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/20684804/6fe101b8-4b62-4af2-be21-e2724fedae85">

**Comment by robertyulisman** [comment]
> Actually, I figured it out. Sentry uses the Error class name as the title of the issue. If you change the error's name property, it should work:
> 
> ```
> const error = new Error("error message here");
> error.name = "this is new";
> Sentry.captureException(error);
> ```
> 
> <img alt="image" width="180" src="https://private-user-images.githubusercontent.com/20684804/335831041-6fe101b8-4b62-4af2-be21-e2724fedae85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjM1MjAsIm5iZiI6MTcyMjMyMzIyMCwicGF0aCI6Ii8yMDY4NDgwNC8zMzU4MzEwNDEtNmZlMTAxYjgtNGI2Mi00YWYyLWJlMjEtZTI3MjRmZWRhZTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3MDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMmFiZmI3ZmRiYjdmMDEzMWVmNDU2ZWIwMjcwMmNkZDgxY2UxMWRmNjUwYmE5NjUzZmI5NDc3NzY4ZDVjZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4MX-e8WhACmMRP50BaCPaksJI2zKLABXIsFsCAAJ-A">

its work, thanks @matheuscouto 

![Image](https://github.com/user-attachments/assets/9bf9a5e8-dd66-4e67-982b-7b672f3aa254)

**Comment by DivMode** [comment]
I noticed setting the err.name, removes some validation info, is there a way to get around this? 

With err.name it shows:
<img width="962" alt="Image" src="https://github.com/user-attachments/assets/5322c25f-7d8f-4cb5-88f0-ed69ff40aaf1" />

Without err.name it has additional data:
<img width="962" alt="Image" src="https://github.com/user-attachments/assets/54fe70c9-c792-4985-8b27-b106f5eb150f" />

<img width="962" alt="Image" src="https://github.com/user-attachments/assets/7d92a8e3-eb08-4814-b896-77011e0e8fd6" />

**Comment by krystofwoldrich** [comment]
Hi @DivMode,
thank you for the message, the additional information should not be removed when updating the error name. 

Could you share a code example in a new issue?
