### ISSUE TITLE
Invalid Hook Call Warning - Mismatching Versions of React 

### ISSUE THREAD

**Issue by walterholohan** [getsentry/sentry-react-native#1034]
After upgrading to 1.7.0 I get an `Invalid Hook Call Warning` error message. This is due to the dep `@Sentry/react` having a dependency of React that does not support Hooks. https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react. Is anyone else experiencing this issue?

**Comment by AbhiPrasad** [comment]
`@sentry/react` does not have a react dependency, only requires it as a peer dependency. - see: https://github.com/getsentry/sentry-javascript/blob/master/packages/react/package.json#L18-L29

This same behaviour exists for `@sentry/react-native`:
https://github.com/getsentry/sentry-react-native/blob/master/package.json#L38-L51

Can you provide a more detailed stack trace or steps to replicate - I am not able to duplicate. Thanks!

**Comment by AbhiPrasad** [comment]
I am closing due to lack of reproduction/response. Please re-open this ticket if the issue is still occurring.
