### ISSUE TITLE
TypeError Network request failed

### ISSUE THREAD

**Issue by patelnets** [getsentry/sentry-react-native#1049]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^1.7.1

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/second-nature-u3/issues/1860149392/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
      enableAutoSessionTracking: true,
  // other options
});
```

---
**I have following issue:**
I am getting an  'TypeError : Network request failed' which is being logged a lot more than any other error. There is no stack trace or any other details which could help identify what is causing it. Is this a problem with sentry and should I be ignoring the error?

**Expected result**
I should not have these errors or I should have better detailed errors

**Comment by jennmueng** [comment]
Hey there. I definitely understand the frustration with lack of detail in errors but I just gave a look at the issue you sent, and Sentry will just display what is sent over from your app. Sometimes network error requests just don't attach a stack trace for us to display.

**Comment by patelnets** [comment]
Thanks for the reply! So is there no way of squeezing any helpful information out of these errors and I should just ignore them?

**Comment by jennmueng** [comment]
@patelnets Hmm out of the box, this is all the info that the error provides sadly, but this does depend on what networking library you use, usually they should provide more info than this.

I assume the network errors you received were automatically caught without manually capturing the exception? Usually if you capture the error and send it to Sentry such as
```js
someNetworkRequest().catch(e => {
    Sentry.captureException(e);
}
```
, you do get rich info from most network libraries.
