### ISSUE TITLE
react-dom dependency warning from using @sentry/react

### ISSUE THREAD

**Issue by diegomais** [getsentry/sentry-react-native#1065]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.2

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

---
**I have following issue:**

I receive the warning: "@sentry/react-native > @sentry/react@5.23.0" has unmet peer dependency "react-dom@15.x || 16.x".

**Steps to reproduce:**
- Step 1 Run on terminal: `yarn add @sentry/react-native`
- Step 2 Run on terminal: `yarn audit`

**Actual result:**

Warning message.

**Expected result:**

No warning message.

**Comment by jennmueng** [comment]
Hi @diegomais! Thanks for the report, I've added it to our TODO to handle this.
