### ISSUE TITLE
How do I disable automatic breadcrumb collection? (All console logs are being recorded as breadcrumbs)

### ISSUE THREAD

**Issue by LonelyCpp** [getsentry/sentry-react-native#1066]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.2

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

```
  Sentry.init({
    dsn: SENTRY_DSN,
    environment,
    logLevel: 1,
    integrations: [
      new Sentry.Integrations.ReactNativeErrorHandlers({
        onunhandledrejection: false,
      }),
      new Sentry.Integrations.Breadcrumbs({
        console: false,
      }),
    ],
  });
```

---
**I have following issue:**

```
Unhandled promise rejection TypeError: Sentry.Integrations.Breadcrumbs is not a constructor
    at initializeSentry$ (SentryManager.js:30)
    at tryCatch (runtime.js:45)
    ...
```

**Expected result:**

`Sentry.Integrations.Breadcrumbs` should be present, and console logs should be discarded

**Comment by jennmueng** [comment]
Hi @LonelyCpp! Breadcrumbs is actually exported through `BrowserIntegrations` not `Integrations` as `Sentry.BrowserIntegrations.Breadcrumbs`. Let me know if this works for you!

**Comment by LonelyCpp** [comment]
@jennmueng Thanks, that seems to have done the trick. 

I was going through https://docs.sentry.io/platforms/javascript/integrations/default/ and it says `Sentry.Integration`. Perhaps I was looking at the wrong place?
