### ISSUE TITLE
Passing additional info to setUser displays as unknown

### ISSUE THREAD

**Issue by StebanDev** [getsentry/sentry-react-native#1074]
**OS:**
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.2

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://sentry.io/organizations/riqra-pp/issues/1892936475/?project=5422172&query=is%3Aunresolved&statsPeriod=90d)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});

Sentry.configureScope((scope) => {
      scope.setUser({
        id: 101,
        email: 'user_prueba3@test.com',
        name: 'User Hello',
        endpoint: 'companynamex.com',
      })
    })
```

---
**I have following issue:**

Sentry is not displaying user additional info passed with the `setUser` method.

**Steps to reproduce:**
- Init sentry and set a user with additional data
- Throw an error on RN side

**Actual result:**

[Actual result]
The additional info is shown together as json with an unknown label
![image](https://user-images.githubusercontent.com/13490436/93056031-72ea2780-f631-11ea-8bb7-fa3c25cbbd49.png)

**Expected result:**

I would expect to parse the additional fields as it does on another project

![image](https://user-images.githubusercontent.com/13490436/93056299-d8d6af00-f631-11ea-8c08-62e649a3bb2f.png)

**Comment by jennmueng** [comment]
Hi @StebanDev, I reproduced this. This actually occurs on our backend as I checked, the React Native SDK sends the user object with the unknown keys on the same level as the other fields. Do you mind letting me know what SDK your other project uses? Thanks.

**Comment by StebanDev** [comment]
Hi @jennmueng, thank you for the quick response. I have checked and it's working fine on 1.3.1 version.

**Comment by StebanDev** [comment]
Another thing to notice is that with latest sdk version the user properties are overridden instead of merged, e.g `IP Address` is not longer showing if not passed as a user field.

**Comment by jennmueng** [comment]
@StebanDev Hmm I will investigate this further and get back to you. Thanks!

Also, `setUser` is intended to be overwrite any existing user object set before. This is because if you have a new user in your app, you would want `Sentry.setUser` to completely change the stored user. If it was merged before then that must have been a bug.

**Comment by marandaneto** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
