### ISSUE TITLE
'Sentry/Sentry.h' file not found

### ISSUE THREAD

**Issue by pinguo-zhouwei** [getsentry/sentry-react-native#1078]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.7.2

**`react-native` version:** 0.59.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

'Sentry/Sentry.h' file not found

**Steps to reproduce:**
- 1. yarn add @sentry/react-native
- 2. react-native link @sentry/react-native
- 3. run Android and iOS
<img width="741" alt="WX20200916-150943@2x" src="https://user-images.githubusercontent.com/8786349/93303881-b8277880-f82e-11ea-8203-00a6f6cada50.png">

**Actual result:**

Android work for me, iOS error with 'Sentry/Sentry.h' file not found

**Expected result:**

Android & iOS run correctly

**Comment by jennmueng** [comment]
@pinguo-zhouwei You don't run `react-native link @sentry/react-native` anymore, instead you would run `@sentry/wizard` following the install steps here: https://docs.sentry.io/platforms/react-native/

**Comment by pinguo-zhouwei** [comment]
> @pinguo-zhouwei You don't run `react-native link @sentry/react-native` anymore, instead you would run `@sentry/wizard` following the install steps here: https://docs.sentry.io/platforms/react-native/

But the document says that this step is required for react-native> 0.60. My react-native version is 0.59.9

**Comment by jennmueng** [comment]
@pinguo-zhouwei Oh my mistake, I missed that part. After the linking step, I assume you ran `pod install`?

**Comment by pinguo-zhouwei** [comment]
> @pinguo-zhouwei Oh my mistake, I missed that part. After the linking step, I assume you ran `pod install`?

I also tried but it still doesn't work

**Comment by jennmueng** [comment]
@pinguo-zhouwei This is most likely some issue with your installation somehow and not with the SDK then, maybe cocoapods is set up wrong.

**Comment by trantus** [comment]
> @pinguo-zhouwei This is most likely some issue with your installation somehow and not with the SDK then, maybe cocoapods is set up wrong.

i have this issue too, but i dont have cocapods in my project

**Comment by marandaneto** [comment]
likely similar to https://github.com/getsentry/sentry-react-native/issues/1018 (see last comment)
so, does it still happen?

**Comment by marlti7** [comment]
same problem. has no Sentry file , how to link?
