### ISSUE TITLE
"@sentry/react-native": "1.3.7" : caused by: [56] Failure when receiving data from the peer

### ISSUE THREAD

**Issue by husadakingdom** [getsentry/sentry-react-native#1083]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

"@sentry/react-native": "1.3.7"

**`react-native` version:** 0.59.8

**Are you using Expo?**
- [ ]  Yes
- [X]  No

I face a problem in 2 days and get error message :

`info   DEBUG   2020-09-16 15:54:26.385460 +07:00 using token authentication

info   DEBUG   2020-09-16 15:54:26.385509 +07:00 retry number 0, max retries: 0

info   DEBUG   2020-09-16 15:54:26.490843 +07:00 > GET /api/0/organizations/aaa/chunk-upload/ HTTP/1.1

info   DEBUG   2020-09-16 15:54:26.490894 +07:00 > Host: sentry-new.mydomain.com

info   DEBUG   2020-09-16 15:54:26.490904 +07:00 > Accept: */*
  DEBUG   2020-09-16 15:54:26.490913 +07:00 > Connection: TE

info   DEBUG   2020-09-16 15:54:26.490926 +07:00 > TE: gzip

info   DEBUG   2020-09-16 15:54:26.490939 +07:00 > User-Agent: sentry-cli/1.55.0

info   DEBUG   2020-09-16 15:54:26.491893 +07:00 > Authorization: Bearer ***

info   DEBUG   2020-09-16 15:54:26.530470 +07:00 < HTTP/1.1 200 OK

info   DEBUG   2020-09-16 15:54:26.530507 +07:00 < X-XSS-Protection: 1; mode=block

info   DEBUG   2020-09-16 15:54:26.530517 +07:00 < Content-Language: en

info   DEBUG   2020-09-16 15:54:26.530526 +07:00 < X-Content-Type-Options: nosniff

info   DEBUG   2020-09-16 15:54:26.530535 +07:00 < Vary: Accept-Language, Cookie

info   DEBUG   2020-09-16 15:54:26.530544 +07:00 < Allow: GET, POST, HEAD, OPTIONS

info   DEBUG   2020-09-16 15:54:26.530553 +07:00 < X-Frame-Options: deny

info   DEBUG   2020-09-16 15:54:26.530562 +07:00 < Content-Type: application/json

info   DEBUG   2020-09-16 15:54:26.535550 +07:00 error: running update nagger

info   DEBUG   2020-09-16 15:54:26.535589 +07:00 skipping update nagger because session is not attended
error: API request failed

info   caused by: [56] Failure when receiving data from the peer

info   DEBUG   2020-09-16 15:54:26.541342 +07:00 client close; no transport to shut down  (from sentry)`

> Everything working fine a week before, and now always get that error for iOS (Android working fine). Any idea why?

**Comment by jennmueng** [comment]
@husadakingdom Does this issue still persist? Maybe check that the SDK can reach the domain?

**Comment by husadakingdom** [comment]
Still happen. iOS Solve but now Android get same error like above.

**Comment by husadakingdom** [comment]
@jennmueng : is it related to Sentry server or React Native Sentry library?

**Comment by jennmueng** [comment]
> @jennmueng : is it related to Sentry server or React Native Sentry library?

I'm not sure, are you running Sentry on-premise and not using the SaaS product, seeing that the error contains `Host: sentry-new.mydomain.com`?

**Comment by husadakingdom** [comment]
@jennmueng : i install Sentry on my own server. By the way, what actually error mean? react native try to download something from Sentry Server ?

**Comment by jennmueng** [comment]
@husadakingdom This looks like a failed upload to your Sentry instance, possibly a failed source map upload? https://github.com/getsentry/sentry-cli/issues/547

**Comment by husadakingdom** [comment]
@jennmueng : where the file that i put keep alive false?

I mean where location of the file to add keep alive para meter?

**Comment by jennmueng** [comment]
@husadakingdom `.sentryclirc` in the root of your React Native project, or wherever you would have the url of your local Sentry instance set for your React Native project's `sentry-cli`.

**Comment by jennmueng** [comment]
Closing this on the basis of being more than a year old with no updates. If the issue still persists, feel free to reopen.
