### ISSUE TITLE
Can't find variable: Performance

### ISSUE THREAD

**Issue by HaswinVidanage** [getsentry/sentry-react-native#1089]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.55.1

**`react-native` version:** 0.60.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

---
**I have following issue:**

Getting the error "Can't find variable: Performance"

![87251c266aae7d495e8dd772249b22ac](https://user-images.githubusercontent.com/8643302/93594723-f9fc1e80-f9e8-11ea-81ab-a49261522a5c.png)

Problem seems to originate from this method located at npm_modules/@sentry/utils/dist /misc.js

> function getReactNativePerformanceWrapper() {
    var INITIAL_OFFSET = performance.now(); // <-- This performance does not exists
    return {
        now: function () {
            return performance.now() - INITIAL_OFFSET;
        },
        timeOrigin: INITIAL_TIME,
    };
}

**Steps to reproduce:**
- `react-native run-android`

**Comment by jennmueng** [comment]
This was a mistake as we didn't add a check for RN <0.63 without `performance` being defined. You can fix this for now by downgrading to `1.8.0`

**Comment by HaswinVidanage** [comment]
it seems to fails on 1.8.0 and 1.4.x

**Comment by jennmueng** [comment]
@HaswinVidanage You might need to delete your `node_modules` before reinstalling the new version

**Comment by SocialBrothersDEV** [comment]
Same issue here. Can't release my app because of this, would love a fix.

**Comment by jennmueng** [comment]
Fixed in 1.8.2 https://github.com/getsentry/sentry-react-native/releases/tag/1.8.2

**Comment by HaswinVidanage** [comment]
Thanks for the quick fix. Works fine on 1.8.2 @jennmueng .
