### ISSUE TITLE
ReferenceError: Can't fin variable: performance

### ISSUE THREAD

**Issue by icastillejogomez** [getsentry/sentry-react-native#1090]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^1.8.1
**react native version:** 0.61.5
**Node.js version:** 14.11.0
**react native cli version:** 4.13.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
I don't know what is Sentry on-premise...
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

There is no an issue
**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

When I try to run my React Native app, I get the following error: `ReferenceError: Can't fin variable: performance`

If I click in the top stack items I can see this fragment of code:

```
function getReactNativePerformanceWrapper() {
    var INITIAL_OFFSET = performance.now(); // <-- This performance does not exists
    return {
        now: function () {
            return performance.now() - INITIAL_OFFSET;
        },
        timeOrigin: INITIAL_TIME,
    };
}
```
The above code are in node_modules > @sentry > utils > dist > misc.js

**Actual result:**

![Screenshot 2020-09-18 at 13 52 16](https://user-images.githubusercontent.com/16567802/93594471-2a769500-f9b6-11ea-828d-823661e898a4.png)

**Expected result:**

I expect the app works fine like yesterday

**Comment by nickdemers** [comment]
same here. Works yesterday et today, error...

**Comment by icastillejogomez** [comment]
@nickdemers try to restore the yarn.lock of yesterday and run `yarn install —-frozen-lockfile` 

this temporally fix works for us. 

@juanma-lora-pepephone

**Comment by jennmueng** [comment]
@icastillejogomez @nickdemers 
This was a mistake as we didn't add a check for RN <0.63 without `performance` being defined. You can fix this for now by downgrading to `1.8.0`

**Comment by icastillejogomez** [comment]
But why in versión 1.4.5 also fails? Thank you for your quickly response

**Comment by jennmueng** [comment]
@icastillejogomez You might need to delete your node_modules and reinstall

**Comment by icastillejogomez** [comment]
versión with the fix?

**Comment by jennmueng** [comment]
Fixed in 1.8.2 https://github.com/getsentry/sentry-react-native/releases/tag/1.8.2

**Comment by icastillejogomez** [comment]
When will be available on npm registry?

**Comment by icastillejogomez** [comment]
Available on npm registry and works as expected. Thank you all!
