### ISSUE TITLE
"error: Permission denied (os error 13)" when using custom build script to set entry file to src/index.tsx

### ISSUE THREAD

**Issue by lukewlms** [getsentry/sentry-react-native#1092]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** "@sentry/react-native": "^1.7.2",

**`react-native` version:** "react-native": "^0.63.2",

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
No issue logged

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({ dsn: SENTRY_DSN });
```

---
**I have following issue:**

I have a non-standard (though very common, for Typescript users) index file location (`src/index.tsx`).

I was originally getting the error EOF while parsing a value at line 1 column 0`, so I've tried to set up a build custom build script to reference this file.  Now I'm getting this error:

```
error: Permission denied (os error 13)
```

In project.pbxproj:
```
sellScript = "export SENTRY_PROPERTIES=sentry.properties\nexport SENTRY_LOG_LEVEL=debug\nexport EXTRA_PACKAGER_ARGS=\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\"\nexport NODE_BINARY=node\n../node_modules/@sentry/cli/bin/sentry-cli react-native xcode sentry-cli-xcode-build.sh";
```

In ios/sentry-cli-xcode-build.sh (custom script - but deleting contents of this file still repros the error):
```
../node_modules/react-native/scripts/react-native-xcode.sh src/index.ios.tsx
```

What could be happening here?  I know that my custom script is getting found, because if I change the name then
sentry reports that the file could not be found.

It also doesn't appear to have anything to do with the script itself because even when I clear out all contents, this error still appears.

Here's the full output:

```
  INFO    2020-09-18 13:01:20.281428 -05:00 Loaded config from /Users/me/.sentryclirc
  DEBUG   2020-09-18 13:01:20.282270 -05:00 sentry-cli version: 1.57.0, platform: "darwin", architecture: "x86_64"
  INFO    2020-09-18 13:01:20.282399 -05:00 sentry-cli was invoked with the following command line: "/Users/me/Projects/mobile2mr/node_modules/@sentry/cli/sentry-cli" "react-native" "xcode" "sentry-cli-xcode-build.sh"
  INFO    2020-09-18 13:01:20.283313 -05:00 Issuing a command for Organization: 2-minute-revolution Project: 2-minute-revolution
  INFO    2020-09-18 13:01:20.283328 -05:00 Using react-native build script at /Users/me/Projects/mobile2mr/ios
  INFO    2020-09-18 13:01:20.283335 -05:00 Parsing Info.plist
  INFO    2020-09-18 13:01:20.307631 -05:00 Parse result from Info.plist: InfoPlist { name: "mobile2mr", bundle_id: "com.twominuterevolution.mobile2mr-ios", version: "2.8.0", build: "1" }
  INFO    2020-09-18 13:01:20.307837 -05:00 Using node interpreter 'node'
error: Permission denied (os error 13)
  DEBUG   2020-09-18 13:01:20.309038 -05:00 client close; no transport to shut down  (from sentry)
  DEBUG   2020-09-18 13:01:20.309058 -05:00 skipping update nagger because session is not attended
```

I think it would be invaluable to have this info ("how to use a custom path to index.js") in the docs because this is quite a common use case - e.g. using `src/index.tsx` or just having `index` be TS instead of JS.

Thanks!

**Comment by marandaneto** [comment]
can you just patch the build steps directly on the Xcode file? usually the project.pbxproj file
