### ISSUE TITLE
[Docs issue] Need guidance on how securely to treat Sentry auth token (should it go in source control?)

### ISSUE THREAD

**Issue by lukewlms** [getsentry/sentry-react-native#1096]
By default, the Sentry auth token is added to source control in multiple ways:

- ./ios/sentry.properties and ./android/sentry.properties
- In our case, added to `fastfile` in the `upload_symbols_to_sentry` step

The docs don't specify if the auth token should be treated more securely than the URL-esque key used in source code (which we put in an .ENV file although it will of course ship in the client).

It doesn't look like the CLI can do anything too destructive - only add, not delete, as far as I can see on a quick skim.  So perhaps it's ok to have this auth token in source control.

But it would be I think valuable to have an explicit instruction both in the setup steps, and at this URL: https://sentry.io/settings/account/api/auth-tokens/  (That page also does not appear to give any guidance on how to treat this auth token.)

That way we'll all know what the best security practice is for these tokens.  

Thanks for taking a look!

**Comment by jennmueng** [comment]
Hmm I agree, the auth token should not be included in source-control. Thanks for the suggestion and I will get on this.

**Comment by marandaneto** [comment]
we'll discuss that internally if we have to document the optimal approach for this but I'd say this is App's responsibility to secure its own token, this is sensitive information and should be treated as such, not checking into source control, etc.
an idea is to remove the token from files and set as `SENTRY_AUTH_TOKEN` env. var. when running releases

**Comment by darrylyoung** [comment]
In case this is useful for anyone else coming across the issue, this has since been discussed here as well — https://github.com/getsentry/sentry-react-native/discussions/2618

**Comment by krystofwoldrich** [comment]
Both sentry/wizard and docs https://docs.sentry.io/platforms/react-native/manual-setup/expo/#add-the-sentry-expo-plugin now specify that SENTRY_AUTH_TOKEN should not be added to source control.
