### ISSUE TITLE
Not recording events in Issues

### ISSUE THREAD

**Issue by daheeahn** [getsentry/sentry-react-native#1097]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2) <---- not install because it wasn't in [docs](https://docs.sentry.io/platforms/react-native/)

**SDK version:** 1.8.2

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
import * as Sentry from '@sentry/react-native';
Sentry.init({
  dsn: 'https://aba2317845374603a2a6de31607c3d29@o441761.ingest.sentry.io/5412441',
});
```

At first, I set it according to the docs, and the error was well seen in the issue tab (setting was completed about 3 weeks ago), but the error was not logged from two weeks ago. I haven't changed anything. It occured both Platfrom Android, iOS.
What's the matter?

**Comment by jennmueng** [comment]
@daheeahn What kind of error is it, and how was it thrown? Is the correct project being selected on the issue tab?

**Comment by jennmueng** [comment]
Closing this on the basis of being more than a year old with no updates. If the issue still persists, feel free to reopen.
