### ISSUE TITLE
Segfault crashes not ignored even though added to ignore list. 

### ISSUE THREAD

**Issue by patelnets** [getsentry/sentry-react-native#1107]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^1.7.1

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
https://sentry.io/share/issue/d1ee109c3830406f93939af227f73891/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  ignoreErrors: [
        // https://github.com/getsentry/sentry-react-native/issues/1049
        /^Network request failed/,

        // https://github.com/facebook/react-native/issues/25494
        /^Segfault/,
      ],
   enableAutoSessionTracking: true,
});
```

**I have following issue:**

I'm seeing these crashes logged by sentry. They seem to be native crashes and i believe there is not much I can do to fix those. My problem is that I can't seem to prevent them getting tracked by sentry even after adding Segfault to ignoreErrors list. Is it not possible to ignore these native errors? 
![image](https://user-images.githubusercontent.com/34072639/95067244-6ec69c80-06fb-11eb-8632-0de01ab60edb.png)

**Steps to reproduce:**
I don't know how to reproduce it as the sentry logging doesn't give enough information. 

**Actual result:**
Segfault crashes are logged in sentry

**Expected result:**
Segfault crashes are not logged in sentry

**Comment by jennmueng** [comment]
@patelnets So we currently don't support passing down `ignoreErrors` to the Android SDK underneath, currently it only applies to JS errors. I've tagged this as a requested feature.

**Comment by patelnets** [comment]
Ah okay I see. Thanks for flagging it as a feature request. Would there be any other way to achieve this in the meantime?

**Comment by jennmueng** [comment]
@patelnets You would have to initialize the SDK separately, while mirroring this call that our React Native SDK does: https://github.com/getsentry/sentry-react-native/blob/fde2a751551a4699cdcac76f95ae12ce7fd8d1db/android/src/main/java/io/sentry/RNSentryModule.java#L74

Personally, I don't think it's worth the hassle to ignore these segfaults. In the meantime, you can also ignore/mute the errors on your Sentry dashboard.

**Comment by patelnets** [comment]
Okay sure. Thanks for the help!

**Comment by marandaneto** [comment]
> @patelnets You would have to initialize the SDK separately, while mirroring this call that our React Native SDK does:
> 
> https://github.com/getsentry/sentry-react-native/blob/fde2a751551a4699cdcac76f95ae12ce7fd8d1db/android/src/main/java/io/sentry/RNSentryModule.java#L74
> 
> Personally, I don't think it's worth the hassle to ignore these segfaults. In the meantime, you can also ignore/mute the errors on your Sentry dashboard.

docs on how to init the native SDKs manually https://docs.sentry.io/platforms/react-native/manual-setup/native-init/
then you set a `beforeSend` filtering your events if its the case
