### ISSUE TITLE
Pod Install: Error installing Sentry

### ISSUE THREAD

**Issue by Billmike** [getsentry/sentry-react-native#1129]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

[Description]
- I am trying to install Sentry with Cocoapods in a React Native project. I have it installed and configured using the sentry-wizard. The configuration was successful. On running `pod install` in the iOS directory, I get the error below:
**Steps to reproduce:**
- Install sentry react native
- Configure the project with the wizard
- Run `pod install`

**Actual result:**
```
[!] Error installing Sentry
[!] /usr/bin/git clone https://github.com/getsentry/sentry-cocoa.git /var/folders/55/hk1l5pn11p76d9_80q8r02080000gn/T/d20201013-63636-tqjy6s --template= --single-branch --depth 1 --branch 5.2.2

Cloning into '/var/folders/55/hk1l5pn11p76d9_80q8r02080000gn/T/d20201013-63636-tqjy6s'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Expected result:**

Success

**Comment by jennmueng** [comment]
Looks like your Github access is possibly set up wrong? `sentry-cocoa` is a public repository to clone, this doesn't look like an issue with our SDK. You can maybe see if this helps: https://github.com/jakubroztocil/cloudtunes/issues/46, or you can try manually cloning the `sentry-cocoa` repo and see if there are any issues there.

I will be closing this for now.
