### ISSUE TITLE
how to do user feedback on a native crush

### ISSUE THREAD

**Issue by sammysium** [getsentry/sentry-react-native#1138]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x ]  Linux

**Platform:**
- [ ]  iOS
- [ x]  Android

**SDK:**
- [ x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.63.1

**Are you using Expo?**
- [ ]  Yes
- [ x]  No

**Are you using sentry.io or on-premise?**
- [ x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
      enableAutoSessionTracking: true,
      sessionTrackingIntervalMillis: 10000,
      environment: Config.environment,
      beforeSend(event, hint) {
        // Check if it is an exception, and if so, show the report dialog
       // is the event a death screen crush or not?
        return event;
      },
});
---
**I have following issue:**

when a native JAVA crush happens (picture shown), it is logged in sentry alright. But I want to enable collecting feedback to the event. not sure if am doing anything wrong but for a test I did:

![errrrrr nl](https://user-images.githubusercontent.com/46919720/96621944-962b8500-1309-11eb-997b-d52e83a2fe75.png)


```
      beforeSend(event, hint) {
        Alert.alert('title', event.event_id);
        return event;
      },
```
but the alert never shows up. It does alert for handled exceptions (from trycatch). Am I missing something?

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

[Actual result]

**Expected result:**

[Expected result]

**Comment by jennmueng** [comment]
@sammysium Native errors don't get sent through `beforeSend` in the javascript code. You would need to use the Android SDK's `beforeSend` to handle this functionality.

If you don't want to code the popup in java, you would need to call across the native bridge into javascript code, you can read about how to achieve this on the React Native docs: https://reactnative.dev/docs/native-modules-android.html#sending-events-to-javascript.

If you do choose to supply your own `beforeSend` in the java code, you will have to replicate the one we currently have to ensure everything is working: https://github.com/getsentry/sentry-react-native/blob/ebaf73e1f42e5a914c5bfc9cacb26b72c644c7dc/android/src/main/java/io/sentry/RNSentryModule.java#L113-L147
