### ISSUE TITLE
"../node_modules/@sentry/cli/bin/sentry-cli: No such file or directory" and "An organization slug is required (provide with --org)"

### ISSUE THREAD

**Issue by neildevas** [getsentry/sentry-react-native#1140]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have following issue:**

I cannot build my iOS app after following the react-native installation instructions outlined [here](https://docs.sentry.io/platforms/react-native/)

First I receive this error: 
```
line 8: ../node_modules/@sentry/cli/bin/sentry-cli: No such file or directory
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/neilde/Library/Developer/Xcode/DerivedData/Scouts-fcmgxnokvpsmxedqvlqzqdwluxyn/Build/Intermediates.noindex/Scouts.build/Debug-iphonesimulator/Scouts.build/Script-00DD1BFF1BD5951E006B06BC.sh
```

The first thing I did was update part of my React Native Bundle script from 
```
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ./node_modules/react-native/scripts/react-native-xcode.sh
```
to 
```
export NODE_BINARY=node
./node_modules/@sentry/cli/bin/sentry-cli react-native xcode ./node_modules/react-native/scripts/react-native-xcode.sh
```
Which solved the first error. But then I receive the following error: 
```
    /bin/sh -c /Users/neilde/Library/Developer/Xcode/DerivedData/Scouts-fcmgxnokvpsmxedqvlqzqdwluxyn/Build/Intermediates.noindex/Scouts.build/Debug-iphonesimulator/Scouts.build/Script-00DD1BFF1BD5951E006B06BC.sh
error: An organization slug is required (provide with --org)
```

**Steps to reproduce:**
- Follow the [instructions](https://docs.sentry.io/platforms/react-native/) to install with an existing rn app using yarn
- run ```react-native run-ios```

**Actual result:**

First 
```
line 8: ../node_modules/@sentry/cli/bin/sentry-cli: No such file or directory
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/neilde/Library/Developer/Xcode/DerivedData/Scouts-fcmgxnokvpsmxedqvlqzqdwluxyn/Build/Intermediates.noindex/Scouts.build/Debug-iphonesimulator/Scouts.build/Script-00DD1BFF1BD5951E006B06BC.sh
```

Then 
```    
/bin/sh -c /Users/neilde/Library/Developer/Xcode/DerivedData/Scouts-fcmgxnokvpsmxedqvlqzqdwluxyn/Build/Intermediates.noindex/Scouts.build/Debug-iphonesimulator/Scouts.build/Script-00DD1BFF1BD5951E006B06BC.sh
error: An organization slug is required (provide with --org)
```

**Expected result:**

iOS builds successfully

**Comment by bfricka** [comment]
Dude, you just closed this without saying the issue? Come on man.
