### ISSUE TITLE
Sentry tries to upload sourcemaps for custom targets when bundle is disabled

### ISSUE THREAD

**Issue by asmeikal** [getsentry/sentry-react-native#1142]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Not related to any particular issue.

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

I'm working on a react native project with different debug variants:
```
project.ext.react = [
        bundleInCustom      : false,
        devDisabledInCustom : false,
]
```
When I assemble the application with the `Custom` variant, the `SentryUpload` step runs and fails, even though the react native bundle step is not enabled.
There is a solution described [in this issue](https://github.com/getsentry/sentry-react-native/issues/525), but it does not scale well.

**Steps to reproduce:**
- create a variant with `bundle` disabled, as described above
- assemble the variant (or install on a device) with `./gradlew assembleVariant`

**Actual result:**

The command fails with this error:
```
> Task :app:bundleCustomJsAndAssets_SentryUpload_18 FAILED
Processing react-native sourcemaps for Sentry upload.
error: No such file or directory (os error 2)
```

**Expected result:**

The command should not fail: JS code was not bundled, so Sentry shouldn't try to upload source maps.

I'm going to open a PR with a possible fix.

**Comment by asmeikal** [comment]
I opened [this PR](https://github.com/getsentry/sentry-react-native/pull/1143) with a possible fix.

**Comment by jennmueng** [comment]
Closed as the PR was merged.
