### ISSUE TITLE
Breadcrumbs are missing on app restart

### ISSUE THREAD

**Issue by ambatisuman** [getsentry/sentry-react-native#1155]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.3

**`react-native` version:** 0.57.8

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
 dsn: SENTRY_DSN,
    environment,
    integrations: [
      new Sentry.BrowserIntegrations.Breadcrumbs({
        console: false,
        sentry: false,
        dom: false,
      }),
    ],
});
```
---
**I have following issue:**

We have migrated from `react-native-sentry` version 0.43.2 from 1.3.3 a few weeks ago and noticed that breadcrumbs from before a forced app restart are not attached to an event.
For every app force restart, we send a sentry event that allows the user to provide additional feedback.

**Expected result:**
Version 0.43.2: With this behaviour, the sentry event has been reported and it has all the breadcrumbs until the app restart attached. If the user adds any feedback, it is attached to the same event.

**Actual result:**
Version 1.3.x: The sentry event has been reported and it only has new breadcrumbs since the app restart attached. If the user adds any feedback, it is also attached to the same event.
So, all breadcrumbs from before the app force restart are lost. When we log the event from the `RNSentryEventEmitter` it has a different `event_id` and all expected breadcrumbs. But we see a different event reported to sentry.io with without these expected breadcrumbs.
When we try to get the `lastEventId` from hub: `Sentry.getCurrentHub().lastEventId();`it gives us the event which is posted to the sentry.io. 
The question is, what happened to the event from `RNSentryEventEmitter` which has breadcrumbs?
Why don't we have all expected breadcrumbs together with the event which has been sent to the sentry.io?
Is this the expected behaviour after the changes introduced with version 1.0.0?

**Comment by jennmueng** [comment]
`RNSentryEventEmitter` was removed in the `1.0.0` major bump, if it still exists, you should update the iOS part of the SDK by calling `pod install` and the issue should be fixed.

Also, you actually don't need to pass `Sentry.BrowserIntegrations.Breadcrumbs` to `Sentry.init`, breadcrumbs are already stored by default.

**Comment by erikmueller** [comment]
Hey @jennmueng , thanks for the answer and sorry for the delay.
We have now updated to version 2.1.0 but are not too clear on how we could re-implement our old behaviour:

Once the app crashed we hooked into the `Sentry.setEventSentSuccessfully` to get the `eventId` and attach feedback to it. As this is gone now we tried to make use of `beforeSend` to grab the eventId and call the feedback API with it (attaching some user feedback).
However it seems that `beforeSend` is not called when a native crash or a JS exception occurred (but the event is sent to sentry)- we just don't have any possibility to hook into that.

Do you have any advice how we can solve our use case?

**Comment by jennmueng** [comment]
@erikmueller A crashed app would cache the event and then send it when the app opens and wouldn't pass through `beforeSend` a second time. Hmm currently there isn't a way to do so, as we just send the cached event right away and don't pass it through anything. If you would like that as a feature, you can make a separate issue and write the needed use cases.

Also, I'll be closing the issue as the original problem seemed solved. Let us know if it still occurs.

**Comment by erikmueller** [comment]
> A crashed app would cache the event and then send it when the app opens and wouldn't pass through beforeSend a second time

What do you mean by "a second time"? As far as I understood when the crash happens there's no event sent. So is there a reason why beforeSend is not invoked when a cached event is sent. It feels inconsistent. It should not matter if it's cached or not as long as it is sent.

**Comment by jennmueng** [comment]
@erikmueller Let me clarify that beforeSend is invoked the first time when the event happens, when we cache it it's considered "sent" in the SDK's perspective, so it's not passed through `beforeSend` when the cached event is being picked up.

**Comment by erikmueller** [comment]
@jennmueng I agree the naming is a bit misleading so thank you for clarifying. 
Indeed a user feedback feature would be solving all of that :)
However a callback for sending (to get the actual event id for further use with the API) would also help very much.

Again thank you for explaining. I know there's an issue somewhere around the native feedback feature and depending on how we proceed further I might open a feature request for said callback 👍
