### ISSUE TITLE
Sourcemaps are not resolved in the errors

### ISSUE THREAD

**Issue by varungupta85** [getsentry/sentry-react-native#1169]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/acintyo/issues/2001332228/?project=98211&query=firstRelease%3A%223.9.1+%284%29%22

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn:
      'https://abc:xyz@sentry.io/98211'
  })

  Sentry.setTags({
    os: DeviceInfo.getSystemName(),
    osVersion: DeviceInfo.getSystemVersion(),
    locale: I18n.currentLocale(),
    device:
      store.getState().userInfo.deviceManufacturer + '-' + DeviceInfo.getModel()
  })

  // const bundleId =
  //   Platform.OS === 'android' ? 'com.galarmapp' : 'com.acintyo.galarm'
  // const release = bundleId + '-' + GlobalConfig.release
  const release = `${GlobalConfig.release} (${DeviceInfo.getBuildNumber()})`
  console.tron.log('Current release', release)
  Sentry.setRelease(release)
  Sentry.setDist(DeviceInfo.getBuildNumber())
```

---
**I have following issue:**

The source maps are no longer resolved in the errors. They used to work fine. For example, check the following error: https://sentry.io/organizations/acintyo/issues/2001743680/?project=98211&query=firstRelease%3Acom.galarmapp-3.4.0. The source maps are resolved fine in this one but they are no longer resolved in my recent releases.

I used to set the `release` as `<bundle-id>-<release-number>` but then I saw that in the recent releases, the source maps were tagged with release `<release-number> (<distribution-number>)` on the Sentry console. So, I changed the call to `Sentry.setRelease` accordingly but that didn't help either.

**Steps to reproduce:**
1. Log an error on Sentry
2. Check that the sourcemaps are not resolved the errors are shown in the bundled js file without any reference to the actual code

**Actual result:**

Actual place of error in the code not seen

**Expected result:**

Actual place of error in the code should be seen

**Comment by jennmueng** [comment]
Hi @varungupta85 does an error show above the event on the dashboard saying "Source Maps Not Found"? Can you also pass the event json? Thanks!

**Comment by varungupta85** [comment]
hi @jennmueng, yes there is an error on the console saying "Source Maps Not Found". For e.g., check this event: https://sentry.io/organizations/acintyo/issues/2013423438/?project=98211&query=is%3Aunresolved+release%3Acom.galarmapp-3.10.0&statsPeriod=14d.

What do you mean by the event json? Please let me know where I can find it and I will share that information with you.

**Comment by varungupta85** [comment]
I see the following in the gradle output

```
> Task :app:bundleReleaseJsAndAssets_SentryUpload_7340769
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release com.galarmapp@3.10.0+7340769 distribution 7340769
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete
```

Does it mean that I need to set the `RELEASE` to `com.galarmapp@3.10.0+7340769` while configuring Sentry in the app?

**Comment by jennmueng** [comment]
@varungupta85 You can find the event json by clicking on "JSON" here:
<img width="372" alt="Screen Shot 2020-11-10 at 8 57 06 PM" src="https://user-images.githubusercontent.com/30991498/98683191-53ece500-2397-11eb-8c40-0bdb58c20551.png">
But yes, if you have the error then it means that the source maps aren't getting correctly mapped. You need to make sure the `release` and `dist` set on the source maps exactly matches the values on the errors.

**Comment by varungupta85** [comment]
@jennmueng Thanks for your response. Setting the release to the updated value helped.
