### ISSUE TITLE
Github Actions bundle step fails

### ISSUE THREAD

**Issue by 2j2e** [getsentry/sentry-react-native#1170]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.0

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**I have following issue:**

I have added Sentry support to the project according to the manual.
Changed the "Bundle React Native code and images" step to :
```
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
  ../node_modules/react-native/scripts/react-native-xcode.sh
```
and the build stopped to work on Github Actions right after this (works fine on my local machine)
I'm using Fastlane and here is a part of log with an issue:

```
▸ Compiling LaunchScreen.xib
▸ Processing Info.plist
▸ Running script 'Bundle React Native code and images'
▸ Generating '*****.app.dSYM'
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/*****-fmfqpyfxempgprdhpdggdtgweezz/Build/Intermediates.noindex/ArchiveIntermediates/****/IntermediateBuildFilesPath/*****.build/Release-iphoneos/*****.build/Script-44994D65255075CC0000B470.sh
Exit status: 65
```

```
Command PhaseScriptExecution failed with a nonzero exit code

▸ GenerateDSYMFile /Users/runner/Library/Developer/Xcode/DerivedData/*****-fmfqpyfxempgprdhpdggdtgweezz/Build/Intermediates.noindex/ArchiveIntermediates/*****/BuildProductsPath/Release-iphoneos/*****.app.dSYM /Users/runner/Library/Developer/Xcode/DerivedData/*****-fmfqpyfxempgprdhpdggdtgweezz/Build/Intermediates.noindex/ArchiveIntermediates/*****/InstallationBuildProductsLocation/Applications/*****.app/***** (in target '*****' from project '*****')

▸     cd /Users/runner/work/mobile/mobile/ios15503
▸     /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/runner/Library/Developer/Xcode/DerivedData/*****-fmfqpyfxempgprdhpdggdtgweezz/Build/Intermediates.noindex/ArchiveIntermediates/*****/InstallationBuildProductsLocation/Applications/*****.app/***** -o /Users/runner/Library/Developer/Xcode/DerivedData/*****-fmfqpyfxempgprdhpdggdtgweezz/Build/Intermediates.noindex/ArchiveIntermediates/*****/BuildProductsPath/Release-iphoneos/*****.app.dSYM
```

I searched for all possible solutions but can't find anything and also can't get the source of the issue.

**Comment by jennmueng** [comment]
Hmm this is interesting as it still works fine on our Github Actions. Is that the whole error message that it outputs? Usually there is more as that doesn't really give us any info.

**Comment by 2j2e** [comment]
This is the whole error message, which makes hard to identify the real issue.
After playing some time I found that the real issue (at least for now) is missed bundle file. For some reason Github Action environment can't generate it (which works locally). Potentially the issue is with Node path. But it's hard to debug as there is no way to connect to the virtual machine and play live. I will continue my research and back with results.

**Comment by b08Walls** [comment]
@2j2e how is it going ? did you find a solution ?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
