### ISSUE TITLE
it stopped to building () error: API request failed   caused by: [6] Couldn't resolve host name

### ISSUE THREAD

**Issue by felipemillhouse** [getsentry/sentry-react-native#1187]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.0, also happened at 1.3.9

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/1837884'
  // other options
 ).install();
```

---
**I have following issue:**

Well... we just build it 4 hours ago and it was working fine, so right now we tried to build again and we are getting this issue, no commit on project after last build.
We were using 1.3.9 sentry version, so we tried to upgrade it to 2.0.0 to try to fix it, but no luck with that.

**Steps to reproduce:**
- Just try to build to Android or iOS

**Actual result:**

```> Task :app:bundleReleaseJsAndAssets_SentryUpload_1055145 FAILED
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: API request failed
  caused by: [6] Couldn't resolve host name

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:bundleReleaseJsAndAssets_SentryUpload_6569
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: API request failed
  caused by: [6] Couldn't resolve host name

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Expected result:**

build it successfully

**Comment by felipemillhouse** [comment]
Nevermind... probably it was in our side, it's working in another computer, please, close it

**Comment by bencagri** [comment]
I also have the same problem. 


The debug
```
> Adding source map references
  DEBUG   2022-03-05 13:59:18.604882 +02:00 request POST https://sentry.io/api/0/projects/***/***/releases/
  DEBUG   2022-03-05 13:59:18.604944 +02:00 using token authentication
  DEBUG   2022-03-05 13:59:18.604965 +02:00 json body: {"version":"com.***@1.1.0+58","projects":["***"]}
  DEBUG   2022-03-05 13:59:18.604981 +02:00 retry number 0, max retries: 0
error: API request failed
  caused by: [6] Couldn't resolve host name (Could not resolve host: sentry.io)
  DEBUG   2022-03-05 13:59:18.608892 +02:00 skipping update nagger because session is not attended

FAILURE: Build failed with an exception.

```

when I run `sentry-cli info`  I see a valid response. It was working but suddenly started giving this error. 


 @sentry/react-native to 3.3.0
 react-native: 0.65.1

**Comment by thoth-seshat** [comment]
I'm getting the same issue now

**Comment by krystofwoldrich** [comment]
@thoth-seshat Can you use `export SENTRY_LOG_LEVEL=debug` to get more detailed error logs?
