### ISSUE TITLE
How are errors linked to a release?

### ISSUE THREAD

**Issue by vtoupet** [getsentry/sentry-react-native#1197]
**OS:**
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

**Platform:**
- [x ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [x]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/vincent-toupet/issues/1972979131/?project=5410474&query=is%3Aunresolved+release%3Acom.vtoupet.smartmixin%401.0.13%2B87

**Configuration:**

I am releasing version for both iOS and Android and I think some of my errors are not using the correct source map.

I am wondering how I can make sure my Android errors are not linked to the equivalent iOS release ? Version are equivalent and distribution also.

And if it cannot be mistaken, why some of my JS errors are not properly decoding thanks to the source maps? (see https://sentry.io/organizations/vincent-toupet/issues/1972979131/?project=5410474&query=is%3Aunresolved+release%3Acom.vtoupet.smartmixin%401.0.13%2B87 for example).

Thanks,
Vincent

**Comment by jennmueng** [comment]
@vtoupet Usually android source maps would be named something like `index.android.bundle` while iOS source maps would be something like `main.jsbundle`. If these files are named differently (both in the sourcemap upload and in how your bundle is named in your app build) then they shouldn't be linked to each other.

**Comment by vtoupet** [comment]
Ok thanks.
