### ISSUE TITLE
captureException return invalid event id

### ISSUE THREAD

**Issue by aminerol** [getsentry/sentry-react-native#1200]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.0

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No link.

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  enableAutoSessionTracking: true,
  dsn: config.sentry.dsn,
  ignoreErrors: [
       "remote notifications are not supported in the simulator",
 ],
 environment: config.env,
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

`captureException` returns a wrong event id and no issue been reported to sentry dashboard, also tried to attach that event to a feedback through axio but same result, no feedback been reported

**Steps to reproduce:**
- here is the function am using for reporting a feedback

```
const eventId = captureException(error, {level: Severity.Error})
        const params = {
            event_id: eventId,
            name: currentUser?.name,
            email: currentUser?.email,
            comments: message,
            logger: Severity.Info,
        };

        return Axios.post(config.sentry.feedbackEndpoint, params, {
            headers: {
                "Content-Type": "application/json",
                Authorization: `DSN ${config.sentry.dsn}`,
            },
        });
```

**Actual result:**

a wrong event id and no feedback nor exception been reported

**Expected result:**

a valid event id, hence a new feedback reported

**A working workaround**

downgrading to v1.8.2 solve this issue and captureException behave as it should

**Comment by jennmueng** [comment]
Hmm, for clarification, by wrong event id you mean that the event isn't getting sent and doesn't exist on the Sentry Dashboard right? Or how is it wrong?

**Comment by aminerol** [comment]
Yes, indeed it returns an event id but that event doesn't exist on the sentry dashboard, it's more like an invalid event id

**Comment by marandaneto** [comment]
@aminerol does that still happen? I can't reproduce that an event does not get sent using the latest Sentry RN SDK

**Comment by aminerol** [comment]
@marandaneto nope, it works just fine in latest Sentry RN
