### ISSUE TITLE
No such file or directory when uploading sourcemaps

### ISSUE THREAD

**Issue by samaneh-kamalian** [getsentry/sentry-react-native#1201]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ * ]  Linux

**Platform:**
- [ ]  iOS
- [ * ]  Android

**SDK:**
- [ * ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [* ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have following issue:**

Hi.
I want to create apk with different logo(for different customers) so I add my customer logo to this location:
`android/app/src`
so in this location I have three folder: `debug, main, mycustomerFolder`.
and in `mycustomerFolder` folder I have `res` folder that contain my customer logos.
and I add my customer to build.gradle:
```
    buildTypes {

        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            //signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }

        myCustomer{
            
            matchingFallbacks = ['release']
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }

    }
```
Now I want to create apk with this command: `./gradlew assemble` 
But I get this Error:
```
> Task :app:bundleMyCustomerJsAndAssets_SentryUpload_3145738 FAILED
error:Processing react-native sourcemaps for Sentry upload.
 No such file or directory (os error 2)
```

**Expected result:**

like when I disable sentry, apks for release and mycustomer create correctly.

**Comment by williamgurzoni** [comment]
Same problem here.

**Comment by tamago3keran** [comment]
Same problem.

**Comment by renaudmathieu** [comment]
You need to add a `sentry.properties` file. This file is used by Sentry to upload the `mapping.txt` into the correct Sentry project.

**Comment by marandaneto** [comment]
> You need to add a `sentry.properties` file. This file is used by Sentry to upload the `mapping.txt` into the correct Sentry project.

@samaneh-kamalian does that solve the issue?
