### ISSUE TITLE
circular structure error occurred

### ISSUE THREAD

**Issue by seosea** [getsentry/sentry-react-native#1202]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

no link

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: SENTRY_URL,
      enableAutoSessionTracking: true,
      sessionTrackingIntervalMillis: 1000
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

hello, 
I applied sentry to the project and there was no problem with implementation.
However, when I press firebase notification, the following error occurs in app initialization.

![Screenshot_20201118-211123_Connecting](https://user-images.githubusercontent.com/13011923/99529213-c9cdfd80-29e2-11eb-8cb8-3668cde37122.jpg)

**Steps to reproduce:**

- Initialize `firebase` first and call `sentry.init()`

**Actual result:**

circular structure error occurred

**Expected result:**

rending to the screen related to notification

**Comment by jennmueng** [comment]
Oh, looks like you're using Sentry with Redux right? There is a non-serializable instance of `Notification` stored on the redux state. You will need to serialize it before setting it on the state. The documentation is here: https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/redux/#redux-enhancer-options

Closing this for now, let me know if there is anything.

**Comment by seosea** [comment]
What method should I look for in the link you sent me for a non-serializable instance of Notification?
