### ISSUE TITLE
User id missing on iOS native crashes

### ISSUE THREAD

**Issue by ioveracker** [getsentry/sentry-react-native#1204]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.1

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Private link](https://sentry.io/organizations/cbtnuggets/issues/2042573164/?project=5270634&query=is%3Aunresolved) -- public link doesn't show user info?

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: REDACTED, // If this is not a security risk to share in a PR, let me know and I'll edit this
    enableAutoSessionTracking: true,
    enabled: !__DEV__,
});
```
---
**I have following issue:**

The user id is not logged for iOS native crashes, but is present on JS errors and Android native crashes.

**Steps to reproduce:**
- After logging in, setting the user id like this: `Sentry.setUser({ id: memberId });`
- Trigger an iOS native crash via `Sentry.nativeCrash()`

**Actual result:**

The user id is a GUID on iOS native crashes, but is correctly set as the `memberId` from above on JS errors and Android native crashes.

**Expected result:**

The user id on iOS native crashes should match the user id on JS errors and Android native crashes.

**Comment by jennmueng** [comment]
Hmm interesting, just tested and setting the user id on iOS is working fine on my end. Can you try updating to the latest version `2.0.2` with a `pod install` which will get you `sentry-cocoa` version `6.0.9` and see if the issue persists?

**Comment by jennmueng** [comment]
Closing this for now as it looks like it should be solved, let me know if the issue still persists.
