### ISSUE TITLE
Sentry.captureException doesn't seem to send my context

### ISSUE THREAD

**Issue by lucasriondel** [getsentry/sentry-react-native#1213]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.2

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/lonestone/issues/2050084236/?project=5525775&query=is%3Aunresolved

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

While capturing an exception, I am setting extra context to have additionnal data to have a better analysis on my error. But I do not know why they do not appear on sentry.io

**Steps to reproduce:**

```
Sentry.captureException(e, {
    tags: {
        screen: Routes.AccountProCreationForm,
        step: step,
        email: email,
    },
    contexts: {
        formContext: {
            step1: {
            name,
            surname,
            phone,
            email,
            password,
            address,
            zipcode,
            city,
            },
            step2: {
            description,
            googleUrl,
            profilePicture,
            diplomas,
            insuranceNumber,
            },
        },
    },
});
```
There's a `console.log` right before the `captureException` call logging the content of `formContext`, and everything is right, but there's anything on Sentry.io's console. Tags are well sent though.

**Actual result:**

![image](https://user-images.githubusercontent.com/7773454/99996689-60703500-2dbc-11eb-8858-c73f368b03e0.png)

**Expected result:**

I was expecting to see my values :<

**Comment by jennmueng** [comment]
Hmm can you please do
```js
const captureContext = {
    tags: {
        screen: Routes.AccountProCreationForm,
        step: step,
        email: email,
    },
    contexts: {
        formContext: {
            step1: {
            name,
            surname,
            phone,
            email,
            password,
            address,
            zipcode,
            city,
            },
            step2: {
            description,
            googleUrl,
            profilePicture,
            diplomas,
            insuranceNumber,
            },
        },
    },
}

const eventId = Sentry.captureException(e, captureContext)
console.log(eventId, captureContext)
```
and paste the logs of the eventId and captureContext, thanks. And please replace any sensitive data if there are any.

**Comment by jennmueng** [comment]
I will be closing this for now as there seems to be no updates. Please let me know if the issue still persists.
