### ISSUE TITLE
Manage source maps for multiple appps

### ISSUE THREAD

**Issue by indapublic** [getsentry/sentry-react-native#1215]
Hi there. 
I have several RN apps with single codebase (just app name and skins are changed during build and publish). 
I see that source maps are uploaded on each Xcode build. But on Sentry web I see a warning about not uploaded source maps and messy callstack. 
I think it caused by single Sentry instance for multiple apps (source map is overwritten by last build). Am I correct? If yes - my question is about: is it possible to manage multiple source maps for single Sentry account?
Thank you.

**Comment by indapublic** [comment]
![image](https://user-images.githubusercontent.com/856260/100229258-1469ef80-2f78-11eb-81fc-600c02de764b.png)

![image](https://user-images.githubusercontent.com/856260/100229339-319ebe00-2f78-11eb-8314-bde03e54528e.png)

![image](https://user-images.githubusercontent.com/856260/100229442-572bc780-2f78-11eb-81de-de575163b704.png)

**Comment by jennmueng** [comment]
Are you using the same project for multiple apps? You should split the apps into their own separate projects on Sentry each with their own DSN. If they are in separate projects then the source maps should not conflict with one-another.

**Comment by indapublic** [comment]
Same project but with different bundle ids. Sentry calls `release` this variable.

**Comment by indapublic** [comment]
Ok. Just build release, source maps uploaded. So source maps should not conflict, correct?
Throw exception, but Sentry shows me `Source code was not found`


sentry.javascript.react-native@1.9.0

**Comment by jennmueng** [comment]
@indapublic Can I have the link to the issue on Sentry Dashboard?

**Comment by indapublic** [comment]
@jennmueng https://sentry.io/organizations/macroactiveio/issues/2056813181/

**Comment by indapublic** [comment]
Created new project, still "Source code was not found" 
https://sentry.io/organizations/macroactiveio/issues/2056893452/

**Comment by jennmueng** [comment]
@indapublic Sorry for the late reply, I just got the chance to give this a look again.

Your stack frames seem to not have the `app:///` prefix that the SDK should be appending on, for example in one of the issues you sent, the frames start with `/private/var/containers/Bundle/Application/`. The filename should be truncated to just the last part, along with `app:///` being prefixed by this default integration in the SDK:
https://github.com/getsentry/sentry-react-native/blob/75e637e009610b1586eb45c4a368ce6cc1f0e07a/src/js/sdk.ts#L57-L80

Are you using `RewriteFrames` anywhere, or overwriting this?

**Comment by indapublic** [comment]
Hi @jennmueng Thanks for your investigation

> Are you using RewriteFrames anywhere, or overwriting this?

Absolutely not 🤔

**Comment by jennmueng** [comment]
@indapublic Can you show the code block for `Sentry.init`, along with passing `debug: true` to it, and paste the JS logs when the app initializes?

**Comment by indapublic** [comment]
```
Sentry.init({
	dsn: __DEV__ ? Env.DEV_SENTRY_ENDPOINT : Env.SENTRY_ENDPOINT,
	environment: "production",
	loglevel: LogLevel.Debug,
	attachStacktrace: true,
	debug: true,
})
```

```
[Sat Dec 05 2020 11:31:31.334]  BUNDLE  ./index.js 

[Sat Dec 05 2020 11:31:51.800]  WARN     Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/whatwg-fetch/dist/fetch.umd.js -> node_modules/react-native/Libraries/Network/fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Sat Dec 05 2020 11:31:51.840]  LOG      Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
[Sat Dec 05 2020 11:31:51.850]  LOG      Sentry Logger [Log]: Integration installed: Release
[Sat Dec 05 2020 11:31:51.850]  LOG      Sentry Logger [Log]: Integration installed: InboundFilters
[Sat Dec 05 2020 11:31:51.860]  LOG      Sentry Logger [Log]: Integration installed: FunctionToString
[Sat Dec 05 2020 11:31:51.870]  LOG      Sentry Logger [Log]: Integration installed: Breadcrumbs
[Sat Dec 05 2020 11:31:51.870]  LOG      Sentry Logger [Log]: Integration installed: LinkedErrors
[Sat Dec 05 2020 11:31:51.880]  LOG      Sentry Logger [Log]: Integration installed: UserAgent
[Sat Dec 05 2020 11:31:51.890]  LOG      Sentry Logger [Log]: Integration installed: DebugSymbolicator
[Sat Dec 05 2020 11:31:51.890]  LOG      Sentry Logger [Log]: Integration installed: RewriteFrames
[Sat Dec 05 2020 11:31:51.900]  LOG      Sentry Logger [Log]: Integration installed: DeviceContext
[Sat Dec 05 2020 11:31:51.910]  LOG      Running "myapp" with {"rootTag":1,"initialProps":{}}
```

**Comment by indapublic** [comment]
Hi @jennmueng Do you have any updates for me?

**Comment by indapublic** [comment]
Seems not resolved

**Comment by marandaneto** [comment]
the linked issues don't exist anymore, @indapublic have you tried the latest RN version? it works for me ootb

question, since you have "multiple apps", does it work when creating a new project and compiling and uploading source maps for the very first App? (avoiding the overwriting problem)

**Comment by indapublic** [comment]
@marandaneto I don't have latest RN in my production products so it will be long test. Give me some time and I will try to check

**Comment by marandaneto** [comment]
@indapublic any news?

**Comment by indapublic** [comment]
@marandaneto Sorry, not reached it yet. Give me a week please, I'll try to reproduce

**Comment by indapublic** [comment]
Hi, sorry for late.

Just created two new apps with RN 0.66.3 and @sentry/react-native 3.2.3

Same apps, different `CFBundleDisplayName` and `PRODUCT_BUNDLE_IDENTIFIER`

App just crashed on button pressing with `Sentry.nativeCrash();`

Sentry is enabled via manual

```
Sentry.init({
	dsn: "https://de42747da2aa4ef7bce48588aeb9e30c@o140491.ingest.sentry.io/6085670",
	// Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
	// We recommend adjusting this value in production.
	tracesSampleRate: 1.0,
});
```

No any issues from app 1 (which one is published at first) and issues from app 2 (which is published after app 1).
Source maps case will check tomorrow.

**Comment by jennmueng** [comment]
@indapublic Can I get a link to the Sentry issue where the source maps are not working again?

**Comment by indapublic** [comment]
@jennmueng https://sentry.io/organizations/macroactiveio/issues/2824548633/?project=6085670&query=is%3Aunresolved This is issue from fresh app RN 0.66 with recent sentry

![image](https://user-images.githubusercontent.com/856260/143984453-4f992032-612f-4a1f-b490-027a45aedb8e.png)

**Comment by marandaneto** [comment]
@indapublic this is an iOS event, breadcrumbs are not symbolicated, that's why you can't read it.

that's the stack trace:

<img width="1012" alt="Screenshot 2021-11-30 at 08 08 20" src="https://user-images.githubusercontent.com/5731772/144001648-3e2fdd35-fbed-4d26-9709-e87237bacfcd.png">

have you ran a release version? since the library `macroactive` is missing symbols.

<img width="949" alt="Screenshot 2021-11-30 at 08 09 15" src="https://user-images.githubusercontent.com/5731772/144001722-fcfdd639-6204-4f51-a9b1-9103becdfa65.png">

just for context, this is not related to source maps, but rather missing debug symbols for iOS.

https://docs.sentry.io/platforms/react-native/upload-debug/

for iOS they should be uploaded automatically tho, if you run compile and run a release version.

**Comment by indapublic** [comment]
> this is an iOS event, breadcrumbs are not symbolicated, that's why you can't read it.

Be honest, it's not seems like solution for me :) As I said this crash was issued by JS code

> have you ran a release version?

Release version from TestFlight 

> just for context, this is not related to source maps, but rather missing debug symbols for iOS.

Debug is uploaded succesfull during each archiving process, but probably it can be related that I have many apps (with different bundle id).

**Comment by marandaneto** [comment]
@indapublic not sure if I follow, if you triggered the exception via `Sentry.nativeCrash();`, this causes an iOS native issue, even though it's been called from JS code, the native code is responsible for handling it.

The same would be if doing that on Android, you will see a Java stack trace and not the JS code.

We do add a breadcrumb

if you call `throw new Error` on JS, then stack trace and source maps are JS only.

does that answer your question?

**Comment by indapublic** [comment]
My issue provided by url is caused by JS via `throw new Error` so I expect JS stack here

You can see title `RCTFatalException: Unhandled JS Exception: Error: Crashed!`

Code is ```<Button
				title="Crash me!"
				onPress={() => {
					throw new Error("Crashed!");
				}}
			/>```
			
> does that answer your question?

So I'm afraid not. Or I something not understood here

**Comment by indapublic** [comment]
Oh, I see new event here https://sentry.io/organizations/macroactiveio/issues/2824548602/?project=6085670&query=is%3Aunresolved 

Not sure why I see two events regarding to one crash (you can see same title "Crashed")

It looks like JS exception, isn't it? But still no maps and `Source code was not found` warning inside

**Comment by marandaneto** [comment]
> My issue provided by url is caused by JS via `throw new Error` so I expect JS stack here
> 
> You can see title `RCTFatalException: Unhandled JS Exception: Error: Crashed!`
> 
> Code is `<Button title="Crash me!" onPress={() => { throw new Error("Crashed!"); }} />`
> 
> > does that answer your question?
> 
> So I'm afraid not. Or I something not understood here

sorry I read this from you: https://github.com/getsentry/sentry-react-native/issues/1215#issuecomment-981704705

> App just crashed on button pressing with Sentry.nativeCrash();

**Comment by marandaneto** [comment]
> Oh, I see new event here [sentry.io/organizations/macroactiveio/issues/2824548602/?project=6085670&query=is%3Aunresolved](https://sentry.io/organizations/macroactiveio/issues/2824548602/?project=6085670&query=is%3Aunresolved)
> 
> Not sure why I see two events regarding to one crash (you can see same title "Crashed")
> 
> It looks like JS exception, isn't it? But still no maps and `Source code was not found` warning inside

yep, if you go to project settings and source maps:

> There are no artifacts in this archive.

https://docs.sentry.io/platforms/react-native/sourcemaps/#using-custom-release-and-distribution

in case you are using custom `release` and `dist`, you have to follow the page above or check why its not uploading source maps, check the build output for fishy logs as well.

**Comment by indapublic** [comment]
> sorry I read this from you

Yes, it was first attempt. Later I mentioned [here](https://github.com/getsentry/sentry-react-native/issues/1215#issuecomment-982267449)  that I tried with JS error for maps issue investigation.

> in case you are using custom release and dist

I'm not using it. Just simple as described [here](https://github.com/getsentry/sentry-react-native/issues/1215#issuecomment-981704705) 

```
Sentry.init({
	dsn: "https://de42747da2aa4ef7bce48588aeb9e30c@o140491.ingest.sentry.io/6085670",
	// Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
	// We recommend adjusting this value in production.
	tracesSampleRate: 1.0,
});
```

**Comment by marandaneto** [comment]
@indapublic did you run the `sentry-wizard`?

`npx @sentry/wizard -i reactNative -p ios android`

**Comment by indapublic** [comment]
Yes

**Comment by marandaneto** [comment]
@indapublic please generate a local release build and copy-paste the whole log, I'd like to see the output of it.

**Comment by indapublic** [comment]
@marandaneto thanks, I will do that but tomorrow probably

**Comment by indapublic** [comment]
Hi @marandaneto Log file is [here](https://gist.github.com/indapublic/fda6a29ac67482777a812d726803a5f8)

**Comment by marandaneto** [comment]
@indapublic thanks but apparently the log is incomplete, I don't see the "finished" step, nor I did find the `sentry-cli` call at all.
which command do you run to compile your app btw? is there any custom build and setup or just standard eg `npx react-native run-ios --configuration Release`?

**Comment by indapublic** [comment]
@marandaneto Code is published as [repository](https://github.com/indapublic/react-native-sentry-example)

> which command do you run to compile your app btw?

It was just Cmd+B

<img width="311" alt="image" src="https://user-images.githubusercontent.com/856260/144205838-1050806a-e96e-4b52-ab8a-348131e3922c.png">

Log was exported from Xcode output

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/856260/144205937-09f8f299-2c29-45e1-b7c1-c10e4a1f6bef.png">

**Comment by marandaneto** [comment]
@jennmueng please have a look at it

**Comment by marandaneto** [comment]
Android works ootb, no issue on building and reporting the exception, I could reproduce tho using iOS.
maybe there's custom code in the xcode project files or something like that? did you do something different or enabled xcode features? I can't reproduce it using the latest RN and latest Sentry RN SDK on a fresh and new project.

**Comment by marandaneto** [comment]
@indapublic the RCTFatalException issue is different than the one described in the title and description.
is the "Manage source maps for multiple apps" resolved?
would you like to close this one and open a new one for RCTFatalException?

**Comment by indapublic** [comment]
Thanks @marandaneto GIve me a couple of days, I'll try to reproduce this issue.
Regarding to multiple apps - I can't say that resolved until I check it when RCTFatalException will be resolved for test project (or not reproduced), so can we hold this issue for some short time please

**Comment by indapublic** [comment]
Hi @marandaneto Could you check new app from scratch please?

New app is [here](https://github.com/indapublic/testsentryapp), check `README.md`  for my steps. Take attention I have M1 Mac, can be a reason?

Build log is [here](https://gist.github.com/indapublic/0d0510b60e94a47e8abaa60ff41f3eea)

Sentry exception are [here](https://sentry.io/organizations/macroactiveio/issues/2844667250) and [here](https://sentry.io/organizations/macroactiveio/issues/2844667275)

**Comment by marandaneto** [comment]
maybe its related to m1 mac, i will give it a try

**Comment by marandaneto** [comment]
@indapublic I did get the event with symbolicated stack trace, source maps were uploaded correctly using mac M1, but I also have got the RCTFatalException event, this is with an empty project using latest RN SDK and Sentry RN SDK, gonna try using your sample.

**Comment by marandaneto** [comment]
<img width="813" alt="Screenshot 2021-12-15 at 11 03 52" src="https://user-images.githubusercontent.com/5731772/146166022-623091aa-4483-4289-9ef5-be4c6d36c1f1.png">

Everything works with your sample project on my end, the only issue is the `RCTFatalException` report, but it's not related to the issue's title, `Manage source maps for multiple appps`.

I'd rather close this one as it seems related to your environment and open a new one related to the `RCTFatalException`, how does that sound? thanks for the example.

**Comment by indapublic** [comment]
So weird, `RCTFatalException` is not important for me if I can't use library so closing.
