### ISSUE TITLE
Unable to find a specification for `React-Core` depended upon by `RNSentry`

### ISSUE THREAD

**Issue by Kowaio** [getsentry/sentry-react-native#1225]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.9.0 and up

**`react-native` version:** 0.59.9

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- Step 1 `yarn add @sentry/react-native@latest` (or @1.9.0)
- Step 2 `pod install`

**Actual result:**
[!] Unable to find a specification for `React-Core` depended upon by `RNSentry`
[Actual result]

**Expected result:**
Hello, I didn't find this problem in the issues so I'm posting this today. Starting with version 1.9.0, when trying to install pods, it triggers the message above. I tried updating cocoapods and repo of course but I stil get this message. If I test with version 1.8.2, it works like a charm. Any idea why I'm having this starting with 1.9.0 and up ?

Thanks!

[Expected result]

**Comment by jennmueng** [comment]
Looks like you need React Native `>=0.60` for `React-Core`. You can either stay on `1.8.2` or upgrade React Native to `>=0.60`. Closing this for now.
