### ISSUE TITLE
Cannot add task 'bundleReleaseJsAndAssets_SentryUpload_7497576' as a task with that name already exists.

### ISSUE THREAD

**Issue by Giosevid** [getsentry/sentry-react-native#1226]
**OS:**
- [ ]  Windows
- [ * ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ * ]  Android

**SDK:**
- [ * ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.0.9

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [ * ]  No

**Are you using sentry.io or on-premise?**
- [ * ]  sentry.io (SaaS)
- [ ]  on-premise

**I have following issue:**
`Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/../../ws/tc-react-native/example/node_modules/@sentry/react-native/sentry.gradle' line: 72

* What went wrong:
Cannot add task 'bundleReleaseJsAndAssets_SentryUpload_7497576' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (/../../ws/tc-react-native/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/../../ws/tc-react-native/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /../../ws/tc-react-native/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/../../ws/tc-react-native/example/node_modules/@react-native-community/cli/build/index.js:182:9)``

**Steps to reproduce:**
- yarn add @sentry/react-native
- yarn sentry-wizard -i reactNative -p ios android
- yarn android

**Actual result:**

same problem

**Expected result:**

the app should build

**Comment by FaggioniHQ** [comment]
Any news on this?. We are updating to RN 0.64, and we are getting this issue.

**Comment by ehynds** [comment]
Also seeing this issue on RN 0.64

**Comment by jyprksh001** [comment]
> Also seeing this issue on RN 0.64
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/Users/eric/Projects/.../node_modules/@sentry/react-native/sentry.gradle' line: 72
> 
> * What went wrong:
> Cannot add task 'bundleReleaseJsAndAssets_SentryUpload_24' as a task with that name already exists.
> ```

Did you solve it ??

**Comment by stefan-chelaru-auka** [comment]
Any updates?

**Comment by marandaneto** [comment]
do you have any special configuration (different than the default template) on android/app/build.gradle?
have you tried to run a clean build? ./gradlew clean app:installDebug
or ./gradlew stop and then ./gradlew app:installDebug
that could happen if you have multiple variants or build types but not increasing the `versionCode` which is mandatory otherwise you cant publish in the store (2 different apks with the very same versionCode)

**Comment by marandaneto** [comment]
similar to https://github.com/getsentry/sentry-react-native/issues/1401
it's likely an RN issue and could be solved by upgrading RN itself.

please raise a new issue if the problem persists, ideally answering https://github.com/getsentry/sentry-react-native/issues/1226#issuecomment-964924954
