### ISSUE TITLE
Allow custom release for source map upload scripts

### ISSUE THREAD

**Issue by Francesco-Voto** [getsentry/sentry-react-native#1229]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.2

**`react-native` version:** 0.62.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**I have following issue:**

Hello,
should it be possibile to create a different (custom) naming convention for release when source maps are created and uploaded?

Currently we found that release is created as following:
project_name@release+build_number 

We would like to customise it.

Thank you

**Comment by jennmueng** [comment]
We have this feature on our backlog to be able to customize the release on the source map upload script, I'll label this issue as a Feature Request and will post any updates when we implement this.

But for now, you can manually upload source maps with a custom `release` name and `dist` with the cli command here: https://docs.sentry.io/platforms/react-native/sourcemaps/. Note that the `release` and `dist` on the source map and an event have to match **_exactly_** for the source maps to be correctly detected.

**Comment by jennmueng** [comment]
Marked this `up-for-grabs`, if anyone is interested I would start here: 

https://github.com/getsentry/sentry-cli/blob/10dada5914eac25c2c233af6028524c7813057a2/src/commands/react_native_xcode.rs#L271-L281

and maybe add an argument `--release`

**Comment by retyui** [comment]
Have the same problem

I check the source code of `sentry.gradle` + `react_native_xcode.rs` and find that `releaseName` value hardcoded and no way to change it :


**Android:**
https://github.com/getsentry/sentry-react-native/blob/2612b4dafc08c034a12dd6bc38f7148a3004cbf5/sentry.gradle#L168

**iOS:**
https://github.com/getsentry/sentry-cli/blob/d63a0b2ce9c033f5bc1c35bc1405d7719e29e969/src/commands/react_native_xcode.rs#L277-L289

---


I suggest to create env or config support

1) [Android] Using `sentryCli` config

```gradle
project.ext.sentryCli = [
    logLevel: "debug",
    release: '1.2.3',                                                                 // specific value
    getRelease: variant => "${variant.getVersionName()}"    // or function that return value
]
``` 

2) [iOS + Android] Env variable :

```sh
export SENTRY_RELEASE_NAME="1.2.3"
```

**Comment by retyui** [comment]
Any update?

**Comment by retyui** [comment]
I create PRs to fix this issue ^^^

**Comment by retyui** [comment]
fixed

**Comment by marandaneto** [comment]
fixed by https://github.com/getsentry/sentry-cli/pull/967 on iOS and https://github.com/getsentry/sentry-react-native/pull/1548 on Android
