### ISSUE TITLE
Missing symbolication for hermesFatalErrorHandler

### ISSUE THREAD

**Issue by vtoupet** [getsentry/sentry-react-native#1234]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.2

**`react-native` version:** 0.63.4

I am using 'io.sentry:sentry-android-gradle-plugin:1.7.36' plugin with this configuration:
 * uploadNativeSymbols true
 * includeNativeSources true

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/vincent-toupet/issues/2029861519/?project=5410474&query=is%3Aunresolved

---
**I have following issue:**

I have several fatal issues linked to (or in reference with) Hermes (facebook::hermes::detail::hermesFatalErrorHandle). Symbolication is missing even though I am using the Android gradle plugin to upload native symbols and native sources.

There is no way for me to debug this and traces are not symbolicated.

Additionally, would there be a way to add few lines of the logcat to the breadcrumbs? I haven't found anything within the documentation to do so.

**Comment by jennmueng** [comment]
Hmm you can add breadcrumbs natively from the java code, although the method in [this guide](https://blog.waldo.io/integrating-sentry-for-android/)(under Attaching logs) is legacy, you can do something like it by using the `addEventProcessor ` on the scope. So instead of using `addBuilderHelper` you would do:
```java
Sentry.configureScope(scope -> {
  ...
  scope.addEventProcessor(...)
})
```

**Comment by vtoupet** [comment]
@jennmueng I came up with the following
```
Sentry.configureScope(scope -> {
          scope.addEventProcessor((event, hint) -> {
              try {
                  Process process = Runtime.getRuntime().exec("logcat -t 50 --pid ${android.os.Process.myPid()} *:I");
                  BufferedReader bufferedReader = new BufferedReader(
                          new InputStreamReader(process.getInputStream()));

                  // Grab the results
                  String line;
                  while ((line = bufferedReader.readLine()) != null) {
                      event.addBreadcrumb(line);
                  }
              } catch (IOException e) {
                  e.printStackTrace();
              }
              return event;
          });
      });
```
and I place this snippet in the onCreate method of my MainActivity.java. this call is not called when triggering a native crash. I am wondering whether I copied the snippet at the right location (react-native-sentry is probably not initialized at react-native side when the configureScope is called.

**Comment by jennmueng** [comment]
@vtoupet That code snippet looks correct, and yes it would need to be called after the Android SDK is initialized, as this is done asynchronously and we don't return a promise for SDK initialization, you would have to find a way to make sure its called after it's initialized. I will put it forward to the rest of the team about returning a promise when calling `init` or some other way to determine that the native SDK has been initialized.

**Comment by vtoupet** [comment]
@jennmueng @HazAT any news about returning a promise on initialization. That would help with Native customization such as detailed in comment https://github.com/getsentry/sentry-react-native/issues/1234#issuecomment-743765622

**Comment by vtoupet** [comment]
@jennmueng @HazAT Could you please tell me whether you've planned returning a promise on initialization.

**Comment by jennmueng** [comment]
@vtoupet Would a callback such as `onReady` work? Discussed this internally and having only the React Native SDK return a promise would make the API inconsistent between the other SDKs.

**Comment by vtoupet** [comment]
`onReady` callback attribute would be perfect. I can then call a method of my Android NativeModule to set the preprocessor.

**Comment by vtoupet** [comment]
@jennmueng thanks for your dedication on this issue.
