### ISSUE TITLE
was resolved to 2.1.0, which depends on Sentry (= 6.0.9)

### ISSUE THREAD

**Issue by XPgan** [getsentry/sentry-react-native#1244]
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 2.1.0, which depends on
      Sentry (= 6.0.9)

None of your spec sources contain a spec satisfying the dependency: `Sentry (= 6.0.9)`.

    "@sentry/react-native": "^2.1.0",
    "react-native": "0.63.4"

**Comment by MakChan** [comment]
You probably need to do `pod install --repo-update`.

**Comment by jennmueng** [comment]
Exactly what @MakChan said, closing this for now, please reopen if issue persists.

**Comment by LMestre14** [comment]
> You probably need to run `pod install --repo-update` in iOS folder.

I had this issue today and that was the solution, thank you @MakChan !

**Comment by mariomurrent-softwaresolutions** [comment]
And if I don't have an iOS folder and using Expo EAS service? I'm getting the same errir

**Comment by yolpsoftware** [comment]
@mariomurrent-softwaresolutions have you found out anything? I'm getting the same error, on a Managed Expo project, with EAS build (no `ios` folder).

**Comment by mariomurrent-softwaresolutions** [comment]
> @mariomurrent-softwaresolutions have you found out anything? I'm getting the same error, on a Managed Expo project, with EAS build (no `ios` folder).

Updated all versions and made a clean build
