### ISSUE TITLE
Allow native SDK options to be specified by user without needing to re-initialize native SDK.

### ISSUE THREAD

**Issue by serhiipalash** [getsentry/sentry-react-native#1263]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/stroller-ab/issues/2118758655/?environment=development&project=246038&query=is%3Aunresolved&statsPeriod=14d

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
  debug: false,
  enableAutoSessionTracking: true,
  integrations(integrations) {
    return integrations.filter(integration => integration.name !== 'Breadcrumbs')
  },
});
```

---
**I have following issue:**

I can see default breadcrumbs for native errors even after disabling `Breadcrumbs` integration during initing SDK

**Steps to reproduce:**
- Init SDK with disabling Breadcrumbs
- Raise Native error
- Check tracked breadcrumbs

**Actual result:**

You can see default native breadcrumbs

<img width="1076" alt="Screenshot 2021-01-03 at 10 38 11 PM" src="https://user-images.githubusercontent.com/14208343/103488354-7558d300-4e14-11eb-8032-acaacc79886c.png">

**Expected result:**

You should see only exception in breadcrumbs

<img width="1070" alt="Screenshot 2021-01-03 at 10 39 34 PM" src="https://user-images.githubusercontent.com/14208343/103488372-99b4af80-4e14-11eb-92a4-9edd25bb8590.png">

**Comment by serhiipalash** [comment]
The issue is presented only on Native errors, on JS errors everything works as expected 

https://sentry.io/organizations/stroller-ab/issues/2118676054/?environment=development&project=246038&query=is%3Aunresolved

**Comment by serhiipalash** [comment]
Should I do this manually in Native code?

```
import Sentry

SentrySDK.start(options: [
    //...
    "integrations": Sentry.Options.defaultIntegrations().filter { (name) -> Bool in
        return name != "SentryAutoBreadcrumbTrackingIntegration" // This will disable  SentryAutoBreadcrumbTrackingIntegration
    }
    //...
])
```

https://docs.sentry.io/platforms/apple/usage/#integrations

**Comment by jennmueng** [comment]
> Should I do this manually in Native code?
> 
> ```
> import Sentry
> 
> SentrySDK.start(options: [
>     //...
>     "integrations": Sentry.Options.defaultIntegrations().filter { (name) -> Bool in
>         return name != "SentryAutoBreadcrumbTrackingIntegration" // This will disable  SentryAutoBreadcrumbTrackingIntegration
>     }
>     //...
> ])
> ```
> 
> https://docs.sentry.io/platforms/apple/usage/#integrations

No you shouldn't do this as it will initialize the SDK twice and cause both to not be synced. Currently you're not able to disable just Native breadcrumbs, but there is a way to do it with `patch-package`.

1. Follow the setup instructions for `patch-package` here:  https://github.com/ds300/patch-package

2. Add these lines below to `node_modules/@sentry/react-native/ios/RNSentry.m` inside `startWithOptions`.
```diff
         reject(@"SentryReactNative", error.localizedDescription, error);
         return;
     }
+
+    NSMutableArray *integrations = [SentryOptions defaultIntegrations].mutableCopy;
+    [integrations removeObject:@"SentryAutoBreadcrumbTrackingIntegration"];
+    sentryOptions.integrations = integrations;
+
     [SentrySDK startWithOptionsObject:sentryOptions];
 
     resolve(@YES);
```

3. Run `yarn patch-package @sentry/react-native`

**Comment by jennmueng** [comment]
Actually, now that we just merged https://github.com/getsentry/sentry-react-native/pull/1259, when we release that you can just re-initialize the SDK in Swift/Objective-C and that won't break the SDK.

**Comment by serhiipalash** [comment]
> Now every time you run `yarn install` it should patch the `@sentry/react-native` package to disable this integration.

Thanks! It works. It took me some time to test it in all environments.

Now all native breadcrumbs are disabled. Still, I have one issue with breadcrumbs.

JS-exceptions attach breadcrumbs from previous session

<img width="1132" alt="Screenshot 2021-01-04 at 9 12 17 PM" src="https://user-images.githubusercontent.com/14208343/103570689-36895280-4ed2-11eb-81ce-efc94f15946d.png">

https://sentry.io/organizations/stroller-ab/issues/2129847019/?environment=staging&project=246038&query=is%3Aunresolved&statsPeriod=14d

Native exceptions don't as expected 

https://sentry.io/organizations/stroller-ab/issues/2120472646/?environment=development&environment=staging&project=246038&query=is%3Aunresolved&statsPeriod=14d

<img width="1087" alt="Screenshot 2021-01-04 at 9 21 40 PM" src="https://user-images.githubusercontent.com/14208343/103571037-d9da6780-4ed2-11eb-8556-ab0d25032bc2.png">

@jennmueng can you help with it? It's a minor issue and I can create a separate bug report for it, if you want to.

**Comment by serhiipalash** [comment]
> JS-exceptions attach breadcrumbs from previous session

It seems like it only happens on Android

**Comment by serhiipalash** [comment]
> 2. Add these lines below to `node_modules/@sentry/react-native/ios/RNSentry.m` inside `startWithOptions`.

@jennmueng is there a way to do the same in Android native code?

**Comment by jennmueng** [comment]
Yes you can do something similar in `node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java`.

**Comment by serhiipalash** [comment]
Final patch

```
diff --git a/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java b/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java
index e3fac8d..f31ebc4 100644
--- a/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java
+++ b/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java
@@ -29,6 +29,7 @@ import java.util.logging.Level;
 import java.util.logging.Logger;
 
 import io.sentry.android.core.AnrIntegration;
+import io.sentry.android.core.ActivityBreadcrumbsIntegration;
 import io.sentry.android.core.NdkIntegration;
 import io.sentry.android.core.SentryAndroid;
 import io.sentry.Sentry;
@@ -156,6 +157,13 @@ public class RNSentryModule extends ReactContextBaseJavaModule {
                 }
             }
 
+            final List<Integration> integrations = options.getIntegrations();
+            for (final Integration integration : integrations) {
+                if (integration instanceof ActivityBreadcrumbsIntegration) {
+                    integrations.remove(integration);
+                }
+            }
+
             logger.info(String.format("Native Integrations '%s'", options.getIntegrations().toString()));
             sentryOptions = options;
         });
diff --git a/node_modules/@sentry/react-native/ios/RNSentry.m b/node_modules/@sentry/react-native/ios/RNSentry.m
index da0488d..b46913b 100644
--- a/node_modules/@sentry/react-native/ios/RNSentry.m
+++ b/node_modules/@sentry/react-native/ios/RNSentry.m
@@ -64,6 +64,9 @@ + (BOOL)requiresMainQueueSetup {
         reject(@"SentryReactNative", error.localizedDescription, error);
         return;
     }
+    NSMutableArray *integrations = [SentryOptions defaultIntegrations].mutableCopy;
+    [integrations removeObject:@"SentryAutoBreadcrumbTrackingIntegration"];
+    sentryOptions.integrations = integrations;
     [SentrySDK startWithOptionsObject:sentryOptions];
 
     resolve(@YES);
```

**Comment by jennmueng** [comment]
That looks about right, yep.

**Comment by serhiipalash** [comment]
Hi @jennmueng ! Can you please help me? We have upgraded our `@sentry/react-native` from v2.1.0 to v2.4.0 and now I am trying to apply patch for disabling activity breadcrumbs on native side. I see that new config option `isEnableActivityLifecycleBreadcrumbs` was added on Android.

1. Is it already exposed to React Native? 
2. Can I use it? 
3. Will it work for iOS or should I keep the iOS patch as is?

**Comment by jennmueng** [comment]
@serhiipalash 
1. No it is not
2. Yes you can by supplying it as an option to the `init` call on Android with `setEnableActivityLifecycleBreadcrumbs`.
3. It's not an option on iOS
