### ISSUE TITLE
Better docs for Hermes sourcemaps

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1270]
We've seen a lot of issues along with customers contacting our support team regarding issues with sourcemaps from Hermes. A lot of the issues end up being fixed with this bundle step: https://github.com/getsentry/sentry-react-native/issues/761#issuecomment-587498344 We [mention this in the docs](https://docs.sentry.io/platforms/react-native/hermes/) but it's not clear whatsoever about how to achieve this.

We need to make it more clear how to handle source maps from Hermes with Sentry.

Maybe also consider making the automatic source map upload process handle this.

**Comment by scblason** [comment]
Are there any plans to fix the correct bunlde upload in the automatic source map upload process?
I'm getting the index.android.bundle of size 0b uploaded to sentry.io.

**Comment by jennmueng** [comment]
@scblason 0b for Hermes source maps is correct.
