### ISSUE TITLE
Write documentation for autoInitializeNativeSdk

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1273]
With https://github.com/getsentry/sentry-react-native/pull/1259 merged, you can now disable the React Native SDK on the JS layer from initializing the SDK on the native layer while still allowing the native SDK to be used.

This allows you to manually initialize the native SDK yourself. This opens up the door for catching native errors before the JS engine runs: https://github.com/getsentry/sentry-react-native/issues/542 and gives native-code-heavy apps more customization options.

This feature should be documented of course, but we need to also mention that to maintain the same behavior as usual, you would have to copy over some of the options we pass such as `beforeSend`.

**Comment by bruno-garcia** [comment]
@jennmueng should we rename this options before documenting it?

to `autoInitializeNativeSdk` instead of `should`?

**Comment by jennmueng** [comment]
Hmm yes I agree that name makes more sense

**Comment by bruno-garcia** [comment]
It's worth making a note about Android and the use of `ContentProvider`. @marandaneto has more details about this.

**Comment by bruno-garcia** [comment]
The flag was renamed and the feature documented: https://docs.sentry.io/platforms/react-native/manual-setup/
