### ISSUE TITLE
Sentry close and flush is not a function

### ISSUE THREAD

**Issue by farodrig** [getsentry/sentry-react-native#1279]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  debug: DEBUG,
  dsn: SENTRY_DSN,
  enableAutoSessionTracking: true,
  environment: SENTRY_ENV,
  release: `cuidemonos-app@${DeviceInfo.getVersion()}`,
});
```

---
**I have following issue:**

When I try to follow this [instructions](https://docs.sentry.io/platforms/react-native/configuration/draining/) from the react-native docs. I have an error saying `TypeError: Sentry.close is not a function. (In 'Sentry.close(2000)', 'Sentry.close' is undefined)`

**Code example:**
```
    Sentry.captureException(new Error('Forced logout for unauthenticated user'))
    await Sentry.close(2000)
```

**Actual result:**

`TypeError: Sentry.close is not a function. (In 'Sentry.close(2000)', 'Sentry.close' is undefined)`

**Expected result:**

`Forced logout for unauthenticated user` error shown on issues list

**Comment by jennmueng** [comment]
Oh `Sentry.close()` actually is not supported on React Native. This is a mistake and should not be on the documentation.

**Comment by jennmueng** [comment]
We fixed the docs, closing this now.
