### ISSUE TITLE
User is always defined with static ID and cannot be reset according to documentation

### ISSUE THREAD

**Issue by jeseter45** [getsentry/sentry-react-native#1280]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.63.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
  environment: 'localhost',
  debug: __DEV__,
  enabled: true,
  normalizeDepth: 0,
  enableAutoSessionTracking: true,
  release: `${getBundleId()}@${getVersion()}`, // functions from react-native-device-info package
  dist: getBuildNumber(), // as in previous line
});
```

---
**I have following issue:**
Error reported to Sentry.io has set user with static ID. By static I mean that every following error has defined user with the same ID. 

ID is probably stored somewhere in the device storage or generated from device metadata. I am using Android Emulator. When I wipe emulator data (Android Studio -> AVD Manager -> device XY -> Wipe Data) then errors are reported under new user with different ID. 

Also, calling `Sentry.setUser(null)` at global scope or calling `scope.setUser(null)` and `scope.setUser({})` on local scope does NOT reset the user to `Uknown User`. Only `Sentry.setUser({})` call with empty object works as expected.

I noticed this problem in Sentry UI after I started to play with Sentry API (`Sentry.configureScope` vs `Sentry.withScope` vs `const scope = new Sentry.Scope()`) today. But that doesn't have to mean anything.

Examples of static IDs:
- `b1bcd671e7d7c46c`
- `a08d80028cf7c972`
- `2d21d6592ec1f65f`
- `51e81450a760d8d6`

*Note:* I did not created release via sentry-cli, thus was detected by Sentry after first error was sent. Also no source maps was sent yet.

iOS works fine.

**Steps to reproduce:**
// Sentry.init(...);
throw new Error('Test');

**Actual result:**
Error was sent to Sentry.io, but user is defined with static ID.
![Screenshot 2021-01-12 at 12 33 19](https://user-images.githubusercontent.com/70572245/104309409-663bea00-54d2-11eb-83d8-2aac11342450.png)
![Screenshot 2021-01-12 at 12 39 22](https://user-images.githubusercontent.com/70572245/104309946-380ada00-54d3-11eb-8d45-de64064d6305.png)

**Expected result:**
Error sent to Sentry.io without defined user.
![Screenshot 2021-01-12 at 12 33 57](https://user-images.githubusercontent.com/70572245/104309449-78b62380-54d2-11eb-9214-37b721359270.png)

**Comment by jeseter45** [comment]
More info about reseting the user:

```
// this works fine - user is unknown in Sentry UI
Sentry.configureScope(scope => {
  scope.setUser({});
  Sentry.captureException(new Error('Test 1'));
});

// this works fine too
Sentry.configureScope(scope => {
  scope.setUser({});
  Sentry.captureException(new Error('Test 2'), () => scope);
});

// this does not - user is defined with static ID
const scope = new Sentry.Scope();
scope.setUser({});
Sentry.captureException(new Error('Test 3'), () => scope);
```

**Comment by jeseter45** [comment]
Now, when I am testing release version of Android app on real device I see user to be set, but instead of ID is used IP address of the internet connection (still using `new Error('Test 1')` example from previous commit).

Is it because I am setting user by `scope.setUser({})` instead of `scope.setUser(null)` (which currently does not work)?

**Comment by jeseter45** [comment]
To my previous comment about IP address:
My assumption about `scope.setUser({})` is probably correct, because after I enabled IP address storage prevention in Sentry UI (project-level), error reports in UI shows `Unknown User` as expected.

![Screenshot` 2021-01-13 at 09 49 36](https://user-images.githubusercontent.com/70572245/104428404-bc696580-5584-11eb-9013-2e6d5da32835.png)

So `Sentry.setUser(null)` and `scope.setUser(null)` API still needs to be resolved.

**Comment by jennmueng** [comment]
Hmm, seeing this part
```js
// this does not - user is defined with static ID
const scope = new Sentry.Scope();
scope.setUser({});
Sentry.captureException(new Error('Test 3'), () => scope);
```
tells me that it's not just the user that's the issue it's the fact that on Android the global scope (which is synced down from the JS layer to the Android layer) overwrites the scope on the event every time it's sent. I will raise this issue with the team and investigate it further.

**Comment by marandaneto** [comment]
indeed, Android does set an event id if there's none, a workaround would be:

`scope.setUser({id: ''});`

since we only check if the `id` is null and not empty

**Comment by marandaneto** [comment]
@jeseter45 The generated id isn't PII since it's a randomly generated value by the SDK, just to have a consistent id during the app's installation.
In case you still want to strip it off, you can by doing either https://github.com/getsentry/sentry-react-native/issues/1280#issuecomment-964939518 or https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/
So you can set the `beforeSend` callback on the Native SDKs and remove the user id directly in there https://docs.sentry.io/platforms/android/configuration/filtering/#using-platformidentifier-namebefore-send-
