### ISSUE TITLE
SDK doesn't start session on first app launch on iOS

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-react-native#1292]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 
https://github.com/getsentry/sentry-react-native/blob/ccf1fe10d608a4497bf6a5974ac6131e787f6cd3/sample/package.json#L20-L24

**Configuration:**

https://github.com/getsentry/sentry-react-native/blob/ccf1fe10d608a4497bf6a5974ac6131e787f6cd3/sample/src/App.tsx#L18-L36

---
**I have following issue:**

The sentry-cocoa SDK doesn't start a session on the first launch of the app, because [`SentrySessionTracker.didBecomeActive`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentrySessionTracker.m#L116) doesn't fire. If you put the app in the background and open it again `didBecomeActive` fires. I'm not sure if we need to fix this in sentry-cocoa, in sentry-react-native, or both.

**Steps to reproduce:**
* Start sample app
* Put the app in background for 6 seconds
* Launch app again

**Actual result:**

The SDK doesn't send a session.

**Expected result:**

The SDK should send a healthy session.

This is related to https://github.com/getsentry/sentry-dart/issues/271

**Comment by marandaneto** [comment]
we've fixed it on Flutter and it worked pretty well, I'd just replicate the same solution.

See: https://github.com/getsentry/sentry-dart/pull/274/files

@bruno-garcia we need to prioritize this.

**Comment by bruno-garcia** [comment]
@marandaneto right! thanks
