### ISSUE TITLE
setContext sometimes shows [Filtered]

### ISSUE THREAD

**Issue by sammysium** [getsentry/sentry-react-native#1331]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
sentry react-native 2.0.1

### Steps to Reproduce

Sentry.setContext("details", {
message: '"DB ERROR: Could not fetch User RIghts from DB - abc@abc.net: User has no valid authorizations in the database.",
kind: "MISSING_DATA",
api: 'http://www.abc.net'
});

### Expected Result

in Sentry dashboard in details section i should see:

message: '"DB ERROR: Could not fetch User RIghts from DB - abc@abc.net: User has no valid authorizations in the database.",
kind: "MISSING_DATA",
api: 'http://www.abc.net'

### Actual Result
message: [Filtered],
kind: [Filtered],
api: 'http://www.abc.net'

I don't think it is a bug but I don't want to filter anything; just to show it as it is.

**Comment by jennmueng** [comment]
@sammysium You can go on to your Sentry Dashboard -> Project Settings -> Security & Privacy, and you will be able to adjust your data scrubbing settings to not filter this.

<img width="1423" alt="Screen Shot 2021-02-07 at 10 17 44 PM" src="https://user-images.githubusercontent.com/30991498/107150818-4f35ce00-6992-11eb-8805-5c83e5bc5ffa.png">
