### ISSUE TITLE
Doesn't catch rendering errors

### ISSUE THREAD

**Issue by kesha-antonov** [getsentry/sentry-react-native#1345]
Hi!

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Simulator, iOS 14.3
"@sentry/react-native": "^2.2.0"

### Steps to Reproduce

In your app with react-navigation to Tabs stack scene add this code:

```
useEffect(() => {
    throw new Error('My new custom error: 123')
  }, [])
```

You will not see error in Sentry dashboard.

Replace code above with this one (basically add setTimeout):

```
useEffect(() => {
    setTimeout(() => {
      throw new Error('My new custom error - with setTimeout: 123')
    }, 2000)
  }, [])
```

You will see error in dashboard.

### Expected Result

To see both errors in dashboard.

### Actual Result

Only error with setTimeout get caught.

**Comment by jennmueng** [comment]
The SDK should catch all unhandled exceptions, and I've tried to reproduce this. Maybe you have something that's capturing the error and not letting it get thrown like an `ErrorBoundary`?

Otherwise, if you can provide a repo with a reproduction it would be great help for us to debug this 😁

**Comment by kesha-antonov** [comment]
Hey
Thanks
I'll try to make repro

**Comment by Chinocy** [comment]
@kesha-antonov the same happens to me, works with setTimeout

**Comment by marandaneto** [comment]
> Hey Thanks I'll try to make repro

did you have the chance to make a repro case?
@jennmueng did you manage to reproduce it?

**Comment by BatDroid** [comment]
I'm facing the same issue, any news on this?

**Comment by BatDroid** [comment]
seems to be from redux-persist, cause when I put a container component before that, it works, but putting that component inside `PersistGate`, it doesn't send the report anymore...
wondering what should I do now...

**Comment by jennmueng** [comment]
@BatDroid @kesha-antonov @Chinocy Try wrapping your root app with a `Sentry.wrap` [like so](https://docs.sentry.io/platforms/react-native/#wrap-your-app) and please let me know if the issue is fixed?

**Comment by marandaneto** [comment]
@jennmueng let's keep it closed since we need a repro case for further investigation, which has been asked already 1y ago.
Please raise a new issue if necessary with a repro case since we cannot reproduce it locally.
