### ISSUE TITLE
Linking library in separate folder doesn't load correctly with Android: "SentryError: Native Client is not available, can't start on native." error.

### ISSUE THREAD

**Issue by massanen7** [getsentry/sentry-react-native#1349]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native": "^2.2.0"

### Steps to Reproduce
- We work on a monorepo and we store the sentry library in separate folder, called workspaces.
- We've linked the library from the new location:
**android/app/build.gradle**
`apply from: "../../../workspaces/node_modules/@sentry/react-native/sentry.gradle"`
and 
`dependencies {
    // ... other dependencies listed here //
    implementation project(':@sentry_react-native')
}`

**android/settings.gradle**
`include ':@sentry_react-native'
project(':@sentry_react-native').projectDir = new File(rootProject.projectDir, '../../workspaces/node_modules/@sentry/react-native/android')`

### Expected Result
- The sentry library to load normally.
-  It does load normally with iOS, and having the library in workspaces folder is not a problem.
- Checking if it works loading the library normal, in the regular react-native node-modules folder, it also works well with Android.
- But we want to have the library installed only in workspaces, not having to install it twice.

### Actual Result
- When running the app with Android (having the library in worskpaces folder) we got the following error:
`  ERROR    SentryError: Native Client is not available, can't start on native.`
- If we install the library in react-native node-modules regular folder, with the linking library pointing to workspaces folder, and only removing the step of the previous configuration:
`dependencies {
    // ... other dependencies listed here //
    implementation project(':@sentry_react-native')
}`
it loads all good. 

- It looks like https://github.com/getsentry/sentry-react-native/blob/master/src/js/wrapper.ts#L8 `RNSentry`  has null value with android and library in workspaces folder. 

- And again, if I install the library in native, without touching the workspaces one, then `RNSentry`has a value, and all works fine.

Any ideas?

**Comment by jennmueng** [comment]
This looks like the library is not correctly linked in gradle. `RNSentry` being missing in https://github.com/getsentry/sentry-react-native/blob/master/src/js/wrapper.ts#L8 means that React Native is not loading the Android native bridge code. The SDK has no issue being included from an external folder outside `node_modules` as we do so in our sample app: https://github.com/getsentry/sentry-react-native/blob/8473e57945da007393dce641beaa0690e5a72d67/sample/android/app/build.gradle#L85

**Comment by massanen7** [comment]
Hi Jen, thanks much for answering.

The thing is that It is correctly linked. Without changing how it is linked:
`apply from: "../../../workspaces/node_modules/@sentry/react-native/sentry.gradle"`

just installing the library in the regular node modules, the `RNSentry` from workspaces library it isn't then missing.

**Comment by jennmueng** [comment]
@massanen7 Hmm if it's not your configuration and you believe something is broken, maybe I would bring this up with React Native then, as the RNSentry module is just a React Native module and the issue is with the native module being loaded.

**Comment by marandaneto** [comment]
@massanen7 have you tried to check all the config? see docs to do it manually https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/
does it work using the latest Sentry RN SDK?
