### ISSUE TITLE
React-Native performance traces not being uploaded to Sentry

### ISSUE THREAD

**Issue by chrisfinch** [getsentry/sentry-react-native#1361]
### Environment

Using Sentry.io on React-Native.

Running React-Native on Android device only (ios not used).

```
"@sentry/react-native": "^2.2.0",
"react": "16.13.1",
"react-native": "^0.63.4",
"@react-navigation/drawer": "^5.8.2",
"@react-navigation/native": "^5.5.1",
"@react-navigation/stack": "^5.5.1",
```

### Steps to Reproduce

Instructions from documentation were followed;

Setup:
```typescript
// index.ts

import * as Sentry from '@sentry/react-native';
import { SENTRY_DSN, SENTRY_ENV } from '@env';

export const routingInstrumentation = new Sentry.ReactNavigationV5Instrumentation();

Sentry.init({
  dsn: SENTRY_DSN,
  tracesSampleRate: 1.0,
  enableAutoSessionTracking: true,
  environment: SENTRY_ENV,
  integrations: [
    new Sentry.ReactNativeTracing({
      tracingOrigins: ['localhost', 'some.other.url', /^\//],
      routingInstrumentation
    })
  ],
  debug: true,
  logLevel: 3
});

// ...

```
Attempt to send a performance trace.
```typescript
// App.ts

// ...
const App = () => {
  const transaction = Sentry.startTransaction({
    name: 'App Component',
    sampled: true
  });
  transaction.sampled = true;
  const span = transaction.startChild({ op: 'functionX' }); // This function returns a Span
  span.sampled = true;
  
  setTimeout(() => {
    span.finish(); // Remember that only finished spans will be sent with the transaction
    transaction.finish();
  }, 500);

  return (
 // ...
```
Metro bundler logs from React-Native on App startup:
```
Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
Sentry Logger [Log]: Integration installed: Release
Sentry Logger [Log]: Integration installed: InboundFilters
Sentry Logger [Log]: Integration installed: FunctionToString
Sentry Logger [Log]: Integration installed: Breadcrumbs
Sentry Logger [Log]: Integration installed: LinkedErrors
Sentry Logger [Log]: Integration installed: UserAgent
Sentry Logger [Log]: Integration installed: DebugSymbolicator
Sentry Logger [Log]: Integration installed: RewriteFrames
Sentry Logger [Log]: Integration installed: DeviceContext
Sentry Logger [Log]: Setting idle transaction on scope. Span ID: a5a7ff17b3c5b929
Sentry Logger [Log]: Starting heartbeat
Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
Sentry Logger [Log]: Integration installed: ReactNativeTracing
Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2021-02-23T20:25:50.545Z navigation
Sentry Logger [Log]: [Tracing] flushing IdleTransaction
Sentry Logger [Log]: [Tracing] Discarding transaction because its trace was not chosen to be sampled.
Sentry Logger [Log]: [Tracing] starting undefined transaction - App Component
```

### Expected Result

Performance traces should be uploaded and visible on Sengry.io dashboard.

### Actual Result

No performance traces appear, logs suggest that none are uploaded.

**Comment by jennmueng** [comment]
Hmm the discarded transaction seems to be from the route transaction and not the one you created. Can you provide a reproduction sample in a repo that we can check out? We've tried what you have and can't reproduce it. Also, are you looking in the right place on the dashboard—the discover tab > all events, and transactions should appear there not in the issues list.

**Comment by chrisfinch** [comment]
> Also, are you looking in the right place on the dashboard—the discover tab > all events, and transactions should appear there not in the issues list.

My organisation is currently on the free developer plan and as such does not have access to the discover tab. Our aim is to try out the error capture and performance tracing features and upgrade plans if they meet our needs. I am looking in the "Performance" tab and the only thing in there for our React-Native project is the option to take a tour or start setup.

Perhaps there is something I'm missing in the above? I've followed the setup as instructed and confirmed that the free plan should include performance traces..?

I'll see if I can put together a reproduction.

**Comment by jennmueng** [comment]
@chrisfinch Yes a reproduction would be great. What's also unusual is that the route transaction should also be sampled.

I checked with the team and you should be able to use performance if the option to take a tour or start setup is being shown—so this points towards possibly being a bug.

**Comment by chrisfinch** [comment]
Feeding back - I updated and things seem to be working for the time being - will keep an eye on it and open a support case if needed.

Thanks for the help

**Comment by jeffreyroshan** [comment]
Hey, I am facing similar issue. The performance traces are not being uploaded.
I am trying a custom transaction. I can see the tracing started log but nothing more.

`Sentry Logger [Log]: [Tracing] starting undefined transaction - SampleTrace
`

I am using:
```
"react": "16.13.1",
"react-native": "0.63",
"@sentry/react-native": "^2.2.1"
```

@chrisfinch what was the fix that worked for you?

Thanks

**Comment by chrisfinch** [comment]
@jeffreyroshan This is one issue I have: https://github.com/getsentry/sentry-react-native/issues/1369 - hopefully a fix comes soon.

The non-uploading issue was fixed by updating to the latest version - not sure what the issue was there....
