### ISSUE TITLE
iOS build from react native cli fails on network error

### ISSUE THREAD

**Issue by alpha0010** [getsentry/sentry-react-native#1364]
### Environment

How do you use Sentry?
Self-hosted 21.3.0.

Which SDK and version?
sentry.javascript.react-native 2.2.1

### Steps to Reproduce

1. Create a disruption between the dev computer and Sentry server (no internet, firewall, server error, etc.)
2. Build from command line (`npm run ios` -> `react-native run-ios`)

### Expected Result

App builds an runs.

### Actual Result

Build fails.  There is a lot of text printed, but the key part appears to be:
```
The following build commands failed:
    PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/alpha0010/Library/Developer/Xcode/DerivedData/template-acqjxszvghjxvjfvcyernkgabbtm/Build/Intermediates.noindex/template.build/Debug-iphonesimulator/template.build/Script-E07C1CA5205B4C85AA582C57.sh
```

However, if building from within Xcode (but all else remains the same), app builds and runs fine.

This issue does not occur on Android.

**Comment by jennmueng** [comment]
The app builds but I assume the "Upload Debug Symbols to Sentry" build script still fails right—it just does not fail the whole build. This is because on Xcode the command is run in the background instead of the foreground like when calling `run-ios`.

I'm not sure if this is possible, but I can forward it to our CLI team.

**Comment by marandaneto** [comment]
It fails because the CLI requires the network to upload debug symbols, this only happens on release mode.
If you don't have connection, compile on debug mode or comment out the script that uploads debug symbols.
