### ISSUE TITLE
ReactNavigationV5Instrumentation un-usable due to unconfigurable timeout

### ISSUE THREAD

**Issue by chrisfinch** [getsentry/sentry-react-native#1369]
cc @jennmueng

Further to my now closed issue: https://github.com/getsentry/sentry-react-native/issues/1361 I've figured out why the route transition traces are not working.

[This non-configurable timeout](https://github.com/getsentry/sentry-react-native/blob/master/src/js/tracing/reactnavigationv5.ts#L27) `STATE_CHANGE_TIMEOUT_DURATION ` means that I can't get traces on my route transitions.

Monkey patching the sentry node module with a larger timeout results in the traces getting sent.

Ironically I'm trying to use sentry to diagnose and trace my slow route transitions on old devices and this very timeout prevents me from doing that because they are too slow!

This should be configurable via an options object I think.

Let me know if I've misunderstood something - thanks.

**Comment by jennmueng** [comment]
This makes perfect sense, my mistake for missing out on this—will add this ASAP.
