### ISSUE TITLE
Sentry `sampelRate` caused "Discarding event because..."

### ISSUE THREAD

**Issue by abdullahizzuddiin** [getsentry/sentry-react-native#1371]
### Environment

How do you use Sentry?
sentry io

Which SDK and version?
- RN 0.61.5
- "@sentry/react-native": "^2.2.2",

### Steps to Reproduce
1. Add Sentry installation
```
const dsn = Config.SENTRY_DSN;
const debug = __DEV__;
const release = `${DeviceInfo.getBundleId()}@${versionName}@${versionCode}+codepush:${codepushDist}`;
const environment = isProductionEnv ? 'production' : 'staging';
const sampleRate = 0.2;
const tracesSampleRate = 0.2;
const maxBreadcrumbs = 150;

Sentry.init({
        dsn,
        debug,
        release,
        dist: release,
        environment,
        sampleRate,
        tracesSampleRate,
        maxBreadcrumbs,
    });
```
2. run debug app
3. trigger false-error with `let a = {}; a.hehe();` on random button
3. red dev menu displaying what error happened

### Expected Result
I expect our dev menu will display what code that triggered error like this.
![image](https://user-images.githubusercontent.com/6801853/110279856-6527c480-800c-11eb-97c2-8c0e8377a466.png)

### Actual Result
But, instead, dev menu only displayed `Discarding event because it's not included in the random sample`. I know, I add low/small `sampleRate` value. But, I don't expect this thing happened. It will hide the real error message of my buggy code.

![image](https://user-images.githubusercontent.com/6801853/110279639-fd717980-800b-11eb-9b0d-e483c2cb8cf9.png)

**Comment by jennmueng** [comment]
@abdullahizzuddiin You are passing `debug: true` to the init options. This enables debug mode for the SDK which is why it's showing this as the purpose of this mode is to debug the Sentry SDK. If you disable debug mode for the SDK it will not log this.

Closing as this would resolve the issue.
