### ISSUE TITLE
Source code was not found `app:///index.android.bundle`even I've uploaded sourcemap

### ISSUE THREAD

**Issue by abdullahizzuddiin** [getsentry/sentry-react-native#1385]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
- react native 0.61.5
- @sentry/react-native: ^2.2.2

### Steps to Reproduce
**Initial Configuration**

```javascript
const dsn = Config.SENTRY_DSN;
const debug = __DEV__;
const release = `${DeviceInfo.getBundleId()}@${versionName}@${versionCode}+codepush:${codepushDist}`;
const dist = `${versionName}@${versionCode}+codepush:${codepushDist}`;
const environment = isProductionEnv ? 'production' : 'staging';
const sampleRate = debug ? 1 : 0.5;
const tracesSampleRate = 0.2;
const maxBreadcrumbs = 150; 

    Sentry.init({
        dsn,
        debug,
        release,
        dist,
        environment,
        sampleRate,
        tracesSampleRate,
        maxBreadcrumbs,
    });
```

- upload sourcemap
```
node_modules/@sentry/cli/bin/sentry-cli releases --org my-org --project my-project-slug     files "my.app.staging.debug@1.23.0@155+codepush:1"     upload-sourcemaps     --dist "my.app.staging.debug@1.23.0@155+codepush:1"     --strip-prefix . --bundle android/app/build/generated/assets/react/staging/debug/index.android.bundle --bundle-sourcemap android/app/build/generated/sourcemaps/react/staging/debug/index.android.bundle.map

// I also did this
node_modules/@sentry/cli/bin/sentry-cli releases --org my-org --project my-project-slug     files "my.app.staging.debug@1.23.0@155+codepush:1"     upload-sourcemaps     --dist "my.app.staging.debug@1.23.0@155+codepush:1"     --strip-prefix . android/app/build/generated/sourcemaps/react/staging/debug/index.android.bundle.map
```
- trigger random bug.
- Look at sentry UI and find the issue

### Expected Result
I won't see any error as on [Actual Result section](#actual-result). 

I want to see my stack trace (without minified) and find the real root cause of my buggy app.

### Actual Result

- Issue Section
  ![image](https://user-images.githubusercontent.com/6801853/110460877-58d16380-8101-11eb-958d-f2b5107eb46f.png)

- Sourcemap Section
  ![image](https://user-images.githubusercontent.com/6801853/110460929-67b81600-8101-11eb-8d70-ce7a80f94025.png)

### Notes
I also have read these issues:
- https://github.com/getsentry/sentry-fastlane-plugin/issues/44
- https://github.com/getsentry/sentry-react-native/issues/1190

**Comment by jennmueng** [comment]
@abdullahizzuddiin As it says in your screenshot, you cannot have the `@` character in the `dist` field. I would just set `dist` to `155+codepush:1` in your case.

**Comment by abdullahizzuddiin** [comment]
Thanks for pointing out @jennmueng.

Actually, I've fixed `dist` issue. Unfortunately, my app was building when I posted this issue.

My main concern is the second error message. How to fix this `app:///index.android.bundle` issue

**Comment by jennmueng** [comment]
@abdullahizzuddiin Your new error is happening because your sourcemaps are named `index.android.bundle` and the error occurs in `index.js`. The filenames have to match for the sourcemaps to work. Are you running in dev mode or something that's causing the JS code not to be loaded from `index.android.bundle`?

**Comment by abdullahizzuddiin** [comment]
Actually, both of error that I uploaded (on thread starter and on previous post) is happened on react-native android debug mode.

And I just realized, my app's sourcemap that usually generated and located on `android/app/build/generated/sourcemaps/` is not exist. As I read `@sentry/react-native/sentry.gradle`, that gradle will delete sourcemap after uploaded to sentry server. Unfortunately, sourcemap's release name that come from sentry.gradle didn't same as release name that I initialize on `Sentry.init()`

![image](https://user-images.githubusercontent.com/6801853/110633968-01ec8c80-81dc-11eb-86a1-6a5db4ae229a.png)

can we customize release name used on `sentry.gradle` ? or can we disable auto delete from that gradle?

**Comment by jennmueng** [comment]
@abdullahizzuddiin If you use custom release names, you will have to manually upload sourcemaps: https://docs.sentry.io/platforms/react-native/manual-setup/sourcemaps/

**Comment by abdullahizzuddiin** [comment]
Ah, I don't know that. Thanks for pointing it out.

So, how can I disable autoupload then? 

Should I omit this command on `app/build.gradle` `apply from: "../../node_modules/@sentry/react-native/sentry.gradle"` ? is it safe?

**Comment by jennmueng** [comment]
Sorry for the late reply, I thought I had already replied! Yes, you can omit the `sentry.gradle` build step to stop sourcemaps if you wish to do so.
