### ISSUE TITLE
Question about install from git+https

### ISSUE THREAD

**Issue by ajp8164** [getsentry/sentry-react-native#1389]
**OS:**
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

**Platform:**
- [ x]  iOS
- [ x]  Android

**SDK:**
- [ x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 6a4bd7e2fe025cea3bf14554139926e392ee1e31

**`react-native` version:** 0.6.4

**Are you using Expo?**
- [ ]  Yes
- [ x]  No

**Are you using sentry.io or on-premise?**
- [ x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  release: '0.0.0',
  dist: '0',
  // other options
});
```
---
**I have following issue:**

Thanks for the merge of [1388](https://github.com/getsentry/sentry-react-native/pull/1388)!

Adding to package.json the following results in no dist dir. How can I grab the repo and have the dist dir built?

    "@sentry/react-native": "https://github.com/variant-inc/sentry-react-native#6a4bd7e2fe025cea3bf14554139926e392ee1e31",

**Steps to reproduce:**
- Change package.json
- npm i

**Actual result:**

No dist dir created

**Expected result:**

dist dir to be created

**Comment by ajp8164** [comment]
I suppose we can go on this recommendation until a new version is pushed to npm.

**Comment by jennmueng** [comment]
@ajp8164 You just need to run `yarn build` to get the dist directory.
