### ISSUE TITLE
Error bundle release android

### ISSUE THREAD

**Issue by lorenzoangelini** [getsentry/sentry-react-native#1390]
### Environment

I'm using the last version of react native,"react-native": "0.64.0",  and last version of sentry "@sentry/react-native": "^2.3.0" 

### Steps to Reproduce

I run bundleStagingRelease or assembleStagingRelease

### Expected Result
The bundle is created correctly 
### Actual Result
> Task :app:bundleStagingReleaseJsAndAssets_SentryUpload_-1898184413 FAILED
> Task :app:bundleStagingReleaseJsAndAssets_SentryUpload_-1898184415 FAILED
error: Found argument '-1' which wasn't expected, or isn't valid in this context
USAGE:
 sentry-cli react-native gradle [OPTIONS] --bundle <PATH> --dist <DISTRIBUTION>... --release <RELEASE> --sourcemap <PATH>

**Comment by jennmueng** [comment]
Closing this in favor of #1401

**Comment by zoontek** [comment]
@jennmueng I don't think this is the same issue. This one happen because a `-` is prepend here: `SentryUpload_-1898184413` (`Found argument '-1'`)

In my case, it fails with:

> Task :app:bundleDevelopmentReleaseJsAndAssets_SentryUpload_-868184591 FAILED
> error: Found argument '-8' which wasn't expected, or isn't valid in this context

**Comment by zoontek** [comment]
I got it, this is related to this change in RN 0.64:

```diff
output.versionCodeOverride =
-   versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
+  defaultConfig.versionCode * 1000 + versionCodes.get(abi)
```

**Comment by jennmueng** [comment]
@zoontek Hmm, as we just wrap the original build task: https://github.com/getsentry/sentry-react-native/blob/5fbd5ba6265431b3fc9a6d859aa36e6f1c1c406e/sentry.gradle#L69

 and take the original version code as is, then that means the original version code override is invalid in the first place right? I'm not too familiar with gradle myself.

**Comment by marandaneto** [comment]
@jennmueng do you know if we should do something about it?

**Comment by marandaneto** [comment]
sounds like its been fixed on RN itself https://github.com/facebook/react-native/pull/29808
closing it then -> https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle#L179-L180
