### ISSUE TITLE
Remove Threads list on the event if not an Android event

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1403]
In line with Flutter: https://github.com/getsentry/sentry-dart/blob/main/flutter/android/src/main/kotlin/io/sentry/flutter/SentryFlutterPlugin.kt#L199-L207

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/releases/tag/5.0.0-beta.7 does it, need to bump the SDK

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-java/issues/1473
