### ISSUE TITLE
TouchEventBoundary doesn't work in react-native 0.59

### ISSUE THREAD

**Issue by thainx** [getsentry/sentry-react-native#1408]
### Environment

react-native 0.59.10 (for private reasons I cannot update), RN Sentry SDK 2.3.0, SaaS

### Steps to Reproduce

1. Wrap the App with TouchEventBoundary
2. Press on any Touchable which triggers Sentry to send events

### Expected Result

A message is sent to Sentry with the press event being recorded as breadcrumb

### Actual Result

A message is indeed sent, but no press event recorded

### Additional information

I have tried the same Sentry SDK version with react-native 0.63 and it worked, but not with react-native 0.59. If any of you guys have ever run into this issue, how did you fix it? (can't update react-native though)

**Comment by jennmueng** [comment]
Thanks for notifying us, will investigate.

**Comment by marandaneto** [comment]
@thainx have you tried using the latest versions?
