### ISSUE TITLE
Cannot connect performance monitoring with react native

### ISSUE THREAD

**Issue by nwpnkmngm** [getsentry/sentry-react-native#1410]
Try to connect Performance monitoring by following Sentry document but still not working.

App.js 👇🏻

Sentry.init({
    dsn: "//.....",
    environment: __DEV__ ? "development" : "production",
    ignoreErrors: ['NSInvalidArgumentException: Application tried to present modally a view controller'],
    integrations: [
        new Sentry.ReactNativeTracing({
            routingInstrumentation: new Sentry.ReactNavigationV5Instrumentation()
        }),
    ],
    tracesSampleRate: 1.0
});

App navigator 👇🏻

const AppNavigator = ({ stack, url }) => {
    const navigation = useRef(null);
    return (
        <NavigationContainer ref={navigation} onReady={() =>   routingInstrumentation.registerNavigationContainer(navigation.current)}>
<AppStackNavigator url={url} /> 
        </NavigationContainer >
    )
}

Performance screen 👇🏻
![image](https://user-images.githubusercontent.com/48342930/111769500-e10ef000-88db-11eb-8388-2fc180ff74a5.png)

**Comment by jennmueng** [comment]
Those code snippets look incorrect, you would have to initialize the instrumentation outside, assign it to a variable, and use that variable in the `onReady`. You would also pass the whole ref `navigation` not `navigation.current`.

```js
import * as Sentry from "@sentry/react-native";

// Construct a new instrumentation instance. This is needed to communicate between the integration and React
const routingInstrumentation = new Sentry.ReactNavigationV5Instrumentation();

Sentry.init({
  ...
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      // ...
    }),
  ],
})

// Functional Component Example
const App = () => {
  // Create a ref for the navigation container
  const navigation = React.useRef();

  return (
    // Connect the ref to the navigation container
    <NavigationContainer
      ref={navigation}
      onReady={() => {
        // Register the navigation container with the instrumentation
        routingInstrumentation.registerNavigationContainer(navigation);
      }}>
      ...
    </NavigationContainer>
  );
};
```

https://docs.sentry.io/platforms/react-native/performance/included-instrumentation/#react-navigation-v5

**Comment by jennmueng** [comment]
Closing this for now, please let me know if issues pop up.

**Comment by lukebrandonfarrell** [comment]
I am having same issue, were you able to solve it @nwpnkmngm ?
