### ISSUE TITLE
Auto Sourcemap upload script on Xcode fails unless --force_foreground is present

### ISSUE THREAD

**Issue by nicomontanari** [getsentry/sentry-react-native#1424]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
React Native 2.3.0

### Description

At the end of the compilation procedure on Android the source maps are uploaded correctly, but with iOS the files are not uploaded on sentry and no errors are shown

#### Bundle React Native code and images code
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node
yarn buildTsCode
export ENTRY_FILE="artifacts/index.js"
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh

#### Upload Debug Symbols to Sentry
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym

**Comment by jennmueng** [comment]
What does `yarn buildTsCode` do, I assume it builds ts code into js? Can you pass `--verbose` to the `sentry-cli` command, and see what it logs?

```
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode --verbose ../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by nicomontanari** [comment]
Hi @jennmueng, `buildTsCode` is a custom script that i made to build the typescript code and do other actions.

I tried to put `--verbose` in the "Bundle React Native code and images code" script and these are the logs:
<img width="889" alt="Schermata 2021-03-25 alle 10 24 46" src="https://user-images.githubusercontent.com/15747776/112461127-ed71cd80-8d5f-11eb-9644-d45b91fcfe79.png">

**Comment by emirsavran** [comment]
Hi, probably same issue. I created an issue in sentry-cli repository. https://github.com/getsentry/sentry-cli/issues/932

**Comment by jennmueng** [comment]
Actually, that log looks familiar to something I've seen before. @nicomontanari 

Can you try passing `--force_foreground` to the cli command?

Also @emirsavran too.

**Comment by emirsavran** [comment]
> Actually, that log looks familiar to something I've seen before. @nicomontanari
> 
> Can you try passing `--force_foreground` to the cli command?
> 
> Also @emirsavran too.

Hi, actually `--force-foreground` flag worked well. Thanks for your help.

**Comment by nicomontanari** [comment]
> Actually, that log looks familiar to something I've seen before. @nicomontanari
> 
> Can you try passing `--force_foreground` to the cli command?
> 
> Also @emirsavran too.

Hi, i'm sorry for my absence. Everything works with `--force-foreground`. Thank you

**Comment by marandaneto** [comment]
@jennmueng I see it in our docs https://docs.sentry.io/platforms/react-native/troubleshooting/#ios-build-script-failed but should we rather fix it on CLI or RN SDK?

**Comment by jennmueng** [comment]
@marandaneto I think this is a fix that needs to be done on the CLI

**Comment by marandaneto** [comment]
@jennmueng should we always invoke the CLI with `--force-foreground`? we can patch the xcode script (via wizard), if the CLI already has such option, why would we need to fix it on the CLI? what was the motivation for doing it in the background actually in the first place? @jan-auer do you have context about that?

**Comment by marandaneto** [comment]
apparently this was an issue with sentry-cli and it should be solved by using the latest sentry-cli https://github.com/getsentry/sentry-cli/releases/tag/1.71.0

**Comment by majirosstefan** [comment]
Using 1.71.1 according to the 'yarn list' output, and the problem still persists.

**Comment by marandaneto** [comment]
> Using 1.71.1 according to the 'yarn list' output, and the problem still persists.

thanks, gonna check with the CLI team https://github.com/getsentry/sentry-cli/issues/932#issuecomment-986658868

**Comment by marandaneto** [comment]
@kamilogorek is checking this out.

**Comment by kamilogorek** [comment]
Should be fixed once https://github.com/getsentry/sentry-react-native/pull/2016 is release.
