### ISSUE TITLE
Compatibility with React Native 0.64.0

### ISSUE THREAD

**Issue by Chrischuck** [getsentry/sentry-react-native#1425]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
React Native 2.3.0

### Steps to Reproduce

1. Upgraded from 1.0.9 to 2.30
2. Re-linked sentry module

### Expected Result

Sentry would not error out

### Actual Result

Sentry errors out (two different issues for android and ios)

Initialization for both ios and android:
```
'use strict';

import { AppRegistry } from 'react-native';
import Config from 'react-native-config';
import * as Sentry from '@sentry/react-native';
import Index from './build';

Sentry.init({
  dsn: 'XXX',
  debug: true,
  beforeSend(event) {
    if (!__DEV__) {
      return event;
    }
    return null;
  },
});

Sentry.setTag('environment', Config.ENV);

AppRegistry.registerComponent('app', () => Index);
```
Android errors out with:
```
 Sentry Logger [Error]: SentryError: `beforeSend` returned `null`, will not send event.
```

Ios errors out with:
```
Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' was thrown while invoking fetchRelease on target RNSentry with params (
    1158,
    1159
)
```

If I remove `beforeSend` from the initialization object, the error disappears from android. If I remove all sentry related code from ios, the error disappears from ios.

Simply doing:
```
Sentry.init({
  dsn: 'XXX',
});
```
fails for ios

**Comment by jennmueng** [comment]
Your Android code is exactly what you have it set up to do. You're returning `null` from `beforeSend` which will not send the event. And on iOS looks like you did not re-install cocoa pods because it's trying to call an old method that no longer exists in the newer version. You can do this by doing

```bash
cd ios
pod repo update
pod install
```

None of this is related to 0.64 by the way, so let's close this for now. Please let me know if your issues persist otherwise.

**Comment by Chrischuck** [comment]
@jennmueng Hmm, I guess I was missing `pod repo update` and the android error magically went away. Thanks for the help!
