### ISSUE TITLE
Source code was not found. The maximum number of remote source requests was made.

### ISSUE THREAD

**Issue by davinctor** [getsentry/sentry-react-native#1435]
### Environment

How do you use Sentry?
**Sentry SaaS**

Which SDK and version?
`@sentry/react-native: ^2.4.0`

### Steps to Reproduce
1. My `Sentry.init`:

    <img width="492" alt="Screenshot 2021-03-29 at 21 33 11" src="https://user-images.githubusercontent.com/6543359/112883007-5ea1df80-90d6-11eb-97d0-79153fbf859f.png">
    
2. `react-native bundle  --dev false  --platform android  --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map`

3. `yarn sentry-cli releases files  {BUNDLE_ID}-MAIN-1.3.5077-TEST-v15 upload-sourcemaps --dist 135077  --strip-prefix . --rewrite index.android.bundle index.android.bundle.map`

4. The artifacts are on the place:

    <img width="716" alt="Screenshot 2021-03-29 at 21 40 56" src="https://user-images.githubusercontent.com/6543359/112883853-7332a780-90d7-11eb-9804-8d6e5bb63fad.png">

### Actual Result

The source code is displaying but not the same way as the ios (see Expected Result):
    <img width="605" alt="Screenshot 2021-03-29 at 21 50 20" src="https://user-images.githubusercontent.com/6543359/112884919-c3f6d000-90d8-11eb-88ef-11ed5489c84e.png">

### Expected Result

The what I should see at the dashboard page for particular issue (it's my iOS app report):
    <img width="596" alt="Screenshot 2021-03-29 at 21 51 24" src="https://user-images.githubusercontent.com/6543359/112885039-ea1c7000-90d8-11eb-8379-79281eeb022b.png">

### Details

1. Result of `react-native bundle  --dev false  --platform android  --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map`

    <img width="1218" alt="Screenshot 2021-03-29 at 21 39 13" src="https://user-images.githubusercontent.com/6543359/112883633-3666b080-90d7-11eb-8c39-54769d2cfb16.png">

2. Result of `yarn sentry-cli releases files  {BUNDLE_ID}-MAIN-1.3.5077-TEST-v15 upload-sourcemaps --dist 135077  --strip-prefix . --rewrite index.android.bundle index.android.bundle.map`

    <img width="505" alt="Screenshot 2021-03-29 at 21 46 47" src="https://user-images.githubusercontent.com/6543359/112884517-44690100-90d8-11eb-8556-8a21e14aeeaf.png">

3. `There were 545 errors encountered while processing this event`:
    <img width="610" alt="Screenshot 2021-03-29 at 21 53 28" src="https://user-images.githubusercontent.com/6543359/112885249-336cbf80-90d9-11eb-978c-dedcba457147.png">

P.S.
I have checked these threads:
 - https://github.com/getsentry/sentry-react-native/issues/79
 - https://github.com/getsentry/sentry-fastlane-plugin/issues/44
 - https://github.com/getsentry/sentry-react-native/issues/1385

Links:
 - https://docs.sentry.io/platforms/react-native/manual-setup/hermes/
 - https://docs.sentry.io/platforms/react-native/manual-setup/codepush/
 - https://docs.sentry.io/platforms/react-native/manual-setup/sourcemaps/

**Comment by jennmueng** [comment]
Are you using hermes? Have you tried https://github.com/getsentry/sentry-react-native/issues/761#issuecomment-587498344?

**Comment by davinctor** [comment]
@jennmueng Thank you for your reply, it is working for me with that solution in the comment. But I still have a lot of issues on the sentry issue page around 300. Right now it's not critical because I still can see the crash origin place but anyway it's weird.
