### ISSUE TITLE
import sentry NOT FOUND

### ISSUE THREAD

**Issue by ControlAndC** [getsentry/sentry-react-native#1436]
### Environment
I am using react-native version     "react-native": "^0.59.10" and version of sentry.

Which SDK and version?
Version i am using is  "react-native-sentry": "0.43.2".

I tried linking the library using manual linking and every time it says "MODULE 'sentry' not found.

@import Sentry;

![image](https://user-images.githubusercontent.com/5564601/113160941-8f5f5180-925b-11eb-9907-02a28334eaae.png)

Please help, I am missing deadline.

**Comment by jennmueng** [comment]
@ControlAndC Please update to the latest version as I see you're on the very old `0.43.2` version. And following the [installation guide over on our docs.](https://docs.sentry.io/platforms/react-native/)

**Comment by jennmueng** [comment]
Closing this as it is an old version and as there has not been a reply.

**Comment by ninjz** [comment]
> ### Environment
> I am using react-native version "react-native": "^0.59.10" and version of sentry.
> 
> Which SDK and version? Version i am using is "react-native-sentry": "0.43.2".
> 
> I tried linking the library using manual linking and every time it says "MODULE 'sentry' not found.
> 
> @import Sentry;
> 
> ![image](https://user-images.githubusercontent.com/5564601/113160941-8f5f5180-925b-11eb-9907-02a28334eaae.png)
> 
> Please help, I am missing deadline.

Did you ever figure this out?

**Comment by lucas-zimerman** [comment]
I got something similar on Cordova that got fixed when I solved the warnings (I think it was fixed by updating the minimun iOS version.)
