### ISSUE TITLE
sentry-cli was not installed by @sentry/cli install script

### ISSUE THREAD

**Issue by mohity777** [getsentry/sentry-react-native#1437]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. What
2. you
3. did.

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by jennmueng** [comment]
Can you try manually adding `@sentry/cli` as a dependency and see if that fixes your issue? `yarn add @sentry/cli`

**Comment by mohity777** [comment]
uninstalling and then reinstalling @sentry/react-native lib resolved my issue.
