### ISSUE TITLE
sentry.gradle script not compatible with Gradle > 6.5

### ISSUE THREAD

**Issue by radko93** [getsentry/sentry-react-native#1446]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"@sentry/react-native": "^2.4.0"

### Steps to Reproduce
1. `sentry.properties` file is not specified or missing config
2. Use Gradle newer than 6.5 in `gradle-wrapper.properties`

### Expected Result

Process is successful.

### Actual Result

1. Sentry crashes with `java.lang.IllegalArgumentException: Illegal null value provided in this collection:  [--url, null, --auth-token, null, react-native, gradle, ...`

**Comment by cKurultayKalkan** [comment]
+1

**Comment by marandaneto** [comment]
@cKurultayKalkan have you tried using the latest versions of the SDK?

our samples use Gradle 6.9.x and it works https://github.com/getsentry/sentry-react-native/blob/master/sample/android/gradle/wrapper/gradle-wrapper.properties

**Comment by radko93** [comment]
I don't have this issue anymore.
