### ISSUE TITLE
Sentry.ReactNativeTracing with Firestore

### ISSUE THREAD

**Issue by 345ml** [getsentry/sentry-react-native#1448]
This may be more of a question than a feature request.
I apologize.

The app I'm developing relies heavily on Firebase and uses Firestore for the DB.

I am setting up Sentry tracing with the following code.

```js
const routingInstrumentation = new Sentry.ReactNavigationV4Instrumentation();

Sentry.init({
  dsn: "dsn",
  tracesSampleRate: 0.2,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation: routingInstrumentation,
      tracingOrigins: [
        "firestore.googleapis.com", // Database
      ],
      // ... other options
    }),
  ],
});
```

This seems to be working well.

<img width="1013" alt="Screen Shot 2021-04-12 at 17 32 21" src="https://user-images.githubusercontent.com/8254811/114365113-fb309c80-9b2e-11eb-948d-27afb16cabb3.png">

We use react-native-firebase to call Firestore.
What I'm hoping to find out is which queries are taking longer, for example.

Is there a good way to achieve this goal?
Like wrapping the database call and embedding code to manually instrument the transaction?

**Comment by jennmueng** [comment]
@345ml This would not work as the Firebase SDK performs all of its api calls on the native layer, and not the JS layer. I had this issue too when working on my React Native app that uses Firebase, so I made this blogpost that would give you an idea of how to implement performance tracing for Firestore: https://blog.sentry.io/2021/03/11/performance-monitoring-support-for-react-native

Let's close this issue for now.

**Comment by 345ml** [comment]
Thanks, @jennmueng !!!
