### ISSUE TITLE
Support setting `maxCacheItems` on Android

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1452]
Supported on iOS as it just takes the JSON object

**Comment by marandaneto** [comment]
on Android we have 2 config though.
`cacheDirSize` defaults to 30 and `maxQueueSize` defaults to 30 too

**Comment by jennmueng** [comment]
@marandaneto Oh yes I was referring to `cacheDirSize`, mistakingly assumed they had the same keys on Cocoa and Android.

I see that Flutter uses `cacheDirSize` but it's only for Android?

Should we unite them into just a single key on the JS side, have it be passed to iOS as `maxCacheItems` and have it set `cacheDirSize` on Android?

**Comment by marandaneto** [comment]
keep using the old one, we've to rename it on Android, see https://github.com/getsentry/sentry-java/issues/1162
