### ISSUE TITLE
environment option not working

### ISSUE THREAD

**Issue by geniuscva** [getsentry/sentry-react-native#1455]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

### Steps to Reproduce

1.  Config App.js with environment option

`Sentry.init({
  environment: 'staging',
  dsn: 'https://xxx,
});`

2. Build android release 

### Expected Result

staging option in Releases build

### Actual Result

no staging option in Releases, only production

![image](https://user-images.githubusercontent.com/46478820/115008084-e9574c80-9ed4-11eb-8806-7efadab25f38.png)

**Comment by jennmueng** [comment]
@geniuscva Did you send an event from the SDK under the new environment? If yes, is the environment tag set on the event correct?
<img width="247" alt="Screen Shot 2021-04-17 at 2 32 59 PM" src="https://user-images.githubusercontent.com/30991498/115105537-d18dd000-9f89-11eb-83c3-9f738badd63e.png">

**Comment by geniuscva** [comment]
> @geniuscva Did you send an event from the SDK under the new environment? If yes, is the environment tag set on the event correct?
> <img alt="Screen Shot 2021-04-17 at 2 32 59 PM" width="247" src="https://user-images.githubusercontent.com/30991498/115105537-d18dd000-9f89-11eb-83c3-9f738badd63e.png">

I tried to send an error event and now it's works. My 'staging' tag shown.
Is there any way to tag a release on the first build without sending an event

**Comment by jennmueng** [comment]
@geniuscva By "tag a release" I'm not quite sure what you mean, can you please clarify? Nevertheless, environments can only get created when an event comes in with the new environment set: https://docs.sentry.io/product/sentry-basics/environments/.

Closing this as the original issue is solved.
