### ISSUE TITLE
Sentry.setTag() doesn't report tags for events all the time

### ISSUE THREAD

**Issue by siddhisuthar** [getsentry/sentry-react-native#1458]
I tried:
```
Sentry.init({
dsn: SENTRY_DSN
});
Sentry.configureScope(scope => scope.setUser({ id: ‘’}));  //clear automatically set user
```
after I get the userID
`Sentry.setTag("loggedInUser", userID)`

I see loggedInUser reported only for a few events, not all. Same is the case when I try to overwrite the automatically set user:
`Sentry.setUser({ id: userID });`

What am I doing wrong?

**Comment by jennmueng** [comment]
That is not the correct way to set the user, `Sentry.setUser("id", userID);`. Please use the correct methods as stated on the docs: https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/

Please try using the correct methods and also provide the version of the SDK you are using.

**Comment by siddhisuthar** [comment]
I'm on @sentry/react-native@2.3.0 
Sorry, that was a typo in my question. I've updated it. 
But I've tried both: 
```
  Sentry.setUser({ id: userID });
  Sentry.setTag("loggedInUser", userID);
```
 I noticed that only some of the crash events come with a loggedInUser tag or a User (with ID).

**Comment by svenlombaert** [comment]
I am encountering the same problem on @sentry/react-native 2.4.2

The tags are always set on iOS, but never for events on Android. I set them like below:

```typescript
Sentry.setUser({
    id: userId,
});

Sentry.setTags({
    deviceUUID: DeviceInfo.getUniqueId(),
    deviceId,
});
```

Also tried setting them inside `Sentry.configureScope()`, but that didn't resolve the problem.

**Comment by siddhisuthar** [comment]
I'm seeing this issue even for iOS platform. In most cases, the tag/user is set to device's ip instead of userID

**Comment by marandaneto** [comment]
@siddhisuthar @svenlombaert tags need to be only String, could it be that you are calling with non String types?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

ps: works on latest RN SDK on Android and iOS
