### ISSUE TITLE
Native SDK still trying to initialize after passing `enableNative: false`

### ISSUE THREAD

**Issue by cruzach** [getsentry/sentry-react-native#1461]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"@sentry/react-native": "^2.4.1"

### Steps to Reproduce

1. init new react-native project
2. call 
```
Sentry.init({
  enableNative: false,
  enableNativeNagger: false,
  enableNativeCrashHandling: false,
  autoInitializeNativeSdk: false,
});
``` 

(there's a lot of native options so i just disabled them all)

### Expected Result

no error

### Actual Result

`SentryError: Native Client is not available, can't start on native.`

**Comment by jennmueng** [comment]
If you pass `autoInitializeNativeSdk: false` it currently assumes that you will initialize a native SDK on your own and it won't disable the native bridge calls: https://github.com/getsentry/sentry-react-native/blob/c179178485ca7ea2ffce184a2bc6cba334f97c85/src/js/wrapper.ts#L88-L92

Hmm but regardless I think it should prioritize `enableNative: false`. Will fix this.

**Comment by cruzach** [comment]
@jennmueng , sorry but I think there's still a bug here-
```
Sentry.init({
  enableNative: false,
});
```

Results in a redbox error : `SentryError: Native Client is not available, can't start on native.`

**Comment by jennmueng** [comment]
@cruzach Hmmm that should work with no issue..let me try to reproduce and will get back to you in a minute.

**Comment by jennmueng** [comment]
@cruzach I just tried it with the latest version on the master branch and disabling the native SDK via 
```js
Sentry.init({
  enableNative: false,
  enableNativeNagger: false,
});
```
works fine. Are you sure you have the latest build? Note that we haven't made the release (2.4.2) for this yet as we have an issue with CI.

**Comment by cruzach** [comment]
Installing the `master` branch still results in the `Native Client is not available, can't start on native.` error for me (testing on iOS)

**Comment by jennmueng** [comment]
@cruzach The error occurs for you right on init right? Or does it occur afterwards (sending an event, setting a scope property etc)? 

I'm testing on iOS simulator from the `master` as well, tried resetting the React Native packager cache with `--reset-cache`, rebuilt the SDK, set `RNSentry` to `undefined` to simulate the Native Client not existing, and I could not reproduce that error. Also tried sending events, setting scope, native crash, and no error is thrown.

**Comment by cruzach** [comment]
Oh I figured it out- after it wasn't working before with `autoInitializeNativeSdk`, I was just trying again **without the DSN key in init**. It looks like, for whatever reason, that causes the problem.

i.e. this works:
```
Sentry.init({
  dsn: "dsn here",
  enableNative: false,
  enableNativeNagger: false,
});
```

this fails with `Native Client is not available, can't start on native.`
```
Sentry.init({
  enableNative: false,
  enableNativeNagger: false,
});
```

Sorry about the goose chase!
