### ISSUE TITLE
react-navigation non-serializable state recursive call to `dropUndefinedKeys`

### ISSUE THREAD

**Issue by Krisztiaan** [getsentry/sentry-react-native#1477]
### Environment

`sentry.io`
`"@sentry/react-native": "^2.4.0"`
`react-navigation`

### Steps to Reproduce

1. Pass a circular object as a `param` to a navigation call

### Expected Result

Navigation successful, something's logged in Sentry

### Actual Result

RangeError, call stack size exceeded in `dropUndefinedKeys`

**Comment by lachenmayer** [comment]
Can confirm this is still an issue.

**Comment by Krisztiaan** [comment]
Still an issue, Mr. Bot Sir!

**Comment by marandaneto** [comment]
thanks for reporting, can one of you share a code snippet that causes the issue? thanks

**Comment by Krisztiaan** [comment]
Use `react-navigation`
```ts
  const paramsToPass = {
    something: 'foo',
    self: undefined,
  };
  paramsToPass.self = paramsToPass
  navigate('somewhere', paramsToPass)
```

**Comment by marandaneto** [comment]
I can confirm:

 

> WARN  Non-serializable values were found in the navigation state. Check:
> 
> ManualTracker > params.self (Circular reference)
> 
> This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details. 
>     at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:108134:28)
>     at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:112128:21)
>     at NavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:112034:26)
>     at Provider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:104925:21)
>     at App (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:104751:34)
>     at ReactNativeProfiler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:132017:36)
>     at RCTView
>     at View
>     at __Sentry.TouchEventBoundary (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:143539:36)
>     at RootApp
>     at RCTView
>     at View
>     at RCTView
>     at View
>     at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=io.sentry.sample:68798:36)

also:

>  WARN  0 [RangeError: Maximum call stack size exceeded (native stack depth)]

**Comment by marandaneto** [comment]
@jennmueng can you take a look at this, thanks.

**Comment by marandaneto** [comment]
For Sentry JS SDK 7.x https://github.com/getsentry/sentry-docs/pull/4844

**Comment by marandaneto** [comment]
Closed in favor of https://github.com/getsentry/sentry-javascript/issues/4777
