### ISSUE TITLE
Android source maps not being uploaded with gradle

### ISSUE THREAD

**Issue by osamaarefm** [getsentry/sentry-react-native#1488]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-expo: 3.1.0
@sentry/react-native: 2.4.2

### Steps to Reproduce
Setup: expo bare workflow, build using EAS which uses gradle command.

1. Use sentry wizard to config iOS & Android projects
2. Build Android project (using gradle command **assembleRelease**)
3. Checking Gradle logs. They do not mention anything about sentry uploading anything.
4. Generate a crash on the app. Sentry dashboard shows:

### Expected Result

Sourcemaps should be uploaded on Sentry for both iOS and Android. Gradle logs should indicate this for Android.

### Actual Result
iOS builds successfully upload sourcemaps and they work fine. But for Android they're missing:

![image](https://user-images.githubusercontent.com/48062944/116879724-0bb9cb80-ac32-11eb-8396-8623067c16f0.png)

![image](https://user-images.githubusercontent.com/48062944/116879810-32780200-ac32-11eb-94b3-9bc5a54e6690.png)

### Code snippets
**build.grade:**
```
project.ext.react = [
    enableHermes: false
]

apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"

.....
dependencies {
    ......
    addUnimodulesDependencies()

    implementation project(':@sentry_react-native')
    .....
}
```

**settings.gradle:**
```
rootProject.name = .......
include ':@sentry_react-native'
project(':@sentry_react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@sentry/react-native/android')
```

**MainApplication.java:**
```
import io.sentry.react.RNSentryPackage;
...
....
    @Override
    protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
      return packages;
    }
```

**sentry.properties:**

```
defaults.url=https://sentry.io/
defaults.org=xxxxxxx
defaults.project=xxxxxx
auth.token=xxxxx
```

Any idea why uploading sourcemaps doesnt get triggered?

**Comment by valeriashpiner** [comment]
@osamaarefm in your `gradle.properties` did you set `org.gradle.configureondemand=false`?

**Comment by osamaarefm** [comment]
@valeriashpiner Yeah I've already done that, it didnt make a difference.

**Comment by osamaarefm** [comment]
Here are the gradle logs, just in case:
```
> Task :unimodules-react-native-adapter:bundleLibResRelease
> Task :unimodules-react-native-adapter:mergeReleaseNativeLibs NO-SOURCE
> Task :unimodules-react-native-adapter:stripReleaseDebugSymbols NO-SOURCE
> Task :unimodules-react-native-adapter:copyReleaseJniLibsProjectOnly
> Task :app:copyReleaseExpoManifest
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere
info Writing bundle output to:, /build/workingdir/build/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /build/workingdir/build/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 69 asset files
info Done copying assets
> Task :app:copyReleaseBundledJs
> Task :app:generateReleaseResValues
> Task :app:generateReleaseResources
```
For some reason, the task `bundleReleaseJsAndAssets_SentryUpload` is not running after `bundleReleaseJsAndAssets`, that's what I don't get.

**Comment by osamaarefm** [comment]
Actually @valeriashpiner you were right. I'm using EAS build service, and I found out that it uses its own `gradle.properties`, and it has `configureondemand` as true. I need to check with EAS team instead. Apologies for that.

Thanks for your help!
