### ISSUE TITLE
captureMessage, captureException not working on Android

### ISSUE THREAD

**Issue by fragilehm** [getsentry/sentry-react-native#1490]
### Environment

On Android, only the native crashes are appearing in the sentry dashboard. 
`captureMessage`, `captureException` are not being registered,

How do you use Sentry?

```"react-native": "0.63.4"```

Which SDK and version?
```"@sentry/react-native": "^2.4.1"```

### Steps to Reproduce

Capture the exception on Android -> `Sentry.captureException(error, {})`

### Expected Result

Appear on Sentry dashboard.

### Actual Result

Not appearing on sentry.

on iOS everything works as expected, but on Android, only the native crashes are appearing.

**Comment by jennmueng** [comment]
@fragilehm Can you pass `debug: true` to your Sentry.init call while on Android and paste the logs?

**Comment by fragilehm** [comment]
@jennmueng  These logs appear after initialization,  but nothing after sending the error message.

```
Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
logger.js:32 Sentry Logger [Log]: Integration installed: Release
logger.js:32 Sentry Logger [Log]: Integration installed: InboundFilters
logger.js:32 Sentry Logger [Log]: Integration installed: FunctionToString
logger.js:32 Sentry Logger [Log]: Integration installed: Breadcrumbs
logger.js:32 Sentry Logger [Log]: Integration installed: LinkedErrors
logger.js:32 Sentry Logger [Log]: Integration installed: UserAgent
logger.js:32 Sentry Logger [Log]: Integration installed: DebugSymbolicator
logger.js:32 Sentry Logger [Log]: Integration installed: RewriteFrames
logger.js:32 Sentry Logger [Log]: Integration installed: DeviceContext
```

**Comment by jennmueng** [comment]
@fragilehm If it works on iOS and not on Android, I'm surprised no error messages show up. This means the native bridge should be initialized correctly especially if native crashes are captured. Can you check the logcat logs: `adb logcat -s Sentry` and `adb logcat -s react-native-sentry` and see if anything is logged when trying to send an event? I would try clearing the Android build cache: `./gradlew clean` and rebuilding the Android app, or reinstalling Sentry.

**Comment by fragilehm** [comment]
@jennmueng don't see anything logged after sending the error, but this might be helpful
![image](https://user-images.githubusercontent.com/20160573/116999648-32364000-ace0-11eb-998a-59a489b51e0a.png)

**Comment by fragilehm** [comment]
@jennmueng any updates ?

**Comment by jennmueng** [comment]
@fragilehm  Can you get the event by passing `beforeSend: (event) => {console.log(event)}` to `Sentry.init` and get me the event? Maybe there's a bad field getting attached to the event. I assume a reinstall does not fix the issue?

**Comment by fragilehm** [comment]
@jennmueng 

![image](https://user-images.githubusercontent.com/20160573/117206026-a19c5480-adf2-11eb-94a5-4cf0a981e0a0.png)

**Comment by jennmueng** [comment]
@fragilehm `tags.deviceInfo` is an object, did you set that tag? Tags can only be strings.

**Comment by fragilehm** [comment]
@jennmueng not sure if that is related, here you can see the native crash (probably the object is auto stringified)

![image](https://user-images.githubusercontent.com/20160573/117450072-0c5ba600-af41-11eb-81bf-d459cbf626cd.png)

**Comment by jennmueng** [comment]
@fragilehm The object is auto-stringified when passed to the native layer for native crashes, but it is not when JS events are passed down. Please remove the object. We will most likely add a warning or error instead of auto-stringifying it as that code should only auto-stringify primitives.

**Comment by fragilehm** [comment]
@jennmueng thanks this fixed the issue indeed, tho we had the same for ios and it showed:
![image](https://user-images.githubusercontent.com/20160573/124545791-edd33780-de29-11eb-912a-de2128428fb3.png)

Closing the issue.
