### ISSUE TITLE
403 Forbidden @ dl.bintray.com

### ISSUE THREAD

**Issue by astout** [getsentry/sentry-react-native#1492]
### Environment

How do you use Sentry?

- Sentry SaaS (sentry.io)

Which SDK and version?

`@sentry/react-native 1.3.3` (upgraded to `1.9.0` while troubleshooting)

### Steps to Reproduce

1. CI (Bitrise) builds of React Native app worked up until today
  * Even re-running old builds that were successful previously are now failing

### Expected Result

Android App is able to build with RNSentry

### Actual Result

Android App is unable to build with RNSentry

From build logs:

__File `raw-gradle-output.log`__

```txt
Caused by: org.gradle.api.resources.ResourceException: Unable to load Maven meta-data from https://dl.bintray.com/getsentry/sentry-android/com/facebook/react/react-native/maven-metadata.xml.
```

__File `build.gradle`__

```
...
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven {
            url = "https://dl.bintray.com/getsentry/sentry-android"
        }

        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
...
```

**References**
  * https://github.com/getsentry/sentry-android/issues/270
  * https://github.com/getsentry/sentry-react-native/issues/767
  
The above references recommend `dl.bintray.com` domain for maven, but currently `dl.bintray.com` domain is all `403 Forbidden`. It looks like the service has been sunset by JFrog. Is there an alternative source for the maven resources?

**Comment by astout** [comment]
It looks like it may have been some kind of outage, I don't fully understand how the maven resource fetching works, I'm still unable to manually fetch the resource mentioned above, but my CI (Bitrise) seems to be able to create the Android bundle now. My iOS build is currently not working, but this particular issue seems to have remedied itself for now.

**Comment by kg-currenxie** [comment]
I'm getting this too today. Maybe it's an outage, but they don't seem to have any issues according to their status page. Also, they are still shutting down soon-ish. Still need this to be available somewhere else.
