### ISSUE TITLE
[SouceMaps] No ability to specify custom release value for sentry.gradle script & xcode build phase

### ISSUE THREAD

**Issue by retyui** [getsentry/sentry-react-native#1499]
### Problem 

I init Sentry with the next params in our app :

```tsx
Sentry.init({
  release: '1.2.3', // instead of 'com.my.app@1.2.3+1221'
  dist: '1221',
});
```

But when I bundle release a task `bundleReleaseJsAndAssets_SentryUpload` invoke next  command: 

```sh
"/mur/node_modules/@sentry/cli/sentry-cli" \
  "--log-level" "debug" "react-native" "gradle" \
  "--bundle" "/mur/android/app/build/generated/assets/react/release/index.android.bundle" \
  "--sourcemap" "/mur/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map" \
  "--release" "com.my.app@1.2.3+1221" \
  "--dist" "1221"
```

I check the source code of `sentry.gradle` + `react_native_xcode.rs` and find that `releaseName` value hardcoded and no way to change it :

https://github.com/getsentry/sentry-react-native/blob/2612b4dafc08c034a12dd6bc38f7148a3004cbf5/sentry.gradle#L168

https://github.com/getsentry/sentry-cli/blob/d63a0b2ce9c033f5bc1c35bc1405d7719e29e969/src/commands/react_native_xcode.rs#L277-L289

### Feature Request

I suggest create env or config support

1) [Android] Using `sentryCli` config

```gradle
project.ext.sentryCli = [
    logLevel: "debug",
    release: '1.2.3',                                                                 // specific value
    getRelease: variant => "${variant.getVersionName()}"    // or function that return value
]
``` 

2) [iOS + Android] Env variable :

```sh
export SENTRY_RELEASE_NAME="1.2.3"
```

**Comment by retyui** [comment]
https://github.com/getsentry/sentry-cli/blob/d63a0b2ce9c033f5bc1c35bc1405d7719e29e969/src/commands/react_native_xcode.rs#L277-L289

**Comment by jennmueng** [comment]
Closing this in order to consolidate to https://github.com/getsentry/sentry-react-native/issues/1229, and also pinning it to make this higher priority.
