### ISSUE TITLE
Android: increase compileSdkVersion to 30

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#1512]
We want to move to java 11  in our project updating these lines:
sourceCompatibility JavaVersion.VERSION_1_8

We have a build error because some libs like sentry-react-native are still compiling with < 30 like:
compileSdkVersion safeExtGet('compileSdkVersion', 28)

Error:
In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

So please compile with 30 so that we can do our update.

Maybe also even switch to:
sourceCompatibility JavaVersion.VERSION_11

**Comment by pvegh** [comment]
When is next?

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/releases/tag/3.0.2
