### ISSUE TITLE
Android: Upgrade buildToolsVersion to 30.0.2

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#1515]
Currently an old version is used:
buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')

Which causes a warning, spamming the build output:
The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.0.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

Please update it to 30.0.2 fixing this warning or removing it should also work.

**Comment by pvegh** [comment]
It's an easy fix, please improve your product

**Comment by pvegh** [comment]
It's 3 major versions behind.
Please fix this warning for all of us soon!

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/releases/tag/3.0.2
