### ISSUE TITLE
autoInitializeNativeSdk is broken on Android

### ISSUE THREAD

**Issue by vovkasm** [getsentry/sentry-react-native#1516]
### Environment

How do you use Sentry?

Sentry SaaS (sentry.io)

Which SDK and version?

@sentry/react-native@2.4.2

### Steps to Reproduce

We initialize Android sentry SDK in MainApplication to properly catch early native errors, because of this we set `autoInitializeNativeSdk` to `false` on JS side.

### Expected Result

Events properly sent to sentry server.

### Actual Result

No event sent to server. Error from console:
```
react-native-sentry: Error reading envelope
```

It is because of [RNSentryModule.captureEnvelope](https://github.com/getsentry/sentry-react-native/blob/2.4.2/android/src/main/java/io/sentry/react/RNSentryModule.java#L191) trying to get path from private `sentryOptions` variable, that can be settled only from `startWithOptions` which skipped because of `autoInitializeNativeSdk`.

### Suggestion fix

May be we can factor out native initialization code to singleton that can be accessed from native application side, so application will call it before RN module initialized?

**Comment by jennmueng** [comment]
Fixed in release [2.4.3](https://github.com/getsentry/sentry-react-native/releases/tag/2.4.3) by using the latest outbox path from the sdk instead of a cached options instance.
