### ISSUE TITLE
App Crashing with SIGABRT: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'n.default.init') Open  Open

### ISSUE THREAD

**Issue by mljlynch** [getsentry/sentry-react-native#1530]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io

Which SDK and version?
@sentry/react-native: 2.3.0

### Steps to Reproduce

- Add an environment variable to configure when to init sentry
- App builds locally and runs on simulator
- App crashes when deployed via app center with the following issues:

```txt
SIGABRT: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'n.default.init')
```

**Comment by jennmueng** [comment]
@mljlynch You are initializing the SDK wrong it looks like. You are using a default import, but you need to use `import * as Sentry from "@sentry/react-native"`.

**Comment by mljlynch** [comment]
Thanks!
