### ISSUE TITLE
Add React native as Runtime (name and version)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#1558]
The SDK should include runtime and version.

For example, Unity:

![image](https://user-images.githubusercontent.com/1633368/120344147-52e5bb80-c2c7-11eb-8a84-88babbc538db.png)

Related to: https://github.com/getsentry/sentry-capacitor/issues/38

**Comment by marandaneto** [comment]
Similar to https://github.com/getsentry/sentry-dart/issues/416

**Comment by krystofwoldrich** [comment]
Related to the dependencies metadata, as RN is dep of the application. https://github.com/getsentry/team-mobile/issues/54

**Comment by marandaneto** [comment]
@krystofwoldrich Maybe you can close this one then and add a note on https://github.com/getsentry/team-mobile/issues/54
Since they are sort of a dupe for RN at least, unless you can tackle this one first in an easier way.

**Comment by krystofwoldrich** [comment]
I'm not aware of a simpler solution than reading the deps, therefore I will close this issue.
