### ISSUE TITLE
Errors reported to Sentry, but stack trace is all "Unknown"

### ISSUE THREAD

**Issue by mtimofiiv** [getsentry/sentry-react-native#1559]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`sentry.javascript.react-native` v. `2.4.2`

### Steps to Reproduce

I have no idea.

 * React-Native app, ejected from Expo SDK 41
 * I am running `expo publish --release-channel release` to create a release 

### Expected Result

I would look at the log entry and happily continue debugging.

### Actual Result

Here's what I'm seeing in the Sentry dashboard:

<img width="870" alt="Screenshot 2021-06-02 at 12 07 23" src="https://user-images.githubusercontent.com/428948/120426882-6d1fa800-c360-11eb-950a-78d73a0b0f77.png">

This makes sense since  here's what the stack trace looks like:

```
Error: Text strings must be rendered within a <Text> component.
  at ai(app:///de6b708ef4031fd66a9ac4afafdfa031:106:54895)
  at Nl(app:///de6b708ef4031fd66a9ac4afafdfa031:106:74917)
  at Cl(app:///de6b708ef4031fd66a9ac4afafdfa031:106:74806)
  at Rl(app:///de6b708ef4031fd66a9ac4afafdfa031:106:74659)
  at Pl(app:///de6b708ef4031fd66a9ac4afafdfa031:106:74426)
  at Tl(app:///de6b708ef4031fd66a9ac4afafdfa031:106:71559)
  at Tl([native code])
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:106:23573)
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:209:3883)
  at an(app:///de6b708ef4031fd66a9ac4afafdfa031:106:23520)
  at ln(app:///de6b708ef4031fd66a9ac4afafdfa031:106:23455)
  at ml(app:///de6b708ef4031fd66a9ac4afafdfa031:106:68245)
  at Ir(app:///de6b708ef4031fd66a9ac4afafdfa031:106:43539)
  at Ir([native code])
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:662:2509)
  at y(app:///de6b708ef4031fd66a9ac4afafdfa031:14:587)
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:14:1890)
  at y(app:///de6b708ef4031fd66a9ac4afafdfa031:14:587)
  at o(app:///de6b708ef4031fd66a9ac4afafdfa031:14:1066)
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:14:1209)
  at f(app:///de6b708ef4031fd66a9ac4afafdfa031:49:155)
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:49:864)
  at y(app:///de6b708ef4031fd66a9ac4afafdfa031:137:581)
  at C(app:///de6b708ef4031fd66a9ac4afafdfa031:137:947)
  at callImmediates(app:///de6b708ef4031fd66a9ac4afafdfa031:137:3004)
  at value(app:///de6b708ef4031fd66a9ac4afafdfa031:37:2919)
  at ? (app:///de6b708ef4031fd66a9ac4afafdfa031:37:1095)
  at value(app:///de6b708ef4031fd66a9ac4afafdfa031:37:2611)
  at value(app:///de6b708ef4031fd66a9ac4afafdfa031:37:1065)
  at value([native code])
  at value([native code])
```

The release artefacts are being sent correctly:

<img width="977" alt="Screenshot 2021-06-02 at 12 10 34" src="https://user-images.githubusercontent.com/428948/120427139-e4edd280-c360-11eb-9fae-13ff3a42963d.png">

So I looked at the raw data, and it appears that the bundles are not referenced and instead called `de6b708ef4031fd66a9ac4afafdfa031`.

My Sentry code looks like this:

```js
Sentry.init({
  dsn: config.sentryDSN,
  enableInExpoDevelopment: true,
  debug: __DEV__,
});
```

Any ideas why this is?

**Comment by jennmueng** [comment]
Hmm, @cruzach who maintains Sentry on expo would have a better idea than I would regarding this.

**Comment by cruzach** [comment]
I haven't seen that before, but my first recommendation is to make sure you've followed the setup properly for a bare workflow project- https://github.com/expo/sentry-expo#sentry-expo

You should also check that the `release` and `dist` values for the error match the `release` and `dist` values associated with the sourcemap artifacts

**Comment by mtimofiiv** [comment]
@cruzach we have both `sentry-expo` and `@sentry/react-native` installed at the moment. The reason is that we need to support both managed and ejected – we use the managed to rapidly test stuff internally and ejected to do actual builds. This I suspect is what might be part of the problem.

But as for the rest, we followed the instructions to install to the letter. Perhaps that's the problem? In `app.json` we have this:

```
"hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "...",
            "project": "...",
            "authToken": "..."
          },
        },
      ],
    },
```

Do we need to change this to `@sentry/react-native/upload-sourcemaps` or something when we're in the ejected flow, where the problem is?

**Comment by cruzach** [comment]
Your app.json looks good to me. Like I said above, you should also check that the `release` and `dist` values for the error match the `release` and `dist` values associated with the sourcemap artifacts

**Comment by brkastner** [comment]
I'm seeing this issue as well but can't seem to figure out the cause. My stack traces were working fine for months but after upgrading to the latest sdk, I see random file paths as well.

Issues are assigned to the appropriate release and the regular bundle files are uploaded to sentry after the build finishes so not sure what changed.

**Comment by brkastner** [comment]
I added my expo-updates manifest as context to a test exception and it looks like the stack traces are using `Updates.manifest.bundleKey`. Do we need to manually set the release/dist if it's an OTA update and if so what should they be?

**Comment by cruzach** [comment]
If you do not set your `release` and `dist`, **and** your app is running on an OTA:
- `release` defaults to `${Updates.manifest.revisionId}`
- `dist` defaults to `${Updates.manifest.version}`

If you're running on the embedded JS bundle from `eas build`, then 
- Your release will automatically be set to Sentry's expected value- `${bundleIdentifier}@${version}+${buildNumber}` (iOS) or `${androidPackage}@${version}+${versionCode}` (Android).
- Your dist will automatically be set to Sentry's expected value- `${buildNumber}` (iOS) or `${versionCode}` (Android).

**Comment by brkastner** [comment]
@cruzach that's what I thought but it doesn't seem to be attaching errors to the correct release. I also tried using the deprecated `Sentry.setRelease` but that didn't work either. When I go to the releases section, I do see a new session for the OTA release but the error itself still uses the embedded bundle's release. 

Oddly enough though, the Additional Data context section shows the OTA version for `__sentry_release`.

**Comment by brkastner** [comment]
I finally got it to assign to the correct release on OTA bundles by overriding both dist and release like so:
```ts
const sentryOptions: ReactNativeOptions = {
    dsn: '...',
    enableAutoSessionTracking: true,
    attachStacktrace: true,
};

if (Updates.manifest) {
    const manifest = Updates.manifest as AppManifest;
    if (manifest.revisionId)
        sentryOptions.release = manifest.revisionId;
    if (manifest.version)
        sentryOptions.dist = manifest.version;
}

Sentry.init(sentryOptions);
```
which means the default settings are not being applied correctly. Is this because I'm importing from `@sentry/react-native` instead of `sentry-expo` since I'm using the bare workflow? If tried using `sentry-expo` but the app fails to start.

Regardless, the stack traces are still using `Updates.manifest.bundleKey` rather than `~/main.jsbundle` like the artifacts uploaded by the `postPublish` hook.

**Comment by marandaneto** [comment]
ping @jennmueng

**Comment by jennmueng** [comment]
@marandaneto Closing as this is expo related only.
