### ISSUE TITLE
Cannot use Performance tracking because NOT be the latest SentrySDK

### ISSUE THREAD

**Issue by moonjava2005** [getsentry/sentry-react-native#1589]
Sentry is introducing Performance tracking which requires use to upgrade SentrySDK to the latest
Could you support that? I tried to force upgrade SentrySDK to 7.xx but it is not compatible with this module requirement

![Screen Shot 2021-06-08 at 18 16 42](https://user-images.githubusercontent.com/16474293/121175809-b2266b80-c885-11eb-9a3b-16a48064d0af.png)

**Comment by jennmueng** [comment]
@moonjava2005 We're now using `7.0.0` in the version that is in master branch. We will be releasing `2.5.0` shortly.
