### ISSUE TITLE
Uploading source maps fails when DERIVED_FILE_DIR has a space in it

### ISSUE THREAD

**Issue by elliottkember** [getsentry/sentry-react-native#1593]
### Environment

Sentry SaaS, latest React Native version

### Steps to Reproduce

```
. ~/.nvm/nvm.sh

export SENTRY_PROPERTIES=ios/sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node
cd ..
./node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
```

### Expected Result

When `DERIVED_FILE_DIR` has a space in it, I'm trying to escape it with quotes above. That doesn't seem to work.

I've tried this:

`export EXTRA_PACKAGER_ARGS="--sourcemap-output \"$DERIVED_FILE_DIR/main.jsbundle.map\""`

and 

`export EXTRA_PACKAGER_ARGS="--sourcemap-output \\\"$DERIVED_FILE_DIR/main.jsbundle.map\\\""`

But I keep getting spaces in this directory result. So the source map never gets written, because the DERIVED_FILE_DIR gets quoted right after the name of my app (which has "myapp DEV" in the name of the scheme, and therefore the derived file dir).

` --sourcemap-output /Users/administrator/Library/Developer/Xcode/DerivedData/myapp-ceocblmsanifffazayuorapzsldx/Build/Intermediates.noindex/ArchiveIntermediates/myapp DEV/IntermediateBuildFilesPath/myapp.build/Release-iphoneos/myapp DEV.build/DerivedSources/main.jsbundle.map`

```
  error EISDIR: illegal operation on a directory, open '/Users/administrator/Library/Developer/Xcode/DerivedData/myapp-ceocblmsanifffazayuorapzsldx/Build/Intermediates.noindex/ArchiveIntermediates/myapp'
```

Note the `myapp` without `myapp DEV`

### Actual Result

Nothing seems to escape this correctly. My sourcemap-output variable gets set with a space in it when the Scheme has a space in it (it's built on a build server). It will also fail if the Product name has a space in it. Is there a way to escape these spaces?

**Comment by elliottkember** [comment]
Turns out the best answer is [here](https://github.com/philipshurpik/react-native-source-maps/issues/4#issuecomment-524201077) - you can't pass this as a parameter if it has a space in it. I'm going to have to figure out a workaround, or patch this script.

**Comment by marandaneto** [comment]
@elliottkember did you have the chance to find out a solution or a code snippet to patch the script?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
