### ISSUE TITLE
Inconsistent tags between OS, can't filter by Android

### ISSUE THREAD

**Issue by maxkomarychev** [getsentry/sentry-react-native#1599]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native: 2.4.3.

### Steps to Reproduce

```
const transaction = Sentry.startTransaction({ name: 'app.loader' })
const span = transaction.startChild({....})
...
span.finish()
transaction.finish()
```

### Expected Result

I can filter my transactions using tag `os.name`

### Actual Result

Available tags are inconsistent between platforms, more specifically: 
`os.name` is only available with value `iOS` but not on android (screenshots attached)

<img width="361" alt="Screen Shot 2021-06-11 at 21 23 41" src="https://user-images.githubusercontent.com/7002833/121733061-aba12980-cafb-11eb-8dc3-a7f58c7f20f6.png">
<img width="372" alt="Screen Shot 2021-06-11 at 21 24 29" src="https://user-images.githubusercontent.com/7002833/121733064-acd25680-cafb-11eb-854c-2ab6cf543b7b.png">

**Comment by jennmueng** [comment]
@maxkomarychev Device context on transactions was added in the latest Sentry Android SDK, you can update to the React Native SDK version [2.5.0](https://github.com/getsentry/sentry-react-native/releases/tag/2.5.0) to get device context. I'll add this to the changelog to be more clear.
