### ISSUE TITLE
[2.5.1] Require cycle warn

### ISSUE THREAD

**Issue by ku8ar** [getsentry/sentry-react-native#1612]
### Environment

Which SDK and version?
"@sentry/react-native": "^2.5.1",

### Steps to Reproduce

install 2.5.1 and watch console:

```
WARN  Require cycle: node_modules/@sentry/hub/dist/session.js -> node_modules/@sentry/hub/dist/hub.js -> node_modules/@sentry/hub/dist/session.js
```

### Expected Result

no warn

### Actual Result

warn

**Comment by Leleka14** [comment]
same here
