### ISSUE TITLE
Incorrect Redux state in issues

### ISSUE THREAD

**Issue by olindv** [getsentry/sentry-react-native#1615]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.5.1

**`react-native` version:** 0.63.3

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```javascript
Sentry.init({
  dsn: SENTRY_DSN,
  environment: REACT_APP_ENVIRONMENT,
  maxBreadcrumbs: 50,
  release: getReleaseName(),
  enableAutoSessionTracking: true,
  sessionTrackingIntervalMillis: 10000,
  integrations: [
    new Sentry.ReactNativeTracing({
      tracingOrigins: [
        'localhost',
        API_URL,
        /^\//,
        /^https:\/\//,
      ],
      idleTimeout: 5000,
      routingInstrumentation,
      normalizeDepth: 10,
    }),
  ],
  tracesSampleRate: 1.0,
  debug: false,
})
```

**I have following issue:**

Good day. Faced the following issue - when I open an error in the Sentry dashboard, I see an incorrect Redux state. 

This is my store.js file:

```javascript
import { createStore, applyMiddleware, combineReducers } from 'redux'
import { loggerMiddleware } from 'src/store/middlewares/logger'
import createSagaMiddleware from 'redux-saga'
import { composeWithDevTools } from 'redux-devtools-extension'

import * as Sentry from '@sentry/react'
import { captureException } from 'utils/sentry'

import chat from './domains/chat/reducers'

import chatSaga from './domains/chat/sagas'

export default function configureStore(state) {
  const sagaMiddleware = createSagaMiddleware({
    onError(error) {
      captureException(error)
    },
  })

  const middlewares = [sagaMiddleware]

  if (__DEV__) {
    middlewares.push(loggerMiddleware)
  }

  const composeEnhancers = composeWithDevTools({})

  const sentryReduxEnhancer = Sentry.createReduxEnhancer()

  const store = createStore(
    combineReducers({
      chat,
    }),
    state,
    composeEnhancers(applyMiddleware(...middlewares), sentryReduxEnhancer),
  )

  sagaMiddleware.run(chatSaga)

  return store
}
```

**Steps to reproduce:**
- triggering the error events
- open an issue in the Sentry dashboard

**Actual result:**

![photo_2021-06-18_22-18-32](https://user-images.githubusercontent.com/44572777/122607379-21b90980-d083-11eb-8985-cca3647ab5fc.jpg)

**Expected result:**

Correct display Redux state in errors in the Sentry dashboard

**Comment by jennmueng** [comment]
@olindv You would pass `normalizeDepth` to `Sentry.init` not `Sentry.ReactNativeTracing`, this is caused by the normalizeDepth being set by default to 3.
