### ISSUE TITLE
Sometimes has sources maps other times can't find them

### ISSUE THREAD

**Issue by ChrisWiles** [getsentry/sentry-react-native#1681]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
```
    "@sentry/react-native": "1.1.0"
     "react-native-code-push": "5.7.0",
```

### Steps to Reproduce

Some of my iOS errors have source maps and others can't find source maps. This is for the same build. 
It used to work fine at one point but broke a while back... 

```
# create codepush OTA release
appcenter codepush release-react --description "$DESCRIPTION" -t $BINARY_VERSION -d $DEPLOYMENT --app $APPNAME --output-dir ./build/android
# upload source maps
sentry-cli react-native appcenter --deployment $DEPLOYMENT --version-name $SENTRY_VERSION_NAME $APPNAME android ./build/android/CodePush
```

Explain this one, I have two test crash errors both have full stack trace and source maps, a few hours later I repeat the test, and this time sentry can't find the source maps. Any ideas? 
<img width="385" alt="Screen Shot 2021-07-19 at 7 27 34 PM" src="https://user-images.githubusercontent.com/9455409/126244955-791863b1-ba9a-4b86-afde-68553d1d28d9.png">

**Comment by ChrisWiles** [comment]
Anyways gave up and just updated sentry and added dist and now everything works but Hermes.

**Comment by jennmueng** [comment]
@ChrisWiles This is hermes on iOS right? I've tested it a while back and it should just work without any extra steps needed unlike on Android.
