### ISSUE TITLE
Add event.environment and align with other Hybrid SDKs such as Flutter and Capacitor.

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1697]
This SDK only has `event.origin` and we have yet to add the `event.environment` tag like other newer hybrid SDKs yet.

**Comment by bruno-garcia** [comment]
We're also missing some docs.

https://twitter.com/brungarc/status/1419990519447498753?s=21

**Comment by bruno-garcia** [comment]
Resolved in #1749
