### ISSUE TITLE
Update SDK recommendation when starting to use Sentry  in ReactNative

### ISSUE THREAD

**Issue by Syntbeheer** [getsentry/sentry-react-native#1705]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native: "^2.6.1"

### Steps to Reproduce

1. `npm install --save @sentry/react-native`
2. `npx @sentry/wizard -i reactNative -p ios android`
3. Add Sentry into App.js:
```
import * as Sentry from '@sentry/react-native';

Sentry.init({
  dsn: '***',
  integrations: [new Sentry.ReactNativeTracing()],
  tracesSampleRate: 1,
});
```

### Expected Result

I'd expect to have the latest SDK.

### Actual Result

> Update your SDKs
> We recommend updating the following SDKs to make sure you’re getting all the data you need.
> 
> unblnd
> sentry-swift @v2.1.2
> migrate to the sentry-cocoa SDK so you can:
> update your SDK from @v2.1.2 to @v3.11.1

**Comment by jennmueng** [comment]
@Syntbeheer Did you update from a prior version and forgot to remove a prior dependency? We do not have a dependency on `sentry-swift`.
