### ISSUE TITLE
Early native initialization causes unreadable sourcemaps - can we call init twice?

### ISSUE THREAD

**Issue by alex-a-pereira** [getsentry/sentry-react-native#1710]
After following the steps for manual native initialization, we observe two unexpected behaviors:
1. native exceptions do not include user, even after JS runtime calls configureScope to set user
2. JS errors have unreadable stack traces

My real question here is - why do we have to set `autoInitializeNativeSdk` to false? Are we not allowed to init native sdk twice? Thinking we should theoretically be able to do something like this:
- in `didFinishLaunchingWithOptions` inside AppDelegate we call `[SentrySDK startWithConfigureOptions` as the docs suggest
    - this catches all native exceptions before JS runtime is available
    - here we are lacking user, environment, etc. which is OK
- in JS layer, we call `Sentry.init()` and pass in environment
    - in this theoretical example, we don't set `autoInitializeNativeSdk: false` as part of options
        - this causes native to re-initialize with proper information

Is this not allowed??

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
```
"react-native": "0.64.0",
"@sentry/react-native": "^1.8.2",
```

### Steps to Reproduce

1. Follow steps in [manual native init docs](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/)
2. make sure when calling `Sentry.init()` from JS runtime, `autoInitializeNativeSdk` is set to false (as docs suggest)
3. start your app, run it on ios simulator in release mode to mimic a real user (`yarn ios --configuration=Release`)
4. call Sentry.configureScope to set user id
5. throw a JS error somewhere in the app (i did it on button press), reopen app
    - check sentry.io for the issue, notice that stacktrace comes from `RCTFatalException` (native code) rather than from the JS code
6. throw a native crash from js code via `Sentry.nativeCrash()` , reopen app
    - check sentry.io for the issue, notice that user is null even though we set user in step 4

### Expected Result

early native initialization can be overriden by init called at JS runtime

### Actual Result

Stacktrace for JS error when using early native init and `autoInitializeNativeSdk` set to false
![image](https://user-images.githubusercontent.com/36137079/127895772-e05b6a24-c726-4ebf-b992-e0b0a2a81957.png)

Stacktrace for JS error when not using early native init
![image](https://user-images.githubusercontent.com/36137079/127895862-fef3d533-8a2d-4e80-a694-1fec771ec1a3.png)

**Comment by jennmueng** [comment]
@alex-a-pereira Yes calling init twice isn't allowed.

Can you try adding this statement to the `beforeSend` in obj c? Essentially follow how we init the Sentry Cocoa SDK in this React Native SDK. I think we forgot to add this as a note when writing the documentation.

https://github.com/getsentry/sentry-react-native/blob/afdb12befc999e51d6b25912ccb14ff26f51bb91/ios/RNSentry.m#L50-L54

**Comment by alex-a-pereira** [comment]
@jennmueng thanks for the response - we've de-prioritized the early-init for now on ios because android is really where we needed the early-init and the example in the android docs works perfectly. 

I'll close this issue for now and re-open it when we return to implementing this (maybe a few weeks or so). I'll try your suggestion at that time! thanks again
