### ISSUE TITLE
NoSuchFileException while running release build

### ISSUE THREAD

**Issue by Kamalnrf** [getsentry/sentry-react-native#1724]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native: "^2.4.3"

### Steps to Reproduce

1. npm install
2. cd android && ./gradlew :app:assembleProductionRelease 

### Expected Result

Build to pass and generate a release APK 

### Actual Result

The build fails with this error 
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.nio.file.NoSuchFileException: /Users/mukkamala.kamal/Work/ipartner/node_modules/@sentry/react-native/android/build/intermediates/res/symbol-table-with-package/release/package-aware-r.txt
```

**Comment by HamzaIkram20** [comment]
+1, Started having the same issue today. Yesterday builds were working fine.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
