### ISSUE TITLE
React Native Sentry uploaded sourcemap not showing error traces correctly

### ISSUE THREAD

**Issue by iagormoraes** [getsentry/sentry-react-native#1737]
### Environment
React Native

How do you use Sentry?
"@sentry/react-native": "^2.6.0"

Which SDK and version?
"@sentry/react-native": "^2.6.0",

### Steps to Reproduce

1. run gradlew assembleRelease
2. gradlew sentry method uploads sourcemap and index.android.bundle
3. In sentry panel it shows 0B for index.android.bundle and 15.5MiB for sourcemap file
4. The error trace is being shown minified without any information

### Expected Result

Error trace shows the methods and variables proper names for references.

### Actual Result

Error trace don't show anything useful to understand it because is minified.

### Screenshots

<img width="1090" alt="Screen Shot 2021-08-20 at 09 16 45" src="https://user-images.githubusercontent.com/13892132/130232398-517eeff4-98a5-4af1-82fe-6857135c061e.png">
<img width="1180" alt="Screen Shot 2021-08-20 at 09 16 55" src="https://user-images.githubusercontent.com/13892132/130232408-1dddec60-2f68-4646-bb8f-d92c4452e43c.png">

**Comment by iagormoraes** [comment]
@jennmueng I've read the document you shared and as we don't have a custom map for it there is no need for extra setup to make the source map hermes to work, what I saw on the standard is that we need to wrap the App component. Does this is the missing part that is making the source map to not being used?

**Comment by jennmueng** [comment]
@iagormoraes No you do not need the wrapper for the source maps to work. Can you try doing the manual step and see if those source maps work compared to the default ones? FYI you might need a new release for the new source maps to be registered as overwriting the auto-generated ones don't always work.

**Comment by jennmueng** [comment]
@iagormoraes Make sure you're passing `--org` and `--project` as an argument to the releases command and not to the subcommands:

```bash
npx @sentry/cli releases \
    --org <org>\
    --project <project> \
    files <release> \
    upload-sourcemaps \
    --dist <dist> \
    --strip-prefix /path/to/project/root \
    --rewrite index.android.bundle index.android.bundle.map
```

**Comment by marandaneto** [comment]
@jennmueng are u sure? https://docs.sentry.io/product/cli/configuration/#explicit-options

**Comment by jennmueng** [comment]
Yup @marandaneto, ran it to make sure.

**Comment by iagormoraes** [comment]
> @iagormoraes Make sure you're passing `--org` and `--project` as an argument to the releases command and not to the subcommands:
> 
> ```shell
> npx @sentry/cli releases \
>     --org <org> \
>     --project <project> \
>     files <release> \
>     upload-sourcemaps \
>     --dist <dist> \
>     --strip-prefix /path/to/project/root \
>     --rewrite index.android.bundle index.android.bundle.map
> ```

Followed @jennmueng configuration for the cli command and it uploaded my generated files, so I have tested them on sentry platform and the files are there.

The error traces is being mapped as expected:

<img width="1074" alt="Screen Shot 2021-09-14 at 15 03 18" src="https://user-images.githubusercontent.com/13892132/133310189-95884af5-e596-4985-bea5-4375a73b02f3.png">

**Comment by jennmueng** [comment]
@iagormoraes If I recall correctly, you would use the format `com.company.package@version` for your release value, you would then get the `package` field in your release info. The error icon for JS files can either be a JS or a NodeJS one.
