### ISSUE TITLE
Support for React Navigation v6

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-react-native#1756]
`sentry-react-native` currently has an integration for `react-navigation` v4 and v5.

React Navigation v6 [has been released](https://reactnavigation.org/blog/2021/08/14/react-navigation-6.0) so it would be amazing to have support for it.

I dont expect the changes to be complex, here is the full upgrade guide with the important changes: https://reactnavigation.org/docs/upgrading-from-5.x

**Comment by cvburgess** [comment]
Will the v5 handler work in the meantime or should we turn off instrumentation?

**Comment by bruno-garcia** [comment]
3.1.0 includes support. We just merged docs too.

Basically v5 was renamed to just ReactNavigation and it works for v5 and v6
