### ISSUE TITLE
Warm and Cold start metrics not reported

### ISSUE THREAD

**Issue by rnystrom** [getsentry/sentry-react-native#1758]
### Environment

How do you use Sentry? RN app on iOS only
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?): Sentry.io

Which SDK and version? 3.0.1
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. Wrapped app with `Sentry.wrap(App)`

### Expected Result

Cold and warm start metrics automatically captured as [the docs suggest](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#app-start-instrumentation).

### Actual Result

Cold/warm start is blank for our project's performance tab.

---

I spent some time poking around the [sentry-cocoa](https://github.com/getsentry/sentry-cocoa) iOS pod and can see that app start logging is enabled. However there are many cases where [if the hybrid SDK is enabled, it returns early](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryTracer.m#L313-L316). Comments suggest that the hybrid SDK (which I assume would be this library) will handle cold/warm start metrics. However I can't find any references to cold/warm in this library.

I'm not sure how all of this is supposed to work. After modifying some code and putting breakpoints in locally (also enabling logging on dev builds), I'm seeing some numbers but this is clearly from my debugging (30+ seconds of cold start, ha):

<img width="1115" alt="Screen Shot 2021-09-03 at 2 07 11 PM" src="https://user-images.githubusercontent.com/739696/132048866-d5eeffdb-bba8-4fae-9e9a-fa9c43c1cab3.png">

We have no cold/warm start traces from testers at all, all of our other automatic logging is working.

**Comment by rnystrom** [comment]
Actually may have solved this accidentally by enabling 100% sampling for navigation events.

```ts
tracesSampler: (context) => {
  switch (context.transactionContext.op) {
    case "navigation":
      return 1;
    default:
      // disable unexpected trace logging
      return 0;
  }
},
```

Is that how this works?

**Comment by jennmueng** [comment]
@rnystrom App start measurements should be attached to transactions with `op: "ui.load"`. So I would sample those if you are looking to enable traces one-by-one in `tracesSampler`.

**Comment by rnystrom** [comment]
@jennmueng Great! We are seeing cold start measurements now, but warm start looks totally blank. Is that expected? Or is there something we may have overlooked to also receive warm start metrics?

**Comment by jennmueng** [comment]
@rnystrom Hmm warm starts should also come when cold start measurements come. Maybe you can try to trigger a warm start manually and see if it works. You can read what a warm start is here: https://docs.sentry.io/product/performance/mobile-vitals#app-start
