### ISSUE TITLE
Can't upgrade to v3.0.0

### ISSUE THREAD

**Issue by NilPuig** [getsentry/sentry-react-native#1760]
### Environment

iOS (Xcode)

Which SDK and version?
- sentry-react-native v3.0.0
- Node v14.17.5
- Xcode v12.5.1
- Deployment info: iOS 10.0
- Pod version: 1.10.1 

### Steps to Reproduce

1. `yarn add @sentry/react-native@latest`
2. `yarn; npx pod-install`
3. Error occurs during pod installation 

### Expected Result

Pods should be installed 

### Actual Result

I get the following error: 
```
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 3.0.0, which depends on
      Sentry (= 7.2.6)

None of your spec sources contain a spec satisfying the dependency: `Sentry (= 7.2.6)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I've tried the following:
- remove Podfile.lock file
- remove Pods folder
- `pod install --repo-update`
- `pod repo update`

Nothing worked so far.

**Comment by jennmueng** [comment]
Hmm, I would try it again and make sure the `pod repo update` command is run before you do the pod install. Closing this as Sentry Cocoa version `7.2.6` exists and looks like no one else has run into this issue. So it looks to just be an out of date source for you and not an issue with our SDK.
