### ISSUE TITLE
An error occurred during Android build since last update

### ISSUE THREAD

**Issue by TomCorvus** [getsentry/sentry-react-native#1762]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
react-native 3.0.2

### Steps to Reproduce

1. Build the Android application (Debug or release mode)

### Expected Result

Build successfully

### Actual Result

An error is occurred. Same error when I try to build the Android app with AppCenter.
Everything worked fine 3 hours ago. Maybe caused by @marandaneto last commit?

```
project1/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java:86: error: lambda expressions are not supported in -source 7
        SentryAndroid.init(this.getReactApplicationContext(), options -> {
                                                                      ^
  (use -source 8 or higher to enable lambda expressions)
1 error

FAILURE: Build failed with an exception.
```

Thanks for your help

**Comment by nomi9995** [comment]
same issue

**Comment by nomi9995** [comment]
@TomCorvus you can manually patch from this PR https://github.com/getsentry/sentry-react-native/pull/1763 to fix this error

**Comment by TomCorvus** [comment]
Thanks @nomi9995 👍

**Comment by TomCorvus** [comment]
@nomi9995 I think you miss to close braces line 21-22 in build.gradle

**Comment by nomi9995** [comment]
@TomCorvus fixed. thanks

**Comment by marandaneto** [comment]
@TomCorvus which version of the Android Gradle Plugin are you building against? https://github.com/getsentry/sentry-react-native/pull/1763 should not be necessary since Java 8 is the default target/source for AGP >= 4.2

**Comment by marandaneto** [comment]
https://developer.android.com/studio/releases/gradle-plugin#java-8-default

**Comment by nomi9995** [comment]
@marandaneto most of the users are not using AGP >=4.2. there are two options for the user to fix this

1. update AGP version to 4.2
2. patch package by adding default java 8

I think, forcefully update the AGP version from the user is not a good approach
