### ISSUE TITLE
Document `promise` min version required on troubleshooting page

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#1766]
We need to document the min required version of `promise` to be 8.1.0 (or matching RN version) so this can be clarified in the troubleshooting page and close the issue: https://github.com/getsentry/sentry-react-native/issues/1077

**Comment by marandaneto** [comment]
@jennmueng did we add the docs for it already? I don't see linked PRs

**Comment by jennmueng** [comment]
@marandaneto Working on this one currently, this issue needs lots of experimentation.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-docs/pull/4392
