### ISSUE TITLE
Unknown UserID in uppercase

### ISSUE THREAD

**Issue by ayubov** [getsentry/sentry-react-native#1783]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
"@sentry/react-native": "^2.6.0",

Hello! 

I'm identifying my users by calling ```Sentry.setUser({ id });``` in the app. With some events everything works and I see IDs there, but with others I see a weird uppercased IDs which I couldn't have passed.

Where are these IDs coming from, how to fix that?

**Comment by marandaneto** [comment]
@ayubov iOS or Android? could be that your `id` is null at this point? if there's nothing set, the SDK sets a default `id` which is the `installationId`, can you also copy and paste this weird uppercased ID so we can check its format?

**Comment by ayubov** [comment]
iOS, not sure about Android. Nope, looks like it couldn't be null in the moment of calling `Sentry.setUser()`. But I call it after `Sentry.init()`. 

ID example: 
`C3469EB5-130E-4682-8D6E-A7AFBEF35F9F`

**Comment by marandaneto** [comment]
that looks like the generated id by https://github.com/getsentry/sentry-cocoa, @philipphofmann to confirm.
please @ayubov double check if your `id` can be null at any point, that would fall back to the default generated id.

**Comment by marandaneto** [comment]
@jennmueng please have a look at it then, if the `id` can be lost during serialization or something

**Comment by philipphofmann** [comment]
See https://docs.sentry.io/platforms/apple/enriching-events/identify-user/

> Since 6.0.1: Sentry will by fallback to installationId if you do not provide a user identity.

Do we do something similar on Android @marandaneto? I think we should add this info also to the identify-user docs of the hybrid SDKs.

**Comment by ayubov** [comment]
@marandaneto @philipphofmann @jennmueng hey guys, any updates, please?

**Comment by marandaneto** [comment]
> See [docs.sentry.io/platforms/apple/enriching-events/identify-user](https://docs.sentry.io/platforms/apple/enriching-events/identify-user/)
> 
> > Since 6.0.1: Sentry will by fallback to installationId if you do not provide a user identity.
> 
> Do we do something similar on Android @marandaneto? I think we should add this info also to the identify-user docs of the hybrid SDKs.

yes, just fixed the Android wording https://github.com/getsentry/sentry-docs/pull/4200 since `Secure.ANDROID_ID` has been removed a while ago

**Comment by marandaneto** [comment]
@philipphofmann indeed, would you like to raise an issue? Flutter and RN should be added as well, probably Cordova, etc...

@jennmueng could you check if `setUser` works as expected?

@ayubov sorry for delay, we'll have a look at it, meanwhile, would you mind to check your `setUser` call? maybe you are missing the `id` part of it.

eg `Sentry.setUser({ id: id });`, looks like you are setting the `id` as the `user` object, but you have to pass the `id` property name.

**Comment by philipphofmann** [comment]
I opened up a PR instead @marandaneto https://github.com/getsentry/sentry-docs/pull/4201.

**Comment by ayubov** [comment]
@marandaneto I think I'm doing everything according to the [docs](https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/)

When I'm calling `Sentry.setUser({ id })` - I'm calling setUser with an object with property with name id and value equals to id variable in current lexical scope. It is the same as `Sentry.setUser({ id: id })` [since ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015)

**Comment by marandaneto** [comment]
@ayubov thanks for confirming, as I don't know the structure of your `id`, I wanted to confirm, lets wait for @jennmueng

**Comment by ayubov** [comment]
@jennmueng I noticed it with native code errors (like app crash events, OOM etc). I think yes, all of these events are missing the IDs. setUser is being called right after user's signing in.

Also interesting that some JS events which happens before signing in don't have any ID in user section at all, like this:
![image](https://user-images.githubusercontent.com/26591995/135440306-faea85fa-83e0-41da-81d0-78e489aea98f.png)

But these native events with changed IDs are looking like that:
![image](https://user-images.githubusercontent.com/26591995/135440592-98e09d9a-745f-48f5-9600-db2fea3a407f.png)

**Comment by marandaneto** [comment]
@ayubov have you tested the latest Sentry RN SDK version? I've tested myself and it works, I do set an ID, capture events on Android and iOS and they are there.

**Comment by marandaneto** [comment]
otherwise, could you share with us a minimal reproducible example? thanks
