### ISSUE TITLE
Obfuscated hermes source code

### ISSUE THREAD

**Issue by jaydgoss** [getsentry/sentry-react-native#1789]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
sentry.io

Which SDK and version?
@sentry/react-native 3.1.1

### Steps to Reproduce

1. Create ios js bundle and sourcemap
   - `react-native bundle --platform ios --entry-file index.js --bundle-output codepush/main.jsbundle --assets-dest codepush --dev false --sourcemap-output ./codepush/main.jsbundle.map`
2. Create hermes version of js bundle and sourcemap
   - `node_modules/hermes-engine/osx-bin/hermesc -O -emit-binary -output-source-map -out=codepush/main.jsbundle.hbc codepush/main.jsbundle`
3. Merge the two source maps
   - `node node_modules/react-native/scripts/compose-source-maps.js codepush/main.jsbundle.map codepush/main.jsbundle.hbc.map -o codepush/main.jsbundle.combined.map`
4. Rename main.jsbundle.combined.map => main.jsbundle.map
5. Rename main.jsbundle.hbc => main.jsbundle
6. Codepush the directory containing the bundle and assets
   - `appcenter codepush release -a xxx/xxx -d Staging -c ./codepush`
7. Create sentry release matching new version via fastlane
   - `sentry_create_release(version: sentry_version, app_identifier: app_id, finalize: true)`
8. Upload bundle to sentry via fastlane (I have also attempted to use sentry-cli directly instead and it didn't appear to help)
   - `sentry_upload_file(version: sentry_version, app_identifier: app_id, dist: codepush_tag, file: "./codepush/main.jsbundle", file_url: "app:///main.jsbundle")`
9. Upload sourcemap to sentry via fastlane (I have also attempted to use sentry-cli directly instead and it didn't appear to help)
   - `sentry_upload_sourcemap(version: sentry_version, app_identifier: app_id, dist: codepush_tag, sourcemap: "./codepush/main.jsbundle.map", url_prefix: "app:///", rewrite: false)`
10. Generate error in app using newly deployed codepush bundle and check sentry.

### Expected Result
Source code is readable as is the case with non-hermes bundles.

### Actual Result
Source code is obfuscated and instead appears as hermes bytecode
<img width="936" alt="Screen Shot 2021-09-24 at 4 11 05 PM" src="https://user-images.githubusercontent.com/6308575/134735837-700814ac-3f02-40a6-a85f-e5b596e5a86e.png">

### Question
Do I need to be uploading a non-hermes version of either the bundle or the sourcemaps?  I have tried uploading the non-hermes version of the same bundle and sourcemap to sentry, this didn't seem to work either.

I can tell that the bundle and sourcemaps I uploaded to sentry are correctly associated with the release in question by checking "Project Release Details" => "Source Maps" on sentry.io, so it's not a question of the assets being missing / not associated with the error event.

**Comment by jaydgoss** [comment]
Appears similar to https://github.com/getsentry/sentry-react-native/issues/649

**Comment by jaydgoss** [comment]
Was able to fix this by uploading the plain JS bundle + the merged hermes sourcemap to sentry

**Comment by jennmueng** [comment]
@jaydgoss On iOS you don't need to do the hermes sourcemap steps actually, it has proven to us to seem to work just fine with just the normal source maps, the [merging step outlined here](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/#custom-source-maps) is only needed on Android.

**Comment by dawidchyrzynski** [comment]
@jennmueng I'm wondering if the merging step is really needed on Android. Latest RN seems to be already generating merged source maps, see it here from line 178 - https://github.com/facebook/react-native/blob/main/react.gradle
