### ISSUE TITLE
Obfuscated Hermes source code

### ISSUE THREAD

**Issue by dawidchyrzynski** [getsentry/sentry-react-native#1815]
### Environment

How do you use Sentry?
SaaS

Which SDK and version?

- @sentry/react-native@3.1.1
- fastlane-plugin-sentry@1.10.0

### Steps to Reproduce

1. Setup project with RN 0.65.1
2. Add `SOURCEMAP_FILE=sourcemaps/main.jsbundle.map` env variable to `Bundle React Native code and images` build step (iOS)
2. Build project using Fastlane (`gym`)
3. Upload source map and Hermes jsbundle using Fastlane as shown below. I assume no extra steps are needed as `react-native-xcode.sh` script already generates composed source map.

![Zrzut ekranu 2021-10-6 o 22 35 48](https://user-images.githubusercontent.com/7567202/136279191-5d351ccc-ab40-41f7-91f8-c08af086f592.png)

### Expected Result

Human readable source code for both iOS and Android.

### Actual Result

<img width="654" alt="Zrzut ekranu 2021-10-6 o 22 30 23" src="https://user-images.githubusercontent.com/7567202/136278498-424d4518-8b44-4159-9c97-e50e534c45d7.png">

<img width="771" alt="Zrzut ekranu 2021-10-6 o 22 46 28" src="https://user-images.githubusercontent.com/7567202/136280695-5764411b-1d4c-4e0d-a4a0-f970b65b514d.png">

Event:  39a2d269e91e47dd8325e508894f590f

**Comment by marandaneto** [comment]
cc @jennmueng

**Comment by marandaneto** [comment]
@dawidchyrzynski does it work if you don't use fastlane but rather the original setup that uploads everything automatically via sentry-cli on the Bundle React Native code and images step?

**Comment by dawidchyrzynski** [comment]
@marandaneto I'll give it a try later this week and get back to you.

**Comment by marandaneto** [comment]
@dawidchyrzynski please let us know if that worked.

**Comment by dawidchyrzynski** [comment]
Hi @marandaneto,

Unfortunately I'm getting the same result using original setup with automatic sourcemaps upload (event 88a8460d463d413c85fffe1f48ef4dbc)

**Comment by marandaneto** [comment]
thanks, can you provide a minimal reproducible example? on GH would be ideal, thanks

**Comment by marandaneto** [comment]
@dawidchyrzynski any news here? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
