### ISSUE TITLE
Getting <redacted> in crash logs in on-premise integration

### ISSUE THREAD

**Issue by radhakrishnapai** [getsentry/sentry-react-native#1816]
### Environment
React native integration in iOS

How do you use Sentry?
On-premise Sentry 21.6.3

Which SDK and version?
"@sentry/react-native": "3.0.3".
"@sentry/wizard": "1.2.11"

### Steps to Reproduce

1. Integrate React native sentry SDK as per document [Sentry React Native](https://docs.sentry.io/platforms/react-native/)
2. Log native crashes in iOS.

### Expected Result

See complete stack trace with proper names of classes and description of issue.

### Actual Result

Getting "redacted" in stack trace instead of actual description with class names.

<img width="666" alt="Screenshot 2021-10-07 at 11 08 55 AM" src="https://user-images.githubusercontent.com/5534291/136350837-a0ba3ed1-4687-4564-9111-84b930b12124.png">

**Comment by marandaneto** [comment]
cc @jennmueng

**Comment by marandaneto** [comment]
@radhakrishnapai if you run a test on sentry.io, do you experience the same behavior?
how are you simulating the iOS crash event? can you share the code snippet?

**Comment by radhakrishnapai** [comment]
@marandaneto no issues found on sentry.io. I am using the following code snippet in swift to test the crash.
`fatalError("sentry test crash")`

**Comment by marandaneto** [comment]
@radhakrishnapai your issue describes `redacted` frames and not that you don't get any issues at all in your dashboard, can you elaborate on that? in case you don't get issues on your dashboard, I'd rather close this issue and open a new one with up to date description.

**Comment by radhakrishnapai** [comment]
@marandaneto I thought it is pretty obvious from the very first comment. I have put a screenshot in which you can clearly understand issue is getting logged but I am not able to read the stacktrace.

**Comment by marandaneto** [comment]
@radhakrishnapai your last comment says:

> no issues found on sentry.io

by that do you mean, issues were not appearing in there or that everything worked out on sentry.io? maybe it was a misunderstanding.

**Comment by radhakrishnapai** [comment]
@marandaneto in sentry. io, what i meant to say is that all issues are getting logged as expected and I am able to read the stack trace. the only difference from on-premise setup is that I am gettimg <redacted> in stacktrace for on-premise setup

**Comment by marandaneto** [comment]
@radhakrishnapai since you know the code and the stack trace, are the redacted frames from the system? or are the redacted frames part of your own App's code?

**Comment by marandaneto** [comment]
@radhakrishnapai any news?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
