### ISSUE TITLE
Huge bundle size in react-native for sentry/react-native (264kb)

### ISSUE THREAD

**Issue by jayshah123** [getsentry/sentry-react-native#1818]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-react-native 3.0.0
React native 0.63.2

### Steps to Reproduce

1. analyze using `npx react-native-bundle-visualizer` in a project that contains `sentry/react-native`

### Expected Result
Smaller bundle size, I see packages like browser etc included which would probably not be needed.

### Actual Result
264kb bundle

<img width="1668" alt="Screenshot 2021-10-09 at 10 46 43" src="https://user-images.githubusercontent.com/659202/136645143-0997c25f-625f-4b70-9c77-8770436fe43c.png">

**Comment by marandaneto** [comment]
@jayshah123 is 264kb before or after treeshake?

`browser` and `integrations` are vitals for the RN SDK so we can't remove them, but only used code should be bundled anyway.

**Comment by marandaneto** [comment]
dup of https://github.com/getsentry/sentry-react-native/issues/1733
