### ISSUE TITLE
My React Native project always send a 'Should add at least one event processor' warning

### ISSUE THREAD

**Issue by superhen** [getsentry/sentry-react-native#1834]
As title described,
my React Native project always send a 'Should add at least one event processor' warning.
![image](https://user-images.githubusercontent.com/21170613/137249150-37e5a9da-880a-4195-bffb-073dbc8c9db4.png)
I don't know why it occurs.Should I ignore it?

**Comment by marandaneto** [comment]
@superhen thanks, nothing is fishy, can you link me to the issue on sentry.io so I can have a look at the stacktrace? thanks

**Comment by jennmueng** [comment]
@superhen When does the error happen, right when the app opens or when an event is sent?

Also you should not be using `ErrorUtils.setGlobalHandler` as this will overwrite the global Sentry handler that is already there.

You shouldn't be initializing Sentry inside an async function, can you try moving it outside to the global scope and see if the error still occurs?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
