### ISSUE TITLE
React native 0.65. Can not read ios stack trace. Missing app:///InternalBytecode.js

### ISSUE THREAD

**Issue by roy-rayyone** [getsentry/sentry-react-native#1845]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Sentry.io
Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
"@sentry/react-native": "^3.1.1"

### Steps to Reproduce

1. Disable the automatic source maps upload script by reverting the build script "Bundle React Native code and images" to

```
export NODE_BINARY=node
../node_modules/react-native/packager/react-native-xcode.sh
```

2. Remove `Upload Debug Symbols to Sentry` script
3. Build app using fastlane
```
build_app(
        workspace: 'MyApp.xcworkspace',
        scheme: scheme,
        export_method: "ad-hoc",
        suppress_xcode_output: true,
        include_symbols: true,
      )
```
4. Upload to firebase
```
firebase_app_distribution(
        app: "xxx",
        groups: "internal-testers",
      )
```
5.  Upload dSYM
```
 sentry_upload_dif(
        upload_symbol_maps: true,
        symbol_maps: './My.app.dSYM.zip'
      )
```
6. Generate sourcemap
```
ENVFILE=${projectPath}/.env.${env} npx react-native bundle \
    --dev false \
    --platform ${platform} \
    --entry-file index.js \
    --bundle-output ${buildDir}/${output} \
    --sourcemap-output ${buildDir}/${sourcemapOutput}
```
7. Upload sourcemap to Sentry
```
${projectPath}/node_modules/@sentry/cli/bin/sentry-cli releases \
      --project=${sentryProjectName} \
      files ${getSentryReleaseVersion(platform, getFullAppVersion(pkgJson.version))} \
      upload-sourcemaps \
      --dist ${config.buildVersion} \
      --bundle=${absBuildDir}/${config.bundleName} \
      --bundle-sourcemap=${absBuildDir}/${config.bundleMap}
```

### Expected Result

I can read the error log in iOS correctly

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?
Got error: **Source code was not found** app:///InternalBytecode.js And the stack trace is showing the wrong line

![CleanShot 2021-10-19 at 23 47 44@2x](https://user-images.githubusercontent.com/89457221/137955729-5d27450d-0f89-45c9-9a49-da65a97a8c74.png)
![CleanShot 2021-10-19 at 23 48 13@2x](https://user-images.githubusercontent.com/89457221/137955904-90e630b3-7f93-4cb2-8c13-6762955d7c59.png)
![CleanShot 2021-10-19 at 23 50 01@2x](https://user-images.githubusercontent.com/89457221/137956056-9b6c041b-cb73-45c2-81f3-7d0a042fb4c4.png)
![CleanShot 2021-10-19 at 23 50 20@2x](https://user-images.githubusercontent.com/89457221/137956097-dc0b8c5e-fc0a-4957-9e7f-3f8bfde891a5.png)

**Comment by roy-rayyone** [comment]
@jennmueng can confirm that this bug does not happen in react native 0.64.2 but 0.65

**Comment by jennmueng** [comment]
@roy-rayyone This is interesting, I will have to investigate on 0.65 then.

**Comment by vuletuanbt** [comment]
> @roy-rayyone This is interesting, I will have to investigate on 0.65 then.

I managed to [fix](https://github.com/getsentry/sentry-react-native/issues/1869#issuecomment-960377783) it on RN 0.66.1. Check it out.

**Comment by marandaneto** [comment]
@jennmueng have you tested on 0.65? do we need to do something here?

**Comment by jennmueng** [comment]
@marandaneto @roy-rayyone My assumption here is maybe it's generating a malformed sourcemap as they're getting "Invalid Location in Sourcemap" errors. @roy-rayyone Have you tried updating to 0.66 and/or followed @vuletuanbt's steps?

**Comment by marandaneto** [comment]
@roy-rayyone any updated? thanks

**Comment by roy-rayyone** [comment]
hi @marandaneto @jennmueng unfortunately, I'm quite busy with my current projects now. Will try to upgrade to 0.66 when I have a chance!

**Comment by marandaneto** [comment]
@roy-rayyone any news here? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by makirby** [comment]
<img width="712" alt="Screenshot 2021-12-21 at 12 00 04" src="https://user-images.githubusercontent.com/3802468/147241587-80b475fd-b157-405d-9e4e-d997822fb19b.png">
Hey there,

We seem to be running into a similar issue, this has only started happening since we enabled hermes and upgraded to RN 0.66.3. 
We have no custom dist etc so just leave the gradle script to do its thing. Can provide any other details if needed.
