### ISSUE TITLE
"Source code was not found" on Hermes

### ISSUE THREAD

**Issue by mrousavy** [getsentry/sentry-react-native#1869]
### Environment

How do you use Sentry?
* Sentry SaaS (sentry.io)

Which SDK and version?
* `@sentry/react-native`: `3.2.1`

### Steps to Reproduce

1. Installed Sentry as mentioned in installation documentation
2. Enable Hermes on App
3. Built a new Release

### Expected Result

I expect all crashes to have desymbolicated stacktraces to be able to determine where an error is coming from.

### Actual Result

No stacktraces are available, in the console it says:
![Screenshot 2021-11-03 at 18 20 10](https://user-images.githubusercontent.com/15199031/140145625-2804944f-02ea-4157-a2de-798dedc180df.png)

and the stacktraces don't have correct symbols:

![Screenshot 2021-11-03 at 18 20 18](https://user-images.githubusercontent.com/15199031/140145791-8270bb51-62e7-45ce-a84f-6da3b9136195.png)

**Comment by mrousavy** [comment]
My questions:

1. Do you guys support Hermes already?
2. I've re-read the [getting started/installation guide](https://docs.sentry.io/platforms/react-native/) about 5 times now, I don't think I have missed anything. The wizard also didn't throw any errors. One thing I don't fully understand is ["iOS Specifics"](https://docs.sentry.io/platforms/react-native/#ios-specifics) - the wizard didn't add a build step there, do I need to add this manually? Is there an example for this?
3. How can I see if the release contains a sourcemap in the sentry web console?

**Comment by vuletuanbt** [comment]
My App:
RN: 0.66.1
@sentry/react-native: 3.2.2

What I do:
- Install [hermes](https://hermesengine.dev/docs/building-and-running)
- Clear your source maps on sentry
- Clean build and run on release mode
- Run script
```bash
#!/bin/bash

node_modules/.bin/react-native bundle \
  --dev false \
  --platform ios \
  --entry-file index.ios.js \
  --bundle-output main.jsbundle \
  --sourcemap-output main.jsbundle-plain.map

path/to/your/build/hermes/bin/hermesc -O -emit-binary -out ios-release.bundle.hbc main.jsbundle -output-source-map

node node_modules/react-native/scripts/compose-source-maps.js main.jsbundle-plain.map ios-release.bundle.hbc.map -o main.jsbundle.map

node_modules/@sentry/cli/bin/sentry-cli --auth-token YOUR_SENTRY_TOKEN \
  releases \
  --org=YOUR_ORG \
  --project=YOUR_PROJECT \
  files "YOUR_BUNDLE_ID@YOUR_VERSION+YOUR_BUILD" \
  upload-sourcemaps \
  --dist YOUR_BUILD \
  --strip-prefix path/to/root/source \
  --bundle main.jsbundle \
  --bundle-sourcemap main.jsbundle.map


```

**Comment by marandaneto** [comment]
@mrousavy https://docs.sentry.io/platforms/react-native/manual-setup/hermes/
you don't really need any custom source maps or anything done manually rather than just enabling hermes.
you don't have to fiddle with the bundles either, it should work with eg:
npx react-native run-ios --configuration Release
npx react-native run-android --variant release

only.
can you provide a minimal reproducible example? thanks

**Comment by mrousavy** [comment]
How do I upload those correctly? I couldn't find anything in the getting started docs.

 Here's the link: https://sentry.io/organizations/pink-panda-1t/issues/2783621680/?project=6044200&query=is%3Aunresolved

**Comment by jennmueng** [comment]
They should be uploaded by default with a build script added by the Sentry Wizard. Check your xcode build phases and make sure the one called something like "Bundle React Native Code and Images" calls `sentry-cli`.

@marandaneto Please check the link for me and confirm that the source maps exist for the release/dist of the event.

**Comment by marandaneto** [comment]
<img width="1123" alt="Screenshot 2021-11-18 at 10 09 14" src="https://user-images.githubusercontent.com/5731772/142385302-dfd54a42-7508-4a64-ac72-f5602caeb126.png">

**Comment by mrousavy** [comment]
@jennmueng 
> Check your xcode build phases and make sure the one called something like "Bundle React Native Code and Images" calls `sentry-cli`.
It doesn't, how should that command look like? Can you give me an example? Re-running the wizard also doesn't fix this.

@marandaneto Looks like the bundle maps are there, maybe I am using wrong versions in the init call (dist & release)?

**Comment by marandaneto** [comment]
@mrousavy your message here https://github.com/getsentry/sentry-react-native/issues/1869#issuecomment-959754791 says that you don't use `dist` and `release` directly, but now you say you are, wondering if that's the issue, please double-check https://docs.sentry.io/platforms/react-native/sourcemaps/ in case you are using custom values, but you don't have to set them at all, the SDK assign default values.

the sourcemaps don't have a view button, you can download and open via eg Sublime.

**Comment by mrousavy** [comment]
> but now you say you are

Sorry my bad, I worded that weird. I am NOT using `dist` or `release`, but I thought that I have to use it so it knows which bundle to use. My issue exists with the current init call:

```ts
    Sentry.init({
      dsn: 'https://.........@.......ingest.sentry.io/......',
    })
```

**Comment by mrousavy** [comment]
> the sourcemaps don't have a view button, you can download and open via eg Sublime.

Yeah but where do I download them? 😅

**Comment by marandaneto** [comment]
go to your project settings, the menu is called "Source maps", eg 
https://sentry.io/settings/{org}/projects/{project}/source-maps/

**Comment by marandaneto** [comment]
@mrousavy any news?

**Comment by mrousavy** [comment]
Hey! No, I have found the source maps for Android, but they're not there for iOS. I am not using custom `dist` or `release` options, so not quite sure what's failing here.

As @jennmueng pointed out, there should be a build phase (command) that calls `sentry-cli` in my iOS Project - but that isn't there. Can you help me figure out what that should look like?

**Comment by marandaneto** [comment]
@mrousavy try to run the wizard again? or https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols and https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry

**Comment by mrousavy** [comment]
Re-running the wizard didn't work in my case because my Xcode pbxproj is a bit different (lots of custom stuff).

I've manually added the upload symbols script and will now check if it works. My bad for not noticing that the Sentry Wizard (probably) failed the first time I ran it 😅

**Comment by marandaneto** [comment]
@mrousavy any news here?

**Comment by mrousavy** [comment]
Hey! I just created a new organisation on Sentry and restarted the getting started from scratch, and now everything seems to work. Not sure what I messed up, but was my fault - thanks for the help guys! 🖤
