### ISSUE TITLE
Crash in file SentryUIViewControllerSwizziling.m

### ISSUE THREAD

**Issue by radhakrishnapai** [getsentry/sentry-react-native#1885]
### Environment

How do you use Sentry?
On-premise Sentry 21.6.3

Which SDK and version?
"@sentry/react-native": "3.0.3".
"@sentry/wizard": "1.2.11"

### Steps to Reproduce
Integrate React native sentry SDK as per document [Sentry React Native](https://docs.sentry.io/platforms/react-native/)

### Expected Result

Performance metrics should be captured. No crashes should happen in SDK.

### Actual Result

SDK is crashing in following class` SentryUIViewControllerSwizziling.m` line no. 150
most likely issue is happening when trying to capture performance metrics

screenshot of stack trace
<img width="1183" alt="sentry issue" src="https://user-images.githubusercontent.com/5534291/141067431-053e0595-7b2a-401a-b0a5-03d5e8f94816.png">

stack trace logs:
[sentry - stack trace logs.txt](https://github.com/getsentry/sentry-react-native/files/7510758/sentry.-.stack.trace.logs.txt)

**Comment by marandaneto** [comment]
@radhakrishnapai please upgrade the SDK to the latest version and let us know if that still happens

**Comment by radhakrishnapai** [comment]
@marandaneto thanks for the update. Will check and let you know.

**Comment by marandaneto** [comment]
@radhakrishnapai any news?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
