### ISSUE TITLE
React Native "Source code was not found" (hashed bundle name)

### ISSUE THREAD

**Issue by sethcwhiting** [getsentry/sentry-react-native#1898]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
```
{
  "dependencies": {
    ...
    "@sentry/react-native": "^3.1.1",
    "react-native": "~0.63.4",
    ...
  },
}
```

### Steps to Reproduce

Add Sentry to React Native project (configured as below) and create a release.

### Expected Result

I expected Sentry to correctly detect the name of/path to my uploaded source map.

### Actual Result

I'm getting this error:
<img width="926" alt="Screen Shot 2021-11-16 at 9 10 27 AM" src="https://user-images.githubusercontent.com/2145601/142003349-a763a0ee-022a-4e89-a62b-28bc76e02b6f.png">

Here are my uploaded artifacts:
<img width="1058" alt="Screen Shot 2021-11-16 at 9 11 22 AM" src="https://user-images.githubusercontent.com/2145601/142003393-6557042e-4a3a-440e-bd24-80379fcf27a6.png">

I understand that these file names are supposed to match, but I'm unclear as to how I can match them up if Sentry is looking for those hashed bundle names (different hashes for each release it seems). Hopefully I'm missing something pretty obvious and this is an easy fix.

Here's my config:
```
Sentry.init({
  dsn: "https://XXXX@XXXX.ingest.sentry.io/XXXX",
  debug: process.env.$ENVIRONMENT === "qa" || process.env.$ENVIRONMENT === "uat",
  tracesSampleRate: 0.25,
  integrations: [new Sentry.ReactNativeTracing({ routingInstrumentation })],
});
```
Any help you can provide would be much appreciated!

**Comment by marandaneto** [comment]
@sethcwhiting the file names should be matching by default and no extra configuration should be needed.
are you using hermes? RAM bundles? or something different than the standard setup?
can you try using the latest `react-native` and `@sentry/react-native` version?

**Comment by sethcwhiting** [comment]
@marandaneto Thanks for the response! This is an ejected Expo project. Maybe that has something to do with it?

**Comment by sethcwhiting** [comment]
Also, I'm a little unclear as to when the source maps are generated and uploaded. Is it at build time? We're using AppCenter to build the app if that's relevant at all.

**Comment by jennmueng** [comment]
@sethcwhiting I'm not sure myself and I have never worked with building apps on AppCenter, so assuming that these bundle hashes are generated by AppCenter, can you test and see if you add this integration, does sourcemaps work:

```js
  integrations: [new RewriteFrames({
        iteratee: (frame: StackFrame) => {
          if (frame.filename) {
            frame.filename = frame.filename
              .replace(/^file:\/\//, "")
              .replace(/^address at /, "")
              .replace(/^.*\/[^.]+(\.app|CodePush|.*(?=\/))/, "");

             if (
              frame.filename !== "[native code]" &&
              frame.filename !== "native"
             ) {
              const appPrefix = "app://";
              // We always want to have a triple slash
              frame.filename =
                frame.filename.indexOf("/") === 0
                  ? `${appPrefix}${frame.filename}`
                  : `${appPrefix}/${frame.filename}`;
            }

           // Everything above this line is what we already do by default
           // Here it just replaces the filename for the bundle-hash files to main.jsbundle
           if (frame.filename.startsWith("app:///bundle-")) {
              frame.filename = "app:///main.jsbundle";
            }
          }
          return frame;
         },
      })]
```
This is just the default frame rewriting code we already have in the SDK by default, however just to see if just renaming the bundle name will work.

**Comment by sethcwhiting** [comment]
@jennmueng That seems to have worked! Thanks so much!

**Comment by sethcwhiting** [comment]
@jennmueng  One last question:
With each build, I seem to get artifacts for both iOS and Android:

<img width="1009" alt="Screen Shot 2021-11-17 at 12 20 20 PM" src="https://user-images.githubusercontent.com/2145601/142252589-b54b1a26-461f-4973-80e9-da7db8344a70.png">

<img width="1011" alt="Screen Shot 2021-11-17 at 12 20 34 PM" src="https://user-images.githubusercontent.com/2145601/142252624-0b6c24ec-9794-45f6-9346-8d98a51c2c34.png">

<img width="1009" alt="Screen Shot 2021-11-17 at 12 20 58 PM" src="https://user-images.githubusercontent.com/2145601/142252655-fadc8efe-8763-4f36-afe9-647b9bff704c.png">

Should I do anything in that snippet you shared to include the Android file? Something like `frame.filename = "app:///index.android.bundle";`?

I tested an exception on Android and iOS using just the code you sent and it worked great on both. So it _seems_ like I might not need to worry about it, but I figured I'd check with you since you probably know a lot of things about this that I don't.

**Comment by jennmueng** [comment]
@sethcwhiting You can change the if block to
```
if (frame.filename.startsWith("app:///bundle-")) {
  if (Platform.OS == "android") {
    frame.filename = "app:///main.jsbundle";
  } else {
    frame.filename = "app:///index.android.bundle";
  }
}
```
when you have separate bundles for Android and iOS. It works fine as I assume you don't really have too much Android/iOS specific code. However, this should be a patch and if you are able to find the source of where the bundles are being bundled with the hash in their names I would reckon that would be a more solid solution.

**Comment by sethcwhiting** [comment]
@jennmueng Thanks so much for your help 🙏🙏🙏
