### ISSUE TITLE
Use `accessibilityLabel` for identifying touch events

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-react-native#1913]
Hi!

I am not sure if this is doable, but properly tracking which components have been touched is a bit cumbersome as you need to set `displayName` for the component, so:
- it needs to be a component
- you need separate component for every touchable in the view to differentiate them, ie, you cant directly use
  ```tsx
  <View>
    <Button />
    <Button />
  </View>
   ```
  and know which button has been pressed.

Similarly to some testing libraries, it would be quite useful to enrich the event with the `accessibilityLabel` prop on the touched component (and its parents?). It would give much more useful information in traces and would immediately benefit every accessible app.

**Comment by marandaneto** [comment]
@renchap thanks for the suggestion, I'll discuss it internally

**Comment by marandaneto** [comment]
Maybe that could hep with https://github.com/getsentry/sentry-react-native/issues/950 too

**Comment by marandaneto** [comment]
@jennmueng would you mind having a look at it?

**Comment by marandaneto** [comment]
That could be a breaking change if the `displayName` is being used somewhere rather than only breadcrumbs, pay attention to that.

**Comment by jennmueng** [comment]
@marandaneto @renchap Let's have it be able to detect both where we will use the accessibilityLabel if a displayName is not present.

**Comment by Natural0413** [comment]
Hello sentry lost and then found it it's a good

**Comment by Natural0413** [comment]
- [ ] hello sentry lost it then found it it's a good thing for my mom she's 98 need to go

**Comment by marandaneto** [comment]
> @marandaneto @renchap Let's have it be able to detect both where we will use the accessibilityLabel if a displayName is not present.

Yes, but let's add both when available via extra data bag.

**Comment by rusakovic** [comment]
Hello @marandaneto
Start implementing Sentry library. Thank you for your efforts.
Just to figure out, if it's possible.
1. I have a button and press on in throw an error

![image](https://user-images.githubusercontent.com/17801144/153677114-54fabd43-4d13-4573-b479-b5485de61553.png)

2. Inside this component `ButtonWithShadow` I specified a `displayName`
![image](https://user-images.githubusercontent.com/17801144/153677164-8fe5802a-3488-4432-ae67-da60b3040e19.png)


3. But in Sentry log I see `Touch event within element: View`
That in real life will be hard to understand what exactly was touched.

![image](https://user-images.githubusercontent.com/17801144/153677372-948ec3f0-c579-4a0a-af60-30a5c0be48db.png)


4. Question: Is it possible to catch/identify with Sentry what exactly last wrapped component (not full structure tree) was touched by user?

Thank you!

**Comment by marandaneto** [comment]
@renchap Not sure yet, we'll check when working on this issue, thanks.

**Comment by rusakovic** [comment]
> lementing Sentry library. Thank you f

It will be a very useful feature, I suppose, for quicker debugging!

**Comment by fabiendem** [comment]
+1 for this feature.

The `displayName` is not really useful, especially in an app which relies on a component library.
Most of the time you will always see the same label, like `Button`, `Input`, etc...

We get this for our `NavBarButton`:
![Screen Shot 2022-02-16 at 16 09 46](https://user-images.githubusercontent.com/1186282/154307373-a7bc41d4-6fc9-4ae1-9b31-db93d9e1e5ab.png)

Datadog allows to set a custom label like `dd-action-name="click_me_button"` or to rely on `accessibilityLabel`: https://github.com/DataDog/dd-sdk-reactnative#user-interactions-tracking

Just bear in bind that ideally `accessibilityLabel` shouldn't be use as a key for tracking purpose. Apps which must be accessible actually use this `accessibilityLabel` property for its actual purpose.
Accessibility is more and more a requirement out there.

**Comment by jennmueng** [comment]
@fabiendem This makes sense, use a custom prop, say `sentryLabel`, then fallback to `accessibilityLabel` and then `displayName`.

**Comment by fabiendem** [comment]
@jennmueng 
Do you mean the error `Property 'someRandomProp' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)`?
Looks like you must use the `dash-case`:
Fail:
```tsx
someRandomProp="Hello world"
```
Success:
```tsx
some-random-prop="Hello world"
```

See https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking

> Note: If an attribute name is not a valid JS identifier (like a data-* attribute), it is not considered to be an error if it is not found in the element attributes type.

**Comment by jennmueng** [comment]
@fabiendem Thanks! looks like `sentry-label` would work then.

**Comment by appsgenie** [comment]
How to disabled these events? `Touch event within element: View`

**Comment by krystofwoldrich** [comment]
@appsgenie You can add the following to your `Sentry.init`.

```js
beforeBreadcrumb: (breadcrumb) => {
  if (breadcrumb.category === 'touch') {
    return null;
  }
},
```
