### ISSUE TITLE
Android APK build issue - Could not resolve all files for configuration ':@sentry_react-native:releaseRuntimeClasspath'.

### ISSUE THREAD

**Issue by karthinidc** [getsentry/sentry-react-native#1916]
Android Platform: Build getting failed but running in the emulator.

Execution failed for task ':@sentry_react-native:generateReleaseRFile'.
> Could not resolve all files for configuration ':@sentry_react-native:releaseRuntimeClasspath'.
   > Could not resolve io.sentry:sentry-android:4.3.0.
     Required by:
         project :@sentry_react-native
      > Could not resolve io.sentry:sentry-android:4.3.0.
         > Could not get resource 'http://tokbox.bintray.com/maven/io/sentry/sentry-android/4.3.0/sentry-android-4.3.0.pom'.
            > Could not GET 'http://tokbox.bintray.com/maven/io/sentry/sentry-android/4.3.0/sentry-android-4.3.0.pom'. Received status code 502 from server: Bad Gateway

It worked up to yesterday - Issue from today only 

    "@sentry/react-native": "2.4.2",
    "react": "16.8.3",
    "react-native": "0.59.9",

### Expected Result

APK file needs to generate.

### Actual Result

> Task :@sentry_react-native:generateReleaseRFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@sentry_react-native:generateReleaseRFile'.
> Could not resolve all files for configuration ':@sentry_react-native:releaseRuntimeClasspath'.
   > Could not resolve io.sentry:sentry-android:4.3.0.
     Required by:
         project :@sentry_react-native
      > Could not resolve io.sentry:sentry-android:4.3.0.
         > Could not get resource 'http://tokbox.bintray.com/maven/io/sentry/sentry-android/4.3.0/sentry-android-4.3.0.pom'.
            > Could not GET 'http://tokbox.bintray.com/maven/io/sentry/sentry-android/4.3.0/sentry-android-4.3.0.pom'. Received status code 502 from server: Bad Gatewa
<img width="1520" alt="Screenshot 2021-11-30 at 9 26 35 PM" src="https://user-images.githubusercontent.com/59463519/144081775-8bc5fd58-26f8-4cc1-a6ae-78f713eb935f.png">

**Comment by karthinidc** [comment]
Any updates.

**Comment by marandaneto** [comment]
@karthinidc that's not Sentry's issue, but rather your `repositories` configuration in the Gradle file.

where you see

```
repositories {
  ...
  // be sure that `mavenCentral` is also there
  mavenCentral()
}
```

**Comment by Lurtroxx** [comment]
In a managed expo project, this issue is occurring again! Any advice on how to add this "mavencentral()" to expo project?
@marandaneto @karthinidc

**Comment by marandaneto** [comment]
I am no longer part of the Sentry staff, cc @krystofwoldrich

**Comment by krystofwoldrich** [comment]
Thanks @marandaneto 

@Lurtroxx Can you share the error you are seeing together with your Expo SDK version and Sentry SDK version and step how do you build your app?

In a new issue, please.

**Comment by Lurtroxx** [comment]
@krystofwoldrich Yes I will do so today.
