### ISSUE TITLE
Run E2E test using a matrix of RN versions

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#1924]
Helps to catch issues like https://github.com/getsentry/sentry-react-native/pull/1923

**Comment by marandaneto** [comment]
we can consider a sample that compiles with different RN versions, it's cheaper and faster than E2E test, it'd already help us out preventing the mentioned issue above.

**Comment by jennmueng** [comment]
@marandaneto Yeah, compiling the sample with different versions and just check if it crashes at runtime or not would catch the above issues.

**Comment by krystofwoldrich** [comment]
I don't know id that should be new issue, or if it make sense here, but

as the new 5.0.0 and new RN Architectures are coming closer, this issue will be more and more relevant.

Not even we should at least build with RN version matrix but also with the same RN version and new Arch enabled/disabled. What do you think?

**Comment by krystofwoldrich** [comment]
The perf tests relate to this as they are a part of e2e tests.

https://github.com/getsentry/sentry-react-native/issues/2545

Is this still a p1? As we are planning to cut off a lot of older versions in v5.
