### ISSUE TITLE
Mismatched line numbers when using RAM Bundles

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#1937]
When using https://reactnative.dev/docs/ram-bundles-inline-requires
line numbers may be mismatched, the reason is unknown, could be that RN generates already mismatched line numbers or Sentry symbolication do it wrongly.

Removing `extraPackagerArgs: ["--indexed-ram-bundle"]` does not help.
Tested on latest RN (66.3) and latest Sentry RN (3.2.5)

**Comment by marandaneto** [comment]
Line number should have been 19

<img width="700" alt="Screenshot 2021-12-06 at 10 56 23" src="https://user-images.githubusercontent.com/5731772/144825707-1e204139-ed93-4712-bc5c-14bfe0298787.png">

Line number should have been 18

<img width="771" alt="Screenshot 2021-12-06 at 10 57 00" src="https://user-images.githubusercontent.com/5731772/144825813-d060a530-fe7d-4186-bf32-47dd4ce77eff.png">

**Comment by marandaneto** [comment]
@jan-auer have you had the time to look into it? thanks.

**Comment by marandaneto** [comment]
Likely related to https://github.com/facebook/metro/issues/399

**Comment by krystofwoldrich** [comment]
Although possible to use RAM Bundles are deprecated and not developed for a while (timestamp December 2024). 

Since the symbolication issue is type of +1 we are closing this.

If this is still an issue feel free to open a new issue if the context changed.
