### ISSUE TITLE
React native app just warm start

### ISSUE THREAD

**Issue by dangdo1** [getsentry/sentry-react-native#1968]
_Platform:_
- [x]  Android -> 29, 30, 31
- [x]  React-Native -> 0.66.3
- `    "@sentry/react-native": "^3.2.6",
    "@sentry/tracing": "^6.15.0",
    "@sentry/wizard": "^1.2.15",` 
---------------------------------

> @Override
>   public synchronized void onActivityCreated(
>       final @NonNull Activity activity, final @Nullable Bundle savedInstanceState) {
>     setColdStart(savedInstanceState);
>     addBreadcrumb(activity, "created");
>     startTracing(activity);
>     firstActivityCreated = true;
>   }

  

>  LOG  Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
>   "app_start_warm": {
>     "value": 1232.434
>   }
> }

  
  **savedInstanceState alway null and my app just warm start**

**Comment by marandaneto** [comment]
@dangdo1 its indeed an issue, not sure if on the RN SDK or Android SDK yet, will debug, thanks for the repro.

**Comment by marandaneto** [comment]
@dangdo1 I've dug into it and found out the root cause, App start was always reported as Warm start but the numbers were correct anyway.
PR is in place https://github.com/getsentry/sentry-react-native/pull/1985
