### ISSUE TITLE
Way to avoid an Android app crash being logged on Sentry Dashboard?

### ISSUE THREAD

**Issue by abitling** [getsentry/sentry-react-native#1969]
### Environment
- OS: MacOS
- Platform: Android

How do you use Sentry?
I am Using Sentry SaaS (sentry.io) for crash reporting in my application and have the default configuration as mentioned in the documentation. I am trying to handle a native crash on the Android side using Thread.setDefaultUncaughtExceptionHandler in the onCreate lifecycle event of my launch Activity (MainActivity.java). I am using the following environment setup in my project.

Which SDK and version?
"react-native": "0.64.2"
"react": "17.0.1"
"@sentry/react-native": "^2.6.2"
"react-native-webview": "^11.3.2"

Link to the issue : 
I am using sentry.io, here is [link](https://sentry.io/share/issue/6bd0486d32a847ffb2320d5c1b3089d3/) to the issue being logged.

### Steps to Reproduce
- Create a react native app using react-native cli For Eg. "npx react-native init AwesomeApp" and implement any WebView based feature like in app browser. Also, setup Sentry with the default configuration as mentioned in the documentation.
- Implemented Thread.setUncaughtExceptionHandler to handle an Exception globally in MainActivity.java as follows : 

       @Override
        protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              originalHandler = Thread.getDefaultUncaughtExceptionHandler();
              Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
                    if (ExceptionUtils.containsMessage(throwable, getString("No WebView installed"))
                          || ExceptionUtils.containsMessage(throwable, getString("Cannot load WebView"))) {
                           // Show an informative alert to user
                           ...Handling logic
                   } else {
                       if (originalHandler != null) {
                          originalHandler.uncaughtException(thread, throwable);
                      }
                 }
             });
         }

- Disable the Android System WebView from System Settings.
- Launch the application.

### Expected Result
- App should not crash, instead should show an informative Alert to the user.
- Crash log should not be sent to Sentry dashboard as we are handling the Exception globally using Thread.setDefaultUncaughtExceptionHandler.

### Actual Result
- App doesn't crash and an informative Alert is shown to the user.
- Crash log is still being sent to Sentry dashboard.

**Comment by jennmueng** [comment]
@abitling You can set `enableNativeCrashHandling: false` just for Android while enabling it for iOS. For example:

```js

Sentry.init({
  ...
  enableNativeCrashHandling: Platform.OS !== "android"
})

```

**Comment by abitling** [comment]
@jennmueng Thanks for the response.

With the above config, the native crash handling will be completely disable for android but unfortunately thats not what I am looking for. I am looking for a way where I don't want the issue to be logged on the dashboard if it is being handled on the native side.

For eg. In the code snippet mentioned in the description of this issue, I am trying to handle the AndroidRuntimeException that contains "No WebView installed" or "Cannot load WebView" strings in the message. So, for this particular exception is there any way I can skip the crash reporting on Sentry Dashboard?

Any help is highly appreciated. Thanks

**Comment by abitling** [comment]
> @abitling You can set `enableNativeCrashHandling: false` just for Android while enabling it for iOS. For example:
> 
> ```js
> Sentry.init({
>   ...
>   enableNativeCrashHandling: Platform.OS !== "android"
> })
> ```

@jennmueng Thanks for the response.

With the above config, the native crash handling will be completely disable for android but unfortunately thats not what I am looking for. I am looking for a way where I don't want the issue to be logged on the dashboard if it is being handled on the native side.

For eg. In the code snippet mentioned in the description of this issue, I am trying to handle the AndroidRuntimeException that contains "No WebView installed" or "Cannot load WebView" strings in the message. So, for this particular exception is there any way I can skip the crash reporting on Sentry Dashboard?

Any help is highly appreciated. Thanks

**Comment by jennmueng** [comment]
I will hand this over to @marandaneto who would have more insight on the Android side here.

**Comment by marandaneto** [comment]
right now the only way to do it is to initialize the Native SDKs manually https://docs.sentry.io/platforms/react-native/manual-setup/native-init/
then you can set your own `beforeSend` callback for the Android SDK and filter out the exceptions you don't want https://docs.sentry.io/platforms/android/configuration/filtering/
