### ISSUE TITLE
App start tracking is replaced by navigation tracking (Route Change)

### ISSUE THREAD

**Issue by wbinarytree** [getsentry/sentry-react-native#1997]
### Environment

How do you use Sentry?
 self-hosted(Sentry 20.11.1)

Which SDK and version?
    "@sentry/react-native": "3.2.6"

### Steps to Reproduce

Sentry setup:

```

    const routingInstrumentation = new Sentry.ReactNavigationInstrumentation({
      routeChangeTimeoutMs: __DEV__ ? 50000 : 10000,
    });

    Sentry.init({
      dsn: dsn,
      debug: __DEV__,
      environment: environment,
      release: releaseName,
      dist: getBuildNumber(),
      tracesSampler: samplingContext => {
        return 1;
      },
      enableAutoSessionTracking: true,
      integrations: [
        new Sentry.ReactNativeTracing({
          routingInstrumentation: routingInstrumentation,
          }),
      ],
    });

    export default Sentry.wrap(App);
```

### Expected Result

Still use `App Start` as app start change but not `Route Change`

 
### Actual Result

`App Start` transaction replaced(or Rename?) to `Route Change`. 

 When disable routingInstrumentation :
![image](https://user-images.githubusercontent.com/7286338/148206310-8ed49eeb-0c9e-4abc-a47f-0608d32013e4.png)

When enable routingInstrumentation:
![image](https://user-images.githubusercontent.com/7286338/148206456-49459ad9-2b69-4a3a-bebe-1ec5ec2bb497.png)

**Comment by bruno-garcia** [comment]
Without the routing integration all you get is that app start transaction. With routing enable you get a transaction for each screen. The app start one is just replaces by the routing and that's by design

**Comment by jennmueng** [comment]
@wbinarytree Like @bruno-garcia said, the transaction should just be renamed to the initial route of the routing navigation. So if your initial route is "Home" then it the app start transaction should be named "Home". Although what's interesting here is that it's called "Route Change" and not the name of the initial route.

**Comment by jennmueng** [comment]
@wbinarytree Does this occur everytime? What is your intial route?

**Comment by wbinarytree** [comment]
@jennmueng @bruno-garcia Thx for the reply. I will check if my initial root is set up properly. And yes, it happens to me every time.

**Comment by bruno-garcia** [comment]
Added a note on the docs about the transaction name change: https://github.com/getsentry/sentry-docs/pull/4511

@carates pointed out:

> @bruno-garcia @imatwawana You should also mention here something about the cold/warm start metrics. In my case, once I integrated the auto instrumentation with the react-native navigation, the App Start transaction stopped being sent, and these columns/information is now missing.

This would be a bug though, as we need to continue to collect startup measurements even when using routing

**Comment by bruno-garcia** [comment]
@carantes worth noting only the transactions that happened when the app start will include this measurement. Transactions that happen as a result of a route change once the app is already running will not have it.

**Comment by marandaneto** [comment]
> @jennmueng @bruno-garcia Thx for the reply. I will check if my initial root is set up properly. And yes, it happens to me every time.

Hey, did you figure out what was going on?

> @bruno-garcia This would be a bug though, as we need to continue to collect startup measurements even when using routing

I've tested myself with and without the routing library and both setups send measurements, this issue is more about the naming of the transaction which is explained by https://github.com/getsentry/sentry-docs/pull/4511 and the screenshot also states the measurements for both transactions (with and w/o the routing library).

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
