### ISSUE TITLE
Source map upload for release seems to be overwriting previously uploaded source maps

### ISSUE THREAD

**Issue by kowalski** [getsentry/sentry-react-native#1998]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
    "@sentry/react-native": "^3.2.10",

### Steps to Reproduce

We are using CI to push out both Android and IOS releases to Google Play and Testflight respectively.
When I inspect releases in Sentry I can see that each release has always two sourcemap files uploaded.
I either have:
* ~/index.android.bundle
* ~/index.android.bundle.map

or

* ~/main.jsbundle
* ~/main.jsbundle.map

I never have all 4 artifacts uploaded. As a result, some incidents end up without nice backtraces and it seems random for which release I will have either Android or Ios working well.

My guess is that the randomness is caused by the fact that I'm doing both builds concurrently and **whichever ends last wins and overwrites the result of the previous one**.

### Expected Result

I would like to have all sourcemaps for both platforms for each release.

**Comment by jennmueng** [comment]
@kowalski Are the release names the same between the releases where the `index.android.bundle` files are present and the `main.jsbundle` ones are present? They should not be completely overwriting the artifacts in the release when uploading files of different names, and creating a release when it exists shouldn't overwrite it either. So what I think is happening is the release names might be different between the iOS and Android one.

Can I see a screenshot of the artifacts screen for each of the releases you mentioned like below: (Hover over the title so we can see the full name too)

<img width="1446" alt="Screen Shot 2022-01-07 at 3 21 30 PM" src="https://user-images.githubusercontent.com/30991498/148609042-9957946a-731f-468b-bd5f-631a295ea4ca.png">

**Comment by kowalski** [comment]
Ok, my bad.
I can see now IOS release is named 1.2.59+51 and Android one 1.2.59+53. The build number diverged.

Thank you for suggesting this.
