### ISSUE TITLE
Sentry doesn't work when Code-Push on my app.

### ISSUE THREAD

**Issue by dkahdwk** [getsentry/sentry-react-native#2006]
### Environment

Which SDK and version?

@sentry/react-native: 3.2.10

### Steps to Reproduce

When applied with a code push, the centry does not work.
I followed the guide, but the problem still remains...

my code:
```
    useEffect(() => {
        const checkAndGetCodePush = async () => {
            try {
                let result = await CodePush.checkForUpdate();
                if (result) {
                    setIsUpdating(true);
                    CodePush.sync(
                        {
                            installMode: CodePush.InstallMode.IMMEDIATE,
                            mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE
                        },
                        async (status) => {
                            switch (status) {
                                case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
                                    break;
                                case CodePush.SyncStatus.INSTALLING_UPDATE:
                                    break;
                                case CodePush.SyncStatus.UPDATE_INSTALLED:

                                // Sentry
                                await CodePush.getUpdateMetadata().then(update => {
                                    if (update) {
                                        Sentry.init({
                                            environment: 'production',
                                            dsn: myDsn,
                                            tracesSampleRate: 1.0,
                                            enableNative: false,
                                            release: `${update.appVersion}+codepush:${update.label}`,
                                            dist: update.label,
                                        });
                                    }
                                });
                                setIsUpdating(false);
                                    break;
                                case CodePush.SyncStatus.SYNC_IN_PROGRESS:
                                    break;
                            }
                        },
                        (progress) => {
                            setSyncProgress(progress);
                        },
                    );
                } else {

                    await CodePush.getUpdateMetadata().then(update => {
                        if (update) {
                            Sentry.init({
                                environment: 'production',
                                dsn: myDsn,
                                tracesSampleRate: 1.0,
                                enableNative: false,
                                release: `${update.appVersion}+codepush:${update.label}`,
                                dist: update.label,
                            });
                        }
                    });
                    setIsUpdating(false);
                }
            } catch (err: any) {
                setIsUpdating(false);
            }
    }, []);


   ....


  return Sentry.wrap(codePush(codePushOptions)(App));
```

Action code push(android):
```
appcenter codepush release-react -a [name]/[app_name-android] -d Production --sourcemap-output --output-dir ./build
```

Currently, Sentry is not sending issues in my app.
However, except for the Code-Push, the sentry operate normally.
I don't know what the problem is with the code...

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by marandaneto** [comment]
@dkahdwk thanks for reporting.

I'm not entirely sure if it's any Sentry related, is that the case that the `getUpdateMetadata` never gets executed or `update` is null or false and the SDK never gets init.? then its related to CodePush and not Sentry at all

**Comment by dkahdwk** [comment]
@marandaneto `getUpdateMetadata` is running properly. The update also received true and confirmed that Sentry.init was running. Still, when the code push is combined, it does not work, and when the code push is removed, the sentry operates normally...

**Comment by marandaneto** [comment]
@dkahdwk what does not work mean, what's expected and it does not happen?

CodePush and Sentry is just a way to handle the release/dist and upload the source maps file, but sending events don't change along with CodePush or not.
Also, be sure that the uploaded JS bundles to CodePush should contain the code initing Sentry and so on.

Can you provide a minimal reproducible example? thanks.

**Comment by dkahdwk** [comment]
@marandaneto The only reproducible example is the code listed above. Let me check the bundle.

**Comment by marandaneto** [comment]
> @marandaneto The only reproducible example is the code listed above. Let me check the bundle. Do you know how to check the bundle?

Please create a minimal reproducible example (empty - only with necessary files) and upload it to Github and I can try to reproduce it and see what's going on.

If I create a project myself and simply set up Sentry + CodePush, everything works, it could be related to your Sentry or CodePush setup only.

**Comment by jennmueng** [comment]
@dkahdwk Like @marandaneto said a reproducable example would help. But from what I can see here, here are a couple of issues with the code snippet you provided:

1. Because your `CodePush.sync` will install the update immediately due to `CodePush.InstallMode.IMMEDIATE`, calling `Sentry.init` when the status is `UPDATE_INSTALLED` is useless as the app would be refreshed anyways.
2. We highly recommend against calling `Sentry.init` inside a React.useEffect as this executes Sentry way after the React app starts and will not capture any errors until alot later in the app.
3. Unrelated to this issue but you want the `Sentry.wrap` call inside of the code push call.
4. The glaring error I see In the code snippet above, assuming this is not your actual code but just a copy-paste, is that you aren't calling the function `checkAndGetCodePush` inside your useEffect, you're just defining it.

Also, what is not working, are you throwing an error somewhere and it is not captured, a session isn't logged, or what are you using to determine if Sentry is working or not.

**Comment by dkahdwk** [comment]
> > @marandaneto 재현 가능한 유일한 예는 위에 나열된 코드입니다. 번들을 확인하겠습니다. 번들 확인하는 방법을 알고 있습니까?
> 
> 최소한의 재현 가능한 예제(비어 있음 - 필요한 파일만 있음)를 만들고 Github에 업로드하세요. 재현해 보고 무슨 일이 일어나는지 확인할 수 있습니다.
> 
> 내가 직접 프로젝트를 만들고 단순히 Sentry + CodePush를 설정하면 모든 것이 작동하며 Sentry 또는 CodePush 설정에만 관련될 수 있습니다.

It's a company project, so it's hard to upload that part separately.
The code examples are all the ones I put up above...
Thank you for your answer!

**Comment by dkahdwk** [comment]
> > @marandaneto The only reproducible example is the code listed above. Let me check the bundle. Do you know how to check the bundle?
> 
> Please create a minimal reproducible example (empty - only with necessary files) and upload it to Github and I can try to reproduce it and see what's going on.
> 
> If I create a project myself and simply set up Sentry + CodePush, everything works, it could be related to your Sentry or CodePush setup only.

It's a company project, so it's hard to upload that part separately.
The code examples are all the ones I put up above...
Thank you for your answer!

**Comment by dkahdwk** [comment]
> @dkahdwk Like @marandaneto said a reproducable example would help. But from what I can see here, here are a couple of issues with the code snippet you provided:
> 
> 1. Because your `CodePush.sync` will install the update immediately due to `CodePush.InstallMode.IMMEDIATE`, calling `Sentry.init` when the status is `UPDATE_INSTALLED` is useless as the app would be refreshed anyways.
> 2. We highly recommend against calling `Sentry.init` inside a React.useEffect as this executes Sentry way after the React app starts and will not capture any errors until alot later in the app.
> 3. Unrelated to this issue but you want the `Sentry.wrap` call inside of the code push call.
> 4. The glaring error I see In the code snippet above, assuming this is not your actual code but just a copy-paste, is that you aren't calling the function `checkAndGetCodePush` inside your useEffect, you're just defining it.
> 
> Also, what is not working, are you throwing an error somewhere and it is not captured, a session isn't logged, or what are you using to determine if Sentry is working or not.

App.tsx
```
import React from 'react';
....
let codePushOptions = {
    checkFrequency: codePush.CheckFrequency.MANUAL
};

codePush.getUpdateMetadata().then(update => {
    if (update) {
        Sentry.init({
            environment: 'production',
            dsn: mydsn,
            tracesSampleRate: 1.0,
            enableNative: false,
            release: `${update.appVersion}+codepush:${update.label}`,
            dist: update.label,
        });
    }
});

const App = () => {
  ...
}

export default Sentry.wrap(codePush(codePushOptions)(App));
```

Testing code
```
useEffect(() => {
  Sentry.captureMessage("TEST!");
}, []);
```

Even if you modify it in this way, the results do not change.
However, if you erase the codepush content, Sentry.captureMessage works normally!

Example of deleting a code push:
```
...
export default Sentry.wrap(App);
```

**Comment by jennmueng** [comment]
@dkahdwk Oh now I see, I did not think this was the issue at first so I said it was unrelated in my point #3 but I see it now. You said it works when you "delete a code push" into 

```js
...
export default Sentry.wrap(App);
```

right?

You need the Sentry.wrap call to be **inside** of the codepush call, to be clear, like below:

```js
export default codePush(codePushOptions)(Sentry.wrap(App));
```

**Comment by dkahdwk** [comment]
@jennmueng 
```
export default codePush(codePushOptions)(Sentry.wrap(App));
```
As you told me, I modified the code and sent a code push, but the sentry issue is still not coming up...
I don't know the cause.

**Comment by jennmueng** [comment]
@dkahdwk pass `debug: true` to your call to `Sentry.init` and also add a console.log to where you're capturing the error for me:

```js
useEffect(() => {

  // It's not working. But, it works when you remove the code push.
  Sentry.captureMessage("TEST!");
  console.log("TEST");
}, []);
```

And please paste the logs for me, so I can see if the `console.log("TEST");` is logged before the sentry debug messages or note.

**Comment by Natural0413** [comment]
1. useEffect(() => {

  // It's not working. But, it works when you remove the code push.
  Sentry.captureMessage("TEST!");
  console.log("TEST");
}, []);

**Comment by dkahdwk** [comment]
@jennmueng 

Add:

```jsx
codePush.getUpdateMetadata().then(update => {
    if (update) {
        Sentry.init({
            environment: 'production',
            dsn: mydsn,
            tracesSampleRate: 1.0,
            enableNative: false,
            debug: true, // add!
            release: `${update.appVersion}+codepush:${update.label}`,
            dist: update.label,
        });
    }
});
```
and,
useEffect works well, but sentry still does not work.

**Comment by jennmueng** [comment]
@dkahdwk I need you to paste the logs from your react native console after adding the `debug: true` and the console log.

**Comment by dkahdwk** [comment]
@jennmueng 

I feel dejected... It was solved when I changed enable Native to true...
```jsx
        Sentry.init({
            ...
            enableNative: true,
        });
```

You helped me so kindly. It gave me strength!

**Comment by jennmueng** [comment]
Hmm I'll have to look into see if I can reproduce the issue with codepush and enableNative: false then.

**Comment by dkahdwk** [comment]
@jennmueng Yes, in my case, I tested the code push more than 100 times. So I can be sure. When enableNative was false, it could not be uploaded to the sentry release, but when true, it immediately went up to the release and issues were printed.

**Comment by shubhamdeol** [comment]
> jennmueng

Any update on this. 
I am using enableNative with `false` value with codepush. 
When I am triggering the crash on native side before javascript init I am getting the info on dashboard.
But crashes/errors after javascript init are not getting received
