### ISSUE TITLE
Android fails to build with React Native 0.67.1 in release mode

### ISSUE THREAD

**Issue by SMJ93** [getsentry/sentry-react-native#2021]
### Environment

We are using `"@sentry/react-native": "3.2.13"` with `"react-native": "0.67.1"`.

### Steps to Reproduce

It was working as expected with React Native 0.66, but since we have upgraded to 0.67.1 it the release build fails. It works as expected in debug mode.

Release build error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:addSentryProguardSettingsForRelease' (type 'SentryProguardConfigTask').
  - In plugin 'io.sentry.android.gradle' type 'io.sentry.android.gradle.SentryProguardConfigTask' property 'applicationVariant' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Looks like the gradle update to 7.2.0 in the react native upgrade might have caused this?

### Expected Result

The release build works

### Actual Result

It fails, see above.

**Comment by jennmueng** [comment]
I will try to reproduce this and get back to you by today, in the meantime cc @marandaneto

**Comment by jennmueng** [comment]
Looks like you're using our gradle plugin which isn't included by default in our React Native SDK. You should [update it to the latest version in your `build.gradle`.](https://docs.sentry.io/platforms/android/gradle/#install) and please let me know if the error persists.

**Comment by SMJ93** [comment]
Thanks @jennmueng! Updating from `1.7.35` to `2.1.5` fixed the issue! Here is the migration guide incase anyone else has a similar issue:

https://docs.sentry.io/platforms/android/migration/#migrating-from-iosentrysentry-android-gradle-plugin-1x-to-iosentrysentry-android-gradle-plugin-200

**Comment by marandaneto** [comment]
I've just checked on Android and iOS and it works using the latest Sentry RN SDK and RN 0.67.1
