### ISSUE TITLE
Update from 2.6 to 3.2 causing slow transitions

### ISSUE THREAD

**Issue by Domeee** [getsentry/sentry-react-native#2036]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
```
System:
    OS: Linux 5.16 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.04 GB / 30.99 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.asdf/installs/nodejs/16.1.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/installs/nodejs/16.1.0/.npm/bin/yarn
    npm: 7.11.2 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 20220123.190932.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-211.7628.21.2111.8092744
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

```
"dependencies": {
    "@invertase/react-native-apple-authentication": "2.1.5",
    "@react-native-async-storage/async-storage": "1.15.15",
    "@react-native-firebase/app": "14.2.2",
    "@react-native-firebase/remote-config": "14.2.2",
    "@react-native-google-signin/google-signin": "7.0.4",
    "@segment/analytics-react-native": "1.5.0",
    "@sentry/react-native": "3.2.12",
    "@stripe/stripe-react-native": "0.2.3",
    "base-64": "1.0.0",
    "date-fns": "2.28.0",
    "easy-peasy": "5.0.4",
    "hyphenation.de": "0.2.1",
    "hypher": "0.2.5",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-device-info": "8.4.8",
    "react-native-elements": "4.0.0-beta.0",
    "react-native-fbsdk-next": "6.2.0",
    "react-native-iap": "7.5.5",
    "react-native-keyboard-spacer": "0.4.1",
    "react-native-keychain": "8.0.0",
    "react-native-linear-gradient": "2.5.6",
    "react-native-notifications": "4.1.3",
    "react-native-permissions": "3.2.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-share": "7.3.3",
    "react-native-splash-screen": "3.3.0",
    "react-native-svg": "12.1.1",
    "react-native-svg-charts": "5.4.0",
    "react-native-url-polyfill": "1.3.0",
    "react-native-vector-icons": "9.0.0",
    "react-native-webview": "11.16.0",
    "react-router-native": "5.2.0",
    "semver": "7.3.5"
  },
  "devDependencies": {
    "@babel/core": "7.16.7",
    "@babel/runtime": "7.16.7",
    "@storybook/react-native": "5.3.25",
    "@types/base-64": "1.0.0",
    "@types/node": "17.0.9",
    "@types/react": "17.0.38",
    "@types/react-native": "0.66.12",
    "@types/react-native-keyboard-spacer": "0.4.2",
    "@types/react-native-share": "3.3.3",
    "@types/react-native-svg-charts": "5.0.12",
    "@types/react-router-native": "5.1.2",
    "@types/semver": "7.3.9",
    "@typescript-eslint/eslint-plugin": "5.10.0",
    "@typescript-eslint/parser": "5.10.0",
    "eslint": "8.7.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-react": "7.28.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "eslint-watch": "8.0.0",
    "metro-react-native-babel-preset": "0.66.2",
    "prettier": "2.5.1",
    "react-native-clean-project": "4.0.0",
    "react-native-config": "1.4.5",
    "typescript": "4.5.4"
  }
```

### Steps to Reproduce
1. All navigation transitions perform fast (React Router Native in use)
2. Update a React Native project from @sentry/react-native": "2.6.0" to @sentry/react-native": "3.2.12".

### Expected Result

No decline in transition speed.

### Actual Result

All navigation transitions perform extremely slow (2-3s).

Any help in troubleshooting this issue is greatly appreciated. For now, we had to remove the sentry integration in react native.

Cheers

**Comment by marandaneto** [comment]
@Domeee Thanks for reporting.

Can you enable the `debug` property and copy-paste logs?
Do you have performance tracking enabled?

**Comment by Domeee** [comment]
Thanks @marandaneto for reaching out!

Performance tracking is not enabled and we do not intend to use it for now.

Logs
```
LOG  Sentry Logger [Log]: Unhandled promise rejections will be caught by Sentry.
 LOG  Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [Log]: Integration installed: Release
 LOG  Sentry Logger [Log]: Integration installed: InboundFilters
 LOG  Sentry Logger [Log]: Integration installed: FunctionToString
 LOG  Sentry Logger [Log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [Log]: Integration installed: LinkedErrors
 LOG  Sentry Logger [Log]: Integration installed: Dedupe
 LOG  Sentry Logger [Log]: Integration installed: UserAgent
 LOG  Sentry Logger [Log]: Integration installed: EventOrigin
 LOG  Sentry Logger [Log]: Integration installed: SdkInfo
 LOG  Sentry Logger [Log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [Log]: Integration installed: RewriteFrames
 LOG  Sentry Logger [Log]: Integration installed: DeviceContext
```

**Comment by marandaneto** [comment]
@Domeee can you provide logs of the SDK while transiting from different views?
Also, please share the code snippet of your SDK init.

**Comment by Domeee** [comment]
@marandaneto The are no logs while transitioning to a different view.

SDK init
```
  useEffect(() => {
    Sentry.init({
      dsn: "URI",
      environment: Config.SENTRY_ENVIRONMENT, // replace at buildtime
      release: "app" + packageJson.version,
      debug: true,
    });
  }, []);
```

**Comment by marandaneto** [comment]
@Domeee have you tried to init Sentry outside of the `useEffect`?
@jennmueng ideas?

**Comment by Domeee** [comment]
@marandaneto init Sentry outside `useEffect` and outside the render scope of the component leads to no improvement in transition performance.

**Comment by Domeee** [comment]
@marandaneto I was able to pin down the problem. All my http requests via fetch take 10x longer with the sdk enabled. If I disable promise patching via `patchGlobalPromise: false` the app acts as expected. HTH

**Comment by bruno-garcia** [comment]
This bool is on our code base in this repo:

https://github.com/getsentry/sentry-react-native/blob/8d3d9aefd60ac7a8a54d5ab29b871b807849c465/src/js/integrations/reactnativeerrorhandlers.ts#L61-L63

**Comment by marandaneto** [comment]
ping @jennmueng

**Comment by jennmueng** [comment]
> @marandaneto I was able to pin down the problem. All my http requests via fetch take 10x longer with the sdk enabled. If I disable promise patching via `patchGlobalPromise: false` the app acts as expected. HTH

@Domeee Do you know if you use any other library related to promises in your app? By default I can't see how we would be slowing down the performance by much as we only instrument promise rejections.

**Comment by Domeee** [comment]
@jennmueng Thanks for reaching out. The only dependency that comes to mind is `"react-native-url-polyfill": "1.3.0"`. But I don't know if that lib patches anything related to promises.

**Comment by marandaneto** [comment]
@Domeee can you provide a minimal reproducible example that exemplifies this problem using `patchGlobalPromise` or not? I just want to be sure that this isn't an environmental in your setup, or if that would happen in any brand new project (fresh template), thanks.

**Comment by jennmueng** [comment]
@Domeee A minimal reproducable example would be perfect, been trying to reproduce this with multiple tries and see no noticable difference. Do you have a promise in a `useEffect` in a screen or something and it occurs there I assume? Or does this occur on every screen transition?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
