### ISSUE TITLE
Users see transactions name `Route Change` in Sentry.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#2051]
Users see transactions name `Route Change` in Sentry.

It seems this is a template here that should be replaced with the right route name:

https://github.com/getsentry/sentry-react-native/blob/4fd13137fe71984d1166c33198076da9db28f158/src/js/tracing/utils.ts#L14-L19

Router integration used: React Navigation

**Comment by ludwig-pro** [comment]
#2066 

Look like partially fixed for me
