### ISSUE TITLE
Sentry ignores .env.production and uses standard env file

### ISSUE THREAD

**Issue by snips11** [getsentry/sentry-react-native#2064]
### Environment

How do you use Sentry?
SAAS

Which SDK and version?
React Native

### Steps to Reproduce

Install sentry and install react-native-dot-env. Set up .env and .env.production files. Set up the correct babel config.

<img width="400" alt="Screenshot 2022-02-15 at 00 14 46" src="https://user-images.githubusercontent.com/17324531/153968556-a7300d36-bd11-4a8c-82fc-bcd7726e44a7.png">

### Expected Result

We have a mature React Native app running both iOS and Android and have installed Sentry for the first time. We have used [React Native Dot Env](https://github.com/goatandsheep/react-native-dotenv) to manage our environmental variables for debug and release in the past. I was expecting for Sentry to honour the existing env config in place.

Is there a solution in place for React Native to allow release and debug variables?

### Actual Result

Even in production builds the standard .env is used rather than .env.production. We are happy to work another way to accommodate for the way Sentry works but having debug and release env variables are quite important.

**Comment by marandaneto** [comment]
Dup of https://github.com/getsentry/sentry-react-native/issues/1888

**Comment by snips11** [comment]
Hi @marandaneto is there any documentation/ examples of how env variables work with Sentry (Sentry properties) and React Native?

**Comment by marandaneto** [comment]
> Hi @marandaneto is there any documentation/ examples of how env variables work with Sentry (Sentry properties) and React Native?

https://docs.sentry.io/product/cli/configuration/
