### ISSUE TITLE
 react profiler with react-native don't generate any span (ui.react.mount, ui.react.render, and ui.react.update)

### ISSUE THREAD

**Issue by ludwig-pro** [getsentry/sentry-react-native#2065]
Hello ! I have some struggle with react-profiler ! 

### Environment

How do you use Sentry?
**Sentry SaaS (sentry.io)**

Which SDK and version?
```js
// package.json
    "@sentry/react-native": "3.2.13",

// podfile.lock
  - RNSentry (3.2.13):
    - React-Core
    - Sentry (= 7.9.0)
     
  - Sentry (7.9.0):
    - Sentry/Core (= 7.9.0)
  - Sentry/Core (7.9.0)
```

also I use **react-native-navigation**

### Steps to Reproduce
I try to use the react profiler with react-native as describe in the automatic instrumentation [here](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-profiler
) but there are no spans generates by the profiler. I try with the hook and the HoC

implementation :
![image](https://user-images.githubusercontent.com/62896243/154137155-14c8382b-bb6c-4b6e-983a-743995f66fac.png)

![image](https://user-images.githubusercontent.com/62896243/154136922-c696322b-bfd6-48c4-bf94-d6c2f27761e9.png)

### Expected Result
Generates spans the three different kinds of op-codes: ui.react.mount, ui.react.render, and ui.react.update.

### Actual Result
![image](https://user-images.githubusercontent.com/62896243/154136720-ce88c565-d0f7-43c6-89f6-a8e54b8ca056.png)

**Comment by marandaneto** [comment]
cc @jennmueng

**Comment by marandaneto** [comment]
> after investigation, I think it's relative to automatic instrumentation with react-native-navigation because the transaction is never ended. If I trigger a manual transaction then finish it, I find the span event react.mount

By that do you mean if not using react native navigation, it works? thanks.

**Comment by marandaneto** [comment]
> Hey ! I thought it's related to #2066, and the transaction override ! I Will try the latest release and comeback to you :)

any news here? thanks.

**Comment by ludwig-pro** [comment]
hey ! We will ship an alpha app tomorrow, with sentry upgrade. We will compare a custom profiler tracking that we made ourselves (with sentry custom trace) with the Sentry Profiler component.

**Comment by jennmueng** [comment]
@ludwig-pro The transaction you were looking at in the screenshot above seems to be sent from the iOS native layer, and the profiler will only attach spans to transactions sent from the JS layer, are you getting any transactions sent from the routing instrumentation for react-native-navigation? If yes, can I please see that one? Thanks!
