### ISSUE TITLE
There was 1 problem processing this event, Source code was not found.

### ISSUE THREAD

**Issue by shubhnik** [getsentry/sentry-react-native#2081]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
sentry.io

Which SDK and version?
e.g: "@sentry/react-native": "2.5.2"

### Steps to Reproduce

Any issue being reported on the Sentry dashboard comes up with an error `There was 1 problem processing this event`. My sentry initialization looks like this:

```
Sentry.init({
    dsn: __CONFIG__.SENTRY_DSN,
    environment: __CONFIG__.STAGE,
    release: `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
    beforeSend: filterSentryBreadcrumbs,
  });
```

### Expected Result

The error should not be shown as source maps and source bundles are present on Sentry.

### Actual Result

1. The correct code of line where the error is originating is shown, but the below red error is also shown on the Sentry.

2. Earlier in the previous release, it used to show the error as `[messaging/unknown] SERVICE_NOT_AVAILABLE`, and in the current release it shows it as `[messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS`. Any idea why is this change happening, if this can help in finding the root cause.

<img width="967" alt="Screenshot 2022-02-21 at 11 06 09 PM" src="https://user-images.githubusercontent.com/9150371/155003800-5de7b38c-875d-4c70-82a4-09511bacc6df.png">
<img width="947" alt="Screenshot 2022-02-21 at 11 08 20 PM" src="https://user-images.githubusercontent.com/9150371/155004087-c85a4a02-4942-42c6-b172-4b528d428e20.png">
<img width="944" alt="Screenshot 2022-02-21 at 11 15 41 PM" src="https://user-images.githubusercontent.com/9150371/155004981-dd5a38a2-0d21-468e-b755-e432b4012523.png">

**Comment by jennmueng** [comment]
@shubhnik You need to specify a `dist` value both on the sourcemap artifacts and passed to the `Sentry.init` method as well for sourcemaps to correctly be matched.

Read more here: https://docs.sentry.io/platforms/react-native/sourcemaps/#1-set-the-release-and-distribution

**Comment by shubhnik** [comment]
@jennmueng I will try to add `dist` while initialization. But for source maps, we are using the build scripts provided by the Sentry only. In the screenshot below I believe the source maps are tagged properly with the correct `dist`
<img width="897" alt="Screenshot 2022-02-22 at 1 27 58 PM" src="https://user-images.githubusercontent.com/9150371/155087630-319ed415-b5df-49b6-bdad-165eddbecad6.png">
.

**Comment by marandaneto** [comment]
@shubhnik you can also remove this line `release: `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,` since you are using the scripts provided by the SDK, either removing the `release` or adding the `dist` would work.

**Comment by shubhnik** [comment]
@marandaneto [here](https://sentry.io/organizations/rzp/issues/3033834316/?environment=production&project=6037281&query=is%3Aunresolved+release.version%3A1.52.1&statsPeriod=14d) is the issue. The weird part is that it was working fine earlier(we followed the docs), started getting this error message on the last few app releases only. Also in the latest app release, we updated to `@sentry/react-native: 3.2.10`.

**Comment by kamilogorek** [comment]
I'd assume that `InternalBytecode.js` is not coming from your sourcecode, thus it should be marked as non in-app frame.
You can configure it directly in your Sentry UI `[Project] > Settings > Issue Grouping > Stack Trace Rules` with this rule:

```
stack.abs_path:**/InternalBytecode.js -app
```

Read more about it here https://docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules/

**Comment by marandaneto** [comment]
Related to https://github.com/getsentry/sentry-react-native/issues/1845 as well
@shubhnik have you tried upgrading your RN version?

**Comment by shubhnik** [comment]
@marandaneto we are on react-native `0.65.2`. This is quite a recent version. Or do you want me to update to a more recent version because it's not sure if that will fix it as per the above thread?

@kamilogorek other than this, could you find any issue that could be causing this error?

I have one suspect, this somewhat overlaps with the timeline since we are facing the above error. We recently integrated [this](https://github.com/DiederikvandenB/apollo-link-sentry) plugin in our Apollo library and it introduced an issue where the file name was incorrectly reported like this:
<img width="394" alt="Screenshot 2022-02-11 at 1 14 44 PM" src="https://user-images.githubusercontent.com/9150371/157000204-16f5e0fc-921f-4f2d-b740-92f95823dfde.png">
We fixed this by removing transaction tag in recent release, but it still tags new issues with old one with incorrect file names, could you help us in decoupling the new with previous issues, maybe it can fix this?

**Comment by marandaneto** [comment]
> I'd assume that `InternalBytecode.js` is not coming from your sourcecode, thus it should be marked as non in-app frame. You can configure it directly in your Sentry UI `[Project] > Settings > Issue Grouping > Stack Trace Rules` with this rule:
> 
> ```
> stack.abs_path:**/InternalBytecode.js -app
> ```
> 
> Read more about it here [docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules](https://docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules/)

@untitaker do you think this should be a general rule for RN projects? since we can't mark that as not in App at runtime?

**Comment by marandaneto** [comment]
> @marandaneto we are on react-native `0.65.2`. This is quite a recent version. Or do you want me to update to a more recent version because it's not sure if that will fix it as per the above thread?

No, apparently `InternalBytecode` is a known issue, the RN SDK sets that, I believe you should just ignore it.

**Comment by kamilogorek** [comment]
@shubhnik im not sure what's the question here tbh. As for grouping, the plugin you linked is overriding default fingerprint, which causes new groups to pop up - https://github.com/DiederikvandenB/apollo-link-sentry/blob/master/src/sentry.ts
See https://docs.sentry.io/platforms/javascript/usage/sdk-fingerprinting/ for how it works.

**Comment by marandaneto** [comment]
Since the original question was answered, I'll close it, @shubhnik please open a new issue with a detailed description in case you experience new issues, thanks.
