### ISSUE TITLE
React Native for Web

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2083]
https://github.com/necolas/react-native-web#readme

**Comment by chazmuzz** [comment]
Is this on the roadmap?  We have an Expo app which is deployed to iOS, Android and Web.  We would like to be able to use the automatic navigator instrumentation for web.

**Comment by marandaneto** [comment]
@chazmuzz it should work for most of the things out of the box (it's not tested tho).
Disable `enableNative` when initing the SDK.
You'll likely need to upload source maps manually.

**Comment by mikevercoelen** [comment]
@marandaneto It would probably make sense to add documentation on how to cover `react-native-web` and adding `ReactNavigationInstrumentation`.

@chazmuzz 

We are using `sentry-expo` which means we have to `Sentry.Native.xxx` or `Sentry.Browser.xxx` but in web, `Sentry.Native.ReactNativeTracing` is not exported.

I got it working by importing directly:

```
import { ReactNativeTracing } from '@sentry/react-native/dist/js/tracing/reactnativetracing';
import { ReactNavigationInstrumentation } from '@sentry/react-native/dist/js/tracing/reactnavigation';
```

Hope this is useful for others.

**Comment by krystofwoldrich** [comment]
@mikevercoelen I don't know why `Sentry.Native.ReactNativeTracing` doesn't work.

But `@sentry/react-native` exports both [`ReactNativeTracing`](https://github.com/getsentry/sentry-react-native/blob/e60e894b753832728b016e47d398df4d0eee2439/src/js/index.ts#L77) and `ReactNavigationInstrumentation `.

So the import should be as simple as:
```js
import { ReactNativeTracing, ReactNavigationInstrumentation } from '@sentry/react-native';
```

**Comment by mikevercoelen** [comment]
Got it, I was skeptical about it relying on any native stuff so out of precaution I took the direct import approach. Thanks!

**Comment by mikevercoelen** [comment]
> @mikevercoelen I don't know why `Sentry.Native.ReactNativeTracing` doesn't work.
> 
> But `@sentry/react-native` exports both [`ReactNativeTracing`](https://github.com/getsentry/sentry-react-native/blob/e60e894b753832728b016e47d398df4d0eee2439/src/js/index.ts#L77) and `ReactNavigationInstrumentation `.
> 
> So the import should be as simple as:
> 
> ```js
> import { ReactNativeTracing, ReactNavigationInstrumentation } from '@sentry/react-native';
> ```

Actually no this doesn't work and kills our build, so I've gone back to the my original setup.

```


./node_modules/@sentry/react-native/dist/js/sdk.js 106:16
--
  | Module parse failed: Unexpected token (106:16)
  | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | \|     const RootApp = (appProps) => {
  | \|         var _a;
  | >         return (<TouchEventBoundary {...((_a = options === null \|\| options === void 0 ? void 0 : options.touchEventBoundaryProps) !== null && _a !== void 0 ? _a : {})}>
  | \|         <ReactNativeProfiler {...profilerProps}>
  | \|           <RootComponent {...appProps}/>
  | ./node_modules/@sentry/react-native/dist/js/touchevents.js 41:16
  | Module parse failed: Unexpected token (41:16)
  | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | \|      */
  | \|     render() {
  | >         return (<View style={touchEventStyles.wrapperView}
  | \|         // eslint-disable-next-line @typescript-eslint/no-explicit-any
  | \|         onTouchStart={this._onTouchStart.bind(this)}>
  | Failed to compile.
  |  
  | ./node_modules/@sentry/react-native/dist/js/sdk.js 106:16
  | Module parse failed: Unexpected token (106:16)
  | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | \|     const RootApp = (appProps) => {
  | \|         var _a;
  | >         return (<TouchEventBoundary {...((_a = options === null \|\| options === void 0 ? void 0 : options.touchEventBoundaryProps) !== null && _a !== void 0 ? _a : {})}>
  | \|         <ReactNativeProfiler {...profilerProps}>
  | \|           <RootComponent {...appProps}/>
  | error Command failed with exit code 1.
```

It's probably fixable with adding webpack loading setup, but I don't want to go that route.

**Comment by krystofwoldrich** [comment]
@mikevercoelen Thanks for giving it a try and for the log.

**Comment by krystofwoldrich** [comment]
@ansh The naming is a bit unfortunate but [`Browser.wrap`](https://github.com/getsentry/sentry-javascript/blob/2aa4e94b036675245290596884959e06dcced044/packages/browser/src/helpers.ts#L43) is very different from `Native.wrap`. These can't be interchanged.

Use `wrap` on your App component for mobile (not for web).

**Comment by ansh** [comment]
Ah. I thought them to be the same. Thanks for the heads up! @krystofwoldrich 

I have changed my code to only `wrap` with `Native.wrap`.

**Comment by krystofwoldrich** [comment]
@ansh Good to hear,
if you have any other questions/issues feel free to ask here or on our [Discord](https://discord.com/invite/sentry).

**Comment by krystofwoldrich** [comment]
Since https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0 the SDK supports React Native Web, both with and without Expo.
