### ISSUE TITLE
Getting lots of Command PhaseScriptExecution failed with a nonzero exit code in Xcode since moving to Monterey

### ISSUE THREAD

**Issue by mungbeans** [getsentry/sentry-react-native#2086]
I'm trying to build the same project as I've been building for months, the difference is now I'm on OS Monterey.

Occasionally it succeeds, but very very very frequently (and without changing a damn thing) the build fails with 

r/Xcode/DerivedData/XXXProject-dgyskfgwiispgibvghbrmmwksqza/Build/Intermediates.noindex/XXXProject.build/Debug-iphoneos/XXX.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 5: 78574 Killed: 9               ../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh

**Comment by marandaneto** [comment]
@mungbeans please update your issue with the [bug report](https://github.com/getsentry/sentry-react-native/issues/new?assignees=&labels=&template=BUG_REPORT.md) template.

**Comment by marandaneto** [comment]
@mungbeans any update on this? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
