### ISSUE TITLE
app:///index.bundle?platform=ios&dev=true&minify=false

### ISSUE THREAD

**Issue by HacerBusraKILIC** [getsentry/sentry-react-native#2103]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 3.2.12)
- [ ]  `react-native-sentry` (<= 0.43.2)

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/turkcell-iletisim/issues/3047830463/?project=6156519&query=is%3Aunresolved

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: 'https://8582ba51b23647b09378cd253e942deb@o1040061.ingest.sentry.io/6156519',
    tracesSampleRate: 1.0,
    release: '1.13.0',
    dist: `1.13.0.0`,
    debug: true,
});
```
---
**I have following issue:**
General all issues checked.

**Steps to reproduce:**
- npx react-native bundle --dev true --platform ios --entry-file index.ios.js --bundle-output main.jsbundle --sourcemap-output main.jsbundle.map
- npx react-native bundle --dev true --platform android --entry-file index.android.js  --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map
- ./node_modules/@sentry/cli/bin/sentry-cli releases --org turkcell-iletisim  --project bip-meet-mobile files 1.13.0  upload-sourcemaps --dist 13 --strip-prefix "~/" main.jsbundle main.jsbundle.map --validate
- ./node_modules/@sentry/cli/bin/sentry-cli releases --org turkcell-iletisim  --project bip-meet-mobile files 1.13.0  upload-sourcemaps --dist 13 --strip-prefix "~/" index.android.bundle index.android.bundle.map --validate

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/26281251/156652708-552add12-d083-4ace-905b-a70f78840fe2.png">

**Actual result:**

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/26281251/156650873-3db8e4cb-79b8-4e93-81c6-959711adc56b.png">

Where am I doing wrong?

**Comment by marandaneto** [comment]
@HacerBusraKILIC May I ask why are you passing custom values to `release`, `dist` and also calling `sentry-cli` manually?
The SDK should do everything automatically for you.

See https://docs.sentry.io/platforms/react-native/sourcemaps/
You init. your SDK with a custom dist `dist: 1.13.0.0`, but you use another dist to call sentry-cli `--dist 13`, they should match, exactly the same, as the docs say.

**Comment by HacerBusraKILIC** [comment]
@marandaneto Thanks for your response. When I examined the opened tasks, I came to these conclusions. I misunderstood some points. I edited as you said. 

Sentry.init({
    dsn: 'https://8582ba51b23647b09378cd253e942deb@o1040061.ingest.sentry.io/6156519',
    tracesSampleRate: 1.0
});

./node_modules/@sentry/cli/bin/sentry-cli releases --org turkcell-iletisim  --project bip-meet-mobile files 1.13.0  upload-sourcemaps --dist 1 --strip-prefix "~/" index.android.bundle index.android.bundle.map --validate

./node_modules/@sentry/cli/bin/sentry-cli releases --org turkcell-iletisim  --project bip-meet-mobile files 1.13.0  upload-sourcemaps --dist 1 --strip-prefix "~/" main.jsbundle main.jsbundle.map --validate

I reinstalled with commands.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/26281251/156773697-7a10e658-5b4b-4ac7-8d62-45dea690d4c1.png">

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/26281251/156773901-0b10cd3f-250a-46fa-a44c-ac0353d7e17d.png">

https://sentry.io/organizations/turkcell-iletisim/issues/3047830463/?project=6156519&query=is%3Aunresolved&statsPeriod=1h

the problem continues.

**Comment by marandaneto** [comment]
@HacerBusraKILIC I am confused, you are uploading source maps for Android, but testing on iOS?
`release` and `dist` must match.
Please follow our docs https://docs.sentry.io/platforms/react-native/sourcemaps/
You only need to execute those `sentry-cli` calls manually if you need to use custom release and dist, based on your SDK init, this is not the case.

> npx react-native init NameOfYourProject
> yarn add @sentry/react-native
> npx @sentry/wizard -i reactNative -p ios android
> 
> npx react-native run-ios --configuration Release
> npx react-native run-android --variant release

By only doing that, all of your source maps will be uploaded correctly, automatically, during the build time.

**Comment by HacerBusraKILIC** [comment]
@marandaneto I'm looking again

**Comment by jennmueng** [comment]
@HacerBusraKILIC If your js bundle is named `index.bundle` as I can see in your stack trace in the event, your source map files (in this case, for iOS) should be named `index.bundle` and `index.bundle.map` respectively. Currently they are `main.jsbundle` and `main.jsbundle.map`

**Comment by HacerBusraKILIC** [comment]
@jennmueng Thanks for your information. I see that I made a mistake in this part. I fixed most of my mistake with your help. I got confused with the document. :)

**Comment by marandaneto** [comment]
> @HacerBusraKILIC If your js bundle is named `index.bundle` as I can see in your stack trace in the event, your source map files (in this case, for iOS) should be named `index.bundle` and `index.bundle.map` respectively. Currently they are `main.jsbundle` and `main.jsbundle.map`

Do we have this in our troubleshooting page, that file name should match the uploaded bundles?

**Comment by jennmueng** [comment]
@marandaneto https://docs.sentry.io/platforms/react-native/troubleshooting/#source-maps Nope, not a bullet point there, I'll add it.
