### ISSUE TITLE
Incorrect issue grouping

### ISSUE THREAD

**Issue by shubhnik** [getsentry/sentry-react-native#2117]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
`"@sentry/react-native": "3.2.10"`
`"react-native": "0.65.2",`

### Steps to Reproduce
Errors are reported on production, but they are grouped together incorrectly.

### Expected Result

They should not be grouped together.

### Actual Result

Attaching URLs for two different errors but grouped together in a single issue:
1. Error message: [The id provided does not exist](https://sentry.io/organizations/rzp/issues/3003541205/events/c430013eb6aa4bf1ae8b216b85ee3bcc/?environment=production&project=6037281&query=is%3Aunresolved)
2. Error message: [User does not have a mobile number associated with the account
](https://sentry.io/organizations/rzp/issues/3003541205/events/79d9c7bd360e4855b708223643f5fa54/?environment=production&project=6037281&query=is%3Aunresolved)

Need help in understanding how to fix this incorrect grouping.

**Comment by marandaneto** [comment]
@shubhnik why do you think they should not be grouped together? what's the main difference between them?

**Comment by shubhnik** [comment]
@marandaneto these are errors with different error messages coming from different services. I want these to be separate, so I can ignore this issue which is of no concern to us `User does not have a mobile number associated with the account` and maybe close this issue `The id provided does not exist` later once fixed . And there might be many more different errors that might have been already fixed but grouped here under `No error message`

<img width="185" alt="Screenshot 2022-03-07 at 4 23 29 PM" src="https://user-images.githubusercontent.com/9150371/157017800-b6d0967b-0cfa-4ae4-aba0-d5a44e1888f7.png">

**Comment by marandaneto** [comment]
Sentry groups by stack traces, if you want to group or not group events, you can customize this behavior using [fingerprints](https://docs.sentry.io/platforms/react-native/usage/sdk-fingerprinting/)
You can also filter out events you don't want via the [beforeSend](https://docs.sentry.io/platforms/react-native/configuration/filtering/) callback.
