### ISSUE TITLE
Linked error are not symbolicated in Debug builds

### ISSUE THREAD

**Issue by Yupeng-li** [getsentry/sentry-react-native#2118]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
@sentry/react-native 3.2.13

### Steps to Reproduce

I need to report inner error when throwing exceptions, and [LinkedErrors](https://getsentry.github.io/sentry-javascript/classes/node.linkederrors.html) is the solution I found. To link two error, I assigned the inner error to the `cause` property of the final error.  

```js
//....
finalError.cause = innerError
Sentry.captureException(finalError)
```

When I tested, both the higher level error and the inner error are logged to sentry, however the stack trace was minified. But if I don't link them, the stack trace worked fine, so I think it's a bug. Here is a mini repo to reproduce the issue. https://github.com/Yupeng-li/sentry-test

The repo is a react-native app with two simple buttons: one throws an error and another throws an error with `cause` property. 

<img src="https://user-images.githubusercontent.com/31921080/157045959-d8963770-3fdd-416f-be68-e848d8ab9b82.png" width=20% height=20%>

Please modify the DSN before running it.

### Expected Result
Linked error should have original stack trace.  

This is what I got when I reported the error directly. (Throw an error)
![image](https://user-images.githubusercontent.com/31921080/157046821-591205de-66b8-401c-aefd-ebcc90bafb9d.png)

### Actual Result
This is what I got when I reported the error with `cause`.  (Throw an error with cause)
![linked errors](https://user-images.githubusercontent.com/31921080/157045491-60d53d30-ee51-46f5-9650-632fd8b90ad7.jpg)

**Comment by marandaneto** [comment]
This integration is within the [node](https://github.com/getsentry/sentry-javascript/tree/master/packages/node) package, wondering if that makes any difference.
@AbhiPrasad or @kamilogorek do you know what's going on? thanks

**Comment by AbhiPrasad** [comment]
This is strange, it seems that `RewriteFrames` doesn't update the stacktrace here?

https://github.com/getsentry/sentry-react-native/blob/16cfa52fcae796c51d1880b2ad6d9fc73dbede59/src/js/sdk.tsx#L72

Not sure if it's a general SDK bug, or just based on how react native sdk is configuring `RewriteFrames`, we need to test with a stock browser SDK app that uses `LinkedErrors` + `RewriteFrames`.

**Comment by marandaneto** [comment]
Thanks @AbhiPrasad 
Let us know if you find something on your testing.

**Comment by marandaneto** [comment]
@Yupeng-li have you tested on a release or debug mode?

I can reproduce the issue on debug mode but not on release mode.

The issue is here -> https://github.com/getsentry/sentry-react-native/blob/main/src/js/integrations/debugsymbolicator.ts
We are apparently not accounting for all the exceptions when symbolicating on the device.

**Comment by marandaneto** [comment]
That's also the reason why the platform is `node` sometimes -> https://github.com/getsentry/sentry-react-native/blob/main/src/js/integrations/debugsymbolicator.ts#L78

**Comment by Yupeng-li** [comment]
@marandaneto  Thank you for the update. I only tested on debug mode. I will test the release mode as soon as I have a chance.

**Comment by Yupeng-li** [comment]
Hi @marandaneto, sorry for the late reply. I tested with the release version and it worked well as expected.  Thank you for the help. 

![image](https://user-images.githubusercontent.com/31921080/163178597-ac707719-890a-4d00-9785-1ceb37826a98.png)

**Comment by krystofwoldrich** [comment]
Based on [the last comment](https://github.com/getsentry/sentry-react-native/issues/2118#issuecomment-1097986459) is this done?
