### ISSUE TITLE
Sentry sends captured messages to http://localhost:8081/symbolicate and the messages don't appear in my project.

### ISSUE THREAD

**Issue by c-emil** [getsentry/sentry-react-native#2142]
### Environment

How do you use Sentry?
self-hosted Sentry 9.0.0

Which SDK and version?
React native 3.3.2

### Steps to Reproduce

I followed the [getting started guide for React Native](https://docs.sentry.io/platforms/react-native/) step by step. I used the [Sentry wizard](https://github.com/getsentry/sentry-wizard) and added `-u` parameter pointing to our self-hosted url. When I reached the end and initialised the sentry in my application, I tried sending a manual message to sentry using `Sentry.captureMessage("Something went wrong");` right after calling `Sentry.init(...)`. This was message was sent on a livereload build that was generated by `react-native run-ios` and `react-native start`.  

### Expected Result

The message would be sent to Sentry.

### Actual Result

The message doesn't appear in my sentry project and when I check the networks in React Native Debugger, I can see that the message is being sent to `http://localhost:8081/symbolicate` which I suppose is the reason why the message is not logged in my sentry project.

![Screenshot 2022-03-14 at 12 18 20](https://user-images.githubusercontent.com/24896882/158162234-c5813c6d-f2c8-4238-b7b3-197e5033da12.png)

Am I doing something wrong? Is there any additional setup required for self-hosted sentry? Do I need to use any `tunnel` or `transport` configuration? It's not very well documented so I'm not sure how to use those properties.

**Comment by marandaneto** [comment]
@c-emil Nothing is really required other than the [DSN](https://docs.sentry.io/platforms/react-native/#initialize) that points out to your server.

Can you pass the `debug: true` var to the SDK init and copy-paste logs?

**Comment by c-emil** [comment]
This is all I get from the logs:

![Screenshot 2022-03-14 at 14 50 29](https://user-images.githubusercontent.com/24896882/158185753-638538c0-a839-49e9-ab6a-23d16031ee44.png)

**Comment by marandaneto** [comment]
@c-emil Call `Sentry.captureMessage('message') and send us the logs, you should see more than now.

**Comment by marandaneto** [comment]
@c-emil Sicne you are using Sentry server v9, you can't use Sentry's RN SDK >= v2
https://docs.sentry.io/platforms/react-native/migration/#from-1x-to-2x
Please upgrade your Server server.

**Comment by c-emil** [comment]
Thanks @marandaneto very much!

**Comment by csvan** [comment]
@c-emil did this actually solve your problem? I am having a similar problem and am using latest available Sentry server.

**Comment by c-emil** [comment]
@csvan If I remember correctly, I asked my manager to upgrade the server and he told me that I should create sentry cloud account instead. Thus in the end, I never knew if this could potentially be resolved by the suggested approach or not.
