### ISSUE TITLE
`sentry-trace` header not getting added to the request headers

### ISSUE THREAD

**Issue by dnvarun** [getsentry/sentry-react-native#2143]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
React native 3.3.2

### Steps to Reproduce

1. Initialize Sentry
2. In axios call, create a custom transaction before the request fires and finish the transaction after Promise returns
3. Inspect request headers for `sentry-trace` header

### Expected Result

`sentry-trace` header to be present in the request headers

### Actual Result

`sentry-trace` header is not present in the request headers. We are trying to setup distributed tracing with our backend. But because of this issue, the trace id is not propogating. Below is our Sentry init code
```
Sentry.init({
    dsn: SentryConfig.dsn,
    environment: environmentConfig.environment,
    normalizeDepth: 10,
    deactivateStacktraceMerging: false,
    attachStacktrace: true,
    enableAutoPerformanceTracking: true,
    debug: true,
    tracesSampleRate: 1,
    integrations: [
      new Sentry.ReactNativeTracing({
        tracingOrigins: ['localhost', FlyfinConfig.apiBasePath],
      }),
    ],
    beforeBreadcrumb(breadcrumb, hint) {
      if (breadcrumb.category === 'xhr') {
        const data = {
          status: hint.xhr.status,
          responseUrl: hint.xhr.responseURL,
          method: breadcrumb.data.method,
        };
        return {...breadcrumb, data};
      }
      return breadcrumb;
    },
  });
```

Below is how I am creating the sentry transaction
```
const sentryTxn = Sentry.startTransaction({name: 'axios'});
return axios(props).finally(() => sentryTxn.finish());
```

Initially we tried automatic instrumentation assuming a transaction would be automatically created for each XHR request. But no transactions were created. Then I tried creating an explicit transaction. Though the transaction is being shown on the dashboard, it was still not creating a child span for the XHR request and `sentry-trace` is not present in the headers

**Comment by marandaneto** [comment]
I'm currently checking if the JS SDK provides an integration for `axios` in the first place, will come back asap.

**Comment by marandaneto** [comment]
@dnvarun In order to get spans out of the active transaction using custom instrumentation, the transaction should be set in the Scope, See https://docs.sentry.io/platforms/react-native/performance/instrumentation/custom-instrumentation/

`Sentry.getCurrentHub().configureScope(scope => scope.setSpan(transaction));`

Consider using auto instrumentation as well, See https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/
So you don't have to create transactions not set into the scope manually, in some of the cases at least.

**Comment by dnvarun** [comment]
Thanks, actually I tried automatic instrumentation at first, but it did not create any transaction for api requests. The only transactions were App start and navigation related. Is there any way to enable automatic instrumentation for all the api requests? If not, we might have to just use the custom instrumentation for this

**Comment by marandaneto** [comment]
@dnvarun if automatic instrumentation is enabled, you should be able to see API requests as spans.
Transactions are finished automatically after some time if there's nothing happening within the app, maybe you triggered your request seconds later?
Please provide a minimal reproducible example if it's not the case.

**Comment by dnvarun** [comment]
Cool, will spend some time and get back if I am unable to make it work

**Comment by DeepeshMitra** [comment]
@dnvarun is there any solution for this ? 
I observed that, the automatic instrumentation was creating span for api requests made using fetch. But, it is not making spans for requests made using axios.
