### ISSUE TITLE
In case you are facing the very same issue using the latest Sentry RN version, please do raise a new issue with detailed information, thanks.

### ISSUE THREAD

**Issue by CalvinAtHome** [getsentry/sentry-react-native#2159]
In case you are facing the very same issue using the latest Sentry RN version, please do raise a new issue with detailed information, thanks.

_Originally posted by @marandaneto in https://github.com/getsentry/sentry-react-native/issues/350#issuecomment-997855437_

to change android/sentry.properties and anroid/app/build.gradle as the document blow
https://todoit.tech/rn/devops/sentry.html#%E5%AE%89%E8%A3%85-sentry-cli

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
