### ISSUE TITLE
Move RN JS Engine extra to contexts

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2162]
https://github.com/getsentry/sentry-react-native/blob/4f97e940a96576457cd7a5b0c7acf884768ded07/src/js/integrations/debugsymbolicator.ts#L69-L74

Android now supports Contexts

**Comment by marandaneto** [comment]
Its a breaking change because we are moving those values from `event.extra` to `event.contexts` since `extra` is softly deprecated, maybe people rely on this when debugging things, this is only for debugging tho, `debugsymbolicator` integration does not run for production, so maybe its even less breaking change.

**Comment by krystofwoldrich** [comment]
This is already done in v5. But now this information is collected even in `production` if available. It's part of [`ReactNativeInfo`](https://github.com/getsentry/sentry-react-native/blob/5.0.0/src/js/integrations/reactnativeinfo.ts#L14).

- https://github.com/getsentry/sentry-react-native/pull/2552
