### ISSUE TITLE
(ANR) io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush

### ISSUE THREAD

**Issue by guptayush** [getsentry/sentry-react-native#2182]
### Environment

How do you use Sentry?
on-premise version 21.12.0

Which SDK and version?
"react": "^17.0.2",
 "react-native": "^0.66.4",
 "@sentry/react-native": "^3.3.2",

### Steps to Reproduce

Random ANRs mostly in Android 12
UncaughtExceptionHandlerIntegration.java line 156
io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush

### Stack trace

main (timed waiting): tid=1 systid=10364 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1063)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1358)
       at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
       at io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush(UncaughtExceptionHandlerIntegration.java:156)
       at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException(UncaughtExceptionHandlerIntegration.java:98)
       at org.chromium.base.JavaExceptionReporter.uncaughtException(JavaExceptionReporter.java:6)
       at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException(UncaughtExceptionHandlerIntegration.java:114)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)

<img width="415" alt="Screenshot 2022-03-29 at 3 45 43 PM" src="https://user-images.githubusercontent.com/34368613/160589732-c42120f5-5c27-4d3e-b3a5-0325330057e1.png">

**Comment by marandaneto** [comment]
@guptayush thanks for reporting.
Is there a way to reproduce it? how are you testing and getting this data? thanks.

**Comment by TheTushar2696** [comment]
Hi @marandaneto,
We are unable to reproduce it , But this data is getting logged in Crashlytics

**Comment by marandaneto** [comment]
@guptayush Maybe the problem lives when using both crash reports at the very same time, since both SDKs need to rely on UncaughtExceptionHandler and have limited time to do stuff.
Can you check if this happens in specific versions of the Sentry SDK or Crashlytics SDK? It'd be hard to fix if we can't repro it.

**Comment by TheTushar2696** [comment]
@marandaneto  We were always using both Sentry and Crashlytics, but this error stated popping in once we upgraded to sentry 3.x ,

**Comment by marandaneto** [comment]
We'll investigate if we're wrongly blocking at some point and not releasing it afterwards, it could be that Crashlytics detects a false positive ANR since Sentry is writing a file to the disk so the events don't get lost.

**Comment by guptayush** [comment]
@marandaneto any update on this ANR?

**Comment by marandaneto** [comment]
Not really, I believe it could come from here https://github.com/getsentry/sentry-java/blob/ee4bae901f552e1f49435d18f2cc0d44956c7b81/sentry/src/main/java/io/sentry/SentryOptions.java#L67-L72
since the SDK awaits up to this time before letting the process be killed.

You can try to reduce this timeout for now and see if that improves.

I've tried to reproduce it (without Crashlytics) but only with Sentry and everything worked out, no ANR triggered and the thread is released after the event is cached on the disk correctly.

**Comment by marandaneto** [comment]
@guptayush I could not reproduce the issue, did you manage to reproduce it? if so, can you provide a minimal reproduction example? thanks.

**Comment by guptayush** [comment]
@marandaneto We are not able to reproduce the issue

**Comment by Waltari10** [comment]
We are receiving this exact same error on Android with:
 "@sentry/react-native": "4.0.2",
    "react": "17.0.2",
    "react-native": "0.68.1",
    
    
   ```
 io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush
Input dispatching timed out

```

On the following Android versions atleast:
- Android 12L (SDK 32)
- Android 12 (SDK 31)
- Android 11 (SDK 30)
- Android 9 (SDK 28)


Gonna try updating to Sentry 4.2.3. Will know if helped in maybe a month.

**Comment by marandaneto** [comment]
Please raise a new issue with more context in case something is not working, we could not reproduce this issue.
