### ISSUE TITLE
Capturing native crashes that occur prior to the init method and setting up performance tracking

### ISSUE THREAD

**Issue by fabiendem** [getsentry/sentry-react-native#2208]
Hello,

In our React Native app, we've currently setup Sentry using the standard method:
- Auto linking
- Configuration at the JS level: https://docs.sentry.io/platforms/react-native/configuration/options/

Nevertheless, at https://docs.sentry.io/platforms/react-native/manual-setup/native-init/

It is said:

>  the SDK has a current limitation of not capturing native crashes that occur prior to the init method being called on the JS layer. 

We just ran into such an issue, where a crash occurring before the `init` method was not reported to Sentry.

The documentation says:
> You can initialize the native SDKs yourself to overcome this limitation or if you want to provide custom options above what the React Native SDK currently provides.

Now, the problem is that we would do this at the native layer only using:
- https://docs.sentry.io/platforms/apple/guides/ios/#configure
- https://docs.sentry.io/platforms/android/#configure

And If so: I am assuming we won't be able to setup Sentry Performance's plugin, because to set it up we need to call `Sentry.init` again, but at the JS layer.
https://docs.sentry.io/platforms/react-native/performance/

Calling `Sentry.init` both the native and JS layers seems to be prone to bugs.

Could you please suggest a way to setup Sentry for React Native which could allow to both:
- track native crashes that occur prior to the init method called at the JS layer
- enable Sentry Performance
?

Thank you

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/react-native/manual-setup/native-init/

> Calling Sentry.init both the native and JS layers seems to be prone to bugs.

You can install and init the Native SDKs and also init the RN SDK using the `autoInitializeNativeSdk`, so you can init all the SDKs based on your own configuration.

**Comment by marandaneto** [comment]
@fabiendem every option should be documented either here https://docs.sentry.io/platforms/react-native/configuration/options/#hybrid-sdk-options or in the code itself, reading the property docs.
I'm not sure I understand your question, the RN SDK uses the default values when initing the Native SDKs, if using `autoInitializeNativeSdk`, it means we don't init the Native SDK ourselves, so you should configure at your needs, or just use the default values as well.

**Comment by fabiendem** [comment]
Thanks, what I am trying to understand is which properties are a hard requirement at the native layer if I setup the SDK at the native layer manually.
And which ones I can tweak later at the JS Layer.
I think I need to give it a go at this point and it will get clearer.
