### ISSUE TITLE
Send user ID on Android native crash

### ISSUE THREAD

**Issue by jetre219** [getsentry/sentry-react-native#2209]
Hi! We've been using Sentry on our react-native app for a few months now and lately, we realized that sometimes the `userId` is not set correctly on Android native crash. We found out that it was because sentry would assign an [installation id](https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/Installation.java#L32) when nothing is assigned. In our case, in case of a real native crash, that is not nullified [here](https://github.com/getsentry/sentry-react-native/blob/main/android/src/main/java/io/sentry/react/RNSentryModule.java#L169), there was no user ID set so the installation ID was used. In order to fix this problem, we did a patch to be able to give a default user id as an argument, but we were wondering if there's another solution, maybe cleaner.

This is the patch we did:
```
diff --git a/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java b/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java
index e3b4692..79888f0 100644
--- a/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java
+++ b/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java
@@ -169,6 +169,13 @@ public class RNSentryModule extends ReactContextBaseJavaModule {
                 setEventOriginTag(event);
                 addPackages(event, options.getSdkVersion());
 
+                if (rnOptions.hasKey("defaultAndroidUserId")) {
+                    String userId = rnOptions.getString("defaultAndroidUserId");
+                    User user = event.getUser() == null ? event.getUser() : new User();
+                    user.setId(userId);
+                    event.setUser(user);
+                }
+
                 return event;
             });
 
diff --git a/node_modules/@sentry/react-native/dist/js/options.d.ts b/node_modules/@sentry/react-native/dist/js/options.d.ts
index 4e1014f..d946fc3 100644
--- a/node_modules/@sentry/react-native/dist/js/options.d.ts
+++ b/node_modules/@sentry/react-native/dist/js/options.d.ts
@@ -71,6 +71,8 @@ export interface ReactNativeOptions extends BrowserOptions {
      * @deprecated Use `Sentry.configureScope(...)`
      */
     initialScope?: CaptureContext;
+
+    defaultAndroidUserId?: string;
 }
 export interface ReactNativeWrapperOptions {
     /** Props for the root React profiler */
```

Thanks!

**Comment by marandaneto** [comment]
@jetre219 You don't need to patch the SDK plugin for that.
You can init the RN SDK and set a user after init https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/
I also recommend enabling the `NDK scope sync` feature https://docs.sentry.io/platforms/react-native/enriching-events/scopes/#scope-synchronization
The user set on the JS layer is also going to be set on Java/Kotlin and C/C++ events.
