### ISSUE TITLE
Report top level integrations on RN

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2210]
Similar to https://github.com/getsentry/sentry-java/issues/1989 but we already send all the integrations.
It'd be useful to also send the routing libraries etc that are added manually, so we can learn the usage of it.

**Comment by krystofwoldrich** [comment]
@marandaneto Routing libraries you mean the js deps of a project? -> https://github.com/getsentry/team-mobile/issues/54

Would it also make sense to report which one of our [`routingInstrumentation`](https://github.com/getsentry/sentry-react-native/blob/83be16fd96630c3e567aca2bb773d04ad5b08824/src/js/tracing/reactnativetracing.ts#L55) is being used?

**Comment by marandaneto** [comment]
@krystofwoldrich nope, I mean, `ReactNavigationInstrumentation`, `ReactNavigationV4Instrumentation`, `ReactNativeTracing`, `RoutingInstrumentation `, etc... every integration/router/navigator... that has to be added manually, we'd know which integrations are being set or not, also its usage.

**Comment by krystofwoldrich** [comment]
Seems like we should just change the name of the `ReactNativeTracing` integrations based on the used instrumentation since the `ReactNativeTracing` can only create `Transaction` for an app start.
