### ISSUE TITLE
Cannot set release manually in native iOS

### ISSUE THREAD

**Issue by francescov1** [getsentry/sentry-react-native#2213]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
- @sentry/react-native 3.1.1
- react-native 0.64.2

### Steps to Reproduce

We initialize the Sentry SDK on the native side to catch crashes that occur before JS is initialized. We noticed that the native initialization is auto generating a release, rather than using the release we pass to the JS initialization (seems pretty evident looking back now). To fix this, we want to pass the release manually when initializing the native SDK. We are getting an error when we try to do this.

1. Follow steps to [initialize Sentry SDK on the native side](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/), which directs to follow the [native iOS instructions](https://docs.sentry.io/platforms/apple/guides/ios/#configure) (note that we are doing Objective C since we are using React Native)
2. Try to manually set the release:

```objc
  [SentrySDK startWithConfigureOptions:^(SentryOptions *options) {
    options.dsn = sentryDns;
    options.environment = sentryEnv;
    options.release = sentryRelease;
  }];
```

We get two errors from the `options.release = sentryRelease;` line:
- `AppDelegate.m:51:13: error: 'release' is unavailable: not available in automatic reference counting mode`
- `AppDelegate.m:51:21: error: no setter method 'setRelease:' for assignment to property`

### Expected Result

The app builds without errors

### Actual Result

We see the errors described above. Here's a screenshot of the build:
<img width="1486" alt="Screen Shot 2022-04-18 at 3 45 12 PM" src="https://user-images.githubusercontent.com/26126685/163867067-e399d8b9-df5d-4523-96fd-3789460f69f0.png">

**Comment by marandaneto** [comment]
@francescov1 its called `releaseName` on iOS since `release` is a reserved word.

**Comment by marandaneto** [comment]
> Hi @marandaneto, thanks for your reply. This is not reflected in the documentation anywhere: [docs.sentry.io/platforms/apple/guides/ios/configuration/options/#release](https://docs.sentry.io/platforms/apple/guides/ios/configuration/options/#release)

Indeed, https://docs.sentry.io/platforms/apple/guides/ios/configuration/options/#release should have the right name.
@philipphofmann mind fixing it?

**Comment by philipphofmann** [comment]
PR is open https://github.com/getsentry/sentry-docs/pull/4953.
