### ISSUE TITLE
[Question] How Sentry use beforeSend?

### ISSUE THREAD

**Issue by Deodes** [getsentry/sentry-react-native#2217]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.2.8

**`react-native` version:** 0.66.4

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: 'xxxxxxxxxxxxxxxxxxxxx',
    debug: false,
    beforeSend: async event => {
        const restart = await AsyncStorage.getItem('restart');
        if (restart) {
            AsyncStorage.removeItem('restart');
            return null;
        }
        return event;
    },
});
```
---
**I have following issue:**

I'm using Sentry beforeSend method to drop 'out of memory' events when my app(iOS) restarted(before restart I'm setting in async storage a value, to determine that app restarted after using lib). But every time I'm getting these errors. My questions are when Sentry SDK trigger sending events to service(after next app open, or immediately after crash) and can I use beforeSend as async function? 

**Steps to reproduce:**
- Install and initialize SDK,
- Use react-native-restart,
- Try not to catch 'out of memory' event

**Actual result:**

- Catch 'out of memory'

**Expected result:**

- Not to catch ''out of memory

**Comment by marandaneto** [comment]
You can disable the OOM tracking as well: https://docs.sentry.io/platforms/react-native/configuration/options/#enableOutOfMemoryTracking

For filtering, you can follow up on the docs https://docs.sentry.io/platforms/react-native/configuration/filtering/
You cannot use an `async` function since it needs to return a valid value from this callback.
