### ISSUE TITLE
Align SDK with docs regarding session update for dropped events

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-react-native#2218]
We've updated the docs (https://github.com/getsentry/develop/pull/551) to explain how we would like to handle event filter order, updating of sessions for dropped events and sending of session updates. We should check if we're aligned and adapt if necessary. Here's the issue from the Java SDK where all of this started: https://github.com/getsentry/sentry-java/issues/1916

**Comment by marandaneto** [comment]
The RN SDK uses the Android and iOS SDK for that, no need to change it here.
