### ISSUE TITLE
Missing in_app from RewriteFrames ?

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-react-native#2219]
I noticed on Sentry Capacitor that RewriteFrames sets the property in_app
https://github.com/getsentry/sentry-capacitor/blob/7fd3c71be4835782595ad590818b24435b66a50e/src/sdk.ts#L45-L72

Where on React Native, in_app is not touched
https://github.com/getsentry/sentry-react-native/blob/f916f2b3afbb9884f9037b8486539ca6cc8b327c/src/js/sdk.tsx#L72-L93

This is more of a question on why React Native does not set the in_app property where Capacitor sets it. Is it missing on the React Native?

**Comment by marandaneto** [comment]
The Sentry JS processor already does that on the server
https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L1026-L1117=
