### ISSUE TITLE
Incorrect cold app startup time on JS bundle reload on Android

### ISSUE THREAD

**Issue by Suesanz** [getsentry/sentry-react-native#2224]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native: 3.4.1
react-native: 0.68.1

The issue is for Android only. AFAIK for iOS it works fine.

### Steps to Reproduce

1. Make sure the app is not running in the background and open the app. Now cold startup time will be attached as a span when routing instrumentation is enabled. Now wait for a few secs and explicitly restart the app using any library like `react-native-restart` or `react-native-code-push`(`restartApp` method).
2. Here the cold startup time span will be again calculated and attached to first routing transaction. And this value calculated will be incorrect now. This is happening for both debug and release builds.
3. Here's a [repo](https://github.com/Suesanz/test-sentry-app-startup) to reproduce the issue. I have added a few logs for convenience while debugging. Just open the app and click on the button ' Next Screen', here on clicking the button 'RESTART APP', `restartApp` method of `react-native-code-push` will be called and the JS bundle will be reloaded.

### Expected Result

On reloading the JS bundle only, the cold start app time should not be calculated again and reattached as a span to some transaction.

### Why did it happen?

As per my understanding, I think something like below is happening:

1. When we just reload the JS bundle, libraries like `react-native-restart`/`react-native-code-push` will tear down the react context and recreate another. Check this piece of code [here](https://github.com/microsoft/react-native-code-push/blob/9947037a985a04927c64624318e4ce64d43d2049/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L156). Both these libraries are using the same logic that react-native offers when we reload the JS bundle from Dev Settings in debug mode.
2. Now since we have only reloaded the JS bundle the value i.e. start timestamp of cold startup time we get from `sentry-java` SDK is still the old one but now the `RNSentryModule` will be re-initialized and the end timestamp of cold startup time will be calculated again.
3. The SDK uses a local flag `didFetchAppStart` in `RNSentryModule.java` which we make true after fetching the app startup time from `AppStart` instance but since this flag is local to this module only, when react context is recreated we lost the value of this flag as well and it always comes `false` and thus re-calculating end timestamp of cold startup time.

### Actual Result

Here is a video. Look at the value of `didFetchAppStart` when I reload the app from the terminal or by clicking the `Restart` button from inside the app.

https://user-images.githubusercontent.com/26189041/165129929-e43de079-db05-44ce-be80-703e30fddd7a.mov

### Proposed solution

One of the solutions I can think of is setting some value like `didFetchAppStart` at the instance of `AppStartState` class with some method like `setDidFetchAppStart` and set it to true after we fetch(calling `getAppStartTime`) cold start-up time from sentry-java SDK. Now at RN end, RNSentryModule will always fetch this value and set `didFetchAppStart` from `AppStartState` instance.

Check this [gist](https://gist.github.com/Suesanz/de400291f3ae056b8ce4751722f88899) for the changes required in `sentry-java` SDK and check this [gist](https://gist.github.com/Suesanz/63bf7750a53b11c035616e57bf47c105) for changes required in `sentry-react-native`.
Not sure of this solution, and how will it fit in sentry SDK ecosystem. Let me know if this sounds good, happy to create PR here.

Please let me know if you need more context. I have a limited understanding of how the JS bundle is reloaded and react context is recreated, correct me if I missed something.

**Comment by marandaneto** [comment]
@jennmueng would you like to double-check this? thanks.

**Comment by jennmueng** [comment]
Reproduced and found the source of this issue, the boolean flag we set on Android `didFetchAppStart` seems to be reset to false when the React Native JS bundle is reloaded, unlike on iOS where it's not reset.

https://github.com/getsentry/sentry-react-native/blob/42685267ea9dc40a58b73d018550e3fc195cff5e/android/src/main/java/io/sentry/react/RNSentryModule.java#L58

https://github.com/getsentry/sentry-react-native/blob/42685267ea9dc40a58b73d018550e3fc195cff5e/android/src/main/java/io/sentry/react/RNSentryModule.java#L234-L237

**Comment by Suesanz** [comment]
@jennmueng Yes, with your changes in #2229, `didFetchAppStart` is updating correctly. Thanks, folks for resolving this.

@marandaneto Is there a way to delete the previous metrics captured on the sentry dashboard? We have accumulated a significant amount of incorrect metrics on the dashboard for the app startup time which is affecting the average metric.

**Comment by marandaneto** [comment]
> @jennmueng Yes, with your changes in #2229, `didFetchAppStart` is updating correctly. Thanks, folks for resolving this.
> 
> @marandaneto Is there a way to delete the previous metrics captured on the sentry dashboard? We have accumulated a significant amount of incorrect metrics on the dashboard for the app startup time which is affecting the average metric.

I don't think there's a way to delete it, but the metrics are calculated over the selected time, so as soon as people start updating their Apps with the new version of the SDK, the data is gonna get more accurate, sorry about that.
