### ISSUE TITLE
Investigate the RN new architecture

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2226]
https://reactnative.dev/docs/next/new-architecture-intro#table-of-contents

The goal is to identify breaking changes with the current Sentry RN SDK.
Consider upgrading to the latest stable version as well https://react-native-community.github.io/upgrade-helper/?from=0.66.2&to=0.68.1
https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

[Docs for migrating](https://github.com/facebook/react-native-website/pull/3037)
[Discussions new architecture](https://github.com/reactwg/react-native-new-architecture/discussions)
[Examples with steps](https://github.com/react-native-community/RNNewArchitectureLibraries)
[Already migrated libs to take as an example](https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture#migration-status-of-popular-libraries)

**Comment by marandaneto** [comment]
- [ ] Drop RN versions older than 0.60.x, Check `"react-native": ">=$version"`
- [ ] Import `NativeModules` on index.ts
- [ ] Import `RCTBridgeModule` on iOS header
- [ ] Use `RCT_REMAP_METHOD` on iOS plugin
- [ ] Patch `buildscript` build.gradle on Android
- [ ] continue.

**Comment by cipolleschi** [comment]
> Consider upgrading to the latest stable version as well https://react-native-community.github.io/upgrade-helper/?from=0.66.2&to=0.68.1

The new stable version is 0.69.3

> [CodeGen requires min RN version 0.70](https://deploy-preview-3037--react-native.netlify.app/docs/next/the-new-architecture/pillars-codegen).

Not really. Codegen works starting from the 0.67, however we worked on improving it and trying to simplify the setup. The page you linked is a draft of how to use Codegen that will be released together with 0.70, where we changed the syntax of the package.json and we unified how it should work for both ios and android.

> Autolinking doesn’t work with the new architecture out of the box. Therefore you need to ask the user of your library to do the following steps

Autolinking for iOS works since 0.68.
Autolinking for Android is coming with 0.70.

**Comment by marandaneto** [comment]
@cipolleschi Thank you.

**Comment by cipolleschi** [comment]
[Here](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.70) you can find a full migration from 0.67.4 to 0.70.0-rc.0

**Comment by cipolleschi** [comment]
Hi @marandaneto! How's this investigation/migration going? Can I help with anything?

**Comment by marandaneto** [comment]
> Hi @marandaneto! How's this investigation/migration going? Can I help with anything?

Thanks for checking out, I've done the investigation and have an idea on how to proceed but I still need to discuss with the team about this prioritization.
I'll keep you posted :)

**Comment by krystofwoldrich** [comment]
These two repositories with example of new architecture app and library can be useful during the migration.

- https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.70
- https://github.com/react-native-community/RNNewArchitectureLibraries/tree/feat/back-turbomodule#android-autolinking=

Also Sentry could collet tag `fabric`, to see if app is running on the new architecture.

**Comment by krystofwoldrich** [comment]
Nice overview of what changes in an app to include the new arch.
https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.68.0

**Comment by cipolleschi** [comment]
That link is a bit outdated. I suggest that you use v0.70 as reference instead of 0.68. We changed several things and simplified the migration process a bit.. And we are continuously improving it. 
Migrating to 0.71, as soon as we release that, will be even easier!

**Comment by krystofwoldrich** [comment]
@cipolleschi Thanks for the info. I'm now following all the docs for 0.70.

**Comment by krystofwoldrich** [comment]
Upgrade to React 18 can be done after JS SDK is also on 18. Since Rect.Component types are not copatible.

**Comment by krystofwoldrich** [comment]
> * [ ]  Drop RN versions older than 0.60.x, Check `"react-native": ">=$version"` on `package.json`

@marandaneto So we would change this all the way to 0.70.x for the 5.0.0 release?

**Comment by marandaneto** [comment]
> Upgrade to React 18 can be done after JS SDK is also on 18. Since Rect.Component types are not copatible.

Sounds like a problem, does 0.70.x require React 18?
Does it work if people use React 18 but the SDK does not?

**Comment by marandaneto** [comment]
> > * [ ]   Drop RN versions older than 0.60.x, Check `"react-native": ">=$version"` on `package.json`
> 
> @marandaneto So we would change this all the way to 0.70.x for the 5.0.0 release?

Yes, people can use the v4 of the SDK for < 0.70.x

**Comment by cipolleschi** [comment]
I think that a little bit of extra context can be helpful here. 

React Native rebundle and ships its own version of React internally (which is the same code you find in the React repo, it's not a customized versiono of React for React Native). 
React Native 0.70+ is shipping React 18. New apps created with React Native 0.70+ have the React 18 root enabled by default, but the user can disable it

**Comment by krystofwoldrich** [comment]
@cipolleschi So until we can upgrade to react 18 we can just use 17 (but of course, we will miss some features).

**Comment by cipolleschi** [comment]
Yeah, technically if the users turn off [this setting](https://github.com/facebook/react-native/blob/main/template/ios/HelloWorld/AppDelegate.mm#L27-L30) for iOS and its equivalent for Android, it should behave like React 17.

**Comment by krystofwoldrich** [comment]
React 18 is working now, it wasn't actually JS SDK (they support v18), but it was an error in RN.

**Comment by krystofwoldrich** [comment]
Seems like ReactNavigation and New Arch on Android don't play well yet, I've run into the same issue.

https://github.com/software-mansion/react-native-screens/issues/1608

**Comment by marandaneto** [comment]
Also hitting the issue https://github.com/facebook/react-native/issues/34923

**Comment by krystofwoldrich** [comment]
When this will make it to a RN release we will be able to return the modal feedback view to the new arch example.
https://github.com/facebook/react-native/commit/9ac437f25b51b9a7fc8134d17c69b64ae90d508d

**Comment by marandaneto** [comment]
Better stack traces when Java crashes apparently depend on the outcome of this issue https://github.com/getsentry/sentry-native/issues/743 and https://github.com/getsentry/sentry-native/pull/752#issue-1382270623 or if the RN engine actually improves something.
