### ISSUE TITLE
Source maps are not attaching to issues even with manual uploads - Hermes iOS & Android

### ISSUE THREAD

**Issue by shamilovtim** [getsentry/sentry-react-native#2227]
### Environment

How do you use Sentry?
SAAS

Which SDK and version?
Using latest react native sentry 

### Steps to Reproduce

1. I made sure that the gradle plugin and iOS build phase is installed
2. I followed every guide on the website up to and including manual uploads: 
 - I checked to make sure the bundle is named the same as the error trace. 
 - I made sure the dist and the release name of my manual uploaded source maps matches
 - I went so far as to manually build the Hermes sourcemaps following the manual guide and they still did not attach
 - I can see the source maps in the Admin dashboard uploaded and tagged to the release 
 - The source maps just do not get applied to the issue / ticket no matter if the release, dist and file names match.

My suspicion is that something is wrong in the docs or is not being clarified. I suggest revisiting the docs and making sure the advice is true and accurate.

### Expected Result

- I expect source maps to auto attach with the automatic script integrations for both Hermes iOS and Hermes Android
- I expect that when troubleshooting source maps using manual source map building and manual upload, the source maps would be force into working
- I expect that a source map visible in the Admin dashboard tagged with the correct release, dist and labeled with the correct filename on Android would attach to a ticket with the same dist, release and filename.

### Actual Result

- Despite dist, release name and file name matching source maps do not attach to issues

**Comment by marandaneto** [comment]
@shamilovtim if I create an empty project, using the RN template, using Hermes, adding Sentry, and compiling it, it works.
Can you provide a minimal reproduction example? Thanks.

**Comment by marandaneto** [comment]
@shamilovtim any news here? thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
