### ISSUE TITLE
Can users remove or override console to NOOP while using Sentry RN?

### ISSUE THREAD

**Issue by shamilovtim** [getsentry/sentry-react-native#2228]
I'm wondering about using the [babel plugin](https://babeljs.io/docs/en/babel-plugin-transform-remove-console/) to strip console methods or to do:

```typescript
const NOOP = () => {};
export const disableConsoleInProduction = () => {
  if (ENVIRONMENT === 'Production') {
    console.log = NOOP;
    console.info = NOOP;
    console.debug = NOOP;
    console.warn = NOOP;
    console.error = NOOP;
  }
};
```

Would either approach mess with Sentry at all or is it ok? Thanks!

**Comment by marandaneto** [comment]
@shamilovtim I'm not entirely sure if you want to avoid logging into the console, not capturing events on Sentry or even not adding logs as breadcrumbs.
Can you elaborate?

**Comment by shamilovtim** [comment]
> @shamilovtim I'm not entirely sure if you want to avoid logging into the console, not capturing events on Sentry or even not adding logs as breadcrumbs. Can you elaborate?

Sorry, I don't understand. I'm asking if I override and disable our console via babel or pointing it to NOOP if it will mess up Sentry?

**Comment by marandaneto** [comment]
@shamilovtim nope, Sentry won't be able to capture events logged by the console, but if you are disabling it, that's probably what you want, so all good.
