### ISSUE TITLE
Cannot add task 'bundleAppReleaseJsAndAssets_SentryUpload_1048821' as a task with that name already exists.

### ISSUE THREAD

**Issue by jonathanj** [getsentry/sentry-react-native#2242]
As a follow-on to #1226, and to answer [the question](https://github.com/getsentry/sentry-react-native/issues/1226#issuecomment-964924954) about special configuration:

In our application we're using [APK splitting](https://developer.android.com/studio/build/configure-apk-splits), both by density and by ABI. From the documentation:

> As such, Gradle always generates an additional universal APK that contains assets for all screen densities and does not include a &lt;compatible-screens&gt; tag.

The result of this is that each `applicationVariant.outputs` contains _at least_ 2 outputs:

- All densities for the given ABI
- One for each included density

The [sentry.gradle script enumerates all outputs](https://github.com/getsentry/sentry-react-native/blob/372ef4a262f2c26a85ca2dc52b3de8be57309b28/sentry.gradle#L175-L195) and will attempt to upload source maps for every output.

We already override the version code for different ABIs but do _not_ do so for density, and I was unable to find a way to remove unwanted variant outputs from Gradle. (If you know of a way, I would be very appreciative.)

In our case, we do not distribute the "all densities" APK, and so uploading it to Sentry would only cause clutter by having an artifact for a build number that will never exist. However, because the variant output exists Sentry tries to create the upload task and fails, because the task name is only differentiated by version code.

## Suggestion

Ideally there would be a Sentry Gradle _plugin_, which would expose a way to filter outputs with a closure but I understand that is a nontrivial amount of work.

Alternatively, something close could be achieved by checking variant outputs against some externally configured value such as `ext.sentry.excludeVariantOutputs`, a list of `output.getName()` values to exclude, and `extractReleaseInfo` would remove those from its return value.

**Comment by jonathanj** [comment]
@marandaneto Awareness of flavours wouldn't specifically help in this case because there are multiple variant outputs per flavour. As I understand it,  flavour awareness does not imply ABI/density split awareness.

**Comment by marandaneto** [comment]
@jonathanj makes sense, can you share your split configuration so I can try to reproduce it? thanks.
A minimal reproduction example would be that helpful but in case a simple code snippet does, that would be enough.

**Comment by jonathanj** [comment]
@marandaneto So I was trying to make a repo to reproduce this, but couldn't get it to happen even though I had reproduced all the app configuration from the original source. Then I noticed that #2144 had changed the `sentry.gradle` script in a way that would fix this.

What I've realised since is that this failure was caused by behaviour that I don't want: I do not want Sentry to automatically upload all build outputs because some of those outputs will not be distributed, so we'd have source maps for builds that are literally never run by anyone.

I'm not sure if I should create a new ticket for that feature, or if I should instead not use the `sentry.gradle` script and manually run the CLI tool?

**Comment by marandaneto** [comment]
Thanks, we're gonna add a boolean to turn off auto uploading in case you need, see https://github.com/getsentry/team-mobile/issues/3#issuecomment-1125992486
As you just said, you can opt-out of the `sentry.gradle` and use sentry-cli directly.
