### ISSUE TITLE
`sentry.io` is down => cannot upload source maps => 💣

### ISSUE THREAD

**Issue by rafauke** [getsentry/sentry-react-native#2243]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
```sh
"@sentry/react-native": "^3.3.5"
```

### Steps to Reproduce

1. Trying to build RN app
2. It fails when trying to upload source maps
3. trying to `curl -v https://sentry.io`

```sh
$ curl -v https://sentry.io/
*   Trying 35.188.42.15:443...
* connect to 35.188.42.15 port 443 failed: Connection timed out
* Failed to connect to sentry.io port 443 after 131639 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to sentry.io port 443 after 131639 ms: Connection timed out
```

4. Trying different internet connection
5. Trying different computer
6. Trying VPN

### Expected Result

See successful green messages :)

What actually happened. Maybe a screenshot/recording? Maybe some logs?

```sh
$ curl -v https://sentry.io/
*   Trying 35.188.42.15:443...
* connect to 35.188.42.15 port 443 failed: Connection timed out
* Failed to connect to sentry.io port 443 after 131639 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to sentry.io port 443 after 131639 ms: Connection timed out
```

![image](https://user-images.githubusercontent.com/9576167/167136646-a24f0178-036f-41b2-820d-0fe71ead65a0.png)

**Comment by mutablestudio** [comment]
I'm seeing this all day today, not yesterday though. Building with XCode and failing during step Upload Debug Symbols to Sentry. Reverted from `"@sentry/react-native": "^3.4.2"` to `3.2.12`, just as a test, and uploading of maps during Upload Debug Symbols to Sentry worked again. Perhaps an issue with the latest version and the cli.

**Comment by marandaneto** [comment]
We have an Incident going on, sorry about that.
https://status.sentry.io/incidents/zwlnckpsrb6l

**Comment by ToshKoevoets** [comment]
@marandaneto The point is not only the incident. It blocks complete app from starting even in development mode where it's not necessary at all. It would be great to have a parameter to turn of Sentry build, now I have to completely uninstall Sentry just to get my app running and do some work.

**Comment by marandaneto** [comment]
@ToshKoevoets you can run debug mode which does nothing or comment out the integrations that communicate with Sentry during build time.

Android:
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-gradle-integration

iOS:
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#bundle-react-native-code-and-images
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry

Sorry for the inconvenience.

**Comment by marandaneto** [comment]
Closing it since the incident is resolved.
https://github.com/getsentry/mobile-team-meta/issues/3 is created for improving the SDKs and plugins in case of outages.

**Comment by Irfanwani** [comment]
I am also facing the same while trying to build an android build.
