### ISSUE TITLE
Degrade gracefully when uploading debug symbols if sentry is unreachable

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2246]
Related to https://github.com/getsentry/team-mobile/issues/3

Implementation detail: https://github.com/getsentry/team-mobile/issues/3#issuecomment-1125992486

**Comment by kahest** [comment]
Depends on https://github.com/getsentry/sentry-cli/issues/1276

**Comment by krystofwoldrich** [comment]
When this get resolved https://github.com/getsentry/sentry-cli/pull/1343 we can add documentation for the final solution to the mobile sdks docs. Until then this is blocked.

**Comment by krystofwoldrich** [comment]
CLI now allows `--allow-failure` and `SENTRY_ALLOW_FAILURE`

https://github.com/getsentry/sentry-cli/commit/b1ce40f53f329814f9f4c14529d6db69e1f33523

Release in version 2.7.0 (note it's missing in changelog on purpose)

**Comment by marandaneto** [comment]
> CLI now allows `--allow-failure` and `SENTRY_ALLOW_FAILURE`
> 
> [getsentry/sentry-cli@b1ce40f](https://github.com/getsentry/sentry-cli/commit/b1ce40f53f329814f9f4c14529d6db69e1f33523)
> 
> Release in version 2.7.0 (note it's missing in changelog on purpose)

we have to bump the CLI on RN for the major v5 then.

**Comment by krystofwoldrich** [comment]
I was wondering, why we can't upgrade the CLI on the v4. I've tried it and it doesn't seem to break anything.

**Comment by marandaneto** [comment]
> I was wondering, why we can't upgrade the CLI on the v4. I've tried it and it doesn't seem to break anything.

you'd need to address more issues.
https://github.com/getsentry/sentry-wizard/issues/181

also, you'd need to patch the wizard v1 instead of v2, its more work, but possible.
