### ISSUE TITLE
Source maps not working on iOS after upgrading to Hermes

### ISSUE THREAD

**Issue by delgiudices** [getsentry/sentry-react-native#2249]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/react-native 3.3.2

### Steps to Reproduce

1. Upgraded to hermes
2. Noticed that source maps aren't working anymore
3. Followed the steps [in this guide](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/#custom-source-maps) to build source maps for iOS
4. Getting error: 
<img width="1125" alt="Screen Shot 2022-05-18 at 1 18 11 PM" src="https://user-images.githubusercontent.com/4893007/169105985-7296c662-0659-4c9c-8ef7-fbcf45797bc5.png">
5. Realized source maps are working when build automatically on android

### Expected Result

Source maps should be working properly

What you thought would happen.

### Actual Result

<img width="1125" alt="Screen Shot 2022-05-18 at 1 18 11 PM" src="https://user-images.githubusercontent.com/4893007/169105985-7296c662-0659-4c9c-8ef7-fbcf45797bc5.png">

**Comment by jennmueng** [comment]
@delgiudices Can you try uploading the source maps straight from the bundler (output from the first step in the guide), make sure they're named `main.jsbundle` and `main.jsbundle.map`. Also, try it on a fresh `release`/`dist` pair, as there seems to be some issues regarding source maps caching on Sentry right now.

**Comment by marandaneto** [comment]
@delgiudices any updates here? thanks.
