### ISSUE TITLE
[iOS] Build failed when developing offline or Sentry is down

### ISSUE THREAD

**Issue by cacosandon** [getsentry/sentry-react-native#2251]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
`React Native 0.64.2`
`"@sentry/react-native": "^3.2.10",`

### Steps to Reproduce

1. Disconnect your WiFi (or try exactly now `May 23, 2022 - 05:54 PDT` that Sentry is having networking issues)
2. Build your iOS app on any simulator

### Expected Result

Skip the Sentry step and achieve a successful build

### Actual Result

The build failed:

<img width="779" alt="Screen Shot 2022-05-23 at 09 51 43" src="https://user-images.githubusercontent.com/30879716/169834644-72f2f910-9233-4c0c-a9e4-bf87646c4537.png">

**Comment by marandaneto** [comment]
Related to https://github.com/getsentry/team-mobile/issues/3
