### ISSUE TITLE
Touch Events cannot be collected

### ISSUE THREAD

**Issue by TangChanged** [getsentry/sentry-react-native#2255]
version: "@sentry/react-native": "^3.4.2",
Device： <img width="367" alt="image" src="https://user-images.githubusercontent.com/12230238/171572950-bf9ee535-8824-4619-813e-5dd8303540a4.png">

AppRegistry.registerComponent(appName, () => Sentry.withTouchEventBoundary(App));

https://docs.sentry.io/platforms/react-native/touchevents/ 
Follow the documentation, but I can't capture the touch events data on the console.
No Touch type.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/12230238/171573270-5f82c8ff-fd9d-454b-820c-bbca55354322.png">

**Comment by marandaneto** [comment]
@TangChanged Thanks, can you provide a minimal reproduction example?
Our samples have it running and it works.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
