### ISSUE TITLE
Error when running the @sentry/wizard script

### ISSUE THREAD

**Issue by ruanblima** [getsentry/sentry-react-native#2256]
I am trying to set up sentry in my react native project. But when I try to execute the script "npx @sentry/wizard -i reactNative -p ios android" this error occurs

Environment
Node
v16.13.0

React native
"react-native": "0.63.4",

Sentry
"@sentry/react-native": "^3.4.2",

Steps to Reproduce
Execute the command
Actual Result

![image](https://user-images.githubusercontent.com/57442366/171968392-e703fbad-1995-49a4-9e33-bab138791225.png)

![image](https://user-images.githubusercontent.com/57442366/171968396-c8efc17e-4f3f-4445-b5b8-751b0d301db1.png)

**Comment by marandaneto** [comment]
Closing as dup of https://github.com/getsentry/sentry-wizard/issues/167
