### ISSUE TITLE
Using React Native Navigation and Tabs cause spans being added to the wrong screen transaction

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2285]
https://wix.github.io/react-native-navigation/docs/advanced-navigation/

this might be because there can only be one transaction on the scope at a time while there are multiple screens opening in a tabbed navigation.
A React-specific way of doing this would be to have a unique context for every screen to store the transactions.
And each span would attach to the most immediate parent in the component tree.

**Comment by bruno-garcia** [comment]
This came up from a customer

**Comment by marandaneto** [comment]
Similar to https://github.com/getsentry/sentry-java/issues/2004

**Comment by marandaneto** [comment]
Right now users could disable the auto instrumentation for those specific cases and use our auto instrumentation https://docs.sentry.io/platforms/react-native/performance/instrumentation/custom-instrumentation/

**Comment by krystofwoldrich** [comment]
Is this still a bug? Are we going to change this in near future?
