### ISSUE TITLE
App Start measurement has large (days, months) values on iOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-react-native#2295]
A customer with large scale has several transactions with App Start consisting of days/weeks/months.

This happens on iOS but not on Android.

iOS App Start code: https://github.com/getsentry/sentry-cocoa/blob/472d14683103300272ffaf6377385c49a41572dc/Sources/Sentry/SentryAppStartTracker.m#L100-L131

SDK version 3.4.0

**Comment by marandaneto** [comment]
@philipphofmann after your workaround to not report huge app start for iOS, is `PrivateSentrySDKOnly.appStartMeasurement` gonna return null? if so, we don't need to do anything here right now.

**Comment by philipphofmann** [comment]
Yes, `PrivateSentrySDKOnly.appStartMeasurement` is going to return `nil`. If you can, please wait for 7.18.0, which should be out today or tomorrow. Again contains some fixes related to this.

**Comment by marandaneto** [comment]
https://dev.to/pyricau/android-vitals-when-did-my-app-start-24p4
Apparently Android already can give you some weird values due to different reasons and the recommendation is to filter out App start with more than a minute, we should do that as well.

**Comment by marandaneto** [comment]
I could not reproduce it on my end, we've filtered out app starts with more than 60s, let's wait for more feedback or repro cases, and let's watch the app start data from now on.

**Comment by philipphofmann** [comment]
Most likely related to https://github.com/getsentry/sentry-cocoa/issues/1897 and https://github.com/getsentry/sentry-cocoa/issues/1849
