### ISSUE TITLE
Delete "Upload Debug Symbols to Sentry" if uploading source maps manually?

### ISSUE THREAD

**Issue by miladdev85** [getsentry/sentry-react-native#2296]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)
- [x]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.4.2

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  release: "x.x.x",
  dist: "2345",
});
```

---
**I have following issue:**
I'm uploading source maps manually. Should I delete the **"Upload Debug Symbols to Sentry"** in Xcode?

**Comment by jennmueng** [comment]
You want to revert the "Bundle React Native code and images" build phase to the original, usually
```sh
../node_modules/react-native/scripts/react-native-xcode.sh
```

"Upload Debug Symbols to Sentry" is for native debug symbols not js source maps.

**Comment by marandaneto** [comment]
https://docs.sentry.io/platforms/react-native/sourcemaps/#2-disable-the-automatic-source-maps-upload-script
