### ISSUE TITLE
Source Maps not working for React-Native. ( Hermes & Proguard enabled)

### ISSUE THREAD

**Issue by ARIPRASATH4664** [getsentry/sentry-react-native#2314]
### Environment

SaaS (https://sentry.io/)

### Version

"@sentry/react-native": "^3.4.3", "react-native": "0.64.2",

### Steps to Reproduce

I just followed the steps as per the document in the react-native sentry.

1. Created Source Maps using the react-native command.
2. Created bundle using the hermes-engine.
3. Composed the source map and uploaded it to correct dist and release.

**I was able to see the source map mapping in the releases from Sentry**

> Also adding hermes-engine package is crashing the android app.

### Expected Result

I should get the unminified crash report.

### Actual Result

<img width="793" alt="Screenshot 2022-06-20 at 8 48 59 AM" src="https://user-images.githubusercontent.com/65212662/174519704-d537d7f8-6ce5-499b-bb75-01ddd04d2b18.png">

Getting some random issue.

**Comment by bruno-garcia** [comment]
Might be related to: https://github.com/getsentry/sentry-react-native/issues/2244

**Comment by marandaneto** [comment]
@ARIPRASATH4664 can you share the link to the sentry issue?
can you share the commands you are using to generate the bundles?

> Also adding hermes-engine package is crashing the android app.

That's not Sentry's issue tho.

**Comment by ARIPRASATH4664** [comment]
@marandaneto I am usinghttps://docs.sentry.io/platforms/react-native/manual-setup/hermes/#custom-source-maps

> @ARIPRASATH4664 can you share the link to the sentry issue? can you share the commands you are using to generate the bundles?
>  i just followed this link https://docs.sentry.io/platforms/react-native/manual-setup/hermes/#custom-source-maps
> > Also adding hermes-engine package is crashing the android app.
> 
> That's not Sentry's issue tho.

**Comment by marandaneto** [comment]
@ARIPRASATH4664 I meant a link to an issue on sentry.io that shows off the problem.
E.g. https://sentry.io/organizations/$org/issues/$issue/?project=$project

**Comment by marandaneto** [comment]
Thanks, its a dup of https://github.com/getsentry/sentry-react-native/issues/2244 and https://github.com/facebook/react-native/issues/34043#issuecomment-1166281947
Let's wait for the Hermes team to help us out meanwhile.

**Comment by ARIPRASATH4664** [comment]
Thanks @marandaneto.

**Comment by ARIPRASATH4664** [comment]
Is this applicable to ios source maps? @marandaneto

**Comment by marandaneto** [comment]
Yes, there's a workaround for Android, it's in my comment.
For iOS, I don't have a working solution yet.

**Comment by ARIPRASATH4664** [comment]
@marandaneto  
I have seen the comment but I am little confused about that, You mean to say like I need to skip the step 3  ?
