### ISSUE TITLE
Native frames always timeout after upgrade to 4.0.1

### ISSUE THREAD

**Issue by wbinarytree** [getsentry/sentry-react-native#2317]
### Environment

How do you use Sentry?

self-hosted

Which SDK and version?

sentry-react-native 4.0.1

### Steps to Reproduce

Setup a Sentry with frame tracking like this:

```
      Sentry.init({
        dsn: dsn,
        debug: __DEV__,
        enableNativeCrashHandling: restricted,
        environment: env
        release: releaseName,
        dist: getBuildNumber(),
        integrations: [
            new Sentry.ReactNativeTracing({
            routingInstrumentation: routingInstrumentation,
            enableNativeFramesTracking: true,
            enableStallTracking: true,
          }),

```

### Expected Result

Frames are correctly reported. 

### Actual Result

Frames are not reported, always occurs error like:

```
[NativeFrames] Native frames timed out for OwnerApi: transaction 
```

Proposed solution. 

I dig into the code and see that actually the default integration will added regardless of user integration in this line:

https://github.com/getsentry/sentry-react-native/blob/main/src/js/sdk.tsx#L105

And eventually when we set up integrations here : 
https://github.com/getsentry/sentry-javascript/blob/master/packages/core/src/integration.ts#L61

The default `ReactNativeTracing` integration will override user setup `ReactNativeTracing`

**Comment by marandaneto** [comment]
@wbinarytree thanks, I'll check this out.

**Comment by wbinarytree** [comment]
@marandaneto Do you prefer I submit a PR for that?

**Comment by marandaneto** [comment]
> Fix: SDK overwrites the user defined ReactNativeTracing #2319

Thanks, I've opened a PR already since I needed to investigate it.

**Comment by wbinarytree** [comment]
@marandaneto Btw do we have a plan when we update the sentry cocoa to 7.8.1. It seems have a critical fix for frame tracking.
