### ISSUE TITLE
Version code doesn't handle all use cases in the gradle task

### ISSUE THREAD

**Issue by alexisloiselle** [getsentry/sentry-react-native#2322]
### Environment

How do you use Sentry?
**Sentry SaaS (sentry.io)**

Which SDK and version?
**@sentry/react-native@4.0.2**

### Steps to Reproduce

1. Upgraded to latest version.
2. Started the same CI process using
    - Azure Devops
    - [Mobile App Tasks for iOS and Android](https://marketplace.visualstudio.com/items?itemName=vs-publisher-473885.motz-mobile-buildtasks&targetId=dbee4a37-ce2f-4fca-b145-f162cad09648)
    - [Gradle@2](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops)

### Expected Result

Successful build.

### Actual Result

The build failed with this log:

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/runner/work/1/s/apps/gmap/node_modules/@sentry/react-native/sentry.gradle' line: 68

* What went wrong:
No signature of method: static java.lang.Math.abs() is applicable for argument types: (String) values: [347]
Possible solutions: abs(double), abs(float), abs(int), abs(long), any(), acos(double)
```

### Temporary solution

As a temporary solution, I patched the package to remove the `Math.abs` usage:
```diff
diff --git a/node_modules/@sentry/react-native/sentry.gradle b/node_modules/@sentry/react-native/sentry.gradle
index dcdc3d4..f175698 100644
--- a/node_modules/@sentry/react-native/sentry.gradle
+++ b/node_modules/@sentry/react-native/sentry.gradle
@@ -65,12 +65,11 @@ gradle.projectsEvaluated {
           variant = currentVariant[0]
           releaseName = currentVariant[1]
           versionCode = currentVariant[2]
-          def absVersionCode = Math.abs(versionCode)
 
           // The Sentry server distinguishes source maps by release (`--release` in the command
           // below) and distribution identifier (`--dist` below).  Give the task a unique name
           // based on where we're uploading to.
-          def nameCliTask = "${bundleTask.name}_SentryUpload_${releaseName}_${absVersionCode}"
+          def nameCliTask = "${bundleTask.name}_SentryUpload_${releaseName}_${versionCode}"
 
           // If several outputs have the same releaseName and versionCode, we'd do the exact same
           // upload for each of them.  No need to repeat.
```

**Comment by marandaneto** [comment]
@alexisloiselle What's the version of your RN engine, Gradle and AGP? We run this task on CI and it's not an issue.
Also, `versionCode` is an `int` as well, wondering how I can repro this.

**Comment by alexisloiselle** [comment]
The versions are:
- RN engine: ^0.68.1
- Gradle: 6.9
- AGP: 4.2.2

Maybe the Gradle version that I use is too old?

**Comment by marandaneto** [comment]
The RN template uses Gradle 7.3.3 for RN 0.68.x
https://github.com/facebook/react-native/blob/v0.68.2/template/android/gradle/wrapper/gradle-wrapper.properties
and AGP 7.0.4 https://github.com/facebook/react-native/blob/v0.68.2/template/android/build.gradle#L25=
Please try to upgrade it.

Otherwise, provide a minimal reproduction example, I can't reproduce it on my end.

**Comment by SpreadTriad** [comment]
Thank you, @marandaneto and team! :thumbsup:
