### ISSUE TITLE
v4: Unresolved reference: sentry

### ISSUE THREAD

**Issue by tapz** [getsentry/sentry-react-native#2331]
### Environment

How do you use Sentry?
SaaS

Which SDK and version?

"@sentry/react-native": "4.1.0",

Worked just fine with version 3.4.3

RN: 0.69.1
com.android.tools.build:gradle:7.1.1
gradle-7.3.3-all.zip

openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

MacOS Monterey
12.4 (21F79)

### Steps to Reproduce

1. Create .kt file (Android)
2. import io.sentry.Sentry
3. Build

### Expected Result

Sentry imported and build successful

### Actual Result

Unresolved reference: sentry

**Comment by marandaneto** [comment]
Dup https://github.com/getsentry/sentry-react-native/issues/2267
https://github.com/getsentry/sentry-react-native/issues/2267#issuecomment-1166231648
