### ISSUE TITLE
SentryError: Native Client is not available, can't start on native

### ISSUE THREAD

**Issue by MyloCarson** [getsentry/sentry-react-native#2335]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
"@sentry/react-native": "^4.1.0"
"react-native": "0.69.1"

### Steps to Reproduce

1. Upgrade to React Native 0.69
2. Install sentry
3. Run sentry setup wizard.

### Expected Result
I expected auto-linking. But it won't work for both ios and android.

I was able to Manually link ios using

``` pod 'RNSentry', :path => '../node_modules/@sentry/react-native/RNSentry.podspec'  ```

But as for android, the manual link failed also.
![Screenshot 2022-07-02 at 18 21 15](https://user-images.githubusercontent.com/12560014/177010262-26666ea5-4943-436b-bca7-533ab7dd0b5b.png)

**Comment by marandaneto** [comment]
Dup https://github.com/getsentry/sentry-react-native/issues/2267#issuecomment-1166231648
