### ISSUE TITLE
@sentry/react-native has been ignored because it contains invalid configuration. "dependency.platforms.ios.sharedLibraries"

### ISSUE THREAD

**Issue by yahyamokaied** [getsentry/sentry-react-native#2343]
### Environment
React Native 0.69.1

How do you use Sentry?
"@sentry/react-native": "^4.1.0"

Package @sentry/react-native has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.sharedLibraries" is not allowed

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/issues/2267#issuecomment-1166231648
