### ISSUE TITLE
'Sentry/SentryTraceContext.h' file not found

### ISSUE THREAD

**Issue by rafaelmaeuer** [getsentry/sentry-react-native#2353]
Build of React Native App fails after upgrading sentry-react-native to v4.x.x.

react-native-firebase > v15 requires `use_frameworks!` in podfile:
https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#breaking-changes

Seems like sentry-react-native has problems handling dynamic libraries in v4.
There is an open PR on sentry-cocoa for this: https://github.com/getsentry/sentry-cocoa/pull/1726

### Environment

How do you use Sentry?
- Sentry SaaS (sentry.io)

Which SDK and version?
- @sentry/react-native: v4.1.0

### Steps to Reproduce

1. Add `use_frameworks!` to podfile
2. Try to build React Native App

### Expected Result

Build should complete.

### Actual Result

Error: 'Sentry/SentryTraceContext.h' file not found in 'Development Pods/RNSentry/RNSentry.m'

<img width="712" alt="image" src="https://user-images.githubusercontent.com/6418459/177586428-3b05a469-0494-490e-b12f-cc6d5e960e5c.png">

For now this requires to hold back either sentry-react-native < v4 or react-native-firebase < v15

**Comment by marandaneto** [comment]
@rafaelmaeuer you've likely have an outdated pod, try to:

> cd ios
> pod update
> pod install

does it help?

**Comment by rafaelmaeuer** [comment]
> @rafaelmaeuer you've likely have an outdated pod, try to:
> 
> > cd ios
> > pod update
> > pod install
> 
> does it help?

Nope I did this several times while figuring out this error...

**Comment by marandaneto** [comment]
> > @rafaelmaeuer you've likely have an outdated pod, try to:
> > > cd ios
> > > pod update
> > > pod install
> > 
> > 
> > does it help?
> 
> Nope I did this several times while figuring out this error...

@rafaelmaeuer I've created an empty project (template) and everything worked out, so I can't reproduce this issue, since this class was added in the latest versions of the iOS SDK, seems like a cached pod issue.
Try to remove the pod lock file and the `node_nodules` and `yarn/npn install` again, `pod install` as well, if that does not work.
Can you provide a minimal reproduction example?

**Comment by rafaelmaeuer** [comment]
Yes of course:

- Init new App with RN 0.68.2
  ```sh
  npx react-native init MyApp --version 0.68.2
  ```
- Add @sentry/react-native
  ```sh
  cd MyApp
  yarn add @sentry/react-native
  ```
- Modify ios/Podfile
  - Add use_frameworks!
    ```diff
     platform :ios, '11.0'
    +use_frameworks!
     install! 'cocoapods', :deterministic_uuids => false
    ```
  - Disable hermes and fabric
    ```diff
    -    :hermes_enabled => flags[:hermes_enabled],
    -    :fabric_enabled => flags[:fabric_enabled],
    +    :hermes_enabled => false, #flags[:hermes_enabled],
    +    :fabric_enabled => false, #flags[:fabric_enabled],
    ```
  - Disable flipper
    ```diff
    -  use_flipper!()
    +  #use_flipper!()
    ```
- Install Pods
  ```sh
  cd ios
  pod install
  ```
- Open `MyApp.xcworkspace` and build MyApp
<img width="549" alt="image" src="https://user-images.githubusercontent.com/6418459/178295928-c64b5bba-2a2c-47d6-9d09-375655170e4c.png">

**Comment by marandaneto** [comment]
@brustolin or @philipphofmann can you take a look at this? I can't reproduce it but I've not tried with `use_frameworks`

**Comment by philipphofmann** [comment]
The RN SDK imports `SentryTraceContext`, which is not public
https://github.com/getsentry/sentry-react-native/blob/736eee2697e95315f1a76fc24e865c4564a5a9a8/ios/RNSentry.m#L11

see https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryTraceContext.h.

@brustolin, did you maybe recently change anything for the SentryTraceContext? Was it public before?

**Comment by brustolin** [comment]
So, a quick workaround in order for you to continue using the SDK before we fix it.

- Look for the RNSentry.m file in you Xcode project (Pods>Development Pods>RNSentry)
- Replace the line 11 (#import <Sentry/SentryTraceContext.h>) with:

```objc
@interface SentryTraceContext : NSObject
- (nullable instancetype)initWithDict:(NSDictionary<NSString *, id> *)dictionary;
@end
```

**Comment by philipphofmann** [comment]
@brustolin, could you maybe open a PR to fix the code in `RNSentry.m`, please?
