### ISSUE TITLE
Captured events are missing in sentry

### ISSUE THREAD

**Issue by ambatisuman** [getsentry/sentry-react-native#2364]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. We use `sentry.javascript.react-native` version `2.1.0`
2. If the app is restarted within 15secs, we capture an event with the 
```
 Sentry.captureMessage('Application was manually restarted', {
    level: 'info',
    user,
  })
```

3. The request is success and we get the event id back, but when we look at the sentry.io, we don't find the event.

4. As said, if the app is restarted within 15secs time, we ask the user to enter the feedback (optional), if the user enters the feedback, we append the feedback message to the above created event with the api https://docs.sentry.io/api/projects/submit-user-feedback/
5. After submitting the request (userFeedback), we receive the status code of 200, but we still don't see the event in sentry.io under events or the user feedback section.

### Expected Result

Captured event should be shown in the sentry.io

### Actual Result

No events are shown in sentry.io.

But all other events are shown.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
