### ISSUE TITLE
TypeError: Promise.allSettled is not a function

### ISSUE THREAD

**Issue by connorpmullins** [getsentry/sentry-react-native#2379]
### Environment
React Native / iOS

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Sentry.io

Which SDK and version?
@sentry/react-native 4.1.3
react-native 0.64.3
typescript 4.3.5
node 16.6

### Steps to Reproduce
Not sure I can assist with reproducing this issue - I haven't seen it replicated elsewhere with this setup. 

### Expected Result
No warnings are logged from instrument.js @ line 109

### Actual Result
Once a second (approximate), we receive a console warning that Promise.allSettled is not a function. When I inspect the stacktrace, I see a comment with a frowny face that this code fails for some browsers. 

Because of how react native works, this means that a popup appears on my screen every second and effectively keeps me from being able to use the tab bar of the app when logging is on

I've ensured that our Sentry version

What actually happened. Maybe a screenshot/recording? Maybe some logs?
![image](https://user-images.githubusercontent.com/24562987/179861850-5a411cc3-d299-4821-9874-358c54dcea40.png)
```
[app] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x600002ea4d40, {
category = xhr;
data =     {
method = POST;
"status_code" = 200;
url = "http://192.168.0.57:8081/open-stack-frame";
};
level = error;
timestamp = "2022-07-19T22:50:06.938Z";
type = http;
}>
[app] Sentry - debug:: Add breadcrumb: <SentryBreadcrumb: 0x600002e2b000, {
category = console;
data =     {
arguments = "[\"Possible Unhandled Promise Rejection (id: 7):\\nTypeError:
Promise.allSettled is not a function. (In 'Promise.allSettled(promises)',
'Promise.allSettled' is undefined)\"]";
logger = console;
};
level = warning;
message = "Possible Unhandled Promise Rejection (id: 7):\nTypeError: Promise.allSettled is
not a function. (In 'Promise.allSettled(promises)', 'Promise.allSettled' is undefined)";
timestamp = "2022-07-19T22:50:07.380Z";
}>

```

Thanks in advance for the assistance, please let me know if there's any additional information I can provide that would be helpful.

**Comment by marandaneto** [comment]
@connorpmullins I'm not sure this is a bug, See https://github.com/getsentry/sentry-react-native/blob/cd190906d8962d4896251385bf7e4853ef9ccbc1/src/js/integrations/reactnativeerrorhandlers.ts#L123-L125
We don't call `Promise.allSettled` at all.
Your app likely has an unhandled promise and Sentry logs out if it's in the `__DEV__` mode, if that's not the issue, what's the bug? mind adding more context?

**Comment by connorpmullins** [comment]
Hey @marandaneto - I think you're right, sorry and thank you for the prompt response! I was confused by Sentry being part of the stack trace here and by us not calling `Promise.allSettled` anywhere in our code. I believe it's another third party library throwing this.
