### ISSUE TITLE
Failure Rate increased upgrading @sentry/react-native to v4.1.2

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/sentry-react-native#2387]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.1.2

**`react-native` version:** 0.68.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS) v22.5.0
- [ ]  on-premise

**I have following issue:**

Failure rate increase drastically after releasing to production the upgraded SDK7 

![image](https://user-images.githubusercontent.com/77674046/180430476-8cf62bce-69de-4139-b222-f81d309293fc.png)
![image](https://user-images.githubusercontent.com/77674046/180430486-6b5e437a-28c1-4566-a31d-99e2b014f453.png)

1. Why is the failure rate increase so fast ? 
2. Is this bad ?
3.  What should we do ?
4. Is this related to the sentry sdk upgrade ?

This is the PR of the upgrade : https://github.com/pass-culture/pass-culture-app-native/pull/3240

**Comment by marandaneto** [comment]
@kopax-polyconseil what do you mean by SDK7? We RN SDK is in the range of 4.x

**Comment by kopax-polyconseil** [comment]
I thought it was the SDK7....

Have you checked the PR of the upgrade ? https://github.com/pass-culture/pass-culture-app-native/pull/3078/files

**Comment by marandaneto** [comment]
@kopax-polyconseil latest version is https://github.com/getsentry/sentry-react-native/releases/tag/4.2.0
Your PR upgrade just upgrades the dependencies so I don't see any issues with that.
Please investigate the new issues you are getting and check if they make sense, I can't tell it's an issue on the SDK if I don't have enough context.

**Comment by marandaneto** [comment]
@kopax-polyconseil Also please fix your title and PR description accordingly since you are not using the `SaaS` nor you are using SDK7.

**Comment by kopax-polyconseil** [comment]
> Please investigate the new issues you are getting and check if they make sense

What do you mean ? We have a failure_rate which means we do not receive new issue with status 'ok', from the doc:

`failure_rate()` indicates the percentage of unsuccessful transactions. Sentry treats transactions with a status other than “ok,” “canceled,” and “unknown” as failures. For more details, see a [list of possible status values](https://develop.sentry.dev/sdk/event-payloads/span/).


>  can't tell it's an issue on the SDK if I don't have enough context.

how can I give you more context?

I fixed the title.

**Comment by marandaneto** [comment]
We are not aware of any `failure_rate` issue.
Unless you provide more context, we can't tell whats happening, if you are receiving a higher % of `failure_rate`, go check your transactions and see what's going on.

**Comment by kopax-polyconseil** [comment]
> Unless you provide more context, we can't tell whats happening

Can you please clarify and tell me how I can share more context. These are metrics reported by sentry after our users downloaded the latest app, we don't know why and when it happen and locally when we tested, we were able to see the error going to sentry but we didn't had those metrics.

>  if you are receiving a higher % of failure_rate, go check your transactions and see what's going on.

I am sorry, I am a front-end developer, can I ask you how/where can I "check" the transaction? Is it in the self hosted logs, should I ask the ops?

**Comment by marandaneto** [comment]
@kopax-polyconseil That's a product question, https://docs.sentry.io/product/performance/metrics/
Sentry stands exactly for that, ask the person that is monitoring the data from your app on the Sentry dashboards and they will look into it, my goal here is to solve SDK issues, for learning how to use the Sentry product, I'd suggest asking on different Sentry channels, but first take a look at our [docs](https://docs.sentry.io/product/performance/), there is plenty of good material in there.

In case you narrow down the increase of `failure_rate` because of SDK bugs, please let us know and I will reopen the issue.
