### ISSUE TITLE
 @sentry/react-native contains invalid configuration

### ISSUE THREAD

**Issue by ajp8164** [getsentry/sentry-react-native#2391]
### Environment

SaaS (https://sentry.io/)

### Version

4.2.0

### Steps to Reproduce

1. create a react native app
2. add @sentry/react-native
3. run app with metro

### Expected Result

No warnings on app start.

### Actual Result

Warning appears in console at app start.

>warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by marandaneto** [comment]
@ajp8164 Are you using RN >= 0.69? Please try https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0-alpha.1

**Comment by marandaneto** [comment]
@ajp8164 any news here?

**Comment by Keshavdulal** [comment]
In my case (RN 0.69.2 // Xcode 13.4.1 // M1 Mac)
The Android build runs successfully, but the ios build was failing with the same message.

`
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
`

I got the same message with Sentry-react-native `v4.2.2` and with `v5.0.0-alpha.1` too.

So I dug a little deep.

I followed this [Medium Article](https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9) thanks to this [StackOverflow explanation](https://stackoverflow.com/a/65399525/3556531).

And now I am getting a successful build on iOS.

I also tested a forced Error to test the sentry integration and it's being reported on the Sentry dashboard.
`throw new Error("My first Sentry error!");`

I hope this helps someone.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/pull/2332

**Comment by ajp8164** [comment]
> @ajp8164 any news here?

I'm using RN 0.69.4. I have not tried the beta.

**Comment by KrisLau** [comment]
I still see the error on mine. Latest package version for react native and this package

**Comment by ajp8164** [comment]
I'll revise ;-) Had my project in a temp state. Yeah. Still there 😊

**Comment by KrisLau** [comment]
@marandaneto

**Comment by marandaneto** [comment]
Either you use https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0-alpha.1 or https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher
