### ISSUE TITLE
'Sentry/Sentry.h' file not found 

### ISSUE THREAD

**Issue by marlti7** [getsentry/sentry-react-native#2396]
### Environment
react-native: 0.59.9
 "@sentry/react-native": "^4.2.0",
 no use cocopods just remove podspec ; use link
 
 
 'Sentry/Sentry.h' file not found
 
 
 
 i find node_module has no Sentry.h file , so what do you link for this?

**Comment by marandaneto** [comment]
@marlti7 if you are using RN < 0.60 you have to link it manually
https://docs.sentry.io/platforms/react-native/#linking
Does that help?

**Comment by marlti7** [comment]
> @marlti7 if you are using RN < 0.60 you have to link it manually https://docs.sentry.io/platforms/react-native/#linking Does that help?

has link.

**Comment by marandaneto** [comment]
@marlti7 can you provide a Minimal reproducible example?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
