### ISSUE TITLE
Android issue: can't build project

### ISSUE THREAD

**Issue by brascene** [getsentry/sentry-react-native#2407]
After upgrading ReactNative to 0.68.2, I'm facing this issue only on Android, iOS is working as before, but when trying to run the app on Android build is failing with error about something in sentry.gradle file. Here's my environment info:

Libs:
react-native: 0.68.2
@sentry/react-native: 4.2.2

Error:
Build failed with an exception:
`...node_modules/@sentry/react-native/sentry.gradle' line: 37
`

What went wrong:
```
Could not create task ':app:uploadDebugPrivateApk'.
> com/android/build/api/artifact/ArtifactType$APK
```

Here's some more info that I could get on this error:
<img width="1157" alt="Screenshot 2022-07-28 at 16 04 39" src="https://user-images.githubusercontent.com/20214107/182342103-2503faa2-65bb-4dce-8c0b-57dee7313ea5.png">

**Comment by marandaneto** [comment]
@brascene what's the version of your [Gradle plugin](https://developer.android.com/studio/releases/gradle-plugin) and Gradle itself?
Can you give us a minimal reproducible example? I've tried locally and it just works (using default versions of RN 0.68.x)

**Comment by brascene** [comment]
I'm not android guy so I'll give you anything I can find related with gradle :)

- gradle-wrapper.properties:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
`
- android/build.gradle:
`classpath("com.android.tools.build:gradle:7.0.4")
`

**Comment by marandaneto** [comment]
@brascene this issue is likely with the other plugin and not Sentry's SDK.
Sentry does not create the `uploadDebugPrivateApk`.
Please check with folks on the https://github.com/Triple-T/gradle-play-publisher repo.

**Comment by brascene** [comment]
@marandaneto indeed this was related with `Triple-T`, just upgraded its version and it's Ok now.

Only reason I opened issue here on Sentry is that error log message pointing to sentry.gradle, and also when I comment out sentry from build.gradle it was also working, that's the reason why I thought it's about Sentry.
Thanks for your help!
