### ISSUE TITLE
Optimization problem with @sentry/react-native within a react-native-web app - lodash gots fully imported 

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/sentry-react-native#2409]
**OS:**
- [x]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.2

**`react-native` version:** 0.68.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise 22.5.0

**Configuration:**

---
**I have following issue:**

We use `lodash.*` do target exactly which module we need from `lodash`, but after buildeing our react-native-web app (which is also a react-native app), it appears looking at webpack-bundle-analyzer that one of our `dependency` (which is sentry-react-native) import the whole lodash. Is this necessary ?

![image](https://user-images.githubusercontent.com/77674046/182632789-570d5319-8f00-47b7-b685-66fe0d5a3cfd.png)

**see in red the multiple lodash we have now**

**Steps to reproduce:**
- yarn add @sentry/react-native
- npm ls lodash

**Actual result:**

```
├─┬ @sentry/react-native@4.2.2
│ └─┬ @sentry/wizard@1.2.17
│   ├─┬ inquirer@6.5.2
│   │ └── lodash@4.17.21 deduped
│   └── lodash@4.17.21 deduped
```

**Expected result:**

```
├─┬ @sentry/react-native@4.2.2
│ └─┬ @sentry/wizard@1.2.17
│   ├─┬ inquirer@6.5.2
│   │ └── lodash.something@4.17.21
│   └── lodash.something@4.17.21
```

## Related issues

- https://stackoverflow.com/questions/73222347/why-webpack-bundle-analyzer-show-lodash-bundled-more-than-once
- https://github.com/getsentry/sentry-wizard/issues/182

**Comment by kopax-polyconseil** [comment]
Also, I do see that https://www.npmjs.com/package/inquirer is a cli tool, what's the point of shipping it into our iOS/Android app ? Could this dependence be removed?

**Comment by marandaneto** [comment]
It was removed but it's back because of https://github.com/getsentry/sentry-react-native/pull/2015
We can remove it again for the [5.x](https://github.com/getsentry/sentry-react-native/pull/2389) release since we don't need to support older RN versions in that major bump.

**Comment by kopax-polyconseil** [comment]
Hi @marandaneto , it's great, do you have an ETA for the 5.x release ? Meanwhile I presume we must switch to lodash the whole instead of picking everything.

**Comment by kopax-polyconseil** [comment]
Keep open

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/blob/e96259b6ed55622619015e580ed9ca98f29ef8d5/package.json#L57

On the next major version v5, the wizard was moved to the dev deps, so please upgrade your SDK when you feel comfortable with, since its not GA yet.
