### ISSUE TITLE
Allow CLI failures (e.g. server connecting issues in build time)

### ISSUE THREAD

**Issue by n-kulic** [getsentry/sentry-react-native#2413]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 2.4.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.4.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: SENTRY_DSN,
    environment: 'dev'
})
```
---
**I have following issue:**

In IOS build process it happens that a request is made to our Sentry server, and if Sentry server is temporary down (in our case it happens often), an error throws:
```diff
-error: API request failed
  caused by: sentry reported an error: gateway timeout (http status: 504)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
```

I would like to allow CLI failure because it currently makes CI/CD pipeline to fail. 
In [@sentry/webpack-plugin](https://github.com/getsentry/sentry-webpack-plugin#options) there is an option to override default error handler and allow CLI failure, is there a similar option in `@sentry/react-native` as well?
_* source: https://github.com/getsentry/sentry-webpack-plugin#options (**errorHandler**)_

**Steps to reproduce:**
- Add Sentry to newly created app and initialize it `Sentry.init(..)`
- Close/stop Sentry server
- Try to build IOS project 

**Actual result:**

Build fails because Sentry server isn't responsive.

**Expected result:**

Allow CLI failures as in case when there are issues connecting to Sentry server (5xx error)

**Comment by nurycaroline** [comment]
Same issue here.

**Comment by marandaneto** [comment]
We are already tracking this issue [here](https://github.com/getsentry/team-mobile/issues/3), thanks for raising it.
