### ISSUE TITLE
Sentry Does Not Log Errors

### ISSUE THREAD

**Issue by dentep** [getsentry/sentry-react-native#2419]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 4.2.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

**Configuration:**
```
  Sentry.init({
    dsn: SENTRY_URL,
    environment: PRODUCTION ? 'front-prod' : 'front-dev',
    release: `${app.version}-${app.patchVersion}`,
    debug: true,
    beforeSend(event) {
      console.log(JSON.stringify(event, null, 2))

      return event
    },
  })
```

---
**I have following issue:**

Sentry does not send log messages unless they were prefixes with `Sentry.captureEvent()` or `Sentry.captureMessage()` or `Sentry.captureException()`. In the docs, it says that placing `throw new Error('This is my first Sentry Error')` should send a log to sentry dashboard. JS crashes like those are not getting noticed by sentry for unknown reason.

**Steps to reproduce:**
- Add config as stated above
- On any screen or any button press throw an error

**Actual result:**

- An error shows on the device's screen, but it is not logged on the server

**Expected result:**

- An error shows on the device's screen and getting sent to sentry's dashboard.

**Comment by marandaneto** [comment]
@dentep Thanks, What's the version of your React Native Engine and the Sentry SDK?

**Comment by lucas-zimerman** [comment]
Also since you're running on-premise, I experienced events not being sent because the self hosted was old and was rejecting some arguments on the envelope header, would you mind telling the version of your onpremise?

**Comment by marandaneto** [comment]
@dentep any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by justinlawrence** [comment]
Not sure why this had been closed. We literally spent a full week tracking
down a bug, due to Sentry not logging a chronos error. Ended up publishing
about 30 times to find the issue. Sentry was no help at all.

**Comment by marandaneto** [comment]
@justinlawrence We've made multiple questions, there were no answers.

> Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.

**Comment by vibexie** [comment]
Did you solved this issue? i had the same problem？ @dentep @marandaneto

**Comment by krystofwoldrich** [comment]
@vibexie Are you also using sentry on-premise? Could you check if the errors appear in the `beforeSend` callback? Or maybe your server rejects them?

**Comment by vibexie** [comment]
> @vibexie Are you also using sentry on-premise? Could you check if the errors appear in the `beforeSend` callback? Or maybe your server rejects them? You mentioned you had the same problem, how did you resolve it?

1. Using sentry on-premise
2. The errors appear  the beforeSend callback in all sentry-react-native versions (include v4.4.0 and above)
3. I guess it is't server rejection, because in the same server at the same time,  i checked v4.3.1 ok, but v4.4.0 and above appear this issue
4. I have no idea to resove it, so i fallback the version to v4.3.1 to solve it temporarily

Of course, only in ios, same with what @dentep described

**Comment by krystofwoldrich** [comment]
@vibexie Could you enable debug (`debug: true` in the SDK init) and look at iOS logs to check if the envelope is being sent?

**Comment by vibexie** [comment]
> @vibexie Could you enable debug (`debug: true` in the SDK init) and look at iOS logs to check if the envelope is being sent?

If i set debug true, it always shows "Sentry Logger [error]: Error while sending event: [RangeError: Maximum call stack size exceeded.]"

**Comment by krystofwoldrich** [comment]
Does it also happens with the latest [4.6.1](https://github.com/getsentry/sentry-react-native/releases/tag/4.6.1) release, could you try it? Could you post a sample app where this is happening, so we can try to debug it?

**Comment by vibexie** [comment]
> Does it also happens with the latest [4.6.1](https://github.com/getsentry/sentry-react-native/releases/tag/4.6.1) release, could you try it? Could you post a sample app where this is happening, so we can try to debug it?

1. The version which i tested in five hours ago is right 4.6.1.
2. Sorry, i could not provide a sample app, it is my company sentry server on-premise.  Could you make a sample using sentry on-premise by yourself. I guess you will catch the bug easily.

**Comment by krystofwoldrich** [comment]
@vibexie I have tried it and I can reproduce it. Could you try it with a new clean RN app, just add sentry to it and point it to your `dsn`? If that would work it's probably some config in your company app, then I would suggest copping the setting until it breaks. Then you could share the new app with us.
