### ISSUE TITLE
exception.values.0.stacktrace.frames: Missing value for required attribute

### ISSUE THREAD

**Issue by zeusstl** [getsentry/sentry-react-native#2429]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.3

**`react-native` version:** 0.65.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://sentry.io/organizations/grapevine/issues/3512638763/?project=2682797&query=is%3Aunresolved)

**Configuration:**

(`@sentry/react-native`)
```
let sentryDebug = (APP_ENV == 'zzzzz') ? false : true; <<<<Obscured for privacy
let sentryInitObj: Sentry.ReactNativeOptions = {
		dsn: SENTRY_DSN,
		debug: sentryDebug,
		environment: APP_ENV,
		release: version,
		dist: 'vxxxxx', <<<<Obscured for privacy
	};
	if ( APP_ENV == "zzzzz") { <<<<Obscured for privacy
		// Prevent console logs from being sent to Sentry on zzzzz <<<<Obscured for privacy
		sentryInitObj.integrations = [new Sentry.BrowserIntegrations.Breadcrumbs({ console: false })];
	}
	Sentry.init(sentryInitObj);
```

---
**I have following issue:**

Error messages that have been in place for years are suddenly having this red message box with:
```
There was 1 problem processing this event
exception.values.0.stacktrace.frames: Missing value for required attribute
```
Effectively this doesn't break the app, but it creates an unknown error that the team does not understand. We are concerned that this could have other adverse effects.

[Description]

**Steps to reproduce:**
- Run react native app
- Error occurs somewhere in the app
- View error in Sentry Issues interface online

**Actual result:**

1. The issue in the Sentry issue has this message in a red box:
```
There was 1 problem processing this event
exception.values.0.stacktrace.frames: Missing value for required attribute
```
2. There is also a more strange case of this where the error exception itself is the following:
`Sentry Logger [error]:`
https://sentry.io/organizations/grapevine/issues/3512638624/?project=2682797&query=is%3Aunresolved

**Expected result:**
To understand why these errors are happening and how to avoid them. It is unclear what `Missing value for required attribute` is referring to.

**Comment by marandaneto** [comment]
@zeusstl What was the exception type? Wondering if this is a regression in the JS SDK or something else.
Did you capture this event using `captureMessage`?

**Comment by marandaneto** [comment]
It could be related to https://github.com/getsentry/sentry-javascript/issues/5609

**Comment by zeusstl** [comment]
@marandaneto Part of the issue is that there is no information in the issue, so I don't know which Sentry call this is coming from:
`Sentry Logger [error]:`
We have hundreds of Sentry calls.

**Comment by zeusstl** [comment]
@marandaneto I think all of these errors are coming from within react native components. We recently added the react native error boundary wrapped around the app and nothing changed. But at some point these errors started to appear likely due to some other changes we made. Now it's making sense that these are from the react native error boundary. Does Sentry support the error boundary handlers? The main thing that seems off is that the sentry issue has the title `Unknown` and it has this warning about missing frames.

**Comment by marandaneto** [comment]
@zeusstl missing frames is just a warning, the exception, stack trace, and frames were not available and that's the problem.
We need to be sure where this comes from.
Can you reproduce this issue @zeusstl , can you provide specific steps or a minimal reproducible example?
How are you setting the error boundary? how are you throwing errors? etc.
