### ISSUE TITLE
SourceMap works not working in app-center build when source map uploaded to correct dist and release both Android & iOS

### ISSUE THREAD

**Issue by ARIPRASATH4664** [getsentry/sentry-react-native#2439]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)
- [X]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.4.3

**`react-native` version:** 0.64.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

I Have issues in sourcemap for the builds from appcenter is not working as expected. The same works good in local build system in both Android and Ios

**Steps to reproduce:**
- Archive the iOS locally, and /gradlew assembleRelease for android sourcemap errors were working as expected
- The same done through the appcenterr is not mapping as expected

**Actual result:**

Source Maps should be working

**Expected result:**

Not working in app-center build, but works in local builds

**Comment by marandaneto** [comment]
@ARIPRASATH4664 Can you give more context? what's not working?
Can you upgrade the SDK since you are not using the latest version?
Can you link a sentry.io issue so I can have a look at it?
Thanks.

**Comment by ARIPRASATH4664** [comment]
Sure will check and let you know after the update @marandaneto, I don't have the project active now but I just followed the steps, and source maps work as expected when the release builds are generated from my machine but when the build is generated i don't see this mapping happens right because the code and line changes were not exact

**Comment by ARIPRASATH4664** [comment]
@marandaneto https://sentry.io/organizations/rently-ed/issues/3561338198/?project=6692560&query=is%3Aunresolved
Please have a look at this

**Comment by marandaneto** [comment]
@ARIPRASATH4664 are you uploading source maps via sentry-cli manually or its uploading automatically?
Can you upgrade the SDK and test it again?
Also take a look to read the Hermes [docs](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/) and Codepush [docs](https://docs.sentry.io/platforms/react-native/manual-setup/codepush/).
You need to be sure that Sentry has the up to date source maps and release/dist match.

**Comment by marandaneto** [comment]
@ARIPRASATH4664 ok, should we close it then?
