### ISSUE TITLE
Crash on Android: io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush Input dispatching timed out

### ISSUE THREAD

**Issue by Waltari10** [getsentry/sentry-react-native#2441]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.3

**`react-native` version:** 0.68.1

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Issue is not reported to sentry.io

**Configuration:**

(`@sentry/react-native`)
```
export const routingInstrumentation =
  new Sentry.ReactNavigationInstrumentation();
Sentry.init({
        tracesSampleRate: config.NODE_ENV === "development" ? 1 : 0.04,
        environment: config.RELEASE_STAGE,
        enabled: config.NODE_ENV !== "development",
        dsn: config.SENTRY_DSN,
        integrations: [
          new Sentry.ReactNativeTracing({
            // performance tracking
            routingInstrumentation,
          }),
        ],
      });
```
Also in MainApplication.java
```
@Override
  public void onCreate() {
    super.onCreate();

    SentryAndroid.init(this, options -> {
      options.setDsn(BuildConfig.SENTRY_DSN);
      options.setEnvironment(BuildConfig.RELEASE_STAGE);
    });

    SoLoader.init(this, /* native exopackage */ false);

    IntercomModule.initialize(this, BuildConfig.INTERCOM_CLIENT_API_KEY_ANDROID, BuildConfig.INTERCOM_APP_ID);

  }

```

---
**I have following issue:**

From Play Store Console Crash reporting, reported as Application not responding(ANR)
```
io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush
Input dispatching timed out
```

```
Thread
"main" tid=1 Timed Waiting
  at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1063)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1358)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278)
  at io.sentry.UncaughtExceptionHandlerIntegration$UncaughtExceptionHint.waitFlush (UncaughtExceptionHandlerIntegration.java:164)
  at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException (UncaughtExceptionHandlerIntegration.java:102)
  at io.intercom.android.sdk.errorreporting.IntercomExceptionHandler.uncaughtException (IntercomExceptionHandler.java:37)
  at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException (UncaughtExceptionHandlerIntegration.java:118)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1073)
  at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
  at java.lang.Thread.dispatchUncaughtException (Thread.java:2200)
```

More logcat logs: https://gist.github.com/Waltari10/71c68469a7162e6ef6fb55e8a6410ccc

Seems to rarely happen more than once to a single user. So far we have about 30-40 incidents. 

I just realised that maybe it's related to using both Intercom and Sentry together with React Native since intercom is always mentioned with that crash report.

We have latest Intercom version:
"@intercom/intercom-react-native": "3.0.5",

Unfortunately haven't been able to reproduce this bug, so just trying it without Intercom is not really possible.

Or is it that both Intercom and Sentry are trying to grab the issue or have somehow overlapping ExceptionHandlers?

**Steps to reproduce:**
- Unknown

**Actual result:**

Crashes on Android

**Expected result:**

Should not crash

**Comment by marandaneto** [comment]
If you are calling `Sentry.init` on the JS side, you don't need to call `SentryAndroid.init` on Android, everything on the native side is automatically started, maybe that's the problem.
You only need to init the JS side.
Can you check if that helps?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by Waltari10** [comment]
Thank you! That seems to have fixed it.
