### ISSUE TITLE
When I set enableNative=true on init method options the application does not start on android or ios.

### ISSUE THREAD

**Issue by santiagorodriguez24** [getsentry/sentry-react-native#2446]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x ]  iOS
- [x]  Android

**SDK:**
- [ X]  `@sentry/react-native` ( "^3.4.3") 
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.4.3 - I also try to update to 4.2.4 with the same result.

**`react-native` version:** 0.68.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
const config = (): void => {
  const { Environment, EnvironmentVariables, EnvironmentNames } =
    EnvironmentConfig;
  init({
    dsn: EnvironmentVariables.SENTRY_DSN,
    release: `Bundle-ID:${DeviceInfo.getBundleId().toLowerCase()}@App-Version:${DeviceInfo.getVersion()}@Build-Number:${DeviceInfo.getBuildNumber()}`,
    autoSessionTracking: true,
    environment: Environment,
    enableNative: false, // Set this boolean to false to disable the native SDK. This will disable all native crash and error handling and, instead, the SDK will only capture errors on the upper layer. ADDED to avoid app crash
    enableNdkScopeSync: true,
    dist: DeviceInfo.getBuildNumber(),
    maxBreadcrumbs: Environment === EnvironmentNames.development ? 10 : 100,
    // Sessions close after app is 60 seconds in the background.
    sessionTrackingIntervalMillis: 60000,
    integrations: [
      new ReactNativeErrorHandlers({
        patchGlobalPromise: false,
      }),
    ],
  });
};
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- set enableNative option to true.
- try to open the app. It remains on splash screen. onReady callback is never called. 
- set enableNative to false.
- Everything works well.
- But no crashes reported on sentry.io.

**Actual result:**

- set enableNative option to true.
- try to open the app. It remains on splash screen.
- set enableNative to false.
- Everything works well.
- But no crashes reported on sentry.io.

**Expected result:**

- set enableNative option to true
- app works on both platforms and we get crash reports on sentry.io

**Comment by marandaneto** [comment]
@santiagorodriguez24 `enableNative` is enabled by default, you don't need to overwrite it anyway.
Which device is it? which OS version?
Can you provide a minimal reproducible example?
I've tried it myself and everything works.
