### ISSUE TITLE
`attachStacktrace` enabled by default on the JS layer

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2461]
### Description

Android and iOS have it enabled by default.
Its disabled by default on JS and RN inherits this option from JS when events are captured in the JS layer.
Double-check if this [issue](https://github.com/getsentry/sentry-react-native/issues/2131) is fixed as well.
Amend the docs https://github.com/getsentry/sentry-docs/pull/2815/files

**Comment by krystofwoldrich** [comment]
https://github.com/getsentry/sentry-react-native/issues/2131 is fixed, but the stack trace is sent in the `exception` with the message. Correctly it should be in the `threads`

**Comment by marandaneto** [comment]
@krystofwoldrich can we somehow monkeypatch the [fix](https://github.com/getsentry/sentry-javascript/pull/6038) directly into RN?
Looking at the [v8 milestone on JS](https://github.com/getsentry/sentry-javascript/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A8.0.0), not sure about the timeline, might be a bit of stuff and this is going to be after our v5, so we'd need to do v6 to add this breaking change.

**Comment by krystofwoldrich** [comment]
For sure we can fix in in RN and remove the fix after upgrading to v8.

@marandaneto When we release RN v5, won't we have to release RN v6 anyway because of changes in JS .v8

**Comment by marandaneto** [comment]
mmm, your call then @krystofwoldrich

**Comment by krystofwoldrich** [comment]
Patching in would be quite complicated since it's not only about patching `eventFromMessage` but also the `Event` interface is missing the `threads` property.

Or maybe we could add `threads` to `Event` in JS SDK v7. 
- https://github.com/getsentry/sentry-javascript/pull/6038#r1047070949

**Comment by marandaneto** [comment]
Adding threads would not be breaking, just extending the protocol, good idea.
