### ISSUE TITLE
maxTransactionDuration is in ms, not seconds

### ISSUE THREAD

**Issue by i1skn** [getsentry/sentry-react-native#2468]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.3.0

**`react-native` version:** 0.66.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**I have following issue:**

`maxTransactionDuration` here https://github.com/getsentry/sentry-react-native/blob/22ddfe3f0f4cabd21c585f63acba0851cf51ef86/src/js/tracing/reactnativetracing.ts#L49 is indeed in milliseconds and not in seconds. When I try to use `Sentry` with default values, all transactions are capped at around ~600ms with `deadline_exceeded`. If I set `maxTransactionDuration` manually to say 300 or 700, they are capped with the same message on 300ms or 700ms.

**Actual result:**

`maxTransactionDuration` is in ms

**Expected result:**
`maxTransactionDuration` should use seconds

**Comment by marandaneto** [comment]
Sounds like related to https://github.com/getsentry/sentry-react-native/issues/2467
