### ISSUE TITLE
Outdated instructions for "Manual Configuration" of debug symbols upload on iOS

### ISSUE THREAD

**Issue by birdofpreyru** [getsentry/sentry-react-native#2483]
This is a documentation issue. [Here](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#bundle-react-native-code-and-images) you say "we modify Bundle React Native code and images phase" from:

```bash
export NODE_BINARY=node
../node_modules/react-native/packager/react-native-xcode.sh
```

as of RN@0.70.1 the original script in that phase looks like this

```bash
set -e
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE";
```

and the next snippet does not work for me:
```bash
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=../sentry.properties

# If you are using RN 0.46+
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
  ../node_modules/react-native/scripts/react-native-xcode.sh
```

It should be changed to something like this, I believe:

```bash
set -e

export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES="$SRCROOT/sentry.properties"

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

$WITH_ENVIRONMENT "../node_modules/@sentry/cli/bin/sentry-cli react-native xcode"
/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

Similarly, the code in the [next section](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry) does not seem to work for me, unless changed into:
```bash
export SENTRY_PROPERTIES=$SRCROOT/sentry.properties
WITH_ENVIRONMENT="$SRCROOT/../node_modules/react-native/scripts/xcode/with-environment.sh"

$WITH_ENVIRONMENT "$SRCROOT/../node_modules/@sentry/cli/bin/sentry-cli upload-dif $DWARF_DSYM_FOLDER_PATH"
```

**Comment by krystofwoldrich** [comment]
Thank you for catching that. We are aware of the changes from RN 0.69 and up.

Until the stable release of 5.0.0 (https://github.com/getsentry/sentry-react-native/pull/2389) we have written down the changes here https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher
