### ISSUE TITLE
Warm Startup Time tracked as 24h in average

### ISSUE THREAD

**Issue by fabiendem** [getsentry/sentry-react-native#2490]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** v4.3.1

**`react-native` version:** 0.66.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
// In the App's componentDidMount

SentrySdk.init({
    dsn: sentryConfig.dsn,
    release: releaseIdentifier,
    dist: BuildInfo.buildVersion,
    enableAutoSessionTracking: true,
    enableAutoPerformanceTracking: true,
    tracesSampleRate: 0.1,
    integrations: [
      new SentrySdk.ReactNativeTracing({
        // Pass the React Navigation instrumentation to be used as `routingInstrumentation`
        // See https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-navigation-v4
        routingInstrumentation,
      }),
    ],
  });
```

---
**I have following issue:**

We track the performances of our React Native app.

**Actual result:**

The cold startup time is given at ~2 seconds, which is okay...
The warm startup time is given at 24h.

**Expected result:**

The warm startup time should be accurate, around a few ms or seconds.

Is this a known bug? Or have we missed something in our configuration?

**Comment by marandaneto** [comment]
@fabiendem can you link us to a sentry issue that shows the long warm start-up? there were issues before related to that, but not in the latest version, are those coming from older SDK versions?

**Comment by fabiendem** [comment]
@marandaneto Ok thanks, we've been using RN Sentry v3.2.13.
We've just updated it but the app release is not out yet, so we will need to wait a bit to see the results.
Do you know in which release this was fixed? I couldn't find a commit message which seemed relevant.

You can see the stats over [there](https://sentry.io/organizations/hingehealth/discover/results/?display=previous&field=transaction&field=project&field=p75%28measurements.app_start_warm%29&name=Warm%20Startup%20Time&project=5173911&query=event.type%3Atransaction&sort=-tpm&statsPeriod=7d&yAxis=p75%28measurements.app_start_warm%29), private access.

**Comment by marandaneto** [comment]
Its in the 4.x version, I'd upgrade to the latest version.
For context https://github.com/getsentry/sentry-react-native/issues/2295

**Comment by fabiendem** [comment]
Great thanks for the context

**Comment by fabiendem** [comment]
Hi @marandaneto, sorry to reopen this but we seem to have a regression here.
We're running `"@sentry/react-native": "4.14.0"`.

We have the issue again with startup time close to several hours sometimes.

Over 90 days
![Screen Shot 2023-02-22 at 11 10 54](https://user-images.githubusercontent.com/1186282/220608124-25386e06-b974-45c7-a32f-009c2231a671.png)

Over 7 days
![Screen Shot 2023-02-22 at 11 32 05](https://user-images.githubusercontent.com/1186282/220608213-0d8b4cbd-1c76-48c2-932e-4a66c9be690f.png)

Is there anything we're missing? Is it a known issue?
Cheers!

**Comment by krystofwoldrich** [comment]
@fabiendem I'm not aware of any changes regarding the warm startup time. Did the regression happen with any specific version?

**Comment by fabiendem** [comment]
> Did the regression happen with any specific version?

I am struggling to find which change would have introduced this at the moment.
It could be related to the update from  4.10.1 to 4.14.0. We did this around that time.

Filtering by Sentry SDK version returns no results:

![Screen Shot 2023-02-23 at 14 26 01](https://user-images.githubusercontent.com/1186282/220935317-7d32d369-843e-40cc-bb28-bd1f6a9895bb.png)

![Screen Shot 2023-02-23 at 14 26 42](https://user-images.githubusercontent.com/1186282/220935444-a8c7be75-add5-4a20-b460-f535a9b53488.png)


I am wondering if this stat is not getting mixed with other transactions we're tracking:

![Screen Shot 2023-02-23 at 14 20 38](https://user-images.githubusercontent.com/1186282/220934280-05dc3217-0447-441e-be89-87911852cef9.png)

**Comment by krystofwoldrich** [comment]
Since `4.5.0` the measurement was renamed to `app.start.warm`.

Could you try the search with the specified version and `measurements.app.start.warm`?

**Comment by fabiendem** [comment]
Ok.
Sorry I can't find any transaction with `app.start.warm` or `measurements.app.start.warm`.
Though I am not sure I am doing the search correctly. If you have a screenshot it could help.

I am getting there using the "Open in Discover" option of the "Warm Startup Time" widget, displayed on the Mobile tab in the Performance section.
https://foobar.sentry.io/performance/?landingDisplay=mobile&query=

Maybe the "Warm Startup Time" widget must be updated on your end?

**Comment by krystofwoldrich** [comment]
@fabiendem Thanks for the info, we are working on a fix [here](https://github.com/getsentry/sentry-react-native/pull/2855). Because of the naming difference, only organizations with custom metrics could see the `measurements.app.start.warm`.
