### ISSUE TITLE
BufferSize TransportOptions doesn't work

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2497]
NativeTransport uses hardcoded 30 items in promise buffer 

https://github.com/getsentry/sentry-react-native/blob/1e21438517050133d603247baeff05a464c76407/src/js/transports/native.ts#L11

Cocoa SDK uses different name for the bufferSize

https://github.com/getsentry/sentry-cocoa/blob/172c95a0f5823a6a1c37cd1b2d348ed047ba67b4/Sources/Sentry/SentryOptions.m#L47

The naming across the sdks should mathch.

**Comment by krystofwoldrich** [comment]
@marandaneto And maxQueueSize is option of the sdk or transport?

**Comment by philipphofmann** [comment]
It's a public option on [Java](https://github.com/getsentry/sentry-java/blob/24d5c4f3c7acddcc1075f105a221488abf657f0d/sentry/src/main/java/io/sentry/SentryOptions.java#L1154-L1163) and most other SDKs.

**Comment by krystofwoldrich** [comment]
Okay, if I'm looking correct Transport gets the same SentryOptions.

In JS there is different interface only for TransportOptions, where `bufferSize` is defined.

**Comment by krystofwoldrich** [comment]
Deprecate the current unused option and used a new one named similar to the native mobile skds. Pass the options to java and ios. Keep default 30.
