### ISSUE TITLE
beforeBreadcrumb, withScope callbacks do not have their Exceptions caught

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2499]
this resolves in the app crashing

- https://github.com/getsentry/team-mobile/issues/21

JS sdk doesn't solve this because the website doesn't crash like RN app does

List of callback:
- beforeSend - safe from JS sdk
-  beforeBreadcrumb  - not safe - JS sdk won't cahnge it (it doesn't crash a page)
- withScope - not safe - JS sdk won't cahnge it (it doesn't crash a page)
-   onReady - not safe
- integrations - not safe
- initialScope - deprecated not safe 

What should we do with:
- transport - note safe -> create default?
- tracesSampler  - not safe -> default to 0?

**Comment by marandaneto** [comment]
@krystofwoldrich I suspect that we've missed one of them:

configureScope:

```
                Sentry.configureScope((scope: Scope) => {
                  ...
                });
```

Or is it safe? [I guess not](https://github.com/getsentry/sentry-javascript/blob/f5cbc4c79c8757ebc2110aca4f4c01c2344a06b0/packages/hub/src/exports.ts#L67-L73).

**Comment by krystofwoldrich** [comment]
@marandaneto Yes, we missed this one. I'll add it.
