### ISSUE TITLE
NDK debug symbols are not uploaded

### ISSUE THREAD

**Issue by sregg** [getsentry/sentry-react-native#2512]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.3.1

**`react-native` version:** 0.67.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://sentry.io/organizations/properly-homes/issues/3596317273)

**Configuration:**

(`@sentry/react-native`)
```typescript
Sentry.init({
    dsn: '...',
    environment: 'production',
    integrations: [
      new Sentry.ReactNativeTracing({
        tracingOrigins: [...],
        routingInstrumentation: sentryRoutingInstrumentation,
      }),
    ],
    tracesSampleRate: 1,
    beforeSend(event) {
      const { level, message, exception } = event;
      let errorMessage = message ?? '';
      if (exception?.values?.length) {
        if (errorMessage.length) {
          errorMessage += ' ';
        }
        errorMessage += exception.values.map((v) => v.value).join(' ');
      }
      if (level === 'fatal' || level === 'error') {
        segmentClient.track('Application Crashed', {
          message: errorMessage,
          level,
        });
      }
      return event;
    },
  });
```

Android Gradle plugin used like so:

```groovy
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
```

---
**I have following issue:**

Crashes in libjsc are not de-symbolicated.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/1479283/193663145-466c0b87-3599-4318-af67-00042956d830.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1479283/193663178-634f8e44-86cf-409c-913c-e85b56bc5f66.png">
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1479283/193663962-efa16636-0723-42f9-b97b-9326da10ee51.png">

The [docs](https://docs.sentry.io/platforms/react-native/upload-debug/#when-to-upload) mention this:

> Errors raised from the native layer in Android apps require certain debug information files to be uploaded. For example, dwarf debug files need to be uploaded for an Android app with [NDK](https://developer.android.com/ndk/) support.

but doesn't explain how to get dwarf debug files and how to upload them.

The [Android docs](https://docs.sentry.io/platforms/android/gradle/#configure) mention a `uploadNativeSymbols` but I'm not sure that applies to React Native projects.

**Comment by marandaneto** [comment]
The docs links to [this section](https://docs.sentry.io/platforms/react-native/upload-debug/#uploading-with-sentry-gradle-plugin).
Which ends up in https://docs.sentry.io/platforms/android/gradle/
So you have to install the Gradle plugin for Android and turn on the `uploadNativeSymbols` as you suspected.

**Comment by sregg** [comment]
Thanks @marandaneto but the docs doesn't explain how to use the plugin in a React Native app.
Do I replace this line `apply from: "../../node_modules/@sentry/react-native/sentry.gradle"` ?
Do I keep it?
Is the plugin even compatible with a React Native project?
It'd be great to have these answers in the RN docs.

**Comment by sregg** [comment]
Just tested by adding these lines to the top of our `android/app/build.gradle`:

```
plugins {
    id "io.sentry.android.gradle" version "2.1.5"
}
sentry {
    uploadNativeSymbols = true
}
```

and keeping the `apply from` line and all the `.so` files were uploaded successfully to Sentry.
