### ISSUE TITLE
NativeArgumentsParseException: RNSentry.captureEnvelope got 3 arguments, expected 4

### ISSUE THREAD

**Issue by PingvinB** [getsentry/sentry-react-native#2516]
**OS:**
- [x]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.6.0

**`react-native` version:** 0.69.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**`sentry-expo` version:** 5.0.2

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
Can't, sorry. TMI.

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  enableInExpoDevelopment: true,
  debug: true,
  environment: getEnvironment().expoReleaseChannel || 'Development',
  beforeSend: (event: any) => {
      if (event.user) {
          delete event.user.name;
          delete event.user.phoneNumber;
          delete event.user.email;
      }
      return event;
  },
});
```

---
**I have following issue:**

I think Sentry is trying to log a 404 result of a fetch request that happens on app launch. 
Then the app crashes because of this exception:
`NativeArgumentsParseException: RNSentry.captureEnvelope got 3 arguments, expected 4`

![image](https://user-images.githubusercontent.com/89900134/193994611-b5fb1dfc-5d33-40ad-ace3-742fd5b98ec5.png)

I apologize for the lack of info or a reproducible demo.

**Comment by marandaneto** [comment]
Dup https://github.com/getsentry/sentry-react-native/issues/2505
