### ISSUE TITLE
Replace `sdkInfo` on iOS

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2530]
### Description

https://github.com/getsentry/sentry-react-native/blob/86821a42777cb1819de312df6cac058f5224b1af/ios/RNSentry.m#L158-L161

sdkInfo is deprecated https://github.com/getsentry/sentry-cocoa/pull/1960

PrivateSentrySDKOnly.getSdkName
and
PrivateSentrySDKOnly.getSdkVersionString
to retrieve the information

Cocoa [issue](https://github.com/getsentry/sentry-cocoa/issues/2270)

**Comment by brustolin** [comment]
Instead of this:
```objc
resolve(@{ 
     @"name": sentryOptions.sdkInfo.name, 
     @"version": sentryOptions.sdkInfo.version 
         }); 
```

do this
```objc
resolve(@{ 
     @"name": PrivateSentrySDKOnly.getSdkName, 
     @"version": PrivateSentrySDKOnly.getSdkVersionString 
         }); 
```

**Comment by marandaneto** [comment]
@brustolin that's possible but still not possible to add a new package.
https://github.com/getsentry/sentry-dart/issues/1056#issuecomment-1272970663

**Comment by marandaneto** [comment]
on RN iOS, the new package is added on the JS layer.
https://github.com/getsentry/sentry-react-native/blob/86821a42777cb1819de312df6cac058f5224b1af/src/js/integrations/sdkinfo.ts#L54-L61
via `_nativeSdkInfo` that is fetch from `fetchNativeSdkInfo`
So this is possible with the https://github.com/getsentry/sentry-react-native/issues/2530#issuecomment-1272964146 alternative.

**Comment by brustolin** [comment]
Can we close this?

**Comment by marandaneto** [comment]
> Can we close this?

This is not fixed yet, why would we close it?
