### ISSUE TITLE
no source maps are generated

### ISSUE THREAD

**Issue by davoam** [getsentry/sentry-react-native#2538]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.6.1

**`react-native` version:** 0.70.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://sentry.io/organizations/friend2meet-inc/issues/3650710476/events/d8bbbe899d4e439dbe5b86af8024cfdf/?project=4503931679473664)

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn: 'https://9ee0bfad88264a66ac854e8a7af071e3@o4503931044233216.ingest.sentry.io/4503931679473664',
    // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
    // We recommend adjusting this value in production.
    tracesSampleRate: 1.0,
    environment: __DEV__ ? 'development' : 'production',
  });
```

or

---
**I have following issue:**

[Description]

Source maps are not getting uploaded. I tried [this](https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher). It solved the problem with file not found in xCode, but source maps are still missing.

```
app:///index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example
```

**Actual result:**
No source map

**Expected result:**
Source maps are present and it's shown where error happens in TypeScript file

**Comment by mym0404** [comment]
I suffered iOS source map missing problem too after bump RN `0.67.4` -> `0.70.1`

**Comment by marandaneto** [comment]
@davoam please provide a minimal reproducible example, by doing [this](https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher) everything should work for RN >= 0.69.x
Unless your environment has a different setup than normal.
Also share your SDK init code snippet.

**Comment by davoam** [comment]
> ~I suffered iOS source map missing problem too after bump RN `0.67.4` -> `0.70.1`~
> 
> Did you try run `npx @sentry/wizard -i reactNative -p ios`?
> 
> I fixed with this [docs](https://docs.sentry.io/platforms/react-native/#run-the-sentry-wizard)

yeah, I ran the wizard, but it didn't help

**Comment by davoam** [comment]
> @davoam please provide a minimal reproducible example, by doing [this](https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher) everything should work for RN >= 0.69.x Unless your environment has a different setup than normal. Also share your SDK init code snippet.

Could you please clarify what is meant by `SDK init code`? If it `Sentry.init` call, I've added it in the issue description

**Comment by krystofwoldrich** [comment]
@davoam Thank you for the `SDK init code` in the description. Could you provide a reproducible example, a link to a repo/zip file with an app sample where the source maps are not being uploaded?

**Comment by mym0404** [comment]
#### 1. Sure `projectRoot/ios/sentry.properties exists like the following.
![image](https://user-images.githubusercontent.com/33388801/196152708-7dfbdcd3-2a64-4cdb-a605-1556f264744e.png)

#### 2. Check Xcode build phase script exists and runs as expect
![image](https://user-images.githubusercontent.com/33388801/196152893-97343c83-82a7-4412-a9c1-26e73d00c4c0.png)

**Comment by marandaneto** [comment]
@davoam provide a minimal reproducible example on GH and we can take a look, I am pretty sure it's something with your environment, we have this running locally and on CI with integration tests, and its working.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
