### ISSUE TITLE
Add turbo_module and fabric usage to context

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2541]
### Description

Similarly as hermes engine

https://github.com/getsentry/sentry-react-native/blob/c95aa21497ca93aaaaf0b44d170dc39dc7bcf660/src/js/sdk.tsx#L136

tract turbo modules and fabric renderer.

**Comment by marandaneto** [comment]
SDKs should not create tags automatically, ideally, all those tags go under the `contexts`, and later make them searchable via Snuba queries.

**Comment by krystofwoldrich** [comment]
Okay, I didn't know that. In that case, should we remove the `hermes` tag in v5 and add it to the context? Or would that cause a lot of trouble for our customers, possibly?

**Comment by marandaneto** [comment]
> Okay, I didn't know that. In that case, should we remove the `hermes` tag in v5 and add it to the context? Or would that cause a lot of trouble for our customers, possibly?

nope, I'd say this is a different issue, I'd add this info as part of the `contexts` instead of `tags` only.

**Comment by krystofwoldrich** [comment]
Let's make these indexed on SNUBA so we can filter events and track the adoption of the RN new architecture.

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/pull/2552
