### ISSUE TITLE
Should `sentry-cli` be removed from `dependencies`?

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2556]
### Description

`sentry/cli` today is a `dependencies` and it's installed within the final app affecting the bundle size.

The trade-off here is that if we remove the cli as a dependency, users would need to install the cli manually, via docs, for example, patching the getting started and the wizard docs.
https://docs.sentry.io/platforms/react-native/#install

The CLI is needed for uploading debug symbols in the final app, so they need to have the cli installed.

**Comment by marandaneto** [comment]
Example:
`yarn add @sentry/react-native`
`yarn add @sentry/cli --dev`

**Comment by krystofwoldrich** [comment]
So I have tested this and to my surprise removing the CLI did not change the bundle size at all.

5.0.0 - https://github.com/getsentry/sentry-react-native/pull/2389#issuecomment-1257765450
5.0.0 without CLI - https://github.com/getsentry/sentry-react-native/pull/2560#issuecomment-1284269557

Most likely as the CLI package is not used in RN SDK it gets ommited during [the resolution phase](https://facebook.github.io/metro/docs/concepts#resolution).

Therefore I think let's leave the CLI as dep and move one with https://github.com/getsentry/sentry-react-native/pull/2457?

**Comment by krystofwoldrich** [comment]
After discussing this in person we will keep CLI as dep to keep the install process easy for our users.
