### ISSUE TITLE
v5.0.0-alpha.6 hardcodes Folly version which makes it incompatible if used with a react-native version that uses a different one (e.g. RN0.69)

### ISSUE THREAD

**Issue by miallo** [getsentry/sentry-react-native#2557]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0-alpha.6

**`react-native` version:** 0.69.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N.a.

---
**I have following issue:**

A [hardcoded Folly-version](https://github.com/getsentry/sentry-react-native/blob/5053bd782aac751e3f4b858ba1188d0c37c71a86/RNSentry.podspec#L4) will mean that this has to be in sync with the one included by `react-native`. A similar issue is e.g. [here](https://github.com/facebook/react-native/issues/35009) where the solution is just to remove the hardcoded `folly_version` [here](https://github.com/dooboolab/react-native-iap/pull/2056/files)

**Steps to reproduce:**
In a `react-native@0.69.6`-project trying to run 
```sh
npm install @sentry/react-native@5.0.0-alpha.6
RCT_NEW_ARCH_ENABLED=1 pod install
```
**Actual result:**

It will throw the error:
```sh
[!] CocoaPods could not find compatible versions for pod "RCT-Folly":
  In snapshot (Podfile.lock):
    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)

  In Podfile:
    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)

    RNScreens (from `../node_modules/react-native-screens`) was resolved to 3.18.2, which depends on
      RCT-Folly

    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 5.0.0-alpha.6, which depends on
      RCT-Folly (= 2021.07.22.00)

    React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`) was resolved to 0.69.6, which depends on
      RCT-Folly (= 2021.06.28.00-v2)
```

**Expected result:**

Sentry should work with different react-native versions.

**Comment by marandaneto** [comment]
Please use the latest stable version v4 https://github.com/getsentry/sentry-react-native/releases/tag/4.6.1
For the Sentry RN SDK v5, because of the new architecture changes, we're supporting only RN >= 0.70

**Comment by miallo** [comment]
I totally get that, but the same issue would arise with future react-native versions that use a different Folly version, wouldn't it? So basically my question is: wouldn't other people run into the same issue in the future?
