### ISSUE TITLE
 Sentry.captureException(error) results in RNSentry.captureEnvelope red screeen

### ISSUE THREAD

**Issue by huszzsolt** [getsentry/sentry-react-native#2563]
**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)
4.6.1

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
Calling     Sentry.captureException(error); results in error

Also,
TypeScript definition (still) of captureException 
![Screenshot 2022-10-20 at 16 06 35](https://user-images.githubusercontent.com/28455856/196957552-9b44b21e-6b20-4f51-94e5-9890b57dcc58.png)

still has  captureContext which, is not documented anymore at 
https://docs.sentry.io/platforms/react-native/usage/

[Description]

**Steps to reproduce:**
- Initialise Sentry
- Call     Sentry.captureException(error); in react native debug mode

**Actual result:**

[Actual result]
![Screenshot 2022-10-20 at 16 08 21](https://user-images.githubusercontent.com/28455856/196957354-12bfc4ec-59c3-443f-8305-a12671ded3b4.png)

**Expected result:**
No red screen

[Expected result]

**Comment by krystofwoldrich** [comment]
The error on the screenshot is caused by the change of native implementations in [v4.4.0](https://github.com/getsentry/sentry-react-native/releases/tag/4.4.0). 

A clean build is needed so the native code gets rebuilt.
