### ISSUE TITLE
Render time not recording right duration

### ISSUE THREAD

**Issue by adityaputra11** [getsentry/sentry-react-native#2586]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ X  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.6.1

**`react-native` version:** 0.69.4

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [X]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link Issue]
[https://sentry.io/organizations/flipid/performance/flip-mobile:22e6dfc11af84ad296c5c4dd9c6053d2/?cursor=0%3A0%3A1&project=5663353&query=transaction.duration%3A%3C15m&statsPeriod=24h&transaction=domesticTransferBeneficiaryScene#span-a28f2df703ced6f5]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
 debug:true,
 release:release,
 traceSampleRate:1
 enableOutOfMemmoryTracking:false
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**
Currently i am using Sentry React Native SDK to tracking render time, but i found problem while set iddleTimeout into 60000ms or 60s, **render time is so long**. while i check into sentry SDK i found sentry record render time while lifecycle willunmount

[Description]

**Steps to reproduce:**
- Go to some Screen
- Iddle for while
- Go to Another Screen

**Actual result:**

[Actual result]
recorld very long time render
![Screenshot 2022-10-31 at 15 24 46](https://user-images.githubusercontent.com/24503826/198963987-64c282f2-6dbe-42ae-8f7e-01c4eac74235.png)

**Expected result:**

[Expected result]
represent real render time like using react profiler devtool

![Screenshot 2022-10-31 at 15 23 16](https://user-images.githubusercontent.com/24503826/198963740-1ce6b004-0780-49ee-922a-1263e985ff6b.png)

**Comment by marandaneto** [comment]
@adityaputra11 can you share your SDK code snippet including how you set up all the [instrumentation](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/)?

**Comment by adityaputra11** [comment]
sure 
```
const integrations = [
    new Sentry.ReactNativeTracing({
        // Pass instrumentation to be used as `routingInstrumentation`
        routingInstrumentation,
        tracingOrigins: ['localhost', /^\//, /^https:\/\//],
        enableAppStartTracking: false,
        idleTimeout: 60000,
        // ...
    }),
];
```

**Comment by marandaneto** [comment]
@adityaputra11 why are you setting `idleTimeout` to `60000`? if you remove this line, does it help?

**Comment by adityaputra11** [comment]
yes, but we need to extends transaction because we have some of custom span if we set to default our span will be canceled due timeout

**Comment by marandaneto** [comment]
> yes, but we need to extends transaction because we have some of custom span if we set to default our span will be canceled due timeout

I dont follow your problem here, can you provide a minimal reproducible example?

**Comment by adityaputra11** [comment]
yes, so while using automatic instrumentation we set our own span base on current transactions, we get current transactions from this function

```
 transaction = Sentry.getCurrentHub()?.getScope()?.getTransaction();
 ```
 then we create span to extend automatic instrumentation duration

 ```
  const span = transaction?.startChild({
        description: `${method} ${url}`,
        op: 'http.client',
    });
    ```
    when we not set idleTimeout, we found our custom span got cancelled, because transaction is already finished before span finish

**Comment by marandaneto** [comment]
@adityaputra11 can you provide a minimal reproducible example?
That means an empty app only with that and your basic configuration that demonstrates the problem? I can't reproduce this issue.

**Comment by adityaputra11** [comment]
sure @marandaneto , i will create new app using similar configuration

**Comment by adityaputra11** [comment]
hi @marandaneto we have already create app with almost same configuration we extend transaction we can see in this file
src/actions/transaction.ts

https://github.com/adityaputra11/SentryIssue

**Comment by krystofwoldrich** [comment]
@adityaputra11 Thank you for the example app. 

I've built it and run it, this is what the captured transaction looks like.

![Screenshot 2022-11-02 at 15 23 57](https://user-images.githubusercontent.com/31292499/199515050-fe0ae9b2-23ce-4388-acd7-894970cfffb1.png)

I don't see the long `ui.react.render` that you show in the issue description.

**Comment by adityaputra11** [comment]
@krystofwoldrich , thank you i have update my project

<img width="829" alt="Screenshot 2022-11-03 at 13 15 06" src="https://user-images.githubusercontent.com/24503826/199658048-ca5b3f44-a173-47e5-9fa2-e886a4e2ba32.png">

i got quite long render time, it happen when i stay in screen for a while

**Comment by adityaputra11** [comment]
is recomended to using timeout, than timestamp?

**Comment by adityaputra11** [comment]
i wanna asking other question but not related to this issu, is better using timeout or timestamp and why?

**Comment by krystofwoldrich** [comment]
@adityaputra11 I'm not sure what you mean, can you add examples of timeout vs timestamp?

**Comment by adityaputra11** [comment]
i mean this
```const fakeFetch = () => {
  /** This is only example that we have custom span to extend transaction sentry but the real case more complicated because we use action redux */
  const transaction = Sentry.getCurrentHub()?.getScope()?.getTransaction();
  const timeStamp = new Date().getTime() / 1000;
  const span = transaction?.startChild({
    description: 'Testing',
    op: 'fake-fetch',
    startTimestamp: timeStamp,
  });

  setTimeout(() => {
    span?.finish();
    console.log('Finish fake span');
  }, 10000);
};

vs 

const fakeFetch = () => {
  /** This is only example that we have custom span to extend transaction sentry but the real case more complicated because we use action redux */
  const transaction = Sentry.getCurrentHub()?.getScope()?.getTransaction();
  const timeStamp = new Date().getTime() / 1000;
  const span = transaction?.startChild({
    description: 'Testing',
    op: 'fake-fetch',
    startTimestamp: timeStamp,
    endTimeStamp:timeStamp+10
  });
  span.finish()
};
```

**Comment by krystofwoldrich** [comment]
@adityaputra11 Okay got it. I suggest the change because in your original code the `fake-fetch` start many seconds before the app even starts which would not happen with real fetch. That's all. One is not better than the other, it just makes the `fake-fetch` more real.

Could you describe in more detail how to replicate the issue with the example app, step by step, and the commands used to start the app? Or adjust the code, because as you can see [here](https://github.com/getsentry/sentry-react-native/issues/2586#issuecomment-1300540055) I'm getting different-looking transactions.

**Comment by adityaputra11** [comment]
yes @krystofwoldrich  i have already updated the source code, also this is what i am doing just wait a sec in screen then go back

![test_render](https://user-images.githubusercontent.com/24503826/199689395-7a2b210e-d4c7-4251-b9d0-f39e29971f0b.gif)


<img width="829" alt="Screenshot 2022-11-03 at 13 15 06" src="https://user-images.githubusercontent.com/24503826/199689807-f5dbcb4f-4c28-429a-b5d1-bf0cd3f4a294.png">

<img width="833" alt="Screenshot 2022-11-03 at 16 41 34" src="https://user-images.githubusercontent.com/24503826/199689741-1c52a686-93a3-4a88-bc2b-71dbdf9e1e87.png">

this is link event if you need it
[link](https://sentry.io/organizations/flipid/discover/flip-mobile:8f7397d409a2452387d1d6fd3cb92bb4/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=transaction.duration&homepage=true&name=All+Events&query=release%3Atesting-sentry&sort=-transaction.duration&statsPeriod=1h&yAxis=count%28%29)

**Comment by adityaputra11** [comment]
yes, ui.react.render is really confusing, people thought it was real render time than represent the time the component was on the screen

**Comment by krystofwoldrich** [comment]
@adityaputra11 Can we close this issue since the `ui.react.render` shows the on screen time?

**Comment by adityaputra11** [comment]
yes sure, i think so, just to make sure if this is screen time

**Comment by adityaputra11** [comment]
thanks

**Comment by marandaneto** [comment]
> @adityaputra11 Can we close this issue since the `ui.react.render` shows the on screen time?

Can we clarify this on the docs with a note or something?

**Comment by krystofwoldrich** [comment]
It's already part of [the documentation](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-profiler).
