### ISSUE TITLE
Add Documentation on how to remove Sentry from your project – React Native.

### ISSUE THREAD

**Issue by gtokman** [getsentry/sentry-react-native#2596]
Today I removed Sentry from our project because it didn't meet our use case. I removed the dependency from the project but it continued to fail to build because of a build phase script Sentry added to the iOS project.

After looking at the installation docs, I didn't see a section for uninstalling. I think this is an antipattern and it would be great if you can add a section for it.

The error I was receiving: 

```
Error: Cannot find module '@sentry/cli/package.json'
```

To fully uninstall: 

1. Unlink and remove the dependency and plugins/hooks
2. Delete the settings files in the Xcode and Android project
3. iOS – remove the sentry source map build phase and this section from the asset bundle build phase below it.
```
`node --print "require.resolve('@sentry/cli/package.json').slice(0, -13) + '/bin/sentry-cli'"` react-native xcode --force-foreground `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
```
4. Not 100% positive if there are additional Android project scripts to remove.

**Comment by krystofwoldrich** [comment]
Thank you for the comment. Before we update the docs, here are steps for both Android and iOS.

```bash
yarn remove @sentry/react-native
npx @sentry/wizard -i reactNative -p ios android --uninstall
cd ios && pod install
```

The wizard reverts the changes made in the build phases.

**Comment by herbertvuijk** [comment]
fyi the reason for deinstalling was the fact that all of a sudden it slowed the built process down with 30 minutes on xcode / IOS. It had to do with one of these:
/bin/sh -c "$WITH_ENVIRONMENT \"../node_modules/@sentry/cli/bin/sentry-cli react-native xcode $REACT_NATIVE_XCODE\""

/bin/sh -c "$WITH_ENVIRONMENT ../node_modules/@sentry/react-native/scripts/collect-modules.sh"


Shame, I was liking the product but all of a sudden unusable.

**Comment by rolfen** [comment]
> The wizard reverts the changes made in the build phases.

My experience is that it doesn't really. The build step scripts are still modified. I'm having to follow the manual installation documentation and make sure that they are manually reverted.

**Comment by bruno-garcia** [comment]
hey folks, I want to make sure your feedback isn't lost. could you please open a new ticket and reference this one and the relevant comments? closed issues are not monitored by our SLA tool
