### ISSUE TITLE
Sourcemaps not uploading automatically 

### ISSUE THREAD

**Issue by daniel-traindoo** [getsentry/sentry-react-native#2609]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 0.68.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://sentry.io/organizations/traindoo/issues/3719362572)

**Configuration:**

```
yarn sentry-wizard -i reactNative -p ios android
```

(XCode) Bundle React Native code and images:

```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode --log-level debug  ../node_modules/react-native/scripts/react-native-xcode.sh --force-foreground
```

---

Source maps are not being uploaded to sentry.io. The boundle map is correctly created in the DerivedData however they do not show up as artifacts in sentry. I found it also very odd that, even though I set the log level to debug, no sentry logs show up after the bundling process.

The error description is for ios however source maps auto upload is also not working with android.

I did not try this in a blank project however my steps were:

```
npm install @sentry/react-native

cd ios
pod install

yarn sentry-wizard -i reactNative -p ios android
```

Obviously adding Sentry.init in my app code however this should not effect the source maps right?

**Actual result:**

Debug symbols are uploaded however source maps are not uploaded

**Expected result:**

Debug symbols and source maps are uploaded to sentry.io

**Comment by krystofwoldrich** [comment]
Source maps are only uploaded when the release is built, are you creating a release build?

**Comment by daniel-traindoo** [comment]
Omg, sorry to bother you! Just wasted a day being completely confused.. I would suggest maybe mentioning this behaviour somewhere in the docs, or perhaps it is there and I just did not notice 😅  Either way, thanks a lot!!
