### ISSUE TITLE
xCode: Error in Bundle React Native code and images

### ISSUE THREAD

**Issue by atokuswanto** [getsentry/sentry-react-native#2611]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK version:** 3.4.3

**`react-native` version:** 0.59.10

**Are you using Expo?**
- [ ]  Yes
- [x]  No

---
**I have following issue:**
Command PhaseScriptExecution failed with a nonzero exit code

**Steps to reproduce:**
- I've upgraded @sentry/react-native from 3.2.13 to 3.4.3.
- I executed build for xCode (iOS project), it throws a build error in Bundle React Native code and images phase script.

**Actual result:**

```
Error: spawn /***/node_modules/@sentry/cli/sentry-cli ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /***/node_modules/@sentry/cli/sentry-cli',
  path: '/***/node_modules/@sentry/cli/sentry-cli',
  spawnargs: [
    'react-native',
    'xcode',
    '../node_modules/react-native/scripts/react-native-xcode.sh'
  ]
}
Command PhaseScriptExecution failed with a nonzero exit code
```

**Further Steps**
I noticed that sentry-cli binary is not in @sentry/cli/, it was in @sentry/cli/bin.
So I changed /***/node_modules/@sentry/cli/js/helper.js code to refer the binary inside bin directly.
Now, it does not throw build error, but it never complete this phase script, got stuck in there, no error prints etc.

**Comment by krystofwoldrich** [comment]
Hi,
could you send your `Bundle React Native code and images` bash script?

Can you upgrade to the latest SDK version [4.8.0](https://github.com/getsentry/sentry-react-native/releases/tag/4.8.0)?

**Comment by atokuswanto** [comment]
Hi, @krystofwoldrich , thanks for your kind reply. I used default script provided by Sentry.

```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by atokuswanto** [comment]
Is there any limit version of sentry-cli command for RN 0.59?

**Comment by atokuswanto** [comment]
@krystofwoldrich  I got reply from sentry-cli repository issues.
I should install sentry-cli binary manually, by running `run node scripts/install.js` directly in `node_modules/@sentry/cli` directory.
It seems sentry-cli binary is not installed automatically during npm install.

**Comment by atokuswanto** [comment]
https://github.com/getsentry/sentry-cli/issues/1393

**Comment by ghettosoak** [comment]
I'm seeing the same behaviour, RN 0.70.2, Sentry SDK 4.8.0. Mac, targeting iOS, no Expo. Here is my `Bundle React Native code and images` bash script:

```
#!/bin/sh
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

**Comment by atokuswanto** [comment]
@ghettosoak  as you can see on my comments, this is not the problem on sentry react-native.
First you need to check if sentry-cli binary has been installed correctly.

**Comment by marandaneto** [comment]
For RN >= 0.69 https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher

**Comment by krystofwoldrich** [comment]
Since the missing CLI binary was solved in the https://github.com/getsentry/sentry-cli/issues/1393 we can close this.

**Comment by samih-dev** [comment]
for anyone facing this this doc link can help if u are using some node version manager tool like NVM or others 
https://docs.sentry.io/clients/react-native/manual-setup/#using-node-with-nvm-or-notion

note that for me after adding this, I had to remove node_module file and install again
