### ISSUE TITLE
C++ Exception: N5folly4json11parse_errorE

### ISSUE THREAD

**Issue by Marzdor** [getsentry/sentry-react-native#2615]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.2.13

**`react-native` version:** 0.64.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: __DEV__
    ? devIngestUrl
    : prodIngestUrl,
  release: version,
  environment: __DEV__ ? 'develop' : 'production',
  tracesSampleRate: 0.2,
  debug: __DEV__,
});
```

---
**I have following issue:**

Since I have added Sentry to our React Native project I have been seeing issues pop up that only give this error 
`C++ Exception: N5folly4json11parse_errorE` 

looking more into it I have noticed it is only on iOS devices and it also seems that this is a part of the error `folly::detail::str_to_integral<long long>(folly::Range<char const*>*)`

that error lead me to this https://github.com/getsentry/sentry-react-native/issues/328

Like in that issue I am not sure what exactly is causing this nor am I sure that it is even a sentry issue 

**Steps to reproduce:**
I have not been able to reproduce it

**Comment by krystofwoldrich** [comment]
Hi, thank you for the information.

I'm not sure how can we help here since you can reproduce the error.

Have you tried updating to the latest version of  [`@sentry/react-native@4.8.0`](https://github.com/getsentry/sentry-react-native/releases/tag/4.8.0).

**Comment by Marzdor** [comment]
I have now updated to version `4.8.0` will see if I continue seeing the error

**Comment by krystofwoldrich** [comment]
@Marzdor Does it happen both in `release` and `dev` builds? Do you have some idea on how to reproduce it? Does it happen with newer versions of RN too?

**Comment by Marzdor** [comment]
> Does it happen both in release and dev builds? 

I have not seen it show up in dev builds but those are not used to the same extent that release builds are. 

> Do you have some idea on how to reproduce it?

Sadly, not yet.

> Does it happen with newer versions of RN too?

When updating the sentry package to 4.8 I also bumped the react native version to .64.4 since that one is still getting updates so in time I will see if that helped.

**Comment by krystofwoldrich** [comment]
Maybe we can close this since there is no way to reproduce it?

And we can reopen it in case of more information or the new version won't fix it.

**Comment by Marzdor** [comment]
That makes sense to me
