### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Sentry"

### ISSUE THREAD

**Issue by Splicer97** [getsentry/sentry-react-native#2631]
**OS:**
- [ ]  Windows
- [ 13.0 (22A380)]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 0.69.7

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- Step 1
- update "@sentry/react-native": "^4.7.1" to "@sentry/react-native": "^4.8.0"
- Step 2
cd ios && pod install
**Actual result:**
[!] CocoaPods could not find compatible versions for pod "Sentry":
  In snapshot (Podfile.lock):
    Sentry (= 7.28.0)

  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 4.8.0, which depends on
      Sentry (= 7.29.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Sentry` inside your development pod `RNSentry`.
   You should run `pod update Sentry` to apply changes you've made.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Actual result]

**Expected result:**
Correct install sentry pod
[Expected result]

**Comment by krystofwoldrich** [comment]
Just run `pod update Sentry`. SDK version `4.8.0` comes with the new `sentry-cocoa` version `7.29.0`.
