### ISSUE TITLE
iOS Hermes Sourcemaps incorrect

### ISSUE THREAD

**Issue by padge** [getsentry/sentry-react-native#2633]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```javascript
  Sentry.init({
    dsn: sentryDSN,
    tracesSampleRate: 1.0,
    environment: process.env.NODE_ENV,
    release: `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
    dist: `${DeviceInfo.getBuildNumber()}`,
  });
```

---
**I have following issue:**

When I upload sourcemaps to Sentry using Fastlane, the stacktraces aren't correct (see examples below). I can't figure out the correct way to generate the Hermes sourcemap files.

Before uploading the sourcemaps, I ran the `sentry_upload_dif` command pointing to the archive I just built, which uploads a few files (including one for hermes).
```ruby
sentry_upload_dif(
  auth_token: "...",
  org_slug: "myorg",
  project_slug: "myapp",
  path: "./ios/builds/archive-#{tag}.xcarchive"
)
```

Note that the `main.jsbundle` generated in the archive folder (see `archive_path` below) is **hermes bytecode**, and the `main.jsbundle.map` file looks like this:
```json
{"version":3,
"sources":["\/Users\/myuser\/Library\/Developer\/Xcode\/DerivedData\/myapp-asrapnbsmdusjqaiperuroykstdo\/Build\/Intermediates.noindex\/ArchiveIntermediates\/myapp\/BuildProductsPath\/Release-iphoneos\/main.jsbundle"],
"mappings":"AAAA,4BAA8B,MAAJ,KAAiD,MAAQ,KAAA,IAAzD,IAA0B,QAAoB,IAA9C,EAAD,QAAoE,MAAmB,KAAJ,GAAc,EAAf,UAAyC,MAAI,KAAY,KAAO,MAAP,GAAa,EAAd,MAAiB,KAAO,MAAc,KAAO,MAAI,MAAX,MAAD,MAoNrM,MAAA,OAAA,IAAiD,MAAA,GAAA,IAAyC,KAAA,MAAA,IAAgC,MAAzE,EAAgC,MAAjF,EAAoC,MAnNtC,OAmNC,KA4dC,MAAA,GAAA,IAAiD,MAAA,GAAA,IAAyC,KAAA,MAAA,IAAgC,MAAzE,EAAgC,MAAjF,EAAoC,MA3dtC,KA2dC,KAmEC,MAAA,GAAA,IAAiD,MAAA,GAAA,IAAyC,KAAA,GAAA,IAAgC,MAAzE,EAAgC,MAAjF,EAAoC,MAlEtC,KAkEC,KA2CC,MAAA,GAAA,IAAiD,MAAA,GAAA,IAAyC,KAAA,GAAA,IAAgC,MAAhC,EAAT,MAAhC,EAAb,MA1CtC,KA0CC,KACF,MAAI,OAQA,QARD,OASH,MAAI,QAQA,IARD,OASH,MAAI,QAiCA,QAjCD,OAkCH,MAAI,QAQA,IARD,OASH,MAA...
```

Here's what my `sentry_upload_sourcemap` call looks like:
```ruby
archive_path = "./ios/builds/archive-#{tag}.xcarchive/Products/Applications/MyApp.app"
sentry_upload_sourcemap({
  auth_token: "...",
  org_slug: "myorg",
  project_slug: "myproject",
  app_identifier: "myapp",
  version: "#{version}+#{build_number}",
  dist: build_number,
  rewrite: true,
  sourcemap: [
    "#{archive_path}/#{bundle_name}.map",
    "#{archive_path}/#{bundle_name}"
  ],
})
```
### TRACE 1a
Using the these sourcemaps from the archive folder is the most correct out of all the methods I've tried, but it's still showing JS (not TS), the line numbers are wrong, and paths are wrong. Here's the raw trace:
```
Error: Whoops
  at <unknown>(/Users/myuser/Library/Developer/Xcode/DerivedData/myapp-asrapnbsmdusjqaiperuroykstdo/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle:264810:22)
  at <unknown>(/Users/myuser/Library/Developer/Xcode/DerivedData/myapp-asrapnbsmdusjqaiperuroykstdo/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle:28326:53)
  at <unknown>(/Users/myuser/Library/Developer/Xcode/DerivedData/myapp-asrapnbsmdusjqaiperuroykstdo/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/main.jsbundle:28271:45)
  ...
```

### TRACE 1b
If I add the `sentry_upload_sourcemap` param `strip_prefix`, with the value set to `"/Users/myuser/Library/Developer/Xcode/DerivedData/myapp-asrapnbsmdusjqaiperuroykstdo/Build/Intermediates.noindex/ArchiveIntermediates/myapp/BuildProductsPath/Release-iphoneos/"` I get the following (incorrect) raw trace:
```
Error: Whoops
  at <unknown>(main.jsbundle:264807:22)
  at <unknown>(main.jsbundle:28326:53)
  at <unknown>(main.jsbundle:28271:45)
  at <unknown>(main.jsbundle:28117:34)
  at apply(native)
  ...
```

### TRACE 2
I also tried modifying the `Bundle React Native code and images` method in XCode to set `export SOURCEMAP_FILE="$(pwd)/../main.jsbundle.map";` and upload that to sentry instead and that didn't work either (deployed a fresh build to avoid caching). This gave me the following stacktrace:
```
Error: Whoops
  at <unknown>(main:1:1)
  at <unknown>(main:1:1)
  ...
```

### TRACE 3
I also tried "Step 1" in the [manual-setup hermes guide](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/#compile-sourcemaps) and that didn't work either. I'm not sure how this is intended to work, since the generated `main.jsbundle` isn't hermes bytecode? Here's the raw (incorrect) stack I get from this method:
```
Error: Whoops
  at <unknown>(node_modules/metro-runtime/src/polyfills/require.js:11:1)
  at <unknown>(node_modules/metro-runtime/src/polyfills/require.js:11:1)
  at <unknown>(node_modules/metro-runtime/src/polyfills/require.js:11:1)
  at <unknown>(node_modules/metro-runtime/src/polyfills/require.js:11:1)
  at apply(native)
  ...
```
I see in the docs it says:
> Currently, there is an issue when bundling the hermes bundle and source maps manually. We recommend not bundling these manually until this is fixed.

I'm not sure I need "custom" sourcemaps - so how should I be doing it in that case? I thought my **Trace 1a** example would be a non-custom method?

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the detailed description. We are looking into this and we will keep you updated.

**Comment by krystofwoldrich** [comment]
It seems like there are some changes in `@react-native-community/cli-hermes@9.3.0` that break the source maps. Could you try to add `@react-native-community/cli-hermes@9.2.1` to your project and try the source maps again? I've tested it with our sample app.

```bash
yarn add @react-native-community/cli-hermes@9.2.1
```

**Comment by krystofwoldrich** [comment]
Could you try to do a similar thing to `TRACE 2` but with the following instead:

```bash
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
```

**Comment by padge** [comment]
That worked! Thanks for the help!

I initially tried with `$DERIVED_FILE_DIR` but I couldn't locate the output map file, so I changed it to use `pwd` and I was able to find it in my root folder to upload w/ fastlane:
```shell
export EXTRA_PACKAGER_ARGS="--sourcemap-output $(pwd)/../main.jsbundle.map"
```
