### ISSUE TITLE
Archive failing with space in scheme-name and collect-modules.sh

### ISSUE THREAD

**Issue by rafaelmaeuer** [getsentry/sentry-react-native#2654]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0-alpha.9

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [x]  Yes (bare workflow)
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
	debug: false,
	dsn: Config.SENTRY_DSN,
	sampleRate: isDev ? 0.0 : 1.0,
	environment: isDev ? 'development' : 'production',
})
```

---
**I have following issue:**

With update of @sentry/react-native to `v5.0.0-alpha.9` which has latest changes from `4.10.0`, modification of `Bundle React Native code and images build phase` script is required, so I applied changes from [Migration - From 4.8.x to 4.9.x](https://docs.sentry.io/platforms/react-native/migration/#from-48x-to-49x). App-Archive is now failing when having spaces in the scheme-name: e.g. `app-name (release)`. Archive completes when using `app-name-release` as scheme-name instead.

```
Error: ENOENT: no such file or directory, open '/Users/<username>/Library/Developer/Xcode/DerivedData/<app-name-cryptic-build-id>/Build/Intermediates.noindex/ArchiveIntermediates/<app-name>'
at Object.openSync (node:fs:595:3)
    at Object.readFileSync (node:fs:463:35)
    at Object.<anonymous> (/Users/<username>/Development/<project>/<app-name>/app/node_modules/@sentry/react-native/dist/js/tools/collectModules.js:20:29)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/<username>/Library/Developer/Xcode/DerivedData/<app-name-cryptic-build-id>/Build/Intermediates.noindex/ArchiveIntermediates/<app-name>'
```

**Steps to reproduce:**
- Create new project with RN 0.70.6 and Expo 47.0.8 in bare workflow
- Add `use_frameworks! :linkage => :static` in Podfile (required for RNFB)
- Add @sentry/react-native v5.0.0-alpha.9
- Name app-target: `app-name (release)`
- Press Product -> Archive

**Actual result:**

Archive fails

**Expected result:**

Archive completes

**Comment by krystofwoldrich** [comment]
Thank you for the message, we will look into it.

**Comment by krystofwoldrich** [comment]
[The fix is on its way](https://github.com/getsentry/sentry-react-native/pull/2655), just note that the modules collection feature depends on generated source maps and if your source maps are not in the default path `$DERIVED_FILE_DIR/main.jsbundle.map`. You need to export `$SOURCE_MAP_PATH` with the correct path to your source maps.

**Comment by marandaneto** [comment]
@krystofwoldrich 

> You need to export $SOURCE_MAP_PATH with the correct path to your source maps.

Should this be part of our https://docs.sentry.io/platforms/react-native/troubleshooting/ page? or is the fix enough?

**Comment by krystofwoldrich** [comment]
@marandaneto Yes, good idea, I will add it there. We use the same path where RN saves the source maps, but if someone changes the path, the modules would not be collected.
