### ISSUE TITLE
Cannot add task `bundleFooBarJsAndAssets_SentryCollectModulesCleanUp`

### ISSUE THREAD

**Issue by fabiendem** [getsentry/sentry-react-native#2656]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.10.0

**`react-native` version:** 0.66.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Irrelevant

**Configuration:**

Irrelevant

---
**I have following issue:**

Since we updated to 4.10.0 with the modules support (https://github.com/getsentry/sentry-react-native/releases/tag/4.10.0), the Android build on the CI is failing.

**Steps to reproduce:**
- Try to setup the gradle tasks (do a build for example)

**Actual result:**

We're getting the following error message: `Cannot add task 'bundleAlphaReleaseJsAndAssets_SentryCollectModulesCleanUp' as a task with that name already exists.`

```
FAILURE: Build failed with an exception.
* Where:
Script '/Users/vagrant/git/node_modules/@sentry/react-native/sentry.gradle' line: 198
* What went wrong:
Cannot add task 'bundleAlphaReleaseJsAndAssets_SentryCollectModulesCleanUp' as a task with that name already exists.
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'bundleAlphaReleaseJsAndAssets_SentryCollectModulesCleanUp' as a task with that name already exists.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:261)
....
```

**Expected result:**

No error when Gradle is being setup

Since it's related to `SentryCollectModulesCleanUp`, it's probably due to this change: https://github.com/getsentry/sentry-react-native/compare/4.9.0...4.10.0

**Comment by marandaneto** [comment]
@krystofwoldrich we'd need this check for the new task
https://github.com/getsentry/sentry-react-native/blob/bb4d70c6dc942f17105a529a81a74ea44cbd3023/sentry.gradle#LL89C4-L89C4

**Comment by fabiendem** [comment]
Thank you folks 🙌
