### ISSUE TITLE
Build error with AGP 7.4.0-RC01 / Android Studio Electric Eel RC01

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#2659]
**OS:**
- [x]  MacOS

**Platform:**
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 4.2.0

**`react-native` version:** 0.69

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

---
**I have following issue:**

Build Problem when using Android Studio Electric Eel with AGP 7.4.0-rc01.
It worked with up to beta05

**Steps to reproduce:**
classpath("com.android.tools.build:gradle:7.4.0-beta05") // works
classpath("com.android.tools.build:gradle:7.4.0-rc01") // throws gradle error

- Step 2

**Actual result:**

FAILURE: Build failed with an exception.

* What went wrong:
A build operation failed.
    Querying the mapped value of provider(java.util.Set) before task ':app:generateSentryProguardUuidIntegrationRelease' has completed is not supported
Querying the mapped value of provider(java.util.Set) before task ':app:generateSentryProguardUuidIntegrationRelease' has completed is not supported

**Expected result:**

[Expected result]
Build successful

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message.

Could you send a sample project, so we can reproduce the issue?

**Comment by marandaneto** [comment]
@pvegh are you using the [Gradle plugin](https://docs.sentry.io/platforms/android/gradle/)?
If so, the problem would live [here](https://github.com/getsentry/sentry-android-gradle-plugin).

**Comment by pvegh** [comment]
Thanks I think that was the hint I was looking for! Will update here as soon as I know more.

> @pvegh are you using the [Gradle plugin](https://docs.sentry.io/platforms/android/gradle/)? If so, the problem would live [here](https://github.com/getsentry/sentry-android-gradle-plugin).

**Comment by pvegh** [comment]
Yep it's the plugin. Thanks again!
