### ISSUE TITLE
Profiling for RN

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2668]
This issue tracks all related tasks to Sentry React Native Profiling support.

```[tasklist]
### In Development
- [ ] https://github.com/getsentry/sentry-react-native/pull/3349
- [ ] https://github.com/getsentry/sentry-react-native/pull/3397
- [ ] https://github.com/getsentry/relay/pull/2706
- [ ] https://github.com/getsentry/sentry/issues/59989
- [ ] https://github.com/getsentry/sentry/pull/58771
- [ ] https://github.com/getsentry/relay/pull/2685
- [ ] https://github.com/getsentry/sentry-react-native/issues/3641
``` 

```[tasklist] 
### Alpha since https://github.com/getsentry/sentry-react-native/releases/tag/5.8.0
- [x] Mark as alpha
- [x] Release SDK with code snippet in the changelog
- [ ] https://github.com/getsentry/sentry-docs/pull/7228
```

```[tasklist]
### In Progress
- [ ] https://github.com/getsentry/sentry-react-native/pull/3057
- [ ] https://github.com/getsentry/sentry-javascript/pull/8270
- [ ] https://github.com/getsentry/sentry-react-native/pull/3141
```

```[tasklist]
### Planned
- [ ] https://github.com/getsentry/sentry-react-native/issues/3337
- [x] Investigate HBC Bundle Profile symbolication with and without debug info
```

[Private Notion page link.](https://www.notion.so/sentry/RN-Profiling-5c5e43b91e8145ae9393fdcbaedd3771)

---

This issue serves to gather interest and comments regarding Profiling for RN. 

More about the Profiling product [here](https://docs.sentry.io/product/profiling/).

Android and iOS support profiling therefore RN native could offer an option to turn it on in the native layers.

Thumbs up if you are interested.

**Comment by marandaneto** [comment]
Right now that would be possible if you [init](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) the SDK manually.

Enable Performance and Profiling directly on the Native SDKs, for example, Android.
https://docs.sentry.io/platforms/android/performance/
https://docs.sentry.io/platforms/android/profiling/

The same steps for iOS, would work for Android and iOS native code only, not in the JS bits nor C bits for Android.

**Comment by krystofwoldrich** [comment]
Linking opened Profiling discussion.

- https://github.com/getsentry/sentry-react-native/discussions/3009

**Comment by krystofwoldrich** [comment]
For everyone interested in updates on the RN Profiling please see [the new post in the discussion](https://github.com/getsentry/sentry-react-native/discussions/3009#discussioncomment-5998870).

https://github.com/getsentry/sentry-react-native/discussions/3009#discussioncomment-5998870

**Comment by marandaneto** [comment]
@krystofwoldrich is there a draft PR we can look at? no need to be finished or polished, the earlier a draft PR is out, the earlier you get feedback :)

**Comment by krystofwoldrich** [comment]
Yes, there is.

- https://github.com/getsentry/sentry-react-native/pull/3057

**Comment by krystofwoldrich** [comment]
Experimental support released in https://github.com/getsentry/sentry-react-native/releases/tag/5.8.0
