### ISSUE TITLE
instrument.js throws warnings with React Native 0.70+

### ISSUE THREAD

**Issue by alexborton** [getsentry/sentry-react-native#2676]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0-alpha.10

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
export const routingInstrumentation = new Sentry.ReactNavigationInstrumentation(
  { routeChangeTimeoutMs: 6000 }
)

Sentry.init({
  dsn: Config.SENTRY_DSN_KEY,
  integrations: [
    new Sentry.BrowserIntegrations.Breadcrumbs({
      dom: false,
    }),
    new Sentry.ReactNativeTracing({
      tracingOrigins: [
        'localhost',
        /^(?!.*(---.com\/validate|ipv4\.--\.com|---\.eu-west-2|firehose\.eu-west-2)).*$/,
      ],
      routingInstrumentation,
    }),
  ],
  maxTransactionDuration: 6000,
  tracesSampleRate: isProd ? 0.2 : 1.0,
  environment: isProd ? 'production' : 'development',
  normalizeDepth: isProd ? 1 : 11,
  autoSessionTracking: true,
  sessionTrackingIntervalMillis: 180000,
  attachStacktrace: true,
})

Sentry.addGlobalEventProcessor((event) => {
  return event.type === 'transaction' && event.transaction === 'Route Change'
    ? false
    : event
})
```

---
**I have following issue:**

Getting warnings thrown from sentry through the app, intermittently from both iOS and Android pointing to the same line in `instrument.js` 

![Simulator Screen Shot - iPhone 14 - 2022-12-06 at 14 38 14](https://user-images.githubusercontent.com/1439507/205942867-3ec6a322-ff05-4483-af05-8541ada75b83.png)
![Screenshot_1670337348](https://user-images.githubusercontent.com/1439507/205942880-d28c7c9b-ef9e-49d8-9644-6543e98c87f6.png)

**Comment by krystofwoldrich** [comment]
Hi, thanks for the info.

This is caused by the `Sentry.BrowserIntegrations.Breadcrumbs` integration. Why do you use it in React Native?

**Comment by krystofwoldrich** [comment]
@alexborton Any updates?

**Comment by krystofwoldrich** [comment]
@alexborton No worries, thanks for the info. Just let us know if there is something missing after removing it (if you figure out why it was added originally).
