### ISSUE TITLE
Performance monitoring (Custom Instrumentation) logs are not sent on Android

### ISSUE THREAD

**Issue by takahi5** [getsentry/sentry-react-native#2682]
**OS:**

- [ ] Windows
- [x] MacOS
- [ ] Linux

**Platform:**

- [ ] iOS
- [x] Android

**SDK:**

- [x] `@sentry/react-native` (>= 1.0.0)
- [ ] `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.11.0

**`react-native` version:** 0.70.6

**Are you using Expo?**

- [ ] Yes
- [x] No

**Are you using sentry.io or on-premise?**

- [x] sentry.io (SaaS)
- [ ] on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)

```js
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  tracesSampleRate: 1.0, // send transaction always
});
```

---

**I have following issue:**

Performance monitoring (Custom Instrumentation) logs are not sent on Android

**Steps to reproduce:**

- Step 1
  - Create new React Native project with `npx react-native init SampleApp`
- Step 2
  - Setup sentry according to the [document](https://docs.sentry.io/platforms/react-native/)
    - `yarn add @sentry/react-native`
    - `npx @sentry/wizard -i reactNative -p ios android`
- Step 3
  - Setup Performance Monitoring according to the [document](https://docs.sentry.io/platforms/react-native/performance/)

```jsx
import * as Sentry from "@sentry/react-native";

Sentry.init({
  dsn: "https://...",
  tracesSampleRate: 1.0
});

const App: () => Node = () => {
  useEffect(() => {
    const transaction = Sentry.startTransaction({name: 'test-transaction'});
    const span = transaction.startChild({op: 'functionX'});
    // functionCallX
    span.finish();
    transaction.finish();
  }, []);
	...
}
```

- Step 4
  - Check Performance Monitoring at Sentry.io

**Actual result:**

- ❌ When I run [Custom Instrumentation](https://docs.sentry.io/platforms/react-native/performance/instrumentation/custom-instrumentation/) on Android, I cannot see any logs on sentry.io. 
  
- ✅ No problem with [Automatic Instrumentation](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/). 
- ✅ No problem with iOS. 
- ✅ No problem with sentry-react-native v3.4.3. Seems to be a problem with v4 and above. 

<table>
<tr>
  <th>sentry-react-native</th>
  <th>Instrumentation</th>
  <th>iOS</th>
  <th>Android</th>
</tr>
<tr>
  <td rowspan="2">v4.11.0</td>
  <td>Automatic Instrumentation</td>
  <td>✅</td>
  <td>✅</td>
</tr>
<tr>
  <td>Custom Instrumentation</td>
  <td>✅</td>
  <td>❌</td>
</tr>
<tr>
  <td rowspan="2">v3.4.3</td>
  <td>Automatic Instrumentation</td>
  <td>✅</td>
  <td>✅</td>
</tr>
<tr>
  <td>Custom Instrumentation</td>
  <td>✅</td>
  <td>✅</td>
</tr>
</table>

**Expected result:**

Custom Instrumentation performance logs to be sent by Android.

**Comment by marandaneto** [comment]
@takahi5 can you enable `debug: true` in the SDK `init` and check the logs?

**Comment by takahi5** [comment]
@marandaneto Thank you for your support.

Here is the log with `debug: true`.

```
LOG  Sentry Logger [log]: Integration installed: ModulesLoader
 LOG  Sentry Logger [log]: Unhandled promise rejections will be caught by Sentry.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [log]: Integration installed: Release
 LOG  Sentry Logger [log]: Integration installed: InboundFilters
 LOG  Sentry Logger [log]: Integration installed: FunctionToString
 LOG  Sentry Logger [log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [log]: Integration installed: LinkedErrors
 LOG  Sentry Logger [log]: Integration installed: Dedupe
 LOG  Sentry Logger [log]: Integration installed: HttpContext
 LOG  Sentry Logger [log]: Integration installed: EventOrigin
 LOG  Sentry Logger [log]: Integration installed: SdkInfo
 LOG  Sentry Logger [log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [log]: Integration installed: RewriteFrames
 LOG  Sentry Logger [log]: Integration installed: DeviceContext
 LOG  Sentry Logger [log]: [ReactNativeTracing] Native frames instrumentation initialized.
 LOG  Sentry Logger [log]: [ReactNativeTracing] Not instrumenting route changes as routingInstrumentation has not been set.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeTracing
 LOG  Running "SampleApp70" with {"rootTag":11}
 LOG  >>>> startTransaction
 LOG  Sentry Logger [log]: [Tracing] starting undefined transaction - test-transaction
 LOG  Sentry Logger [log]: [Tracing] Starting 'functionX' span on transaction 'test-transaction' (915cd4c61e877e23).
 LOG  Sentry Logger [log]: [Tracing] Finishing 'functionX' span on transaction 'test-transaction' (915cd4c61e877e23).
 LOG  >>>> finishTransaction
 LOG  Sentry Logger [log]: [Measurements] Adding measurements to transaction {
  "stall_count": {
    "value": 0,
    "unit": "none"
  },
  "stall_total_time": {
    "value": 0,
    "unit": "millisecond"
  },
  "stall_longest_time": {
    "value": 0,
    "unit": "millisecond"
  }
}
 LOG  Sentry Logger [log]: [Tracing] Finishing undefined transaction: test-transaction.
 LOG  Sentry Logger [log]: [NativeFrames] Native frames timed out for undefined transaction test-transaction. Not adding native frames measurements.
```

I ran the following code of measurement.
```jsx
  useEffect(() => {
    console.log('>>>> startTransaction');
    const transaction = Sentry.startTransaction({name: 'test-transaction'});
    const span = transaction.startChild({op: 'functionX'}); // This function returns a Span
    // functionCallX
    span.finish(); // Remember that only finished spans will be sent with the transaction
    console.log('>>>> finishTransaction');
    transaction.finish(); // Finishing the transaction will send it to Sentry
  }, []);
```

**Comment by krystofwoldrich** [comment]
@takahi5 The logs look good. Seems like the SDK is sending the data.

Do you maybe have [dynamic sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/) enabled in the Sentry UI?

**Comment by takahi5** [comment]
@krystofwoldrich @marandaneto 
Thank you for the support!
Transaction appeared in Sentry by adding `op`. :tada:

**Comment by ilkanozen** [comment]
https://github.com/getsentry/sentry-react-native/issues/948
Its helped to me
