### ISSUE TITLE
Uploaded Android bundle is 0MB and event processing keeps failing due to it

### ISSUE THREAD

**Issue by StampixSMO** [getsentry/sentry-react-native#2683]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.10.1

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/stampix-zb/issues/3496972388/?project=6259211&query=is%3Aunresolved+os.name%3AAndroid&referrer=issue-stream&statsPeriod=14d

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
  // We recommend adjusting this value in production.
  tracesSampleRate: SENTRY_TRACING_RATE,
  enableNdkScopeSync: true,
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation
      // ...
    })
  ],
  environment: SENTRY_ENVIRONMENT,
  // Any data beyond this depth will be trimmed and marked using its type instead ([Object] or [Array]).
  normalizeDepth: 10,
  beforeBreadcrumb: (breadcrumb, hint) => {
    // We log some more information for XHR requests to our GQL API, since only the method and URL is useless for debugging
    if (breadcrumb.category === 'xhr' && hint) {
      try {
        const { query, variables } = JSON.parse(hint.input);
        if (!breadcrumb.data) breadcrumb.data = {};
        breadcrumb.data.query = query;
        breadcrumb.data.variables = variables;
      } catch {}
    }
    return breadcrumb;
  },
  maxValueLength: 500,
  // Don't auto initialize, instead we do it manually
  // See https://docs.sentry.io/platforms/react-native/manual-setup/native-init/
  autoInitializeNativeSdk: false
});
```
Note that we've just now disabled auto initialization, the issue at hand was present before we did disabled this.

---
**I have following issue:**

Every new release suddenly started having empty Android bundles, giving us the `Invalid location in sourcemap` errors at the top of Android-reported events.
Using the Sentry CLI to debug the particular events reveals the same and the sourcemap uploads in the project Settings also clearly shows it's empty (see screenshot).
![image](https://user-images.githubusercontent.com/79153163/206408580-97496895-68f4-4f9b-a818-10b634a64bd9.png)

Note that this used to work in the past, but it's hard to debug where it started occurring since the older events are long removed due to retention periods.

For iOS, this works perfectly and all is well.

**Steps to reproduce:**
Just make a release bundle, which automatically uploads the bundle to our Sentry environment.

**Actual result:**

Minified stack traces in our events and an error banner on top.

**Expected result:**

Proper reported events with stack traces

**Comment by marandaneto** [comment]
@StampixSMO RN 0.70.6 has Hermes enabled by default, not sure if you had before.
https://docs.sentry.io/platforms/react-native/manual-setup/hermes/
Also, take a look at this https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher
Besides upgrading the SDK to the latest version, let us know if that helps.

**Comment by StampixSMO** [comment]
Hi @marandaneto Thanks for the reply, appreciated!

We've had Hermes quite a while already, so don't think that's the issue here. Additionally, we've got the latest SDK version (see above) in the issue description.
The issue is also that the bundle is 0MB, the source maps seem to be fine and are uploaded correctly as far as I can tell, see the screenshot above.

For the `react-native.config.js` adjustments, we have this patch file so that should all be good already
```
diff --git a/node_modules/@sentry/react-native/react-native.config.js b/node_modules/@sentry/react-native/react-native.config.js
index f85fa01..19782b1 100644
--- a/node_modules/@sentry/react-native/react-native.config.js
+++ b/node_modules/@sentry/react-native/react-native.config.js
@@ -1,18 +1,10 @@
 module.exports = {
   dependency: {
     platforms: {
-      ios: {
-        sharedLibraries: ['libz']
-      },
+      ios: {},
       android: {
         packageInstance: 'new RNSentryPackage()'
       }
-    },
-    hooks: {
-      postlink:
-        'node node_modules/@sentry/wizard/dist/bin.js -i reactNative -p ios android',
-      postunlink:
-        'node node_modules/@sentry/wizard/dist/bin.js -i reactNative -p ios android --uninstall'
     }
   }
 };

```

Any further suggestions we can try?

**Comment by marandaneto** [comment]
@StampixSMO being 0 bytes is fine I don't remember if for Hermes or RAM bundles, have to check it.
@krystofwoldrich will further investigate.

**Comment by krystofwoldrich** [comment]
Hi @StampixSMO,
could you send us an example app with instructions on how to build it so we can reproduce the issue?

Are you using managed or bare workflow?

**Comment by StampixSMO** [comment]
> Hi @StampixSMO, could you send us an example app with instructions on how to build it so we can reproduce the issue?

Publicly I cannot easily share an example app without reproducing our entire app including fastlane CI etc .. Is there an option to privately share this?

Using bare workflow btw

**Comment by krystofwoldrich** [comment]
@StampixSMO Would you be able to recreate the issue with a clean project, just setting up the minimum needed, maybe the issue show even without Fastlane?

**Comment by marandaneto** [comment]
A `minimal reprocible exampe` would do, that means.

```
npx react-native init Name
yarn add @sentry/react-native
npx @sentry/wizard -i reactNative -p ios android
```

Steps to reproduce...

**Comment by StampixSMO** [comment]
Hey @krystofwoldrich I've set up a new project and new project, build the app in release mode and the bundle is again 0MB.
However, the issues on that project do not contain errors.

So to me, it's weird that the main bundle is 0MB, because I thought that was the reason we keep getting "Invalid location in sourcemap" on ALL our Android events in our main app.

We've tried the CLI debugging a few times already, but the only clue I could find is the empty bundle file.

The output of the CLI is always the same:
```
✔ Fetched data for event: 8bddc902c6f6456ab57efbf86feb1189
✔ Event has release name: com.stampix.stampix@3.74.5+3038
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Event exception stacktrace selected frame (0) has incorrect abs_path (valid url is required). Found native
```

Indeed, the issue event mentions `native://` but no idea why that is. Any further suggestions to try?

**Comment by krystofwoldrich** [comment]
@StampixSMO Sadly I don't know what to do at this moment. The only suggestion I have is to compare the newly created project to the original one and try to find the differences in settings, RN version, etc.

**Comment by StampixSMO** [comment]
@krystofwoldrich Is it normal that the bundle is 0MB?

**Comment by dyoste** [comment]
@StampixSMO It's fine if `index.android.bundle` is 0MB, the problem that I'm facing and you may be as well, is that `index.android.bundle.map` is no longer being generated.

**Comment by marandaneto** [comment]
> @krystofwoldrich Is it normal that the bundle is 0MB?

Yes, as mentioned here https://github.com/getsentry/sentry-react-native/issues/2683#issuecomment-1344063151
Its for Hermes apparently, @krystofwoldrich please add a note to https://docs.sentry.io/platforms/react-native/manual-setup/hermes/ that being 0 bytes on Android is fine.

About the issue, @StampixSMO please take a look into @krystofwoldrich questions https://github.com/getsentry/sentry-react-native/issues/2683#issuecomment-1354731167

**Comment by krystofwoldrich** [comment]
@StampixSMO Any updates?

**Comment by StampixSMO** [comment]
@krystofwoldrich No, I've been out and haven't been able to look into the diff. On my TODOs!

**Comment by krystofwoldrich** [comment]
I will close this for now. But please comment down below when you get back to it and we can reopen it and investigate more.
