### ISSUE TITLE
beforeSend is missing hint.originalException

### ISSUE THREAD

**Issue by rogueg** [getsentry/sentry-react-native#2696]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.11.0

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**
[The docs](https://docs.sentry.io/platforms/react-native/configuration/filtering/#event-hints) say the hint argument to beforeSend should contain the `originalException` that was thrown. That doesn't seem to be the case.

Looking at the code, [this line](https://github.com/getsentry/sentry-react-native/blob/6f7366d758b3ed3b8d7f59817828e072c95de927/src/js/integrations/reactnativeerrorhandlers.ts#L217) appears to be missing a hint argument. If I patch it to add one, things work as expected!

In case you're curious, I want the original exception so I can send along the `componentStack` from React to aid in debugging.

**Steps to reproduce:**
- Without an error boundary, throw an error while rendering a component.
- Log the arguments to beforeSend

**Actual result:**
null

**Expected result:**
an error (with `.componentStack`)

**Comment by krystofwoldrich** [comment]
Thank you. We will fix it.

**Comment by ryan-gray-db** [comment]
Just noting this is also happening in @sentry/node. Thanks for taking a look!

**Comment by krystofwoldrich** [comment]
Thank you @ryan-gray-db for the info. Could you open issue in the https://github.com/getsentry/sentry-javascript about the node.
