### ISSUE TITLE
error: Found argument 'index.tsx' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by duttasuraj93** [getsentry/sentry-react-native#2701]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.12.0

**`react-native` version:** 0.66.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

After installing sentry and run the below commands the app cannot build for iOS. It works fine on android though.
in `project.pbxproj` file i have

Bundle React Native code and images:
```
shellScript = "export SENTRY_PROPERTIES=sentry.properties\nexport EXTRA_PACKAGER_ARGS=\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\"\nset -e\n\nexport NODE_BINARY=node\n../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh index.tsx\n\n/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh\n";
```
Upload Debug Symbols to Sentry:
```
export SENTRY_PROPERTIES=sentry.properties\n../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

**Steps to reproduce:**
- `yarn add @sentry/react-native`
- `yarn sentry-wizard -i reactNative -p ios android`
- `cd ios && pod install`
- Build the app using Xcode

**Actual result:**

```
error: Found argument 'index.tsx' which wasn't expected, or isn't valid in this context

USAGE:
    sentry-cli react-native xcode [OPTIONS] [BUILD_SCRIPT] [-- <ARGS>...]

For more information try --help
```

**Expected result:**

Should be able to build successfully.

**Comment by krystofwoldrich** [comment]
Hi, you had an extra `index.tsx` after the original `react-native-xcode.sh` command. 

Can you remove it? After that, the app should build correctly.

**Comment by duttasuraj93** [comment]
will give it a try when i get to work on monday

**Comment by duttasuraj93** [comment]
> Hi, you had an extra `index.tsx` after the original `react-native-xcode.sh` command.
> 
> Can you remove it? After that, the app should build correctly.

unfortunately this does not work. it gives another error

```
warning: the transform cache was reset.
error The resource `/Users/username/Dev/myproject/index.js` was not found.
Error: The resource `/Users/username/Dev/myproject/index.js` was not found.
    at /Users/username/Dev/myproject/node_modules/metro/src/IncrementalBundler.js:289:24
    at gotStat (node:fs:2689:21)
    at FSReqCallback.oncomplete (node:fs:206:21)
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code
```

i tried resetting cache, clean build and build again, but shows the above error

**Comment by krystofwoldrich** [comment]
Okay, I see,
can you try to pass the `index.tsx` like this `../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh -- index.tsx`

The script
```
shellScript = "export SENTRY_PROPERTIES=sentry.properties\nexport EXTRA_PACKAGER_ARGS=\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\"\nset -e\n\nexport NODE_BINARY=node\n../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh -- index.tsx\n\n/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh\n";
```

**Comment by duttasuraj93** [comment]
> 

This does not work either, but fortunately i found a solution.
Remove the `index.tsx` from the original script in the question as mentioned by @krystofwoldrich  and add `export ENTRY_FILE=index.tsx` to the script. That solves the issue.

So, here is how the script would look like
```
shellScript = "export SENTRY_PROPERTIES=sentry.properties\nexport EXTRA_PACKAGER_ARGS=\"--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map\"\nset -e\n\nexport ENTRY_FILE=index.tsx\nexport NODE_BINARY=node\n../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh \n\n/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh\n";
```

Another solution that i found, but **NOT** recommended is, changing the file
`node_modules/react-native/scripts/react-native-xcode.sh:74`
replace `ENTRY_FILE=${1:-index.js}` with `ENTRY_FILE=${1:-index.tsx}`

Hope this resolves the issue if anyone else if facing it
