### ISSUE TITLE
Android build fails in a monorepo due to wrong path for `tools/collectModules.js`

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-react-native#2702]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0-alpha.10

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

No relevant code here as this is a build issue.

But I am using a monorepo (with Yarn Berry), so I have:
- `project/node_modules`: my modules directory
- `project/packages/mobile`: the RN app

To support this, I am loading Sentry in Gradle this way (inspired from Expo):
```
apply from: new File(["node", "--print", "require.resolve('@sentry/react-native/package.json')"].execute().text.trim(), "../sentry.gradle")
```

---
**I have following issue:**

When building for Android, I get the following error:

```
> Task :app:bundleReleaseJsAndAssets_SentryCollectModules_com.inteji.notos@1.0.8+142_142004 FAILED
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/renchap/dev/project/packages/mobile/node_modules/@sentry/react-native/dist/js/tools/collectModules.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The gradle task tries to launch `project/packages/mobile/node_modules/@sentry/react-native/dist/js/tools/collectModules.js`, but the correct path for this file in my setup is `project/node_modules/@sentry/react-native/dist/js/tools/collectModules.js`

**Steps to reproduce:**
- Have a monorepo setup, with a RN app in sub directory
- Build for Android

**Actual result:**

The app builds

**Expected result:**

The app does not build, with the error above

**Comment by renchap** [comment]
I found this as a workaround:

```
# in android/app/build.gradle
project.ext.sentryCli = [
    collectModulesScript: new File(["node", "--print", "require.resolve('@sentry/react-native/package.json')"].execute().text.trim(), "../dist/js/tools/collectModules.js")
]
```

This uses a path relative to the installed node package, so it correctly finds my non-standard `node_modules` location. It could probably also be made to be relative to the `sentry.gradle` file?

Note that for iOS it works fine as the `collectModules.js` path is relative to the shell script.

**Comment by krystofwoldrich** [comment]
I was about to write down the same solution.

Also, note that you must adjust the path from where the modules are collected. By default, it's the `node_modules` dir in the RN project, but yours doesn't exist.

```groovy
project.ext.sentryCli = [
    collectModulesScript: "path/to/@sentry/react-native/dist/js/tools/collectModules.js",
    modulesPaths: [
      "path/to/your/node_modules",
    ],
```

**Comment by renchap** [comment]
I still think that my use-case should be handled natively and paths should be relative to the actual installation.

Or it should be documented somewhere that this needs custom configuration, and what to change.
