### ISSUE TITLE
BUG: after upgrade to version >= 4.10 - sentry-testkit stopped getting reports through `transport` option

### ISSUE THREAD

**Issue by zivl** [getsentry/sentry-react-native#2718]
[`sentry-teskit`](https://wix.github.io/sentry-testkit/) has support for `@sentry/react-native` library since the begining.
recently, an issue was reported from consumers who are using both `@sentry/react-native` and `sentry-teskit`, they mainly complain on support regression after moving from version `@sentry/react-native@4.9.0` to versions `@sentry/react-native@4.10.0` and above.

See original issue [here](https://github.com/wix/sentry-testkit/issues/151): https://github.com/wix/sentry-testkit/issues/151

I was trying to debug and catch what has been changed but so far i'm out of explanations.
I did succeed in reproducing the issue in 100%. 
This is the [PR](https://github.com/wix/sentry-testkit/pull/154) which contains the code to easily reproduce the issue: https://github.com/wix/sentry-testkit/pull/154

**SDK:**
`"@sentry/react-native": "4.9.0",`

**SDK version:** 0.0.0

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Steps to reproduce:**
- Clone branch with https://github.com/wix/sentry-testkit/pull/154
- `cd test/ReactNativeDemoApp`
- Currently the reproducible project is set to use `@sentry/react-native@4.9.0`
- Run the tests with `npm test` - everything works
- Change version to `@sentry/react-native@4.10.0`
- Run the tests with `npm test` - sentry testkit tests are failing for not getting the reported exceptions

**Comment by krystofwoldrich** [comment]
Hi,
thanks for the info, there was JS SDK lib bump up in [`4.10.0`](https://github.com/getsentry/sentry-react-native/releases/tag/4.10.0). Maybe something changed there. 

I can reproduce the issue, I'll take a look and let you know @zivl. I'm not familiar with [`sentry-teskit`](https://wix.github.io/sentry-testkit/) so I might have some questions.

**Comment by zivl** [comment]
@krystofwoldrich sure! i'll be happy to help where ever i can 💪

**Comment by krystofwoldrich** [comment]
@zivl It was the ModulesLoader integration throwing an error because the native was not available. [Here is the fix.](https://github.com/getsentry/sentry-react-native/pull/2730)

**Comment by zivl** [comment]
WOW thanks @krystofwoldrich 🥇 
I'll keep an eye to see when it was released and I'll validate on my end as well

**Comment by krystofwoldrich** [comment]
The https://github.com/getsentry/sentry-react-native/releases/tag/4.13.0 is out. @zivl you can try it.

**Comment by jfaris** [comment]
Version 4.13.0 fixes the issue for us. Thank you @krystofwoldrich for the quick turnaround!
