### ISSUE TITLE
Ability to enable or disable uploading source map and reporting issues in RELEASE mode

### ISSUE THREAD

**Issue by MohammadAzimi** [getsentry/sentry-react-native#2719]
What I need is to be able to **manually** set whether I want to upload my **source map file** or not in **release** mode. For example in different android flavors. Or even completely disable uploads and disable sentry. Like in debug mode.

Best Regard

**Comment by krystofwoldrich** [comment]
Thank you for the info. We already have an issue with this.

Duplicate:
- https://github.com/getsentry/sentry-react-native/issues/1042
