### ISSUE TITLE
"App start was never finished" error when traceSampleRate is set with looping App.

### ISSUE THREAD

**Issue by ansh** [getsentry/sentry-react-native#2721]
**OS:**
- [x]  MacOS

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0) 

**SDK version:** 4.9.0 but happens on 4.12.0 as well (tested)

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [x]  Yes

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Unfortunately, this does not show up on sentyr.io

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  enableInExpoDevelopment: true,
  tracesSampleRate: 1.0, // This is where the problem lies!
  debug: __DEV__, 
});
```

---
**I have following issue:**

When I install 

**Steps to reproduce:**
- Create a fresh install of Expo, expo-dev-client, and install Sentry
- Load the app

**Actual result:**

Warning as shown: 

`Sentry Logger [warn]: App start was never finished.`
<img width="250"  alt="CleanShot 2022-12-28 at 12 08 01@2x" src="https://user-images.githubusercontent.com/8207733/209771170-2e843bb5-5509-43dc-91b5-81da707370fa.png">

Also, this log message keeps looping thousands of times per second:
```
 LOG  Sentry Logger [log]: [Tracing] popActivity 8392fef468d98d41
 LOG  Sentry Logger [log]: [Tracing] new activities count 0
 LOG  Sentry Logger [log]: [Tracing] pushActivity: 82a35edcd06b597c
 LOG  Sentry Logger [log]: [Tracing] new activities count 1
 LOG  Sentry Logger [log]: [Tracing] Starting 'http.client' span on transaction 'App Start' (b1d98ddddd26fc24).
```

**Expected result:**

Everything loads smoothly

**Comment by ansh** [comment]
Related issue: https://stackoverflow.com/questions/71948807/performance-monitoring-is-not-uploaded-by-sentry-expo

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the information, sadly we can't reproduce the issue.

Could you provide a minimal reproducible example with detailed steps on how you build the app?

**Comment by krystofwoldrich** [comment]
This app https://github.com/nikolovlazar/goodbyemoney-reactnative/tree/99d7fc448e4a2d0012b0c72b0ef2cf8b8583e3dc has the same issue, thanks @nikolovlazar.

At first glance, it seems the issue is caused by the frequent HTTP requests from the expo dev client to the dev server. The transaction never ends as new spans are constantly created.

**Comment by krystofwoldrich** [comment]
@ansh @nikolovlazar 

As this only happens when using expo-dev-client, I would suggest not creating spans for requests toward the `/logs` endpoint of the development server.

```javascript
import * as Network from 'expo-network';

const devServerPort = 8081;
let devServerIpAddress: string | null = null;
Network.getIpAddressAsync().then((ip) => {devServerIpAddress = ip});

Sentry.init({
  tracesSampleRate: 1.0,
  integrations: [
    new Sentry.Native.ReactNativeTracing({
      shouldCreateSpanForRequest: (url) => {
        return !__DEV__ || !url.startsWith(`http://${devServerIpAddress}:${devServerPort}/logs`);
      },
    }),
  ],
});
```

**Comment by nikolovlazar** [comment]
That fixed it! Thanks @krystofwoldrich 🙌
