### ISSUE TITLE
Add Sentry Android Gradle Plugin example to the sample app

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2726]
### Description

At the moment the Sentry Android Gradle Plugin (SAGP) is not part of the sample app.

This issue is about adding an example (just a comment is enough) to show how SAGP would be added to the app.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-docs/pull/7078
- [ ] https://github.com/getsentry/sentry-react-native/pull/2861
```

**Comment by kahest** [comment]
Could be on docs page or in sample app (better: both).

**Comment by krystofwoldrich** [comment]
Docs update
- https://github.com/getsentry/sentry-docs/pull/7078

**Comment by krystofwoldrich** [comment]
SAGP is present in docs and the sample app.
