### ISSUE TITLE
Make collecting modules on Android mono repo friendly

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2740]
### Description

That means the path to `tools/collectModules.js` should be resolved relative to the plugin file path and not to the React root path.

https://github.com/getsentry/sentry-react-native/blob/8fbf60092842ca7f698340215dab1be0f53a29e6/sentry.gradle#L168

Currently, users can set their own path, but it can be solved out of the box.
https://github.com/getsentry/sentry-react-native/blob/8fbf60092842ca7f698340215dab1be0f53a29e6/sentry.gradle#L167

Based on https://github.com/getsentry/sentry-react-native/issues/2702

**Comment by mjooms** [comment]
Would be nice to fix this! We run a monorepo and it took me (quite some/too much) time to figure out I could specify this path with:

```
project.ext.sentryCli = [
        collectModulesScript : "../../../../node_modules/@sentry/react-native/dist/js/tools/collectModules.js"
]
```

**Comment by taylorkline** [comment]
Could this potentially be added as a breaking change to the `CHANGELOG.md` for those upgrading Sentry within a monorepo? This seems to be a regression somewhere between v3 and the latest v4 release.

**Comment by otech47** [comment]
👍🏼 

also took a painful amount of time to find the `collectModulesScript` fix and docs don't say anything about it
