### ISSUE TITLE
No known class method for selector 'captureScreenshots'

### ISSUE THREAD

**Issue by 1280103995** [getsentry/sentry-react-native#2746]
**OS:**
 MacOS

**Platform:**
 iOS

**SDK:**
"@sentry/react-native": "4.13.0"

**`react-native` version:** 0.71.0

**Are you using Expo?**
 No

<img width="1386" alt="73daef552d9b" src="https://user-images.githubusercontent.com/17424486/212284583-a491a674-44ca-4f14-99e4-e9106e6322b8.png">

**Comment by krystofwoldrich** [comment]
Seems like you have an outdated version of `sentry-cocoa`. Please run the update below.
```bash
cd ios
pod update Sentry
```

In case it won't work please let us know and we can reopen the issue.

**Comment by 1280103995** [comment]
> Seems like you have an outdated version of `sentry-cocoa`. Please run the update below.
> 
> ```shell
> cd ios
> pod update Sentry
> ```
> 
> In case it won't work please let us know and we can reopen the issue.

Great, it works. Thank you!

**Comment by ospfranco** [comment]
Hey, I'm using react-native-macos and I'm facing the same issue. I've already tried `pod update Sentry` everything seems to be on the latest version but I still get the error.

<img width="2556" alt="CleanShot 2023-04-23 at 19 28 00" src="https://user-images.githubusercontent.com/1634213/233855117-d0895a07-12e4-4305-8b49-eb4b1ee4d5f7.png">

The pod install output:

Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.71.2)
Installing FBReactNativeSpec (0.71.2)
Installing FMDB (2.7.5)
Installing HotKey (0.1.2)
Installing KeychainAccess (4.2.2)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.71.2)
Installing RCTTypeSafety (0.71.2)
Installing RNCAsyncStorage (1.18.1)
Installing RNCPicker (2.4.10)
Installing RNSentry (5.3.1)
Installing React (0.71.2)
Installing React-Codegen (0.71.2)
Installing React-Core (0.71.2)
Installing React-CoreModules (0.71.2)
Installing React-RCTActionSheet (0.71.2)
Installing React-RCTAnimation (0.71.2)
Installing React-RCTAppDelegate (0.71.2)
Installing React-RCTBlob (0.71.2)
Installing React-RCTImage (0.71.2)
Installing React-RCTLinking (0.71.2)
Installing React-RCTNetwork (0.71.2)
Installing React-RCTSettings (0.71.2)
Installing React-RCTText (0.71.2)
Installing React-RCTVibration (0.71.2)
Installing React-callinvoker (0.71.2)
Installing React-cxxreact (0.71.2)
Installing React-jsc (0.71.2)
Installing React-jsi (0.71.2)
Installing React-jsiexecutor (0.71.2)
Installing React-jsinspector (0.71.2)
Installing React-logger (0.71.2)
Installing React-perflogger (0.71.2)
Installing React-runtimeexecutor (0.71.2)
Installing ReactCommon (0.71.2)
Installing Sentry (8.4.0)
Installing SentryPrivate (8.4.0)
Installing SocketRocket (0.6.0)
Installing Sparkle (2.4.1)
Installing Yoga (1.14.0)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing react-native-get-random-values (1.8.0)
Installing react-native-webview (11.26.1)


I've already tried clearing `derived data` folder, cleaning the build via xcode and deleting `macos/build` folder but I still cannot get the app to compile.

**Comment by ospfranco** [comment]
<img width="782" alt="CleanShot 2023-04-23 at 20 50 33" src="https://user-images.githubusercontent.com/1634213/233859080-2c13fd58-7625-4990-85e9-811a533a2526.png">

Ah, now I see the method has only been implemented for UIKit...

**Comment by krystofwoldrich** [comment]
@ospfranco I believe this is related to https://github.com/getsentry/sentry-react-native/issues/3000

**Comment by ospfranco** [comment]
yup, they are the same
