### ISSUE TITLE
Support source code context for iOS, requires `include-sources` option

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2748]
### Description

Relates to https://github.com/getsentry/team-mobile/issues/42

**Comment by marandaneto** [comment]
Let's add an env. var. with this option people can export and get source context on iOS.
This env. var. should be documented on our docs.

**Comment by krystofwoldrich** [comment]
This is already implemented in Wizard https://github.com/getsentry/sentry-wizard/pull/199
And in docs here https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#upload-debug-symbols-to-sentry

I think also this page should mention the env and then this task is done.
https://docs.sentry.io/platforms/react-native/upload-debug/
