### ISSUE TITLE
how solve to react native with unity 

### ISSUE THREAD

**Issue by salgilbarana** [getsentry/sentry-react-native#2749]
### Description

we are company used to unity  in react native 

try to compile android and ios  but conflict

android : 
![스크린샷 2023-01-16 오전 10 36 53](https://user-images.githubusercontent.com/39834903/212580739-93b42ce6-d133-48a4-bc03-629231c319ae.png)

ios : 
compile after removed unityframework for unity
 
![스크린샷 2023-01-16 오전 10 40 41](https://user-images.githubusercontent.com/39834903/212581148-6ac7c402-4e5c-428f-bed0-9d9c7f6f1649.png)
![스크린샷 2023-01-16 오전 10 42 14](https://user-images.githubusercontent.com/39834903/212581186-bac48661-9977-4753-8360-90f48d9312ed.png)

we must import unity so
can u  provide me with detail information or good solution 

i will wait for ur answer

**Comment by bitsandfoxes** [comment]
That is going to be a bit tricky.
You could try disabling the iOS and Android native support in the configuration window inside the Unity Editor.
That way the Unity SDK will not try to setup and include additional SDKs for the platforms you've already covered with the React Native SDK.

**Comment by krystofwoldrich** [comment]
@salgilbarana Any updates? Did you get it to work?

**Comment by salgilbarana** [comment]
There is nothing wrong with the compilation, but does not report in unity so Aos solved it by enabling sentry in unity and deleting the library, but iOS doesn't know how.  can u help me

**Comment by bitsandfoxes** [comment]
@salgilbarana can you tell me more about what you're exporting from Unity? And how do you import/embed it into your react-native app?

**Comment by salgilbarana** [comment]
thanks for your help. asked for unity team  but we decided to look for another way. so I think done this issue

**Comment by krystofwoldrich** [comment]
I'm closing this. In case you have any other questions feel free to comment here or create a new issue.
