### ISSUE TITLE
Android - Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by Mkolakoglu** [getsentry/sentry-react-native#2751]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.13.0

**`react-native` version:** 0.69.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue](https://sentry.io/organizations/bodyfast-gmbh/issues/3868199689/?environment=development&project=5721080&query=is%3Aunresolved&referrer=issue-stream)]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
  environment: Config.ENV
});
```

---
**I have following issue:**

We started to receive `Malformed calls from JS: field sizes are different` error after updating it from `v3.2.2` to `4.13.0`. It's occurring if we add a logger middleware to redux. We are using [redux-logger](https://github.com/LogRocket/redux-logger) as the middleware and I thought it can be happening because the library is not maintained for a long while. Then, I tried creating my own logger but the error still remained. 

Here is my the logger fn I created (took it directly from [react-redux](https://redux.js.org/understanding/history-and-design/middleware#seven-examples) docs), in case you wanna try:
```
export const logger = (store: any) => (next: any) => (action: any) => {
  console.log('dispatching', action)
  const result = next(action)
  console.log('next state', store.getState())

  return result
}
```

Please also note that we are receiving this error when the debug mode is enabled:
<img width="250" alt="Screen Shot 2023-01-16 at 13 16 43" src="https://user-images.githubusercontent.com/16003411/212654240-06e14553-00c6-4b21-9327-531d45628c70.png">

And receiving this when debug mode is `disabled`:
<img width="250" alt="Screen Shot 2023-01-16 at 13 17 50" src="https://user-images.githubusercontent.com/16003411/212654472-ff6cc25d-2afa-4dda-a55b-4f711ab3413c.png">

Thanks in advance!

**Steps to reproduce:**
- You need to add `react-redux` (we are using `v7.1.1`) and `@sentry/react-native` (`4.13.0`) to reproduce the issue
- Add either [redux-logger](https://www.npmjs.com/package/redux-logger) or the custom middleware above with the `applyMiddleware` fn from react-redux
- Dispatch any action. Then it will show the errors above.

**Actual result:**
It's showing the errors above

**Expected result:**
There should be no error

**Comment by krystofwoldrich** [comment]
Thank you for the message. 
There is already an issue with the same error so I will close this one.
- https://github.com/getsentry/sentry-react-native/issues/2744

You can join the discussion in the other issue.
