### ISSUE TITLE
Add user interaction tracing

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2753]
### Description

In a similar way to the [`sentry-cocoa`](https://docs.sentry.io/platforms/apple/performance/instrumentation/automatic-instrumentation/#user-interaction-tracing) the RN SDK could create spans/transactions for user interactions.

For basic touch/click we can use the already existing implementation for [collection touch breadcrumbs](https://github.com/getsentry/sentry-react-native/blob/dea06fbcdbb5ce074a45a41db8d7233b067c7baa/src/js/touchevents.tsx#L64).

This might not be useful at the moment if we want only interactions that course some API calls, and changes in the app. We can make use of the [gesture responder system](https://reactnative.dev/docs/gesture-responder-system#responder-lifecycle) of RN. It doesn't resolve the gestures, but gives back raw information about the number of touches, and generates touch id, position, velocity etc.

- `onStartShouldSetResponder`
- `onMoveShouldSetResponder`

To recognize gestures such as pinch-to-zoom, swipe left, right... we would need to use native implementation or [integrate with a library](https://github.com/software-mansion/react-native-gesture-handler/).

**Comment by AbhiPrasad** [comment]
We have this functionality for Browser SDKs: https://github.com/getsentry/sentry-javascript/blob/98038da8ab5ae35e1d9221dba2b5af0929ec2c02/packages/tracing/src/browser/browsertracing.ts#L290

**Comment by krystofwoldrich** [comment]
@AbhiPrasad Does the browser SDK send the user interaction transaction even if no spans are attached?
https://github.com/getsentry/sentry-javascript/blob/21ab26bd2b93e6ea700f668375c39c473aba755c/packages/tracing/src/browser/browsertracing.ts#L341

The mobile SDKs are only sending the user interaction transactions when spans are attached.

**Comment by AbhiPrasad** [comment]
The user interaction transactions for browser are still experimental, so there's some behavior that needs to be fixed.

I think there's some more work that needs to be done so that the browser UI transactions follow https://develop.sentry.dev/sdk/performance/ui-event-transactions/.

@0Calories is leading work into INP/user interaction transactions - maybe he can help with the convos here
