### ISSUE TITLE
Operation is not supported for read-only collection when running project with version 5.0.0-alpha.11

### ISSUE THREAD

**Issue by laurenzcodes** [getsentry/sentry-react-native#2758]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.0.0-alpha.11

**`react-native` version:** 0.71.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: artifactoryConfig.isProd ? SENTRY_PROD_DSN : SENTRY_NONPROD_DSN,
      release: getBuildNumber(),
      environment,
      tracesSampleRate: 1,
      enabled: process.env.NODE_ENV !== 'development',
    });
```

---
**I have following issue:**

I am in the process of migrating our RN from v0.64 to v0.71 and am updating needed dependencies.
Sentry is currently preventing my android build from starting.

**Steps to reproduce:**
- Disable hermes in android/gradle.properties (Hermes is broken atm)
- Use RN 0.71 and RN-Sentry 5.0.0-alpha.11
- Try to build android

**Actual result:**

```
FAILURE: Build failed with an exception.

* Where:
Script 'app_root/node_modules/@sentry/react-native/sentry.gradle' line: 284

* What went wrong:
Operation is not supported for read-only collection
```

**Expected result:**

- *app being built and launched in emulator*

**Comment by krystofwoldrich** [comment]
Hi,
have you switched to the new RNGP, or are you using the `react.gradle`?

We don't [support the RNGP yet](https://github.com/getsentry/sentry-react-native/issues/2757).
