### ISSUE TITLE
can there be a stable release with support for RN-0.69

### ISSUE THREAD

**Issue by cainlevy** [getsentry/sentry-react-native#2760]
The fix for https://github.com/getsentry/sentry-react-native/issues/2267 has only been made available in an alpha release, which [does not appear to be close to general availability](https://github.com/getsentry/sentry-react-native/milestone/1). Is there an option to backport it to the stable 4.x branch? The [workaround](https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher) is not friendly to automated deployment pipelines.

**Comment by krystofwoldrich** [comment]
Hi, we can take a look into it,

If you are using RN 0.69 sadly build of the app will fail because of the extra properties in `react-native.config.js`, but if you are using RN 0.70 or higher it only warns you during the build about the deprecated properties.

**Comment by Titozzz** [comment]
I agree that's it's confusing to see v4 having support for RN 0.71 while we had to be on v5 to use RN 0.69+

We will definitely roll back to v4, and use patch package to apply the workaround.

Thanks for the hard work @krystofwoldrich

**Comment by krystofwoldrich** [comment]
We've just released https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0-rc.1 and a GA release will follow soon. I'll close this as we won't add 0.69+ support to v4.
