### ISSUE TITLE
too many errors(30K++ in a day) after version upgrade(3.2.10 => 4.13.0)

### ISSUE THREAD

**Issue by heekyu-pu** [getsentry/sentry-react-native#2768]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.13.0

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://sentry.io/organizations/ridi-manta/projects/manta_app/?issuesType=all&project=5735472)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: Config.SENTRY_DSN,
  enableOutOfMemoryTracking: false,
});
```
---
**I have following issue:**

[Description]

**Steps to reproduce:**
- @sentry/react-native version upgrade (3.2.10 => 4.13.0)

**Actual result:**

too many errors reported to sentry (unintended **Error Capacity Depleted**)

**Expected result:**

I hope there is no error other than crash errors
<img width="998" alt="스크린샷 2023-01-20 오후 4 53 15" src="https://user-images.githubusercontent.com/67251827/213645552-b2743a6f-115e-47e3-9110-38104da9e015.png">

**Comment by heekyu-pu** [comment]
One of many errors:
```
Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```

**Comment by krystofwoldrich** [comment]
Hi, thank you for the information,
since you only want to see crash errors, I would filter for only unhandled errors, but note that also handled exceptions might be important to know about for your users' experience.

Or if you want to ignore only the current exceptions you can use the `ignoreErrors` option.

```js
Sentry.init({
  ignoreErrors: ['Name Of The Error', /^Or Regex/],
  beforeSend: (e: Sentry.Event) => {
    let isHandled = true;
    for (const exception of e.exception.values) {
      if (!exception.mechanism.handled) {
        isHandled = false;
        break;
      }
    }

    if (!isHandled) {
      return e;
    } else {
      return null;
    }
  },
});
```

**Comment by heekyu-pu** [comment]
@krystofwoldrich Thank you for your solution!

But...
It was not collected in 3.2.10, but I wonder why many errors are being collected from 4.13.0.
Errors newly reported in 4.13.0 must have occurred in the same way in 3.2.10

**Comment by krystofwoldrich** [comment]
@heekyu-pu Yes, I agree the errors must have occurred the same before the SDK update. 
I don't know what exactly changed between the v3 and v4, I'll check it.

**Comment by krystofwoldrich** [comment]
I'm not sure what causes the new errors, nevertheless here is some more code explaining how could you catch only crashed errors using the `beforeSend` option.

```js
Sentry.init({
  beforeSend: (e: Sentry.Event) => {
    let isHandled = true;
    for (const exception of e.exception.values) {
      if (!exception.mechanism.handled) {
        isHandled = false;
        break;
      }
    }

    if (!isHandled) {
      return e;
    } else {
      return null;
    }
  },
});
```

In case you have any other questions we can reopen this issue or create a new one.
