### ISSUE TITLE
documented integration for routing instrumentation does not work

### ISSUE THREAD

**Issue by cainlevy** [getsentry/sentry-react-native#2771]
**I have following issue:**

The [guide to set up routing instrumentation](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/) does not work. I am using `@sentry/react-native@4.13.0` as tagged in the documentation but it does not appear to have an API (or type definition?) that is compatible with the documentation.

First:

```ts
// Expected 1-2 arguments, but got 0. ts(2554)
const routingInstrumentation = new Sentry.ReactNativeNavigationInstrumentation();
```

Second:

```tsx
<NavigationContainer
  ref={navigation}
  onReady={() => {
    // Property 'registerNavigationContainer' does not exist on type 'ReactNativeNavigationInstrumentation'
    routingInstrumentation.registerNavigationContainer(navigation)
  }}
>
```

**Steps to reproduce:**

Follow documentation to instrument navigation.

**Actual result:**

Typescript errors.

**Expected result:**

No Typescript errors.

**Comment by krystofwoldrich** [comment]
Hi,
I think you might switch `ReactNativeNavigation` and `ReactNavigation`.

[`const routingInstrumentation = new Sentry.ReactNavigationInstrumentation();`](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-navigation) works without any additional params but [`const routingInstrumentation = new Sentry.ReactNativeNavigationInstrumentation();`](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-native-navigation) doesn't.

Based on the message I assume you are using `React Navigation`, therefore use `Sentry.ReactNavigationInstrumentation()` then the second issue will resolve too. Let us know if this helps.

**Comment by cainlevy** [comment]
Thank you! That's exactly what happened. 🙌
