### ISSUE TITLE
[android] Issues uploading source maps with RN 0.71.1

### ISSUE THREAD

**Issue by cjpete** [getsentry/sentry-react-native#2782]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.13.0

**`react-native` version:** 0.71.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/72-days/issues/3894181976/?project=4504553957883904&query=is%3Aunresolved&referrer=issue-stream

**Configuration:**

```
Sentry.init({
      debug: __DEV__,
      dsn: SENTRY_DSN,
      environment: config.environment,
      integrations: [
        new Sentry.ReactNativeTracing({
          routingInstrumentation,
        }),
      ],
    });
```

---
**I have following issue:**

When running `./gradlew bundleRelease` or other release build commands, there are no source-maps appearing in Sentry for the release. When the app is then run and errors are created, the release appears with 0 artefacts listed against it.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/13134961/214336891-e6e1bbe8-fcc3-4cfe-a2f3-474d656d50ed.png">

**Steps to reproduce:**
- Step 1 - Create a fresh RN project on v0.71.X `npx react-native init newproject --version 0.71.1`
- Step 2 - Install Sentry `cd newproject && yarn add @sentry/react-native`
- Step 3 - Apply the patch as described in https://docs.sentry.io/platforms/react-native/troubleshooting/#react-native-069-and-higher 
- Step 4 - Run the sentry wizard `yarn sentry-wizard -i reactNative -p android`
- Step 4.a - Manually add `apply from: "../../node_modules/@sentry/react-native/sentry.gradle"` to line 90 in android/app/build.gradle
- Step 5 - Run `cd android && ./gradlew bundleRelease` 

**Actual result:**

No source maps uploaded for this release (`com.newproject@1.0+1`)

**Expected result:**

Expected source maps to be uploaded.

**Comment by cjpete** [comment]
FYI If you run through the exact same setup steps but instead use RN `0.70.6` (step 4a is not required), then everything works and the source maps are uploaded as expected.

**Comment by krystofwoldrich** [comment]
Hi, thanks for the info.
The support was added in https://github.com/getsentry/sentry-react-native/pull/2759. Will be part of `4.14.0` released likely today.

**Comment by cjpete** [comment]
@krystofwoldrich do you know whether the patch to react-native-config.js is still required?

**Comment by krystofwoldrich** [comment]
@cjpete Yes, the https://github.com/getsentry/sentry-react-native/releases/tag/4.14.0 is still not out-of-the-box compatible with RN v0.69+ and likely won't be, we only added the RNGP support. Since the v5 release is very close.
