### ISSUE TITLE
Use path filter for GH actions

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-react-native#2786]
### Description

When opening https://github.com/getsentry/sentry-react-native/pull/2784, which only touches the PR request template, I noticed that GH actions run almost all checks, which is unnecessary. 

We can use [path](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths) filters for some of the workflows like buildandtest.yml or e2e.yml to avoid unneeded GH action runs.

You can have a look at [Cocoa 1](https://github.com/getsentry/sentry-cocoa/blob/e71cf92b1ee202a891f28c08fa289ff6807b3aaf/.github/workflows/build.yml#L8-L17), [Cocoa 2](https://github.com/getsentry/sentry-cocoa/blob/e71cf92b1ee202a891f28c08fa289ff6807b3aaf/.github/workflows/test.yml#L8-L18) for reference

**Comment by krystofwoldrich** [comment]
- Implemented in https://github.com/getsentry/sentry-react-native/pull/3545
