### ISSUE TITLE
Automatic Instrumentation for react-native-navigation (wix) creates an error *while sending event*

### ISSUE THREAD

**Issue by JimTeva** [getsentry/sentry-react-native#2787]
**OS:**
- [ ]  Windows
- [*]  MacOS
- [ ]  Linux

**Platform:**
- [*]  iOS
- [ ]  Android

**SDK:**
- [*]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.13.0

**`react-native` version:** 0.65.1

**Are you using Expo?**
- [ ]  Yes
- [*]  No

**Are you using sentry.io or on-premise?**
- [*]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://bigmenu.sentry.io/issues/3893282631/?project=4504534576791552&query=is%3Aunresolved&referrer=issue-stream)

**Configuration:**

(`@sentry/react-native`)
```
const sentryRoutingInstrumentation =
  new Sentry.ReactNativeNavigationInstrumentation(Navigation);
Sentry.init({
  dsn: 'https://****************.sentry.io/*********',
  tracesSampleRate: 1.0,
  normalizeDepth: 10,
  debug: __DEV__,
  // FIXME: the below code creates an error
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation: sentryRoutingInstrumentation,
    }),
  ],
});
```

---
**I have following issue:**

I want to add Automatic instrumentation for react-native-navigation.

If I don't put the below code for react-native-navigation:
```
 integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation: sentryRoutingInstrumentation,
    }),
  ],
```
then my purposely made error is reported without problem.

If I add the code for react-native-navigation, then the below error happens: 
```
Sentry Logger [error]: Error while sending event: [Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

[[20,59],[7,0],[[296,100,1674695990047,false]],2949]]
```

**Steps to reproduce:**
- add react-native-navigation library
- add the code from https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/#react-native-navigation

**Actual result:**
![Capture d’écran 2023-01-25 à 17 59 21](https://user-images.githubusercontent.com/10006390/214755871-ce8e3572-ad17-4554-a8d7-87174fbb9eef.png)

**Expected result:**

no error

**Comment by krystofwoldrich** [comment]
This seems like the same error, but different steps on how it occurred.
- https://github.com/getsentry/sentry-react-native/issues/2744
