### ISSUE TITLE
auto-init attribute present in a dependency

### ISSUE THREAD

**Issue by itsramiel** [getsentry/sentry-react-native#2795]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 5.0.0-alpha.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

When trying to run my project on android I get the following error:
```
Attribute meta-data#io.sentry.auto-init@value value=(false) from [:sentry_react-native] AndroidManifest.xml:15:13-34
is also present at [private-dependancy.aar] AndroidManifest.xml:21:13-33 value=(true).
Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:13:9-15:37 to override.
```

I hope you could help me and let me know what I need to do in such a case. It seems like a dependancy I am using, which is a private one, is using Sentry? Is it possible for a dependancy to use Sentry while my app also use it?

What should I do in this case?

**Comment by krystofwoldrich** [comment]
We don't support libraries using Sentry, our SDKs are meant to be used in Apps. Are you able to find out which dependency is causing it? Or can you replicate this in a minimal reproducible example that you could send to us?

**Comment by itsramiel** [comment]
Yes I know which dependency is using it, but as I mentioned it is a private native dependency, not available on npm. 

Unfortunately I can't create a reproducible example since the library is a private one.

I just would like some clarification if I should communicate this to the library maintainers as:

> We don't support libraries using Sentry, our SDKs are meant to be used in Apps.

so from what I understand from you is that they should not be using it in the library. Am I right?

**Comment by krystofwoldrich** [comment]
I see, yes they should not be using Sentry in the library. I'll close the issue for now, but If you have any other questions feel free to add comments and we can reopen the issue again.

**Comment by itsramiel** [comment]
Thank you. I just wanted the question answered 🙏🏻
