### ISSUE TITLE
IOS cannot read version and build number from pbxproj when auto sourcemap uploading, result: $(MARKETING_VERSION)+$(CURRENT_PROJECT_VERSION)

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [getsentry/sentry-react-native#2802]
**OS:**
- [ ]  Windows
- [o ]  MacOS
- [ ]  Linux

**Platform:**
- [o ]  iOS
- [ ]  Android

**SDK:**
- [o ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0
    "@sentry/react-native": "5.0.0-alpha.7",
    "@sentry/wizard": "1.2.17",
sentry-cli 1.74.6

**`react-native` version:** 0.0.0
    "react-native": "0.70.6",

**Are you using Expo?**
- [ ]  Yes
- [o ]  No

**Are you using sentry.io or on-premise?**
- [o ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
import * as Sentry from '@sentry/react-native';

....

Sentry.init({
  dsn: Config.SENTRY_DSN,
  debug: true,
});
...

export default codePush({
  ...options
})(Sentry.wrap(NewApp));
...

```

---
**I have following issue:**

ios cannot read version and build number when soucemap automically uploaded

AOS
2.12.0 (345)

IOS
$(MARKETING_VERSION)+$(CURRENT_PROJECT_VERSION)

AOS
read version and build number perfectly
but ios cannot read version and build number from pbxproj

**Steps to reproduce:**
- Step 1
clean install react native sentry as docs said
- Step 2
do release build android and ios
build succeeded both, but ios sourcemap release and dist is strange

**Actual result:**
source maps

AOS
2.12.0 (345)

IOS
$(MARKETING_VERSION)+$(CURRENT_PROJECT_VERSION)
[Actual result]

**Expected result:**
IOS sourcemap should be 2.12.0 (345) not $(MARKETING_VERSION)+$(CURRENT_PROJECT_VERSION)

[Expected result]

what should i do?
android works well but only ios is a problem

**Comment by taehyun-kim-tenuto** [comment]
ios uploaded sourcemap and issue report

<img width="1542" alt="스크린샷 2023-02-03 오전 12 20 02" src="https://user-images.githubusercontent.com/79429899/216365399-2111556e-bd46-47fa-a9db-fad5fcb341af.png">

**Comment by taehyun-kim-tenuto** [comment]
my build phase status

**Bundle React Native code and images**

export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
../node_modules/react-native-vector-image/strip_svgs.sh

**Upload Debug Symbols to Sentry**
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym

**Comment by taehyun-kim-tenuto** [comment]
plus my project use hermes

**Comment by taehyun-kim-tenuto** [comment]
Please tell me the version that works perfectly on android and ios both

ex)
"@sentry/react-native": "5.0.0-alpha.7",
"@sentry/wizard": "1.2.17",
sentry-cli 1.74.6

**Comment by krystofwoldrich** [comment]
Hi, thank you for all the detailed information.

This was fixed in https://github.com/getsentry/sentry-cli/releases/tag/2.10.0. Please upgrade to the latest version of `@sentry/cli`.
