### ISSUE TITLE
Run custom shell script 'Bundle React Native code and images || Archive failed

### ISSUE THREAD

**Issue by gulsher7** [getsentry/sentry-react-native#2803]
Its working find in debug mode and create crash logs on sentry panel but when i go to archive build its failed and throw an error as mentioned in screen short.

these version i'm using
    "react": "^17.0.2",
    "react-native": "^0.67.5",
    "@sentry/react-native": "^4.14.0",
    
![Screenshot 2023-02-03 at 12 11 10 PM](https://user-images.githubusercontent.com/56266123/216530176-0fa71165-fd28-45fb-b8ab-45cbc661175c.png)

My Bundle React Native code and images Script

export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh

/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh

Notes: I'm using multiple targets in this projects.

**Comment by krystofwoldrich** [comment]
duplicate https://github.com/getsentry/sentry-react-native/issues/2804
