### ISSUE TITLE
Archive Failed  ||  line 43: node: command not found

### ISSUE THREAD

**Issue by gulsher7** [getsentry/sentry-react-native#2804]
### Environment

I'm using these versions : 
    "react": "^17.0.2",
    "react-native": "^0.67.5",
    "@sentry/react-native": "^4.14.0" 

### Steps to Reproduce

1. When i going to archive my build its throw an error which i mentioned in screenshot 

### Expected Result

Archive Successfully.

### Actual Result

<img width="815" alt="Screenshot 2023-02-03 at 1 38 19 AM" src="https://user-images.githubusercontent.com/56266123/216438716-5bd80261-f5c8-430c-bb38-c28b66b04116.png">

**Comment by kamilogorek** [comment]
This is erroring here: https://github.com/getsentry/sentry-react-native/blob/1478dc089f1aa69ba66c4ad7c8859d65282eab42/scripts/collect-modules.sh#L26-L43
Which means that your PATH (or RN project, dunno) is not configured to expose `node` binary for the script to use.

**Comment by gulsher7** [comment]
so how can i fixed this issue please guide me.

**Comment by kamilogorek** [comment]
I don't know how XCode propagates its PATH settings, so you'll have to wait for someone from the team answer this.

**Comment by krystofwoldrich** [comment]
Are you using any node version managers?

This could help if so. 

```bash
ln -s $(which node) /usr/local/bin/node
```

https://docs.sentry.io/platforms/react-native/troubleshooting/#using-node-with-nvm-or-volta

**Comment by gulsher7** [comment]
Yes I’m using nvm and please let me know where i put this line command “ ln
-s $(which node) /usr/local/bin/node”

**Comment by krystofwoldrich** [comment]
@gulsher7 Just run it in your terminal and then build your app as usual.

**Comment by gulsher7** [comment]
thanks @krystofwoldrich it's worked.
