### ISSUE TITLE
Does sentry worth using?

### ISSUE THREAD

**Issue by myckhel** [getsentry/sentry-react-native#2816]
## Opinion

Sentry is now so problematic such that You cannot read crash logs unless you do manual source map uploading that will take you about 10mins every-time you deploy.

Whats the essence of using it when it cannot do its job out of the box without creating another issue.

Anyone can prove me wrong!

**Comment by krystofwoldrich** [comment]
Hi @myckhel,
if you follow [the guide here](https://docs.sentry.io/platforms/react-native/) the source maps are uploaded automatically on a release build.

Can we help you with any concrete issue you are experiencing?

**Comment by myckhel** [comment]
> if you follow [the guide here](https://docs.sentry.io/platforms/react-native/) the source maps are uploaded automatically on a release build.

Unfortunately it didnt work and crashes were not readable.


### From sentry doc
https://docs.sentry.io/platforms/react-native/#add-readable-stack-traces-to-errors
> Add Readable Stack Traces to Errors
Depending on how you've set up your JavaScript project, the stack traces in your Sentry errors probably don't look like your actual code.

> To fix this, head over to our [source maps documentation](https://docs.sentry.io/platforms/react-native/sourcemaps/) where you'll learn how to upload source maps, so you can make sense of your stack traces.

Sentry pointed it out to be done explicitly

**Comment by krystofwoldrich** [comment]
Thank you for the reply,
could you share a bit more details about what version of `react-native` and `@sentry/react-native` are you using?

Can you share your `Sentry.init` code?

Have you run the `@sentry/wizard`? The following command adds automatic source maps upload for iOS and Android.

```
npx @sentry/wizard -i reactNative -p ios android
```

For iOS the upload happens in `Bundle React Native Code and Images` build phase and on Android [`sentry.gradle`](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-gradle-integration) is added. 

If you would like we can guide you on how to verify that the source maps are uploading.

**Comment by myckhel** [comment]
@krystofwoldrich Thanks for your response.

It had always been this issue
<img width="580" alt="Screenshot 2023-02-10 at 12 04 04" src="https://user-images.githubusercontent.com/34090541/218076684-5ddee420-c88b-449c-97a1-a26c311d6971.png">

So I tried to restart the installation process and its working as expected.
The sentry docs made me believe one has to manually upload the source maps every time but now i see that with the proper setup, source maps gets uploaded automatically.

But i discovered one more issue i planned to work on which is making it compatible with codepush: https://docs.sentry.io/platforms/react-native/manual-setup/codepush/

**Comment by krystofwoldrich** [comment]
Thanks for the message,
I'm happy that it worked out, and feel free to open new issues/discussions if something else will come up.
