### ISSUE TITLE
cannot read full stack trace when manual sourcemap uploading with hermes

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [getsentry/sentry-react-native#2817]
**OS:**
- [ ]  Windows
- [O]  MacOS
- [ ]  Linux

**Platform:**
- [O]  iOS
- [O]  Android

**SDK:**
- [O]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

    "@sentry/cli": "2.10.0",
    "@sentry/react-native": "5.0.0-alpha.10",
    "@sentry/wizard": "1.2.17",

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

    "react-native": "0.70.6",

**Are you using Expo?**
- [ ]  Yes
- [O]  No

**Are you using sentry.io or on-premise?**
- [O]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: Config.SENTRY_DSN,
  debug: true,
  release: test123,
  dist: t123,
  environment: Config.ENV,
  tracesSampleRate: 0.1,
  sampleRate: 0.8,
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- Step 1
- Step 2

i did manual sourcemap upload
this is command

`npx react-native bundle --platform ios --dev false --entry-file index.js --reset-cache --bundle-output main.jsbundle --sourcemap-output main.jsbundle.map --minify false

npx react-native bundle --platform android --dev false --entry-file index.js --reset-cache --bundle-output index.android.bundle --sourcemap-output index.android.bundle.packager.map --minify false

chmod 777 index.android.bundle
node_modules/react-native/sdks/hermesc/osx-bin/hermesc -O -emit-binary -output-source-map -out=index.android.bundle.hbc index.android.bundle
rm -f index.android.bundle
mv index.android.bundle.hbc index.android.bundle

node node_modules/react-native/scripts/compose-source-maps.js index.android.bundle.packager.map index.android.bundle.hbc.map -o index.android.bundle.map

node_modules/@sentry/cli/bin/sentry-cli releases files 3.33.3+334 upload-sourcemaps --dist 334 --strip-prefix /path/to/project/root main.jsbundle main.jsbundle.map --org myOrg --project myProject
node_modules/@sentry/cli/bin/sentry-cli releases files 3.33.3+334 upload-sourcemaps --dist 334 --strip-prefix /path/to/project/root index.android.bundle index.android.bundle.map --org myOrg --project myProject

`

release and dist are exactly as same as sentry init options

**Actual result:**

i cannot read the code line the error ocurred

<img width="940" alt="스크린샷 2023-02-09 오후 5 06 37" src="https://user-images.githubusercontent.com/79429899/217753257-db23872a-c760-42e3-abad-4b6d9fb4a2f4.png">

[Actual result]

**Expected result:**

i can read the code line like below

[Expected result]
<img width="856" alt="스크린샷 2023-02-09 오전 11 56 09" src="https://user-images.githubusercontent.com/79429899/217706112-cacc875e-2d1d-4856-8975-71bf62845a2f.png">

btw i use hermes

**Comment by taehyun-kim-tenuto** [comment]
plus i disable auto sourcemap upload
so i deleted the line below in build.gradle
``
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
``
and also deleted upload debug symbols to sentry build phase in pbxproj

plus i changed Bundle React Native code and images too

``
// Bundle React Native code and images
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
../node_modules/react-native-vector-image/strip_svgs.sh
``

**Comment by taehyun-kim-tenuto** [comment]
i think hermes + manual sorcemap upload cannot get a good stack trace
when i did the same thing with auto sourcemap upload there was no problem

**Comment by marandaneto** [comment]
@taehyun-kim-tenuto have you checked this [page](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/)?

**Comment by krystofwoldrich** [comment]
@taehyun-kim-tenuto

Could you provide a minimal reproducible example so we can try to debug this?

**Comment by taehyun-kim-tenuto** [comment]
i have a question what is this??
Grouped by: exception stack-trace, in-app exception stack-trace
are these interrupting stack tracing?

**Comment by taehyun-kim-tenuto** [comment]
first one manual sourcemap upload 
it has tag apply native

third one auto sourcemap upload
the tag said exactly same path the error ocurred

<img width="628" alt="스크린샷 2023-02-09 오후 10 00 42" src="https://user-images.githubusercontent.com/79429899/217819768-a9820150-c9c9-44f9-ae4a-3f510811509f.png">

**Comment by marandaneto** [comment]
@taehyun-kim-tenuto are you building your app on release mode? if not, please test it on release mode and not debug mode.

**Comment by taehyun-kim-tenuto** [comment]
of course i build release mode

**Comment by krystofwoldrich** [comment]
@taehyun-kim-tenuto Maybe there is a mismatch between the release version that the app reports and the release version to which you uploaded the source maps. 

Can you open the issue that is not correctly mapped and open the release from there and check that the correct source maps are uploaded?

**Comment by taehyun-kim-tenuto** [comment]
<img width="852" alt="스크린샷 2023-02-09 오후 11 36 52" src="https://user-images.githubusercontent.com/79429899/217842966-10bc901e-07b3-4376-b2de-1a171c68b961.png">
<img width="958" alt="스크린샷 2023-02-09 오후 11 37 11" src="https://user-images.githubusercontent.com/79429899/217843025-282093cf-6911-467a-bc12-618ec13c3087.png">

**Comment by taehyun-kim-tenuto** [comment]
uploaded release and dist are as same as issue tags

**Comment by taehyun-kim-tenuto** [comment]
this is a json that stack trace working (auto upload)
<img width="916" alt="스크린샷 2023-02-10 오전 12 04 12" src="https://user-images.githubusercontent.com/79429899/217849947-a132d011-25a9-4c42-a26d-9f16bbb7dfea.png">

and this json is manual upload one that stack trace not working
<img width="1164" alt="스크린샷 2023-02-10 오전 12 05 19" src="https://user-images.githubusercontent.com/79429899/217850273-fd77660f-9312-45c8-90bd-f065d9926f38.png">

**Comment by taehyun-kim-tenuto** [comment]
<img width="1027" alt="스크린샷 2023-02-10 오전 11 31 04" src="https://user-images.githubusercontent.com/79429899/217985350-15acbcdb-680f-444b-967c-9b8e28eb0648.png">

**Comment by taehyun-kim-tenuto** [comment]
i think android works but only ios not working

**Comment by taehyun-kim-tenuto** [comment]
when upload manual sourcemap
the log said like this

```
> Found 1 release file
> Found 1 release file
> Analyzing 2 sources
> Analyzing completed in 0.894s
> Rewriting sources
> Rewriting completed in 0.795s
> Adding source map references
> Bundling files for upload... ~/main.jsbundle.map
> Bundling completed in 1.797s
> Optimizing completed in 0.038s
> Uploading completed in 4.866s
> Uploaded release files to Sentry
> Processing completed in 0.277s
> File upload complete (processing pending on server)
> Organization: aaa
> Project: bbb
> Release: 6.66.66+666666
> Dist: 0

Source Map Upload Report
  Scripts
    ~/main.jsbundle
  Source Maps
    ~/main.jsbundle.map
> Found 1 release file
> Found 1 release file
> Analyzing 2 sources
> Analyzing completed in 0.541s
> Rewriting sources
> Rewriting completed in 0.346s
> Adding source map references
> Bundling files for upload... ~/index.android.bundle.map
> Bundling completed in 0.756s
> Optimizing completed in 0.017s
> Uploading completed in 3.238s
> Uploaded release files to Sentry
> Processing completed in 0.248s
> File upload complete (processing pending on server)
> Organization: aaa
> Project: bbb
> Release: 6.66.66+666666
> Dist: 0

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map

```

**Comment by krystofwoldrich** [comment]
@taehyun-kim-tenuto Thank you for all the details. I'm looking into it. 
That is good news that Android works.
I'll keep you posted.

**Comment by taehyun-kim-tenuto** [comment]
if i initialize sentry after codepush.getUpdateMetadata callback
android is not working as well

`codePush.getUpdateMetadata().then(update => {
  Sentry.init({
    dsn: Config.SENTRY_DSN,
    debug: true,
    release: update
      ? `${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}+code:${
          update.label
        }`
      : `${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
    dist: update ? `${update.label}` : 0,
    environment: Config.ENV,
    tracesSampleRate: 0.1,
    sampleRate: 0.8,
    integrations: [
      new Sentry.ReactNativeTracing({
        // Pass instrumentation to be used as `routingInstrumentation`
        routingInstrumentation,
        // ...
      }),
    ],
    beforeSend: event => {
      return event;
    },
  });
});`

<img width="847" alt="스크린샷 2023-02-10 오후 6 41 36" src="https://user-images.githubusercontent.com/79429899/218058189-f0f6ffce-3a60-43d4-8b83-08ed27886ad0.png">

**Comment by taehyun-kim-tenuto** [comment]
if i initialize sentry outside of the codepush.getupdatemetadata callback

```
// codePush.getUpdateMetadata().then(update => {
const update = false;

Sentry.init({
  dsn: Config.SENTRY_DSN,
  debug: true,
  release: update
    ? `${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}+code:${
        update.label
      }`
    : `${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
  dist: update ? `${update.label}` : '0',
  environment: Config.ENV,
  tracesSampleRate: 0.1,
  sampleRate: 0.8,
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      // ...
    }),
  ],
  beforeSend: event => {
    return event;
  },
});
// });
```

stack trace is normal
<img width="1038" alt="스크린샷 2023-02-10 오후 9 38 53" src="https://user-images.githubusercontent.com/79429899/218094479-95b4c70c-a3fd-48df-a1f9-d6d8744caa16.png">

**Comment by taehyun-kim-tenuto** [comment]
iOS manual sourcemap upload worked !!
--minify false option was the cause thank you!!

but i still have problem i explained above

**Comment by krystofwoldrich** [comment]
@taehyun-kim-tenuto Happy to hear that iOS worked out.

[This issue seems to be from an app without `hermes`](https://github.com/getsentry/sentry-react-native/issues/2817#issuecomment-1425522727), which would explain the source maps not to be working.

**Comment by taehyun-kim-tenuto** [comment]
@krystofwoldrich 
i dont understand
my app use hermes

**Comment by taehyun-kim-tenuto** [comment]
build.gradle
```
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
]
```

Podfile
```
use_react_native!(
  :path => config[:reactNativePath],
  # Hermes is now enabled by default. Disable by setting this flag to false.
  # Upcoming versions of React Native may rely on get_default_flags(), but
  # we make it explicit here to aid in the React Native upgrade process.
  :hermes_enabled => true,
  :fabric_enabled => flags[:fabric_enabled],
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  :flipper_configuration => FlipperConfiguration.enabled,
  # An absolute path to your application root.
  :app_path => "#{Pod::Config.instance.installation_root}/.."
)
```

**Comment by taehyun-kim-tenuto** [comment]
i just call sentry init outside of the getupdatemetadata callback
so i use dist as package.json value not a codepush label
i think initializing sentry inside of the getupdatemetadata callback is a bad practice and i also read some texts that dont recommend it
finally all my problems were solved and thank you sentry team
