### ISSUE TITLE
Build failing for android in react-native

### ISSUE THREAD

**Issue by sairajKalkundre** [getsentry/sentry-react-native#2819]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.14.0

**`react-native` version:** 0.71.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**I have following issue:**

Recently I have upgraded react-native-0.66.5 to react-native-0.71.2.
While building for android with command **npm run android** the build failed
![Screenshot 2023-02-10 at 13 12 31](https://user-images.githubusercontent.com/29306307/218089853-b3fe6e5b-aaab-4574-a02e-7132922a9b55.png)

the line on 287 in /node_modules/@sentry/react-native/sentry.gradle is
![Screenshot 2023-02-10 at 13 08 17](https://user-images.githubusercontent.com/29306307/218088972-1478c21e-5916-464a-b139-72b0016d8c6b.png)
but in react-native-0.71.2 ,they have removed the 
![Screenshot 2023-02-10 at 13 09 29](https://user-images.githubusercontent.com/29306307/218089115-9d169a5d-332a-4ebd-8d50-d62f126bc392.png)
instead hermes-flag is now  located in **android/gradle.properties**
![Screenshot 2023-02-10 at 13 10 24](https://user-images.githubusercontent.com/29306307/218089385-269c3a83-0da8-4843-8b9b-9498649d8c69.png)

**How to resolve this issue?**

**Comment by walkerdb** [comment]
Seconding this, also seeing it after our upgrade. We're currently fixing it by patching the package to hardcode our hermes selection (we haven't turned it on yet), would be great to get an official fix out.

**Comment by krystofwoldrich** [comment]
RN 0.71 also introduced [`com.facebook.react:react-native-gradle-plugin`](https://github.com/react-native-community/rn-diff-purge/compare/release/0.66.5..release/0.71.2#diff-090830547073064692312df674487c7c9d93338bd6accf4e6f88a39cb0247595R19) have you upgraded your builds script to it?

We detect if the new plugin is used, if so the `project.ext.react` is not read.

**Comment by sairajKalkundre** [comment]
@krystofwoldrich Yes , I have added in builds script.
![Screenshot 2023-02-13 at 11 45 19](https://user-images.githubusercontent.com/29306307/218437487-f77e6aa5-aca3-4d4c-9c99-484d7232987c.png)

**Comment by krystofwoldrich** [comment]
From the error, you are getting it seems like the old bundle task is still used.

Are you able to replicate this error in a clean 0.71.2 project?

**Comment by sairajKalkundre** [comment]
I found the solution , @krystofwoldrich  It was still using old bundle task. When I ran **./gradlew clean**  , I saw this warning 
![Screenshot 2023-02-13 at 12 11 09](https://user-images.githubusercontent.com/29306307/218442825-d5bdbc47-a2e6-447a-9bf4-ad8a985680a6.png).

In my android/app/build.gradle I was still using
![Screenshot 2023-02-13 at 12 08 07](https://user-images.githubusercontent.com/29306307/218442887-6ec7e8a5-f4a4-492a-afb5-6002472ecd95.png) . Removing this line worked for me.

**Comment by krystofwoldrich** [comment]
@sairajKalkundre Thanks for the message. Happy that it worked out.
