### ISSUE TITLE
TestFlight builds cannot find the JS source map due to dist number mismatch

### ISSUE THREAD

**Issue by mmmulani** [getsentry/sentry-react-native#2821]
**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 4.9.0

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [x]  Yes

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

normally:
https://new-layer-inc.sentry.io/issues/3930478050/?project=4504658913329152&referrer=project-issue-stream
after manually uploading symbols:
https://new-layer-inc.sentry.io/issues/3930493094/?project=4504658913329152&referrer=project-issue-stream

**Configuration:**

using `sentry-expo`

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // no other options
});
```

---
**I have following issue:**

After creating a build in Xcode and then uploading to TestFlight, JS stack frames cannot be unminified/symbolicated.
The issue stems from the build being recorded into Sentry as version "1.0.0" with dist "1", but when it is uploaded to TestFlight, the dist is auto-incremented to something like "28". In this case, the version string when a JS crash comes in is "1.0.0+28", which Sentry does not have the JS source maps for.

I manually uploaded the JS bundle and source map to Sentry (by downloading the one that was uploaded for "1.0.0+1") using `sentry-cli sourcemaps upload --org ... --project ... -d 28 -r "...@1.0.0+28"` and was able to symbolicate the crash. However this should not be necessary.

**Steps to reproduce:**
- Build in Xcode
- Upload to TestFlight from Xcode
- Encounter JS crash

**Actual result:**

https://new-layer-inc.sentry.io/issues/3930478050/?project=4504658913329152&referrer=project-issue-stream

**Expected result:**

https://new-layer-inc.sentry.io/issues/3930493094/?project=4504658913329152&referrer=project-issue-stream

**Comment by krystofwoldrich** [comment]
Thank you for the message.

You can set the `release` and `dist` in the JS options, then the values set by Xcode will be ignored. That way you could avoid the auto-incremented dist from TestFlight.

Would that work for you?

**Comment by mmmulani** [comment]
Hey, thanks for that workaround. While I guess that would work, it would prevent bugs from old versions from TestFlight from being handled correctly, no?

Is there some kind of ID we can use from the JS bundle (or one that we could add) instead?

Oh, weirdly native crashes seem to be symbolicated just fine, not sure how those are being handled though and if there's anything we can re-use from there.

**Comment by krystofwoldrich** [comment]
Setting the `release` and `dist` should not affect the older versions.

How does TestFlight increments the dist? Does the app get rebuilt? From my understanding TestFlight ships what you upload to it.

**Comment by mmmulani** [comment]
Oh sorry, I guess the core issue here is that we aren't using version numbers in any coherent fashion. Currently all our builds are version 1.0.0 with the `dist` being auto-incremented by TestFlight when we release.

Concretely what that means is: when we build the app, we are actually building `1.0.0+1`. When we submit the app to TestFlight, we provide a `1.0.0+1` build and Apple actually increments the `dist` to ensure that it is unique.

In this world, we run into a problem where Sentry only has source maps for the `1.0.0+1` build but our TestFlight users are actually running something like `1.0.0+28`.

If we override the `release` and `dist` manually within the bundle, I imagine that would mean setting `dist` to `1`, which would run into the problem where Sentry only has source maps for `1.0.0+1` and every build is pretending to be `1.0.0+1`.

My ideal solution would be some kind of unique ID being embedded into the bundle at build time that Sentry could use both on the client side and server side. Does something like that exist? (I imagine it's already using something like this for native builds)
If not, I guess we'll have to be sensible about version numbers, which isn't the worst but just means more work on our side.

**Comment by krystofwoldrich** [comment]
Sadly in your case, the JS source maps work differently than the native debug symbols.

I believe the simplest way is what you mentioned, build the app with a unique `version+dist`. And disable the `Manage Version and Build Number` so `TestFlight` doesn't auto increment the `dist`.
