### ISSUE TITLE
Issues integrating @sentry/react-native into a project that uses react-native-web

### ISSUE THREAD

**Issue by CannibalKush** [getsentry/sentry-react-native#2829]
**Platform:**
Web

**SDK:**
`@sentry/react-native` (>= 1.0.0)

**SDK version:** 4.1.3

**`react-native` version:** 0.63.4

**Are you using Expo?**
No

**Are you using sentry.io or on-premise?**
sentry.io (SaaS)

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn,
    environment,
    enableAutoPerformanceTracking: true,
    tracesSampleRate: 0.2,
    integrations,
    beforeSend,
    beforeBreadcrumb(breadcrumb, hint) {
      // Ignore `console.debug` logs.
      if (breadcrumb.category === 'console' && hint?.level === 'debug') {
        return null;
      }
      return breadcrumb;
    },
    enabled,
    autoInitializeNativeSdk,
    enableNative: false,
  });
```
---
**I have following issue:**

[Description]
Try to use @sentry/react-native on a project that uses React Native Web. Run into issues since ErrorUtils is not defined on the web.

```
Uncaught ReferenceError: ErrorUtils is not defined
    at ReactNativeErrorHandlers._handleOnError (reactnativeerrorhandlers.ts:169:9)
    at ReactNativeErrorHandlers.setupOnce (reactnativeerrorhandlers.ts:52:10)
    at integration.ts:68:1
    at Array.forEach (<anonymous>)
    at setupIntegrations (integration.ts:64:1)
    at ReactNativeClient.setupIntegrations (baseclient.ts:258:1)
    at Hub.bindClient (hub.ts:123:1)
    at initAndBind (sdk.ts:35:1)
    at Object.init (sdk.tsx:115:14)
    at initialiseErrorMonitoring (errorMonitoring.ts:36:10)
```

This happens because of [this issue](https://github.com/necolas/react-native-web/issues/1621)

**Comment by krystofwoldrich** [comment]
This was fixed in https://github.com/getsentry/sentry-react-native/pull/2808. Release `4.14.1` is coming later today.

Note that `react-native-web` is not officially supported.

**Comment by CannibalKush** [comment]
dang, nice one! i see that disabling all the default handlers also kind of solves this, but nice fix!
