### ISSUE TITLE
project.ext.sentryCli doesn't use my properties file

### ISSUE THREAD

**Issue by Akeuuh** [getsentry/sentry-react-native#2834]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 71.2.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**I have following issue:**

I try to implement sentry on my react-native app on the Android side. iOS is working fine. This app already had sentry installed but was not used, don't know why.

My app has three environment (debug, staging and production). We only want to use sentry on staging and prod and the way we are splitting the app for different env is by using different .env file.

For exemple, if we want to build staging app, we run the command `ENVFILE=.env.staging ./gradlew installRelease`

We have two projects on sentry, one for prod and one for staging, so we have two sentry.properties files. My goal is to use the good file for the good environment.

The file name is written in the .env files.

I wanted to use this in app/build.gradle:
```
project.ext.sentryCli = [
        logLevel: "debug",
        sentryProperties: "../sentry-staging.properties"
]
```
But it does not work.

I tried with the wizard, the generated file is located at the same place of mine. And it works great. Even if the project.ext.sentryCli is still defined as above.

When I try to rename my file with sentry.properties, it seems to work too.

The project.ext.sentryCli seems not to be taken..

**Actual result:**

The app doesn't build with my config and say that:

```
 What went wrong:
Execution failed for task :app:createBundleReleaseJsAndAssets_SentryUpload_com.XX@6.2.0+6020010_6020010.
Process 'command '/XX/XX/XX/XX/XX/XX/XX/XX/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
```

```
> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.XXX@6.2.0+6020010_6020010 FAILED
  DEBUG   2023-02-16 16:08:59.803274 +01:00 sentry-cli version: 1.74.4, platform: "darwin", architecture: "x86_64"
  INFO    2023-02-16 16:08:59.805530 +01:00 sentry-cli was invoked with the following command line: "/XX/XX/XX/XX/XX/XX/XX/XX/node_modules/@sentry/cli/sentry-cli" "react-native" "gradle" "--bundle" "/XX/XX/XX/XX/XX/XX/XX/XX/android/app/build/ASSETS/createBundleReleaseJsAndAssets/index.android.bundle" "--sourcemap" "/XX/XX/XX/XX/XX/XX/XX/XX/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map" "--release" "XX@6.2.0+6020010" "--dist" "6020010"
error: An organization slug is required (provide with --org)
  DEBUG   2023-02-16 16:08:59.807464 +01:00 skipping update nagger because session is not attended
```

Also, my sentry-staging(/prduction).properties is well defined with defaults.url, defaults.org, defaults.project and auth.token

**Expected result:**

App should build

**Comment by krystofwoldrich** [comment]
If the `sentryProperties` file specified in `project.ext.sentryCli` is picked up by the `sentry.gradle` you should see it in the logs.

Example:
```
Using 'sentry.properties' at: /absolute/path/to/the/sentry.gradle
```

As you, @Akeuuh, mentioned in discord the properties file was not loaded because the `project.ext.sentryCli` must be defined before `apply from "path/to/sentry.gradle"`.
