### ISSUE TITLE
recursion limit hit

### ISSUE THREAD

**Issue by vtoupet** [getsentry/sentry-react-native#285]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.7.0
5.5.1
SmartMixin@0.0.1 /Users/vincent/Documents/workspace/smartmixin/mobile
├── apisauce@0.13.0
├── format-json@1.0.3
├── geopoint@1.0.1
├── http-status-codes@1.3.0
├── jwt-decode@2.2.0
├── moment-range@3.0.3
├── moment-timezone@0.5.13
├── prop-types@15.5.10
├── querystringify@1.0.0
├── ramda@0.23.0
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
├── react-native@0.44.3
├── react-native-billing@2.4.0
├── react-native-code-push@2.1.0-beta
├── react-native-device-info@0.12.1
├── react-native-elements@0.17.0
├── react-native-fbsdk@0.6.1
├── react-native-google-analytics-bridge@5.3.3
├── react-native-i18n@1.0.0
├── react-native-in-app-utils@6.0.0
├── react-native-keyboard-aware-scroll-view@0.3.0
├── react-native-loading-spinner-overlay@0.5.2
├── react-native-maps@0.16.4
├── react-native-modal@4.0.0
├── react-native-orientation@1.17.0 invalid
├── react-native-safari-view@2.1.0
├── react-native-sentry@0.21.2
├── react-native-slider@0.11.0
├── react-native-snap-carousel@3.3.3
├── UNMET PEER DEPENDENCY react-native-vector-icons@4.1.1
├── react-native-webview-android@1.1.11
├── react-navigation@1.0.0-beta.15
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-persist@4.10.0
├── redux-saga@0.15.6
├── reduxsauce@0.4.1
├── reselect@3.0.1
├── seamless-immutable@7.1.2
└── string-raw@1.0.1
```

---
my sentry additional data is truncated like below (it did not happen in the past with same recursive level)

```
{
account: {
last_updated: 1509095522, 
thermostats: [
<recursion limit hit>, 
<recursion limit hit>
]
}, 
chartParams: {
period: day
}, 
connected: True, 
connectionDate: 1504688318, 
shouldSelectorOpen: False
}
```

Is there a way to remove this limit or set it to a higher level?

**Comment by HazAT** [comment]
Can you link to one of these event please?

**Comment by vincejah** [comment]
@HazAT https://sentry.io/vincent-toupet/smartmixin-mobile/issues/393497081/events/8464743902/

**Comment by vincejah** [comment]
@HazAT  any news about that issue?

**Comment by HazAT** [comment]
Hey, sorry it was so quiet around this.
We had a discussion over here https://github.com/getsentry/raven-js/issues/623
not sure where the `<recursion limit hit>` is coming from though.
So short answer there will not be a quick fix for this so I will close it for now.
I will post an answer here as soon as we support it.

**Comment by ywongweb** [comment]
Encountered the same `<recursion limit hit>` message when sending in additional data with 3+ nested levels.

RN: 0.51.0
react-native-sentry: 0.33.0

**Comment by humphriest** [comment]
@HazAT Is there any progression on this issue? Is there a workaround with raven or something else?

**Comment by cpetzel** [comment]
any update on this?

**Comment by humphriest** [comment]
Has a solution been found yet for this?

**Comment by wikka** [comment]
I'm having the same problem and it is affecting the debug of critical issues in an App we are developing.
Does anyone have a recommendation of how to deal with it while it is not fixed?

**Comment by askielboe** [comment]
Same issue when adding redux state to breadcrumbs. 3rd level values are all `recursion limit hit`.

Only seen this on Android so far.

**Comment by abdourahimjallow** [comment]
Any new

**Comment by laurentrivard** [comment]
bump... ? hitting the same limit

**Comment by faizalshap** [comment]
Same here...

**Comment by iagorm** [comment]
same here, <recursion limit hit> is showing on a catch error validation from JOI with sub level object.

**Comment by Danman7** [comment]
Same here...

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
