### ISSUE TITLE
Breadcrumbs in native iOS code are discarded

### ISSUE THREAD

**Issue by RussellNortonArmstrong** [getsentry/sentry-react-native#2850]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.11^

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://hoverinc.sentry.io/issues/2586388726/?query=is%3Aunresolved+no+uri&referrer=issue-stream&statsPeriod=14d)

**Configuration:**

```
  Sentry.init({
    release: version,
    dsn: 'https://7b47224686f74bf08de451b2234f2d96@o291490.ingest.sentry.io/5202064',
    environment: RNInfo.scheme,
    autoSessionTracking: true, // Turn on Release Health
    attachScreenshot: true,
    integrations: [
      new Sentry.ReactNativeTracing({
        routingInstrumentation: new Sentry.ReactNativeNavigationInstrumentation(
          dependencies.NavigationWrapper.Navigation,
        ),
      }),
    ],
    autoInitializeNativeSdk: Platform.OS === 'android' ? false : true, // We natively init Android
  });
```

---
**I have following issue:**
We have a native camera module (iOS Swift) where we have added breadcrumbs.
If a crash occurs in the native code, the breadcrumbs are attached to the crash.
If a crash occurs in JS code after returning from the camera module, no breadcrumbs are present from iOS code.

After breadcrumbs are added to sentry by the native camera code, when JS sends and error to sentry, the sdk crumb are lost.

```
 WARN  ===== error ==== Error taking photo, no uri generated by SDK

 ERROR  Sentry Logger [error]: Error while sending event: [Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
The react native bridge sends messages to JS with JSON of the following format”

[[131,52],[7,0],[[4846,100,1674168221009,false]],19821]]

```
The error being thrown is due to RNSentry.captureEnvelope sending empty parameters. There is only one set of parameters in the third element.

**Comment by krystofwoldrich** [comment]
Synchronizing breadcrumbs from iOS to RN was added in [SDK v5](https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0).

How does it relate to the second error? What are the steps to replicate the second error? There is [an issue](https://github.com/getsentry/sentry-react-native/issues/2744) about it but we weren't able to replicate it.

**Comment by RussellNortonArmstrong** [comment]
What does "Synchronizing breadcrumbs from iOS to RN"? Is that a possible workaround?

**Comment by krystofwoldrich** [comment]
It means that breadcrumbs that are created by `sentry-cocoa` in `obj-c` are added to the JS event.
 
 If you upgrade to https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0 you will see the native breadcrumbs in your JS events.
