### ISSUE TITLE
Script '/redacted/node_modules/@sentry/react-native/sentry.gradle' line: 287

### ISSUE THREAD

**Issue by only1chi** [getsentry/sentry-react-native#2854]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.71.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

The sentry.gradle file is not correctly referencing `hermesEnabled` setting when using RN 0.71.2. 
Line 287 of `sentry.gradle` fails with with this line:
```
def enableHermes = project.ext.react.get("enableHermes", false);
```

It needs to be updated as follows:
```
def enableHermes = project.ext.react.hermesEnabled;
```

**Actual result:**

```
BUILD FAILED in 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/Users/chizurokechikwendu/Desktop/Git_Repo/cma/node_modules/@sentry/react-native/sentry.gradle' line: 287

* What went wrong:
Operation is not supported for read-only collection

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
**Steps to reproduce:**
- Build app React Native 0.71.2 with newArchitecture disabled
- update gradle.properties as follows:
   - newArchEnabled=false
   - hermesEnabled=true

**Expected result:**

[Expected result]

**Comment by krystofwoldrich** [comment]
The line `sentry.gradle:287` is only executed if the old `apply from: "../../node_modules/react-native/react.gradle"` is used.

To use the new properties `hermesEnabled=true` you need to enabled the new `React Native Gradle Plugin` and remove `react.gradle` from your `android/app/build.gradle`.

More detail in prev issue:
- https://github.com/getsentry/sentry-react-native/issues/2819#issuecomment-1427704365

**Comment by only1chi** [comment]
Thank you!
