### ISSUE TITLE
Better support XCode Cloud

### ISSUE THREAD

**Issue by hstaudacher** [getsentry/sentry-react-native#2856]
We are using building a react-native app using [XCode Cloud](https://developer.apple.com/xcode-cloud/). I have integrate sentry as described in the docs. Errors are getting reported but there were no source maps. I have spent a lot of time figuring out what is going on.

In XCode Cloud the `CFBundleVersion` is not used as a build number. Instead XCode Cloud defines a variable called [`CI_BUILD_NUMBER`](https://developer.apple.com/documentation/xcode/environment-variable-reference) which is managed by the service. The result of this is that new releases are going to be created but the source maps are uploaded to the release with defined with the `CFBundleVersion`. In our case this version was `1` which means every build uploaded the source maps to e.g. `1 (1)`. 

I have a fix for this which is adding this line:
```sh
export SENTRY_DIST=$CI_BUILD_NUMBER
```
to the `Bundle React Native code and images` build phase. This leads sentry to upload the sourcemaps to the correct release.

It would be very nice to better support this build environment and e.g. prefer `CI_BUILD_NUMBER` over `CFBundleVersion` if present.

**Comment by krystofwoldrich** [comment]
Thank you for the idea and also for the fix.

**Comment by krystofwoldrich** [comment]
We are currently working on a new way of uploading source maps that doesn't rely on releases. 

- https://github.com/getsentry/sentry-react-native/issues/2892

In meantime, you can use the mentioned workaround.
