### ISSUE TITLE
Support for two or more projects in the same app

### ISSUE THREAD

**Issue by helgifeiti** [getsentry/sentry-react-native#2857]
### Description

Is there a way to have two or more Sentry projects connected to the same app? Seems like `sentry.properties `only assumes one project.

**Comment by krystofwoldrich** [comment]
Hi is not possible at the moment. Could you describe your use case in more detail?

**Comment by helgifeiti** [comment]
I am developing a React Native SDK, which will be imported as a dependency in various apps. I wanted to have one Sentry project connected to the SDK so I could keep a track of errors for everyone using the SDK. But I would also like the client setting up the app to be able to have their own Sentry project set up connected to the app. 

From what I've found, I need to initialise the Sentry client on the app-level for it to work (not inside the SDK) so I would need to be able to either initialise two clients or initialise one client connected to two projects. 
Does that make sense? Is there any other way I could achieve this?

**Comment by krystofwoldrich** [comment]
@helgifeiti Our SDK is created for App monitoring only, we don't support library monitoring. 

I believe that none of the described approaches would work.

**Comment by helgifeiti** [comment]
@krystofwoldrich OK, thank you.
