### ISSUE TITLE
npx @sentry/wizard  unable to find index file

### ISSUE THREAD

**Issue by MetaBenji** [getsentry/sentry-react-native#2870]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.1.0

**`react-native` version:** 0.67.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: Config.SENTRY_ENV,
})
```

---
**I have following issue:**

I received the following output from my terminal when running `npx @sentry/wizard -i reactNative -p ios android`

```
✅ Patched build.gradle file.
🚨 Could not find index.android.@(j|t|cj|mj)s?(x) nor App.@(j|t|cj|mj)s?(x) files.
❓ Please, visit https://docs.sentry.io/platforms/react-native
✅ Added sentry.properties file to android
Successfully set up android for react-native
✅ Patched build script in Xcode project.
🚨 Could not find index.ios.@(j|t|cj|mj)s?(x) nor App.@(j|t|cj|mj)s?(x) files.
❓ Please, visit https://docs.sentry.io/platforms/react-native
✅ Added sentry.properties file to ios
Successfully set up ios for react-native

🎉  Successfully set up Sentry for your project 🎉
```

I've looked through the [manual setup steps ](https://docs.sentry.io/platforms/react-native/manual-setup/) and I don't see anywhere that lists this step.  I've also looked through the troubleshooting steps and searched the repo's Github issues section

What impact is this having on my sentry project?  

**Steps to reproduce:**
- My React Native app is inside an Nx monorepo 
- I navigated to the folder where my react native app lives 
- I ran `npx @sentry/wizard -i reactNative -p ios android`
- I received the output above

Note: my index file is located in a `src` folder.   Could this be causing the issue?

**Actual result:**

The entry point to my project was not found

**Expected result:**

The entry point would be found

**Comment by krystofwoldrich** [comment]
Hi,
if `index.{platform}.{postfix}` or `App.{postfix}` is not found the `Sentry.init()` is not added.

You will need to manually do this https://docs.sentry.io/platforms/react-native/#initialize.

What does the path to your `index.{platform}.{postfix}` or `App.{postfix}` look like, for example, `src/App.js` is supported.

**Comment by MetaBenji** [comment]
@krystofwoldrich thanks so much for the quick response!

Here are the locations of my two files: 
1. `src/index.tsx`
2. `App.tsx` is located in a separate library as I'm using a monorepo.  

I manually added `Sentry.init()` to `index.tsx` so it's the first function called as I see in the docs it should be called as early as possible.  Is that the correct place to call it?

**Comment by krystofwoldrich** [comment]
@MetaBenji Yes, that is a good place to put it.
