### ISSUE TITLE
Sentry not part of release pipeline source map error

### ISSUE THREAD

**Issue by Alecattie** [getsentry/sentry-react-native#2871]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.6.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://miniso-lj.sentry.io/share/issue/04c719eaa78c432b9a034f0c904c02aa/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

I am not being able to read source maps because of an issue where it says: 

We've encountered 1 problem un-minifying your applications source code!

Sentry not part of release pipeline

[Read Guide](https://docs.sentry.io/platforms/react-native/sourcemaps/#uploading-source-maps-to-sentry)
Integrate Sentry into your release pipeline using a tool like Webpack or the CLI. Your release must match what's set in your Sentry.init. The value for this event is mx.com.miniso.app@1.7.56+165.

Basically I uploaded the source maps using sentry CLI with the following script

```#!/bin/bash
export SENTRY_ORG=xxxx
export SENTRY_PROJECT=xxxx
export SENTRY_TOKEN=xxxxxxx

RELEASE_NAME_PREFIX=$(cat android/app/build.gradle | grep -o "applicationId \".*" | cut -d " " -f 2 | sed -e "s/\"//g")
RELEASE_NAME=$(cat android/app/build.gradle | grep -o "versionName \".*" | cut -d " " -f 2 | sed -e "s/\"//g")
DISTRIBUTION_NAME=$(cat android/app/build.gradle | grep -o "versionCode .*" | cut -d " " -f 2)


node_modules/.bin/react-native bundle \
    --dev true \
    --platform android \
    --entry-file index.js \
    --bundle-output index.android.bundle \
    --sourcemap-output index.android.bundle.packager.map
    --minify true
    --reset-cache


node_modules/hermes-engine/osx-bin/hermesc -O -emit-binary -output-source-map -out=index.android.bundle.hbc index.android.bundle
rm -f index.android.bundle
mv index.android.bundle.hbc index.android.bundle
node node_modules/react-native/scripts/compose-source-maps.js index.android.bundle.packager.map index.android.bundle.hbc.map -o index.android.bundle.map


sentry-cli --auth-token ${SENTRY_TOKEN} \
    releases \
    files "mx.com.miniso.app@${RELEASE_NAME}+${DISTRIBUTION_NAME}" \
    upload-sourcemaps \
    --strip-prefix /Users/alecattie/Desktop/Main/miniso-mexico/ \
    --dist ${DISTRIBUTION_NAME} \
    index.android.bundle.map index.android.bundle index.android.bundle-plain.map
    
sentry-cli releases finalize "mx.com.miniso.app@${RELEASE_NAME}+${DISTRIBUTION_NAME}"
```

running sentry-cli sourcemaps explain says they should be working fine.

**Steps to reproduce:**
- Run the above script using the command line on a sentry app

[Actual result]

<img width="1150" alt="Screenshot 2023-03-04 at 7 55 28 PM" src="https://user-images.githubusercontent.com/16178867/222937438-eeca689e-238b-40d7-94f1-d4736d18a90e.png">

<img width="1140" alt="Screenshot 2023-03-04 at 7 56 09 PM" src="https://user-images.githubusercontent.com/16178867/222937451-15c5b138-c92a-4407-bc88-38954527c09b.png">

[Expected result]

To be able to read the source maps without the error and unminified

**Comment by krystofwoldrich** [comment]
Hi,
could you try to build the bundle with `dev=false` and `minify=false`? 

```
node_modules/.bin/react-native bundle \
    --dev false \
    --platform android \
    --entry-file index.js \
    --bundle-output index.android.bundle \
    --sourcemap-output index.android.bundle.packager.map
    --minify false
    --reset-cache
```

The source maps are used for release builds in dev builds the symbolication is done on the device. RN 0.63 [doesn't minify](https://github.dev/facebook/react-native/blob/cfc4d196a947329309e29c08d44967b31220393b/react.gradle#L170) release builds by default.

**Comment by parth-koshta** [comment]
@Alecattie Were you able to resolve this?

**Comment by Alecattie** [comment]
> Hi,
> 
> could you try to build the bundle with `dev=false` and `minify=false`? 
> 
> 
> 
> ```
> 
> node_modules/.bin/react-native bundle \
> 
>     --dev false \
> 
>     --platform android \
> 
>     --entry-file index.js \
> 
>     --bundle-output index.android.bundle \
> 
>     --sourcemap-output index.android.bundle.packager.map
> 
>     --minify false
> 
>     --reset-cache
> 
> ```
> 
> 
> 
> The source maps are used for release builds in dev builds the symbolication is done on the device. RN 0.63 [doesn't minify](https://github.dev/facebook/react-native/blob/cfc4d196a947329309e29c08d44967b31220393b/react.gradle#L170) release builds by default.

Thanks for the response. I will try this and let you know

**Comment by Alecattie** [comment]
> @Alecattie Were you able to resolve this?
> 
> 

I haven't tried. But I will let you know
