### ISSUE TITLE
Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available

### ISSUE THREAD

**Issue by humarkx** [getsentry/sentry-react-native#2883]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.1.0

**`react-native` version:** 0.71.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**If you are using sentry.io, please post a link to your issue so we can take a look:**
Could not determine the dependencies of task ':@sentry_react-native:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':@sentry_react-native:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :@sentry_react-native

**Comment by krystofwoldrich** [comment]
Hi,
what version of our RN SDK are you using, the issue mentions `8.2.0` but our latest version is `5.1.0`?

**Comment by humarkx** [comment]
Updated to 5.1.0, just copied the version `Installing Sentry (8.2.0)` from pod install

**Comment by krystofwoldrich** [comment]
Ohh, got it. Thanks.

Did you also upgrade RN version or just our sdk?

**Comment by humarkx** [comment]
I am running everything latest releases

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the information, sadly we can't reproduce the issue.

Could you provide a minimal reproducible example with detailed steps on how you build the app?
