### ISSUE TITLE
Extend Device Context with CPU info

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-react-native#2884]
Our [device context docs](https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context) describe a few new CPU related fields which are not provided by the mobile SDKs yet.

- `processor_count`
- `cpu_description`
- `processor_frequency`

Need to write the native parts to get the data (or reproduce from https://github.com/getsentry/sentry-java/issues/2561 and https://github.com/getsentry/sentry-cocoa/issues/2740).

**Comment by krystofwoldrich** [comment]
Types are already present in JS SDK so RN can use them right away.
- https://github.com/getsentry/sentry-javascript/blob/2aa4e94b036675245290596884959e06dcced044/packages/types/src/context.ts#L49

**Comment by krystofwoldrich** [comment]
@philipphofmann @brustolin Is there a `sentry-cocoa` release coming soon so we can unblock this?

- https://github.com/getsentry/sentry-cocoa/pull/2855
