### ISSUE TITLE
Sentry RN increases projects build size significantly 

### ISSUE THREAD

**Issue by cseelus** [getsentry/sentry-react-native#2885]
**Platform:**
- [x]  iOS
- [x]  Android
- [x]  Web

I just gave it a try, but adding almost 0.5 Megabytes just for error logging is not really great, especially if one (also) has to build for web.

**Comment by krystofwoldrich** [comment]
Hi, thank you for the comment,
we officially do not support `react-native-web`, but the SDK might work with it.

For mobile apps, we feel like the current size is not too large, but we are aware of it and would like to make the SDK smaller should we support the web too.

Try our JS SDK for the web, it's much smaller (tens of KB).

https://github.com/getsentry/sentry-javascript

**Comment by cseelus** [comment]
@krystofwoldrich thanks for sharing your plans in making the RN-SDK smaller.

Looking forward to it, since it generally works great with `react-native-web` and building for native + web with React Native got much more decent since the release of [Expo Router](https://expo.github.io/router/docs/).

Since in this particular project, native and web builds are created from the same codebase, the Sentry JS SDK for web is not an option here currently.
