### ISSUE TITLE
options for `enableCaptureFailedRequests`

### ISSUE THREAD

**Issue by mym0404** [getsentry/sentry-react-native#2890]
[docs](https://docs.sentry.io/platforms/apple/guides/ios/configuration/http-client-errors/?utm_source=stanislavstankov.com&utm_medium=website&utm_campaign=home_page_link&utm_id=ss_home_page_link)
It seems to `enableCaptureFailedRequests` option emerged from `8.0.0` iOS (`5.0.0` in this package).

I wan't to turn off network failed request error about sentry.

Is there any option to adjust it in current package version?

**Comment by krystofwoldrich** [comment]
Hi, currently you would need to manually initialize the iOS SDK to turn this feature off.
The steps are described [here in docs](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/).

[We already have an issue, and we are tracking this issue.](https://github.com/getsentry/sentry-react-native/issues/2882)

**Comment by markholland** [comment]
@krystofwoldrich  Could you be clear that in a future release of this package we will be able to disable this new default iOS behaviour from React Native?

**Comment by krystofwoldrich** [comment]
@markholland Yes, in a future release, you will be able to disable this default iOS behavior from RN.

To track the progress follow this issue -> https://github.com/getsentry/sentry-react-native/issues/2882
