### ISSUE TITLE
Check if all breaking changes from v5 are reflected in the docs.

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2894]
### Description

Simple task to go thru the https://docs.sentry.io/platforms/react-native/migration/#from-4x-to-5x changes and check if they are up to date across the RN docs.

Changes in https://github.com/getsentry/sentry-docs

**Comment by lucas-zimerman** [comment]
All the breaking changes are reflected on the documentation so I am closing this issue.
