### ISSUE TITLE
Support Android Gradle Plugin 8.0 / Android Studio Flamingo

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#2899]
Currently there is an error when building with AGP 8.0.0-beta05.
Since it will be stable soon, it would be nice to have support for it so we can use the beta version testing for other possible problems.

```* What went wrong:
A problem occurred configuring project ':@sentry_react-native'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
     
     android {
         namespace 'com.example.namespace'
     }
```

**Comment by krystofwoldrich** [comment]
Thanks for the heads-up.

**Comment by krystofwoldrich** [comment]
I see [`7.3.1` in the 0.71 branch](https://github.dev/facebook/react-native/blob/1d22e291462ac452f2bb6b1b6af11986944ec54a/packages/react-native-gradle-plugin/build.gradle.kts#L36).

**Comment by marandaneto** [comment]
Lets try to find a fix and make it back-compatible if possible.

**Comment by krystofwoldrich** [comment]
@pvegh Thanks for the update.

**Comment by pvegh** [comment]
Looks like it was fixed in https://github.com/getsentry/sentry-react-native/releases/tag/5.7.0
Is that true?
We would then plan for the upgrade (enterprise project and sentry-paying customer, not the just quickly updating kind)

**Comment by krystofwoldrich** [comment]
@pvegh Yes, https://github.com/getsentry/sentry-react-native/releases/tag/5.7.0 fixed this.
