### ISSUE TITLE
[5.1.x] Source code was not found

### ISSUE THREAD

**Issue by AlexanderEggers** [getsentry/sentry-react-native#2901]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.1.1

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: env.SENTRY_DNS,
  debug: __DEV__,
  environment: env.SENTRY_ENV,
  enabled: !__DEV__,
  tracesSampleRate: 0.2,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation: SENTRY_ROUTING_INTRUMENTATION,
    }),
  ],
  attachStacktrace: true,
  attachScreenshot: false,
});
```

---
**I have following issue:**

Related to #2879. When reporting any new issues to Sentry, each issue contains the warning "Source code was not found". Downgrading to 5.0.0 or earlier solves the issue for me.

**Steps to reproduce:**
- Use sentry 5.1.1 in your project
- Produce a javascript exception
- Search for the relevant error on Sentry.io which will contain the relevant error.

**Actual result:**

- Source code was not found.
- Inability to inspect the full javascript error due to the missing source maps.

**Expected result:**

No errors.

**Comment by krystofwoldrich** [comment]
Hi, thank you for the info, could you share the issue with us? 

Could you verify that source maps are uploaded in the correct release? (Release Details -> Source Maps artifacts)

**Comment by AlexanderEggers** [comment]
@krystofwoldrich The source maps seem to be uploaded correctly. I cannot see any differences.

How should I share a sample issue you? If you need the URL, can I share that in a private chat somewhere?

**Comment by krystofwoldrich** [comment]
@AlexanderEggers Yes, I meant the URL, you can send me a DM on our discord.

https://discord.gg/sentry

**Comment by AlexanderEggers** [comment]
@krystofwoldrich I had another look at our project setup. After changing our root index file from being a .tsx to .js, the source maps were processed correctly again. I have no idea why that would make a difference..

But I actually noticed a different issue which is on ios around the debug information file. On 4.x these are correctly uploaded but on 5.x these are not included. I will create a new issue for that and link an issue of the sentry ios sdk which I believe might be related to that.
