### ISSUE TITLE
Unity SDK & React Native SDK Conflict

### ISSUE THREAD

**Issue by MetaBenji** [getsentry/sentry-react-native#2902]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** @sentry/react-native 5.1.1
**Sentry Unity version:** 1.0.0

**`react-native` version:**  0.67.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

I'm not sure what to write here.  I don't think it applies to this specific issue

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

I'm using the Unity SDK and React Native SDK.  I managed to get iOS to work, however I'm getting a duplicate class error when trying to run Android.

Here is a screenshot

![image](https://user-images.githubusercontent.com/101577156/226038886-2faa4704-9e2c-4070-a0cc-e90ef952b419.png)

I saw the [other github issue that was opened previously](https://github.com/getsentry/sentry-react-native/issues/2749) and I already have de-selected `Android Native Support` as you can see from the screenshot below.  I actually don't have sentry enabled in unity right now.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/101577156/226041082-0648deb3-170c-4748-ac77-29dbfc6f1c10.png">

We love using sentry on web and would like to use it for all our platforms!  Any suggestions how we can get this to work?

**Actual result:**

Android app won't build

**Expected result:**

Android app builds successfully

**Comment by krystofwoldrich** [comment]
Hi, I suppose turning the native support off in unity and clean-building the app doesn't solve the issue. 

We have not tested combining these two SDKs, would you be able to share what your project structure looks like? Or even share an example app?

**Comment by MetaBenji** [comment]
Native support was already turned off.  When you say clean building the app, what specifically do you mean?

As for project structure, we have a Unity application.  We build the Android unity library and us it in our React Native app using [react-native-unity-view](https://github.com/asmadsen/react-native-unity-view)

It's all in an Nx mono repo.  Is that what you were looking for about project structure?  If not, let me know so I can provide as many details as possible!

It may be difficult to get an example app

**Comment by krystofwoldrich** [comment]
By clean build, I mean this:
```bash
./gradlew clean
rm -rf app/build
```

Just to ensure none of the previous build artifacts are used.

By the project structure I meant how you integrate Unity with RN, link to [react-native-unity-view](https://github.com/asmadsen/react-native-unity-view) helps a lot, thank you.

I see there is [an example app](https://github.com/asmadsen/react-native-unity-view/tree/master/example) in [react-native-unity-view](https://github.com/asmadsen/react-native-unity-view), when you add both of the SDKs to it, do you run into the same issue?

**Comment by bitsandfoxes** [comment]
I'll have to make some changes to the Unity SDK. This surfaced some issues in the way we embed the native plugins even with the SDK or the specific native support disabled.
When this was first built, the use case of the Unity game being embedded in another app was not taken into consideration.
iOS is being addressed here https://github.com/getsentry/sentry-unity/pull/1233
Android will follow.

**Comment by krystofwoldrich** [comment]
The fix was released in https://github.com/getsentry/sentry-unity/releases/tag/1.2.0 therefore I will close this issue. If this is still an issue feel free to comment here and we can reopen it.
