### ISSUE TITLE
SentryNetworkTrackingIntegration throws HttpClientError status 590 with code 1001

### ISSUE THREAD

**Issue by NorbertSanpruch** [getsentry/sentry-react-native#2919]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.1.0

**`react-native` version:** 0.68.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

(`@sentry/react-native`)
```
Sentry.init({
  environment: ENVIRONMENT,
  tracesSampleRate: 0.2,
  dsn: dns,
  normalizeDepth: 5,
});
```

---
**I have the following issue:**

I get a couple of crashes on iOS

```
[HTTPClientError __57+[SentryNetworkTrackingIntegration swizzleURLSessionTask]_block_invoke_2.27]
in Sentry/Sources/Sentry/SentryNetworkTrackingIntegration.m
HTTP Client Error with status code: 590
```

in error json details there's

```
"response": {
"cookies": "...",
"headers": {
...
"x-ac-error": "Code 1001",
},
"status_code": 590,
"type": "response"
},
```
![Zrzut ekranu 2023-03-23 o 16 01 28](https://user-images.githubusercontent.com/119671073/227244964-14bf67db-c750-4649-841d-e2f9c0c5e44d.png)

**Actual result:**

Sentry tracking integration throw errors

**Expected result:**

No errors reported

**Comment by krystofwoldrich** [comment]
Hi,
these don't look like crashes but captured errors from failed HTTP requests.

More in the docs: https://docs.sentry.io/platforms/apple/guides/tvos/configuration/http-client-errors/
This feature is on by default on iOS. Currently to turn it off [manually initializing](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) the iOS SDK is required.
