### ISSUE TITLE
Sentry causes crashes on Android when a thrown error is a String type

### ISSUE THREAD

**Issue by evan1715** [getsentry/sentry-react-native#2934]
**OS:**
Not applicable (N/A)

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^5.1.1

**`react-native` version:** ^0.71.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue](https://poolconnect-llc.sentry.io/issues/3699254836/?project=1728288)]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({ dsn: 'https://...@sentry.io/...' });
```

---
**I have following issue:**

If the thrown issue inside a try-catch is of the type String, Sentry creates a crash on Android devices. It seems that Sentry is expecting an object (map) type. When it does not receive that, it crashes the app. This has been witnessed numerous times in multiple versions of react-native and sentry. 
I have done multiple things to mitigate it, but it creeps up again sometimes. It can be triggered in multiple ways, including through Sentry.setContext(). It does not need to be through setContext, and can be seen just by throwing an exception as a string. 
For example, if I've used:
Sentry.setContext('functionName', typeof error === 'string' ? JSON.parse(error) : error);

**Steps to reproduce:**
- Step 1: In a try-catch, call throw without the Error class such as: throw 'MsgString'; on Android with Sentry active. This will throw an exception to the catch as a string type. It might be useful to also check other types such as numbers to ensure it doesn't continue to crash.

**Actual result:**
Crash.

**Expected result:**
Not a crash.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and the details.

Based on the step to reproduce I've tried this code and the error was sent to sentry without a crash. Please let me know if the code represents what you had in mind or share your sample.
```
try {
  throw 'Captured exception string';
} catch (e) {
  Sentry.setContext('functionName', { error: JSON.stringify(e) });
  Sentry.captureException(e);
}
```

The example you mentioned `Sentry.setContext('functionName', typeof error === 'string' ? JSON.parse(error) : error);` throws an error during `JSON.parse`, this error is then captured and sent to Sentry.
I would recommend wrapping the `JSON.parse` in `try-catch`.

**Comment by evan1715** [comment]
>Steps to reproduce:
>
 >   Step 1: In a try-catch, call throw without the Error class such as: throw 'MsgString'; on Android with Sentry active. This will throw an exception to the catch as a string type. It might be useful to also check other types such as numbers to ensure it doesn't continue to crash.
```
const someFunction = async () => {
    try {
        throw 'stringed message';
    } catch (error) {
        return error;
    }
};
someFunction();
```

in your attempt, it's more so a scenario of not knowing what the return from a response might be:
```
const someFetchCall = async () => {
    try {
        const response = JSON.stringify{ body: 'some fetch call'};
        throw response;
    } catch (error) {
        Sentry.setContext('someFetchCall', error);
    }
}
someFetchCall();
```

**Comment by evan1715** [comment]
when throw new Error(''); is there, it'll throw it properly since it's an object into Sentry.setContext('', error);
when throwing an exception string, throw 'Aborted'; Sentry.setContext('', error); crashes in java because the error is a string and not an object. forcing an object of Sentry.setContext('', { error: error }); would likely mean that throw new Error(''); would create a scenario of nested errors { error: { error: { message: '', code: '' }}}. i guess i can force the object in it like yours has.

**Comment by krystofwoldrich** [comment]
This looks good `Sentry.setContext('', typeof error === 'string' ? { error } : { ...error });`. 
The [`setContext`](https://docs.sentry.io/platforms/javascript/guides/nextjs/enriching-events/context/#structured-context) accepts only objects, so wrapping the string is necessary.

Could you describe the use case when you set `Sentry.setContext('contextKey', error);` and not `Sentry.captureException( error)`, as the later function accepts anything and correctly handles the case you describe.

**Comment by evan1715** [comment]
for now, i'm just going to remove the context calls. thank you for your help.
