### ISSUE TITLE
[Mac Catalyst] Build issues in a React Native project with Sentry

### ISSUE THREAD

**Issue by birdofpreyru** [getsentry/sentry-react-native#2944]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Mac Catalyst

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.0

**`react-native` version:** 0.71.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**
Irrelevant.

---
**I have following issue:**

I am trying to build an existing (_i.e._ it builds & works fine for iOS target) React Native project with Sentry for Mac Catalyst. The build results in a few errors in Sentry SDK's Objective-C code, which I believe should be patched as the following:

https://github.com/getsentry/sentry-react-native/blob/acadc0f974a0c234a3d9010117b076792d14d6e8/ios/RNSentry.mm#L111
should become
```objective-c
BOOL enableNativeCrashHandling = [mutableOptions valueForKey:@"enableNativeCrashHandling"] != nil;
```
and here:
https://github.com/getsentry/sentry-react-native/blob/acadc0f974a0c234a3d9010117b076792d14d6e8/ios/RNSentry.mm#L122
should become
```objective-c
BOOL enableAutoPerformanceTracing = [mutableOptions valueForKey:@"enableAutoPerformanceTracing"] != nil;
```

Otherwise compiler gives me this error in both places:
> _Cast from pointer to smaller type 'BOOL' (aka 'signed char') loses information_

~I can create a PR later if these look right for you, or probably you'll be faster just to do these corrections yourself :)~

I have submitted PR #2945 

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

[Actual result]

**Expected result:**

[Expected result]

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the issue and PR. There is already an existing PR for this issue.

- https://github.com/getsentry/sentry-react-native/pull/2936
