### ISSUE TITLE
HTTP error response logs show value [Object] in "Headers" key

### ISSUE THREAD

**Issue by bpeltonc** [getsentry/sentry-react-native#2953]
**OS:**
- [x]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 3.1.1

**`react-native` version:** 0.66.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[https://share-one-inc.sentry.io/issues/3451527184/?project=6004509&query=is%3Aunresolved&referrer=issue-stream&stream_index=0]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: SENTRY_DSN,
      environment: __DEV__ ? 'development' : 'production',
      enableAutoSessionTracking: AUTO_SESSION_TRACKING,
      sessionTrackingIntervalMillis: SESSION_TRACKING_INTERVAL_MS,
      integrations: [
        new Sentry.ReactNativeTracing({
          tracingOrigins: ORIGINS,
          routingInstrumentation,
        }),
      ],
      tracesSampleRate: SAMPLE_RATE,
    });
```

---
**I have following issue:**

Some values are not serialized in response logs, preventing me from debugging effectively.

**Steps to reproduce:**
- Server sends 4xx or 5xx response code
- Sentry logs an HTTP error response

**Actual result:**

Sentry shows error logs with some values not serialized. All I can see is the value '[Object]' for some keys in the log.

**Expected result:**

Sentry serializes all values and I can see all the JSON data contained in error logs.

**Comment by krystofwoldrich** [comment]
Hi, could you try this with the latest version of the SDK, we [introduced HTTP Client Errors integration](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#httpclient) where the headers should be processed correctly.

Example in our sample app [here](https://github.com/getsentry/sentry-react-native/blob/b1a6c2edc1c94b90e1934c145ae96f65c768e6bf/sample-new-architecture/src/App.tsx#L58).

**Comment by bpeltonc** [comment]
@krystofwoldrich Thanks for your reply. I'm troubleshooting some errors in migrating to the latest version, but will respond with whether the issue is fixed once I resolve them.

**Comment by krystofwoldrich** [comment]
I'll close this for now, and when you get back to it, feel free to comment here. And if it's still an issue we can open it and solve it.
