### ISSUE TITLE
iOS crash on launch after upgrade to 5.3.0

### ISSUE THREAD

**Issue by bpeltonc** [getsentry/sentry-react-native#2956]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.0

**`react-native` version:** 0.66.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: SENTRY_DSN,
      environment: __DEV__ ? 'development' : 'production',
      enableAutoSessionTracking: AUTO_SESSION_TRACKING,
      sessionTrackingIntervalMillis: SESSION_TRACKING_INTERVAL_MS,
      integrations: [
        new Sentry.ReactNativeTracing({
          tracingOrigins: ORIGINS,
          routingInstrumentation,
        }),
      ],
      tracesSampleRate: SAMPLE_RATE,
    });
});
```
---
**I have following issue:**

After following the migration guide to upgrade my previous 3.1.x version to 5.3.0, iOS builds are crashing both in debug and release builds. Android is working fine, it appears. With a debug build, I get a log in my console as follows: "Native Client is not available, can't start on native." I tried including `enableNative: false` in my config, but still got the same result.

**Steps to reproduce:**
- Upgrade from 3.1.1 to 5.3.0
- Create debug build

**Actual result:**

Crash on app start

**Expected result:**

App works with no crash

**Comment by krystofwoldrich** [comment]
Hi,
could you check if sentry CocoaPod is installed correctly? You should see `RNSentry (5.3.0)` and `Sentry/HybridSDK (8.3.3)` in your `Podfile.lock`.

Do you see any other errors, running the app directly from Xcode could help to see more iOS logs and stack trace of the crash.

Just for context, I'm linking the original issue and the reason why you are upgrading.
- https://github.com/getsentry/sentry-react-native/issues/2953

**Comment by krystofwoldrich** [comment]
@bpeltonc Did you manage to get your project working? Or still, facing the same issue?

**Comment by krystofwoldrich** [comment]
@bpeltonc Okay, thank you for the update, I will close this for now, and when you get back to it, comment here and we can reopen it.

**Comment by krystofwoldrich** [comment]
We have found out what the issue was, and here is a fix. https://github.com/getsentry/sentry-react-native/pull/2980

When it's released Sentry will be in the Pods. If you want to use the v5 now you can [link RNSentry manually](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#linking-the-native-library-via-cocoapods).
