### ISSUE TITLE
`axios` HTTP tracing

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2961]
### Description

https://www.npmjs.com/package/axios
https://www.npmjs.com/package/ky

Maybe both work OOTB with the `fetch/xhr` integration, but I am not sure if it's as rich as we'd get with first-class support.

**Comment by krystofwoldrich** [comment]
`ky` uses fetch so the support should be as goog as possible.
`axios` needs more investigation.

**Comment by krystofwoldrich** [comment]
Update I've tested `axios` and it's also fully supported by our `xhr` integration.
