### ISSUE TITLE
Task :app:bundleProductionReleaseJsAndAssets_SentryUpload failed: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by supmanyu** [getsentry/sentry-react-native#2970]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.1

**`react-native` version:** 0.64.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

We recently purchased a paid plan for sentry.io, and since then we have been unable to create android builds using fastlane, SSL verification fails everytime with `error: API request failed
  caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: Couldn't understand the server certificate format)
`

**Steps to reproduce:**
- Step 1: Run the above gradle task

**Actual result:**

Build fails after `Adding source map references` with `error: API request failed
  caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: Couldn't understand the server certificate format)
`

**Expected result:**

Build should succeed after uploading sourcemaps to sentry.

**Fixes tried**:

1. Upgrading to the latest version of `@sentry/react-native`
2. Adding `http.verify_ssl = false` to `sentry.properties` file
3. Generating a new auth token

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message,

could you try to run [`sentry-cli` source maps upload manually](https://docs.sentry.io/platforms/react-native/sourcemaps/#3-upload-the-bundle-and-source-maps)? Just so we can isolate the issue if it's related to RN and Fastlane or to the cli.

**Comment by theahmadzai** [comment]
I'm facing the same issue here is the gradle build scan https://scans.gradle.com/s/kjhvw6x2nrvuq

**Comment by theahmadzai** [comment]
I was able to upload manually 
![image](https://user-images.githubusercontent.com/9446563/233226320-f0e81766-9015-430e-b5f5-166957834890.png)
with following commands 
```
npx react-native bundle --dev false --platform android --entry-file index.js --reset-cache --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map
npx sentry-cli releases files com.tryperdiem.wh@2.4.1+231 upload-sourcemaps --dist 231 --strip-prefix C:/Users/theah/github/perdieminc/white-label index.android.bundle index.android.bundle.map
```

**Comment by krystofwoldrich** [comment]
@theahmadzai Thank you for the details, look at the log, your issue seems to be different from the original.

It looks like the CLI binary didn't download `C:\\Users\\theah\\Desktop\\perdiem\\node_modules\\@sentry\\cli\\sentry-cli.exe`.

Could you try to reinstall your packages or only the `@sentry/cli`? 
You can try to execute `C:\\Users\\theah\\Desktop\\perdiem\\node_modules\\@sentry\\cli\\scripts\\install.js` to download the binary.

**Comment by theahmadzai** [comment]
@krystofwoldrich thank you for your reply, Just noticed we had --ignore-scripts flag in our CI due to which scripts were getting ignored. it's working now thank you so much

**Comment by krystofwoldrich** [comment]
@supmanyu Any updates on the original error?

**Comment by supmanyu** [comment]
I tried building the app on a colleague's device, as well as on the CI and also manually uploading sourcemaps from CLI. All three scenarios worked fine, so i re-setup the project again from scratch, which seems to have resolved the problem. We can close this issue for now, I'll update here if I'm able to recreate it again.

**Comment by krystofwoldrich** [comment]
Okay, thanks for the update, we appreciate it. Happy to hear it works now.

**Comment by xiongxiongjiang** [comment]
in react native 0.73.4
> Adding http.verify_ssl = false to sentry.properties file

can help

**Comment by rafaelsoncineduobox** [comment]
Any news?

`"react-native": "0.73.6",`

**Comment by krystofwoldrich** [comment]
@rafaelsoncineduobox We were not able to reproduce the issue and some of the user confirmed the upload is working.

If you are running into similar error please open a new issue with the up to date information.
