### ISSUE TITLE
NSInvalidArgumentException -[NSTaggedPointerString sentry_sanitize]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by OskarAtJoint** [getsentry/sentry-react-native#2973]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0) 5.3.0
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise
---
**I have following issue:**

Sentry native crash if data is not a "record"
eg:
Sentry.addBreadcrumb({ data: 123 })
@sentry/react-native 5.3.0

OK its not valid type but it shouldnt crash!
it works in eg 4.2.3 (no crash)

**Steps to reproduce:**
Do Sentry.addBreadcrumb({ data: 123 })

**Actual result:**

2023-04-17 13:50:06.847799+0200 app[36380:3420582] -[__NSCFNumber sentry_sanitize]: unrecognized selector sent to instance 0xb6db535c86b9f994
2023-04-17 13:50:06.869393+0200 app[36380:3420582] [native] Exception '-[__NSCFNumber sentry_sanitize]: unrecognized selector sent to instance 0xb6db535c86b9f994' was thrown while invoking addBreadcrumb on target RNSentry with params (
        {
        data = 123;
        level = info;
        timestamp = "1681732206.23";
    }
)

**Expected result:**

No crash!

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, 

yes, I agree, it's a wrong type but we should not crash on it.
