### ISSUE TITLE
Add ignoreTransactions and ignoreErrors

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-react-native#2974]
### Background:
To further simplfiy ignoring certain events from being sent to sentry, it is also suggested to provide `ignoreTransactions` and `ignoreErrors`

More info here develop docs updated: https://develop.sentry.dev/sdk/features/#event-sampling

- [x] ignoreErrors
- [x] ignoreTransactions
- [ ] SDK docs

**Comment by kahest** [comment]
> @kahest i put this in mobile project but i don't know all your statuses let me know if we need to discuss more, it is being tracked on a meta issue
> 
> [getsentry/team-webplatform-meta#46](https://github.com/getsentry/team-webplatform-meta/issues/46)

🙏  I created a mobile meta-issue on team-mobile: https://github.com/getsentry/team-mobile/issues/108

**Comment by krystofwoldrich** [comment]
RN Docs here: https://docs.sentry.io/platforms/react-native/configuration/options/#ignore-errors
RN has both options from the JS SDK.
