### ISSUE TITLE
Using Code Push along with enableNative set to false does not send errors from sdk.

### ISSUE THREAD

**Issue by shubhamdeol** [getsentry/sentry-react-native#2998]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.9.0

**`react-native` version:** 0.68.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'xyz',
  enableNative: false,
  // other options
});
```
---
**I have following issue:**

I want to initialise the sdk on native side as soon as the App starts. Sometimes crash occurs when javascript is not initialized. To fix this I am following [this](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) doc. 

In MainActivity

```
protected void onCreate(Bundle savedInstanceState) {
    SentryAndroid.init(this, options -> {
      options.setDsn("xyz");
      options.setEnvironment("nativeAndroid");
    });
      super.onCreate(null);
  }
```
**Steps to reproduce:**
- Step 1: I added `System.out.println(2/0);` after `SentryAndroid.init` and successfully received the trace on sentry dashboard. 
- Step 2: I removed the `System.out.println(2/0);` from MainActivity and put logs inside javascript side using methods
  Sentry.nativeCrash() and throw new Error("Test Error")

**Actual result:**

 when followed step 2. I was not able to see error on dashboard. 
 using debug flag logs error on console
 `Sentry Logger [warn]: Event was skipped as native SDK is not enabled.`

**Expected result:**

errors triggered by Sentry.nativeCrash() and throw new Error("Test Error")
should be successfully reported to sentry Dashboard. 

Related issue: https://github.com/getsentry/sentry-react-native/issues/2006
closed because person who reported this issue turned  `enableNative` to true which I can not do. Because I want to get errors on sentry even before js initialization.

**Comment by krystofwoldrich** [comment]
Thank you for the message,
I think in your case you should [use `autoInitializeNativeSdk: false` in the options](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) as you are initializing the native SDKs manually. 

`enableNative: false` is intended for cases when you don't want to/can't use native at all (browse for example).

**Comment by krystofwoldrich** [comment]
If `autoInitializeNativeSdk: false` the RN JS SDK will send breadcrumbs to the native layers, so if a native error occurs JS breadcrumbs will be present.

Is that your desired behavior?

**Comment by shubhamdeol** [comment]
closing the issue. Getting desired behavior with  ```autoInitializeNativeSdk: false```

**Comment by krystofwoldrich** [comment]
Happy to help.
