### ISSUE TITLE
Latest version (5.3.1) does not compile under react-native-macos

### ISSUE THREAD

**Issue by ospfranco** [getsentry/sentry-react-native#3000]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [X]  MacOS

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native-macos` version:** 0.71.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

The latest version of the library does not compile under MacOS **for** MacOS. I've created the following patch:

```patch
diff --git a/node_modules/@sentry/react-native/.DS_Store b/node_modules/@sentry/react-native/.DS_Store
new file mode 100644
index 0000000..36d39ae
Binary files /dev/null and b/node_modules/@sentry/react-native/.DS_Store differ
diff --git a/node_modules/@sentry/react-native/ios/RNSentry.mm b/node_modules/@sentry/react-native/ios/RNSentry.mm
index 78b0a24..d5a75e3 100644
--- a/node_modules/@sentry/react-native/ios/RNSentry.mm
+++ b/node_modules/@sentry/react-native/ios/RNSentry.mm
@@ -311,6 +311,8 @@ RCT_EXPORT_METHOD(captureEnvelope:(NSArray * _Nonnull)bytes
     resolve(@YES);
 }
 
+#if SENTRY_HAS_UIKIT
+
 RCT_EXPORT_METHOD(captureScreenshot: (RCTPromiseResolveBlock)resolve
                   rejecter: (RCTPromiseRejectBlock)reject)
 {
@@ -354,6 +356,8 @@ RCT_EXPORT_METHOD(fetchViewHierarchy: (RCTPromiseResolveBlock)resolve
     resolve(viewHierarchy);
 }
 
+#endif
+
 RCT_EXPORT_METHOD(setUser:(NSDictionary *)userKeys
                   otherUserKeys:(NSDictionary *)userDataKeys
 )
```

**Comment by krystofwoldrich** [comment]
Hi, thank you for the info, the fix looks good.

Would you be willing to open a PR with the mentioned fix?

**Comment by ospfranco** [comment]
Hey, little time right now to fork the repo and apply the changes? can't you do it, it's a two line change :)

**Comment by krystofwoldrich** [comment]
@ospfranco Of course, no problem, just wanted to check if you are not interested.
