### ISSUE TITLE
[Android] Source map reference not found

### ISSUE THREAD

**Issue by joarkosberg** [getsentry/sentry-react-native#3010]
**OS:**
- [x]  Linux

**Platform:**
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.3.1

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

**Configuration:**

(`build.gradle`)
```
project.ext.sentryCli = [
    logLevel: "debug",
    collectModulesScript: "../../../node_modules/@sentry/react-native/dist/js/tools/collectModules.js",
    modulesPaths: [
      "../../node_modules",
      "../../../node_modules",
    ],
]
```

---
**I have following issue:**

Following upgrade to version `5.3.1` source maps are not found for android builds.
The upload works as it should (from what I see), but there seems to be some trouble in reference between source and maps.

Uploading with this version the result says `no sourcemap ref`:
```
[12:02:44]: ▸ Source Map Upload Report
[12:02:44]: ▸ Minified Scripts
[12:02:44]: ▸ ~/index.android.bundle (no sourcemap ref)
[12:02:44]: ▸ Source Maps
[12:02:44]: ▸ ~/index.android.bundle.map
```

While with previous versions like 5.3.0 where it has been working it says it is found:
```
[08:20:22]: ▸ Source Map Upload Report
[08:20:22]: ▸ Minified Scripts
[08:20:22]: ▸ ~/index.android.bundle (sourcemap at index.android.bundle.map)
[08:20:22]: ▸ Source Maps
[08:20:22]: ▸ ~/index.android.bundle.map
```

**Steps to reproduce:**
- The prerequisite for me is using version `5.3.1`, if it is the only one for this bug, not sure.

**Comment by krystofwoldrich** [comment]
This will be fixed in the next RN SDK release, you can fix it now by manually upgrading `sentry-cli`.

```
yarn add @sentry/cli@latest
```

**Comment by joarkosberg** [comment]
@krystofwoldrich Nice, thanks :-)
