### ISSUE TITLE
Compile macOS sample during CI to avoid regression

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#3012]
### Description

We technically [do not support](https://github.com/getsentry/sentry-react-native/issues/1813) RN macOS yet automatically.
But there's nothing blocking people to do themselves.
We should add a bare bones macOS sample that compiles on CI to avoid issues such as https://github.com/getsentry/sentry-react-native/pull/3007

**Comment by marandaneto** [comment]
Related https://github.com/getsentry/sentry-react-native/issues/1813

**Comment by krystofwoldrich** [comment]
Added in https://github.com/getsentry/sentry-react-native/pull/3785
