### ISSUE TITLE
SDK with `enableNative: true` falls back to JS if native is not available  

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3027]
### Description

At the moment RN SDK throws an error when `enableNative: true` with Expo Go, to make DEX better we should not enforceNative but only warn about the situation and use JS as a fallback.

This is especially an improvement for Expo users and `react-native-web` users.

~~We add `forceNative` flag to keep the original behavior for users who want it.~~

**Comment by marandaneto** [comment]
Let's just flip `enableNative` if it's not Android, iOS, and macOS, where the Native SDKs are not available anyway.
