### ISSUE TITLE
Artifact Bundles in React Native

### ISSUE THREAD

**Issue by peterlazar1993** [getsentry/sentry-react-native#3037]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.4.0

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://limehome.sentry.io/issues/4121058060/events/1728e2a5a5eb44629cf7880178ee6878/)

**Configuration:**

```
Sentry.init({
        dsn: EnvironmentProps.SENTRY_DSN,
        environment: EnvironmentProps.ENVIRONMENT,
        tracesSampleRate: 0.5,
        integrations: [
          new Sentry.ReactNativeTracing({
            routingInstrumentation: this.routingInstrumentation,
          }),
        ],
      });
```

---
**I have following issue:**

<img width="912" alt="Screenshot 2023-05-03 at 14 21 56" src="https://user-images.githubusercontent.com/4848554/235914316-b781a2e2-8523-43f3-a84f-36e08e009e31.png">

I see the error in the screenshot above. I checked the source maps settings and I found that for the past two releases there are no `Release Bundles` uploaded, instead there are `Artifact Bundles`. I could not find any information on how `Artifact Bundles` work with React Native(Hermes) so I am unsure on how to get the source maps working again.

This behaviour appeared from SDK 5.2.0

**Actual result:**

Source maps do not work

**Expected result:**

Source maps work

**Comment by krystofwoldrich** [comment]
Hi,
the issue is that by `release` and `dist` we should be able to identify the correct bundle and source map, but you are using the same `release`+`dist` for both iOS and Android bundles.

Could you use a different `dist` for your Android and iOS builds?

If you can't do that at the moment, you can install an older version of the CLI `yarn add @sentry/cli@2.14.4` which will upload the artifacts the old way.

Let us know if this works for you.

**Comment by peterlazar1993** [comment]
@krystofwoldrich 
Gotcha. Setting `@sentry/cli` to 2.14.4 uploaded artefacts the old way indeed.

I will report back with the results of setting a unique `dist` soon.

**Comment by peterlazar1993** [comment]
@krystofwoldrich So I was able to set the `SENTRY_DIST` and `SENTRY_RELEASE`  env vars and also set the same value in `Sentry.init`. And this seems to work as expected.

I need to release a `staging` and `development` build from the same commit and looks like both the `Artifact Bundles` have the same `Bundle ID` and seems to clobber the previous upload.

### Expected
| Bundle ID | Dist | Release |
|--------|--------|--------|
| bundle-id-1 | 33-android | com.limehome.app.development@0.0.1+33-android |
| bundle-id-2 | 33-android | com.limehome.app.staging@0.0.1+33-android |

### Actual
| Bundle ID | Dist | Release |
|--------|--------|--------|
| bundle-id-1 | 33-android | com.limehome.app.development@0.0.1+33-android |

**Comment by peterlazar1993** [comment]
Moreover digging deeper into [`Artifact Bundles`](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/#3-inject-debug-ids-into-artifacts) I tried to look for `debug_id` field in the source map and it doesn't exist.
I don't think it's being injected in the `sourcemap`/`source file` at all by default.

**Comment by krystofwoldrich** [comment]
The debug_ids do not support Hermes bundles yet, so they are not injected. But the association with the release is used instead.

When I suggested different dist I had in mind `33-ios`, `33-android` but with the same release for example `com.limehome.app.development@0.0.1+33`. The way you did it your app has now a separate release for Android and ios, which can be, I just wanted to note it in case it was not your intention.

You are right, the `Bundle ID` is deterministic, but it's strange that your `dev` and `staging` build have the same bundle. At a minimum, the release string that is passed to `Sentry.init` should be different.

**Comment by peterlazar1993** [comment]
@krystofwoldrich I think it makes sense that my `dev` and `staging` bundles are the same since I derived the `release` and `dist` dynamically

```
const dist = `${nativeBuildVersion}+${Platform.OS}`;
const release = `${applicationId}-${nativeApplicationVersion}-${dist}`;
```

`applicationId`, `nativeBuildVersion`, `nativeApplicationVersion` are all resolved from the native layer at runtime using [expo-application](https://docs.expo.dev/versions/latest/sdk/application/)

I now derive `dist` and `release` like so:

```
const dist = `${nativeBuildVersion}+${Platform.OS}`;
const release = `${nativeApplicationVersion}-${dist}`;
```
since my bundles are the same across environments for a particular build, and also set the same values during the build stage as `env` vars.

___

I think you can close this issue now. I think you should also consider making `release` and `dist` mandatory so that users won't shoot themselves in the foot like I did, then again, maybe I missed something in the docs.

**Comment by markholland** [comment]
So is my understanding correct that Sentry no longer supports automatic source map uploading for React Native?

This has started affecting us since April 28th where suddenly the release bundles tab has the warning "No bundle connected to this release" for all new releases.

I don't understand why I'd need to start setting release and diff manually when we aren't using custom values. React Native docs for Sentry haven't changed regarding uploading source maps.

Also why has this started happening without us changing our Sentry version?
- @sentry/react-native: 5.3.0

**Comment by peterlazar1993** [comment]
@markholland From what I saw, it still supports automatic source map uploads.

To associate source map to a release you need to:

1. set the `release` and `dist` values in Sentry.init
2. set the same `release` and `dist` values while uploading the source map

By default sentry  does `1` [here](https://github.com/getsentry/sentry-react-native/blob/58c699554ad349a9a541e2860d1b3d012e79a71c/src/js/integrations/release.ts#L49C1-L61) and 2 [here](https://github.com/getsentry/sentry-react-native/blob/58c699554ad349a9a541e2860d1b3d012e79a71c/sentry.gradle#L254-L257) + [here](https://github.com/getsentry/sentry-react-native/blob/58c699554ad349a9a541e2860d1b3d012e79a71c/sentry.gradle#L144-L148)

So everything should work as earlier. I think you should start by looking at the `release` and `dist` values for your builds and see if there's a corresponding artefact in here `https://<TEAM>sentry.io/settings/projects/<PROJECT>/source-maps/artifact-bundles/`

In my case, the source map artefact for develop build was being overwritten by the artefact for the staging build since both of them had the same bundle and in turn sentry derived the same artefact id for both releases, rightfully so.

**Comment by krystofwoldrich** [comment]
@markholland Could you describe your situation? We do support automatic source map uploading, the docs are still up to date.

We are currently in the process of switching from Release Bundles to Artifact Bundles. As long as you see Artifacts Bundles linked to your releases everything should work as before.

**Comment by markholland** [comment]
@krystofwoldrich We had a crash on a line of Javascript so the same bug on both iOS and Android. But it appears in Sentry as separate issues for each platform and the line of javascript highlighted by Sentry for Android is incorrect. Before we would have expected a single issue in Sentry for any Javascript problems.

**Comment by krystofwoldrich** [comment]
@markholland Could you open a new issue and share there what your releases look like and if they do have artifacts?
