### ISSUE TITLE
[Android] Split APKs can only find one source map

### ISSUE THREAD

**Issue by joarkosberg** [getsentry/sentry-react-native#3046]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.0

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
        init({
            dsn: Config.SENTRY_DSN,
            environment: Config.ENV,
            enableAutoPerformanceTracing: false,
        });
```

---
**I have following issue:**

Since the end of April our release bundles has had warning `No bundle connected to this release` and date uploaded `(no value)`. And new uploads has started turning up under Artifact bundles. 
![Screenshot 2023-05-05 at 16 13 46](https://user-images.githubusercontent.com/9250267/236482810-ec5d8fa8-c952-4d9b-9f21-056eb7799adb.png)

Everything has worked fine for iOS, but on Android it has not worked as expected.

On android we do APK splitting to four architectures and sentry has uploaded source maps per architecture. The log from the android build command logs that all uploads are successful like before. But when I look in Sentry I can only find the last source maps that where uploaded. So source maps works for the last architecture, but none other. 

This then results in source maps only working for 1/4 of the error events on android for us. 

This change happened without doing a upgrade of the npm package. 

**Actual result:**

Only one source map is found.

**Expected result:**

Source maps for all architectures.

**Comment by krystofwoldrich** [comment]
Hi @joarkosberg,
thank you for the message, we are currently transitioning to the new artifacts bundles, and the UI lacks behind a bit, but we are working on it.

As long as there are artifacts bundles linked to your releases symbolication should work as before.

To solve why only the latest Android upload gets symbolicated can you share how does your release name look like and what you choose as dist?

The recommended structure would be release: `{app.package.name}@{app.version}` dist: `{build.number.ios}`, `{build.number.android}-{arch}`. `dist` is used to find the correct source map to symbolicate a stack trace. If your iOS and Android build numbers are different there is no need for a platform post-fix. For Android please include the architecture in the `dist`.

**Comment by joarkosberg** [comment]
@krystofwoldrich 
Thanks for getting back to me :-) 

Per now we have let Sentry do the relase/dist automatically both for creating source maps and initialising in TS. If I look at release log it sends --release: `{app.package.name}@{app.version}+{build.number}` and --dist: `{build:number}`. Where `app.package.name` is different for ios/android and `build.number` is different per arch (and ios/android).

Just to be sure, to follow your suggestion, would be to add android architecture to dist, in addition to unique build number? Both in source map creation then and in initialising in TS?

**Comment by krystofwoldrich** [comment]
@joarkosberg If the `build.number` is different for ios/android and per arch, then there is no need to change anything. As you will get the same result as with my suggestion, meaning different dist for ios/android and per arch.

Could you check one of the Android issues that is not symbolicated and check the release that is sent in that issue, does the release have an artifact bundle linked to it?  You should see a link to the artifacts on the Release page.

**Comment by joarkosberg** [comment]
So did a test release, here is the findings: 

Doing a release (done around 15:39)
* 1 Release can be found under releases for Android with 0 Artifacts connected
  * Same release can be found under release bundles with nothing connected
* 1 artifact bundles can be found for iOS but no releases 

After triggering an error on iOS and Android
* iOS now can be found under releases, connected to the previously mentioned artifact bundle. So stack trace is working.
* Android now has 1 new release found, oddly with created timestamp before release was done, timestamp is at exactly 15:00. But no artifact bundles connected (and I cant find it manually). So stack trace does not work.

Sample android upload end log: 
```
[13:36:47]: ▸ > Bundled 2 files for upload
[13:36:47]: ▸ > Bundle ID: id
[13:36:48]: ▸ > Uploaded files to Sentry
[13:36:48]: ▸ > File upload complete (processing pending on server)
[13:36:48]: ▸ > Organization: org
[13:36:48]: ▸ > Project: mobile-app
[13:36:48]: ▸ > Release: app@803706+843706000
[13:36:48]: ▸ > Dist: 843706000
[13:36:48]: ▸ > Upload type: artifact bundle
[13:36:48]: ▸ Source Map Upload Report
[13:36:48]: ▸ Minified Scripts
[13:36:48]: ▸ ~/index.android.bundle (sourcemap at index.android.bundle.map)
[13:36:48]: ▸ Source Maps
[13:36:48]: ▸ ~/index.android.bundle.map
```

**Comment by krystofwoldrich** [comment]
@joarkosberg This test release, was it a test project you could share a link to?

**Comment by joarkosberg** [comment]
> @joarkosberg This test release, was it a test project you could share a link to?

Just another pipeline for creating test versions of the same project.  
I can try to recreate it a new project that I can share, I'll post a comment here after trying 🙂 

Just a note that we downgraded to 5.0.0 for now, which works like before with releases.

**Comment by krystofwoldrich** [comment]
@joarkosberg Thank you the project would help a lot.

In case you would like to use the newest fixes and features, you can temporarily fix the `cli` version `yarn add @sentry/cli@2.14.4` so the artifacts are uploaded as Release Bundles.

**Comment by krystofwoldrich** [comment]
@joarkosberg Hi, have you managed to recreate the issue an a new project?

**Comment by joarkosberg** [comment]
> @joarkosberg Hi, have you managed to recreate the issue in a new project?

Hi! 
Sorry I have taken a long time on getting back on this. I'll try to prioritise some time on it next week.

**Comment by krystofwoldrich** [comment]
Thank you for the update.

**Comment by krystofwoldrich** [comment]
@joarkosberg Hi, are you still experiencing the issue?

In [this comment](https://github.com/getsentry/sentry-react-native/issues/3046#issuecomment-1538429832) you mentioned an example from the build, do you see this upload log for all the android architectures?

**Comment by krystofwoldrich** [comment]
@joarkosberg I'll close the issue for now, as we can reproduce it and when you get back to it, feel free to comment here so we can reopen it.

**Comment by joarkosberg** [comment]
@krystofwoldrich 

Sorry for my slow responses, I used a bit of time on this now and found the issue when trying to reproduce it, and fixed it.
Firstly UI of Sentry.io has become a bit easier to use also now for this 😄 

I upgraded to latest, which might did something. And I had some leftover sentry config in `settings.gradle` and `build.gradle`., the automatic config has not worked well with the current project, so I have used the manual setup page https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/ , which have said to add info there. While when I tried with a new project, the auto setup did not add it. So I cleaned up a bit, and now it works :-) Connecting one release to all 4 apks.

**Comment by joarkosberg** [comment]
> @joarkosberg Thank you, awesome to hear. What command you used to execute the auto config -> @sentry/wizard?
> 
> Can you check `npx @sentry/wizard --version`?

I have in general gone with the one mentioned in the docs, so dont remember the exact one used before, but looking at the docs now it is `npx @sentry/wizard@latest -s -i reactNative`, so I am guessing thats the one 😄 

Current wizard version is `2.4.0`, which I used when trying to reproduce in a fresh project.

**Comment by krystofwoldrich** [comment]
@joarkosberg The latest version of the wizard is https://github.com/getsentry/sentry-wizard/releases/tag/v3.6.0. Between the version you have and the latest, ve changed the way the `build.gradle` is updated by the Wizard. Likely that fixes also your issue.

**Comment by joarkosberg** [comment]
> @joarkosberg The latest version of the wizard is https://github.com/getsentry/sentry-wizard/releases/tag/v3.6.0. Between the version you have and the latest, ve changed the way the `build.gradle` is updated by the Wizard. Likely that fixes also your issue.

Awesome, will make sure to use an updated version with future updates.
Thanks 😊
