### ISSUE TITLE
A required debug information file was missing.

### ISSUE THREAD

**Issue by markholland** [getsentry/sentry-react-native#3059]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.0

**`react-native` version:** 0.70.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

- https://catenda-as.sentry.io/share/issue/ff2fb2ba67ac43f5b9bcc7d0088b0290/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  maxValueLength: 1024
});
```

---
**I have following issue:**

Issues created from errors reported from native iOS code show warning that debug file is missing for `OurAppName.app`.
This started when the switch to Artifact bundles happened.

**Steps to reproduce:**
- Log an error to sentry from native iOS code.

**Actual result:**

- Issue created on Sentry.io reports `A required debug information file was missing.`

**Expected result:**

- Only optional debug information files to be missing.

**Comment by krystofwoldrich** [comment]
Are you using the `Upload Debug Symbols to Sentry` build phase to upload your iOS App symbols or are you uploading them by `sentry-cli` manually?

If you are using the build phase can you update it like follow and share its output?

```
SENTRY_CLI="../node_modules/@sentry/cli/bin/sentry-cli"
FLAGS="--force-foreground"
"$SENTRY_CLI" debug-files upload $FLAGS $DWARF_DSYM_FOLDER_PATH
```

**Comment by markholland** [comment]
Output of modified build phase when archiving.
```
INFO    2023-05-10 15:32:59.712685 +02:00 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
> Found 0 debug information files
> No debug information files found
> No new debug symbols to associate.
```

**Comment by krystofwoldrich** [comment]
Can you check if the debug symbols were created? You can just search the build log for `dSYM`.

**Comment by krystofwoldrich** [comment]
Okay, we upload sSYMs from `$DWARF_DSYM_FOLDER_PATH`, 

Is `Catenda\ Site.app.dSYM` in the `$DWARF_DSYM_FOLDER_PATH`?

You can check the env value by `xcodebuild -project your-project.xcodeproj -showBuildSettings`.

**Comment by markholland** [comment]
The value of `$DWARF_DSYM_FOLDER_PATH` is 

```
/Users/my-user/Library/Developer/Xcode/DerivedData/Catenda_Site-hbcknjdwtfnhdjfzrzklnyjbbyfr/Build/Products/Release-iphoneos
```
This directory does not exist.

From the Xcode build step output the dSYM file is located at:

```
/Library/Developer/Xcode/DerivedData/Catenda_Site-giynhywnizwqefgjxsvoialuiuty/Build/Intermediates.noindex/ArchiveIntermediates/Catenda\ Site/BuildProductsPath/Release-iphoneos/
```

**Comment by krystofwoldrich** [comment]
`$TEMP_ROOT` should be `Intermediates.noindex` so you can add the to the build phase.

Or you can upload the symbols manually https://docs.sentry.io/platforms/apple/dsym/#sentry-cli

**Comment by markholland** [comment]
I've amended your original build phase suggestion to:

```
SENTRY_CLI="../node_modules/@sentry/cli/bin/sentry-cli"
FLAGS="--force-foreground"
"$SENTRY_CLI" debug-files upload $FLAGS $TEMP_ROOT
```
But it still gives the same result
```
INFO    2023-05-11 11:57:37.723562 +02:00 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
> Found 0 debug information files
> No debug information files found
> No new debug symbols to associate.
```

I also tried providing the entire path in case it wasn't finding it recursively to where the dSYM is located but with the same result.

**Comment by markholland** [comment]
So I logged $TEMP_ROOT from the build phase itself and it has a different path than the one provided by `xcodebuild -project your-project.xcodeproj -showBuildSettings`

It is instead

```
/Users/my-user/Library/Developer/Xcode/DerivedData/Catenda_Site-giynhywnizwqefgjxsvoialuiuty/Build/Intermediates.noindex/ArchiveIntermediates/Catenda Site/IntermediateBuildFilesPath
```

which is one level nested deeper than where it would find the dSYM recursively so it makes sense that it wouldn't find them.

**Comment by markholland** [comment]
I used [this](https://stackoverflow.com/a/66853116/1450638) answer to get all of the actual environment variables available during build phase.

`$BUILD_ROOT` feels like a good candidate with value:
```
/Users/my-user/Library/Developer/Xcode/DerivedData/Catenda_Site-giynhywnizwqefgjxsvoialuiuty/Build/Intermediates.noindex/ArchiveIntermediates/Catenda Site/BuildProductsPath
```

So a resulting build phase with:

```
SENTRY_CLI="../node_modules/@sentry/cli/bin/sentry-cli"
FLAGS="--force-foreground"
"$SENTRY_CLI" debug-files upload $FLAGS "$BUILD_ROOT"
```

Appears to do the job but my question now is surely this is something that Sentry should be managing? or at least it has been until now as our build phase until today was simply:

```
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

**Comment by markholland** [comment]
I am off for the next two weeks but will follow up any replies once I'm back.

**Comment by krystofwoldrich** [comment]
In `sentry-cli@1` we automatically used [`DWARF_DSYM_FOLDER_PATH` env](https://github.com/getsentry/sentry-cli/blob/7a51f9d195bcd210e74935dc94c3d60e414c0238/src/commands/upload_dif.rs#L227), but since `sentry-cli@2` the path to the debug symbols needs to be supplied by the user.

I wonder why there are no symbols in the `DWARF_DSYM_FOLDER_PATH` in your case? Could you compare running Release build and running the archive?

**Comment by markholland** [comment]
`$DWARF_DSYM_FOLDER_PATH` appears to be a valid value when doing a release build with Xcode.
