### ISSUE TITLE
Missing filter for `beforeSendTransaction` on Native Layer 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-react-native#3069]
```
    const { beforeSend, beforeBreadcrumb, integrations, ...filteredOptions } = options;
    /* eslint-enable @typescript-eslint/unbound-method,@typescript-eslint/no-unused-vars */
    const nativeIsReady = await RNSentry.initNativeSdk(filteredOptions);
```
The current filter on the wrapper only applies for `beforeSend` but doesn't filter the `beforeSendTransaction`. We should filter in order to avoid issues with the Native SDK on iOS

# Proposed Solution

a function that receives the React Native options, and return a new object that only contains the valid objects, this avoids users adding custom parameters to the options and the same being sent to the Native Layer, but also prevents that new parameters doesn't get added automatically to the Native layer.

**Comment by krystofwoldrich** [comment]
iOS doesn't have the `beforeSendTransaction` so this is not causing issues at the moment, but could in the future.
