### ISSUE TITLE
How to disable Consecutive HTTP errors?

### ISSUE THREAD

**Issue by Bardiamist** [getsentry/sentry-react-native#3072]
How to disable [Consecutive HTTP](https://docs.sentry.io/product/issues/issue-details/performance-issues/consecutive-http/)?

I don't need to collect this information

**Comment by Bardiamist** [comment]
@krystofwoldrich 
>Is there a specific reason why you don't want to collect the information? Is it not actionable?

API which I use required `Consecutive HTTP`

Now same situation happened with Android. I receiving many `Consecutive HTTP` reports from androids with `@sentry/react-native@5.6.0`

**Comment by Bardiamist** [comment]
I see it should be fixed in 5.7.0

**Comment by krystofwoldrich** [comment]
We haven't made any changes regarding `Consecutive HTTP` in the SDK. Can you be more specific?

**Comment by Bardiamist** [comment]
@krystofwoldrich 
As I see:

@sentry/react-native@5.6.0 uses Android SDK 6.22.0 where performance enabled

@sentry/react-native@5.7.0 uses Android SDK 6.25.0
In Android SDK 6.25.0 Performance is disabled by default again https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md#6250

I don't want to receive `Consecutive HTTP`, is it right that @sentry/react-native@5.7.0 and later will not send `Consecutive HTTP`?
