### ISSUE TITLE
Source maps working only with dev build

### ISSUE THREAD

**Issue by Arcus16** [getsentry/sentry-react-native#3073]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.14.0

**`react-native` version:** 0.70.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Source maps working](https://customink.sentry.io/issues/4185075831/events/7771682e863f43b4af8ab9ab64250ddb/?project=4504638845747200)
[Source maps not working](https://customink.sentry.io/issues/4186757117/?environment=staging&project=4504638845747200&query=is%3Aunresolved&referrer=issue-stream&stream_index=2)

**Configuration:**

(`@sentry/react-native`)
```
export const routingInstrumentation = new Sentry.ReactNavigationInstrumentation({});

Sentry.init({
    dsn: Config.SENTRY_DSN,
    environment: Config.APP_ENV,
    tracesSampleRate: 1.0,
    integrations: [
        new Sentry.ReactNativeTracing({
            routingInstrumentation,
        }),
    ],
});
```

---
**I have following issue:**

I followed [this](https://docs.sentry.io/platforms/react-native/sourcemaps/) guide to upload source maps to sentry. The source maps work when the error is sent from the app in dev mode, but when the error is received from the app built for release, the source maps are not working.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and the links,
are the source maps not working for both Android and iOS release builds?

How do you enable source maps in your iOS builds, using `EXTRA_PACKAGER_ARGS` or [`SOURCEMAP_FILE`](https://reactnative.dev/docs/sourcemaps#enable-source-maps-on-ios)?

**Comment by Arcus16** [comment]
Hi,
Yes, source maps are not working for both platforms, for Android in dev env. [working](https://customink.sentry.io/issues/4185075831/?environment=development&project=4504638845747200&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) , but [here](https://customink.sentry.io/issues/4186841140/?environment=staging&project=4504638845747200&query=is%3Aunresolved&referrer=issue-stream&stream_index=1) the released version and they do not.

> How do you enable source maps in your iOS builds, using EXTRA_PACKAGER_ARGS or [SOURCEMAP_FILE](https://reactnative.dev/docs/sourcemaps#enable-source-maps-on-ios)?

Looking at the document again, I somehow skipped/forgot about this :( .

**Comment by Arcus16** [comment]
Hi,
From the last time, I updated the `@sentry/react-native` to version 5.5.0 and `@sentry/cli` to version  2.18.1.

Now, when I send the error from a simulator, the sourcemaps are working, but I see [this error in sentry](https://customink.sentry.io/issues/4185075831/events/fa7f6e22184f4110996d95b169ffa427/?project=4504638845747200).
```
Integrate Sentry into your release pipeline using a tool like Webpack or the CLI. Your release must match what's set in your Sentry.init. The value for this event is ...
```
I am unsure why I get this error because I checked it, and the `release` variable sent with each event has the same value as `release` I used to upload source maps. Or am I missing something?

**Comment by krystofwoldrich** [comment]
Hi,
the [issue](https://customink.sentry.io/issues/4185075831/events/fa7f6e22184f4110996d95b169ffa427/?project=4504638845747200) is from dev environment. That's symbolicated on the simulator. To verify if the source maps are working can you try to build a release version of your app and send the error?

**Comment by krystofwoldrich** [comment]
Awesome to hear, the second error is issue tracked [here](https://github.com/getsentry/sentry-react-native/issues/3097). So I will close this now. In case of any other issues, we can reopen this one or create a new one.
