### ISSUE TITLE
Migrate from Node 12/14 to 16

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#3083]
### Description

https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

**Comment by krystofwoldrich** [comment]
RN CI already used node 16

https://github.com/search?q=node-version+repo%3Agetsentry%2Fsentry-react-native&type=code&ref=advsearch

**Comment by marandaneto** [comment]
@krystofwoldrich https://github.com/getsentry/sentry-react-native/blob/b92b976dbe856cde3e4bd202e5ffe8af133cbc74/sample-new-architecture/_node-version#L1
You also have to double-check GH action plugins etc, when I created this, I saw a few warnings, are they gone?

**Comment by krystofwoldrich** [comment]
I've updated the sample and also double-checked the logs but I've not seen any warning now. 

https://github.com/getsentry/sentry-react-native/pull/3103
