### ISSUE TITLE
Sentry.captureMessage Stack Trace is not symbolicated

### ISSUE THREAD

**Issue by csath** [getsentry/sentry-react-native#3097]
### Environment

What version are you running? Etc.

@sentry/cli@2.17.1
@sentry/core@7.47.0
@sentry/hub@7.47.0
@sentry/integrations@7.47.0
@sentry/react-native@5.3.1

### Steps to Reproduce

1. I try to upload debug files using following command ion iOS
`../node_modules/@sentry/cli/bin/sentry-cli debug-files upload "$INCLUDE_SOURCES_FLAG" "$DWARF_DSYM_FOLDER_PATH" --project XXX`

2. I can see that the debug-files and source maps are uploaded under Sentry project settings.

3. I try to test following scenarios in my app
- Invoke `Sentry.captureException()` -> Sentry logs correctly point to the exact line number in the JS file ✅ 
- Enable `enableCaptureFailedRequests: true` & simulate a network error -> Works as expected, Sentry shows the network error logs ✅
-  Invoke `Sentry.captureMessage('Logging information for testing', 'warning')` -> Sentry captures the log but says '`Source code was not found`' ❓ 
![image](https://github.com/getsentry/sentry-cli/assets/30233361/a3fe69dd-ae12-414a-a24c-2959220de770)
- Invoke `Sentry.nativeCrash()` to simulate a native crash ->  Sentry captures the error but says '`A required debug information file was missing`'❓ <img width="1269" alt="image" src="https://github.com/getsentry/sentry-cli/assets/30233361/f7cc53d2-8a86-4d16-83b7-0f7cef3358e4">

Some of the logs are readable and only crashes and `Sentry.captureMessage` are having issues finding the correct symbols and debug files.

### Expected Result

Native crashes and `Sentry.captureMessage` should map debug symbols and point to the exact error.

###  More information

Sourcemaps and debug files are uploaded in Sentry.
![image](https://github.com/getsentry/sentry-cli/assets/30233361/b28857fe-76d6-44f1-8882-cd10627948a2)
<img width="1169" alt="image" src="https://github.com/getsentry/sentry-cli/assets/30233361/0b20b1e4-13d8-439d-a678-a2a1e776d104">

**Comment by krystofwoldrich** [comment]
Hi,
I've got a bit confused by the debug symbols. This looks like a bug of `sentry-react-native`. The attached stack trace to the message doesn't get symbolicated using the source maps.

The cause could be the RewriteFrames doesn't get executed for the threads stack trace but only exception stack trace https://develop.sentry.dev/sdk/event-payloads/threads/

**Comment by AlexanderEggers** [comment]
@krystofwoldrich Do you have any updates on this issue?

**Comment by krystofwoldrich** [comment]
@AlexanderEggers Besides what you can see in the issue, no updates.

**Comment by AlexanderEggers** [comment]
@krystofwoldrich I'm mainly interested in https://github.com/getsentry/sentry-react-native/issues/3120 which sill forces us to use the workaround that is mentioned. You closed that issue in favor of this one.

**Comment by krystofwoldrich** [comment]
@AlexanderEggers Thank you for the link to the other issue.

Reacting to the comment from there.

> That case is creating a lot of events with the title <global> which doesn't seem correct.

Could you share the current workaround title and the stack trace (source example if possible) and the expected title?

**Comment by Off2Race** [comment]
> Could you share the current workaround title and the stack trace (source example if possible) and the expected title?

Hi, @krystofwoldrich. I ran into the stack track issue as well. Fortunately, switching from captureMessage to captureException was a reasonable workaround but the one downside is the display of the issues. 

**with captureMessage (preferred)**
![image](https://github.com/getsentry/sentry-react-native/assets/2400179/74ad41e8-e65e-40a1-be5c-cda1fc7aa643)

**with captureException (works but suboptimal)**
![image](https://github.com/getsentry/sentry-react-native/assets/2400179/4f61001f-6b0b-457d-b2a8-31417e7129b1)

In some cases, the captureException displays in RED, which also makes them look more "urgent" than they really are.

If captureException supported the ability to display the same way as captureMessage, the workaround would be fine.

**Comment by krystofwoldrich** [comment]
@Off2Race Thank you for the message, we will focus on fixing the `captureMessage`.

**Comment by krystofwoldrich** [comment]
This https://github.com/getsentry/sentry-react-native/issues/2131 was the original reason to move the stack attached to a message from `stacktrace` to `threads`.

Currently `threads` are not used in JS, both in rewrite frames and in DebugIDs resolution. Therefore the frames from threads are not symbolicated.

The original issue was the message stack was missing on Android because the `stacktrace` field would be removed. That is not the case with `exception` field used by JS SDK today.

Moving the message stack to `exception` to unify with JS SDK will resolve both the rewrite frames issue and DebugIDs resolution. Although it's not in line with https://develop.sentry.dev/sdk/event-payloads/stacktrace/ I believe we should revert to what JS SDK is doing.

**Comment by armata007** [comment]
Hi @krystofwoldrich I am wondering if this fix was released? I am having exactly the same issue and I am on version 5.22.2.

I can confirm that changing captureMessage to captureException fixes the original issue but does not look too good

**Comment by melyux** [comment]
I have `integrations: [captureConsoleIntegration({ levels: ['error'] })]` on to capture `console.error("Test error")` as errors, but this also doesn't include the stack trace despite being an error. Obviously the workaround doesn't work in this case

**Comment by krystofwoldrich** [comment]
@armata007 This will be released in version 6 of the SDK.

**Comment by krystofwoldrich** [comment]
@melyux Could you open a new issue, as you mentioned this is not about `captureMessage`, we will need more information to investigate it.

**Comment by net** [comment]
I'm also having the same issue with `integrations: [captureConsoleIntegration({ levels: ['error'] })]` as @melyux. Is there an existing issue?

It seems `captureConsoleIntegration` uses `captureMessage` instead of `captureException`.
