### ISSUE TITLE
enableCaptureFailedRequests set to false does not stop breadcrumbs for http/xhr requests

### ISSUE THREAD

**Issue by AlexanderEggers** [getsentry/sentry-react-native#3111]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.5.0

**`react-native` version:** 0.71.8

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Can I share that differently? I prefer not sharing any public links.

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: env.SENTRY_DNS,
  debug: __DEV__,
  environment: env.SENTRY_ENV,
  enabled: !__DEV__ && !env.IS_MOCK,
  tracesSampleRate: 0.2,
  integrations: [
    new Sentry.ReactNativeTracing({
      enableCaptureFailedRequests: false,
      routingInstrumentation: SENTRY_ROUTING_INTRUMENTATION,
    }),
  ],
  attachStacktrace: true,
  attachThreads: true,
  enableCaptureFailedRequests: false,
});

```
---
**I have following issue:**

http/xhr requests are listed as breadcrumbs which is not expected when setting that option to false. I have my own integration to capture request failures.

**Steps to reproduce:**
- set enableCaptureFailedRequests to false during sentry init

**Actual result:**
http/xhr requests are listed as breadcrumbs

**Expected result:**
no http/xhr requests are listed as breadcrumbs

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and sorry for the longer response time.

The `enableCaptureFailedRequests` options control sending failed requests as errors to Sentry, not breadcrumb creation.

It's okay to use your own integration it should not interfere with the breadcrumbs.

If you want to remove http/xhr breadcrumbs you can filter them using [beforeBreadcrumb](https://docs.sentry.io/platforms/react-native/enriching-events/breadcrumbs/#customize-breadcrumbs), on iOS the native layer also creates HTTP breadcrumbs, so there it's needed to do [manual init](https://docs.sentry.io/platforms/react-native/manual-setup/native-init/) and then the native HTTP breadcrumbs can be also filtered.

**Comment by AlexanderEggers** [comment]
@krystofwoldrich Wouldn't it make sense to enable/disable such broadcrumbs easily via a flag? Especially in the grpahql space, the current tracked breadcrumbs are pretty useless.

**Comment by krystofwoldrich** [comment]
@AlexanderEggers I agree, there is a simple way here https://docs.sentry.io/platforms/react-native/configuration/integrations/default/#breadcrumbs, but it only works for the JS layer, but not native on iOS.

We are aware of the GraphQL situation and we are working on better support for it, specifically for error reporting.

**Comment by AlexanderEggers** [comment]
@krystofwoldrich Are there any plans to update the implementation so that it is not just impacting js but also native? Configuring the js layer and ios at the same time seems quite error-prone.
