### ISSUE TITLE
Android Symbolicated Stack Trace points to a wrong line

### ISSUE THREAD

**Issue by HariWarshan** [getsentry/sentry-react-native#3121]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**`react-native` version:** 0.68.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
   environment: "production",
    tracesSampleRate: 1,
    enableAutoSessionTracking: true,
      release: `${AppConstant.APP_NAME}@${AppConstant.APP_VERSION }`
     dist: AppConstant.APP_BUILD,
    enableNative: true,
    attachScreenshot: true,
    integrations: [new Sentry.ReactNativeTracing()]
});
```

---
**I have following issue:**

[Description]
I did uploaded the stack trace but noticed `The trace for this event cannot be found` 

**Steps to reproduce:**
- I am creating bundle files with `react-native bundle --dev false --platform android --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map`
- uploading them using `./node_modules/@sentry/cli/bin/sentry-cli --log-level=debug releases --org <org_name> --project <project_name> files $APP_NAME@$APP_VERSION  upload-sourcemaps --dist $BUILD_NUMBER --strip-prefix index.js --rewrite index.android.bundle index.android.bundle.map`
- i can able to see the sourcemaps thats uploaded in archives
![Screenshot 2023-06-14 at 8 54 29 AM](https://github.com/getsentry/sentry-react-native/assets/48403240/3f35c810-0be7-4b03-8ec2-74d05e9da4a9)
- trigger exception manually using `Sentry.captureException("Test Capture Exception")`

**Actual result:**
- i am noticing this message`The trace for this event cannot be found` on that particular event
![Screenshot 2023-06-14 at 8 58 55 AM](https://github.com/getsentry/sentry-react-native/assets/48403240/262cae56-d277-4a0f-9ce5-9cf3c5456cc2)
- when i do sentry-cli sourcemaps explain, am getting  `Event exception stacktrace selected frame (0) has incorrect abs_path (valid url is required). `
<img width="1044" alt="Screenshot 2023-06-14 at 9 00 54 AM" src="https://github.com/getsentry/sentry-react-native/assets/48403240/04573a69-8403-48f3-bc59-3bd01e3c0f15">

**Expected result:**
sourcemap should be linked to the events and i should be able to identify the exact line where the exception happened

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message,
can you open the event JSON on the issue page and search for `exception -> values -> raw_stacktrace -> frames -> abs_path` and share some (or best all if they are different) `abs_path` paths examples with us?

**Comment by HariWarshan** [comment]
@sentry/react-native version is not older than `5.1.1 ` here are the versions 

```
@sentry/react-native: 5.5.0, 
react-native: 0.68.2
```

**Comment by krystofwoldrich** [comment]
I'm looking back at this screen the stack frames look symbolicated, what exactly is the issue here?

![](https://user-images.githubusercontent.com/48403240/245667214-262cae56-d277-4a0f-9ce5-9cf3c5456cc2.png)

**Comment by krystofwoldrich** [comment]
@HariWarshan Thank you, I see now, the stack trace doesn't point to the correct file and line of code.

Are you using Hermes?
