### ISSUE TITLE
Reload async to apply OTA updates causing Sentry to crash due to `LifecycleRegistry.removeObserver` 

### ISSUE THREAD

**Issue by MorenoMdz** [getsentry/sentry-react-native#3131]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 
Expo 48 
Expo sentry 6.10.0
Sentry 4.13.0

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'our dsn',
  enableInExpoDevelopment: false,
  debug: __DEV__ ? true : false, 
  environment: env,
})
```

Configuration setup as in Expo docs:
```
"hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "traba",
            "project": "traba-app",
            "setCommits": true
          }
        }
      ]
    }
```

---
**I have following issue:**

App crashes when calling reload. Our app has a flow that checks if there is a new OTA update in the Expo EAS update channel, if so it prompts the user to reload. When the reload happens it seems like Sentry is failing to properly clear some listeners and or is causing the OS to crash.

We call the app reload with `reloadAsync()` from `expo-updates`

The 

**Steps to reproduce:**
- Load the app in the Android simular
- Press R, it will crash the app

**Actual result:**

This is the error we get in both the local simulator and in our Sentry logs from production, we can tie it directly to when we send a new OTA which cause users to be prompted to reload. The OTA update is applied normally and then no more crashes happen.

```
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer
  androidx.lifecycle.LifecycleRegistry.removeObserver(Unknown Source:3)
  io.sentry.android.core.AppLifecycleIntegration.removeObserver(AppLifecycleIntegration.java:112)
  io.sentry.android.core.AppLifecycleIntegration.lambda$close$1$io-sentry-android-core-AppLifecycleIntegration(AppLifecycleIntegration.java:123)
  io.sentry.android.core.AppLifecycleIntegration$$ExternalSyntheticLambda0.run(Unknown Source:2)
  android.os.Handler.handleCallback(Handler.java:938)
  android.os.Handler.dispatchMessage(Handler.java:99)
  android.os.Looper.loopOnce(Looper.java:201)
  android.os.Looper.loop(Looper.java:288)
  android.app.ActivityThread.main(ActivityThread.java:7842)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
  ```

**Expected result:**

App to reload normally without any errors.

### RN info:
```
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.45 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    ```

**Comment by krystofwoldrich** [comment]
This was fixed in this PR https://github.com/getsentry/sentry-java/pull/2625.

It's part of RN SDK [getsentry/sentry-react-native@5.3.1 (release)](https://github.com/getsentry/sentry-react-native/releases/tag/5.3.1) and newer.

In `sentry-expo` this fix was introduced in https://github.com/expo/sentry-expo/releases/tag/v7.0.0
