### ISSUE TITLE
Production build is failing with RN 0.72 (Gradle 8)

### ISSUE THREAD

**Issue by renchap** [getsentry/sentry-react-native#3144]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.6.0

**`react-native` version:** 0.72.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
**Configuration:**
Not relevant, this happens during build

---
**I have following issue:**

Starting with Gradle 8.0, task dependencies must be explicit.

Building a RN 0.72 app uses Gradle 8, which fails with:

```
…
> Task :app:bundleRelease
> Task :app:uploadSentryNativeSymbolsForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:uploadSentryNativeSymbolsForRelease' (type 'SentryUploadNativeSymbolsTask').
  - Gradle detected a problem with the following location: '/Users/renchap/dev/notos/packages/mobile/android/app/build'.

    Reason: Task ':app:uploadSentryNativeSymbolsForRelease' uses this output of task ':app:produceReleaseBundleIdeListingFile' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':app:produceReleaseBundleIdeListingFile' as an input of ':app:uploadSentryNativeSymbolsForRelease'.
      2. Declare an explicit dependency on ':app:produceReleaseBundleIdeListingFile' from ':app:uploadSentryNativeSymbolsForRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:produceReleaseBundleIdeListingFile' from ':app:uploadSentryNativeSymbolsForRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/renchap/dev/notos/packages/mobile/android/app/build'.

    Reason: Task ':app:uploadSentryNativeSymbolsForRelease' uses this output of task ':app:createReleaseBundleListingFileRedirect' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':app:createReleaseBundleListingFileRedirect' as an input of ':app:uploadSentryNativeSymbolsForRelease'.
      2. Declare an explicit dependency on ':app:createReleaseBundleListingFileRedirect' from ':app:uploadSentryNativeSymbolsForRelease' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:createReleaseBundleListingFileRedirect' from ':app:uploadSentryNativeSymbolsForRelease' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

**Steps to reproduce:**
- Run a production build (`bundleRelease`) with the Sentry SDK installed
- See that Gradle fails the build due to missing tasks dependencies

**Actual result:**

The build fails with the error message above

**Expected result:**

The build succeed

**Comment by renchap** [comment]
Woops, this was caused by the Sentry Android Gradle plugin, we used an old version that was not compatible with Gradle 8.

Updating it to the latest version worked fine.

**Comment by humarkx** [comment]
@renchap still facing the same issue running `5.6.0` with the same configuration as above

**Comment by krystofwoldrich** [comment]
What version of https://github.com/getsentry/sentry-android-gradle-plugin are you using? Please, try to update to the latest version.

**Comment by humarkx** [comment]
@krystofwoldrich https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/

I did the React Native Automatic installation, but doesn't mention anywhere even on the manual docs, where to use that package.
Where should I use/change it?

Thanks

**Comment by devDanielCespedes** [comment]
> @krystofwoldrich https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/
> 
> I did the React Native Automatic installation, but doesn't mention anywhere even on the manual docs, where to use that package. Maybe this should be somewhere in the RN install documentation: https://github.com/getsentry/sentry-react-native/blob/e44fe2d34ac8fb358e6660aa5df0109ee9982b56/sample-new-architecture/android/build.gradle
> 
> After updating to `classpath("io.sentry:sentry-android-gradle-plugin:3.11.1")` in android/build.gradle still causes the error
> 
> Thanks

same here

**Comment by renchap** [comment]
Do you have `io.sentry:sentry-android-gradle-plugin` mentioned somewhere in your gradle files? If yes, what is the full line?

**Comment by humarkx** [comment]
`classpath("io.sentry:sentry-android-gradle-plugin:3.11.1")
`

I have this in my `android/build.gradle`

**Comment by humarkx** [comment]
```
> Task :sentry_react-native:packageDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
166 actionable tasks: 161 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Note: /Users/u/projects/u/u-mobile/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':sentry_react-native:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: '/Users/u/projects/u/u-mobile/node_modules/@sentry/react-native/android/build/generated/res/rs/debug'.

    Reason: Task ':sentry_react-native:packageDebugResources' uses this output of task ':@sentry_react-native:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@sentry_react-native:compileDebugRenderscript' as an input of ':sentry_react-native:packageDebugResources'.
      2. Declare an explicit dependency on ':@sentry_react-native:compileDebugRenderscript' from ':sentry_react-native:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@sentry_react-native:compileDebugRenderscript' from ':sentry_react-native:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/u/projects/u/u-mobile/node_modules/@sentry/react-native/android/build/generated/res/resValues/debug'.

    Reason: Task ':sentry_react-native:packageDebugResources' uses this output of task ':@sentry_react-native:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':@sentry_react-native:generateDebugResValues' as an input of ':sentry_react-native:packageDebugResources'.
      2. Declare an explicit dependency on ':@sentry_react-native:generateDebugResValues' from ':sentry_react-native:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':@sentry_react-native:generateDebugResValues' from ':sentry_react-native:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s

```


And build gradle:


```

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  ext {
    buildToolsVersion = "34.0.0"
    minSdkVersion = 24
    compileSdkVersion = 34
    targetSdkVersion = 34
    ndkVersion = "23.1.7779620"
    kotlin_version = "1.8.0" //keep checking if we can remove this. 0.71.8 -> 0.72.0
  }
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath("com.android.tools.build:gradle")
    classpath("com.facebook.react:react-native-gradle-plugin")
    classpath("io.sentry:sentry-android-gradle-plugin:3.11.1")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    //keep checking if we can remove this. 0.71.8 -> 0.72.0
  }
}

allprojects {
  repositories {
    google()
    mavenCentral()
  }
}
```

**Comment by krystofwoldrich** [comment]
@humarkx @devDanielCespedes Thank you for the information, sadly we can't reproduce the issue.

Could you provide a minimal reproducible example with detailed steps on how you build the app?

**Comment by devDanielCespedes** [comment]
> @humarkx @devDanielCespedes Thank you for the information, sadly we can't reproduce the issue.
> 
> Could you provide a minimal reproducible example with detailed steps on how you build the app?

Hey, @krystofwoldrich how are you? 
I just managed to make a [minimal reproducible example](https://github.com/devDanielCespedes/sentry-minimal-reproducible-example-error) could you take a look, please? 😄 



[Screencast from 05-07-2023 18:24:29.webm](https://github.com/getsentry/sentry-react-native/assets/69821257/8f376e2d-90f7-491f-98ce-698b5ffdfcb8)

**Comment by devDanielCespedes** [comment]
@krystofwoldrich Hello. How are you doing? Did you get a chance to take a look at the example? 😄 If you need any help, let me know

**Comment by krystofwoldrich** [comment]
@devDanielCespedes Thank you for the reproducible example, I've reproduced it.

**Comment by krystofwoldrich** [comment]
@devDanielCespedes Thank you one again for the example, the issue was the manually included `@sentry_react_native` project. You don't have to do that, the react-native tooling includes our android project automatically and correctly assigns the tasks dependencies so the project builds with Gradle 8.

Please see the changes I've made, after this, the project build correctly.

https://github.com/devDanielCespedes/sentry-minimal-reproducible-example-error/compare/main...krystofwoldrich:sentry-minimal-reproducible-example-error:main

**Comment by trevordunn** [comment]
@krystofwoldrich That worked for me as well. If those aren't required anymore would it make sense to remove them from the manual configuration steps here?

https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#android

**Comment by krystofwoldrich** [comment]
@trevordunn Yes, make sense, we will update the docs.

**Comment by TheMakerOleguch** [comment]
Should we update the documentation, it's still there?

**Comment by trevordunn** [comment]
@krystofwoldrich heads up that the docs still haven't been updated to remove the manual inclusion of `@sentry_react-native`.

**Comment by lorenjohnson** [comment]
Yes an update would be good. I also just blew 30 minutes on this before figuring it out.. In general I found the Android manual install docs fairly vague and a little confusing compared to the iOS steps.

**Comment by fimbres** [comment]
I'm facing this in a RN Expo App using the latest version, any update?

**Comment by krystofwoldrich** [comment]
@fimbres If you manually included `@sentry_react_native` in you Android build, then please remove it as mentioned above.

Otherwise please open a new issue with the exact error you are getting and details about your project.
