### ISSUE TITLE
IdleTransaction's `finalTimeout` will exceed when the app is in background 

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3150]
### Description

In RN the JS thread gets paused when the app goes to the background. Scheduled tasks like JS timeouts that would be executed during the time in the background will get executed after reopening the app. If the scheduled task was a Tx final timeout this can cause a Transaction that is hours/days long.

### Solution

Since `finalTimeout` marks the length of Tx that can't be exceeded I think we should adjust the length of the transaction in this case.

```[tasklist]
### Related issues
- [ ] https://github.com/getsentry/sentry-react-native/issues/3149
```

**Comment by kahest** [comment]
related JS issue: https://github.com/getsentry/sentry-javascript/issues/8504

**Comment by krystofwoldrich** [comment]
Browser JS is experiencing the exact same issue, but instead of the app going to the background the browser tab JS execution is paused by the Browser, we should fix this in JS SDK.

[Graph explaining what is happening and how we can fix it.](https://github.com/getsentry/sentry-javascript/issues/8504#issuecomment-1649615267)

**Comment by krystofwoldrich** [comment]
Fixed by JS https://github.com/getsentry/sentry-javascript/pull/8653
