### ISSUE TITLE
Stack Trace not showing the correct code, line, or file.

### ISSUE THREAD

**Issue by coofzilla** [getsentry/sentry-react-native#3196]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:**  "@sentry/react-native": "~5.6.0",

**`react-native` version:** "react-native": "~0.71.0",

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
[issue](https://birdiefire-llc.sentry.io/issues/4320602094/events/4d9453922a7b4d9c861bfa08728e10c6/)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: SENTRY_DSN,
  tracesSampleRate: 1.0,
  environment: process.env.NODE_ENV,
})
```
---
**I have following issue:**

I'm trying to configure `Sentry` with `hermes` so that I can view the `stack trace` in a `readable` format. My end goal is to run this as part of a github action; however, I'd like to be able to view it dev by running my script.

I created a `build_source_maps.sh` with the following code:

```sh
#!/bin/bash
node_modules/@sentry/cli/bin/sentry-cli releases -o $ORGANIZATION -p $PROJECT new $IOS_VERSION_NUMBER

# Bundle and minify with metro to get the packager bundle and source map
npx react-native bundle --platform ios --dev false --entry-file index.js --reset-cache --bundle-output main.jsbundle --sourcemap-output main.jsbundle.map --minify false

# Compile to bytecode using hermes to get the compiler source map
ios/Pods/hermes-engine/destroot/bin/hermesc -O -emit-binary -output-source-map -out=main.jsbundle.hbc main.jsbundle
rm -f main.jsbundle
mv main.jsbundle.hbc main.jsbundle

# Rename the packager map
mv main.jsbundle.map main.jsbundle.packager.map

# Merge the packager source map and the compiler source map to get the final source map
node node_modules/react-native/scripts/compose-source-maps.js main.jsbundle.packager.map main.jsbundle.hbc.map -o main.jsbundle.map

# Upload the source maps
node_modules/@sentry/cli/bin/sentry-cli releases \
    -o $ORGANIZATION \
    -p $PROJECT \
    files $IOS_VERSION_NUMBER \
    upload-sourcemaps \
    --dist $IOS_BUILD_NUMBER \
    --strip-prefix . \
    main.jsbundle main.jsbundle.map

# Finalize the release
node_modules/@sentry/cli/bin/sentry-cli releases -o $ORGANIZATION -p $PROJECT finalize $IOS_VERSION_NUMBER
```

**Steps to reproduce:**
- run `build_source_maps` 
This outputs the following:
![image](https://github.com/getsentry/sentry-react-native/assets/75731066/cab1f693-faa6-4112-8d85-f9ab9ee308c5)

- run the app to trigger an error
- observe error logged in sentry
![image](https://github.com/getsentry/sentry-react-native/assets/75731066/53d6791f-fcec-4130-b9df-bd166b8073a5)

- When viewing stack trace, the file path links to a different file, doesn't display the code with the actual error, or the correct line.

![image](https://github.com/getsentry/sentry-react-native/assets/75731066/8e2c5cda-fba2-4b68-a99b-9d4b7d2036ff)

**note**
- if I check display minified, it will display the correct code and line; however, it just gives me the bundle vs the file which would be `Root.tsx`
![image](https://github.com/getsentry/sentry-react-native/assets/75731066/65826c46-d75d-4382-bae0-2bc6ecce05a7)

- `Root.tsx` source code:
![image](https://github.com/getsentry/sentry-react-native/assets/75731066/82dc72c3-d060-400e-82fc-8861330bd182)

**Expected result:**
I believe that the error should show the correct line, code where the error is thrown, and file. 

**Additional Information**
- I'm not using RAM bundles
- I followed the `hermes support` page [here](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/?original_referrer=https%3A%2F%2Fwww.google.com%2F)
- I tried to use the explain trick from the tutorial and got this:
![image](https://github.com/getsentry/sentry-react-native/assets/75731066/c1b7fc3c-4a70-4f22-8065-448ba8ed1df4)
- I'm using the version, build, and build identifier from xcode.
- Since I'm using `hermes` I believe I _have_ to use manual configuration? I'm not sure what I'm missing here, any help would be appreciated 🙏🏽

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and all the details.

You can use the auto upload with Hermes too, the `npx @sentry/wizard@latest -s -i reactNative` sets up everything, and source maps are uploaded during release builds.

 Are you using `EXTRA_PACKAGER_ARGS` or [`SOURCEMAP_FILE`](https://reactnative.dev/docs/sourcemaps#enable-source-maps-on-ios) env to enable the source maps?
 
 If `EXTRA_PACKAGER_ARGS` only the packager step is needed.
 If `SOURCEMAP_FILE` the spes you described are needed and you have to upload the source maps manually.

**Comment by coofzilla** [comment]
I was using the `EXTRA_PACKAGER_ARGS`. So then, if I revert everything and then use `npx @sentry/wizard@latest -s -i reactNative` to set up everything from scratch, I would just need to add this:

```sh
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

# RN 0.69+
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_CLI="../node_modules/@sentry/cli/bin/sentry-cli"

/bin/sh -c "$WITH_ENVIRONMENT \"$SENTRY_CLI react-native xcode $REACT_NATIVE_XCODE\""

# All versions
/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh
```

to the `Bundle React Native Code and Images` ?

That is so that I can auto do everything with `Hermes`

**Comment by coofzilla** [comment]
**update resolved**

so I had two issues. 

1) Had to add the `EXTRA_PACKAGER_ARGS` stuff, thank you worked like a charm

2) Needed to set my App in the root directory, we have some nesting stuff; but, when I moved it into root for testing it synced with the wizard.

Is there a way to change which file the wizard uses to patch? so Instead of App.tsx for example using like Root.tsx? Or would that enter into "manual" territory.

**Comment by krystofwoldrich** [comment]
@coofzilla Wizard sets up even the Xcode builds script so you should not need to do anything when using the wizard command.

Happy to hear that's working. At the moment wizard only patches `[src]App.[js|ts...]`.
