### ISSUE TITLE
Infinite looping on app startup

### ISSUE THREAD

**Issue by nandorojo** [getsentry/sentry-react-native#3205]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.5.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

**Configuration:**

(`@sentry/react-native`)
```tsx
import * as Sentry from 'sentry-expo'

const dsn = process.env.EXPO_SENTRY_DSN

Sentry.init({
  dsn,
  enableInExpoDevelopment: true,
  debug: __DEV__
})
```
---

**I have following issue:**

Sentry is infinitely looping with an app startup log. Refreshing my development client fixes it. It only happens when I open it for the first time.

https://github.com/getsentry/sentry-react-native/assets/13172299/c8991060-135b-4a28-9ac1-828378542a64

This started after upgrading to SDK 49.

**Steps to reproduce:**

I'm not sure how to reproduce this, or why it's happening.

**Actual result:**

Infinite looping.

**Expected result:**

No infinite looping.

**Comment by lindan4** [comment]
@krystofwoldrich The fix doesn't seem to work for me. I still get the infinite logs.

**Comment by krystofwoldrich** [comment]
Thank you for the comments.

Could anyone check what are the HTTP requests causing the issue? Note you might need to adjust the devServerPort or remove it from like this:

```js
import * as Sentry from 'sentry-expo';
import * as Network from 'expo-network';

let devServerIpAddress: string | null = null;
Network.getIpAddressAsync().then(ip => {
  devServerIpAddress = ip;
});

Sentry.init({
  tracesSampleRate: 1.0,
  integrations: [
    new Sentry.Native.ReactNativeTracing({
      shouldCreateSpanForRequest: url => {
        return !__DEV__ || !url.startsWith(`http://${devServerIpAddress}`);
      },
    }),
  ],
});
```

Does the new snippet fix the code?

**Comment by gloredo** [comment]
> Thank you for the comments.
> 
> Could anyone check what are the HTTP requests causing the issue? Note you might need to adjust the devServerPort or remove it from like this:
> 
> ```js
> import * as Sentry from 'sentry-expo';
> import * as Network from 'expo-network';
> 
> let devServerIpAddress: string | null = null;
> Network.getIpAddressAsync().then(ip => {
>   devServerIpAddress = ip;
> });
> 
> Sentry.init({
>   tracesSampleRate: 1.0,
>   integrations: [
>     new Sentry.Native.ReactNativeTracing({
>       shouldCreateSpanForRequest: url => {
>         return !__DEV__ || !url.startsWith(`http://${devServerIpAddress}`);
>       },
>     }),
>   ],
> });
> ```
> 
> Does the new snippet fix the code?

It works! Thx @krystofwoldrich

**Comment by krystofwoldrich** [comment]
@gloredo Thanks, happy to hear the fix works.

- Regarding the malformed call (it happens only in dev, due to a size limit) https://github.com/getsentry/sentry-react-native/issues/2744

- For anyone reading this later date, this issue track the permanent fix of the infinite loop https://github.com/getsentry/sentry-react-native/issues/3210
