### ISSUE TITLE
Sourcemap not being generated with CodePush and Hermes

### ISSUE THREAD

**Issue by lucaashrq** [getsentry/sentry-react-native#3207]
**OS:**
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.2

**`react-native` version:** 0.66.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://market-media.sentry.io/issues/4333131071)

**Configuration:**

(`@sentry/react-native`)
```
const getSentryConfig = (): SentryModule.ReactNativeOptions => {
  let release = `${Platform.OS}-${version}-${build}`;
  const dist = `${Platform.OS}-${build}`;

  return {
    dsn: environmentConfig.SENTRY_DSN,
    environment: __DEV__ ? 'development' : environmentConfig.ENVIRONMENT,
    release,
    dist,
    tracesSampleRate: 0.01,
  };
};

const init = async (): Promise<void> => {
  const config = getSentryConfig();
  LoggerService.info(
    `initializing Sentry with release: ${config.release} and dist: ${config.dist}`,
  );
  SentryModule.init(config);
  SentryModule.configureScope(async (scope) => {
    scope.setExtras({ platform: Platform.OS, deviceId: getDeviceId() });
  });
};
```

---
**I have following issue:**

I've configured successfully the manual sourcemaps generation with Hermes following the [documentation](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/).

We use code push to handle the OTA and tried to follow the documentation of [CodePush ](https://docs.sentry.io/platforms/react-native/manual-setup/codepush)to configure it.

I'm generating the code push release through this command:

```
yarn appcenter codepush release-react \
            --token myToken \
            --deployment-name developmentName \
            --app org/appId \
            --disable-duplicate-release-error \
            --sourcemap-output \
            --output-dir ./build"
```

It generates successfully a bundle in `build/CodePush`.
Then we upload it to sentry using:

```
 npx sentry-cli react-native appcenter \
            org/appId \
            android ./build/CodePush \
            --deploymentdevelopmentName  \
            --dist android-100\
            --release-name android-1.0.0-100"
```

What I've noticed is that I get a warning in the end of upload: `warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/index.android.bundle)` and there is no .map file like when I manually generate the sourcemap.

I also tried to generate the code push release and then generate the sourcemap manually, not worked.

Am I missing something?

Will attach the evidences.

![image](https://github.com/getsentry/sentry-react-native/assets/30247652/d50b28da-c000-43c8-b830-e10f6300f028)
![image](https://github.com/getsentry/sentry-react-native/assets/30247652/d73b7913-16d7-4d6f-af31-8a4f328f7f3f)
![image](https://github.com/getsentry/sentry-react-native/assets/30247652/5c85d4d9-ec57-417c-af7a-76cbd3fd6fbc)

**Comment by lucaashrq** [comment]
Hi,
thanks for the quick reply.

> Can you try to specify a path for the source map `--sourcemap-output ./build/CodePush/index.android.bundle.map`?

I've tried, now an `index.android.bundle.packager.map` is generated but I got an error in code push hermes compile:

![image](https://github.com/getsentry/sentry-react-native/assets/30247652/7d0e87b3-08d8-40b5-914e-183c1969e7b5)

![image](https://github.com/getsentry/sentry-react-native/assets/30247652/b1184784-5920-4eed-9139-8cd236f4cf91)

I used:

`yarn appcenter CodePush release-react
  -a org/app
  -d Development
  --disable-duplicate-release-error
  --sourcemap-output ./build/CodePush/index.android.bundle.packager.map
  --output-dir ./build
  --token myToken
  --target-binary-version myVersion`

I also tried using `./build/CodePush/index.android.bundle.map` as the output and got the same error.

**Comment by krystofwoldrich** [comment]
@lucaashrq This seems like a CodePush error, there might be [some info here](https://github.com/microsoft/appcenter-cli/issues), are you able to retrieve what the error is? Could be `hermesc.exe` or something after, I'm not able to tell from the current log. 

Maybe by running the hermesc.exe manually after the code push command fails to see if there is more error log.

**Comment by sahilleap** [comment]
@krystofwoldrich I am also facing this issue while Uploading sourcemaps for release in both Android and IOS.

Command I am running for IOS
```
node_modules/@sentry/cli/sentry-cli react-native appcenter wallet/iOS-app ios ./build/CodePush --deployment Staging --dist v8
```

Error log
```
Source Map Upload Report
  Minified Scripts
    ~/main.jsbundle (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/main.jsbundle.)

```

Command I am running for Android
```
node_modules/@sentry/cli/sentry-cli react-native appcenter wallet/android-app android ./build/CodePush --deployment Staging --dist v6
```

Error log
```
Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (no sourcemap ref)
      - warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/index.android.bundle.)
```



In my local files I can sees main.jsbundle  of size 26.8MB

<img width="687" alt="Screenshot 2023-08-03 at 11 56 18 AM" src="https://github.com/getsentry/sentry-react-native/assets/138430303/ec462418-3c24-437c-93d1-a07f362b30ab">



In the sentry Release Bundle it is showing 0MB

I![Screenshot 2023-08-03 at 11 57 04 AM](https://github.com/getsentry/sentry-react-native/assets/138430303/8ddd4a52-2d03-4de1-9b2b-73e3900138f2)

**Comment by krystofwoldrich** [comment]
@sahilleap What version of `appcenter-cli` are you using and what does your command that creates the bundle looks like?

The fact that the bundle is 0 B is expected for Hermes bundles. It looks like your `codepush` command didn't create the source map for the bundle or the source map is not in the `wallet/${platform}-app` folder.

**Comment by sahilleap** [comment]
@krystofwoldrich 
appcenter version is `2.13.9`

command to create bundle
```
appcenter codepush release-react \
    -a "$APP_CENTER_ORG_NAME/$APP_CENTER_APP_NAME" \
    -d "$DEPLOYMENT_NAME" \
    --description "$DESCRIPTION" \
    --sourcemap-output \
    --output-dir ./build
```

**Comment by krystofwoldrich** [comment]
@sahilleap Can you try to specify a path for the source map `--sourcemap-output ./build/CodePush/index.android.bundle.map`?

**Comment by krystofwoldrich** [comment]
@calintamas Is the command you shared working for you or are you also having issues with the source maps upload?

**Comment by calintamas** [comment]
@krystofwoldrich It solves the issue for me. The sourcmaps are generated and then succesfully uploaded using sentry cli.

**Comment by krystofwoldrich** [comment]
@calintamas Awesome, thanks for the confirmation.
