### ISSUE TITLE
Loaded file referenced by SENTRY_PROPERTIES (sentry.properties) error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by chaitanya71998** [getsentry/sentry-react-native#3224]
Hey
i integrated sentry with my react native app, using sentry wizard it worked awesome with android and no ssuues, but with ios i was getting this error during build
```
INFO    2023-08-02 12:58:47.311672 +05:30 Loaded file referenced by SENTRY_PROPERTIES (sentry.properties)
error: No such file or directory (os error 2)
```

the **sentry.properties** file is already there in the ios/ folder even though i was getting this error?
can any one know how to fix this error?

**Comment by krystofwoldrich** [comment]
We have resolved this on Sentry Discord.

For anyone else having the same issue in the future. Check your `Bundle React Native code and images` build phase, it should look the same as https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#bundle-react-native-code-and-images.
