### ISSUE TITLE
Android build fails when switching to new react native architecture due to sentry 

### ISSUE THREAD

**Issue by MetaBenji** [getsentry/sentry-react-native#3231]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.6.0

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: Config.SENTRY_ENV,
  debug: __DEV__,
})
```

---
**I have following issue:**

I'm switching my react native application to use react native's new architecture.  I was previously using the same version of react native without the new architecture.  When I build the android app now locally, I get the following error:

```
* What went wrong:
Execution failed for task ':sentry_react-native:generateCodegenSchemaFromJavaScript'.
> Process 'command 'node'' finished with non-zero exit value 1
``` 

Any help would be greatly appreciated! 😃 

**Steps to reproduce:**
- Set `newArchEnabled=true` in android/gradle.properties
- run `react-native run-android`

**Actual result:**

Build fails with error above

**Expected result:**

build to succeed

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the information, can you share more of the build log, so we can see what failed?

**Comment by Spharian** [comment]
Still having the issue today.

**Comment by krystofwoldrich** [comment]
Hi @Spharian,
thank you for the message,
could you open a new issue and give us details like SDK version, RN version....

That will help resolving the issue as fast as possible.
