### ISSUE TITLE
Failing at "Adding Sentry pods..."

### ISSUE THREAD

**Issue by martaaay** [getsentry/sentry-react-native#3236]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)
- [x] `@sentry/wizard@latest`

**SDK version:** latest?

**`react-native` version:** 0.71.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No link, the wizard is failing here:

$ npx @sentry/wizard@latest -s -i reactNative
[sentry-cli] Using cached binary: /Users/[SNIP]/.npm/sentry-cli/ae4258-sentry-cli-Darwin-universal
Running Sentry Wizard...
version: 3.9.1 | sentry-cli version: 1.75.2
Sentry Wizard will help you to configure your project
Thank you for using Sentry :)
? Select the platforms you like to set up: iOS
will not configure android

Please open
https://sentry.io/account/settings/wizard/jv0i76kyw24hvq6fgv3o9jsi4catu692c4uatoipqzgt4vqjt39c5b4wcwdn94ij/?signup=1&project_platform=react-native
in your browser (if it's not open already)

✓ A compatible version of `react-native` is specified in `package.json`.

✓ Added `@sentry/react-native`
✓ A compatible version of `@sentry/react-native` is specified in `package.json`.
✓ Patched build script in Xcode project.
/ Adding Sentry pods...Error: Command failed: npx --yes pod-install --non-interactive --quiet

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)

To make sure everything is set up correctly, put the following code snippet into your application.
The snippet will create a button that, when tapped, sends a test event to Sentry.

After that check your project issues:
https://trust-check.sentry.io/issues/?project=4505664788758528

<Button title='Try!' onPress={ () => { Sentry.captureException(new Error('First error')) }}/>

- Adding Sentry pods...
`

**Configuration:**

n/a

---
**I have following issue:**

When running the wizard it fails with an error when installing sentry pods. It seems to be running pod-install without a target?

**Steps to reproduce:**
Run the command as above. It's probably something specific to my setup (?). Is there a verbose mode I can turn on to get more output?

**Actual result:**

n/a

**Expected result:**

n/a

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message, 
from the log that you shared, I see that the wizard continues after the pods' command fails.

To finish your RN Sentry setup you can just update your pods and everything should work as expected.  

Can you run `npx --yes pod-install --non-interactive` and share the error output? So we can debug what failed.

Note that due to planned vacations, our response time might be slower than usual.

**Comment by dotsenko** [comment]
any solution?

**Comment by krystofwoldrich** [comment]
@dotsenko Thank you for the message, could you share the command output?
