### ISSUE TITLE
User's id is in a strange format

### ISSUE THREAD

**Issue by borra27** [getsentry/sentry-react-native#3237]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.6.0

**`react-native` version:** 0.70.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue](https://indidlab.sentry.io/issues/4312554057/events/f96e4a59bc424da9aa929de1f9019494/?project=4505071845113856)]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
        dsn: sentryDSN,
        environment: "production",
        tracesSampleRate: 1.0,
        integrations: [
          new Sentry.ReactNativeTracing({
            routingInstrumentation,
          }),
        ],
});
```

---
**I have following issue:**

The user's id in the sentry is different from the format expected.
The format of the user id in our app must be one of the three formats below (or set to null)
1. Email format
2. {6 letters}.{32 letters}.{4 letters}
3. {10 letters}

But sometimes, at Sentry 
{8 letters}-{4 letters}-{4 letters}-{4 letters}-{12 letters} This type of user id is visible.

It doesn't always happen, it happens sometimes.

**Steps to reproduce:**

Set up Sentry's user after auto-login or sign-in.
```
Sentry.setUser({ id: `${id}` }); 
```

**Actual result:**

![image](https://github.com/getsentry/sentry-react-native/assets/25143695/fe8b6735-a75f-40f3-9ccc-171575c46db4)

Looks like {8 letters}-{4 letters}-{4 letters}-{4 letters}-{12 letters}
Why...?

**Expected result:**

![image](https://github.com/getsentry/sentry-react-native/assets/25143695/f00963c9-1474-49f2-8c33-88667bf2fdcd)
![image](https://github.com/getsentry/sentry-react-native/assets/25143695/fcd67bc0-903e-4b6c-a965-a58dbe5131d1)

It should look like a user id form of our app

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message and the details.

This `user.id` is the default Sentry fills when no `user.id` is set. It's an app installation id, more information [here](https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/). Likely the linked error happened before user logged in.
