### ISSUE TITLE
`@sentry/react-native` v5.9.0 is broken on iOS

### ISSUE THREAD

**Issue by birdofpreyru** [getsentry/sentry-react-native#3240]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.9.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

Compilation fails on the line https://github.com/getsentry/sentry-react-native/blob/15b60b6047257e48f1c04258672a7f230a2a72b4/ios/RNSentry.mm#L14 saying the file cannot be found.

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

[Actual result]

**Expected result:**

[Expected result]

**Comment by ibrahimtuna** [comment]
Same issue happening at my side as well.

**Comment by goguda** [comment]
Same issue here

**Comment by kahest** [comment]
This has been fixed in https://github.com/getsentry/sentry-react-native/releases/tag/5.9.1
