### ISSUE TITLE
`sentry-expo` deprecations plans

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3262]
`sentry-expo` is **not** deprecated yet and fully supports the current React Native 0.72 but likely won't get any new features, those will be added to `sentry-react-native`. This issue summarizes the deprecation plans.

- Previous Expo improvements project https://github.com/getsentry/sentry-react-native/issues/3102

```[tasklist]
### In Progress
- [ ] https://github.com/getsentry/sentry-react-native/issues/2083
- [ ] https://github.com/expo/expo/pull/25810
- [ ] https://github.com/expo/expo/pull/25859
- [ ] https://github.com/getsentry/sentry-wizard/issues/498
- [ ] https://github.com/getsentry/sentry-react-native/pull/3465
- [ ] https://github.com/getsentry/sentry-react-native/pull/3466
```

```[tasklist]
### MVP to deprecate `sentry-expo`
- [x] Verify unhandled rejected promise tracking in Expo Go/Expo builds
- [ ] https://github.com/getsentry/sentry-react-native/pull/3391
- [x] Support Expo Go (rewrite frames, only JS)
- [ ] https://github.com/getsentry/sentry-react-native/issues/3394
- [ ] https://github.com/getsentry/sentry-react-native/issues/3101
- [ ] https://github.com/getsentry/sentry-react-native/issues/3393
- [ ] https://github.com/getsentry/sentry-react-native/issues/3081
```

```[tasklist]
### Docs updates
- [x] Add Expo OTA Update source maps upload to Sentry Docs
- [x] Add migration docs to Expo Docs
- [x] Add migration docs to Sentry Docs
- [ ] https://github.com/getsentry/sentry-docs/pull/8631
- [ ] https://github.com/expo/expo/pull/25712
- [x] https://github.com/expo/sentry-expo/pull/385
```

```[tasklist]
### Future expo features
- [ ] https://github.com/getsentry/sentry-react-native/issues/3646
- [ ] https://github.com/getsentry/sentry-react-native/issues/3363
- [ ] https://github.com/getsentry/sentry-react-native/issues/3210
- [ ] https://github.com/getsentry/sentry-react-native/issues/3647
- [ ] https://github.com/getsentry/sentry-react-native/issues/2947
- [ ] https://github.com/getsentry/sentry-wizard/issues/285
- [ ] https://github.com/getsentry/sentry-react-native/issues/3608
```

### Not planned to be migrated
- ExpoBareIntegration (frames rewrite will be migrated, for additional tags, extras, and other event data will be supplied guide on how can be added by users)
- ExpoManagedIntegration (frames rewrite will be migrated, for additional tags, extras, and other event data will be supplied guide on how can be added by users)
- Post publish hook config used to set Sentry org, project, and authToken (will be replaced by envs or new solution)

[Internal Notion notes](https://www.notion.so/sentry/sentry-expo-deprecation-Touch-Base-cd669c0d6ce24422bdfd2b68961f8611)

**Comment by brentvatne** [comment]
thanks for putting this together and for the help here @krystofwoldrich! only feedback I have is re: Expo managed frames / Expo bare frames - those names in our sentry-expo repo are kind of misleading so I'll attempt to clarify that here:

the "Expo managed" integration should be called "Expo Go" (this app is a [sandbox for learning/experimenting](https://docs.expo.dev/get-started/expo-go/), I think even supporting it in Sentry is optional and I wouldn't be opposed to dropping that)

the "Expo bare" integration could just be called "Expo" (any app with the Expo SDK installed will work the same, no need to differentiate between managed or bare)

**Comment by krystofwoldrich** [comment]
@brentvatne Thank you for the context, I agree "Expo Go" is a lower priority (as Sentry is oriented on production bugs), but to keep a good dev experience, we would like the JS error captured during development in Expo Go to be correctly reported (source mapped) in Sentry.

**Comment by shanamatthews** [comment]
Hey @krystofwoldrich - I'm assuming this will need at least a small docs change to the [Expo section](https://docs.sentry.io/platforms/react-native/#expo) of docs. Just want to make sure that's it!

**Comment by krystofwoldrich** [comment]
@shanamatthews Yes, this will need a few changes in the docs, not only the Expo section but also a migration guide from the `sentry-expo` package to `sentry-react-native`.

**Comment by felix-lambert** [comment]
Hello the sourcemap is still not being uploaded. Can we have instruction on how to upload the sourcemap with sentry? On older version of expo I didn't have this problem. It has now been a few months i'm using expo and sentry without sourcemaps :)

**Comment by krystofwoldrich** [comment]
@felix-lambert Hi, thank touch for the message, could you share what Sentry SDK version and Expo version are you using and how you build the app?

The auto upload was fixed in the latest release of sentry-expo.

**Comment by felix-lambert** [comment]
I tried the last release and it has been fixed. The sourcemap seems to upload well to sentry on android and ios now. Well done ! :)

**Comment by krystofwoldrich** [comment]
`@sentry/react-native` now supports Expo out of the box!

Update to https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0 or newer to get all the new features.

Migration guides available:
- https://github.com/expo/fyi/blob/main/sentry-expo-migration.md
- https://docs.sentry.io/platforms/react-native/migration/sentry-expo/

**Comment by natasxa** [comment]
Can you help me with the error: "PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" ..."
Updated app to expo SDK 50 and now trying to update sentry-expo to @sentry/react-native...

**Comment by paulmthiebauth** [comment]
> Can you help me with the error: "PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" ..." Updated app to expo SDK 50 and now trying to update sentry-expo to @sentry/react-native...

Dealing with the same error right now trying to upgrade SDK

**Comment by brentvatne** [comment]
@natasxa @paulmthiebauth - do you have `@sentry/react-native` installed in your project? which version?

**Comment by natasxa** [comment]
@brentvatne sure I do, "@sentry/react-native": "5.10.0"

**Comment by jmacbhc** [comment]
> Can you help me with the error: "PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" ..." Updated app to expo SDK 50 and now trying to update sentry-expo to @sentry/react-native...

I am getting the same error while running npx expo-doctor@latest

**Comment by zowebs** [comment]
> > Can you help me with the error: "PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" ..." Updated app to expo SDK 50 and now trying to update sentry-expo to @sentry/react-native...
> 
> I am getting the same error while running npx expo-doctor@latest

I've got the same problem. Getting this error after running `npx expo-doctor@latest`
