### ISSUE TITLE
Wrong stack trace and code snippet after upload of source maps

### ISSUE THREAD

**Issue by milanirchlo** [getsentry/sentry-react-native#3270]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.9.0

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://e-commerce-1m.sentry.io/issues/4401752945/?project=6760402&query=is%3Aunresolved+dist%3A2032&referrer=issue-stream&statsPeriod=14d&stream_index=0)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn:
  'https://XXXX.ingest.sentry.io/XXXXX',
  tracesSampleRate: '0.1',
  maxBreadcrumbs: '40',
  release: 'br.com.riachuelo.app@' + getRelease() + '+' + getDistribution(), //example: br.com.riachuelo.app@4.3.0+2088
  dist: getDistribution(), //example: 2088
  debug: getDebugStatus(env), //false in release
  integrations: [
  new Sentry.ReactNativeTracing({
	  routingInstrumentation
  })
  ]
});
```

---
**I have following issue:**

When an error occurs where the root cause is in some Javascript code, the stack trace and code snippet displayed on the Sentry dashboard are completely wrong.

We did tests by sending the source maps manually and also automatically, according to the Sentry documentation. We also performed tests by sending the unminified bundle and using others version of Sentry and React Native.

**Steps to reproduce:**

To simulate an error we use the code below into file called CloudFireStore.js in our project, in this case the error occurs on line 21:

<img width="537" alt="cloud-firestore" src="https://github.com/getsentry/sentry-react-native/assets/144175490/6fa1b2e7-50bb-4546-beaf-b4498898401d">

However, in the Sentry dashboard, as shown in the screenshot added in *Actual result*, the code snippet and stack trace are incorrect.

**Actual result:**

Wrong stack trace and code snippet.

<img width="960" alt="issue-android" src="https://github.com/getsentry/sentry-react-native/assets/144175490/2f0cf951-cd11-4cdd-a0d2-ee9cbf39dff8">

**Expected result:**

Show stack trace and code snippet correctly.

Below an example in iOS release (same React Native project), in this case the stack trace and code snippet are correct.

![Screenshot 2023-09-05 at 09 57 11](https://github.com/getsentry/sentry-react-native/assets/144175490/8cf40b10-29c3-417d-9d81-b2c9cbde567c)

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message and the detailed testing. 

Could you try `metro-symbolicate` to check if it produces the correct stack trace for the error?

Steps:
1. Download the source map from Sentry -> Release -> Artifacts.
2. Save the raw minified stack from the Sentry Issue page to `stack.txt`. 
3. Run `npx metro-symbolicate index.android.bundle.map < stack.txt`.
4. Check the output.

This will help us to investigate why the stack trace is not symbolicated correctly.

**Comment by milanirchlo** [comment]
Hi @krystofwoldrich,

Thank you in advance for the support.

**stack.txt: to generate I selected "Minified" and "Raw stack trace" from issue page**

```
TypeError: undefined is not an object (evaluating 'o.gateways')
  at ? (app:///index.android.bundle:49770:47)
  at generatorResume([native code])
  at n(app:///index.android.bundle:23912:19)
  at v(app:///index.android.bundle:23924:12)
  at ? (app:///index.android.bundle:23929:10)
  at f(app:///index.android.bundle:79950:8)
  at y(app:///index.android.bundle:80004:22)
  at c(app:///index.android.bundle:79958:79)
  at ? (app:///index.android.bundle:23921:25)
  at ? (app:///index.android.bundle:49775:25)
  at ? (app:///index.android.bundle:50153:80)
  at value(app:///index.android.bundle:770:60)
  at ? (app:///index.android.bundle:49844:23)
  at value(app:///index.android.bundle:770:60)
  at ? (app:///index.android.bundle:31140:33)
  at value(app:///index.android.bundle:770:60)
  at value(app:///index.android.bundle:1204:155)
  at ? (app:///index.android.bundle:1088:27)
  at value(app:///index.android.bundle:1175:12)
  at value(app:///index.android.bundle:1087:28)
  at value([native code])
```

**output: npx metro-symbolicate index.android.bundle.map < stack.txt**

```
TypeError: undefined is not an object (evaluating 'o.gateways')
  at ? (null:null:null)
  at generatorResume(null:null:null)
  at n(null:null:null)
  at v(null:null:null)
  at ? (null:null:null)
  at f(null:null:null)
  at y(null:null:null)
  at c(null:null:null)
  at ? (null:null:null)
  at ? (null:null:null)
  at ? (null:null:null)
  at value(node_modules/@sentry/core/cjs/baseclient.js:1:<global>)
  at ? (null:null:null)
  at value(node_modules/@sentry/core/cjs/baseclient.js:1:<global>)
  at ? (null:null:null)
  at value(node_modules/@sentry/core/cjs/baseclient.js:1:<global>)
  at value(null:null:null)
  at ? (null:null:null)
  at value(null:null:null)
  at value(null:null:null)
  at value(null:null:null)
```

**Comment by krystofwoldrich** [comment]
@milanirchlo Thanks for testing this, since the output of `metro-symbolicate` is not symbolicated, this means the currently uploaded source map is not the correct one for the release of your app.

As you mentioned before you tried to generate different source maps and upload them to Sentry, you can do the same with the `metro-symbolicate` till you see the symbolicated source map. Make sure you are using the exact same source code as the release of the app (same branch, same tag...).

**Comment by jpinto321** [comment]
I am getting this same exact problem.
On iOS, errors show up correctly (correct line in the stack trace), while on Android they show an incorrect line in the stack trace.

If I try and Symbolicate an Android error that is showing correctly, I get the same type of output as @milanirchlo.

What would cause this? I mean, the upload process of the source maps is automatically done by Sentry, so I don't know how one would go about generating a different source map.

**Comment by jpinto321** [comment]
> @jpinto321 Could you you `Bundle React Native code and image` build phase? Are you using Hermes?

All fixed now.

What happened is that sometimes I need to do a release build to test something locally, and sentry ends up uploading the sourcemaps, even though I wouldn't want that because I'm trying some code changes.

I've re-built the release again, and now the sourcemaps and log errors are showing correctly.

It's unfortunate that there's no way (as far as I'm aware), to disable auto-uploading of sourcemps when doing a release build, because sometimes I just want to create a release build for testing, but not upload the sourcemaps, as they might have code changes that end up breaking the stack traces in future logs.

**Comment by krystofwoldrich** [comment]
@jpinto321 Thank you for the message. There is currently pending PR that add the disable Sentry auto upload flag.

- https://github.com/getsentry/sentry-react-native/pull/3296
