### ISSUE TITLE
Invalid UTF-8 continuation byte for index.android.bundle

### ISSUE THREAD

**Issue by voortexx** [getsentry/sentry-react-native#3272]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

I have a weird problem. We update our react-native from 0.71.7 to O.72.3.
And an issue appeared only for Android.

We use fastlane to generate and upload our files to Sentry, but since this update the `index.android.bundle.map` is no longer created. I saw that instead we have index.android.bundle.packager.map and we should merge it with another file.

So I look at the documentation and add the script like that

````
def create_sentry_release(app_name:, flavor_type:)
  # Create sourcemaps folder at project root
  sh("cd ../.. && mkdir -p sourcemaps")
  # Copy the sourcemaps in the new folder
  flavor = flavor_type  == 'Store' ? app_name : "#{app_name}#{flavor_type}"
  asset_bundle_directory_name = flavor_type  == 'Store' ? "createBundle#{app_name.capitalize}ReleaseJsAndAssets"
                               : "createBundle#{app_name.capitalize}#{flavor_type.capitalize}ReleaseJsAndAssets"
  sh('npx react-native bundle --platform android --dev false --entry-file index.js --reset-cache --bundle-output index.android.bundle --sourcemap-output index.android.bundle.packager.map --minify false')
  sh("cp ../app/build/generated/assets/#{asset_bundle_directory_name}/index.android.bundle ../../sourcemaps")
  sh("../../node_modules/react-native/sdks/hermesc/osx-bin/hermesc -O -emit-binary -output-source-map -out=index.android.bundle.hbc ../../sourcemaps/index.android.bundle")
  sh("rm -f ../../sourcemaps/index.android.bundle")
  sh("mv ../../sourcemaps/index.android.bundle.hbc ../../sourcemaps/index.android.bundle")
  sh("cp ../app/build/intermediates/sourcemaps/react/#{flavor}Release/index.android.bundle.packager.map ../../sourcemaps")
  sourcemap_path="../sourcemaps"
````

But the hermes script that should generate the `index.android.bundle.hbc` file failed with this error
<img width="1625" alt="Capture d’écran 2023-09-08 à 17 48 25" src="https://github.com/getsentry/sentry-react-native/assets/39954641/14c605c8-5184-494e-9e63-af959176e268">

In fact when I run `file -I ../sourcemaps/index.android.bundle` it output `application/octet-stream; charset=binary`

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, 
based on the content of the script I believe you run this after the React Native tooling generated the Hermes bundle and source map. Therefore you don't have to run the packager and hermes compiler manually, you can just use the generated files (copy them to ../../sourcemaps, upload them).

Here is an example on how to do this:
```ruby
def create_sentry_release(app_name:, flavor_type:)
  # Create sourcemaps folder at project root
  sh("cd ../.. && mkdir -p sourcemaps")
  # Copy the sourcemaps in the new folder
  flavor = flavor_type  == 'Store' ? app_name : "#{app_name}#{flavor_type}"
  asset_bundle_directory_name = flavor_type  == 'Store' ? "createBundle#{app_name.capitalize}ReleaseJsAndAssets"
                               : "createBundle#{app_name.capitalize}#{flavor_type.capitalize}ReleaseJsAndAssets"
  # Path of generated bundle (if Hermes -> hermes bundle)
  sh("cp ../app/build/generated/assets/#{asset_bundle_directory_name}/index.android.bundle ../../sourcemaps")
  # Path of generated sourcemap (if Hermes -> combined sourcemap)
  sh("cp ../app/build/generated/sourcemaps/react/#{flavor}Release/index.android.bundle.map ../../sourcemaps")
  sourcemap_path="../sourcemaps"
```

In case this doesn't work, please don't hesitate to comment here, we can reopen the issue and investigate more.
