### ISSUE TITLE
Build fails with undefined symbol facebook::hermes::HermesRuntime::enableSamplingProfiler()

### ISSUE THREAD

**Issue by rpander93** [getsentry/sentry-react-native#3275]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.9.1

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

Build fails with error:

> 
> ▸ Linking RCTTypeSafety
> ▸ Linking RNCAsyncStorage
> ▸ Linking RNSentry
> 
> ❌  Undefined symbols for architecture arm64
> > Symbol: facebook::hermes::HermesRuntime::enableSamplingProfiler()
> > Referenced from: -[RNSentry startProfiling] in RNSentry.o
> 
> ❌  ld: symbol(s) not found for architecture arm64
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Steps to reproduce:**
- Installed latest Sentry SDK into a otherwise running React Native app
- Step 2

**Actual result:**

Build fail

**Expected result:**

Build success

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message,
we are not able to reproduce the error.

Can you share a minimal reproducible example? And the output of `npx react-native info` from that project on your machine?

**Comment by rpander93** [comment]
I created a repo here: https://github.com/rpander93/sentry-reproduce

Build fails with:


ld: Undefined symbols:
  facebook::hermes::HermesRuntime::enableSamplingProfiler(), referenced from:
      -[RNSentry startProfiling] in RNSentry.o
  facebook::hermes::HermesRuntime::disableSamplingProfiler(), referenced from:
      -[RNSentry stopProfiling] in RNSentry.o
  facebook::hermes::HermesRuntime::dumpSampledTraceToStream(std::__1::basic_ostream<char, std::__1::char_traits<char>>&), referenced from:
      -[RNSentry stopProfiling] in RNSentry.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
