### ISSUE TITLE
Cyclic dependencies in sentry react native

### ISSUE THREAD

**Issue by jayshah123** [getsentry/sentry-react-native#3282]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.5.0

**`react-native` version:** 0.68.2

**Are you using Expo?**
- []  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    environment: 'Staging',
    release: `${appJson.version}-${appJson.jsVersion}`,
    dist: `${appJson.versionCode}`,
    beforeSend: sentryFilter,
    enableAutoPerformanceTracing: true,
    enableWatchdogTerminationTracking: false,
    tracesSampleRate: 1.0,
    integrations: [
      new Sentry.ReactNativeTracing({
        tracingOrigins: ['localhost', 'example.com', /^\//],
        routingInstrumentation,
      }),
    ],
  });
```

---
**I have following issue:**

App freezes on launch due to cyclic dependencies.

**Steps to reproduce:**
- Install `@sentry/react-native`
- Step 2

**Actual result:**

```
Require cycle: node_modules/@sentry/react-native/dist/js/measurements.js -> node_modules/@sentry/react-native/dist/js/tracing/index.js -> node_modules/@sentry/react-native/dist/js/tracing/reactnativetracing.js -> node_modules/@sentry/react-native/dist/js/measurements.js
```

Seeing the require cycle mentioned above.

**should run fine**

It should run fine

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, this message is just a warning the app should run with it.

We will remove it and add a check to prevent this in the future.
https://github.com/getsentry/sentry-javascript/pull/3631
