### ISSUE TITLE
Don't mark native `apply` methods as `in-app` in Expo apps 

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3286]
### Description

Sentry expo rewrite frames integration is modifying some native frames which causes them to be marked as `in-app`.

`sentry-expo` https://github.com/expo/sentry-expo/blob/main/src/sentry.ts#L91

Fix from `sentry-react-native` https://github.com/getsentry/sentry-react-native/blob/4cc74aad8da359905a92e4b720375384646a4453/src/js/integrations/rewriteframes.ts#L35

- Might be resolved by https://github.com/getsentry/sentry-react-native/issues/3262

**Comment by lucas-zimerman** [comment]
@krystofwoldrich sentry expo didn't receive any updates in a while, is this issue still needed?

**Comment by krystofwoldrich** [comment]
Since Expo SDK 50 `@sentry/react-native` replaces `sentry-expo`.

https://docs.sentry.io/platforms/react-native/migration/sentry-expo/
