### ISSUE TITLE
Failed to load file referenced by SENTRY_PROPERTIES caused by: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by mym0404** [getsentry/sentry-react-native#3295]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.9.2

**`react-native` version:** 0.72.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

**Xcode 15** build phase failed with 

![image](https://github.com/getsentry/sentry-react-native/assets/33388801/40263960-cd9e-4ff7-8db8-d2a040be40fd)

```
Node found at: /usr/local/bin/node
error: Failed to load file referenced by SENTRY_PROPERTIES (sentry.properties)
  caused by: Operation not permitted (os error 1)
thread 'main' panicked at 'Config not bound yet': src/config.rs:85

   0: backtrace::backtrace::trace

+ [[ Debug = *Debug* ]]
+ echo 'Debug build. Modules are not collected.'
Debug build. Modules are not collected.
+ exit 0
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

I did set full disk access for Xcode correctly
![image](https://github.com/getsentry/sentry-react-native/assets/33388801/a44596c5-f196-45d1-b39c-b85936f84bb7)

My Build Phase script

```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

# RN 0.69+
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_CLI="../node_modules/@sentry/cli/bin/sentry-cli"

/bin/sh -c "$WITH_ENVIRONMENT \"$SENTRY_CLI react-native xcode $REACT_NATIVE_XCODE\""

# RN 0.46 – 0.68
# ../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
#  ../node_modules/react-native/scripts/react-native-xcode.sh

# All versions
/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh

```

**Steps to reproduce:**
- install sentry into react native project 
- build with Xcode 15 in debug build

**Comment by mym0404** [comment]
It seems to not related. [SO](https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w).

This is more about Xcode configuration maybe?

**Comment by krystofwoldrich** [comment]
Hi, thank you for the information and the build phase script. 

The script looks good. From the log, I also see other build phases failed. 

Likely, as you mentioned, this was not related.
