### ISSUE TITLE
Logging outputModulesPath twice

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [getsentry/sentry-react-native#3308]
How does the following output make sense in the [`ModulesCollector`](https://github.com/getsentry/sentry-react-native/blob/main/src/js/tools/ModulesCollector.ts#L106) (both saving and resolving modules to/from the same path (`outputModulesPath`))?

```
logger.info('Saving modules to', outputModulesPath);
logger.info('Resolving modules from paths', outputModulesPath);
```

Example output:
```
Sentry Logger [info]: Saving modules to /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json
Sentry Logger [info]: Resolving modules from paths /Users/johndoe/Documents/repos/sentry-test-logger/android/app/src/main/assets/modules.json
```

Maybe the variable `modulesPaths` was supposed to have been used for `Resolving modules from paths`?

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message,
the `Resolving modules from paths` log should show the paths that are considered when collecting the modules. Typically this will be the `node_modules` dir of the project.

Exactly, `modulesPaths` should've been used.

- https://github.com/getsentry/sentry-react-native/pull/3316
