### ISSUE TITLE
`attachScreenshot` option can result in a blank UI on Android

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry-react-native#3314]
**Platform:**
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.9.2

**`react-native` version:** 0.71.13

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://a8e9796651e6b88bb70e505002fc359d@o169785.ingest.sentry.io/4505951781191680',
  enabled: false,
  attachScreenshot: true,
});
```

---
**I have following issue:**

There seems to be a timing-related issue between `@sentry/react-native` (or `sentry-android`) and `react-native-screens` / `@react-navigation/native-stack` on Android. If Sentry tries to capture a screenshot near to/during navigation occurring and a new activity being mounted the activity's view becomes invisible (but it is still possible to interact with the invisible elements).

**Steps to reproduce:**
- Enable `attachScreenshot` option
- Call `Sentry.captureException()` while navigation is occuring.

**Actual result:**

UI displays blank. See video below.

**Expected result:**

`attachScreenshot` does not interfere with the rendering of the UI.

**Minimal repro:**

Clone https://github.com/liamjones/sentry-screenshot-bug, build & launch the app then tap the Navigate button. If the problem doesn't happen try tweaking the constants in the top of `App.tsx`. Since it's a timing-related issue it's a fine balance between triggering the issue reliably vs asking the JS thread to do too much. I think it's also related to the layout of the newly mounted screen taking a long time (hence rendering a bunch of SVGs in the screen in the repro). Video using the repo which shows it happening 2 out of 3 times: https://drive.google.com/file/d/14p0Cv60Gv1rLcVLHaT7YHKDxT-RmrbxD/view?usp=sharing

**Comment by krystofwoldrich** [comment]
Thank you for the information and the reproducible example,
we will check this.

**Comment by krystofwoldrich** [comment]
> Also, something I noticed while building this repro, attachScreenshot: true seems to be doing processing even when enabled: false. Is this a separate bug or is that deliberate?

I believe screenshots should not be taken when SDK is disabled, let's handle this as a separate issue.

**Comment by krystofwoldrich** [comment]
Though the consts are machine-dependent I'm posting the config I manager to reproduce the issue with.

```js
const INTERVAL_FOR_TAKING_SCREENSHOTS = 5;
const TIMEOUT_TO_STOP_CAPTURING_SCREENSHOTS_AFTER_DETAILS_SCREEN_IS_RENDERED = 100;
const HOW_MANY_SVGS_TO_RENDER_ON_DETAILS_SCREEN = 100;
```

**Comment by liamjones** [comment]
> Let's handle this as a separate issue.

Sure, I'll get one raised.

**Comment by krystofwoldrich** [comment]
Using the `pixelCopy` API fixes the issue.

https://github.com/getsentry/sentry-java/tree/feat/pixel-copy-api-for-screenshots
