### ISSUE TITLE
`attachScreenshot: true` still takes screenshots even when `enabled: false`

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry-react-native#3317]
**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.9.2

**`react-native` version:** 0.71.13

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://a8e9796651e6b88bb70e505002fc359d@o169785.ingest.sentry.io/4505951781191680',
  enabled: false,
  attachScreenshot: true,
});
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- Configure Sentry with `attachScreenshot: true` and `enabled: false`.
- Connect debugger and set breakpoints in 'take screenshot' functions of Android/iOS native modules
- Call `Sentry.captureException()`

**Actual result:**

Breakpoints hit as native modules try to capture a screenshot

**Expected result:**

Screenshots not taken as no reporting is going to happen

**Comment by krystofwoldrich** [comment]
Hi, thank you for the information,
I agree, I would also expect the screenshot not to be taken when the SDK is disabled.

**Comment by krystofwoldrich** [comment]
This is caused by the Screenshot integration being hooked to captureException and not using the event processor.

https://github.com/getsentry/sentry-react-native/blob/5af0e04ecdb7e90a485aeb261ad96a743bc0898f/src/js/client.ts#L55
