### ISSUE TITLE
Xcode 15 build fail - module 'SentryPrivate' not found

### ISSUE THREAD

**Issue by leotm** [getsentry/sentry-react-native#3322]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.8.1

**`react-native` version:** 0.71.13

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

- https://github.com/MetaMask/metamask-mobile/issues/6158

**Configuration:**

https://github.com/MetaMask/metamask-mobile/blob/main/app/util/sentryUtils.js#L143-L162

---
**I have the following issue:**

Loving Sentry ^ but run into this build error since Xcode 15 beta

**Steps to reproduce:**

- Steps detailed in comments: https://github.com/MetaMask/metamask-mobile/issues/6158
  - Steps detailed in commits: https://github.com/MetaMask/metamask-mobile/pull/7114

**Actual result:**

Build error

**Expected result:**

No error

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message,
I read thru the mentioned issue (https://github.com/MetaMask/metamask-mobile/issues/6158) is the error happening with Xcode 15 both on the main metamask-mobile branch and in your PR?

Recently we solved a very similar issue caused by extra c compiler flags. I check your Podfile and I don't see any, but maybe some library changes them?

I'll try to clone the project to reproduce the error.

**Comment by leotm** [comment]
appreciate the speedy reply ^ i look too thru
- https://github.com/getsentry/sentry-react-native/issues/3186

<img width="2050" alt="Screenshot 2023-10-02 at 8 32 24 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/90f41784-92d2-4f6f-ab3e-e9f7a9ea7ea5">

not too helpful, but expanded

<img width="2044" alt="Screenshot 2023-10-02 at 8 32 42 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/0475cc62-afa1-497b-9480-a5ef58c1f8bd">

couldn't spot `-Wno-documentation` to remove (noting couple initial Sentry flags there)

then also tried messing around with some of these flags but to no avail

**Comment by leotm** [comment]
<details><summary>node node_modules/react-native/scripts/generate-codegen-artifacts.js</summary>

```console
➜  metamask-mobile git:(react-native-0.71.13-xcode-15-beta-8) ✗ node node_modules/react-native/scripts/generate-codegen-artifacts.js \
                --path . \
                --outputPath codegen
[Codegen] Processing react-native core libraries
[Codegen] Found react-native


[Codegen] >>>>> Searching for codegen-enabled libraries in /Users/leo/Documents/GitHub/metamask-mobile/node_modules
[Codegen] Found @react-native-community/blur
[Codegen] Found @sentry/react-native
[Codegen] Found react-native-screens
[Codegen] Found @react-native-community/datetimepicker
[Codegen] CodegenConfig Deprecated Setup for @react-native-community/slider.
    The configuration file still contains the codegen in the libraries array.
    If possible, replace it with a single object.

BEFORE:
    {
      // ...
      "codegenConfig": {
        "libraries": [
          {
            "name": "libName1",
            "type": "all|components|modules",
            "jsSrcsRoot": "libName1/js"
          },
          {
            "name": "libName2",
            "type": "all|components|modules",
            "jsSrcsRoot": "libName2/src"
          }
        ]
      }
    }

    AFTER:
    {
      "codegenConfig": {
        "name": "libraries",
        "type": "all",
        "jsSrcsRoot": "."
      }
    }

[Codegen] Found @react-native-community/slider


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
  

[Codegen] >>>>> Searching for codegen-enabled libraries in the app


[Codegen] >>>>> Processing FBReactNativeSpec
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/FBReactNativeSpecMbZ9YU/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing rncore
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/rncorec1EIBX/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing rnblurview
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/rnblurviewL14bJt/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing RNSentrySpec
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/RNSentrySpeciNnD6p/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing rnscreens
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/rnscreensuxljGH/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing RNDateTimePickerCGen
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/RNDateTimePickerCGenjb88u8/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


[Codegen] >>>>> Processing RNCSlider
[Codegen] Generated schema: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/RNCSliderBGs0zf/schema.json
[Codegen] Generated artifacts: codegen/build/generated/ios


>>>>> Creating component provider
Generated schema list: /var/folders/6f/45z345qn1nx4l85rv0kx8y0m0000gn/T/rn-tmp-schema-list.json
Generated provider in: codegen/build/generated/ios


[Codegen] Done.
```

</details>

**Comment by leotm** [comment]
yes should be happening on `main` too ^ but my PR fixes Xcode 15 issues i've encountered so far

**Comment by krystofwoldrich** [comment]
I'm getting the same `SentryPrivate` error now.

Just to keep track.

1. I cloned https://github.com/MetaMask/metamask-mobile/commit/8daa624dd3c6a719f801d92b81407c316f372ebf
2. Applied arc fix https://github.com/MetaMask/metamask-mobile/issues/6158#issue-1661667501
3. Applied boost fix https://stackoverflow.com/a/77136535/8378456

```
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        end
      end
  end
```

Since the last one adjusts the compiler flags it might be the similar issue as https://github.com/getsentry/sentry-react-native/issues/3186

**Comment by krystofwoldrich** [comment]
@leotm 

I'm not getting the `module 'SentryPrivate' not found` error. Here is what I did:

1.  I cloned https://github.com/MetaMask/metamask-mobile/commit/8daa624dd3c6a719f801d92b81407c316f372ebf
2. Applied arc fix https://github.com/MetaMask/metamask-mobile/issues/6158#issue-1661667501 (I assume you have that fixed on your machine)
3. ~Have not applied boost fix [stackoverflow.com/a/77136535/8378456](https://stackoverflow.com/a/77136535/8378456)~
4. Removed the custom `react_native_post_install` function https://github.com/MetaMask/metamask-mobile/blob/8daa624dd3c6a719f801d92b81407c316f372ebf/ios/Podfile#L23C1-L51C6
5. Called the `react_native_post_install` from the react native package.
```ruby
# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
react_native_post_install(
  installer,
  config[:reactNativePath],
  :mac_catalyst_enabled => false
)
```

Let me know if this works for you.

**Comment by leotm** [comment]
cheers @krystofwoldrich! got it working, noting below what i did too

reverted branch/mixpanel git submodule changes again for successful `yarn setup` in CI and locally
re-applied the `IPHONEOS_DEPLOYMENT_TARGET` bumps from `8.0` to `12.0` locally for now
TODO: @jpcloureiro's suggestion https://github.com/MetaMask/metamask-mobile/pull/7114#issuecomment-1746493721

removed our custom `react_native_post_install` (the culprit)
_referring to RN [#L249-L253](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L249-L253) right? i reckon lines `#L197-L202` was right earlier, but `main`'s prob changed already
which makes [permalink](https://github.com/facebook/react-native/blob/d0f750e15d1fb2e75e1263c66ac5f5be31aa0dc5/packages/react-native/scripts/react_native_pods.rb#L249-L253)s handy (;_

<img width="1536" alt="Screenshot 2023-10-06 at 3 05 44 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/e48c47b2-6552-4001-a753-a8af4e9d7760">

no Sentry error 🎉 locally ran `cp node_modules/@metamask/mobile-provider/dist/index.js app/core/InpageBridgeWeb3.js`
TODO: so we need to tidy this our side, most likely within `scripts/build.sh`

<img width="1506" alt="Screenshot 2023-10-06 at 3 32 38 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/8e5934fe-fed0-4359-bbce-f9f16decbf24">

<img width="1511" alt="Screenshot 2023-10-06 at 3 06 17 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/2f201686-351a-429d-b169-b2151b3f8950">

Flipper strikes again, solved locally for now

<img width="1533" alt="Screenshot 2023-10-06 at 3 24 31 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/b1b1349f-ab1d-45d1-ad7c-0d8d5459f0cf">

TODO: need to investigate exactly how this is happening
since `FB_SONARKIT_ENABLED` should be disabled via https://github.com/MetaMask/metamask-mobile/pull/7114/commits/1e432e05dc3ba74e9cd9d548686a39ad38b269ad and https://github.com/MetaMask/metamask-mobile/pull/7114/commits/1e432e05dc3ba74e9cd9d548686a39ad38b269ad (discovered from prev seperate investigation https://github.com/MetaMask/metamask-mobile/pull/6955)

then similar again

<img width="1504" alt="Screenshot 2023-10-06 at 3 33 25 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/a5cf88b0-f2e3-4822-a51d-f9104180b085">

<img width="1535" alt="Screenshot 2023-10-06 at 3 34 15 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/b74ca8fd-5d06-4414-82ad-9c2b37284605">

<img width="1530" alt="Screenshot 2023-10-06 at 3 35 32 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/1d529eef-ed5e-4536-8e05-16e59e0cb99f">

success 🎉

<img width="565" alt="Screenshot 2023-10-06 at 3 36 40 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/0d3c73f6-c20a-4191-bdab-56a5b7b6b4c1">

<img width="2056" alt="Screenshot 2023-10-06 at 3 45 09 pm" src="https://github.com/getsentry/sentry-react-native/assets/1881059/0cf4cf40-63bb-4662-97c6-5284bac02f80">

appreciate your help once again

**Comment by krystofwoldrich** [comment]
@leotm Awesome to hear. Thanks for the message.
