### ISSUE TITLE
Xcode 14.3.1 build failure "env: node: No such file or directory"

### ISSUE THREAD

**Issue by ds8k** [getsentry/sentry-react-native#3325]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.10.0

**`react-native` version:** 0.70.13

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

Bundle React:
```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"

set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT \"../node_modules/@sentry/cli/bin/sentry-cli react-native xcode $REACT_NATIVE_XCODE\""
/bin/sh -c "$WITH_ENVIRONMENT ../node_modules/@sentry/react-native/scripts/collect-modules.sh"
```

Upload Symbols:
```
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
if [ -f "$WITH_ENVIRONMENT" ]; then
    . "$WITH_ENVIRONMENT"
fi 
export SENTRY_PROPERTIES=sentry.properties
[ "$SENTRY_INCLUDE_NATIVE_SOURCES" = "true" ] && INCLUDE_SOURCES_FLAG="--include-sources" || INCLUDE_SOURCES_FLAG=""
../node_modules/@sentry/cli/bin/sentry-cli debug-files upload "$INCLUDE_SOURCES_FLAG" "$DWARF_DSYM_FOLDER_PATH"
```
---
**I have the following issue:**

Following the migration steps for 4.8 to 4.9, my app fails to build during the `Bundle React Native` script.

**Steps to reproduce:**
 - Follow migration steps and modify build phase script as suggested
 - Attempt to build

**Actual result:**

Build fails with error:
```
Node found at: ~/.n/bin/node

env: node: No such file or directory

Command PhaseScriptExecution failed with a nonzero exit code
```

**Expected result:**

App builds successfully

**Comment by krystofwoldrich** [comment]
@ds8k Could you share what your build phases looked like before the update?

Does the app build without this line `/bin/sh -c "$WITH_ENVIRONMENT ../node_modules/@sentry/react-native/scripts/collect-modules.sh"`?

If `$NODE_BINARY` is not specified RN defaults to `node`. From `Node found at: ~/.n/bin/node` I assume your node is at `~/.n/bin/node` can you set `export NODE_BINARY=~/.n/bin/node`?

**Comment by ds8k** [comment]
@krystofwoldrich My build phases looked like the standard RN ones:
```
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

Adding `export NODE_BINARY` in the two scripts actually worked. Why is `WITH_ENVIRONMENT` not working?

**Comment by krystofwoldrich** [comment]
That depends on how your `.xcode.env` looks like, by default it contains `export NODE_BINARY=$(command -v node)`, which could be the culprit. Otherwise adding `export NODE_BINARY=~/.n/bin/node` to `.xcode.env` should also fix the issue.
