### ISSUE TITLE
Wait for `has-sorucemap-debugid` process to exit

### ISSUE THREAD

**Issue by jbagaresgaray** [getsentry/sentry-react-native#3334]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.11.0

**`react-native` version:** 0.71.13

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**
```
Copy `debugId` from packager source map to Hermes source map...

Packager source map does not have `debugId`.

Check generated source map for Debug ID: /home/expo/workingdir/build/android/app/build/generated/sourcemaps/react/stagingRelease/index.android.bundle.map does not contain 'debugId' nor 'debug_id'.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* Where:

Script '/home/expo/workingdir/build/node_modules/@sentry/react-native/sentry.gradle' line: 132
```
**Actual result:**

![image](https://github.com/getsentry/sentry-react-native/assets/3625802/fc72a3ea-7099-4132-8543-d92ef74fd10a)

**Expected result:**

No error and build should be successful

**Comment by AndyMeagher** [comment]
Also experiencing this and am unable to create an Android build. Are there any workarounds?

**Comment by bex-buri** [comment]
I'm also getting this issue even though I checked sentry.gradle and the fix has already been applied.

**Comment by bex-buri** [comment]
> @bex-buri Could you share your build log?

Sure. It works fine in development when running metro. It's only when building the release apk that the issue occurs.

![Untitled](https://github.com/getsentry/sentry-react-native/assets/105632836/68e51b77-ca90-4d90-9667-cd6c974a4606)

**Comment by krystofwoldrich** [comment]
@bex-buri Based on the log this looks like a different error than the one in this issue, could you try this with `export SENTRY_LOG_LEVEL=debug` and share the output in a new issue?

**Comment by bex-buri** [comment]
@krystofwoldrich Sorry, you were right. It was a different issue and related to our own self-hosted url being down at the time of testing. We've resolved the issue now. Thanks.

**Comment by Yuniac** [comment]
Hey there... same issue here :(


```
> Task :app:createBundleProductionReleaseJsAndAssets_SentryUpload_huntapp.gg@1.8.7+62_62 FAILED
Copy `debugId` from packager source map to Hermes source map...
Packager source map does not have `debugId`.
Check generated source map for Debug ID: /Users/x/Desktop/work/hunt/apps/hunt-mobile/android/app/build/generated/sourcemaps/react/productionRelease/index.android.bundle.map does not contain 'debugId' nor 'debug_id'.

Sentry Source Maps upload will include the release name and dist.
Sentry-CLI arguments: [/Users/x/Desktop/work/hunt/apps/hunt-mobile/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /Users/x/Desktop/work/hunt/apps/hunt-mobile/android/app/build/generated/assets/createBundleProductionReleaseJsAndAssets/index.android.bundle, --sourcemap, /Users/yusufsabbag/Desktop/work/hunt/apps/hunt-mobile/android/app/build/generated/sourcemaps/react/productionRelease/index.android.bundle.map, --release, huntapp.gg@1.8.7+62, --dist, 62]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleProductionReleaseJsAndAssets_SentryUpload_huntapp.gg@1.8.7+62_62'.
> A problem occurred starting process 'command '/Users/x/Desktop/work/hunt/apps/hunt-mobile/node_modules/@sentry/cli/bin/sentry-cli''

```

I was on version `^5.15.2` then I updated to `^5.17.0` but that didn't change anything.

Android. MacOs. Sentry.io. react-native: 0.73.1

**Comment by PanosPapad** [comment]
Why was the issue closed? What is the solution to the last question? I have the same issue.
