### ISSUE TITLE
Upload Sourcemaps from `eas update`

### ISSUE THREAD

**Issue by nandorojo** [getsentry/sentry-react-native#3363]
A huge, huge painpoint currently is uploading sourcemaps from the result of `npx eas update` (Expo's over-the-air update service). It works for `eas build` for new builds, but not for updates. There are what feels like dozens of issues and feature requests for this on the Expo repo. It requires a script that reads the outputs of `dist` and uploads them to Sentry.

Could you please add a CLI script to this? The Expo team has said they've tried contacting Sentry about it. Some sort of `postPublish` hook in the `app.config.ts` file would be a great DX. 

I currently cannot use Sentry in React Native easily due to this, since most of our updates happen over-the-air. It would be a huge contribution to over a hundred devs I know of to fix this.

Thank you!

**Comment by krystofwoldrich** [comment]
Hi @nandorojo,
thank you for the message, we are aware of this and are working with the Expo team.

Currently, we are starting the process of moving away from `sentry-expo` to `sentry-react-native` supporting Expo out of the box.

- https://github.com/getsentry/sentry-react-native/issues/3262

And one of the items on the features list is `sourcemaps for eas update`.

**Comment by nandorojo** [comment]
@krystofwoldrich thanks for letting me know. Adding that would be **awesome.** At the moment I have no visibility into errors on our app.

**Comment by nandorojo** [comment]
@krystofwoldrich do you know when this feature in particular might go live? Or is there a Gist somewhere with a CLI script that I can run manually after `eas update` completes to upload source maps? I am willing to test or help if I can. It's a dire issue on our part. Thank you.

**Comment by krystofwoldrich** [comment]
@nandorojo Currently we don't have a timeline.

There are some community scripts [here](https://github.com/expo/sentry-expo/issues/335) that might be useful.
- https://github.com/expo/sentry-expo/issues/335

**Comment by rikur** [comment]
+1 for a fix, workaround take forever to test and I couldn't get them to work

**Comment by mikevercoelen** [comment]
Bump any update on this?

**Comment by RobertoJoseph** [comment]
Any updates on this?

**Comment by krystofwoldrich** [comment]
As mentioned before this is part of 
- https://github.com/getsentry/sentry-react-native/issues/3262

We are taking a step towards a new simple way of uploading source maps for eas updates.

- [50.0.0-preview.7](https://www.npmjs.com/package/expo/v/50.0.0-preview.7) includes Debug IDs (needed for source maps resolution)
- [Update to Sentry Metro Serializer](https://github.com/getsentry/sentry-react-native/pull/3477) (to handle correctly Hermes source maps debug ID)

 After these changes, the process will consist only of calling `eas update` and `sentry-cli upload`. We will update this issue when the mentioned changes are released and also publish a detailed guide to our docs.

**Comment by krystofwoldrich** [comment]
Hello everyone,
`@sentry/react-native` now supports Expo out of the box!

You can upload source maps for EAS Update as easily as `npx sentry-expo-upload-sourcemaps dist`. 
Source maps uploads are now configured using `@sentry/react-native/expo`.

```json
{
  "expo": {
    "plugins": [
      [
        "@sentry/react-native/expo",
        {
          "url": "https://sentry.io/",
          "warning": "DO NOT COMMIT YOUR AUTH TOKEN",
          "authToken": "Click to generate token",
          "project": "android",
          "organization": "demo"
        }
      ]
    ]
  }
}
```

Update to https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0 or newer to get all the new features.

Migration guides available:
- https://github.com/expo/fyi/blob/main/sentry-expo-migration.md
- https://docs.sentry.io/platforms/react-native/migration/sentry-expo/
