### ISSUE TITLE
No method named startSpan

### ISSUE THREAD

**Issue by pranshuchittora** [getsentry/sentry-react-native#3370]
### Description

Hey, As per the docs here https://docs.sentry.io/platforms/react-native/performance/instrumentation/custom-instrumentation/#start-span

There should be a method named `startSpan` on the RN SDK. Unfortunately there's no such method available.

**Comment by krystofwoldrich** [comment]
Hi,
thanks for the message, you can temporarily use the core exports before we add this to `@sentry/react-native`.

```js
import { startSpan } from '@sentry/core';
```
