### ISSUE TITLE
SIGPIPE exception on React Native 0.72.6 only iOS version

### ISSUE THREAD

**Issue by fcaldarelli** [getsentry/sentry-react-native#3378]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm not able to reproduce

### Expected Result

-

### Actual Result

-

### Product Area

Issues

**Comment by kahest** [comment]
Hey @fcaldarelli thanks for writing in - could you share links to the events in Sentry either here or via karl.struggl@sentry.io? Do you have reason to suspect the issues are caused by Sentry?

**Comment by kahest** [comment]
@fcaldarelli thank you for the links - it looks like this happens a while (seconds and up to 1-2 minutes) after the app went to background. It's likely that the app tried to access a socket that is already closed at this time. I don't see an indication that this is caused by Sentry, but we'll investigate. In case your app performs network activity while in background, this might be the root cause.

**Comment by fcaldarelli** [comment]
@kahest we don't make activities in background, then in iOS background activities need specific permissions, that we don't require.

**Comment by fcaldarelli** [comment]
Hi @kahest , we should have fix the bug dued to a framework from third-party vendor that made actions when app was going  to background. Thanks for your time and support!

**Comment by kahest** [comment]
@fcaldarelli thanks for reporting back, glad you got it sorted out 👍

**Comment by fcaldarelli** [comment]
Ho @kahest , I have to reopen this issue because we get the error in sentry but we have not any XCCrash in Xcode. I'll send you more details via email

**Comment by kahest** [comment]
@fcaldarelli on Apple systems, people can (and very often will) opt out of sending analytics data to Apple (see e.g. [here for iOS](https://support.apple.com/en-us/HT202100), which means that crashes from their devices won't show up in Xcode or App Store Connect. Also, the filters might be set differentle in Xcode (usually only shows one version whereas on Sentry we show all versions unless you filter). Another aspect is that processing of crashes might take longer on Apple's side while we usually show you crashes within a few seconds.

**Comment by fcaldarelli** [comment]
@kahest What does `<redacted>` mean near app name?

![Screenshot 2023-11-20 alle 12 55 31](https://github.com/getsentry/sentry-react-native/assets/4108673/d7983829-4244-410f-86ef-2fa131df02a6)

**Comment by krystofwoldrich** [comment]
@fcaldarelli The `sentry-cocoa` SDK sends `<reducted>` in production builds of the applications. If you upload native debug symbols the name will by symbolicated on the server.

You can configure automatic debug symbols upload https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-debug-symbols-upload

Or upload native symbols manually https://docs.sentry.io/product/cli/dif/#uploading-files
