### ISSUE TITLE
Support breadcrumbCallback in config

### ISSUE THREAD

**Issue by RickDT** [getsentry/sentry-react-native#339]
OS:
- [ ]  Windows
- [x]  macOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.11.1
3.10.10
GuitarTunes@1.1.1 /Users/rickdt/Documents/Projects/Optek/FRET-GT-ReactNative
├── app-icon@0.6.3
├── base-64@0.1.0
├── base64-arraybuffer@0.1.5
├── fast-memoize@2.2.8
├── fuse.js@3.2.0
├── immutable@3.8.2
├── lodash@4.17.4
├── midi-file-parser@1.0.0
├── midi-player-js@1.1.4
├── midiconvert@0.4.2
├── pitchfinder@2.0.7
├── prop-types@15.6.0
├── re-reselect@0.5.0
├── UNMET PEER DEPENDENCY react@16.2.0
├── react-native@0.50.4
├── react-native-billing@2.4.0
├── react-native-fbsdk@0.7.0
├── react-native-fetch-blob@0.10.8 (git://github.com/big-swing/react-native-fetch-blob.git#6a43877c5f2985efe929a2786c70bc7b29bf7dca)
├── react-native-icon@0.2.10
├── react-native-mail@3.0.5
├── react-native-mixpanel@0.0.16
├── react-native-pdf@2.0.7
├── react-native-recording@0.2.0
├── react-native-sentry@0.30.3
├── react-native-sound@0.10.4
├── react-native-sqlite-storage@3.3.4
├── react-native-svg@6.0.0
├── react-native-tab-view@0.0.69
├── react-native-video@2.0.0
├── react-redux@5.0.6
├── recompose@0.25.1
├── redux@3.7.2
├── redux-immutable@4.0.0
├── redux-logger@3.0.6
├── redux-saga@0.15.6
└── reselect@3.0.1

npm ERR! peer dep missing: react@16.0.0, required by react-native@0.50.4
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
  breadcrumbCallback: function(crumb) { 
    return crumb 
  }
}).install()
```

---
I have following issue:

I would like to filter some breadcrumbs that are automatically collected due to noise. Could the RN SDK support the breadcrumbCallback config setting from the JS SDK?

**Steps to reproduce:**
Attempt to alter Breadcrumbs via config setting.

**Actual result:**
All Breadcrumbs go through. Callback is not called.

**Expected result:**
Callback is used to filter Breadcrumbs

**Comment by yarian** [comment]
I just spent a bit wondering why that config option was not working. Of course disabling `disableNativeIntegration: true` makes it work since then it relies 100% on the Raven client. The cost is you get non of the app crashes.

**Comment by HazAT** [comment]
We will soon do a rewrite of the react-native SDK which should fix this issue.
Please stay tuned.

**Comment by reneeichhorn** [comment]
Any news on that? Or is there any other workaround to filter out some of the XHR breadcrumbs?

**Comment by ongmin** [comment]
Any updates on this feature?

**Comment by prsauer** [comment]
Curious as well. Even just being able to disable fetch/xhr crumbs would be very helpful...

**Comment by HazAT** [comment]
We released a new version of the SDK `@sentry/react-native` which uses the unified JS API where you are able to do this.
See for more info: https://github.com/getsentry/sentry-react-native/issues/612
