### ISSUE TITLE
denyUrls does not not filter URLs from HttpClient

### ISSUE THREAD

**Issue by daniel-johns-99** [getsentry/sentry-react-native#3404]
**OS:**
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.13.0

**`react-native` version:** 0.67.5

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
      integrations: [
        new HttpClientIntegration({
          failedRequestStatusCodes: [[400, 599]],
          failedRequestTargets: [/.*/],
        }),
      ],
      denyUrls: [
        /google\.com/i,
      ],
});
```

[Description]

**Steps to reproduce:**
- Create a XHR request to Google which causes a status code between 4XX>599

**Actual result:**

- Observe that the Event is sent as a error to Sentry
- In Sentry UI and the raw JSON event note the `google.com` url has clearly been distinguished as a tag and indexed as the `url` property making it look like a first class citizen property.

**Expected result:**

Expect Sentry to Drop the event with this debug message: Event dropped due to being matched by `denyUrls` option.

### Additional Information

Looking at the implementation of the [inboundfilters ](https://github.com/getsentry/sentry-javascript/blob/ff416aeb41aa729c0ed02459e8010ae3fa4016f4/packages/core/src/integrations/inboundfilters.ts#L218)which is providing the functionality of the `debugUrls` the  implementation is trying to access the url from the `event.exception.values[0].stacktrace.frames` where it walks backwards through the frames returning when it sees a valid string referenced in `frame.filename`. 

However the [event captured by the](https://github.com/getsentry/sentry-javascript/blob/ff416aeb41aa729c0ed02459e8010ae3fa4016f4/packages/integrations/src/httpclient.ts#L380) `httpClient` does not have the `stackTrace` property instead populating the `request` field with a url
```
request: {
        url: data.url,
        method: data.method,
        headers: data.requestHeaders,
        cookies: data.requestCookies,
      },
```

As a result the `denyUrls` property in `inboundfilters` does not filter this event out. 

Note, I understand that this is a problem with the upstream `sentry-javascript` but as the documentation for the `httpClient` differs between both I have logged it here as this is where my problem originates.

I also understand that the denyUrls is intended for filtering on the stackTrace however it doesn't make sense that the value is called deny**Urls** and when a url property is actually passed it doesn't provide any filtering.

**Comment by krystofwoldrich** [comment]
@daniel-johns-99 Thank you for the message.

You are correct about the `allowUrls` and `denyUrls` they only apply to the exception stack trace. Filtering URLs in a sense of the origin of the error.

The HttpClient doesn't use these, although I understand that the naming of the properties could be more clear.

To achieve your goal please use the `failedRequestTargets` of the `HttpClient`. For example `/^(?:(?!google\.com).)*$/` will ignore anything with `google.com`.
