### ISSUE TITLE
Expose an API to check if there are pending crash reports on Android

### ISSUE THREAD

**Issue by monotkate** [getsentry/sentry-react-native#341]
`crashedLastLaunch` is exposed on iOS, but there is nothing equivalent to check to see if the app is launching after a crash for Android.

- `setShouldSendCallback` runs before the crash, and there isn't enough time to record anything to storage
- `setEventSentSuccessfully` runs after the report has been sent, which is after our boot workflow has completed

The workflow we would like to follow is much like the iOS version:
- begin booting the app
- call `sentry#install`
- expose `crashedLastLaunch` to native bridge and call new `sentry#didCrashLastLaunch` to see if last launch did crash
- if true do A if false do B

**Comment by zjullion** [comment]
In https://github.com/getsentry/react-native-sentry/issues/148, it is stated that sentry supports offline error logging.  Given this issues, does offline error logging work on Android?  We don't seem to be able to get it to work.

**Comment by HazAT** [comment]
@zjullion 
It should work. 
Check your android events, if they say `sentry-react-native` at the bottom of the event detail page in the SDK section it should work.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
