### ISSUE TITLE
TouchTracking is not defauling to accessibilityLabel 

### ISSUE THREAD

**Issue by daniel-johns-99** [getsentry/sentry-react-native#3410]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.13.0

**`react-native` version:** 0.68.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

(`react-native-sentry`)
```
export default Sentry.wrap(App);

```

The documentation mentions that by wrapping the App with Sentry we will get automatic Touch Tracking. https://docs.sentry.io/platforms/react-native/touchevents/ , The documentation also says that if no `sentry-label` is passed to a Component then Sentry will fallback to the accessibilityLabel Prop (https://docs.sentry.io/platforms/react-native/touchevents/#tracking-specific-components).

This is not working and the accessibilityLabel is not being seen in Sentry traces. 

It appears that this behaviour was changed in https://github.com/getsentry/sentry-react-native/pull/2712 however, is it a case of the documentation not being updated or is this accessibilityLabel prop still being read by default.

**Comment by krystofwoldrich** [comment]
@daniel-johns-99 Thank you for the message, this is an oversight on our side.

This behavior was changed in 5.0.0 major version.

- This PR fixes the docs https://github.com/getsentry/sentry-docs/pull/8540
