### ISSUE TITLE
5.14.0 - 'Sentry/SentryCurrentDateProvider.h' file not found

### ISSUE THREAD

**Issue by kekami** [getsentry/sentry-react-native#3414]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.14.0

**`react-native` version:** 0.71.13

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

Build failing due to:

 `/Users/XXXXXXXX/XXXXXXX/node_modules/@sentry/react-native/ios/RNSentry.mm:25:9: 'Sentry/SentryCurrentDateProvider.h' file not found`

Seems to be due to https://github.com/getsentry/sentry-react-native/pull/3349

**Comment by krystofwoldrich** [comment]
Hi @kekami,
have you updated your pods after updating the JS dependency? 

```
pod repo update
pod update Sentry
```

**Comment by kekami** [comment]
> Hi @kekami, have you updated your pods after updating the JS dependency?
> 
> ```
> pod repo update
> pod update Sentry
> ```

Yes, pods have been updated. 

Podfile.lock
```
  - RNSentry (5.14.0):
    - React-Core
    - Sentry/HybridSDK (= 8.15.2)
```

**Comment by krystofwoldrich** [comment]
Have you cleaned your iOS build? Do you use `use_frameworks`? 

Would you be able to share a minimal reproducible example?

**Comment by kekami** [comment]
> Have you cleaned your iOS build? Do you use `use_frameworks`?
> 
> Would you be able to share a minimal reproducible example?

You are right! It seems due to the use of `use_frameworks`.

Small repro: https://github.com/kekami/sentry-issue-repro

Basically just added som react-native-firebase libs and the following in the `Podfile`
```
  # For react-native-firebase
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
```

This results in `'Sentry/SentryCurrentDateProvider.h' file not found`
