### ISSUE TITLE
Change default User ID Logic

### ISSUE THREAD

**Issue by daniel-johns-99** [getsentry/sentry-react-native#3415]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.13.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://docs.sentry.io/platforms/react-native/enriching-events/identify-user/

Based on the out of the box configuration, Sentry uses a default device ID for new users who are yet to have called Sentry.identiftyUser.

Is there a way to edit that logic or potentially prepend a string to this ID? 

The out of the box ID generation is a UUID which is the same type as our internal UUID. Ideally I'd like to prepend a token such as `unregistered` to this id so that we know that this is not one of our users yet. I can't see any method to change this, and if I try and pre-process the event then I would need addiitonal logic so that my actual users dont have that token.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, you can change this in the `beforeSend` callback.

For example, you can check if the user has an email or different value on which you base if it's registered or not. 

```js
Sentry.init({
  beforeSend: (event: Sentry.Event) => {
    if (!event.user?.email) {
      event.user = {
        ...event.user,
        id: `unregistered-${event.user?.id}`,
      };
    }
    return event;
  },
});
```
