### ISSUE TITLE
stacktrace is not properly processed

### ISSUE THREAD

**Issue by gdanov** [getsentry/sentry-react-native#3424]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

"@sentry/react-native": "^5.14.0",
"sentry-expo": "~7.1.1",
"expo": "~49.0.0",

**`react-native` version:** 0.0.0

"react-native": "0.72.7",

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

stack traces are not displayed properly

**Steps to reproduce:**
- build (via expo's eas build ...)
- or push OTA (via expo's update)

probably important: using Hermes as the default. Using Typescript. metro config excerpt:
```
  config.serializer = {
    experimentalSerializerHook: TypeScriptPlugin(),
    customSerializer: createSentryMetroSerializer()
  };
```

in both cases, the stack trace is not showing proper detail. One example:
<img width="1141" alt="Screenshot 2023-11-27 at 14 24 45" src="https://github.com/getsentry/sentry-react-native/assets/957113/917338ab-4d45-4f32-9f23-a4fd907b70dd">

running `npx metro-symbolicate dist/bundles/ios-bcb962fec04f66d92f53e887a0bf2572.map < stacktrace.txt` produces 
```
at App(null:null:null)
  at renderWithHooks(null:null:null)
  at updateFunctionComponent(null:null:null)
  at beginWork(null:null:null)
  at beginWork$1(null:null:null)
  at performUnitOfWork(null:null:null)
  at workLoopSync(null:null:null)
  at renderRootSync(null:null:null)
  at performSyncWorkOnRoot(null:null:null)
  at flushSyncCallbacks(null:null:null)
  at flushPassiveEffectsImpl(null:null:null)
  at flushPassiveEffects(null:null:null)
  at anonymous(null:null:null)
```

with or without `>export USE_HERMES=true`. This should mean that problem begins already at build time I guess?

I've had the process running properly for a while, but for several weeks (not sure since when exactly actually) I have problems. Haven't changed anything that I'm aware of directly related to sentry. What I've changed since is to reorder my monorepo (yarn workspace) and fiddle with thsconfig a little.

What's verified to work:
- pushed bundle/sourcemap is properly associated with the release (e.g. the release page correctly links to the bundle page)
- when clicking on trace line (see screenshot), I'm taken to 40mb js bundle that's up to date transpiled version of my code. but there's no line information (and it's JS, not TS code).

Any advise how to debug the situation is appreciated. I've spent hours reviewing configs and applying things I've seen in other tickets, but no luck.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, the screenshot you shared is from a dev build.

To verify that the generated OTA update source map is correct can you try the `metro-symbolicate` command with stack trace from a production build?

**Comment by krystofwoldrich** [comment]
@gdanov You don't need to look for the bundle in a compiled app. 

You can run a production build of the app, create an error, and try its stack trace with `npx metro-symbolicate dist/bundles/ios-bcb962fec04f66d92f53e887a0bf2572.map < stacktrace.txt`

From the output `at App(null:null:null)` you shared at first the source map and the stack are not from the same bundle that's why no frames are resolved (all null).
