### ISSUE TITLE
Using contexts to filter beforeSend not working properly?

### ISSUE THREAD

**Issue by mfelix5** [getsentry/sentry-react-native#3430]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.14.1

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://energyhub.sentry.io/issues/4268308264/?environment=production&project=6619738&query=&referrer=issue-stream&statsPeriod=24h&stream_index=0)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: Config.SENTRY_PUBLIC_DSN,
  environment: Config.STAGE,
  tracesSampleRate: Config.STAGE === "production" ? 1.0 : 0,
  beforeSend(e) {
    const isSimulator = e.contexts?.device?.simulator;
    if (isSimulator) return null;
    else return e;
  },
});
```

---
**I have the following issue:**

Working locally using an iOS simulator, I can successfully filter out exceptions reported to Sentry using the `beforeSend` hook as shown above. I have tested this with a number of different attributes from the device and app contexts. And as expected in debug mode, I can see the following message: "Sentry Logger [log]: before send for type `error` returned `null`, will not send event". 

However, when I run a suite of Detox e2e tests on a simulator in a Github runner they produce a handful of "App hanging for at least 2000 ms" errors. For whatever reason I am not able to filter these errors. In Sentry, I see that the issues are properly categorized as having come from a simulator. 

Am I missing something? Is it possible under some scenarios that the device or app context is added to the issue AFTER the beforeSend hook runs? 

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

[Actual result]

**Expected result:**

[Expected result]

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message.

The `App hanging for at least 2000 ms` errors are created by the underlying `sentry-cocoa` SDK. This is a limitation of the current native auto initialization. Native errors and crashes are not available in the javascript `beforeSend` callback. 

There is an option to initialize the native SDK manually and create `beforeSend` in `sentry-cocoa`.https://docs.sentry.io/platforms/react-native/manual-setup/native-init/

**Comment by mfelix5** [comment]
Thank you for your response @krystofwoldrich. I appreciate it. Instead of changing the setup, is there a way that I could ignore the issue in the Sentry console? Because of the way that we manage releases, the e2e tests that run as part of a Github action and result in "App hanging" issues are always reported as version 1.0 (1). Is there a combination of archiving or resolving that I can perform that would basically ignore the "App hanging" issue UNLESS the app version is something other than 1.0 (1)?

**Comment by krystofwoldrich** [comment]
You can disable app hangs from RN https://docs.sentry.io/platforms/react-native/configuration/app-hangs/ for your e2e tests.

Would that work for you?

**Comment by mfelix5** [comment]
Thanks, @krystofwoldrich great suggestion. My init now looks like this and solves the problem: 
`Sentry.init({
  dsn: Config.SENTRY_PUBLIC_DSN,
  enableAppHangTracking:
    getVersion() === UNRELEASED_PROD_VARIANT ? false : true,
  environment: Config.STAGE,
});`
