### ISSUE TITLE
Sourcemaps broken since release of artifact bundles

### ISSUE THREAD

**Issue by xanderdeseyn** [getsentry/sentry-react-native#3432]
**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.14.1

**`react-native` version:** 0.72.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://de-lijn.sentry.io/issues/4521057732/?project=1398325&query=is%3Aunresolved++dist%3Aalpha&referrer=issue-stream&statsPeriod=90d&stream_index=0)

We upload sourcemaps in a manual release step. The sourcemap is successfully created and uploaded. When I download the sourcemap and run metro-symbolicate, it works. However, it seems like Sentry simply does not use the sourcemap for our issues. I can only assume this has to do with the new artifact bundles. We are unable to upload release bundles it seems...

**Comment by krystofwoldrich** [comment]
Hi,
could you share the command steps for how you create and upload the source maps?

I see that the linked issue has debug id: `c69461c8-27d6-4e3d-9ebd-740d13b71778` but the uploaded source maps has debug id `c69461c8-27d6-4e3d-9ebd-740d13b71778`.

**Comment by krystofwoldrich** [comment]
We recently updated our source maps upload guide, maybe that could help you.

https://docs.sentry.io/platforms/react-native/sourcemaps/#manual-upload-with-javascript-core

**Comment by krystofwoldrich** [comment]
@xanderdeseyn

You can see the debug ID sent with the event by clicking the `View JSON` button and then looking up `debug_meta.images.[0].debug_id`.

If the source code doesn't change, the Debug ID will be the same.

**Comment by xanderdeseyn** [comment]
I can see in our build logs that the Debug ID generated by Sentry is different when bundling during the release command and when bundling afterwards to generate our sourcemap. The code is of course the same. Do you have any ideas here?

**Comment by krystofwoldrich** [comment]
Check that the RN version, metro version, Hermes version are the same.

You can check the app build logs, RN is calling the same commands during the build as you do manually later. Check for differences. Typically it's `minified: true/false`.

**Comment by xanderdeseyn** [comment]
I confirmed these are all the same. I'm running them right after each other, and on the same machine. I have tried playing with the bundle parameters as well, and minify true or false does indeed give a different Debug ID, but not the one that is generated during the release command.

**Comment by krystofwoldrich** [comment]
@xanderdeseyn No worries, thanks for the message, we are happy it works now.
