### ISSUE TITLE
iOS source map only works with force-foreground flag

### ISSUE THREAD

**Issue by maykonmichel** [getsentry/sentry-react-native#3456]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.15.1

**`react-native` version:** 0.73.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Unminified code issue](https://mmp-it.sentry.io/issues/4709255598/?project=4506359953162240)
[Issue with workaround](https://mmp-it.sentry.io/issues/4709263104/?project=4506359953162240)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://241a4d607de84f2b3aff4b18f06c88a6@o4506359951392768.ingest.sentry.io/4506359953162240'
});
```

---
**I have the following issue:**

When a crash happens on iOS, Sentry doesn't capture sourcemap unless I set the force foreground flag adding `export SENTRY_CLI_EXTRA_ARGS="--force-foreground"` at `.xcode.env`

**Steps to reproduce:**
- Initialize a new project
- Run sentry wizard and setup app
- Build a release app and test the crash

[Reproducer repo](https://github.com/maykonmichel/reproducer-sentry)

**Actual result:**

Sentry issues dashboard shows the crash, but with unminified code

**Expected result:**

Sentry issues dashboard shows the crash with unminified code

**Comment by krystofwoldrich** [comment]
I reproduced the issue, thank you for the repository, we are still investigation why is it happening.

**Comment by krystofwoldrich** [comment]
Based on our investigation the background upload is working in https://github.com/getsentry/sentry-cli/releases/tag/2.21.3. You can manually downgrade to that version of Sentry CLI until we fix the bug.

**Comment by krystofwoldrich** [comment]
Please follow the `sentry-cli` issue for more details.

- https://github.com/getsentry/sentry-cli/issues/1895
