### ISSUE TITLE
LogBox shows instrument.js for all codeframes

### ISSUE THREAD

**Issue by rickhanlonii** [getsentry/sentry-react-native#3471]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 8.17.1

**`react-native` version:** 0.73.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

n/a

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have the following issue:**

When `console.error` or `console.warn` is fired in the app (such as a React "unique 'key' warning), the codeframe in LogBox is broken because it points to sentry's instrument.js file instead of the application code. 

The way this works in LogBox is through collapsing frames in Metro. The following change to metro.config.js fixes the issue:

```js
// metro.config.js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

// Copied from metro-config
const INTERNAL_CALLSITES_REGEX = new RegExp(
  [
    '/Libraries/BatchedBridge/MessageQueue\\.js$',
    '/Libraries/Core/.+\\.js$',
    '/Libraries/LogBox/.+\\.js$',
    '/Libraries/Network/.+\\.js$',
    '/Libraries/Pressability/.+\\.js$',
    '/Libraries/Renderer/implementations/.+\\.js$',
    '/Libraries/Utilities/.+\\.js$',
    '/Libraries/vendor/.+\\.js$',
    '/Libraries/WebSocket/.+\\.js$',
    '/Libraries/YellowBox/.+\\.js$',
    '/metro-runtime/.+\\.js$',
    '/node_modules/@babel/runtime/.+\\.js$',
    '/node_modules/event-target-shim/.+\\.js$',
    '/node_modules/invariant/.+\\.js$',
    '/node_modules/react-devtools-core/.+\\.js$',
    '/node_modules/react-native/index.js$',
    '/node_modules/react-refresh/.+\\.js$',
    '/node_modules/scheduler/.+\\.js$',
    '^\\[native code\\]$',
    
    // ⚠️ Important: add this line
    '/node_modules/@sentry/utils/cjs/instrument.js', 
  ].join('|'),
);

const config = {
  symbolicator: {
    customizeFrame: (frame /*: $ReadOnly<{file: ?string, ...}>*/) => {
      const collapse = Boolean(
        frame.file && INTERNAL_CALLSITES_REGEX.test(frame.file),
      );
      return {collapse};
    },
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

**Steps to reproduce:**
- Install new RN app with template
- Add sentry and wrap App.tsx (with console breadcrumbs enabled)
- Add console.error to App.tsx render
- Observe LogBox error shows codeframe for instrument.js 

**Actual result:**

<img width="556" alt="Screenshot 2023-12-14 at 1 24 02 PM" src="https://github.com/getsentry/sentry-react-native/assets/2440089/d2d3b997-d41d-4fed-8480-8772b728fcec">

**Expected result:**
<img width="556" alt="Screenshot 2023-12-14 at 1 36 20 PM" src="https://github.com/getsentry/sentry-react-native/assets/2440089/adfa1051-b4d6-4f93-9a3d-520865a65462">

(Note: the codeframe here points to the wrong app code, which is a separate issue I reported in https://github.com/facebook/react-native/issues/41945).

**Comment by rickhanlonii** [comment]
Having to copy INTERNAL_CALLSITES_REGEX is not ideal because if upstream adds frames to it, then users won't get the update when installing the package. Unless there's already another way to do this, I think we a metro config option to append internal frames, something like:

```js
const config = {
  symbolicator: {
    additionalInternalFrames: ['/node_modules/@sentry/utils/cjs/instrument.js']
  },
};
```

I'm also not sure if we have this, but it would be nice if users didn't need to configure this themselves, since sentry or other libraries might need to add to this later. That could be done by supporting plugins that merge configs, like:

```js
const config = {
  plugins: [@sentry/metro-config, {
     // To support this metro config for sentry
     // https://docs.sentry.io/platforms/react-native/sourcemaps/#manual-upload-with-hermes
     sourceMaps: true
  }]
}
```

cc @motiz88 @huntie for interest

**Comment by krystofwoldrich** [comment]
Hi @rickhanlonii,
thank you for the message and all the details, workaround, and possible solutions.

We recently added `withSentryExpoSerializer(config)` to `@sentry/react-native/metro`. We can do a similar wrapper generic wrapper `withSentry` and inside of that, we can add the missing Sentry call sites.

 The fix could look like this:
 
 ```js
 const originalCustomizeFrame = config.symbolicator.customizeFrame;
const collapseSentryInternalFrames = frame =>
   typeof frame.file === 'string' && frame.file.includes('node_modules/@sentry');
config.symbolicator.customizeFrame = frame => {
   const original = originalCustomizeFrame(frame);

   return {
     ...original,
     collapse: original.collapse || collapseSentryInternalFrames(original),
   };
};
 ```

**Comment by rickhanlonii** [comment]
@krystofwoldrich, yeah that's awesome +1
