### ISSUE TITLE
Upload debug symbols fails on iOS in monorepo.

### ISSUE THREAD

**Issue by joarkosberg** [getsentry/sentry-react-native#3490]
The script `sentry-xcode-debug-files.sh` does not enable overriding the `WITH_ENVIRONMENT` variable. So in a monorepo, it does not find the with environment script. 
All other environment variables I have needed to change are configurable. So would be nice if this one was too.

Looked into creating PR, with looking it up as a environment variable, but unsure if that is the preferable way.

**Comment by krystofwoldrich** [comment]
Thank you, we will review the PR.
