### ISSUE TITLE
Stack Frame Not Matching Artifact Name

### ISSUE THREAD

**Issue by objectiveSee** [getsentry/sentry-react-native#3492]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (5.10.0)
- [ ]  `react-native-sentry` (<= 0.43.2)
- [x] `sentry-expo` (7.1.1)

**`react-native` version:** 0.72.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

```
import * as Application from 'expo-application';
import * as Sentry from 'sentry-expo';

if ( !process.env.EXPO_PUBLIC_SENTRY_DSN ) {
  throw new Error( 'Missing EXPO_PUBLIC_SENTRY_DSN environment variable' );
}

// Set to true if you want to enable analytics in dev mode (eg. for testing)
// See: https://docs.expo.dev/guides/using-sentry/#disabled-by-default-in-dev
const ENABLE_IN_DEV = false; // TODO: set to false before committing

// Enable or disable logging based on the environment
// By default, analytics is disabled in dev mode and enabled in prod mode
let enabled = false;
if (__DEV__) {
  if ( ! ENABLE_IN_DEV ) {
    console.log('🔭 Sentry - Disabling in DEV mode');
  } else {
    console.log('🔭 Sentry - Enabling in DEV mode');
    enabled = true;
  }
} else {
  console.log('🔭 Sentry - Enabling in PROD mode');
  enabled = true;
}

const sampleRate = 1.0;
const enableInExpoDevelopment = true;
const debug = __DEV__;

// TODO: get this from the apps config instead of hardcoding it
const release = `testing.appid.debug@1.0.0+${Application.nativeBuildVersion}`
console.log(`🔭 Sentry - Release: ${release}`);

if ( enabled ) {
  console.log(`🔭 Sentry - Initializing`);
  Sentry.init({
    dsn: process.env.EXPO_PUBLIC_SENTRY_DSN,
    enableInExpoDevelopment,
    tracesSampleRate: 0, // Disable this for now, as it's very noisy in logs and not sure how to use it yet
    debug,
    sampleRate,
    release,
    // environment: __DEV__ ? 'development' : 'production',
    // dist: ,
    beforeBreadcrumb: (_breadcrumb, _hint) => {
      // TODO: Document this, and figure out if it's needed to turn off console.logs turning into breadcrumbs
      return null;
    }
  })
}
```

🕵️

---
**I have the following issue:**

[Description]

**Steps to reproduce:**
- Generate a new build using Expo EAS Build (iOS or Android)
- Launch app, click the special "Crash Now" button
- Re-launch app
- Open Sentry.io and browse to latest crashes.

**Actual result:**
- The stack track looks like this: `app:///main.jsbundle in crashTestFunction at line 280978:20`
- The JS crashes are not symbolicated. If we click the "unminify code" button and we get a modal saying that " the original source code for this stack frame couldn't be determined when this error was captured". 
![Screenshot 2024-01-04 at 9 55 22 AM](https://github.com/getsentry/sentry-react-native/assets/1684106/a879c0f1-cdfa-4e35-ab39-754a9faddd2f)

- We cannot use DebugIds (recommended) because Expo's library is on version 5.10.0 and 5.11.1 is required.
- Under "Releases" we get an error about no matching release artifacts.
- Under project releases for this release version, we have 4 "artifact bundles", 2 for iOS and 2 for Android. However there are no "release bundles". 

![Screenshot 2024-01-04 at 9 59 23 AM](https://github.com/getsentry/sentry-react-native/assets/1684106/92c3e50f-21bb-4425-8e3b-fa9bfc9e95fa)

![Screenshot 2024-01-04 at 10 01 53 AM](https://github.com/getsentry/sentry-react-native/assets/1684106/a6c6769d-9cde-4f49-bfde-1dc8961ea1ef)

![Screenshot 2024-01-04 at 10 02 20 AM](https://github.com/getsentry/sentry-react-native/assets/1684106/bf878999-31b6-4138-8850-f4461c354ceb)

**Expected result:**
- Our stack traces contain the symbolicated crash info including the filename and line number of the crash (Typescript files)

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and all the detailed information. From the screenshot and code sample, I see that you are not setting a `dist` value but the source maps are uploaded with `dist: 41`.

If you set dist to `Application.nativeBuildVersion` the source maps should resolve.

**Comment by objectiveSee** [comment]
Thanks for the tip @krystofwoldrich! That resolved our issues and saved me a lot of time trying random things. We will keep an ear out for when 5.16 stable is released and switch to that eventually.

Expo's documentation appears to have been wrong:

📝
distribution: The name/value to give your distribution (you can think of this as a sub-release). **Expo defaults to using your version from app.json.** If you provide a custom distribution, you must pass the same value to dist in your call to Sentry.init(), otherwise you will not see stacktraces in your error reports.

📝
Your dist will automatically be set to Sentry's expected value: ${buildNumber} (iOS) or ${versionCode} (Android).

https://docs.expo.dev/guides/using-sentry/#app-configuration
https://docs.expo.dev/guides/using-sentry/#uploading-source-maps-at-build-time

**Comment by krystofwoldrich** [comment]
@objectiveSee Thanks for the message, dist, and release are automatically set only if neither release nor dist is set manually. We will update the text.

**Comment by mmospanenko** [comment]
Hi guys, having similar issue

dist the identical, sources pushes on build stage using Action:
![Image](https://github.com/user-attachments/assets/17c2b3dc-b928-49dc-a2a2-bde109659a1b)


![Image](https://github.com/user-attachments/assets/41f48d58-dc0f-47c3-88d9-4a086993d7fe)

uploaded:
![Image](https://github.com/user-attachments/assets/9b3c3ac1-7629-4796-9f46-e3b4d7f81723)

How to find the mistake?

**Comment by joshsmith-watchbox** [comment]
For anyone still experiencing this problem, we were able to resolve by revisiting the Sentry specific iOS build steps and the Android gradle settings:
- [Configure Automatic Source Maps Upload](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload)
- [Configure Automatic Debug Symbols Upload](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-debug-symbols-upload)
- [Enable Sentry AGP](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-sentry-agp)

It appears the iOS source maps build step was reverted at some point after we bumped React Native from 0.73 to 0.74, thereby preventing the source maps from uploading.
