### ISSUE TITLE
IOS building from the command line throws error

### ISSUE THREAD

**Issue by n-kulic** [getsentry/sentry-react-native#3511]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 5.15.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [X]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://ab2285313....@log.org.hr/4',
});
```

---
**I have the following issue:**

Building IOS project is failing over command line, i.e. `xcodebuild` command

**Steps to reproduce:**
- Step 1: Generate new react-native project `npx react-native@latest init AwesomeProject`
- Step 2: Run Sentry Wizard `npx @sentry/wizard@latest -s -i reactNative`
- Step 3: Manage app signing (automatic or manual)
- Step 3: Run build command `xcodebuild -allowProvisioningUpdates -quiet -workspace ios/AwesomeProject.xcworkspace -sdk iphoneos -configuration Release -scheme AwesomeProject archive -archivePath AwesomeProject.xcarchive`

**Actual result:**
Build fails with following error:
```
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: This version of Sentry does not support artifact bundles. A release slug is required (provide with --release)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Expected result:**
Build to succeed.
Note: Work well when building through xcode ide

**Comment by krystofwoldrich** [comment]
Hi @n-kulic,
Thank you for the issue and the details. This happens when the version of your Sentry backend doesn't support the new Artifact Bundles.

You can add `export AUTO_RELEASE=true` env to avoid upgrading to a newer Sentry backend version.

https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload
