### ISSUE TITLE
Transactions/spans get dropped if you specify a startTimestamp or provide a timestamp to finish()

### ISSUE THREAD

**Issue by evelant** [getsentry/sentry-react-native#3517]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ X ]  iOS
- [ ]  Android

**SDK:**
- [X ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.16.0-alpha.2

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [ X ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ X ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A transactions get dropped so I can't link to them

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: "my_dsn_here",
    enabled: true,
    tracesSampleRate: 1.0,
    attachScreenshot: false,
    attachStacktrace: false,
    attachThreads: false,
    attachViewHierarchy: false,
    autoInitializeNativeSdk: true,
    autoSessionTracking: true,
    enableAppHangTracking: true,
    enableAutoPerformanceTracing: true,
    enableNative: true,
    enableNativeCrashHandling: true,
    environment: process.env.MYAPP_ENV ?? "default",
    enableTracing: true,
    enableWatchdogTerminationTracking: true,
    enableCaptureFailedRequests: true,
    enableAutoSessionTracking: true,
    enableNdkScopeSync: true,
    integrations: [
        new Sentry.ReactNativeTracing({
            idleTimeoutMs: 3000,
            enableAppStartTracking: false,
            enableNativeFramesTracking: false,
            enableStallTracking: false,
            enableUserInteractionTracing: true,
            shouldCreateSpanForRequest: url => {
                return !__DEV__ || !url.startsWith(`http://localhost:8081/logs`)
            },
        }) as any,
    ],
    maxBreadcrumbs: 200,
    maxValueLength: 3000,
    debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
})
```

---
**I have the following issue:**

If I create a transaction with `startTimestamp` and provide a timestamp when calling `finish` it gets dropped by Sentry.

**Steps to reproduce:**
```
const trans = Sentry.startTransaction({ name: "AppDataLoading", startTimestamp: Date.now() })
cons span = trans.startChild({ op: "AppDataLoadingSpan" startTimestamp: Date.now() })
setTimeout(() => {
   span.finish(Date.now())
   trans.finish(Date.now())
}, 2000)
```

Sending the same transaction without `startTimestamp` and without passing an end timestamp to `finish` works correctly.

**Actual result:**

The transaction never shows up in the Sentry UI. Debug logging indicates it is sent, but Sentry's server appears to drop it (I see dropped transactions in the stats page)

```
 LOG  Sentry Logger [log]: [Tracing] Finishing 'AppDataLoadingSpan' span on transaction 'AppDataLoading' (ab2f8f0db3931651).
 LOG  Sentry Logger [log]: [Tracing] Finishing default transaction: AppDataLoading.
```

and in iOS simulator logs

```
[Sentry] [debug] [SentrySerialization:148] Header {"event_id":"e2f87a25d4ac4b14a3b4082062e76ebd","sent_at":"2024-01-10T22:37:53.936Z","sdk":{"name":"sentry.javascript.react-native","version":"5.16.0-alpha.2"},"trace":{"environment":"development","public_key":"11b7700198a24e3c8abb3dcd36dcd64e","trace_id":"900d5c9d0f3848b6a7bccf7a1e150930","sample_rate":"1","transaction":"AppDataLoading","sampled":"true"}}

[Sentry] [debug] Item Header {"type":"transaction","content_type":"application/json","length":58378}

[Sentry] [debug] [SentryFileManager:260] Writing envelope to path: /Users/imagio/Library/Developer/CoreSimulator/Devices/C9BF5541-77BD-453A-B9A7-CCFC11DBCA82/data/Containers/Data/Application/175F679A-B843-4885-96BB-7088F718C6F5/Library/Caches/io.sentry/071f92a1683389279703902ac167925fb20eb39e/envelopes/1704926273.958307-00002-5F996DD4-4E94-401E-9984-3FE51DE12B8D.json

[Sentry] [debug] [SentryHttpTransport:268] sendAllCachedEnvelopes start.

[Sentry] [debug] [SentrySerialization:148] Header {"sdk":{"name":"sentry.javascript.react-native","version":"5.16.0-alpha.2","packages":{"name":"cocoapods:getsentry\/sentry.javascript.react-native","version":"5.16.0-alpha.2"}},"sent_at":"2024-01-10T22:37:53.936Z","trace":{"trace_id":"900d5c9d0f3848b6a7bccf7a1e150930","public_key":"11b7700198a24e3c8abb3dcd36dcd64e","environment":"development","sampled":"1","sample_rate":"1","transaction":"AppDataLoading"},"event_id":"e2f87a25d4ac4b14a3b4082062e76ebd"}

[Sentry] [debug] Item Header {"type":"transaction","length":58378}

[Sentry] [debug] [SentryRequestOperation:34] Request status: 200

[Sentry] [debug] [SentryRequestOperation:38] Request response: {"id":"e2f87a25d4ac4b14a3b4082062e76ebd"}
```
**Expected result:**

Transaction API should work properly with custom startTimestamp and end timestamps.

**Comment by evelant** [comment]
....and it turns out it was my fault for not reading the docs carefully enough. The timestamp expected by Sentry is not a standard "milliseconds since epoch" as returned by `Date.now()` or `new Date().getTime()`. It expects _seconds_ since epoch. After diving my timestamps / 1000 the traces and spans show up in Sentry no problem.

I'm going to leave this open because I think it would be good to discuss how Sentry can better surface this sort of error. As far as I can tell there's no way to know if you've sent an invalid payload or how it is invalid. The only thing I could find is a count of dropped transactions on the stats page, but that may not even be usable as an indicator depending on the project in question.

Maybe the Sentry UI should provide a sample of invalid/dropped events for inspection. Or the SDK could do some basic sanity checks. Or the sentry ingestion endpoint could return an error on invalid data instead of succeeding then dropping the event.

**Comment by krystofwoldrich** [comment]
Thank you for all the details and explanation. This is valuable feedback for our SDK and docs.

I'll close this issue and open a follow-up in the `sentry-docs` repository.
