### ISSUE TITLE
Adding Sentry wrapper cmd in iOS Bundle RN phase results in missing assets folder in .ipa

### ISSUE THREAD

**Issue by Ananthakr-Jupiter** [getsentry/sentry-react-native#3519]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native`: 5.12.0, 5.15.0
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 8.14.2

**`react-native` version:** 0.72.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

After adding the sentry wrapper in `Bundle React Native code and images` phase in Build phases, 
```bash
set -e

WITH_ENVIRONMENT=\"../node_modules/react-native/scripts/xcode/with-environment.sh\"
REACT_NATIVE_XCODE=\"../node_modules/react-native/scripts/react-native-xcode.sh\"

/bin/sh -c \"$WITH_ENVIRONMENT $REACT_NATIVE_XCODE\"
```
either manually or through sentry-wizard, the ipa builds from CI doesn't have `assets` folder which contains the local images and lottie files which referenced internally through `require` syntax. There is no error observed during the build logs and the same step works fine in local xcode builds and archives.

With the default command from react-native core, this issue isn't there. 

**Steps to reproduce:**
- Initiate a 0.72.x version based React Native project
- Load a .png image in App.tsx through local require syntax
- Install sentry-react-native
- Run sentry-wizard to configure the project
- Make .ipa builds from CI like Github actions or CodeMagic
- Inspect the .ipa build and see if the .png image exists in the assets folder

**Actual result:**

- no assets folder

**Expected result:**

- assets folder should be there

**Comment by krystofwoldrich** [comment]
@Ananthakr-Jupiter Thank you for the message and the steps to reproduce the issue. We will try it and keep you updated.

**Comment by Ananthakr-Jupiter** [comment]
We have recently migrated from RN 0.65.2 to 0.72.6 along with that, we have bumped sentry-react-native version from 4.15.0 to 5.12.0. We have noticed this issue after this.

I have also tried to downgrade sentry alone to 4.15.0 with RN 0.72.6 as well, the issue persists.

**Comment by Ananthakr-Jupiter** [comment]
@krystofwoldrich any updates on this issue?

**Comment by kahest** [comment]
Hey @Ananthakr-Jupiter, we still need to investigate, hope to have an update soon

**Comment by bnussman** [comment]
I'm having an issue where my iOS production build's Drawer icon is missing. I saw that React Navigation `require`s a png under the hood. I'm wondering is this is related. I'm pretty stuck.

**Comment by krystofwoldrich** [comment]
@Ananthakr-Jupiter Sadly I was not able to reproduce the issue,
could you add the following code to you `.xcode.env` and try the build again? And share the log from `Bundle React Native code and image`?

```bash
export SENTRY_CLI_EXTRA_ARGS="--force-foreground --log-level=debug"
```

**Comment by krutarth-h-dave** [comment]
We are working on 

> @Ananthakr-Jupiter Sadly I was not able to reproduce the issue, could you add the following code to you `.xcode.env` and try the build again? And share the log from `Bundle React Native code and image`?
> 
> ```shell
> export SENTRY_CLI_EXTRA_ARGS="--force-foreground --log-level=debug"
> ```

Sure, Let us check this and update here.

**Comment by Ananthakr-Jupiter** [comment]
@krystofwoldrich Thanks a lot for helping us out with this issue. 

We narrowed down the issue to the js bundling command getting killed due to heap memory exhaustion and just after the `main.jsbundle` was created before the assets were copied to the IPA folder. This ensured the next steps in bundle creation proceeded without any issues, making it harder for us to detect. 

Setting extra node args in the `.xcode.env` file helped resolve the issue.
```
export NODE_ARGS="--max_old_space_size=8192"
```
