### ISSUE TITLE
react-native-web with Webpack warn about TurboModuleRegistry not found

### ISSUE THREAD

**Issue by jparkrr** [getsentry/sentry-react-native#3527]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Web

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.16.0

**`react-native` version:** 0.73.2

**`react-native-web` version:** 0.18.12

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

Getting the following warning with react-native-web. (I'm on expo sdk 50 beta).

```
WARNING in ./node_modules/@sentry/react-native/dist/js/wrapper.js:33:4
export 'TurboModuleRegistry' (imported as 'TurboModuleRegistry') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, DeviceInfo, Dimensions, DrawerLayoutAndroid, Easing, FlatList, I18nManager, Image, ImageBackground, InputAccessoryView, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, PermissionsAndroid, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Settings, Share, StatusBar, StyleSheet, Switch, Systrace, TVEventHandler, Text, TextInput, ToastAndroid, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, ViewPropTypes, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)
  31 |
  32 | const RNSentry: Spec | undefined = isTurboModuleEnabled()
> 33 |   ? TurboModuleRegistry.get<Spec>('RNSentry')
     |    ^
  34 |   : NativeModules.RNSentry;
```

Everything still seems to work, which is great. Thanks for all your work! But hopefully we can get rid of the warning.

I found a fix for a similar issue with react-native-reanimated: https://github.com/software-mansion/react-native-reanimated/pull/1378

**Actual result:**

Receive a warning.

**Expected result:**

No warning

**Comment by krystofwoldrich** [comment]
Hi @jparkrr, happy to hear that everything else works,
we will get this fixed.

I just could not reproduce it, what version of the Expo SDK are you using, I have tried it with `50.0.0-preview.8` and built the web using Metro.

**Comment by jparkrr** [comment]
You're right, I'm using webpack, not metro for web. I know expo has deprecated `@expo/webpack-config`, but hopefully the warning can be fixed for webpack as well, because there are probably a lot of people using it with react-native-web, both with and without`@expo/webpack-config`.

Here's a repro for you https://github.com/jparkrr/repro-sentry-warning

Thanks!

**Comment by krystofwoldrich** [comment]
Thanks for the confirmation, yes, we can fix the warning for Webpack.

**Comment by Niravpatel129** [comment]
just to confirm, i'm also getting a similar issue:

<img width="544" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/43049943/d420a19f-fc45-4ecb-9def-16fc05fd83ff">

**Comment by krystofwoldrich** [comment]
@Niravpatel129 Thank you.

**Comment by sergeushenecz** [comment]
I have also the same warning. i use webpack instead of metro

**Comment by jparkrr** [comment]
Any update or workaround on this? We're about to take this into production and it's annoying that all the developers I work with have to see this warning locally every time a fast-refresh happens.

**Comment by krystofwoldrich** [comment]
@jparkrr Thank you for the message, we understand that. We will fix this shortly.

**Comment by fb55** [comment]
@krystofwoldrich Thanks for the fix! Note that webpack builds were broken again in a recent version, now with the message:

> Attempted import error: 'requireNativeComponent' is not exported from 'react-native' (imported as 'requireNativeComponent').

from `@sentry/react-native/dist/js/tracing/timetodisplaynative.js`. Let me know if you would like to see a new issue for this!
