### ISSUE TITLE
Android app bundle build fails with error message "A release slug is required"

### ISSUE THREAD

**Issue by n-kulic** [getsentry/sentry-react-native#3528]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 5.15.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [X]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://ab2285313....@log.org.hr/4',
});
```

---
**I have the following issue:**

Android app bundle build is failing, i.e. `./gradlew bundleRelease` command.

**Steps to reproduce:**
- Step 1: Generate new react-native project `npx react-native@latest init AwesomeProject`
- Step 2: Run Sentry Wizard `npx @sentry/wizard@latest -s -i reactNative`
- Step 3: Manage app signing (automatic or manual)
- Step 3: Run build command `./gradlew bundleRelease`

**Actual result:**
Build fails with following error:
```
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
-error: This version of Sentry does not support artifact bundles. A release slug is required (provide with --release)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

And based on source code this seems intentional:
**sentry.gradle** line 133
```gradle
def notIncludeRelease = "$bundleCommand" == "bundle" && exitValue == 0
def not = notIncludeRelease ? 'not ' : ''
project.logger.lifecycle("Sentry Source Maps upload will ${not}include the release name and dist.")
extraArgs.addAll(notIncludeRelease ? [] : [
    "--release", releaseName,
    "--dist", versionCode
])
```
Specifically the following part:
> _`def notIncludeRelease = "$bundleCommand" == "bundle" && exitValue == 0`:_
- https://github.com/getsentry/sentry-react-native/blob/main/sentry.gradle#L133C23-L133C40

Why are release args not included when building app bundle?

**Expected result:**
Build to succeed.

**Comment by krystofwoldrich** [comment]
Hi @n-kulic,
thank you for the message,
yes, this was intentional as the release and dist are not needed when debug IDs are used. This must be supported by the Sentry backend (since 23.3.0).

You can set the release and dist using envs, `SENTRY_RELEASE` and `SENTRY_DIST` would that work for you?

**Comment by n-kulic** [comment]
> Hi @n-kulic, thank you for the message, yes, this was intentional as the release and dist are not needed when debug IDs are used. This must be supported by the Sentry backend (since 23.3.0).
> 
> You can set the release and dist using envs, `SENTRY_RELEASE` and `SENTRY_DIST` would that work for you?

I'm not quite sure where should i set release and dist values?
Would it be in `android/app/build.gradle`?
```gradle
apply plugin: "io.sentry.android.gradle"

sentry {
    release = ...?
}
```

**Comment by krystofwoldrich** [comment]
At the moment you would need to set the environmental variables manually.

https://docs.sentry.io/platforms/react-native/sourcemaps/troubleshooting/optional-release-and-distribution/

**Comment by n-kulic** [comment]
> At the moment you would need to set the environmental variables manually.
> 
> https://docs.sentry.io/platforms/react-native/sourcemaps/troubleshooting/optional-release-and-distribution/

I've exported `SENTRY_RELEASE` and `SENTRY_DIST` env variables before running `./gradlew bundleRelease` and I still get the error:
![image](https://github.com/getsentry/sentry-react-native/assets/94164339/67b78dd3-67b5-4536-a89a-f0dc4d6ebac5)

**Comment by krystofwoldrich** [comment]
@n-kulic Thank you, we will check it.

**Comment by krystofwoldrich** [comment]
@phuocantd Thank you for the message, ale you using the latest RN SDK including [this fix](https://github.com/getsentry/sentry-react-native/pull/3540)? 

Please consider opening a new issue, since this thread is almost half a year old.

**Comment by phuocantd** [comment]
> @phuocantd Thank you for the message, ale you using the latest RN SDK including [this fix](https://github.com/getsentry/sentry-react-native/pull/3540)?
> 
> Please consider opening a new issue, since this thread is almost half a year old.

Looks like I've fixed it
