### ISSUE TITLE
Expo Sentry CLI fails on 301 `not a JSON response`

### ISSUE THREAD

**Issue by mikevercoelen** [getsentry/sentry-react-native#3536]
Versions:

```
"@sentry/react-native": "5.16.0",
"react-native": "0.73.2",
"expo": "^50.0.2",
```

**Are you using Expo?**
- [x ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

We've followed the default setup as listed here: https://docs.expo.dev/guides/using-sentry/ and https://docs.sentry.io/platforms/react-native/manual-setup/expo/

We've correctly verified that the env vars are set correctly, but our buildpipe line is failing:

```
[stderr] 
  DEBUG   2024-01-19 11:57:07.326335393 +00:00 > User-Agent: sentry-cli/2.25.3
2600
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327095773 +00:00 > Authorization: Bearer cb462f83***
2601
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327138412 +00:00 < HTTP/1.1 301 Moved Permanently
2602
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327147363 +00:00 < Cache-Control: private
2603
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327154151 +00:00 < Location: https://sentry.io:443/api/0/organizations/nestio-1/chunk-upload/
2604
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327160016 +00:00 < Content-Length: 0
2605
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327166338 +00:00 < Date: Fri, 19 Jan 2024 11:57:07 GMT
2606
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327172328 +00:00 < Content-Type: text/html; charset=UTF-8
2607
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327237345 +00:00 response status: 301
2608
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
  DEBUG   2024-01-19 11:57:07.327245554 +00:00 body: 
2609
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
error: not a JSON response
2610
Fri, 19 Jan 2024 11:57:07 GMT
[stderr] 
Command failed, however, "SENTRY_ALLOW_FAILURE" variable or "allow-failure" flag was set. Exiting with 0 exit code.
```

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message,

does this happen only during native builds or also during `npx sentry-expo-upload-sourcemaps`?

**Comment by mikevercoelen** [comment]
@krystofwoldrich Full builds.

(not important but) I wish we would've tried to run `npx sentry-expo-upload-sourcemaps` because this is very exciting! Great job and congrats on the Expo collab, this will make a lot of people happy.

Unfortunately without the full builds Sentry integration working, we can't yet upgrade to v50 and newer sentry-rn.

Thanks!

**Comment by krystofwoldrich** [comment]
@mikevercoelen Does it happen when you build it locally or EAS Build?

Could you share a large part of the log including the stdout?

**Comment by mikevercoelen** [comment]
> @mikevercoelen Does it happen when you build it locally or EAS Build?
> 
> Could you share a large part of the log including the stdout?

For reasons I can't share the logs, this was EAS build.

**Comment by jredmond-sentry** [comment]
I see the `Location:` header in the response, and it looks like the redirect Sentry's systems will return for a plain-HTTP request. Are you sending to `http://sentry.io` or `https://sentry.io`?

**Comment by lucasfronza** [comment]
My Sentry config url was `'https://www.sentry.io/'`, will test now with `'https://sentry.io/'`. 🤞 Bear in mind that in the Release notes, it does suggest using `www` domain https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0. I double-checked other places, including Sentry and Expo docs, and they are all using `https://sentry.io/`.

**Comment by lucasfronza** [comment]
Can confirm that using the non-www url in the Sentry expo config (`"url": "https://sentry.io/",`) fixed the issue for us.

If someone could edit the Release notes, that would be great as it will avoid any further people from bumping into this issue.

**Comment by mikevercoelen** [comment]
Confirmed too, we actually had too issues:

- We used `http` vs `https` for the `url`
- We still had the old publish hook in our app config (oops)

All good now, cheers!

**Comment by krystofwoldrich** [comment]
@lucasfronza 
> My Sentry config url was 'https://www.sentry.io/', will test now with 'https://sentry.io/'. 🤞 Bear in mind that, in the Release notes, it does suggest using www domain [5.16.0 (release)](https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0). I double-checked other places, including Sentry and Expo docs, and they are all using https://sentry.io/.

Thank you for the notice, we updated the changelog.
