### ISSUE TITLE
Expo: Source Maps Upload fails on invalid project (http response 400) 

### ISSUE THREAD

**Issue by iM-GeeKy** [getsentry/sentry-react-native#3543]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.16.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [x]  Yes (50.0.2)
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: SENTRY_DATA_SOURCE,
    debug: ENVIRONMENT !== "production",
    integrations: [
      new Sentry.ReactNativeTracing({
        shouldCreateSpanForRequest: (url) => {
          return (
            !__DEV__ ||
            !url.startsWith(`http://${Constants.expoConfig?.hostUri}/logs`)
          );
        },
      }),
    ],
  });
```
---
**I have the following issue:**

Since `expo-sentry` is now deprecated as of Expo version 50, they have provided a guide to [migrate](https://github.com/expo/fyi/blob/main/sentry-expo-migration.md) to `@sentry/react-native`. Locally the migration appears to work and using `eas build` with `"developmentClient": true` also appears to work.

**Steps to reproduce:**
- Step 1 From an Expo project run `eas build` on where the build name has a `"distribution": "internal"`.

**Actual result:**

iOS (failed) - The output is didn't appear to be super insightful, but here is a bit from the final log errors.
<img width="1054" alt="Screenshot 2024-01-22 at 3 28 39 PM" src="https://github.com/getsentry/sentry-react-native/assets/7604441/f5404cc0-ff07-4be1-98ca-84505dd7e3de">

Android (failed - The output appeared to be a bit more helpful. Here is a bit from the final log errors.
<img width="1069" alt="Screenshot 2024-01-22 at 3 21 01 PM" src="https://github.com/getsentry/sentry-react-native/assets/7604441/fa2215ba-24af-43f5-b383-8f778ba4140e">

**Expected result:**

The build should successfully complete. I'm still in the process of troubleshooting and will update if I find a resolution. Perhaps, I missed a step in the migration guide so I'll be going back to double check. [krystofwoldrich](https://github.com/krystofwoldrich)

**Comment by krystofwoldrich** [comment]
Hi @iM-GeeKy,
thank you for the message and the log.

Does your `@sentry/react-native/expo` plugin configuration contain the correct project and organization slugs?

https://docs.sentry.io/platforms/react-native/manual-setup/expo/#add-the-sentry-expo-plugin

**Comment by iM-GeeKy** [comment]
> Hi @iM-GeeKy, thank you for the message and the log.
> 
> Does your `@sentry/react-native/expo` plugin configuration contain the correct project and organization slugs?
> 
> https://docs.sentry.io/platforms/react-native/manual-setup/expo/#add-the-sentry-expo-plugin

To the best of my knowledge, yes. It appears to same configuration values that I'm using in my production app that uses Expo 49, but I can double check!
