### ISSUE TITLE
Recent visionos change is breaking ios builds

### ISSUE THREAD

**Issue by johnf** [getsentry/sentry-react-native#3547]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [X]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

**Configuration:**
N/A
---
**I have the following issue:**

When building on iOS I'm getting the following error for `pod update`

```
Configuring Pod with statically linked Frameworks
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration

[!] Invalid `Podfile` file: 
[!] Invalid `RNSentry.podspec` file: undefined method `visionos' for #<Pod::Specification name="RNSentry">.
```

**Steps to reproduce:**
- Standard sentry setup
- pod update

**Actual result:**
Build fails see above
**Expected result:**

No build failure

I'm about to submit a PR

**Comment by U1320100568** [comment]
same problem on `pod install`

**Comment by rodrigodiasf1984** [comment]
Same problem, how to fix it?

**Comment by rodrigodiasf1984** [comment]
hi , i've downgrade to "@sentry/react-native": "5.16.0", without ^,  and removed node_modules, yarn, and pod install, its working now.

**Comment by johnf** [comment]
If you are using patch-package you can use this diff
```
diff --git a/node_modules/@sentry/react-native/RNSentry.podspec b/node_modules/@sentry/react-native/RNSentry.podspec
index e752ab8..d5f7558 100644
--- a/node_modules/@sentry/react-native/RNSentry.podspec
+++ b/node_modules/@sentry/react-native/RNSentry.podspec
@@ -28,7 +28,7 @@ Pod::Spec.new do |s|
   s.ios.deployment_target = "11.0"
   s.osx.deployment_target = "10.13"
   s.tvos.deployment_target = "11.0"
-  s.visionos.deployment_target = "1.0"
+  s.visionos.deployment_target = "1.0" if s.respond_to?(:visionos)
 
   s.preserve_paths = '*.js'
 
```

**Comment by krystofwoldrich** [comment]
Hello everyone, 
and thank you @johnf for the issue and PR, we will try it in a `react-native-visionos` and release a hot fix.

**Comment by dnelsonlivecurrence** [comment]
FYI, an Expo Doctor check will fail on the latest version if you try downgrading to fix this issue:
```
The following packages should be updated for best compatibility with the installed expo version:
  @sentry/react-native@5.16.0 - expected version: 5.17.0
Your project may not work correctly until you install the correct versions of the packages.
```

**Comment by evulse** [comment]
This is just caused by having an older version of Cocoapods, you can just update with

```$ [sudo] gem install cocoapods```

https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

**Comment by evulse** [comment]
@erik-lissen maybe just confirm the version you are running with `pod --version`. 

After i updated to `1.14.3` i didn't have this issue any more.

**Comment by erik-lissen** [comment]
@evulse thank you, I had a mismatch of cocoapods installations. Can confirm, updating to 1.14.3 solved the issue

**Comment by esphung** [comment]
> If you are using patch-package you can use this diff
> 
> ```
> diff --git a/node_modules/@sentry/react-native/RNSentry.podspec b/node_modules/@sentry/react-native/RNSentry.podspec
> index e752ab8..d5f7558 100644
> --- a/node_modules/@sentry/react-native/RNSentry.podspec
> +++ b/node_modules/@sentry/react-native/RNSentry.podspec
> @@ -28,7 +28,7 @@ Pod::Spec.new do |s|
>    s.ios.deployment_target = "11.0"
>    s.osx.deployment_target = "10.13"
>    s.tvos.deployment_target = "11.0"
> -  s.visionos.deployment_target = "1.0"
> +  s.visionos.deployment_target = "1.0" if s.respond_to?(:visionos)
>  
>    s.preserve_paths = '*.js'
>  
> ```

Thanks for this patch! WOrks like a charm

**Comment by felipesilva-plank** [comment]
Thank god, i thought i was the only one having this problem

**Comment by leons1767** [comment]
Thanks @evulse for the cocoapods suggestion. 

I'm using Expo and EAS is doing the building. I added ` "image" : "latest" `  to "ios" properties to fix it. I suppose the latest xcode server image included the latest cocoapods to do the build.

**Comment by MIRTAHAALI** [comment]
I had similar issue but with RNCClipboard, and it is fixed by doing following in package.json


`"@react-native-clipboard/clipboard": "^1.6.0",`

to 

`"@react-native-clipboard/clipboard": "1.6.0",`

**Comment by JacobDel** [comment]
> I had similar issue but with RNCClipboard, and it is fixed by doing following in package.json
> 
> `"@react-native-clipboard/clipboard": "^1.6.0",`
> 
> to
> 
> `"@react-native-clipboard/clipboard": "1.6.0",`

visionOS support was added in update v1.14.0, v1.13.2 should be good.
Otherwise I found this: https://github.com/react-native-clipboard/clipboard/issues/241

**Comment by BenjaminWatts** [comment]
Or disable hermes in your podfile : 

 :hermes_enabled => false, ##podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
