### ISSUE TITLE
sentry-expo-upload-sourcemaps does not use plugin defined org

### ISSUE THREAD

**Issue by LegendEffects** [getsentry/sentry-react-native#3556]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

When trying to upload source maps using `npx sentry-expo-upload-sourcemaps dist` as [documented here](https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/expo/) I get the following error:

```
🐕 Fetching SENTRY_PROJECT from expo config...
2024-01-26T15:03:37.157Z expo:env No environment variables loaded from .env files.
SENTRY_PROJECT resolved to REDACTED from expo config.
⬆️ Uploading dist/_expo/static/js/android/index-e2816ec341c0b1feb2fbda3f7d1362b4.hbc bundle and sourcemap...
error: An organization slug is required (provide with --org)
Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
node:child_process:965
    throw err;
    ^
Error: Command failed: /builds/[REDACTED]/[REDACTED]/app-v2-experiments/node_modules/@sentry/cli/bin/sentry-cli sourcemaps upload --debug-id-reference dist/_expo/static/js/android/index-e2816ec341c0b1feb2fbda3f7d1362b4.hbc dist/_expo/static/js/android/index-e2816ec341c0b1feb2fbda3f7d1362b4.hbc.map
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (/builds/[REDACTED]/[REDACTED]/app-v2-experiments/node_modules/@sentry/react-native/scripts/expo-upload-sourcemaps.js:151:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 707,
  stdout: null,
  stderr: null
}
Node.js v20.11.0
```

This appears to be due to the source map script assuming that the organization will be provided through an env var and not within the config.

**Steps to reproduce:**
- Follow Expo's sentry setup steps
- Configure the org within the plugin config instead of an env var

**Actual result:**

Sentry CLI errors due to not getting an org slug

**Expected result:**

The Sentry CLI should be passed the org slug defined within the Expo config

**Comment by krystofwoldrich** [comment]
Hi @LegendEffects,
thank you for the message and the PR, we will review it shortly. 

The current script expects the org to be inferred from the organization auth token or set by env `SENTRY_ORG`. Nevertheless, reading it from the plugin configuration is a good addition.
