### ISSUE TITLE
Expo 50.0.2 IOS release build fails

### ISSUE THREAD

**Issue by andrewdavidcostello** [getsentry/sentry-react-native#3558]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

Using Expo to publish a release build results in a failure. Android is fine.

The problem seems to be a difference in paths.

`Error: ENOENT: no such file or directory, open`

For example:

`HBC_SOURCEMAP_FILE=/Users/expo/Library/Developer/Xcode/DerivedData/[redacted]/Build/Intermediates.noindex/ArchiveIntermediates/[redacted]/BuildProductsPath/Release-iphoneos/[redacted].app/main.jsbundle.map`

but then it tries to load from

`/Users/expo/Library/Developer/Xcode/DerivedData/[redacted]/Build/Intermediates.noindex/ArchiveIntermediates/[redacted]/BuildProductsPath/Release-iphoneos/main.jsbundle.map`

**Actual result:**

The map file is not found and throws an error

**Expected result:**

The map file is found

**Comment by andrewdavidcostello** [comment]
This may be fixed by updating eas-cli, will be unable to confirm till next week.

**Comment by krystofwoldrich** [comment]
Hi @andrewdavidcostello,
the HBC_SOURCEMAP_FILE should not be uploaded, it's an intermediate file, that is used to create the JS source map. 

More detail here: https://github.com/expo/expo/blob/8d29bbba0ccd4ecb35bac0df7b512ee129d3cde8/packages/expo/scripts/react-native-xcode.sh#L183-L184

Could you share the commands you used to build/archive the application? Are you using the [Continuous Native Generation](https://docs.expo.dev/workflow/continuous-native-generation/)?

**Comment by francescov1** [comment]
Hi all, Im running into this issue without using expo (just recently added Sentry to my RN project, all archives fail now due to a missing main.jsbundle.map file)
