### ISSUE TITLE
Apple analytics shows triple the amount of crashes since adding sentry-react-native

### ISSUE THREAD

**Issue by dylancom** [getsentry/sentry-react-native#3561]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.16.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have the following issue:**

After I released a new version of my app which only added Sentry integration, Apple Analytics shows triple the amount of crashes. While there used to be between 0 - 50 crashes per day, now it shows 100-150 crashes per day.
In Sentry I notice a lot of "The OS watchdog terminated your app, possibly because it overused RAM." errors. The breadcrumbs show that it happens if people leave the app a while in the background and return.

Could it be that Sentry doesn't play nicely with for e.g. nodejs-mobile-react-native?
The only thing I have added in the new release was Sentry integration...

**Comment by krystofwoldrich** [comment]
Hi @dylancom,
thank you for the message, we are unaware of any incompatibility with `nodejs-mobile-react-native`, but we also don't know the package in detail.

Is there any specific behavior/functionality that you have in mind?

**Comment by nugmanoff** [comment]
Hey @dylancom! Were you able to pinpoint the root cause of the issue eventually? I am facing somewhat similar issue

**Comment by dylancom** [comment]
Nope, stopped using nodejs-mobile-react-native.
