### ISSUE TITLE
Release version using sentry-android 7.2.0

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#3570]
Currently the newest version has a dependency on sentry-android 6.34.

In a hybrid project using sentry-android-gradle-plugin, which uses sentry-android 7.2.0, sentry-react-native isn't working with the forced newer version.

Please release all libraries with compatible dependencies together.

**Comment by bastiaanv** [comment]
Upvote!

**Comment by krystofwoldrich** [comment]
@pvegh @bastiaanv Thank you for the message, we will release a new version of the RN SDK with the updated `sentry-android` soon.

For anyone running into issues here are steps on how to stay on v6 of sentry-android.
- https://github.com/getsentry/sentry-react-native/issues/3497#issuecomment-1889566285

**Comment by krystofwoldrich** [comment]
- This PR will fix it: https://github.com/getsentry/sentry-react-native/pull/3434

I will be part of the next release (likely 5.19.0).

**Comment by pvegh** [comment]
Thanks.
But in that case it's going to be 7.3 vs 7.2 coming from https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.2.0
We need a version with 7.2 before 7.3

**Comment by krystofwoldrich** [comment]
@pvegh I'm not sure if I understand what would be the issue with 7.3. Could you describe an example?

https://github.com/getsentry/sentry-android-gradle-plugin ships with the latest `sentry-android` version at the moment of its release for convenience. But it's not limiting users from using different `sentry-android` versions they specify. You can use both older and newer versions of `sentry-android` with https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.2.0 with the auto-install disabled.

**Comment by pvegh** [comment]
If sentry-android-gradle-plugin transitively uses 7.3 and sentry-react-native uses 7.2 it's a gradle dependency mismatch which will be solved by gradle, without guarantee that it will work perfectly.

Not sure how auto install works, just because I define a different version, is it guaranteed to function perfectly?

Thanks for the fix and release!

**Comment by krystofwoldrich** [comment]
@pvegh Thank you for the details.

@markushi @romtsn Does the autoInstall flag solve the dependency mismatch?

**Comment by krystofwoldrich** [comment]
@tobi512 Could it be crashes from older versions of your application?

When you clean build a release version of your app and cause a native crash on Android, what version gets reported?

**Comment by krystofwoldrich** [comment]
Closing in favor of https://github.com/getsentry/sentry-react-native/issues/3671 which solves the version mismatch.
