### ISSUE TITLE
Expo source maps upload - release is not being created

### ISSUE THREAD

**Issue by lusarz** [getsentry/sentry-react-native#3581]
### Description

Upload source maps script from the `sentry-expo` repository contained a `sentry-cli releases new ...` invocation (see [here](https://github.com/expo/sentry-expo/blob/329888ed38d5a5d72e0f2bd432f31e661a7ab5f0/src/hooks/upload-sourcemaps.ts#L129-L132)). The script from this repository doesn't contains this logic - the only `sentry-cli` [invocation](https://github.com/getsentry/sentry-react-native/blob/a588df89e1c05a0e33e75f91ec633f3d9becf5b9/scripts/expo-upload-sourcemaps.js#L183-L190) is for upload source maps itself.

**Comment by krystofwoldrich** [comment]
@lusarz Thank you for the message,
could you share a bit more details about if and when is this an issue? Do you not see your releases in Sentry?

Note releases are automatically created when the first event is sent to Sentry.

Releases are not required anymore for source maps upload as Debug IDs are used to select the correct source map for symbolication.

**Comment by lusarz** [comment]
@krystofwoldrich I don't see new releases in Sentry but we didn't yet published the app so no event was propagated so far. I'll check if new release will be created that way.

**Comment by krystofwoldrich** [comment]
@lusarz I'll close this for now, in case something won't work feel free to comment here and we can reopen the issue.
