### ISSUE TITLE
Failure to find NODE_BINARY causes debug upload to fail

### ISSUE THREAD

**Issue by wkirby** [getsentry/sentry-react-native#3587]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.18.0

**`react-native` version:** 0.73.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: SENTRY_DSN,
  tracesSampleRate: 0.1,
});
```

---
**I have the following issue:**

From Xcode, running the `Archive` command results in a `PhaseScriptExecution` failure with nonzero exit code in `Upload Debug Symbols to Sentry`:

```
+ '[' -z '' ']'
+ WITH_ENVIRONMENT=../node_modules/react-native/scripts/xcode/with-environment.sh
+ '[' -f ../node_modules/react-native/scripts/xcode/with-environment.sh ']'
+ . ../node_modules/react-native/scripts/xcode/with-environment.sh
+++ command -v node
++ NODE_BINARY=
Command PhaseScriptExecution failed with a nonzero exit code

+ '[' -z '' ']'

+ WITH_ENVIRONMENT=../node_modules/react-native/scripts/xcode/with-environment.sh

+ '[' -f ../node_modules/react-native/scripts/xcode/with-environment.sh ']'

+ . ../node_modules/react-native/scripts/xcode/with-environment.sh

+++ command -v node

++ NODE_BINARY=

Command PhaseScriptExecution failed with a nonzero exit code
```

The error appears to happen when the `with-environment.sh` attempts to call `command -v node`, but _only_ within the `Upload Debug Symbols to Sentry` build phase. The same script (`with-environment.sh`) executes without issue as part of other steps of the build process.

Here is a screenshot of the build-phase configuration:

<img width="971" alt="Screenshot 2024-02-09 at 12 43 33 PM" src="https://github.com/getsentry/sentry-react-native/assets/579688/336f4618-779f-48e7-ad3e-6540605969e9">

**Note:**

If I modify `with-environment.sh` and comment out these lines:

```sh
# Start with a default
NODE_BINARY=$(command -v node)
export NODE_BINARY
```

The build works as expected.

**Actual result:**

The build fails to complete.

**Expected result:**

The build completes successfully and uploads debug symbols.

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message,
this was fixed in
- https://github.com/getsentry/sentry-react-native/pull/3573

and will be released shortly.

**Comment by wkirby** [comment]
@krystofwoldrich thank you!
