### ISSUE TITLE
Sentry.wrap types don't play nicely with Expo's registerRootComponent

### ISSUE THREAD

**Issue by jgarplind** [getsentry/sentry-react-native#3596]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Prerequisites:
- Use TypeScript
- Use React Native

1. Set up Sentry SDK as per https://docs.sentry.io/platforms/react-native/manual-setup/expo/
2. In `index.tsx` use `registerRootComponent(App);`, (worked fine before introducing Sentry), because:

> // registerRootComponent calls AppRegistry.registerComponent('main', () => App);
> // It also ensures that whether you load the app in Expo Go or in a native build,
> // the environment is set up appropriately

### Expected Result

Happy TypeScript

### Actual Result

```
Argument of type 'ComponentType<Record<string, unknown>>' is not assignable to parameter of type 'ComponentType<InitialProps>'.
  Type 'ComponentClass<Record<string, unknown>, any>' is not assignable to type 'ComponentType<InitialProps>'.
    Type 'ComponentClass<Record<string, unknown>, any>' is not assignable to type 'ComponentClass<InitialProps, any>'.
      Construct signature return types 'Component<Record<string, unknown>, any, any>' and 'Component<InitialProps, any, any>' are incompatible.
        The types of 'props' are incompatible between these types.
          Property 'exp' is missing in type 'Readonly<Record<string, unknown>>' but required in type 'Readonly<InitialProps>'.ts(2345)
registerRootComponent.d.ts(4, 5): 'exp' is declared here.
```

### Product Area

Unknown

**Comment by krystofwoldrich** [comment]
This is caused by the props type to be resolved as `unknown` when no props are specified.

If the `App` props are typed to a type satisfying the https://github.com/krystofwoldrich/expo/blob/7ca7c4308a4a76f5d30824fca34262f10df13b79/packages/expo/src/launch/registerRootComponent.tsx#L6

then the type error won't occur.

```ts
export default function App(props: { exp: {} }) { // or props: undefined
//...
});
```

It this helpful?

**Comment by jgarplind** [comment]
> It this helpful?

Maybe, but not the sort of workaround solution I had in mind.

I'm not sure exactly what Expo is doing on their side, but so far I've been able to happily run `function App() {` with no further type issues.

**Comment by rayronvictor** [comment]
This worked for me:

```tsx
registerRootComponent(Sentry.wrap(App) as Parameters<typeof registerRootComponent>[0]);
```

**Comment by krystofwoldrich** [comment]
When https://github.com/expo/expo/pull/27095 is released, no workarounds will be needed.

Thank you everyone for the engagement and thank you @brentvatne for the Expo PR.
