### ISSUE TITLE
Sourcemaps not working with `react-native-web`

### ISSUE THREAD

**Issue by mikevercoelen** [getsentry/sentry-react-native#3598]
First of all, it's great to see a collab going with Expo, we have sourcemaps working for EAS updates, however that migration now broke react-native-web sourcemaps.

This is important for teams who built a cross platform app.

The sourcemaps are just not resolved correctly anymore.

**SDK:**
- [x]  `@sentry/react-native` 5.19.0
- [x]  `expo` 50.0.6
- [x]  `react-native` 0.73.4
- [x]  `react-native-web` 0.19.9

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://nestio-1.sentry.io/issues/4976569864/?environment=staging_web&project=6178292&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0

**Comment by krystofwoldrich** [comment]
Hi @mikevercoelen,

I see that you are using `@sentry/react` for your web build, that's okay.

I've checked the event you have linked and the source maps for that particular build were not uploaded. You can verify that but the `Unminify Code` button next to the stack frames.

Is it possible you only uploaded the source maps to your mobile Sentry project? Or default guides assume you have one Sentry project for mobile and web. If you have two separate projects you have to upload the source maps to both.

**Comment by mikevercoelen** [comment]
@krystofwoldrich we trigger uploads to Sentry manually for web, separately,

First we trigger `npx expo export --platform web--dump-sourcemap` which creates the bundle (and sourcemaps in `/dist`)

Then we run this:

```
import SentryCli from '@sentry/cli';

const uploadSourcemaps = async () => {
    const cli = new SentryCli(null, {
        org: process.env.EXPO_PUBLIC_SENTRY_ORG!,
        project: process.env.EXPO_PUBLIC_SENTRY_PROJECT!,
    }).releases;

    const releaseId = process.env.EXPO_PUBLIC_SENTRY_RELEASE!;

    await cli.new(releaseId);
    await cli.uploadSourceMaps(releaseId, {
        include: [PATH_DIST],
    });
    await cli.finalize(releaseId);
};
```

Does all of this look correct to you? Could it be that since the react native version, we had to make changes to the `metro.config.js` file:

```
const { getSentryExpoConfig } = require('@sentry/react-native/metro');

const defaultConfig = getSentryExpoConfig(__dirname, {
    isCSSEnabled: true,
});
```

It's now conflicting?

**Comment by mikevercoelen** [comment]
> Hi @mikevercoelen,
> 
> I see that you are using `@sentry/react` for your web build, that's okay.
> 
> I've checked the event you have linked and the source maps for that particular build were not uploaded. You can verify that but the `Unminify Code` button next to the stack frames.
> 
> Is it possible you only uploaded the source maps to your mobile Sentry project? Or default guides assume you have one Sentry project for mobile and web. If you have two separate projects you have to upload the source maps to both.

Seems like its uploaded correctly?

<img width="574" alt="Screenshot 2024-02-14 at 16 37 51" src="https://github.com/getsentry/sentry-react-native/assets/3009836/6f82d19e-00d6-4511-aa13-05db464f0c36">

**Comment by krystofwoldrich** [comment]
@mikevercoelen 

From the linked event I see that the error event has a DebugID, this is created and poly-filled into the bundle by `getSentryExpoConfig`. So that seems to be working correctly.

The warning says you uploaded some source maps with DebugIDs, but for the specific build of your app the source maps with `a2fcc08a-c00a-4f33-9d5c-4075f73b1151` were not uploaded.

Can you try to upload the source maps using this:

```bash
SENTRY_PROJECT=your-project \
SENTRY_ORG=your-org \
npx sentry-expo-upload-sourcemaps dist
```

**Comment by mikevercoelen** [comment]
@krystofwoldrich it worked! boom, thanks for the help man!

We can now ditch all our custom source map uploading code which was smelly from all sides.

Might be worth adding this to the docs, it's not intuitive that this also works out of the box for `react-native-web`.

**Comment by mikevercoelen** [comment]
RESOLVED, thanks
