### ISSUE TITLE
Unable to modify build script 'Bundle React Native code and images'.

### ISSUE THREAD

**Issue by Acetyld** [getsentry/sentry-react-native#3602]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.4

**`expo` version:** ~50.0.6

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [X]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://4d0d38cd5d49dbdd5047062a34e716c1@sentry.vitrion.dev/50',
  debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
});
```

---
**I have the following issue:**

The stacktrace is not working on anything other then a full production release.
Only when eas build is ran a actuall release is being uploaded to sentry.
It looks like the metro.config.js is correctly uploading the debug ID's but we are just not getting any matches inside sentry

**Steps to reproduce:**
- Step 1: Clone the reproduction repo: **https://github.com/stichingsd-vitrion/sentry-expo-bug-reproduction**
- Step 2: Setup the auth token inside the .ENV for sentry and if needed change the URL in the app.json (does not matter if sentry.io or self hosted) 
- Step 3: Run yarn && yarn ios and press the crash button

**Actual result:**

A incorrect stack trace in sentry, here is a example from a crash on localhost or a dev build:
<img width="809" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/55088242/b88cfb68-6469-4f0b-b282-3674764b3454">

**Expected result:**
A actual stack trace in sentry, here is a example from a production build of the app

<img width="809" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/55088242/98cd9106-46e1-4e7e-9658-85f049d03002">

**More screenshots of sentry:**
Release bundles
<img width="917" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/55088242/ce89b176-a26f-4f45-905e-acf8d3f33cc2">
Artifact Bundles
<img width="922" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/55088242/b8dbcc4c-76a6-438f-8104-b15eea436bc7">
Debug Files
<img width="945" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/55088242/b412a01a-3ee1-47e1-b5dd-da09bb6f8da3">

**Warning when running prebuild**

As the docs says *builds are uploaded automatically during EAS Builds and when building the native application release locally using npx expo prebuild.*

So one of many things i tried was ofc running prebuild, but this gives:
```
» ios: @sentry/react-native: Unable to modify build script 'Bundle React Native code and images'. Please open a bug report at https://github.com/expo/sentry-expo.
```

**Comment by Acetyld** [comment]
Hi there! The --clean and the deletion of ios/android has no difference in the output sadly.

```
/bin/sh `${NODE_BINARY:-node} --print "require('path').dirname(require.resolve('@sentry/react-native/package.json')) + '/scripts/sentry-xcode-debug-files.sh'"`
```
![image](https://github.com/getsentry/sentry-react-native/assets/55088242/dbc4ee90-d242-4942-a387-d5b0dd6b22e1)

PS:
I also tried --clean and deletion of ios and android again, but i still have the same warning
```
» ios: @sentry/react-native: Unable to modify build script 'Bundle React Native code and images'. Please open a bug report at https://github.com/expo/sentry-expo.
```

**Comment by krystofwoldrich** [comment]
@Acetyld Can you share the `Bundle React Native code and images` as that's the one that the Sentry plugin wasn't able to update?

**Comment by Acetyld** [comment]
Hi! 

Where can i find the bundle/images? Are they in .expo or somewhere else?

**Comment by krystofwoldrich** [comment]
It's in the same list as the other build phase `Upload Debug Symbols to Sentry` in Xcode.

**Comment by Seamus1989** [comment]
any update on this?
