### ISSUE TITLE
Expo production app crashes when introducing new expo package and tracesSampleRate is set

### ISSUE THREAD

**Issue by bjornevik** [getsentry/sentry-react-native#3623]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** `@sentry/react-native@5.17.0`

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://haugaland-kraft-energi.sentry.io/issues/4928342061/?project=4504360499085312)

**Configuration:**

(`@sentry/react-native`)
```ts
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  debug: false,
  tracesSampleRate: 0.01 // If I comment this line out it works
});
```

---
**I have the following issue:**

Background: Recently one of our integrations introduced android and iOS SDKs to extend functionality. These sdks were very neatly packaged into a simple expo plugin [`@youssefhenna/expo-enode-link-sdk`](https://www.npmjs.com/package/@youssefhenna/expo-enode-link-sdk), where I've opened an issue for that project as well (https://github.com/YoussefHenna/expo-enode-link-sdk/issues/12). This plugin works fine in our existing app when running iOS and android developments builds, as well as a iOS production builds.

When running android production builds after this plugin is installed (not even used) the app will show the splash screen and then immediately crash. If I remove either this plugin OR I comment out the `Sentry.init` and `Sentry.wrap(App)` lines the app launches fine with production builds. I found that it worked if I passed an empty object to `Sentry.init({})`, and was able to narrow it down to the `tracesSampleRate` property. It seems like whenever I set `tracesSampleRate` the app will crash on startup for production builds.

The only related logs I find in `adb logcat` is as follows:
```
AndroidRuntime: java.lang.RuntimeException: Could not invoke RNSentry.fetchNativeAppStart

// ...
E ReactNativeJS: ReferenceError: Property 'viewManagersMetadata' doesn't exist, js engine: hermes
E ReactNativeJS: Invariant Violation: "main" has not been registered. This can happen if:
E ReactNativeJS: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
E ReactNativeJS: * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

I've been stuck on this for about a week. I don't get why this Invariant violation _only_ happens when Sentry is configured AND this plugin is installed. If there was something wrong with the plugin by itself I would expect it to happen in under scenarios as well.

This happened on both Expo SDK 49, as well as after upgrading to Expo SDK 50.

Any pointers, or help with troubleshooting is appreciated.

I'm suspecting it may be roughly related to #3497,, but given that it only happens when I introduce the `@youssefhenna/expo-enode-link-sdk` package it might be some interaction between Sentry and it. I don't know.

**Steps to reproduce:**
I have yet to be able to reproduce this on a clean project myself - I know it's bad practice to open an issue without a minimal repro, but I've been hard stuck with this issue for a while and I'm at wits end here.

As far as I can tell, this should be the steps to reproduce, but once again, I haven't been able to reproduce it in a clean project myself.
- Have an app with a configured `@sentry/react-native`
- `npx expo install @youssefhenna/expo-enode-link-sdk`
- Build production build
- Launch

**Actual result:**
Crash

**Expected result:**
No crash

**Comment by krystofwoldrich** [comment]
Hi @bjornevik,
it seems like the same issue as https://github.com/getsentry/sentry-react-native/issues/3497 which you mentioned.

Can you try to upgrade to https://github.com/getsentry/sentry-react-native/releases/tag/5.19.0 and let us know if it resolves the issue?

**Comment by bjornevik** [comment]
@krystofwoldrich seems like 5.19.0 fixes it.

Forgot that `npx expo install` doesn't necessarily install the latest version.
