### ISSUE TITLE
MaxBreadcrumbSize to 0 crashes Android on Start

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-react-native#3634]
## 🔴 Waiting for
- Release of https://github.com/getsentry/sentry-java/issues/3313
- Bump `sentry-android` in RN

**OS:**
- [X]  Windows
- [ ]  MacOS
- [X]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  // Replace the example DSN below with your own DSN:
  dsn: SENTRY_INTERNAL_DSN,
  debug: true,
  environment: 'dev',
  maxBreadcrumbs: 0,
 ...
});
```

---
**I have the following issue:**

 If you set maxBreadcrumbs: 0, the app will crash when opened. it's not mentioned that the size 0 will not work  on the docs but if I recall it worked on other SDK that I worked in the past.

**Steps to reproduce:**
- Step 1
- maxBreadcrumbs: 0 on SentryOptions
- Step 2
- Open the app

**Actual result:**

<img width="333" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/8229322/76efc5d1-e353-4cc6-8c88-63d66fa3a1ad">

**Expected result:**

The app to not crash and have events without breadcrumbs.

**Comment by krystofwoldrich** [comment]
Two items to fix, pass a valid value to `sentry-android` and ensure that no breadcrumbs are added in JS.

We might need to fix/check `sentry-java` to allow `0`.

**Comment by lucas-zimerman** [comment]
Related: https://github.com/getsentry/sentry-java/issues/3313
