### ISSUE TITLE
filter release data per client os

### ISSUE THREAD

**Issue by pierricklete** [getsentry/sentry-react-native#3637]
querying release dataset doesn't allow to filter per client os name (like with `os.name` for _errors and transactions_ dataset)
this is blocking us to create a dashboard widget to have crash rate per mobile platform

**Comment by krystofwoldrich** [comment]
Hi @pierricklete,
thank you for the message,

you could create a similar view using errors and filtering crashes and `os.name`, like this:

![Screenshot 2024-02-28 at 11 32 38](https://github.com/getsentry/sentry-react-native/assets/31292499/b2ea2e92-138a-42f4-bf8a-26f7ddc25890)

Would that work for you?

**Comment by pierricklete** [comment]
thanks @krystofwoldrich but your solution is about number of affected users or sessions, this is not a rate that depends of traffic
only a rate will allow us to efficiently detect anomaly

**Comment by pierricklete** [comment]
> maybe filtering for specific releases could help if you have separate releases for Android and iOS?

this will only be possible if we can use wildcard to filter
<img width="267" alt="Screenshot 2024-02-29 at 11 28 06" src="https://github.com/getsentry/sentry-react-native/assets/7978490/35f1b807-c331-4fbc-9263-cd75bcae7768">


> Or you can add the platform to the environment option in the SDK and then use that for the filtering.

I would prefer to avoid this workaround, this will result into a breaking change for on alerts and dashboard

**Comment by krystofwoldrich** [comment]
@pierricklete I see, thanks for the details, I'll mark this as a feature request.
