### ISSUE TITLE
expo web not sending debug ids - metro

### ISSUE THREAD

**Issue by 0mitch** [getsentry/sentry-react-native#3638]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Web

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.19.1

**`react-native` version:** 0.73.4

**Are you using Expo?**
- [x]  Yes - Expo 50
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

- [Working mobile source maps](https://moonpay.sentry.io/issues/5014043834/?project=4506704741072896&query=error.unhandled%3Atrue+is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30m&stream_index=0)
- [Broken web source maps ](https://moonpay.sentry.io/issues/5005994180/?project=4506704741072896&query=error.unhandled%3Atrue+is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=30m&stream_index=1)

**Configuration:**

Example Metro Config
```
// Learn more: https://docs.expo.dev/guides/monorepos/
const exclusionList = require('metro-config/src/defaults/exclusionList');
const { getSentryExpoConfig } = require('@sentry/react-native/metro');
const { withNativeWind } = require('nativewind/metro');

const path = require('path');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

// Create the default Metro config
// https://docs.expo.dev/guides/using-sentry/#update-metro-configuration
const config = getSentryExpoConfig(projectRoot, { isCSSEnabled: true });

if (config.resolver) {
  // 1. Watch all files within the monorepo
  config.watchFolders = [workspaceRoot];
  // 2. Let Metro know where to resolve packages and in what order
  config.resolver.nodeModulesPaths = [
    path.resolve(projectRoot, 'node_modules'),
    // Needed to resolve deps of expo router
    path.resolve(workspaceRoot, 'node_modules/expo-router/node_modules'),
    path.resolve(workspaceRoot, 'node_modules/expo/node_modules'),
    path.resolve(workspaceRoot, 'node_modules'),
  ];
  // 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
  config.resolver.disableHierarchicalLookup = true;
  // 5. Adds cjs and mjs resolutions for packages that use them as an extension
  config.resolver.sourceExts = [...config.resolver.sourceExts, 'cjs', 'mjs'];
}

module.exports = withNativeWind(config, { input: './assets/global.css' });
```

---
**I have the following issue:**

I've followed the instructions as per the [Use Sentry Expo Documentation ](https://docs.expo.dev/guides/using-sentry/#update-metro-configuration) however our sourcemaps are still not working for our web version (bundled via [metro](https://docs.expo.dev/guides/customizing-metro/#adding-web-support-to-metro)).

**Actual result:**

As per the links above you can see sourcemaps are working fine for mobile however on web we get the following issue where no debug ids are sent which smells like an issue with the metro bundling on web and maybe the debug ids not being added. This results in the below error from the Sentry UI:

<img width="586" alt="Screenshot 2024-02-28 at 13 13 28" src="https://github.com/getsentry/sentry-react-native/assets/138505192/a1678734-af43-45c0-b61b-e53910180492">

**Expected result:**

Debug Ids are sent across from our bundled web app that is built via metro and the uploaded sourcemaps as part of the build process (`pnpm sentry-expo-upload-sourcemaps ./dist`) are correctly associated.

**Comment by krystofwoldrich** [comment]
Hi @0mitch,
thank you for the message,

can you verify that the Debug ID is generated for the web bundle as it is for the mobile bundles?

The Debug ID polyfill should be on the second line of the bundle as well as in the source maps under `debugId` key.

**Comment by 0mitch** [comment]
> Hi @0mitch, thank you for the message,
> 
> can you verify that the Debug ID is generated for the web bundle as it is for the mobile bundles?
> 
> The Debug ID polyfill should be on the second line of the bundle as well as in the source maps under `debugId` key.

@krystofwoldrich Thanks for getting back to us... below is what I'm seeing when looking at an Artifact Bundle is this what you meant? 

<img width="1195" alt="Screenshot 2024-03-01 at 10 50 19" src="https://github.com/getsentry/sentry-react-native/assets/138505192/8b8cecdd-8098-46ae-9533-02374377da56">

The downloaded Source Map doesn't appear to have a `debugID` on the second line either:

<img width="219" alt="Screenshot 2024-03-01 at 10 53 10" src="https://github.com/getsentry/sentry-react-native/assets/138505192/06f937bd-442c-425d-bad1-68bb2d1b9df1">

Let me know if I'm looking in the wrong place.

**Comment by krystofwoldrich** [comment]
@0mitch Thank you. This is the mobile source map, from what I understand that is working for you? 

I had in mind the web bundle and source map. This is how you can check it:

1. Run `npx expo export --dump-sourcemap --platform web`
2. Check if `dist/_expo/static/js/web/entry-*.js` contains a Debug ID polyfill on the second line (starts with `var _sentryDebugIds={}`).
3. Check if `dist/_expo/static/js/web/entry-*.js.map` contains `"debugId"` key (usually as the last key in the JSON).

**Comment by krystofwoldrich** [comment]
@0mitch Thank you for the details, I see from the file names, that you are using bundle splitting, and I was able to reproduce the issue when enabling bundle splitting for our sample application.

**Comment by 0mitch** [comment]
> @0mitch Thank you for the details, I see from the file names, that you are using bundle splitting, and I was able to reproduce the issue when enabling bundle splitting for our sample application.

@krystofwoldrich Thanks for confirming the issue I also tested with no bundle splitting and can confirm the sourcemaps are now working as expected. For anyone else that stumbles across this issue with expo router the following config will get this running:

```
  plugins: [
    [
      'expo-router',
      {
        asyncRoutes: {
          web: false, // SET THIS TO FALSE
          default: 'development',
        },
      },
    ],
```
   
> Note: after you need to make sure to run the source map upload on your web build _(not EAS update)_ . `expo export -p web --dump-sourcemap && pnpm sentry-expo-upload-sourcemaps ./dist`
