### ISSUE TITLE
Missing source file with a matching Debug ID

### ISSUE THREAD

**Issue by erwannbst** [getsentry/sentry-react-native#3639]
**OS:**  macOS

**Platform:** iOS

**SDK:** `@sentry/react-native` (5.19.1)

**`react-native` version:** 0.73.2

**Without Expo**

**using sentry.io (SaaS)**

[Link to issue](https://dronespot.sentry.io/issues/4920055844/?environment=production&project=4506473774776320&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  tracesSampleRate: 1.0,
    environment: __DEV__ ? "development" : "production",
    attachScreenshot: true,
    integrations: [new Sentry.ReactNativeTracing({routingInstrumentation})],
});
```
---
**I have the following issue:**

I've setup sentry in react native using `npx @sentry/wizard@latest -i sourcemaps` but the source map are not uploaded despite I get the notification at build

**Steps to reproduce:**
- Create a react native project without expo
- Instantiate sentry
- Create release version

**Actual result:**
<img width="166" alt="Screenshot 2024-02-29 at 10 15 17" src="https://github.com/getsentry/sentry-react-native/assets/16354899/74432368-5258-46b1-adc9-7c5c762c17f1">

<img width="410" alt="Screenshot 2024-02-29 at 10 26 59" src="https://github.com/getsentry/sentry-react-native/assets/16354899/7f9f9524-f336-41d9-be39-69a4f1c6deda">

I have source maps for android but not for iOS

<img width="1050" alt="Screenshot 2024-02-29 at 10 27 15" src="https://github.com/getsentry/sentry-react-native/assets/16354899/bc963ae4-456c-4192-ac35-22de9d00c317">

**Expected result:**
To see the stacktrace

**Comment by krystofwoldrich** [comment]
Hi @erwannbst,
thank you for the message, from the link you shared, I can see that the issue includes Debug ID, which means it was generated during the build. 

Now, we need to find out why it was not uploaded.

 The notification you mentioned `Debug symbols upload finished`, confirms native debug symbols were uploaded, which is unrelated to the javascript source maps.
 
 Can you check the `Bundle React Native code and images` build phase, you should see the generated Debug ID and information about the upload.
 
 If not, can you run the build with `export SENTRY_CLI_EXTRA_ARGS="--force-foreground --log-level=debug"`, https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload.

**Comment by erwannbst** [comment]
Here is the `Bundle React Native code and images` build phase :

<img width="764" alt="Screenshot 2024-02-29 at 13 20 00" src="https://github.com/getsentry/sentry-react-native/assets/16354899/3bf2dfff-faaf-41f0-b9b6-4db09223b1b5">

Since I archive using XCode, I don't have logs

**Comment by krystofwoldrich** [comment]
@erwannbst Thank you,  your `Bundle React Native code and images` is different from the default RN script. So `@sentry/wizard` automatically didn't update the build phase.

Here is what it should look like https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload 

```bash
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_XCODE="../node_modules/@sentry/react-native/scripts/sentry-xcode.sh"
BUNDLE_REACT_NATIVE="/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE"

/bin/sh -c "$WITH_ENVIRONMENT '$BUNDLE_REACT_NATIVE'"
```
