### ISSUE TITLE
Sentry Log error with IOS

### ISSUE THREAD

**Issue by meedodk** [getsentry/sentry-react-native#3645]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** "^5.19.1"

**`react-native` version:** 0.73.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://x@o1195017.ingest.sentry.io/x',
  tracesSampleRate: 0.2,
});
```
---
**I have the following issue:**

I suggest the issue is with when error/report/trace is sent to sentry.

**Steps to reproduce:**

Below error Happens on/off.  So a bit hard to reproduce

Argument 0 (eyJldmVudF9pZCI6Ijk5ZTFmMzdkMWIxMjQ2ZGJiMDdiZDUwZGUyMzA1MzFlIiwic2VudF9hdCI6IjIwMjQtMDItMjhUMjA6NDI6MTYuOTM2WiIsInNkayI6eyJuYW1lIjoic2VudHJ5LmphdmFzY3JpcHQucmVhY3QtbmF0aXZlIiwidmVyc2lvbiI6IjUuMTkuMSJ9LCJ0cmFjZSI6eyJlbnZpcm9ubWVudCI6ImRldmVsb3BtZW50IiwicHVibGljX2tleSI6IjBkNDJhZGFiMTg4YjQ3ODFiM2E4NzRiMTNhZGE3NTYxIiwidHJhY2VfaWQiOiIyNWVhMDcwZTEzZmY0NjlhYWMzYWY3MjhiOTZkZTEyMyIsInNhbXBsZV9yYXRlIjoiMC4yIiwidHJhbnNhY3Rpb24iOiJBcHAgU3RhcnQiLCJzYW1wbGVkIjoidHJ1ZSJ9fQp7InR5cGUiOiJ0cmFuc2FjdGlvbiIsImNvbnRlbnRfdHlwZSI6ImFwcGxpY2F0aW9uL2pzb24iLCJsZW5ndGgiOjgxNzd9CnsiY29udGV4dHMiOnsiYXBwIjp7ImFwcF9pZCI6IjhDMEU2OUU2LTNENTktMzAxQy04NDBFLTg3N0Y1RTAxN0M3QyIsImFwcF92ZXJzaW9uIjoiMi41LjAiLCJidWlsZF90eXBlIjoic2ltdWxhdG9yIiwiYXBwX2lkZW50aWZpZXIiOiJkay5wYXBwLnBhcHAiLCJhcHBfbWVtb3J5IjoyNzM1MzA4ODAsImFwcF9zdGFydF90aW1lIjoiMjAyNC0wMi0yOFQyMDo0MjoxNVoiLCJhcHBfYnVpbGQiOiIyMyIsImRldmljZV9hcHBfaGFzaCI6ImM2N2M3ODIzOWE4MTg4ODAzYTllYmI2ZmEwZTc0ODg0YmVkMGY5OWEiLCJhcHBfbmFtZSI6IlBhcHBSTiIsImluX2ZvcmVncm91bmQiOmZhbHNlfSwiZGV2aWNlIjp7ImJvb3RfdGltZSI6IjIwMjQtMDItMjhUMTA6Mzk6NTNaIiwic2ltdWxhdG9yIjp0cnVlLCJ1c2FibGVfbWVtb3J5IjoyMjkwOTM4Njc1MiwibW9kZWxfaWQiOiJzaW11bGF0b3IiLCJtZW1vcnlfc2l6ZSI6MzQzNTk3MzgzNjgsInNjcmVlbl93aWR0aF9waXhlbHMiOjM5MywiZnJlZV9tZW1vcnkiOjEzNTcwODY3Miwic3RvcmFnZV9zaXplIjo5OTQ2NjI1ODQzMjAsInNjcmVlbl9oZWlnaHRfcGl4ZWxzIjo4NTIsInByb2Nlc3Nvcl9jb3VudCI6MTAsImZyZWVfc3RvcmFnZSI6NDc1ODM5NTg2MzA0LCJmYW1pbHkiOiJpT1MiLCJsb2NhbGUiOiJkYV9ESyIsIm1vZGVsIjoiaVBob25lMTUsNCIsImFyY2giOiJhcm02NCJ9LCJvcyI6eyJidWlsZCI6IjIzQzcxIiwicm9vdGVkIjpmYWxzZSwia2VybmVsX3ZlcnNpb24iOiJEYXJ3aW4gS2VybmVsIFZlcnNpb24gMjMuMi4wOiBXZWQgTm92IDE1IDIxOjUzOjE4IFBTVCAyMDIzOyByb290OnhudS0xMDAwMi42MS4zfjIvUkVMRUFTRV9BUk02NF9UNjAwMCIsIm5hbWUiOiJpT1MiLCJ2ZXJzaW9uIjoiMTcuMiJ9LCJyZWFjdF9uYXRpdmVfY29udGV4dCI6eyJ0dXJib19tb2R1bGUiOmZhbHNlLCJmYWJyaWMiOmZhbHNlLCJyZWFjdF9uYXRpdmVfdmVyc2lvbiI6IjAuNzIuNyIsImV4cG8iOmZhbHNlLCJqc19lbmdpbmUiOiJoZXJtZXMiLCJoZXJtZXNfdmVyc2lvbiI6ImZvciBSTiAwLjcyLjciLCJoZXJtZXNfZGVidWdfaW5mbyI6dHJ1ZX0sInRyYWNlIjp7ImRhdGEiOnsic2VudHJ5Lm9yaWdpbiI6Im1hbnVhbCIsInNlbnRyeS5vcCI6InVpLmxvYWQiLCJzZW50cnkuc2FtcGxlX3JhdGUiOjAuMn0sIm9wIjoidWkubG9hZCIsInNwYW5faWQiOiI4MWU4YzkwNGQ3ZDMxNjhlIiwidHJhY2VfaWQiOiIyNWVhMDcwZTEzZmY0NjlhYWMzYWY3MjhiOTZkZTEyMyIsIm9yaWdpbiI6Im1hbnVhbCJ9fSwic3BhbnMiOlt7ImRhdGEiOnsic2VudHJ5Lm9yaWdpbiI6Im1hbnVhbCIsInNlbnRyeS5vcCI6ImFwcC5zdGFydC53YXJtIn0sImRlc2NyaXB0aW9uIjoiV2FybSBBcHAgU3RhcnQiLCJvcCI6ImFwcC5zdGFydC53YXJtIiwicGFyZW50X3NwYW5faWQiOiI4MWU4YzkwNGQ3ZDMxNjhlIiwic3Bhbl9pZCI6IjlmYmI5MDVhNDViNzllNjIiLCJzdGFydF90aW1lc3RhbXAiOjE3MDkxNTI5MzQuNjgzNjEyLCJ0aW1lc3RhbXAiOjE3MDkxNTI5MzUuNTY1LCJ0cmFjZV9pZCI6IjI1ZWEwNzBlMTNmZjQ2OWFhYzNhZjcyOGI5NmRlMTIzIiwib3JpZ2luIjoibWFudWFsIn0seyJkYXRhIjp7Imh0dHAucmVzcG9uc2Uuc3RhdHVzX2NvZGUiOjIwMCwic2VudHJ5Lm9yaWdpbiI6ImF1dG8uaHR0cC5icm93c2VyIiwic2VudHJ5Lm9wIjoiaHR0cC5jbGllbnQiLCJ0eXBlIjoieGhyIiwiaHR0cC5tZXRob2QiOiJHRVQiLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjQ0MzA5L3YxL3pvbmVzL2F2YWlsYWJsZS16b25lcyJ9LCJkZXNjcmlwdGlvbiI6IkdFVCBodHRwOi8vbG9jYWxob3N0OjQ0MzA5L3YxL3pvbmVzL2F2YWlsYWJsZS16b25lcyIsIm9wIjoiaHR0cC5jbGllbnQiLCJwYXJlbnRfc3Bhbl9pZCI6IjgxZThjOTA0ZDdkMzE2OGUiLCJzcGFuX2lkIjoiYjczZmE3ZjdlYjQ2NzJjYyIsInN0YXJ0X3RpbWVzdGFtcCI6MTcwOTE1MjkzNS43MTA2NzU1LCJzdGF0dXMiOiJvayIsInRhZ3MiOnsiaHR0cC5zdGF0dXNfY29kZSI6IjIwMCJ9LCJ0aW1lc3RhbXAiOjE3MDkxNTI5MzUuOTAyOTk5NCwidHJhY2VfaWQiOiIyNWVhMDcwZTEzZmY0NjlhYWMzYWY3MjhiOTZkZTEyMyIsIm9yaWdpbiI6ImF1dG8uaHR0cC5icm93c2VyIn1dLCJzdGFydF90aW1lc3RhbXAiOjE3MDkxNTI5MzQuNjgzNjEyLCJ0YWdzIjp7Imhlcm1lcyI6InRydWUiLCJldmVudC5vcmlnaW4iOiJqYXZhc2NyaXB0IiwiZXZlbnQuZW52aXJvbm1lbnQiOiJqYXZhc2NyaXB0In0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS45MDI5OTk0LCJ0cmFuc2FjdGlvbiI6IkFwcCBTdGFydCIsInR5cGUiOiJ0cmFuc2FjdGlvbiIsInRyYW5zYWN0aW9uX2luZm8iOnsic291cmNlIjoiY3VzdG9tIn0sIm1lYXN1cmVtZW50cyI6eyJhcHBfc3RhcnRfd2FybSI6eyJ2YWx1ZSI6ODgxLjM4NzkzOTQ1MzEyNSwidW5pdCI6Im1pbGxpc2Vjb25kIn19LCJyZXF1ZXN0Ijp7ImhlYWRlcnMiOnt9fSwiZXZlbnRfaWQiOiI5OWUxZjM3ZDFiMTI0NmRiYjA3YmQ1MGRlMjMwNTMxZSIsImVudmlyb25tZW50IjoiZGV2ZWxvcG1lbnQiLCJzZGsiOnsiaW50ZWdyYXRpb25zIjpbIlJlYWN0TmF0aXZlRXJyb3JIYW5kbGVycyIsIk5hdGl2ZUxpbmtlZEVycm9ycyIsIkluYm91bmRGaWx0ZXJzIiwiRnVuY3Rpb25Ub1N0cmluZyIsIkJyZWFkY3J1bWJzIiwiRGVkdXBlIiwiSHR0cENvbnRleHQiLCJSZWxlYXNlIiwiRXZlbnRPcmlnaW4iLCJTZGtJbmZvIiwiUmVhY3ROYXRpdmVJbmZvIiwiRGVidWdTeW1ib2xpY2F0b3IiLCJSZXdyaXRlRnJhbWVzIiwiRGV2aWNlQ29udGV4dCIsIk1vZHVsZXNMb2FkZXIiLCJSZWFjdE5hdGl2ZVRyYWNpbmciXSwibmFtZSI6InNlbnRyeS5qYXZhc2NyaXB0LnJlYWN0LW5hdGl2ZSIsInZlcnNpb24iOiI1LjE5LjEiLCJwYWNrYWdlcyI6W3sibmFtZSI6InNlbnRyeS5jb2NvYS5yZWFjdC1uYXRpdmUiLCJ2ZXJzaW9uIjoiOC4xMy4wIn0seyJuYW1lIjoibnBtOkBzZW50cnkvcmVhY3QtbmF0aXZlIiwidmVyc2lvbiI6IjUuMTkuMSJ9XX0sImJyZWFkY3J1bWJzIjpbeyJ0eXBlIjoiZGVidWciLCJsZXZlbCI6ImluZm8iLCJjYXRlZ29yeSI6InN0YXJ0ZWQiLCJtZXNzYWdlIjoiQnJlYWRjcnVtYiBUcmFja2luZyIsInRpbWVzdGFtcCI6MTcwOTE1MjkzNS40NjN9LHsibGV2ZWwiOiJkZWJ1ZyIsImNhdGVnb3J5IjoiY29uc29sZSIsIm1lc3NhZ2UiOiJSdW5uaW5nIFwiUGFwcFJOXCIgd2l0aCB7XCJyb290VGFnXCI6MSxcImluaXRpYWxQcm9wc1wiOnt9fSIsImRhdGEiOnsiYXJndW1lbnRzIjpbIlJ1bm5pbmcgXCJQYXBwUk5cIiB3aXRoIHtcInJvb3RUYWdcIjoxLFwiaW5pdGlhbFByb3BzXCI6e319Il0sImxvZ2dlciI6ImNvbnNvbGUifSwidGltZXN0YW1wIjoxNzA5MTUyOTM1LjU0Mn0seyJ0eXBlIjoiaHR0cCIsImxldmVsIjoiZXJyb3IiLCJjYXRlZ29yeSI6Imh0dHAiLCJkYXRhIjp7Im1ldGhvZCI6IkdFVCIsInJlc3BvbnNlX2JvZHlfc2l6ZSI6MCwidXJsIjoiaHR0cDovL3dwYWQvd3BhZC5kYXQiLCJyZXF1ZXN0X2JvZHlfc2l6ZSI6MH0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS41NzJ9LHsibGV2ZWwiOiJpbmZvIiwiY2F0ZWdvcnkiOiJjb25zb2xlIiwibWVzc2FnZSI6InJlcXVlc3Qgc2VudCB0byBodHRwOi8vbG9jYWxob3N0OjQ0MzA5IHYxL3pvbmVzL2F2YWlsYWJsZS16b25lcyIsImRhdGEiOnsiYXJndW1lbnRzIjpbInJlcXVlc3Qgc2VudCB0byIsImh0dHA6Ly9sb2NhbGhvc3Q6NDQzMDkiLCJ2MS96b25lcy9hdmFpbGFibGUtem9uZXMiXSwibG9nZ2VyIjoiY29uc29sZSJ9LCJ0aW1lc3RhbXAiOjE3MDkxNTI5MzUuNzM2fSx7InR5cGUiOiJuYXZpZ2F0aW9uIiwibGV2ZWwiOiJpbmZvIiwiY2F0ZWdvcnkiOiJ1aS5saWZlY3ljbGUiLCJkYXRhIjp7InNjcmVlbiI6IlJOU05hdmlnYXRpb25Db250cm9sbGVyIiwid2luZG93IjoiPFVJV2luZG93OiAweDEwNzcxMWY5MDsgZnJhbWUgPSAoMCAwOyAzOTMgODUyKTsgZ2VzdHVyZVJlY29nbml6ZXJzID0gPE5TQXJyYXk6IDB4NjAwMDAwYzMxNTkwPjsgbGF5ZXIgPSA8VUlXaW5kb3dMYXllcjogMHg2MDAwMDBjMzAxODA+PiIsIndpbmRvd19pc0tleVdpbmRvdyI6InRydWUiLCJwYXJlbnRWaWV3Q29udHJvbGxlciI6IlVJVmlld0NvbnRyb2xsZXIiLCJ3aW5kb3dfd2luZG93TGV2ZWwiOiIwLjAwMDAwMCIsImJlaW5nUHJlc2VudGVkIjoiZmFsc2UiLCJpc193aW5kb3dfcm9vdFZpZXdDb250cm9sbGVyIjoiZmFsc2UifSwidGltZXN0YW1wIjoxNzA5MTUyOTM1Ljc2N30seyJ0eXBlIjoibmF2aWdhdGlvbiIsImxldmVsIjoiaW5mbyIsImNhdGVnb3J5IjoidWkubGlmZWN5Y2xlIiwiZGF0YSI6eyJ3aW5kb3ciOiI8VUlXaW5kb3c6IDB4MTA3NzExZjkwOyBmcmFtZSA9ICgwIDA7IDM5MyA4NTIpOyBnZXN0dXJlUmVjb2duaXplcnMgPSA8TlNBcnJheTogMHg2MDAwMDBjMzE1OTA+OyBsYXllciA9IDxVSVdpbmRvd0xheWVyOiAweDYwMDAwMGMzMDE4MD4+IiwidGl0bGUiOiJIb21lIiwic2NyZWVuIjoiUk5TU2NyZWVuIiwicGFyZW50Vmlld0NvbnRyb2xsZXIiOiJSTlNOYXZpZ2F0aW9uQ29udHJvbGxlciIsIndpbmRvd19pc0tleVdpbmRvdyI6InRydWUiLCJ3aW5kb3dfd2luZG93TGV2ZWwiOiIwLjAwMDAwMCIsImJlaW5nUHJlc2VudGVkIjoiZmFsc2UiLCJpc193aW5kb3dfcm9vdFZpZXdDb250cm9sbGVyIjoiZmFsc2UifSwidGltZXN0YW1wIjoxNzA5MTUyOTM1Ljc2OH0seyJ0eXBlIjoiaHR0cCIsImxldmVsIjoiaW5mbyIsImNhdGVnb3J5IjoiaHR0cCIsImRhdGEiOnsicmVhc29uIjoibm8gZXJyb3IiLCJodHRwLnF1ZXJ5IjoicGxhdGZvcm09aW9zJmhhc2g9OWFhNGE0YmI5NGRhNTdhNzM4MjcwZjg2MTdkYTQwZmYiLCJtZXRob2QiOiJHRVQiLCJyZXNwb25zZV9ib2R5X3NpemUiOjAsInN0YXR1c19jb2RlIjoyMDAsInJlcXVlc3RfYm9keV9zaXplIjowLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXNzZXRzL2Fzc2V0cy9pbWFnZXMvbW9yZUAzeC5wbmcifSwidGltZXN0YW1wIjoxNzA5MTUyOTM1Ljc3NX0seyJ0eXBlIjoiaHR0cCIsImxldmVsIjoiaW5mbyIsImNhdGVnb3J5IjoiaHR0cCIsImRhdGEiOnsicmVhc29uIjoibm8gZXJyb3IiLCJodHRwLnF1ZXJ5IjoicGxhdGZvcm09aW9zJmhhc2g9ZjUyNDY3ZDFlODhmMWQ5YmRmYWExOWY4MDNjOTVhYTgiLCJtZXRob2QiOiJHRVQiLCJyZXNwb25zZV9ib2R5X3NpemUiOjAsInN0YXR1c19jb2RlIjoyMDAsInJlcXVlc3RfYm9keV9zaXplIjowLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXNzZXRzL2Fzc2V0cy9pbWFnZXMvaWNvbnNlYXJjaEAzeC5wbmcifSwidGltZXN0YW1wIjoxNzA5MTUyOTM1Ljc3NX0seyJ0eXBlIjoiaHR0cCIsImxldmVsIjoiaW5mbyIsImNhdGVnb3J5IjoiaHR0cCIsImRhdGEiOnsicmVhc29uIjoibm8gZXJyb3IiLCJodHRwLnF1ZXJ5IjoicGxhdGZvcm09aW9zJmhhc2g9NjJiNjJkODZjNTAzOGEzOWJiMWIyOTk2Y2ViYWVkNDEiLCJtZXRob2QiOiJHRVQiLCJyZXNwb25zZV9ib2R5X3NpemUiOjAsInN0YXR1c19jb2RlIjoyMDAsInJlcXVlc3RfYm9keV9zaXplIjowLCJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjgwODEvYXNzZXRzL2Fzc2V0cy9pbWFnZXMvcGFya2luZ3NAM3gucG5nIn0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS43Nzh9LHsidHlwZSI6Imh0dHAiLCJsZXZlbCI6ImluZm8iLCJjYXRlZ29yeSI6Imh0dHAiLCJkYXRhIjp7InJlYXNvbiI6Im5vIGVycm9yIiwiaHR0cC5xdWVyeSI6InBsYXRmb3JtPWlvcyZoYXNoPTUzOWJjYmYyMzYzZmM4YjlmYTRlZjAwMmQ1MTM3MGUzIiwibWV0aG9kIjoiR0VUIiwicmVzcG9uc2VfYm9keV9zaXplIjowLCJzdGF0dXNfY29kZSI6MjAwLCJyZXF1ZXN0X2JvZHlfc2l6ZSI6MCwidXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2Fzc2V0cy9hc3NldHMvaW1hZ2VzL2NlbnRlcl9waW5AM3gucG5nIn0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS43Nzl9LHsidHlwZSI6Imh0dHAiLCJsZXZlbCI6ImluZm8iLCJjYXRlZ29yeSI6Imh0dHAiLCJkYXRhIjp7InJlYXNvbiI6Im5vIGVycm9yIiwiaHR0cC5xdWVyeSI6InBsYXRmb3JtPWlvcyZoYXNoPTU5MTc2MTAwYjhhMDY2YWNkOGRiMTM5N2UyNTE3N2I4IiwibWV0aG9kIjoiR0VUIiwicmVzcG9uc2VfYm9keV9zaXplIjowLCJzdGF0dXNfY29kZSI6MjAwLCJyZXF1ZXN0X2JvZHlfc2l6ZSI6MCwidXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2Fzc2V0cy9hc3NldHMvaW1hZ2VzL2NlbnRlckxvY2F0aW9uQDN4LnBuZyJ9LCJ0aW1lc3RhbXAiOjE3MDkxNTI5MzUuNzgzfSx7InR5cGUiOiJodHRwIiwibGV2ZWwiOiJpbmZvIiwiY2F0ZWdvcnkiOiJodHRwIiwiZGF0YSI6eyJyZXF1ZXN0X2JvZHlfc2l6ZSI6NCwicmVzcG9uc2VfYm9keV9zaXplIjowLCJtZXRob2QiOiJQT1NUIiwicmVhc29uIjoibm8gZXJyb3IiLCJ1cmwiOiJodHRwczovL21hcHNtb2JpbGVzZGtzLXBhLmdvb2dsZWFwaXMuY29tLyRycGMvZ29vZ2xlLmludGVybmFsLm1hcHMubWFwc21vYmlsZXNka3MudjEuTWFwc01vYmlsZVNES3NTZXJ2aWNlL0RlZHVjdFF1b3RhIiwic3RhdHVzX2NvZGUiOjIwMH0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS43OTR9LHsidHlwZSI6Imh0dHAiLCJsZXZlbCI6ImluZm8iLCJjYXRlZ29yeSI6Imh0dHAiLCJkYXRhIjp7InJlcXVlc3RfYm9keV9zaXplIjowLCJyZXNwb25zZV9ib2R5X3NpemUiOjAsIm1ldGhvZCI6IkdFVCIsInJlYXNvbiI6Im5vIGVycm9yIiwidXJsIjoiaHR0cHM6Ly9kbC5nb29nbGUuY29tL2dlb3Nkay9pb3MtbGF0ZXN0Iiwic3RhdHVzX2NvZGUiOjIwMH0sInRpbWVzdGFtcCI6MTcwOTE1MjkzNS43OTZ9LHsidHlwZSI6Imh0dHAiLCJsZXZlbCI6ImluZm8iLCJjYXRlZ29yeSI6Imh0dHAiLCJkYXRhIjp7InJlcXVlc3RfYm9keV9zaXplIjowLCJyZXNwb25zZV9ib2R5X3NpemUiOjAsIm1ldGhvZCI6IkdFVCIsInJlYXNvbiI6Im5vIGVycm9yIiwidXJsIjoiaHR0cDovL2xvY2FsaG9zdDo0NDMwOS92MS96b25lcy9hdmFpbGFibGUtem9uZXMiLCJzdGF0dXNfY29kZSI6MjAwfSwidGltZXN0YW1wIjoxNzA5MTUy

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0

From BugReporting
[AppRegistry.ru](http://appregistry.ru/) Running “APPNAME” with
nApplication1   {“rootTag”: 1, “initialProps”: {}}

**Comment by meedodk** [comment]
It seems like the error does not pop up anymore.
I removed everything related to Sentry, added it again, and configured it manually.

So my guess is some configuration must have messed it up.

**Comment by krystofwoldrich** [comment]
@meedodk Thanks for the message, I will close the issue for now.

But feel free to comment here if it appears again and we can investigate more.

**Comment by owjsub** [comment]
@krystofwoldrich I discovered my yarn.lock had two different versions of `@sentry/react-native`. Once I removed the older version, the crash on `captureEnvelope` was resolved.
