### ISSUE TITLE
Expo 50: Events are processed on device, but never sent to Sentry (worked on SDK 49)

### ISSUE THREAD

**Issue by csvan** [getsentry/sentry-react-native#3698]
**OS:**
- [ ]  Windows
- [ x ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ x ]  Android

**SDK:**
- [ x ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ x ]  Yes (SDK 50)
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ x ]  on-premise (24.3.0)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  beforeSend: (event) => {
    event.tags = {
      ...(event.tags || {}),
      app: 'my-app',
    };
    return event;
  },
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
    }),
  ],
  debug: true,
  dsn: 'https://xxxx@onprem.domain/sentry/6',
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

We have configured `@sentry/react-native` on an Expo SDK 50 app according to the provided instructions. However, while `debug` shows that events are (seemingly) being processed, nothing is sent upstream. We have manually added several instances of e.g. `Sentry.captureMessage('Hello world!')` and `Sentry.captureException(new Error('some error'))` in the code, and we even get warnings at times that Sentry dedupes events when these are being run repeatedly (again, showing that Sentry is seemingly working and picking them up).

Opening the Expo JS debugger and inspecting the Network tab, we can see that Sentry is (I guess correctly) calling the `symbolicate` endpoint on localhost when these checkpoints are invoked. However, there are _no_ network calls made to our Sentry instance, possibly ruling out a direct communication issue. The events are simply never sent.

To rule out that this is isolated to running locally with Metro, we also did a Preview build using EAS and installed this on a physical device on a public network. Again, as far as we can tell nothing is sent - no events are showing up in our Sentry instance. 

If the error is on our side, it would be very helpful to know how we can debug this, if at all.

**Finally, this DID work during a previous trial we did on SDK 49, before the new setup instructions for SDK 50**

**Steps to reproduce:**
- Install Sentry react-native SDK as per instructions
- Try to capture an event.

**Actual result:**

Sentry processes event in app, but never sends them to Sentry

**Expected result:**

The processed events should be correctly submitted to Sentry

**Comment by csvan** [comment]
As an addition - we also enabled automatic instrumentation with `tracesSampleRate: 1.0` to check if this is isolated to error reporting. It isn't. With `debug: true` the logs are full of activity about transactions being processed, but again, inspecting the JS Debugger we can see that no data is ever sent to Sentry.

**Comment by krystofwoldrich** [comment]
Hi @csvan,
thank you for the message and the details.

You should be able to see the request to Sentry in the network tab. Sadly, I'm unable to reproduce it.

Could you share the exact steps to reproduce the issue? Or share the sample app you created to test this?

**Comment by csvan** [comment]
Working in a corporate environment, so sadly cannot share anything as of now. The steps are unfortunately not more than following the setup instructions as per the documentation for now.

Just to be clear - should this work even when running locally with Metro?

**Comment by krystofwoldrich** [comment]
@csvan Thank you, I misunderstood, I thought you tried it in a new empty app.

Yes, it works in Expo Go, native builds with Metro, and release builds. 

Are you migrating from `sentry-expo` to `@sentry/react-native`? 

The `Sentry.captureException/Message` are the best to try sending an event to Sentry.

I would recommend using Logcat as that will give you more insides into the sending process.

iOS is working as expected? Or your app is only for Android?

**Comment by csvan** [comment]
We run both Android and iOS, neither is working.

Dug through logcat but sadly I cannot find much there either. However, intercepting events in `beforeSend` I can see that they all have `localhost:8081` as URL. Would that be indicative of a problem, e.g. that events are all sent to localhost and not to Sentry?

**Comment by csvan** [comment]
@krystofwoldrich we have made som progress - **it works in Expo Go, but not in Dev or Release builds**. 

We don't really do anything magical or special in either our dev or release builds, but do you see something that could potentially interfere there?

**Comment by krystofwoldrich** [comment]
>  I can see that they all have localhost:8081 as URL.

The `request` property contains related request information to the event, it doesn't relate to the request sending the event.

> it works in Expo Go

That confirms, as you mentioned that the issue is in the native layers.

> Could there be something in those builds that "fools" Sentry into thinking the device is offline or the like, so that events just get stored up but never sent?

When the `debug: true`, this is passed to the native layers and you should be able to see debug messages about processing and sending/storing/discarding the envelopes.

Do you see Sentry native logs in logcat or only the ones from `ReactNativeJS`?

**Comment by csvan** [comment]
@krystofwoldrich thanks for the reply, I indeed think I found something logcat (dev build on a physical device):

```
2024-03-25 11:12:34.868 24869-25043 Sentry                  com....volvo.pub.charging.devclient  D  Request failed, API returned 400
2024-03-25 11:12:34.871 24869-25043 Sentry                  com....volvo.pub.charging.devclient  D  Failed to buffer the request body: Invalid gzip header
2024-03-25 11:12:34.872 24869-25043 Sentry                  com....volvo.pub.charging.devclient  D  The transport failed to send the envelope with response code 400
2024-03-25 11:12:34.874 24869-25043 Sentry                  com....volvo.pub.charging.devclient  E  Envelope submission failed
                                                                                                    java.lang.IllegalStateException: The transport failed to send the envelope with response code 400
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:303)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:227)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-03-25 11:12:34.875 24869-25043 Sentry                  com....volvo.pub.charging.devclient  D  Marking envelope submission result: false
```

Looking at the logs on our Sentry backend, it's the same error:

```
1|index          | {"@timestamp":"2024-03-25T10:22:28.076Z","ecs.version":"8.10.0","log.level":"warn","message":"Got bad response from sentry 400 Failed to buffer the request body: Invalid gzip header [UNSERIALIZABLE]"}
```

This appears to be a constant for ALL outgoing envelopes.

**Comment by csvan** [comment]
@krystofwoldrich issue is resolved. The problem was that our reverse proxy _decoded_ the gzip packages sent by the React Native client but kept the `content-encoding: gzip` header. This led to Sentry throwing when trying to decode it since it was no longer gzipped.

A lot o thanks for your help and patience in trying to track this down!
