### ISSUE TITLE
Proguard UUIDs file not found

### ISSUE THREAD

**Issue by uriva** [getsentry/sentry-react-native#370]
_Platform:_
Android

node v9.4.0
npm 5.6.0

Sentry.config('🔑').install();

I have following issue:
After following installation instructions, upon exception, seeing this in android logcat: `io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.`

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
