### ISSUE TITLE
Apple privacy manifest requirements (File timestamp, System boot time & Disk space)

### ISSUE THREAD

**Issue by johnhatvani** [getsentry/sentry-react-native#3708]
Hello!

Starting may 1 apple require 3rd parties to describe their use of some API's. [doc link.](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

I have used some tooling to scan our app for usages of these api's and have found the following for this project:

```
Used symbols in binary ./Sentry/Sentry.framework/Sentry: mach_absolute_time, NSFileCreationDate, NSFileSystemFreeSize, NSFileSystemSize, stat

```

which maps to these entries which need declarations:
- NSPrivacyAccessedAPICategoryFileTimestamp
- NSPrivacyAccessedAPICategorySystemBootTime
- NSPrivacyAccessedAPICategoryDiskSpace

I can see that the [sentry-cocoa](https://github.com/getsentry/sentry-cocoa/issues/3775) library has already made this change, but I cannot see if `sentry-react-native` depends on this code? or if the reasons there would be the same

Im happy to bring that change across if it will help, But I can also see that the `sentry-cooca` library does not declare / use `NSPrivacyAccessedAPICategoryDiskSpace` we are using an older version of the library (5.5.0) so im not sure if later versions remove the need for those API's

If this is already on the radar could you please link to a discussion or I can bring across the manifest used in `sentry-cocoa` and discuss usage of `NSPrivacyAccessedAPICategoryDiskSpace`

Thanks.

**Comment by alex1092** [comment]
I'm having the same issue

**Comment by kahest** [comment]
@johnhatvani we added the privacy manifest stating the required API usages and reasons for this in version 8.11.0 of the sentry-cocoa SDK: https://github.com/getsentry/sentry-cocoa/pull/3259
The latest additions to the privacy manifest have been shipped with 8.21.0. We have no pending changes currently.

Depending on which version of @sentry/react-native you use, you might need to update the dependency to get the manifest file in via the sentry-cocoa SDK.

**Comment by krystofwoldrich** [comment]
@johnhatvani The cocoa changes are included in https://github.com/getsentry/sentry-react-native/releases/tag/5.19.3 and later releases.

**Comment by johnhatvani** [comment]
thank you

**Comment by sunny131984** [comment]
@johnhatvani  may i know which tools you have used to scan required manifest in existing code.

**Comment by Maker-Mark** [comment]
@sunny131984  These two tools are helpful
[GitHub - Wooder/ios_17_required_reason_api_scanner: A simple shell script to scan your Xcode Swift project for required reason API usage to ensure privacy compliance and to simplify the creation of privacy manifests.](https://github.com/Wooder/ios_17_required_reason_api_scanner) 

[GitHub - stelabouras/privacy-manifest: A simple tool that parses your Xcode project/workspace or Swift Package, detects required reason APIs and generates a Privacy Manifest if needed.](https://github.com/stelabouras/privacy-manifest)

**Comment by sleekLancelot** [comment]
Hi guys, i am bit confused on this issue, do i need to generate said manifest file, or has this been handled by sentry?

**Comment by kahest** [comment]
Hey @sleekLancelot, thanks for asking - as far as we can, we handle this, but depending on your setup you may need to perform specific steps. We added documentation for this, see here: https://docs.sentry.io/platforms/react-native/data-management/apple-privacy-manifest/

Please let us know if this doesn't answer your questions
