### ISSUE TITLE
`sentry-cli` SSLRead error during debug symbols upload

### ISSUE THREAD

**Issue by allen-hsu** [getsentry/sentry-react-native#3716]
**OS:**
- [ ]  Windows
- [ *]  MacOS
- [ ]  Linux

**Platform:**
- [*]  iOS
- [ ]  Android

**SDK:**
- [*]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.6.0

**`react-native` version:** 0.72.12

**Are you using Expo?**
- [ ]  Yes
- [ *]  No

**Are you using sentry.io or on-premise?**
- [*]  sentry.io (SaaS)
- [ ]  on-premise

[Description]

When I was building an app with Xcode 15, I encountered an unexpected unknown error: 'Command PhaseScriptExecution failed with a nonzero exit code'. After repeated attempts, I found that the error occurred in one of the scripts for 'Upload Debug Symbols to Sentry':

```
$SENTRY_CLI debug-files upload "$INCLUDE_SOURCES_FLAG" "$DWARF_DSYM_FOLDER_PATH"
```

Deleting this line allows everything to work fine, but I need to upload Symbols to Sentry. Please advise me on how to fix it. If you use a version of Xcode lower than 15, it also works very well.

**Comment by krystofwoldrich** [comment]
Hi @allen-hsu,
can you add `--log-level=debug --force-foreground` to the command, and share the log output with us?

```bash
$SENTRY_CLI debug-files upload --log-level=debug --force-foreground "$INCLUDE_SOURCES_FLAG" "$DWARF_DSYM_FOLDER_PATH"
```

**Comment by BruceWind** [comment]
I got the same error:
```
> Found 8 debug information files
> Prepared debug information files for upload
error: API request failed
  caused by: [56] Failure when receiving data from the peer (SSLRead() return error -36)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by krystofwoldrich** [comment]
@BruceWind Thank you for the message,
please check if your build phase is up to date -> https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-debug-symbols-upload

Then you can use `export SENTRY_CLI_RN_XCODE_EXTRA_ARGS="--force-foreground"` to add the flag.

Does it happen locally or in CI?

**Comment by BruceWind** [comment]
Hi, @krystofwoldrich krystofwoldrich thanks 4 ur reply. I've edited `.zshrc ` to add 2 lines:
```
export SENTRY_CLI_RN_XCODE_EXTRA_ARGS="--force-foreground"

export SENTRY_LOG_LEVEL="debug"
```


and, then I open xcode to **build(Archive)**, but I still got this error:
```
Using React Native Packager bundle and source map.
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Bundled 2 files for upload
> Bundle ID: f02ec074-bbc7-5a65-9219-0b0d6680259e
error: API request failed
  caused by: [56] Failure when receiving data from the peer (SSLRead() return error -9820)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

```
Maybe this is because of network problems?

**Comment by krystofwoldrich** [comment]
@BruceWind Thank you for the update, I'm happy the symbols uploaded successfully now.
