### ISSUE TITLE
Remove `browser/replay` from mobile bundles to lower bundle size

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3718]
### Description

Metro currently doesn't support tree shaking out of the box. And so all `@sentry/*` dependencies are included in the final bundle.

Some packages can be easily excluded using the metro resolver options:

### Current solution

```js
const config = {
  resolver: {
    resolveRequest: (context, moduleName, platform) => {
      if (moduleName.includes('@sentry/replay')) {
        return { type: 'empty' };
      }
      return context.resolveRequest(context, moduleName, platform);
    },
  },
};
```

### Proposed solution

Sentry Metro config will automatically remove web replay for mobile platforms and expose an option to remove it for web builds.

```js
const { withSentryConfig } = require('@sentry/react-native/metro');

const m = mergeConfig(getDefaultConfig(__dirname), config);
module.exports = withSentryConfig(m, { includeReplay: true });
```

**Comment by krystofwoldrich** [comment]
- Bundle analysis with overview and steps to reproduce is part of https://github.com/getsentry/sentry-react-native/issues/3826.

**Comment by vovkasm** [comment]
Just experimented with one of concurrent products... Only +40Kb to production JS bundle (mesuread with empty RN 0.73.8 app)... (
<img width="600" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/95272/5bcd48fd-289d-4b46-ac93-e69d30ec7d59">

I would also like to add that this is not just the size in the bundle, it is a measurable slowdown at the start of the application, which is a very important metric for business.

**Comment by kahest** [comment]
@vovkasm thanks for the additional data 👍

**Comment by lucas-zimerman** [comment]
I am closing this as completed, you can add a parameter on Sentry metro config to remove browser/replay

 ``` diff
withSentryConfig(m, {
   annotateReactComponents: true,
+ includeWebReplay: false
});
