### ISSUE TITLE
Sentry for android unable to show the code where the error occurs

### ISSUE THREAD

**Issue by sahil290791** [getsentry/sentry-react-native#372]
OS:
- [x ]  MacOS

_Platform:_
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
node: v8.9.3
npm: 5.5.1
```
---
I have following issue:
The sourcemaps get automatically uploaded during the build process for iOS and android as given in the sentry documentation.

When I do a release build for iOS from xcode, it uploads two files:
```js
// in case of iOS
main.jsbundle
main.jsbundle.map
```

In case of android also I have this line in **app/build.gradle**:
```gradle
apply from: "../../node_modules/react-native-sentry/sentry.gradle"
```
the above code takes care of uploading sourcemaps during build process.

It uploads two files:
```js
// in case of android
index.android.bundle
index.android.bundle.map
```
It also shows this in android:
```
Source code was not found for app:///index.android.bundle Collapse
{
  "url": "app:///index.android.bundle"
}
```
However I can see that the file is present in `sentry > releases`.

**Actual result:**

But when I receive any error in android, it shows up like this in sentry:
![screen shot 2018-03-07 at 11 11 59 am](https://user-images.githubusercontent.com/7287280/37075785-7685c0fc-21f9-11e8-87a4-9a6de4e72785.png)

Is it happening because of some mismatch in the bundle used by app and bundle uploaded with a different name by **react-native-sentry**.

I am able to trace the line and see the code in sentry for iOS:
![screen shot 2018-03-07 at 11 12 51 am](https://user-images.githubusercontent.com/7287280/37075656-dc95ba6a-21f8-11e8-8539-87e8125a8002.png)

**Expected result:**
To be able to see the code where the error occurs in sentry.

**Comment by sahil290791** [comment]
It was happening due to environment variables that I had exported day before related to sentry which was overriding the config.

**Comment by riyazMuhammad** [comment]
Hey @sahil290791, Can you please share what had gone wrong?
I have come across the same thing! Please!

**Comment by sahil290791** [comment]
@riyazMuhammad sentry.properties was picking up my previously defined env variables which was causing a mismatch and hence the error was happening. I had just opened a new terminal tab and then again started the app generation process and everything worked fine after that.

**Comment by riyazMuhammad** [comment]
Thank you @sahil290791.

**Comment by sahil290791** [comment]
I am seeing the above error again. I have checked all the linking steps they are correct.
This is happening for both android and iOS.

<img width="758" alt="screenshot 2018-12-24 at 11 03 00 am" src="https://user-images.githubusercontent.com/7287280/50391865-5b894d80-076f-11e9-9830-aaf9ccc82c4e.png">
<img width="1202" alt="screenshot 2018-12-24 at 11 02 17 am" src="https://user-images.githubusercontent.com/7287280/50391872-62b05b80-076f-11e9-9aa4-08307f7fc2cb.png">

<img width="872" alt="screenshot 2018-12-24 at 11 31 47 am" src="https://user-images.githubusercontent.com/7287280/50391964-0ac62480-0770-11e9-81db-af77d247a698.png">

<img width="862" alt="screenshot 2018-12-24 at 11 01 55 am" src="https://user-images.githubusercontent.com/7287280/50391927-c9ce1000-076f-11e9-943c-48e884bb106f.png">

I have seen all the existing issues related to index.android.bundle but they didn't help. I am using:
- react-native 0.55.4
- react-native-sentry: 0.35.1

I have private sentry server so will not be able to share the URL.

Is there any other way to infer release version and dist from sourcemap to find the actual issue?

**Comment by sahil290791** [comment]
@HazAT can u show me a sample release name for ios/android project, in my case its like: **com.example.com-<version_number>** and **dist** is lets say 91.

And in Releases page I can see release as just <version_no> there is no package name mentioned:
<img width="796" alt="screenshot 2018-12-30 at 8 22 46 am" src="https://user-images.githubusercontent.com/7287280/50543937-4b102180-0c0c-11e9-869f-c1b0fc72890c.png">

If I open the releases page for a specific release:
<img width="703" alt="screenshot 2018-12-30 at 8 23 01 am" src="https://user-images.githubusercontent.com/7287280/50543940-59f6d400-0c0c-11e9-814d-43174e8df216.png">

But when the error gets reported I see the **release** as **com.example.com-<version_number>**.

Is this the reason I keep seeing the error that `Source code was not found`? It used to work few months back but that too randomly. Now it doesn't decode the errors at all. 

What should I do to make it work. Is there any way for me to backtrack the release name and dist that gets set in the sourcemap file to see if there is any issue?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
