### ISSUE TITLE
Enabled in Sentry.init Doesn't Seem to Work on Android Physical Device

### ISSUE THREAD

**Issue by tao-qian** [getsentry/sentry-react-native#3722]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- []  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.15.1

**`react-native` version:** 0.71.14

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]
](https://brightgo-inc.sentry.io/issues/5107340794/?alert_rule_id=14019821&alert_timestamp=1711571583894&alert_type=email&environment=development&notification_uuid=97528b44-6f37-47ad-adc3-111afe821e9e&project=4504906435330048&referrer=alert_email)
**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: XXX,
  environment: __DEV__ ? 'development' : 'production',
  tracesSampleRate: 1.0,
  beforeBreadcrumb(breadcrumb, hint) {
    return null;
  },
  enabled: !__DEV__,
});
```
---
**I have the following issue:**

When we run the app on Android physical device, traces would still be sent to server even with `enabled` set as false in `Sentry.init`. This doesn't happen on emulator.

**Steps to reproduce:**
- run `npx react-native run-android` to install a development build on Android physical device
- trigger some exception

**Actual result:**

Nothing should be reported to Sentry because enabled is false.

**Expected result:**

Issues are still reported.

**Comment by krystofwoldrich** [comment]
Hi @tao-qian,
thank you for the message, can you try this with https://github.com/getsentry/sentry-react-native/releases/tag/5.19.2 or newer, we recently fixed [a bug](https://github.com/getsentry/sentry-react-native/pull/3606) related to not sending events when enabled false.

**Comment by tao-qian** [comment]
Thank you! We will try it out and let you know!

**Comment by carbonatedcoder** [comment]
We were seeing the same behavior where the `enabled` setting was being ignored and events were still getting sent when set to `false`. After upgrading to `5.19.2`, it seems to be fixed. However, it seems that the current version of the `expo` package within SDK 50 is still pinned to `5.19.1`, so hopefully they'll adjust that soon.

**Comment by krystofwoldrich** [comment]
@carbonatedcoder The https://github.com/expo/sentry-expo is deprecated, and we recommend using `@sentry/react-native` directly.

You can check migration guide here, https://docs.sentry.io/platforms/react-native/migration/sentry-expo/

**Comment by carbonatedcoder** [comment]
> @carbonatedcoder The https://github.com/expo/sentry-expo is deprecated, and we recommend using `@sentry/react-native` directly.

@krystofwoldrich, thanks, we actually are using @sentry/react-native. I meant that when using "expo install" under SDK 50, they are currently pinning the recommended version of @sentry/react-native to 5.19.1.

**Comment by krystofwoldrich** [comment]
@carbonatedcoder Thank you for the clarification, yes, that will be bumped soon.

**Comment by krystofwoldrich** [comment]
@tao-qian I'll close the issue since there is another person confirming the newer version of the SDK works.

But please, feel free to comment here if it did not work for you, we can reopen the issue.
