### ISSUE TITLE
@sentry/react dependency is pinned to an old version

### ISSUE THREAD

**Issue by abejfehr** [getsentry/sentry-react-native#3725]
### Description

In a monorepo with both web and mobile projects, where both `@sentry/react-native` and `@sentry/react` are dependencies in package.json, it's tough to get them to align on version.

Right now in our yarn.lock there are 2 copies of `@sentry/react` installed, one from the package.json and one which is a dependency of this package.

Is it possible to use the carat instead to allow a range of versions? That way we don't get duplicates

**Comment by krystofwoldrich** [comment]
Hi @abejfehr,
thank you for the message, we pin the `@sentry/*` packages to ensure the `@sentry/react-native` package is as stable and reliable as possible.

The SDKs share internal APIs that are not required to follow Semver versioning and therefore might change from version to version.

We recommend sticking with the `@sentry/*` packages shipped with the RN SDK, but I understand that might not always be possible for your web application.

Please, let us know what you think, and feel free to share specific errors you are encountering.

**Comment by krystofwoldrich** [comment]
I'm closing this as we recently updated the RN SDK to include very recent version of the JS SDK.

https://github.com/getsentry/sentry-react-native/releases/tag/5.22.0
