### ISSUE TITLE
Configuration of enableCaptureFailedRequests doesn't work for Android

### ISSUE THREAD

**Issue by steffenmayerdmde** [getsentry/sentry-react-native#3749]
**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 7.3.0

**`react-native` version:** 0.72.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://dmtech.sentry.io/issues/5016208369

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    beforeSend: shouldSendEvent,
    beforeBreadcrumb(breadcrumb, hint) {
      return null; // this disables all JS breadcrumbs
    },
    dsn: latestConfiguration.dsn,
    enableNative: true,
    enableNativeCrashHandling: true,
    enableAppHangTracking: false,
    enabled: latestConfiguration.enabled,
    environment: latestConfiguration.environment,
    enableWatchdogTerminationTracking: false,
    tracesSampleRate: 0.0,
    enableCaptureFailedRequests: false,
  });
```

---
**I have the following issue:**

Unfortunately, the `enableCaptureFailedRequests: false` setting does not appear to function as expected. Despite setting this flag to false, we continue to receive SentryHttpClientException errors since the behavior was changed to enable this feature by default. 

We are utilizing the Sentry React Native SDK, and this flag is the only configuation mentioned in your React Native implementation documentation. Since this breaking change we do see a high increase of events resulting in increased costs.

**Steps to reproduce:**
- Execute a failing HTTP request.

**Actual result:**

- The SentryHttpClientException is logged even though enableCaptureFailedRequests is set to false.

**Expected result:**

- No SentryHttpClientException should be logged because enableCaptureFailedRequests is set to false.

**Comment by kahest** [comment]
@steffenmayerdmde thanks for writing in and apologies for the troubles - we'll take a look and follow up here. Can you please confirm - on iOS this works as expected, on Android the flag doesn't turn off HTTP Client errors being reported?

**Comment by krystofwoldrich** [comment]
@steffenmayerdmde The error is send from `sentry-android`, do you use [`Sentry Android Gradle Plugin`](https://docs.sentry.io/platforms/android/configuration/gradle/)?

Can you share your configuration from `app/build.gradle`?

**Comment by krystofwoldrich** [comment]
To disable the OkHttp instrumentation, please add the following to your Sentry Android Gradle Plugin config, if you are using it.

```
tracingInstrumentation {
  enabled = false
}
```

**Comment by steffenmayerdmde** [comment]
Thanks for the quick reply. We are indeed using the Senty Android Gradle Plugin and will try again with

```
tracingInstrumentation {
    enabled.set(false)
}
```

I will let you know if it worked

**Comment by bpeltonc** [comment]
@krystofwoldrich If I disable tracingInstrumentation in my build.gradle file, but keep `enableCaptureFailedRequests` as `true` in my `Sentry.init` call, will I still get HTTP error reports? I have a custom filter to remove some events in a `beforeSend` there, but I'm noticing that isn't being respected after upgrading react-native SDK to a version using Android SDK 7.0+
