### ISSUE TITLE
`sentry-cocoa` Unknown receiver 'SwiftDescriptor' 

### ISSUE THREAD

**Issue by TrustDec** [getsentry/sentry-react-native#3765]
**OS:**
- [x]  MacOS

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**I have the following issue:**
iOS cannot be built. After upgrading @sentry/react-native 5.20 to 5.22, it cannot be built and can't be downgraded.
<img width="393" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/20201085/e5ae8120-250c-4831-8903-785338816290">

And when executing `npx @sentry/wizard -s -i reactNative`, an error is displayed:
TypeError: Cannot read properties of null (reading 'token')
![image](https://github.com/getsentry/sentry-react-native/assets/20201085/8592a7dc-482d-41ad-a04d-4f5265ff3d4e)

**Comment by krystofwoldrich** [comment]
This error is coming from `sentry-cocoa`.

- https://github.com/getsentry/sentry-cocoa/issues/3850

We will keep this issue open until resolved in RN. But expect most of the updates in the linked issue.

**Comment by pestrige** [comment]
The same issue after upgrading to @sentry/react-native@5.22.0. The solution for me is downgrade to v5.20.0:
```
yarn add @sentry/react-native@5.20.0
pod update Sentry
```

**Comment by TrustDec** [comment]
> Hi @TrustDec, thank you for the message, are you using statically or dynamically linked frameworks?
> 
> Have you clean the build and reinstalled pods after upgrading to 5.22.0?

Yes, after the upgrade, the project was cleaned up and rebuilt like this.

**Comment by TrustDec** [comment]
> The same issue after upgrading to @sentry/react-native@5.22.0. The solution for me is downgrade to v5.20.0:
> 
> ```
> yarn add @sentry/react-native@5.20.0
> cd ios && pod update Sentry
> ```
I tried to solve this problem in this way.The only way I can solve it now is to uninstall Sentry and delete the Sentry-related code.
![image](https://github.com/getsentry/sentry-react-native/assets/20201085/d3262ede-9682-4567-9ca5-cf99151d114b)

**Comment by krystofwoldrich** [comment]
@TrustDec @pestrige Would you be able to share a minimal reproducible example with us, that would help us debugging the issue.

**Comment by TrustDec** [comment]
> Hi @TrustDec and @pestrige, this issue might be relater to `APPLICATION_EXTENSION_API_ONLY=NO`, Sentry requires this option to be set to YES, this is how the Sentry Pod is setup by default. But it's possible that this configuration was overwritten in your case.
> 
> Can you verify `APPLICATION_EXTENSION_API_ONLY=YES` for the Sentry Pod in your application, or share your Pod file with us?

OK, changing APPLICATION_EXTENSION_API_ONLY to YES will cause other mistakes. I'm just curious why  suddenly need to set APPLICATION_EXTENSION_API_ONLY to YES? There was no any problem before.

**Comment by krystofwoldrich** [comment]
@TrustDec Thanks for the response, to avoid the issue, you can change this only for Sentry, or vice versa only for other Libraries.

Yes, `APPLICATION_EXTENSION_API_ONLY` has to be `YES` in order for Sentry to build.

This example will not change the default value of `APPLICATION_EXTENSION_API_ONLY` for Sentry. 

```ruby
post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      # Check if the pod is not Sentry
      unless target.name == 'Sentry'
        # Iterate through each build configuration
        target.build_configurations.each do |config|
          # Modify the build settings
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
        end
      end
      target.build_configurations.each do |config|
         # disable code signing for pods
         config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
         config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
         config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
```

**Comment by TrustDec** [comment]
Thank you for your reply. Add the following code and work for me.
```
 if target.name == 'Sentry'
  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
else
  config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
end
```

**Comment by krystofwoldrich** [comment]
@TrustDec Thanks for the replay, I'm happy to hear that this worked for you.
