### ISSUE TITLE
Android release created with no artifacts after local expo build

### ISSUE THREAD

**Issue by joeporpeglia** [getsentry/sentry-react-native#3776]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

When I build my app and to run in local dev mode it creates a release in our sentry dashboard. The release matches the version defined in my expo app config, but it uses 1 for the build number. This issue was observed after upgrading from `5.19.1` to `5.20.0`.

**Steps to reproduce:**
- `expo run:android` (i started the dev server in a separate terminal and ran on my physical device)

**Actual result:**

The app builds and runs on device as usual, but a release is created in sentry.

**Expected result:**

No release is created for local builds. I also tried `SENTRY_DISABLE_AUTO_UPLOAD=true expo run:android`, but it still creates the release.

**Comment by krystofwoldrich** [comment]
Hi @joeporpeglia,
thank you for the message,

releases are created dynamically based on the events sent to Sentry.

If you have Sentry enabled in your local builds release is automatically created. 

To avoid this you can disable Sentry for local builds:

```js
Sentry.init({
  enabled: !__DEV__,
})
``` 

Or you can create a manual release for all of your debug releases:
```js
Sentry.init({
  release: __DEV__ ? 'debug@1.0.0' : undefined,
  dist: __DEV__ ? '1' : undefined,
})
```

**Comment by joeporpeglia** [comment]
Okay got it - that setup works as expected. Thanks @krystofwoldrich!

Some additional context I missed in the original issue: With `5.19.1` we used the `beforeSend` hook to log errors in development instead of sending to sentry, so it seems like that behavior might have changed wrt release creation in `5.20.0`
