### ISSUE TITLE
Sourcemaps are not correctly uploaded and crashes in issues don't reference JS source code

### ISSUE THREAD

**Issue by anagovitsyn** [getsentry/sentry-react-native#3779]
**OS:**

- [*]  MacOS

**Platform:**
- [*]  iOS

**SDK:**
- [*]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.15.0

**`react-native` version:** 0.71.12

**Are you using Expo?**
- [*]  No

**Are you using sentry.io or on-premise?**

- [*]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: "https://fa8......e5@sentry.obs.mts.ru/694",
    tracesSampleRate: 1.0,
  });
```

---
**I have the following issue:**

1. Upon manual upload of source maps script main.jsbundle uploaded with zero size
2. Crash information for the release doesn't contain references to the JS source code

**Steps to reproduce:**
- Step 1
 generate bundle and sourcemap according to documentation https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/hermes/

- Step 2
upload sourcemaps to sentry (screenshot of uploading command/process attached)

**Actual result:**

- main.jsbundle is shown with zero bytes size in sourcemaps for the release
- crash references in issues for the release are not pointing to the line numbers in JS source code

**Expected result:**
- main.jsbundle is uploaded with it's original content and size
- crash references in issues for the release are pointing to the JS source code

![Screenshot1](https://github.com/getsentry/sentry-react-native/assets/55987916/93d2453d-245a-4fb7-a44a-ddd9261f8f27)
<img width="829" alt="Screenshot2" src="https://github.com/getsentry/sentry-react-native/assets/55987916/1613bfd5-b07d-42b4-a198-99d003b8c188">
![Screenshot3](https://github.com/getsentry/sentry-react-native/assets/55987916/a4e2b9d9-fee1-4e50-84c5-31ba9efc82ca)
![Screenshot4](https://github.com/getsentry/sentry-react-native/assets/55987916/1dc8ec24-0a99-4273-af09-d64663d02c3e)

**Comment by anagovitsyn** [comment]
For android upload source maps was successful, but still no references to source code
![Screenshot5](https://github.com/getsentry/sentry-react-native/assets/55987916/82874dca-90cb-4eb2-a080-1610e4efa84c)
![Screenshot6](https://github.com/getsentry/sentry-react-native/assets/55987916/e926d5b3-05c4-4f7c-945f-7450c213a62c)

**Comment by krystofwoldrich** [comment]
Hi @anagovitsyn,
thank you for the message,

have you setup Sentry in your ` metro.config.js`? The uploaded source maps are missing Debug IDs to be linked to the correct source code.

I would also recommend updating to the latest SDK version, https://github.com/getsentry/sentry-react-native/releases/tag/5.22.0.

**Comment by anagovitsyn** [comment]
> Hi @anagovitsyn, thank you for the message,
> 
> have you setup Sentry in your ` metro.config.js`? The uploaded source maps are missing Debug IDs to be linked to the correct source code.
> 
> I would also recommend updating to the latest SDK version, https://github.com/getsentry/sentry-react-native/releases/tag/5.22.0.

Where can I get debug ids? for matching souce maps? 
![image](https://github.com/getsentry/sentry-react-native/assets/55987916/f5dffcb3-c6a8-407d-972c-dbc9d01487c9)

**Comment by krystofwoldrich** [comment]
Although the source maps are linked, the might not be the correct source maps for the build. 

Debug IDs help with that making sure only the appropriate source maps are used.

The guide that you linked ensures Debug IDs are generated.

https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/hermes/

Could you share how does your `metro.config.js` looks like?

**Comment by anagovitsyn** [comment]
We have already customized metro.config.js, just added there code for sentry and got error, so it doesn't work showing this error


<img width="1303" alt="Screenshot 2024-05-03 at 13 28 46" src="https://github.com/getsentry/sentry-react-native/assets/55987916/e21dfbc3-fe04-4942-bb0f-91cdf7b881d7">
![Screenshot 2024-05-03 at 14 24 29](https://github.com/getsentry/sentry-react-native/assets/55987916/011272f7-05b1-4538-87fa-392db7d4ffb0)

**Comment by krystofwoldrich** [comment]
Hi @anagovitsyn,
thank you for the details.

From the `package.json` I see you are using `react-native@0.71.12` with `metro@0.72.0`.

But RN ships with `metro@0.73.10`, can you upgrade to that version?

**Comment by anagovitsyn** [comment]
Thank you. I have upgraded metro to 0.73.10 and previous error 'size' of undefined had gone and now build is successful on both platforms. But now new error both on ios and android upon startup of the app, though nothing was changed in source code structure, and index.js where call to registerComponent is - is unchanged in comparison with code without sentry and all the updates to the packages.json.

![Screenshot_1714740622](https://github.com/getsentry/sentry-react-native/assets/55987916/def30307-33b5-4f95-846e-fee6374bf4bc)

Here's updated package.json
[package.json](https://github.com/getsentry/sentry-react-native/files/15200195/package.json)

**Comment by krystofwoldrich** [comment]
@hubertdeng123 Can you try to isolate the issue, does it happen without `createSentryMetroSerializer`? Or without Sentry only with `metro@0.73.10` upgrade?

**Comment by anagovitsyn** [comment]
> @hubertdeng123 Can you try to isolate the issue, does it happen without `createSentryMetroSerializer`? Or without Sentry only with `metro@0.73.10` upgrade?

All problems with build errors finaly closed. There was problem using react-navigation package alone i.e. import { Header } from 'react-navigation' which is not supported after upgrading to use centry. This error was preceeding message of "GoGym" is not registed module, and was the couse of "registerComponent wasn't called"

**Comment by anagovitsyn** [comment]
And now I have upon iOS successful build this error message
![image](https://github.com/getsentry/sentry-react-native/assets/55987916/23572268-d9d7-43ff-a56a-653031053091)

so it still doen't solved. What are next steps to solve the issue?

**Comment by krystofwoldrich** [comment]
@anagovitsyn If you can, upgrade to the latest Sentry on your server, that will solve the issue.

Or add `export AUTO_RELEASE=true # Automatically detect release from Xcode project` which will add the required slug.
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload

**Comment by anagovitsyn** [comment]
Now everything is solved, after I have upgraded sentry client version to 5.19.1. It works ok with backend 23.5.2 and now I can see mapping of errors to source code.

Thank you
