### ISSUE TITLE
Webrtc audio stops working

### ISSUE THREAD

**Issue by ruslanjabari** [getsentry/sentry-react-native#3780]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://github.com/VapiAI/react-native/issues/4#issue-2267257039
Example: https://github.com/ruslanjabari/rn-sentry-webrtc-bug/tree/9b9e69e88d71abeb0d31ecf3cb1787a797409e6d

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

Webrtc audio stops working

**Comment by krystofwoldrich** [comment]
@ruslanjabari Thank you for the message and the reproducible example.

We will try it and keep you updated here.

**Comment by kahest** [comment]
Hey @ruslanjabari no updates as of now, we'll follow up on this issue once we managed to repro it or if we have questions.

**Comment by krystofwoldrich** [comment]
We are closing this issue, as to reproduce it we would have to register to a third party service of `@vapi-ai/react-native`.

If this is still an issue, please provide minimal reproducible example which doesn't require third party services to produce the issue.
