### ISSUE TITLE
Auto Time to Initial Display for React Navigation is always 15 seconds

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3786]
### Description

On some Android devices the auto instrumentation for time to initial display results in heartbeat timeout and the TTID span is always 15 seconds.

To avoid this bug you can you the manual instrumentation `<Sentry.TimeToInitialDisplay record={true} />`

https://docs.sentry.io/platforms/react-native/performance/instrumentation/time-to-display/

**Comment by krystofwoldrich** [comment]
- Example of this behaviour from a user report https://github.com/getsentry/sentry-react-native/issues/3847

**Comment by matheuscouto** [comment]
Moving the discussion to this thread, as you asked in the issue my navigators are structured like this:
          
```
Stack Navigator (root)
   └─ Tab Navigator
      └─ Stack Navigator
```

Tbh I didn't know we also could define the `TimeToInitialDisplay` the same way you can with the `TimeToFullDisplay`, I was relying only on auto instrumentation for that. I'll add it and see if it solves the issue.

**Comment by krystofwoldrich** [comment]
@matheuscouto Thank you for the details.

**Comment by kahest** [comment]
Just dropping a note here that we have at least one more instance of this reported on another channel

**Comment by sregg** [comment]
It seems that manually using `<Sentry.TimeToInitialDisplay record={true} />` is helping.
But for screens without that, we're seeing those 15s TTID and TTFD even with `enableTimeToInitialDisplay: false`.
Is there a way to ignore/filter-out those 15s TTID and TTFD spans?

**Comment by krystofwoldrich** [comment]
Hi @sregg,
thank you for confirming that the manual instrumentation works.


> But for screens without that, we're seeing those 15s TTID and TTFD even with enableTimeToInitialDisplay: false.

Are those possibly from old releases? Or do you see it when testing locally?

**Comment by krystofwoldrich** [comment]
Thank you for the explanation @sregg

**Comment by sregg** [comment]
> Thank you for the explanation @sregg 

I'm happy to jump on a quick call to show you how this Time to Display is working in our app. There seems to be a few bugs at the moment.

**Comment by krystofwoldrich** [comment]
Thank you,

we are currently working on a fix -> https://github.com/getsentry/sentry-react-native/pull/4042,

let's wait for it.
