### ISSUE TITLE
sentry-expo-upload-sourcemaps requires sentry url set in expo config

### ISSUE THREAD

**Issue by domenipavec** [getsentry/sentry-react-native#3792]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

When running `sentry-expo-upload-sourcemaps` it reads config from expo plugin config. The sentry url config should not be required and default to sentry.io, but in recent update that doesn't work anymore.

I see this error and the process exits.
`Could not resolve sentry url, set it in the environment variable SENTRY_URL or in the '@sentry/react-native' plugin properties in your expo config.`

The issue was introduced here:
https://github.com/getsentry/sentry-react-native/commit/c651c797b4cbc58d9b1c1a5001e414a59d1e3a4b

**Comment by krystofwoldrich** [comment]
Hi @domenipavec,
thank you for the report, I agree, the SENTRY_URL should be optional.

**Comment by hannojg** [comment]
Meanwhile, what is the default sentry URL?

**Comment by ert78gb** [comment]
`https://sentry.io` works for me

**Comment by krystofwoldrich** [comment]
As @ert78gb mentioned -> `https://sentry.io/`

**Comment by isaachinman** [comment]
Just got hit with this after upgrading to Expo v51. Surely this is a very easy fix? Why has it sat around for almost two months?
