### ISSUE TITLE
Support Metro plugins with createSentryMetroSerializer

### ISSUE THREAD

**Issue by Waltari10** [getsentry/sentry-react-native#3797]
Feature Request for React Native Metro bundler with createSentryMetroSerializer.

Previously our projects metro.config.js was defined like this:
```
const config = {
  serializer: {
    customSerializer: MetroSerializer([
      CyclicDependencies({
        includeNodeModules: false,
        linesOfContext: 1,
        throwOnError: true,
      }),
    ]),
  },
```

We would like to start using `createSentryMetroSerializer`, but it seems there is no way to use it with the CyclicDependency plugin.

Is this the case or am I just unable to figure out how to do it?

**Comment by krystofwoldrich** [comment]
@Waltari10 Thank you for the message, we are already tracking this as a feature in https://github.com/getsentry/sentry-react-native/issues/3748

I'll close this as duplicate of https://github.com/getsentry/sentry-react-native/issues/3748
