### ISSUE TITLE
Get the "Failed to resolve plugin for module '@sentry/react-native/expo'" error when creating a new build

### ISSUE THREAD

**Issue by nandercarmo-plank** [getsentry/sentry-react-native#3799]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.10.0

**`react-native` version:** 0.72.10

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn: process.env.EXPO_PUBLIC_SENTRY_DSN,
    tracesSampleRate: 1.0,
    integrations: [new Sentry.ReactNativeTracing({ routingInstrumentation })],
});
```
---
**I have the following issue:**

Everytime I try to run `expo run:ios` I get the following error:

CommandError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to "(_my_project_path_)"

**Steps to reproduce:**

I have this plugin configured in my app.json file:

```json
[
    "@sentry/react-native/expo",
    {
      "url": "https://sentry.io/",
      "note": "Use SENTRY_AUTH_TOKEN env to authenticate with Sentry.",
      "project": "MY_ORG_NAME",
      "organization": "MY_ORG_NAME"
    }
  ],
  ```
  
  And this version in the package.json:
  
  ```json
  "dependencies": {
    "@sentry/react-native": "5.10.0",
  }
  ```

**Actual result:**

the build should work

**Expected result:**

CommandError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to "_my_project_path_"

**Comment by krystofwoldrich** [comment]
Hi @nandercarmo-plank,
thank you for the message, 
`@sentry/react-native/expo` was introduced in https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0

Please upgrade your SDK to https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0 or newer.

The latest steps to setup the SDK with Expo are at https://docs.sentry.io/platforms/react-native/manual-setup/expo/

In case the answer have not solved the issue, feel free to post a comment here and we can reopen it.

**Comment by oussamakh96** [comment]
I got always this probleme , EXPO SDK 52 ,
"@sentry/react-native": "^6.2.0",

**Comment by charlestbell** [comment]
> I got always this probleme , EXPO SDK 52 , "@sentry/react-native": "^6.2.0",

Same 

Expo SDK 52

"@sentry/react-native": "^6.2.0",

**Comment by jmacbhc** [comment]
Same issue with 

`
"expo": "^52.0.7",
"@sentry/react-native": "~6.1.0",
`

**Comment by TAQ2** [comment]
me 2

**Comment by abhichaurasiya2022** [comment]
me too, pls suggest solution

**Comment by sylainx** [comment]
I have this problem

Expo@52
"@sentry/react-native": "~6.1.0",

**Comment by SPR-IE** [comment]
I changed @sentry/react-native/expo for @sentry/react-native in the app.json and it worked. Not really sure what are the implications or why is the documentation not right. 
I'm getting logs alright so.
Hope it helps...

    "plugins": [
      [
        "@sentry/react-native",
        {
          "organization": "your org",
          "project": "your project",
          "url": "https://sentry.io/"
        }
      ],

**Comment by DavidDolyak** [comment]
Same here

**Comment by SleeplessByte** [comment]
The change proposed by @SPR-IE also works for me.

This seems to be a change in how *expo* is loading it, not how *sentry-react-native* works, as I have had the _same_ version for `@sentry/react-native` for the past 6 months (`"5.22.3"`) and `npx expo-doctor` stopped working. `eas-cli` worked until I just upgraded to the latest using `npm install -g eas-cli`. Now eas commands started failing with the error above.

**Comment by sergioisidoro** [comment]
Leaving this here for my fellow absent minded people - I had forgotten a `"sentry-expo"` in my dependencies. It is no longer needed since a few versions of `@sentry/react-native`, and seemed to have been the issue for me. It worked fine until I upgraded to SDK 52
