### ISSUE TITLE
Cannot find protocol declaration for 'SentryMXManagerDelegate'

### ISSUE THREAD

**Issue by emre-atilla** [getsentry/sentry-react-native#3800]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.1

**`react-native` version:** 0.72.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "https://xxx@yyy.ingest.us.sentry.io/zzz",
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
  // We recommend adjusting this value in production.
  tracesSampleRate: 1.0,
  _experiments: {
    // profilesSampleRate is relative to tracesSampleRate.
    // Here, we'll capture profiles for 100% of transactions.
    profilesSampleRate: 1.0,
  },
});
```

---
**I have the following issue:**
![image](https://github.com/getsentry/sentry-react-native/assets/139748840/311ca474-89c5-4b3c-92af-3f97c10443bb)

![image](https://github.com/getsentry/sentry-react-native/assets/139748840/2e5e8597-1754-4485-ab7f-8f7c95d47319)

I have this issue on iOS it says Cannot find protocol declaration for 'SentryMXManagerDelegate'

[Description]

**Steps to reproduce:**
- npx @sentry/wizard@latest -s -I reactNative

**Comment by krystofwoldrich** [comment]
Hi @emre-atilla,
thank you for the message,
we will take a look at this.

If you are able to create a minimal reproducible example, could you share it with us, it would help us debugging the issue.

**Comment by krystofwoldrich** [comment]
@brustolin @philipphofmann This seems specific to `sentry-cocoa`, any ideas?

**Comment by emre-atilla** [comment]
Hi @krystofwoldrich thank you for responding,

I created a repo for reproduce error again.

What I did :
- i just simply install with npx @sentry/wizard@latest -s -I reactNative
- I add my own den number to the project

and its working on android what I expect but on iOS it says cannot find protocol declaration for 'SentryMXManagerDelegate'

here is repo : https://github.com/emre-atilla/ProjectCloneForSentry

**Comment by krystofwoldrich** [comment]
Thank you for the repro. I've reproduced the build issue, we'll investigate it and keep you updated.

**Comment by krystofwoldrich** [comment]
The Sentry pod requires `APPLICATION_EXTENSION_API_ONLY` to be set to `YES`, but your `podfile` sets it to `NO` for all pods.

You can change your code like this to fix the build.

```ruby
      # Check if the pod is not Sentry
      unless target.name == 'Sentry'
        # Iterate through each build configuration
        target.build_configurations.each do |config|
          # Modify the build settings
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
        end
      end
```

Could you share with us why are you using the `APPLICATION_EXTENSION_API_ONLY` flag?

Let us know if this help you solve the issue, in case it did not or you have some other question feel free to post it here and we can reopen this.

**Comment by emre-atilla** [comment]
Thank you so much for your help it solves the issue. I don't really remember why I used the `APPLICATION_EXTENSION_API_ONLY` flag it's a bit old project

**Comment by julian-gargicevich** [comment]
I'm getting this same error after upgrading to 5.22 from 5.19, I'm using expo and the expo plugin

**Comment by FashMuyhee** [comment]
> ```ruby
> unless target.name == 'Sentry'
>         # Iterate through each build configuration
>         target.build_configurations.each do |config|
>           # Modify the build settings
>           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
>         end
>       end
> ```

i am experiencing similar issue i used APPLICATION_EXTENSION_API_ONLY flag to NO bcos i to resolve an error
<img width="905" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/34525848/3780b57e-41f7-4d2d-82d1-b63c6d7e5973">

using the above snippet solves sentry issue but will end-up throwing the above screenshooted error

**Comment by tkyr-hh** [comment]
@FashMuyhee  I think the best solution that worked for me is this: 

```
        # Iterate through each build configuration
        target.build_configurations.each do |config|
          # Modify the build settings
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = target.name == 'Sentry' ? 'YES' : 'No'
      end
```

**Comment by marianJ97** [comment]
> > ```ruby
> > unless target.name == 'Sentry'
> >         # Iterate through each build configuration
> >         target.build_configurations.each do |config|
> >           # Modify the build settings
> >           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
> >         end
> >       end
> > ```
> 
> @krystofwoldrich i am experiencing similar issue. i used APPLICATION_EXTENSION_API_ONLY flag to NO bcos i to resolve an error <img alt="image" width="905" src="https://private-user-images.githubusercontent.com/34525848/333922952-3780b57e-41f7-4d2d-82d1-b63c6d7e5973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODc2NTEsIm5iZiI6MTcxODI4NzM1MSwicGF0aCI6Ii8zNDUyNTg0OC8zMzM5MjI5NTItMzc4MGI1N2UtNDFmNy00ZDJkLTgyZDEtYjYzYzZkN2U1OTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE0MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhY2FkMDg3YjQ3ZmI2N2EwYTQ4ZTJhNzQ4YjQ2ZjI5MTY2MmY1NDdmZjgxY2Y0NjUwZTA2NWIzMTA2MjhiNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZEHJrcrvgHi9otdTk47UyIZeoeePSAvysr6W8qJe4wk">
> 
> using the above snippet solves sentry issue but will end-up throwing the above-screenshot error

@FashMuyhee did you manage to solve it? That error went from MMKV lib?

**Comment by batuhanbag** [comment]
@krystofwoldrich  `      unless target.name == 'Sentry'` approach solved my issue thanks a lot !

**Comment by julian-gargicevich** [comment]
In case someone is using expo and has some other plugin adding that line to the Podfile I wrote this little hack plugin to override it. You just need to import the plugin from your app.config file  like ['./plugins/withSentry.js']

`const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

function updatePodfile(config) {
  return withDangerousMod(config, [
    "ios",
    (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        "Podfile"
      );

      let podfileContents = fs.readFileSync(podfilePath, "utf-8");

      const searchString = `config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'`;
      const replaceString = `config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = target.name == 'Sentry' ? 'YES' : 'No'`;

      podfileContents = podfileContents.replace(searchString, replaceString);

      fs.writeFileSync(podfilePath, podfileContents);

      return config;
    },
  ]);
}

module.exports = function withSentryPlugin(config) {
  return withPlugins(config, [[updatePodfile]]);
};
`
