### ISSUE TITLE
Source map file is missing debugId after upload

### ISSUE THREAD

**Issue by rajatkantinandi** [getsentry/sentry-react-native#3801]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Web

**SDK:**
- [x]  `@sentry/react-native` (5.20.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**Expo SDK version:** 50.0.17

**`react-native` version:** 0.73.6

**`@sentry/cli` version:**  2.31.2

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://guide-care-inc.sentry.io/issues/5002500684/events/ca72c698c1424e0898ee583677b9dac8/)

**Configuration:**

(`@sentry/react-native`)
```ts
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  environment: process.env.ENV,
  sendDefaultPii: false,
  ...(Platform.OS === 'web' ? { release: Constants.expoConfig?.version } : {}),
  beforeSend(event) {
      // docs.sentry.io/platforms/react-native/data-management/sensitive-data/#scrubbing-data
      if (event.contexts?.device?.name) {
        delete event.contexts.device.name;
      }

      return event;
    },
});
```

---
**I have the following issue:**

I am uploading sourcemaps after generating using expo command: `expo export --source-maps --platform web`.
Upload command: 
```
cd dist && npx sentry-cli sourcemaps upload --org <org-name> --project <project-name> --release=<release> --dist=<environment> _expo/static/js/web/
```

Before and after upload I checked both the `.js` and `.js.map` file and both of them contains the same `debugId`.
But after uploading when I go to sentry release, I see that the `.js` file has the debugId but `.js.map` file does not have debugId. See the screenshot:
![Screenshot 2024-05-06 at 9 30 19 PM](https://github.com/getsentry/sentry-react-native/assets/17743895/89600033-fcb6-4280-8442-343c9b1fe0c3)

As a result, when an error happens on the frontend it show stack trace of minified code.
![Screenshot 2024-05-06 at 9 32 02 PM](https://github.com/getsentry/sentry-react-native/assets/17743895/7261360f-66d0-4c54-bfeb-0c8adeb8c399)
It also says: "No Source Map With Matching Debug ID"
![Screenshot 2024-05-06 at 9 32 26 PM](https://github.com/getsentry/sentry-react-native/assets/17743895/936301b0-f243-4318-a300-8b401179bf38)

I am not sure why the debug id is missing from the uploaded `.map` file but present before upload when I check it by opening the file.

Also, I saw in the documentation mentioning that the source map file should have a property `debug_id` but my source map file has a property `debugId` instead. Is that why this is happening? Do you know how the sourcemap will have `debug_id` instead of `debugId`?

**Steps to reproduce:**
- As described above.

**Actual result:**

Soucemap file is missing debugId and error shows minified code.

**Expected result:**

Soucemap file should have debugId and error should show the source code.

**Comment by krystofwoldrich** [comment]
Hi @rajatkantinandi,
you are correct the `debugId` and `debug_id` difference is the reason why the source map is missing the Debug ID.

You can use our built-in script for uploading Expo source maps which takes care of these differences.

https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/expo/#upload-source-maps

```sh
SENTRY_PROJECT=android \
SENTRY_ORG=demo \
SENTRY_AUTH_TOKEN=Click to generate token \
npx sentry-expo-upload-sourcemaps dist
```

In case this has not helped, feel free to comment here and we can reopen the issue.

**Comment by rajatkantinandi** [comment]
Thanks for the response.
Looks like the script you mention internally does this:
```js
    if (sourceMap.debugId) {
      sourceMap.debug_id = sourceMap.debugId;
    }
```

Any reason why it is implemented this way?
Also, running `npx sentry-expo-upload-sourcemaps dist` does not associate the build with a release. Is there a way to do that with that script?
