### ISSUE TITLE
CaptureException - Object captured as exception with keys: extensions, message

### ISSUE THREAD

**Issue by saqibaligorilla** [getsentry/sentry-react-native#3808]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ~5.12.0

**`react-native` version:** 0.73.7

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
 Sentry.init({
      dsn: 'dns',
      tracesSampleRate: 0.6,
      _experiments: {
        profilesSampleRate: 1.0,
      },
      attachViewHierarchy: true,
      attachScreenshot: true,
      beforeBreadcrumb(breadcrumb) {
        return breadcrumb.category === 'ui.click' ? null : breadcrumb;
      },
      integrations: [
        new Sentry.ReactNativeTracing({
          tracingOrigins: ['*', /^\//],
          enableAppStartTracking: true,
          ignoreEmptyBackNavigationTransactions: true,
          routingInstrumentation,
        }),
      ],
    });
```

---
**I have the following issue:**
- captureException
Object captured as exception with keys: extensions, message

**Comment by krystofwoldrich** [comment]
Hi @saqibaligorilla,
thank you for the message,
this happens when the object provided in `captureException(myObject)` or uncaught `throw myObject` is not an instance of an JS Error.

Could you share a bit more details about what kind of object causes the behaviour and what is the expected behaviour?
