### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy [Expo]

### ISSUE THREAD

**Issue by julian-gargicevich** [getsentry/sentry-react-native#3810]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.0

**`react-native` version:** 0.74.1

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Description]

**Steps to reproduce:**
- Install Expo SDK 51 with the new privacyManifests config
- Run expo build

**Actual result:**

❌  error: Multiple commands produce '/Users/expo/Library/Developer/Xcode/DerivedData/App-fjauxkscdlvanfetgxcdeduzrxxs/Build/Intermediates.noindex/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/PrivacyInfo.xcprivacy'

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » App/App » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

**Expected result:**

Successful build

**Comment by krystofwoldrich** [comment]
Hi @julian-gargicevich,
thank you for the message, we will investigate this.

When you mention the new config are you referring to this https://docs.sentry.io/platforms/react-native/data-management/apple-privacy-manifest/

**Comment by kahest** [comment]
Related: [Expo 51 changelog entry on Apple Privacy Manifest](https://expo.dev/changelog/2024/05-07-sdk-51#apple-privacy-manifests). There is a new features to merge manifests, but this is disabled by default, so currently we wouldn't expect Expo 51 to behave differently than Expo 50.

**Comment by krystofwoldrich** [comment]
I've created a new Expo project like follow:

1. `npx create-expo-app@3.0.0` (currently with expo@51.0.13)
2. `npm i -E @sentry/react-native@5.23.1` (I also tried with 5.22.0)
3. Followed https://docs.sentry.io/platforms/react-native/manual-setup/expo
4. eas build
5. No privacy manifest errors

Please if you are still experiencing this problem or it occurred again, can you share a minimal reproducible example, which we can debug?

I'll close the issue for now. Feel free to comment here and we can reopen it.

**Comment by troberts-28** [comment]
@julian-gargicevich running into the same problem on Expo SDK 51 - did you find a fix?

**Comment by w4t3r-45** [comment]
installing latest sentry/cli fixed my issue 
 pnpm add -D @sentry/cli@latest
