### ISSUE TITLE
Cold Start metrics not recorded on RN 72 w/ Hermes

### ISSUE THREAD

**Issue by rpropst** [getsentry/sentry-react-native#3834]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.72.10

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://best-buy-el.sentry.io/performance/trace/d191e2bd29ee460c84a2e25435251f4f/?fov=0%2C4875.175048828125&node=txn-3b463c94d3ec45d79a9e8bc8ddc896b6&statsPeriod=30m&timestamp=1716344119)

---
**I have the following issue:**
Cold start metrics do not show

**Comment by krystofwoldrich** [comment]
Hi @rpropst,
thank you for posting the issue,
excuse the longer response time cause by the conference season.

I'm currently looking into it.

**Comment by krystofwoldrich** [comment]
This issue was resolved in a private chat with the customer.
