### ISSUE TITLE
User Feedback API does not work (dropping)

### ISSUE THREAD

**Issue by AyoCodess** [getsentry/sentry-react-native#3844]
**OS:**
- [ ]  MacOS

**Platform:**
- [ ]  iOS
- [ ]  Android

**SDK:**
   "@sentry/react-native": "~5.22.3",
   "react-native": "0.73.6",
  "expo": "~50.0.14",

**Are you using Expo?**
- [ ]  Yes

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)

```
Sentry.init({
  dsn: 'https://******',
  attachScreenshot: true,
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
  // We recommend adjusting this value in production.
  tracesSampleRate: 1.0,
  _experiments: {
    // profilesSampleRate is relative to tracesSampleRate.
    // Here, we'll capture profiles for 100% of transactions.
    profilesSampleRate: 1.0
  },
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      enableNativeFramesTracking: !isRunningInExpoGo()
      // ...
    })
  ]
});
```
**NONE**
Sentry.config(

---
**I have the following issue:**

I have a react naive expo app (SDK 50), i get errors in my sentry dashboard without any hickups almost instantly. but the User Feedback API does not work at all. any insights?

**edit** just one of them came through finally after 21 mins, but the rest from what it looks like got dropped by the sentry cloud server. i've sent over 50 in the last 7 hours.

this api also does not work

```
Sentry.captureEvent({
                     level: 'info',
                      message: comment,
                      event_id: topic
                      });               

```

**The action trigger**
```
 onPress={ () => {
                     try { 
 Sentry.captureUserFeedback(userFeedback);
                        handleClose();    
                      } catch (err) {
          Sentry.captureException(err);
                        alert('Error sending feedback, please try again');
                      }
                    }}
```

**Comment by krystofwoldrich** [comment]
Hi @AyoCodess,
thank you for the message.

Can you add `debug: true` to your `Sentry.init` and see if the event from `captureEvent` is not dropped before sending?

`captureEvent` is low level api, I would recommend using `captureMessage` instead.

```js
// Preferred 
Sentry.captureMessage({
    message: comment,
});

Sentry.captureEvent({
    level: 'info',
    message: comment,
    // event_id: topic // Sentry will generate new event id
});
```

The feedback function requires `event_id` of an existing event, otherwise it won't be processed by the server. Does this snipped works for you?

```js
const id = Sentry.captureEvent({
  message: 'Captured event',
  level: 'info',
});
console.log('Sentry.captureEvent() event_id:', id);
Sentry.captureUserFeedback({
  event_id: id,
  name: 'User Feedback',
  comments: 'This is a test feedback',
  email: 'me@test.com',
});
```

If you would like to attach the feedback to the last captured error you can use `Sentry.lastEventId`.

Let us know if the message was helpful and if it solved your issue.

**Comment by AyoCodess** [comment]
> ```js
> const id = Sentry.captureEvent({
>   message: 'Captured event',
>   level: 'info',
> });
> ```

thanks for the response, i made the recommend changes. This what the the logs look like
```

 LOG  Sentry Logger [log]: Event processor "Dedupe" dropped event
 LOG  Sentry Logger [log]: Adding outcome: "event_processor:error"
 LOG  Sentry Logger [log]: An event processor returned `null`, will not send event.
```

**Comment by krystofwoldrich** [comment]
Happy to hear that it works!

> Can the docs be updated with more information around this

Definitely, are you referring to this page https://docs.sentry.io/platforms/react-native/user-feedback/#user-feedback-api

Or you meant more information about the `captureEvent` method?

**Comment by AyoCodess** [comment]
> Happy to hear that it works!
> 
> > Can the docs be updated with more information around this
> 
> Definitely, are you referring to this page https://docs.sentry.io/platforms/react-native/user-feedback/#user-feedback-api
> 
> Or you meant more information about the `captureEvent` method?

referring to this https://docs.sentry.io/platforms/react-native/user-feedback/#user-feedback-api
