### ISSUE TITLE
Android initial load screen time is way above then it should be

### ISSUE THREAD

**Issue by matheuscouto** [getsentry/sentry-react-native#3847]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.4

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Android trace](https://turbotenant.sentry.io/performance/trace/3ae2ad94310442c3b1b4f1a4c79ae6ce/?fov=0%2C15859.35302734375&node=txn-7ae6d89b635a4814b10c95e2481352bc&timestamp=1717161343)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: ENVS.SENTRY_DSN,
  release: releaseString,
  tracesSampleRate: 1.0,
  environment: ENVS.APP_ENV,
  integrations: [new Sentry.ReactNativeTracing({ routingInstrumentation })],
  normalizeDepth: 10,
  _experiments: {
    profilesSampleRate: 1.0,
  },
});
```

---
**I have the following issue:**

Hey there! As you can see in the attached images, the initial display time for the android is way higher then it should, the screen is loaded many seconds before the actual transaction is recorded. I also attached a comparison between the Android and iOS operations. Is there anything I can do here? Tks!

![Screenshot 2024-05-31 at 10 33 17](https://github.com/getsentry/sentry-react-native/assets/20684804/c83d967e-aae6-4d4a-af55-8591a943d692)
![Screenshot 2024-05-31 at 10 36 16](https://github.com/getsentry/sentry-react-native/assets/20684804/3a841c1d-364b-4621-b8eb-2a417685572d)

**Comment by krystofwoldrich** [comment]
Hi @matheuscouto,
thank you for the report,

are you seeing the same behaviour on simulator and real devices? Are you using tabs navigation or stack or combination, if combination, can you describe how are the navigators nested?

We have an issue tracking this bug, please let's move further discussion there.

- https://github.com/getsentry/sentry-react-native/issues/3786
