### ISSUE TITLE
Missing setup instructions for Android

### ISSUE THREAD

**Issue by wbyoung** [getsentry/sentry-react-native#385]
It appears that the manual setup steps are missing the required Java code changes. Having previously added `react-native-navigation`, the `react-native link` step did not make these changes for me (and didn’t warn about that either… probably a separate issue). I had to end up [here](https://github.com/getsentry/react-native-sentry/issues/6#comment-368777938) before realizing what was missing & why data wasn’t being sent for Android only.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
