### ISSUE TITLE
How to capture console warnings and errors in react native

### ISSUE THREAD

**Issue by ishaangandhi** [getsentry/sentry-react-native#3865]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want console warnings and errors to be captured in my Expo application and be reported to Sentry so I can get alerts. The reason is that sometimes there are async functions which have errors logged with `console.error`, but don't throw. I want to get reports of these issues.

### How are you getting stuck?

I see capture console exists in the [JS SDK](https://docs.sentry.io/platforms/javascript/configuration/integrations/captureconsole/), but I don't see an equivalent in the React-Native SDK.

### Where in the product are you?

Alerts

**Comment by krystofwoldrich** [comment]
Hi @ishaangandhi,
thank you for the message, 

you are correct the `captureConsoleIntegration` will work for RN projects. 

We will add it to the RN Docs.

**Comment by krystofwoldrich** [comment]
The docs page will be added as part of https://github.com/getsentry/sentry-react-native/issues/3876.

**Comment by delandchen** [comment]
For anyone upgrading to `Expo 52` and `sentry/react-native @6.1.0` — `@sentry/integration` has been removed.

Use `import { captureConsoleIntegration } from "@sentry/core";` instead. 

Or if you're using other SDKs, here is the migration doc:
[MIGRATION.md Reference](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#sentryintegrations)
