### ISSUE TITLE
Sentry client is missing, the error event might be lost

### ISSUE THREAD

**Issue by LonelyCpp** [getsentry/sentry-react-native#3870]
**OS:**
- [x]  MacOS

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** "5.20.0"

**`react-native` version:** "0.72.13"

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```js
 Sentry.init({
    enabled: true,
    debug: true,

    environment: 'staging',
    dsn: '[redacted]',

    enableCaptureFailedRequests: false,

    enableAppHangTracking: true,

    onReady: params => {
      console.log('sentry-event onReady:', params);
    },

    beforeBreadcrumb: (breadcrumb: Sentry.Breadcrumb) => {
      // remove automatic http breadcrumbs (from native)
      const isHttp = breadcrumb.category === 'http';

      // remove automatic console-log tracking
      const isConsole = breadcrumb.category === 'console';

      if (!isHttp && !isConsole) {
        // note : uncomment to see all the breadcrumbs added
        // console.log('sentry-event adding breadcrumb:', breadcrumb);

        return breadcrumb;
      }

      return null;
    },

    integrations: integrations => {
      integrations.push(
        new HttpClient({
          failedRequestStatusCodes: [[500, 599]],
        }),
      );

      console.log(
        'sentry-integrations:',
        integrations.map(item => item.name),
      );

      return integrations;
    },
  });
```

---
**I have the following issue:**

Errors and crashes are not captured in release builds. 
When debug flag is enabled, I can see errors that say "sentry client is missing, the error event might be lost"

`Sentry.getClient()` returns `null`

(errors and crashes are reported as expected on debug builds)

**Comment by krystofwoldrich** [comment]
Hi @LonelyCpp,
thank you for the message,

could you share how did you tested the errors in release? (Note that you have to reopen the application to let the errors upload to Sentry)

`sentry client is missing, the error event might be lost` do I understand it correct, that in release this is logged out but in debug it's not?

 Is your setup monorepo? Have you possibly installed some `@sentry/*` libraries in addition to `@sentry/react-native`? (There might be a mismatch of versions.)

**Comment by LonelyCpp** [comment]
A npm package internally used the js sentry package, disabling that resolved the issue

>  how did you tested the errors in release

we set `debug` to true in the `Sentry.init` call and inspected adb logs

**Comment by krystofwoldrich** [comment]
Thank you for the details about resolution.
