### ISSUE TITLE
Sourcemaps upload not working with Expo SDK 50. Manual upload stuck with "Absolute Path Mismatch"

### ISSUE THREAD

**Issue by ByronStar** [getsentry/sentry-react-native#3886]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.ina.coach/2',
  enabled: !__DEV__,
  enabledNative: !__DEV__, // Set to true to enable Sentry for EAS builds.
  logLevel: 3,
  debug: true, // If `true`, Sentry will try to print out useful debugging information if something goes wrong with sending the event. Set it to `false` in production
  release: "de.bosconnect.inacoach.v3@" + app.expo.version,
});
```

---
**I have the following issue:**

By switching from Expo SDK49 to SDK50 I had to migrate [sentry-expo to @sentry/react-native](https://docs.sentry.io/platforms/react-native/migration/sentry-expo/) including the metro config stuff. With sentry-expo I already had to switch to **sentry-cli** for sourcemaps upload when I started to use **eas update**.

With the new SDK50 I tried to reactivate the automatic upload and used the sentry wizzard scripts. The result config did not differ from what I already changed manually. So I am currently back to manual upload. Originally the Sentry.init did not contain the release attribute (we relied on the Expo/Sentry? mechanism <bundle>@<version>+<buildnumber>) but then I got "Sentry not part of release pipeline" on my events despite the fact, that sourcemap artefacts where attached to the release.

Manual tries:
npx sentry-expo-upload-sourcemaps ./dist 
dies with: error: This version of Sentry does not support artifact bundles. A release slug is required (provide with --release)

./node_modules/.bin/sentry-cli sourcemaps upload --debug-id-reference --release="de.bosconnect.inacoach.v3@3.1.1" ./dist
works fine, but the uploaded sourcemaps seem unusable and I get "Absolute Path Mismatch" on the triggered events

**Steps to reproduce:**
- Setup project with Expo SDK50, Sentry, eas update, metro and Hermes  engine 🤪
- Run above commands

[Actual result]
Commands fail (see above)

[Expected result]
Any way to upload usable sourcemaps, but preferably automatic upload on eas update and eas build.

**Comment by krystofwoldrich** [comment]
Hi @ByronStar,
thank you for the message,
based on the error message, the version of self hosted Sentry you are using at the moment doesn't support [the artifacts bundles](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/) which the Sentry SDK for Expo 50 and newer uses to upload source maps for EAS Updates.

What version of Sentry are you using?

**Comment by ByronStar** [comment]
Hi @krystofwoldrich ,
thx for the quick response and nice that it is you 😄 helping us - we've met at App.js in Krakow. 
We are using 23.4.0 (1b0b60329f75) from May 8th 2023 - is there an upgrade path to the latest version or do we need to start over for using SDK50 builds?

**Comment by krystofwoldrich** [comment]
Ohhh, nice! Thanks for the exact Sentry version, I'll check with our self-hosted experts and keep you updated here.

**Comment by ByronStar** [comment]
Hi @krystofwoldrich.

thx again for pointing out the base problem. In the meantime I have upgraded our Sentry successfully to 24.4.2  (after I have added more CPU power to our server 🤪 - Sentry got quite resource hungry). 

For some reason (I forgot to capture) the upgrade to 24.5.1 did not work quite as well, but 24.4.2 seems to be enough to support Artifact bundles. After that I could use `npx sentry-expo-upload-sourcemaps ./dist` to upload sourcemaps and bundles and got back seeing issues within the source code!

**Comment by krystofwoldrich** [comment]
Thank you for the message, I'm happy that the Sentry upgrade eventually worked out.

If you have some more question about self-hosted, you can visit our Discord channel #self-hosted to talk directly to the engineers working on that part of Sentry.

https://discord.gg/UMecZVkG
