### ISSUE TITLE
CWE-330: Use of Insufficiently Random Values in `MetricsHelper.java`

### ISSUE THREAD

**Issue by sizhe-eb** [getsentry/sentry-react-native#3897]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** Android SDK 34

**`react-native` version:** 0.74.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
const reactInstrumentation = new Sentry.ReactNavigationInstrumentation({
      routeChangeTimeoutMs: 500, // How long it will wait for the route change to complete Default is 1000ms
    });
    Sentry.init({
      dsn: ENV.SENTRY_INTERNAL_DNS,
      debug: false, //Enable debuger when needed
      enableNative: false, //The SDK will only capture errors on the upper layer.
      maxBreadcrumbs: 150,
      // enableNdkScopeSync: true,
      enableAutoSessionTracking: true,
      sessionTrackingIntervalMillis: 10000,
      environment: ENV,
      // Performance
      integrations: [
        new Sentry.ReactNativeTracing({
          idleTimeout: 5000,
          tracingOrigins: ["localhost", /^\//, /^https:\/\//],
          routingInstrumentation: reactInstrumentation,
        }),
      ],
      tracesSampleRate: 1.0,
    });
```

---
**I have the following issue:**
CWE-330: Use of Insufficiently Random Values
https://github.com/MobSF/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md#weak-random-number-generators
![image](https://github.com/getsentry/sentry-react-native/assets/62536400/24cbdade-5d34-4b24-b508-14b0265a74a0)

**Steps to reproduce:**
- Yarn add @sentry/react-native
- Use [Mobile Security Framework Mobsf](https://github.com/MobSF/Mobile-Security-Framework-MobSF.git) to test the APK file
- Start the Static Analysis and check the Security Analysis -> Code Analysis
- Check the [The App uses an insecure Random Number Generator.](https://github.com/MobSF/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md#weak-random-number-generators) issue

![image](https://github.com/getsentry/sentry-react-native/assets/62536400/948a895b-0960-47c0-948a-85a0c524dd79)

**Comment by krystofwoldrich** [comment]
Hi @sizhe-eb,
thank you for the report. We will check this.

**Comment by krystofwoldrich** [comment]
@markushi Can we change https://github.com/getsentry/sentry-java/blob/7ce635b0df36f67d46a78ad0fad8cd60c7152308/sentry/src/main/java/io/sentry/metrics/MetricsHelper.java#L30 to `java.security.SecureRandom`?

**Comment by markushi** [comment]
> @markushi Can we change [getsentry/sentry-java@`7ce635b`/sentry/src/main/java/io/sentry/metrics/MetricsHelper.java#L30](https://github.com/getsentry/sentry-java/blob/7ce635b0df36f67d46a78ad0fad8cd60c7152308/sentry/src/main/java/io/sentry/metrics/MetricsHelper.java#L30) to `java.security.SecureRandom`?

Yes we can, PR is up here: https://github.com/getsentry/sentry-java/pull/3495

**Comment by sizhe-eb** [comment]
@krystofwoldrich @markushi
Thanks a lot! Can't wait for the next release!
