### ISSUE TITLE
SentryPrivate.modulemap not found

### ISSUE THREAD

**Issue by ospfranco** [getsentry/sentry-react-native#3921]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [X]  MacOS
**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.24.1

**`react-native` version:** 0.73.1

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

I'm using sentry for macOS. I just updated to the latest version. However when I try to compile my app in release mode I get the following exception:

![OSP 000065](https://github.com/getsentry/sentry-react-native/assets/1634213/a8646241-91d5-4aae-a9e9-4a95f7b75893)

On debug everything compiles correctly, it's only when I try to compile on release that it fails. Any idea what might be going on?

As I side note, when I updated the package and did a `pod install` the SentryPrivate pod was removed from the project.

**Comment by krystofwoldrich** [comment]
Hi @ospfranco,
thank you for the message,
from the current information I'm not sure what could cause this error.

Do you use `OTHER_CFLAGS`, `APPLICATION_EXTENSION_API_ONLY` or any other compiler flags? Do some of there differ between debug and release?

**Comment by ospfranco** [comment]
Nope, don't user any other flag.

**Comment by krystofwoldrich** [comment]
Got it thank you.

Are you able to reproduce it in a new `react-native-macos` project?

We recently added [macos sample app](https://github.com/getsentry/sentry-react-native/pull/3785) to our sample, but it build with the latest SDK.

The command I use:

```bash
xcodebuild \
    -workspace sentry-react-native-sample.xcworkspace \
    -configuration "Release" \
    -scheme sentry-react-native-sample-macOS \
    -destination 'platform=macOS' \
    ONLY_ACTIVE_ARCH=yes \
    -derivedDataPath "$derivedData" \
    build
```

**Comment by ospfranco** [comment]
Thanks for the reply, it seems indeed it builds on a completely new project. So it has to be some migration artifact. I will keep trying to resolve it on my side.

**Comment by akshaysngt** [comment]
> Thanks for the reply, it seems indeed it builds on a completely new project. So it has to be some migration artifact. I will keep trying to resolve it on my side.

@ospfranco  Are you able to resolve it? Currently facing this issue on XCode 16 with sentry@5.33.1

**Comment by ospfranco** [comment]
uhm no, I had forgotten about this actually. Right now I'm on 5.24.3 and it's working, did not try with the latest versions yet.
