### ISSUE TITLE
Fatal error in iOS SentryCrashMonitor CPP Exception

### ISSUE THREAD

**Issue by KrisLau** [getsentry/sentry-react-native#3937]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 7.117.0

**`react-native` version:** 5.24.1

**Are you using Expo?**
- [x]  Yes (bare workflow)
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```js
Sentry.init({
  dsn: 'https://c9d52bc679c44d0f8d455f02d3356df5@o851837.ingest.sentry.io/5818647',
  enableAutoSessionTracking: true,
  sessionTrackingIntervalMillis: 10000,
  integrations: [
    new Sentry.ReactNativeTracing({
      idleTimeout: 5000,
      tracingOrigins: ['localhost', /^\//, /^https:\/\//],
    }),
  ],
  tracesSampleRate: 0.2,
  beforeSend: handleSentryBeforeSend,
});

function handleSentryBeforeSend(event, hint) {
  addAxiosContextRecursive(event, hint?.originalException);
}

function addAxiosContextRecursive(event, error) {
  if (error.isAxiosError) {
    addAxiosContext(event, error);
  } else if (error instanceof Error && error.cause) {
    addAxiosContextRecursive(event, error.cause);
  }
}

function addAxiosContext(event, error) {
  if (error.response) {
    const contexts = {...event.contexts};
    contexts.Axios = {Response: error.response};
    event.contexts = contexts;
  }
}
```

---
**I have the following issue:**

Sentry (I think) is causing my react native app to fatally crash when I click on a specific button in my app but only for ios when my build configuration for the schema is set to Release. The error I'm getting:
```swift
Unhandled JS Exception: Error: TypeError: Cannot assign to property 'Symbol.toStringTag' on HostObject with default setter, js engine: hermes
```
The button click does not error at all in my regular build (which uses a different schema that sets the build configuration to debug). I also tried adding a try catch to the method that the button press calls and nothing is caught. Anyone have a clue as to what I can do to fix it?

(Unrelated but release builds are also missing debug information:
![image](https://github.com/getsentry/sentry-react-native/assets/46275463/8d8cfe88-6b20-4c6a-bb7c-3253b323720c)
not sure what I need to get release builds working)

**Steps to reproduce:**

1. Function being called
  ```js
  function selectPlayer(index) {
      const playersCopy = [...players];
      const selectedPlayersCopy = [...selectedPlayers];
      const selectedIndex = selectedPlayers.findIndex(x => x.id === players[index].id);
      const newIsChecked = !players[index].checked;
  
      playersCopy[index] = _.cloneDeep(players[index]);
      playersCopy[index].checked = newIsChecked;
  }
  ```
2.  Set the schema build configuration to Release and run

**Actual result:**

![image](https://github.com/getsentry/sentry-react-native/assets/46275463/53171136-45bc-46bb-8d39-aa5fb717697e)

**Expected result:**

No crash

**Comment by KrisLau** [comment]
Removing the _.deepClone() gets rid of the error but causes my function to not work fully and still not sure why it's fatally crashing

**Comment by krystofwoldrich** [comment]
Hi @KrisLau,
thank you for the message and the details.

From the screenshot of the crash and the information that it's not happening after removing `_.deepClone()` I believe it's not Sentry causing the crash. The Xcode debugger stops right before terminating the application and the last frame in this case is the Sentry CPP Handler calling the original handler.

Is the `JS Unhandled` error reported to Sentry? Do you see the javascript stack trace in Sentry? Is the error about missing debug information from the same error?

Do you have the Xcode build phases configured with Sentry?
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload

For Expo these are configured by the `@sentry/react-native/expo` plugin, but you can also do it manually.

**Comment by KrisLau** [comment]
@krystofwoldrich My app uses an ErrorBoundary in addition to Sentry and neither of them seem to be catching the error. I also tried to add a try catch to the function itself and that didnt catch the error either so I'm fully stumped as to why this might be happening.

**Comment by krystofwoldrich** [comment]
Based on the message, most likely this is the error you are seeing.

https://github.com/krystofwoldrich/hermes/blob/4bcd62206c672c5b9674cab1399931ae8c275829/API/jsi/jsi/jsi.cpp#L77-L82

Depending on how this is called, the error might not be re thrown in JS and directly crashes the native runtime.

**Comment by KrisLau** [comment]
> Based on the message, most likely this is the error you are seeing.
> 
> https://github.com/krystofwoldrich/hermes/blob/4bcd62206c672c5b9674cab1399931ae8c275829/API/jsi/jsi/jsi.cpp#L77-L82
> 
> Depending on how this is called, the error might not be re thrown in JS and directly crashes the native runtime.

ahh ok I see, thank you so much! Is there a way to catch this to your knowledge? 


> `npx @sentry/wizard@latest -s -i reactNative` adds the Build Phases automatically. So the source maps should be uploaded during the release build.
> 
> Could you share the stack trace of the error?

Would this work?
![image](https://github.com/getsentry/sentry-react-native/assets/46275463/cca4687a-86f9-40da-8faa-943ffd238e5d)

The expanded error:
![image](https://github.com/getsentry/sentry-react-native/assets/46275463/02d4ded0-0617-4504-b351-16003faea0b7)

**Comment by KrisLau** [comment]
Ok I just retested my development build and it looks like the error logging isnt working there either. Looking back in my commits it looks like it started happening when I updated from 5.22.2 to 5.24.1 and made this change:
![image](https://github.com/getsentry/sentry-react-native/assets/46275463/3e42e880-e44e-4b15-b267-b1311c689b7e)
Maybe that will help?

**Comment by krystofwoldrich** [comment]
@KrisLau Thank you for the details, I'm happy to hear it works now.

It might been a poisoned cache somewhere in the build process, but that's just a guess. I'll close the issue. But feel free to add more information if the issue should rise up again.
