### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'hot')

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [getsentry/sentry-react-native#3938]
**OS:**
MacOS

**Platform:**
Android

**SDK:**

- [ ]  `@sentry/react-native` (5.24.1)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.63.5

**Are you using Expo?**
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    environment: process.env?.NODE_ENV,
    dsn: env.SENTRY_DSN,
    tracesSampleRate: 1.0,
    debug: true,
    enableNative: true,
    enableNativeCrashHandling: true,
  });
```

---
**I have the following issue:**
I have integrated sentry  manual setup 
when I run my project build successful but in meteor server getting this error
<img width="710" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/16689214/60666cdf-0bf9-4f16-bf39-a4c377a8764f">

**Steps to reproduce:**
integrate sentry manuall in react native version 0.63.5

**Actual result:**
getting error 
ode_modules/@sentry/react-native/dist/js/tools/sentryMetroSerializer.js:40
            if (graph.transformOptions.hot) {
                                       ^

TypeError: Cannot read properties of undefined (reading 'hot')

[Actual result]

**Expected result:**
should work fine

**Comment by krystofwoldrich** [comment]
Hi @mubashiralisiddiqui,
thank you for the message,

sadly the minimum supported version for Sentry RN SDK is RN 0.65.

Are you able to upgrade to that version or newer?

**Comment by mubashiralisiddiqui** [comment]
@krystofwoldrich  I have upgraded to react native v0.66
and when I tried to install sentry its says 

![Image](https://github.com/user-attachments/assets/8b0fead4-8305-4ed5-9229-2ceacac069dd)

unsupported while in  the readme its written that minimum required version is 0.65 you also said earlier
