### ISSUE TITLE
Seeking Activation example for Expo SDK51 since it no longer generates App.js!

### ISSUE THREAD

**Issue by ezrover** [getsentry/sentry-react-native#3946]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.25.0

**`react-native` version:** 0.74.2

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

The provided examples dont indicate how to handle apps that no longer have App.js as their starting point as it has been removed in the latest apps generated by Expo SDK51. Please provide an example of how to activate Sentry without app.js

**Comment by kahest** [comment]
Hey @ezrover depending on your setup and routing instrumentation, you can init Sentry e.g. in your `app/_layout.js` or `app/_layout.tsx`, where your `App` or `RootLayout` lives. See https://docs.sentry.io/platforms/react-native/manual-setup/expo/ and https://docs.expo.dev/guides/using-sentry/#usage-with-expo-router for more info.
