### ISSUE TITLE
Redaction disabled in code, still seeing replays being redacted

### ISSUE THREAD

**Issue by hackily** [getsentry/sentry-react-native#3962]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.23.0-alpha.1

**`react-native` version:** 0.74.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://curai.sentry.io/replays/387f9058b27546b0a189cf5659c66916

**Configuration:**

(`@sentry/react-native`)
```
    SentrySDK.init({
      dsn: "https://5dde36833792a09c9887576b78bd803e@o4505633803468800.ingest.sentry.io/4505639539507200",
      environment: nativeEnv,
      tracesSampleRate: 1.0,
      sendDefaultPii: true,
      release: "app",
      dist: "lystrosaurus-32",
      _experiments: {
        // React Native replay
        replaysSessionSampleRate: 1.0,
        replaysOnErrorSampleRate: 1.0,
      },
      integration: [
        SentrySDK.mobileReplayIntegration({
          maskAllText: false,
          maskAllImages: false,
        }),
      ],
    });
```

---
**I have the following issue:**

I've set the mobile SDK to not redact text and images, and yet I am seeing our replays be redacted

**Actual result:**

See this replay:
https://curai.sentry.io/replays/387f9058b27546b0a189cf5659c66916

**Expected result:**

Replays should not be redacted

**Comment by kahest** [comment]
@hackily thanks for the report, we're taking a look. Can you clarify - does this only happen on iOS, or also on Android?

**Comment by romtsn** [comment]
@hackily can you confirm you have ` integration: [` and not `integrations: [`? Because, I think, it should be `integrations`, or is this just a typo?

**Comment by romtsn** [comment]
> I indeed have `integration: [`, which I copied from the email we received when we were alerted to alpha being available. Changing it to `integrations` fixed it! Thanks for catching this

oh noes 🙈 we'll have the docs updated, thanks for reporting!

**Comment by bruno-garcia** [comment]
Fixed through: https://github.com/getsentry/sentry-docs/pull/10813

Thanks for raising
