### ISSUE TITLE
Duplicate Issues for same event

### ISSUE THREAD

**Issue by anirudhsama** [getsentry/sentry-react-native#3963]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.74.3

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]
https://lounge.sentry.io/issues/5631745136/?project=4505006490058752
https://lounge.sentry.io/issues/5634175537/?project=4505006490058752
https://lounge.sentry.io/issues/5630881604/?project=4505006490058752
https://lounge.sentry.io/issues/5632068281/?project=4505006490058752
https://lounge.sentry.io/issues/5625357376/?project=4505006490058752

**Configuration:**

(`@sentry/react-native`)
```typescript
Sentry.init({
	dsn: Env.SENTRY_DSN,
	tracesSampleRate: 0.01,
	enabled: !__DEV__,
	debug: __DEV__,
	enableNdkScopeSync: true,
	integrations: [new Sentry.ReactNativeTracing({ routingInstrumentation })],
	// only sample transaction events for paid users
	beforeSendTransaction: (event) => {
		if (event.user && event.user.is_paid) {
			return event;
		}

		return null;
	},
});

Sentry.configureScope((scope) => {
	scope.setTag("expo-update-id", Updates.updateId);
	scope.setTag("expo-is-embedded-update", Updates.isEmbeddedLaunch);

	if (typeof updateGroup === "string") {
		scope.setTag("expo-update-group-id", updateGroup);

		const owner = extra?.expoClient?.owner ?? "[account]";
		const slug = extra?.expoClient?.slug ?? "[project]";
		scope.setTag(
			"expo-update-debug-url",
			`https://expo.dev/accounts/${owner}/projects/${slug}/updates/${updateGroup}`,
		);
	} else if (Updates.isEmbeddedLaunch) {
		// This will be `true` if the update is the one embedded in the build, and not one downloaded from the updates server.
		scope.setTag(
			"expo-update-debug-url",
			"not applicable for embedded updates",
		);
	}
});
```

`metro.config.js`

```javascript
// Learn more https://docs.expo.dev/guides/monorepos
// Learn more https://docs.expo.io/guides/customizing-metro
/**
 * @type {import('expo/metro-config')}
 */
const { getSentryExpoConfig } = require("@sentry/react-native/metro");
const path = require("path");

// Find the project and workspace directories
const projectRoot = __dirname;
// This can be replaced with `find-yarn-workspace-root`
const workspaceRoot = path.resolve(projectRoot, "../..");

const config = getSentryExpoConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot];
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
	path.resolve(projectRoot, "node_modules"),
	path.resolve(workspaceRoot, "node_modules"),
];
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;

// Enable Inline Requires https://x.com/dan_abramov2/status/1761497722371137717
config.transformer.getTransformOptions = async () => ({
	transform: {
		inlineRequires: true,
	},
});

module.exports = config;
```

In case of EAS Updates, we upload the source maps using `sentry-expo-upload-sourcemaps`. Sample command:

`bun run eas update --branch production --message "HW Help fixes" && bun x sentry-expo-upload-sourcemaps dist`

---
**I have the following issue:**

We are using `Sentry.captureMessage` to send an event whenever an API times out on the app. Somehow this results in having multiple different Issues created on Sentry. I have attached the screenshot showing multiple issues across app versions.

**Steps to reproduce:**

```typescript
// Log the error to Sentry
if (error instanceof ClientTimeoutError) {
	Burnt.alert({
		title: "Request timed out, check internet and try again",
		preset: "error",
		message: "Please try again!",
		duration: 2,
	});

	Sentry.captureMessage("Client API Timeout", {
		contexts: {
			request: {
				url,
			},
		},
		tags: {
			timeout: true,
			path: options.dynamicPathIdentifier || path,
			timeout_value: error.timeout / 1000,
			retry_count: error.retryCount,
			method: options.method,
		},
		level: "warning",
	});
}
```

**Actual result:**

There are multiple issues being created for this event.

**Expected result:**

We expect only one issue to be created.

![Image](https://github.com/user-attachments/assets/069af917-764c-4526-8a06-b53221d6e35b)

**Comment by kahest** [comment]
Hey @anirudhsama thanks for the detailed report! We'll dig through the information and follow up here with questions and findings.

**Comment by armenzg** [comment]
This is not using the message for grouping but the thread stack trace.

Is it normal for the filename to change so often?

![Image](https://github.com/user-attachments/assets/174dc8bf-6efd-481b-8237-2f0028ffb1f7)



![Image](https://github.com/user-attachments/assets/14e3025d-e267-46b1-8ecc-918cd9674ed3)

**Comment by armenzg** [comment]
If you opted-in your org as an early adopter we can investigate if our new AI grouping would help in your case.

**Comment by anirudhsama** [comment]
The source maps are uploaded, so shouldn't the file name be taken from the that? Im seeing that in that event, somehow source map isn't available. But in another error which is running the same bundle (hot push via EAS Update) the source map is available.

Client API Timeout event ID: 3f724b60d16c4e7da9fed3a66a2b05ca - no source maps available
Another error event ID: 639e21c5dbef4f178c958c7c38833713 - source maps available

**Comment by yefim** [comment]
We've narrowed it down to `@sentry/integrations` version 7.114.0. We see a bunch of logs after only one tap:

https://github.com/user-attachments/assets/f9ce00ce-6046-4d0a-ad38-e12a83fb4b1a

We're fixing this by removing `@sentry/integrations` for now. This diff works for us:

![Image](https://github.com/user-attachments/assets/29326f23-871a-4ba4-9d56-a77c2c62f47c)

**Comment by anirudhsama** [comment]
> If you opted-in your org as an early adopter we can investigate if our new AI grouping would help in your case.

@armenzg We don't mind opting in, please let me know how to. Also, we have temporarily worked around this issue by logging it as an error via `captureException` rather than using `captureMessage` and that uses the source maps which resolves to a consistent file name.

**Comment by krystofwoldrich** [comment]
@anirudhsama Thank you for the details. The issue is caused by the placement of the stack trace in the message event.

We fixed this for the next major version RN SDK v6, and now brought it for v5 as well.

- https://github.com/getsentry/sentry-react-native/pull/3988

**Comment by krystofwoldrich** [comment]
Hi @yefim,
thank you for the message and the video,

it seem like what you are experiencing is related to `captureConsoleIntegration`. 

Could you open a new issue?

**Comment by anirudhsama** [comment]
Thanks @krystofwoldrich. Will upgrade the package. 

Might not be related, but is there a difference in how Sentry handles `captureMessage` vs `captureException`? Reason, after sending the error with `Sentry.captureException` we are seeing a lot more errors of this and the only thing that changed was this.

![Image](https://github.com/user-attachments/assets/ae7e9185-061a-4744-9e6a-575ff35109d2)
