### ISSUE TITLE
Sentry.properties not copy - build fails

### ISSUE THREAD

**Issue by IgorDePaula** [getsentry/sentry-react-native#3965]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

```
Sentry.init({
    dsn: 'https://xxxx',

    enableSpotlight: __DEV__,
    debug: __DEV__,
    tracesSampleRate: 1.0,
    attachScreenshot: true,
    integrations: [
        Sentry.metrics.metricsAggregatorIntegration()
    ],
    _experiments: {
        profilesSampleRate: 1.0,
    },
    beforeSend(event, hint) {
        if (hint && hint.originalException && hint.originalException.isAxiosError) {
            if (hint.originalException.response && hint.originalException.response.data) {
                let contexts = {
                    ...event.contexts
                };
                contexts.errorResponse = {
                    data: hint.originalException.response.data
                };
                event.contexts = contexts;
                event.tags = {'name': 'axios-reject'}
            }
        }

        return event;
    },
});
```

---
**I have the following issue:**
MY problem is on build with eas, it make a temporary build folder in /tmp, but the sentry.properties generated in android folder is not copied to this temp build folder, broken the build. When I put the file in this build folder, The build out success.

![Image](https://github.com/user-attachments/assets/3a1ea521-4fc2-45e9-ab56-cd96b65194e3)

[Description]

**Steps to reproduce:**
- Init a react native project with expo
- setup eas to build an android app
- setup a sentry account
- build the project with eas.

**Actual result:**

![Image](https://github.com/user-attachments/assets/3a1ea521-4fc2-45e9-ab56-cd96b65194e3)

**Expected result:**

successful build.

**Comment by kahest** [comment]
Hi @IgorDePaula which version of the SDK do you use? Did you follow the instructions on [setting up the SDK with Expo](https://docs.sentry.io/platforms/react-native/manual-setup/expo/)?
Is everything working as expected on iOS builds?

**Comment by IgorDePaula** [comment]
@kahest I'm using expo sdk 50 (sorry I not know if are expo sdk, android sdk...)

**Comment by kahest** [comment]
@IgorDePaula sorry for being ambiguous :) I mean which version of the Sentry React Native SDK (@sentry/react-native) are you using. Thanks for clarifying the Expo SDK version and that you don't use iOS.

**Comment by IgorDePaula** [comment]
@kahest @sentry/react-native": "~5.20.0, and yes, I followed [the automatic install](https://docs.sentry.io/platforms/react-native/manual-setup/expo/#automatic-install) with expo

**Comment by kahest** [comment]
Thanks for the quick replies, we'll take a look

**Comment by IgorDePaula** [comment]
@kahest I discovery the problem. My project have android folder already, for any previuos step. This folder was copied for build, but not this sentry.properties file. Now, I removed this folder, the eas create another android folder specifically for this build, and I used the sentry token like an environment variable, and then success.

**Comment by kahest** [comment]
@IgorDePaula glad it worked out for you! I'm gonna close this issue then, but feel free to comment in case a problem related to this issue comes up

**Comment by IgorDePaula** [comment]
@kahest Thank you very much for your attention.
