### ISSUE TITLE
Not Seeing Metrics Reported by Sentry.metrics

### ISSUE THREAD

**Issue by tao-qian** [getsentry/sentry-react-native#3971]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.7.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No link

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "https://XXX@XXX.ingest.sentry.io/XXX",
  environment: __DEV__ ? 'development' : 'production',
  tracesSampleRate: 1.0,
});
```

---
**I have the following issue:**

I am trying to enable counter in the app but it didn't seem to be working. Here is my code
```
    <Button
        onPress={() => {
          Sentry.metrics.increment("add_new_area", 1, {
            tags: { graph: 'none', public_data: true },
          });
          Sentry.captureException(new Error("Add new area"));
        }}
      >
```
The error would be reported correctly to Sentry, but I am not seeing the metrics in the metrics page for our project: https://brightgo-inc.sentry.io/metrics/?environment=development&interval=5m.

Am I looking for the metrics in the wrong place or there is something wrong with the setup?

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

No metrics is showing up.

**Expected result:**

Metrics is showing up.

**Comment by tao-qian** [comment]
Actually it started to work now, after I add the
```
  // Only needed for SDK versions < 8.0.0
 // integrations: [
 //   Sentry.metrics.metricsAggregatorIntegration(),
 //],
```
to the `init`. I thought the config wouldn't required since the comment says it is only required for 8.0.0 and we are on the latest version of the SDK, but I guess the latest version is also < 8.0.0.. Should the sample just be updated if the integration is always going to be required?

https://docs.sentry.io/platforms/react-native/metrics/#configure-metrics

**Comment by kahest** [comment]
@tao-qian thanks for the report and apologies for the confusion - we opened a [PR](https://github.com/getsentry/sentry-docs/pull/10891) to update the docs
