### ISSUE TITLE
React native session recoding not working on RN for Windows

### ISSUE THREAD

**Issue by gmacmaster** [getsentry/sentry-react-native#3977]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [X] Windows

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.72.15

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

I have enabled session recording for Andriod and iOS with no issue, but so far I haven't been able to create any sessions in the React Native windows environment. 

Is there any Windows RN specific configuration that needs to be done?

**Comment by krystofwoldrich** [comment]
Hi @gmacmaster,
just to ensure we are on the same line, by session recording you mean https://docs.sentry.io/platforms/react-native/session-replay/

If that's the case, we are happy to hear it works without issues on Android and iOS.

We currently don't have any plans of adding Windows support.

**Comment by gmacmaster** [comment]
Thanks @krystofwoldrich. That is what I mean. Do you know of any tools that support that support session replay on windows?

**Comment by bruno-garcia** [comment]
@krystofwoldrich do we bundle sentry-native on React Native already? do we support Windows native crashes?

**Comment by krystofwoldrich** [comment]
No, we don't bundle sentry-native yet. Only the JS layer works on Windows.

**Comment by bruno-garcia** [comment]
@vaind did this for Flutter, maybe some learnings there:
* https://github.com/getsentry/sentry-dart/pull/2286

I tried this .. 6 years ago? but it was UWP and sentry-native at that time didn't really work with it.
But would be keen to get this working if we can.

**Comment by krystofwoldrich** [comment]
@bruno-garcia Thanks for the context, I've linked it to https://github.com/getsentry/sentry-react-native/issues/1407
