### ISSUE TITLE
crash report uploaded with wrong context

### ISSUE THREAD

**Issue by mmerickel** [getsentry/sentry-react-native#398]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
node 8.9.4
npm 5.8.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
    deactivateStacktraceMerging: true,
    disableNativeIntegration: false,
    handlePromiseRejection: true,
    instrument: {
      tryCatch: true,
    },
    autoBreadcrumbs: {
      xhr: true,
      console: false,
      dom: false,
      location: false,
      sentry: false,
    },
}).install()
```

---
I have following issue:

We received a crash report containing tags and os information that does not match the context when the crash occurred. Specifically we call `Sentry.setTagsContext` and `Sentry.setUserContext` when our app starts up. These tags contain some information about the os, app version etc. When the app crashed it was on an older version, then the user upgraded, launched the app, and the report was uploaded.

**Steps to reproduce:**

- set tags
- crash the app
- configure app to set different tags, rebuild and reinstall
- run the app
- observe crash report contains the new javascript tags but old native metadata

**Actual result:**

- Crash report contains some old metadata (the stuff from native sentry-cocoa) but the new js context set by app when it started up.

**Expected result:**

- The app saved the context and was able to attach it to the crash report as it was when the app crashed.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
