### ISSUE TITLE
Upgrade to `sentry-cocoa@8.33.0` to fix Xcode 16 beta 5 build error

### ISSUE THREAD

**Issue by thespacemanatee** [getsentry/sentry-react-native#4009]
https://github.com/getsentry/sentry-cocoa/releases/tag/8.33.0

**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.27.0

**`react-native` version:** 0.74.3

**Are you using Expo?**
- [x]  Yes
- [ ]  No

---
**I have the following issue:**

Build error occurs on Xcode 16 beta 5. See this [PR](https://github.com/getsentry/sentry-cocoa/pull/4244) that fixes it in the new release.

**Comment by krystofwoldrich** [comment]
Hi @thespacemanatee,
thank you for the message, we just merged the https://github.com/getsentry/sentry-react-native/pull/4007 which bumps the cocoa version.

Will be released soon.
