### ISSUE TITLE
NSInvalidArgumentException   sentry_sanitize  New Level: Fatal -[__NSArrayM allKeys]: unrecognized selector sent to instance 0x28125c7b0

### ISSUE THREAD

**Issue by OskarAtJoint** [getsentry/sentry-react-native#4013]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.27.0

**`react-native` version:** 0.73

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
https://joint-academy.sentry.io/issues/5695182179/?project=5970155&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0

**I have the following issue:**

IOS crash 

**Steps to reproduce:**
Sentry.addBreadcrumb({ data:[] })

**Actual result:**

Native crash

**Expected result:**

No crash

**Comment by OskarAtJoint** [comment]
same as https://github.com/getsentry/sentry-react-native/issues/2973 but with different type

**Comment by krystofwoldrich** [comment]
@OskarAtJoint Thank you for the message, the fix is here

- https://github.com/getsentry/sentry-react-native/issues/4013
