### ISSUE TITLE
App is crashing after include Session Replays, on Android Device (Xiaomi at least)

### ISSUE THREAD

**Issue by elenitaex5** [getsentry/sentry-react-native#4034]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]
](https://abi-global-health-v0.sentry.io/issues/5400181358/?project=4504884103479296&query=release%3Acom.abiglobalhealth.proapp%404.1.2%2B335&referrer=release-issue-stream)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: process.env.EXPO_PUBLIC_SENTRY_DSN,
  environment: process.env.EXPO_PUBLIC_APP_ENV,
  _experiments: {
    replaysSessionSampleRate: 1.0,
    replaysOnErrorSampleRate: 1.0
  },
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation
    }),
    Sentry.mobileReplayIntegration({
      maskAllText: true,
      maskAllImages: true
    })
  ],
  ignoreErrors: ['notification.vapidPublicKey'],
  tracesSampleRate: 0.8
})
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

After including new Sentry dependency ( "@sentry/react-native": "~5.26.0") and all configuration needed for Session Replay Android app is crashing 4-5 seconds after open the app. 
Is working fine in native web, EXPO Android simulator, EXPO iOS simulator and iOS devices, but not in Android device (at least in Xiaomi)

**Steps to reproduce:**
- Install the app
- Open the app.

**Actual result:**
Crashing with this error 

![Image](https://github.com/user-attachments/assets/37b6a75c-07e8-4a77-a212-acf519b64902)

**Expected result:**

After open the app can be used normally.

**Comment by krystofwoldrich** [comment]
Hi @elenitaex5,
thank you for the message,

could you test this with the latest release of the RN SDK, https://github.com/getsentry/sentry-react-native/releases/tag/5.30.0, since `5.26.0` we have included multiple fixes, some related to crashes on Android devices.

Please, let us know if the upgrade fixes the issue.

**Comment by elenitaex5** [comment]
Hi @krystofwoldrich thanks for your answer! I've tried `5.30.0` and works fine also in Android devices. 
It fix the issue so I close it. Thanks
