### ISSUE TITLE
'ReactCommon/RCTTurboModule.h' file not found RN 0.75 New Architecture

### ISSUE THREAD

**Issue by serhii-yalla** [getsentry/sentry-react-native#4035]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [X]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.30.0

**`react-native` version:** 0.75.1

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

Can't build app in XCode with 0.75.1 react native and new arch enabled.
```
'ReactCommon/RCTTurboModule.h' file not found
In file included from /Users/pprnd/Documents/yalla_cashier/node_modules/@sentry/react-native/ios/RNSentry.mm:35:
```

**Steps to reproduce:**
- Step 1 Set up app with 0.75.1 react native and add @sentry/react-native 5.30.0
- Step 2 Install deps, pods and try to build app

**Actual result:**

![Image](https://github.com/user-attachments/assets/a8aeb59f-4f1f-4cfd-a103-cf88a02b1cc1)

**Expected result:**

Successful app build

**Comment by krystofwoldrich** [comment]
Thank you @serhii-yalla for the report, we will investigate this.

**Comment by serhii-yalla** [comment]
@krystofwoldrich When can I expect new release?

**Comment by thespacemanatee** [comment]
@krystofwoldrich we're also eagerly waiting for the release!

**Comment by krystofwoldrich** [comment]
This fix will be released later today.

**Comment by frankcalise** [comment]
I am experiencing this issue with RN 0.75.3, Expo 51 and @sentry/react-native 5.24.3

**Comment by Kaveh-ap** [comment]
I'm getting the same error with RN 0.75.4 and @sentry/react-native: 5.31.1

**Comment by gunnartorfis** [comment]
Yup, still an issue in 5.33.2 and RN 0.75.4. 

@krystofwoldrich was this released? If so, the issue should probably be reopened.
