### ISSUE TITLE
How to improve crash reports in RN sdk?

### ISSUE THREAD

**Issue by gavrilikhin-d** [getsentry/sentry-react-native#4039]
Currently native crash reports almost don't have any meaningful information
image

![Image](https://github.com/user-attachments/assets/8a5b59b0-f683-4bc9-97f8-148257b11633)

How can we improve it? Maybe add logcat logs, crash dumps, etc. Do we need to use native sdks for it?

**Comment by krystofwoldrich** [comment]
Hi @gavrilikhin-d,
thank you for the message,
the Sentry React Native SDK is using Sentry Android SDK which is using Sentry Native SDK.

Do the native crashes contain breadcrumbs and other context information?

Are you using Sentry Android Gradle Plugin to upload the native debug symbols?

https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#enable-sentry-agp

**Comment by gavrilikhin-d** [comment]
> Do the native crashes contain breadcrumbs and other context information?

Yes 

> Are you using Sentry Android Gradle Plugin to upload the native debug symbols?

No

**Comment by krystofwoldrich** [comment]
@gavrilikhin-d Thank you for the answer,

let us know if there is anything else we can help with. Or if you need any help setting up the `Sentry Android Gradle Plugin`.

**Comment by gavrilikhin-d** [comment]
@krystofwoldrich We have the following line in our `android/app/build.gradle`
```
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
```
Should we remove it?

**Comment by gavrilikhin-d** [comment]
@krystofwoldrich how to check if this plugin is working?

**Comment by gavrilikhin-d** [comment]
Here's an example of error after enabling SAGP. We still don't have source context, even in our kotlin code


![Image](https://github.com/user-attachments/assets/4623f9cd-d538-4212-af59-a2890080bb04)

**Comment by gavrilikhin-d** [comment]
I've figured out that you need to use additional configuration flag from https://docs.sentry.io/platforms/android/configuration/gradle/
```
includeSourceContext = true
```
