### ISSUE TITLE
Sentry Wizard adds invalid options to Yarn v2+ 

### ISSUE THREAD

**Issue by Julio-Hostmundo** [getsentry/sentry-react-native#4043]
**OS:**
- [ X ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ X ]  Android

**SDK:**
- [ X ]  `@sentry/react-native` (>= 1.0.0)
- [ X ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.30.0

**`react-native` version:** 0.75.2

**Are you using Expo?**
- [ ]  Yes
- [ X ]  No

**Are you using sentry.io or on-premise?**
- [ X ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

not implemented

---
**I have the following issue:**

I'm trying to implement the SDK in a React Native 0.75.2 project, however, I'm getting a strange error.

**Steps to reproduce:**

-Create an app 0.75.2
![Image](https://github.com/user-attachments/assets/37a38197-5500-4998-bfa6-acad505fbf34)

-Try using Sentry Wizard to install
![Image](https://github.com/user-attachments/assets/fcdae5a7-0694-45b3-a25e-1d3c00b04782)

**Comment by krystofwoldrich** [comment]
Thank you for the message.

This issue is fixed by https://github.com/getsentry/sentry-wizard/pull/652
