### ISSUE TITLE
Session replays recording while app is in background

### ISSUE THREAD

**Issue by hammoudma** [getsentry/sentry-react-native#4047]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 8.33.0

**`react-native` version:** 0.74.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: SENTRY_DSN,
      environment: SENTRY_ENVIRONMENT,
      _experiments: {
        replaysSessionSampleRate: 0,
        replaysOnErrorSampleRate: 1.0
      },
      integrations: [
        Sentry.mobileReplayIntegration({
          maskAllText: false,
          maskAllImages: false
        })
      ]
    });
```

---
**I have the following issue:**

I am getting hours-long replay sessions of the app idling in the background. Is there a way to disable that? 
I am assuming that that is also happening when the app is open and then the screen is locked. 

**Expected result:**

I only get replays of user sessions were the user is using the app.

**Comment by hammoudma** [comment]
Hi @krystofwoldrich 

Sorry I wasnt clear in the description, the replays I am getting are not of an error, they are just of the app idling for a long time. 


![Image](https://github.com/user-attachments/assets/d49ab6d4-ccb5-42e0-a405-86fe1c84cb1f)

For example, is there a way to get rid of these or limit the recording time

**Comment by krystofwoldrich** [comment]
@hammoudma Thank you for the explanation. I understand now.

**Comment by krystofwoldrich** [comment]
@brustolin @romtsn Does the current Replay length limit includes the inactive/paused replay time?

**Comment by brustolin** [comment]
Technically, yes, but this should not happen. Once it goes into the background for more than 30 seconds, we should not consider it the same session.

**Comment by krystofwoldrich** [comment]
Bump cocoa when https://github.com/getsentry/sentry-cocoa/pull/4303 is released.

**Comment by krystofwoldrich** [comment]
RN https://github.com/getsentry/sentry-react-native/releases/tag/5.34.0 contains the https://github.com/getsentry/sentry-cocoa/pull/4303 fix.

The current latest RN SDK version is https://github.com/getsentry/sentry-react-native/releases/tag/6.2.0
