### ISSUE TITLE
build issue with RN 0.75.2

### ISSUE THREAD

**Issue by gurbela** [getsentry/sentry-react-native#4052]
I was built on MacOS Sonoma 14.6.1 with new architect of react native enabled.

 "@sentry/react-native": "^5.31.0"

![Image](https://github.com/user-attachments/assets/9f18ee3b-b095-48c8-9662-2c6de54db249)

**Comment by kahest** [comment]
@gurbela thanks for the report, I reopened the original issue describing this: https://github.com/getsentry/sentry-react-native/issues/4036
