### ISSUE TITLE
Persistent Sentry Log - Request to Suppress or make conditional(Expo)

### ISSUE THREAD

**Issue by quememo** [getsentry/sentry-react-native#4053]
(Intended for Expo)

I have a problem regarding Sentry interaction with LogRocket.

In this [line of code](https://github.com/getsentry/sentry-react-native/blob/d738710951fdbc6536384475d13405e899692b32/ios/RNSentry.mm#L345) the message is always being logged. Could this be either removed or made conditional based on a debug flag?

Each time this appears, LogRocket recognizes it as an error and uploads a session recording to their servers, which floods my logs and causes me to reach my quota limit.

LogRocket captured logs that trigger the upload:
![Image](https://github.com/user-attachments/assets/da48d7fd-08e8-42be-b4ca-b72de5146bb2)

Related versions:
```
    "react": "18.2.0",
    "expo": "50.0.19",
    "@sentry/react-native": "5.20.0",
    "@logrocket/react-native": "1.32.0",
```

**Comment by quememo** [comment]
Asked for help in LogRocket support also already

**Comment by krystofwoldrich** [comment]
Hi @quememo,
thank you for the message,

yes this definitely can be guarded by the `debug: true`.
