### ISSUE TITLE
After installing Sentry with the wizard the events are not being reported

### ISSUE THREAD

**Issue by CH-SebastianEscalona** [getsentry/sentry-react-native#4079]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK version:** 5.31.1

**`react-native` version:** 0.74.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

---
**I have the following issue:**

[Description]

**Steps to reproduce:**
- Install sentry sdk using the wizard ```npx @sentry/wizard -s -i reactNative```
- Try capture an exception using the example given at the end of the wizard flow

**Actual result:**

Not seeing any events on the sentry dashboard

**Comment by CH-SebastianEscalona** [comment]
Yes, that's the code snippet I'm using. The version of the sentry is the 9.0.0. And yes the DSN is correctly set.

**Comment by krystofwoldrich** [comment]
Hi @CH-SebastianEscalona,
thank you,

can you share your `Sentry.init`, add `debug: true` and share the logs from JS console, Logcat and iOS Console?

**Comment by CH-SebastianEscalona** [comment]
Hi! @krystofwoldrich , sorry for the delay. Here are the logs thrown with `debug: true`

![Image](https://github.com/user-attachments/assets/a0f000c9-f75b-4782-bfcc-5029ddf19864)



My Sentry init is currently like this

```
Sentry.init({
  dsn: 'htttps://....',
  debug: true,
});
```

**Comment by mauripavan** [comment]
Hi, facing exactly same issue migrating from sentry.io to self-hosted. Any updated on that?

**Comment by kahest** [comment]
@mauripavan no update as of now. Which versions of the SDK and self-hosted Sentry are you using? Did you also use the Wizard in the same way described above?

**Comment by mauripavan** [comment]
Hi @kahest! These are the versions being used: 

self-hosted Sentry: 24.9.0.dev0
sentry/react-native": 5.32.0

And yes, I'm using the wizard in the same way described above.

**Comment by CH-SebastianEscalona** [comment]
@kahest any updates?

**Comment by kahest** [comment]
@CH-SebastianEscalona thanks for checking - that's strange, something should show up in debug logging. I'm not sure if something like this is built-in in Sentry, but in the cases I saw it was another networking issue, like firewalls blocking, or running the app locally on a device/simulator that can't connect to the network where the on-premise Sentry is hosted.

**Comment by CH-SebastianEscalona** [comment]
@kahest just to make sure, the stand alone version of the sentry is the 9.0.0 is this version supported by the current sdk (5.31.1) I'm working with?

**Comment by kahest** [comment]
@CH-SebastianEscalona thanks for highlighting this - I missed your Sentry version. You're right, since `@sentry/react-native` version 2+ the SDK uses the `envelope` endpoint that was introduced in version `20.6.0` of Sentry - see [docs](https://docs.sentry.io/platforms/react-native/migration/#from-1x-to-2x). 

Note that `20.6.0` is only [slightly newer](https://github.com/getsentry/sentry/blob/master/CHANGES#L2337) than `9.0.0` since we moved to CalVar with that version. More information on upgrading from v9 to v20 is available here: https://develop.sentry.dev/self-hosted/releases/#hard-stops
