### ISSUE TITLE
missing ucontext64_t type  Xcode Version 16.0 (16A242d)

### ISSUE THREAD

**Issue by hanwenbo** [getsentry/sentry-react-native#4097]
### Description

#ifdef __arm64__
#include <sys/_types/_ucontext64.h>
#    define UC_MCONTEXT uc_mcontext64
typedef ucontext64_t SignalUserContext;

https://github.com/getsentry/sentry-cocoa/pull/4244

**Comment by kahest** [comment]
Hey @hanwenbo which version of the SDK do you use? The issue should be fixed with `5.31.0` and newer.

**Comment by andandrej** [comment]
I can confirm it's working with version `5.32.0` on MacOS `15` and xCode `16.0`
