### ISSUE TITLE
Sentry.ReactNavigationInstrumentation is not a constructor

### ISSUE THREAD

**Issue by victorpavlenko** [getsentry/sentry-react-native#4099]
**OS:**
MacOS 15.1

**Platform:**
iOS 17.5

**SDK:**
@sentry/react-native 6.0.0-beta.1

**Are you using Expo?**
Yes

**Are you using sentry.io or on-premise?**
sentry.io

**Configuration:**

(`@sentry/react-native`)
```
"Sentry.ReactNavigationInstrumentation" is not a constructor
```

---
**I have the following issue:**

I was lucky enough to run this on the new OS 15 with Xcode 16
But now after a successful build it throws an error in the console

`App.tsx:34 Uncaught TypeError: Sentry.ReactNavigationInstrumentation is not a constructor`

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening this issue!
Was it working on prior versions?

on v6, you will need to use a different name, instead of 
````typscript
const reactNavigationIntegration = new Sentry.ReactNavigationInstrumentation();
```
you will need to use 
```
const reactNavigationIntegration = Sentry.reactNavigationIntegration();
```

Let me know if that works for you.

**Comment by victorpavlenko** [comment]
Where I can found v6 docs or something like this? Or it still in progress?

**Comment by c-emil** [comment]
@victorpavlenko https://docs.sentry.io/platforms/react-native/tracing/instrumentation/react-navigation/
