### ISSUE TITLE
TimeToDisplayProps.spanName is not used

### ISSUE THREAD

**Issue by sregg** [getsentry/sentry-react-native#4108]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

[TimeToDisplayProps.spanName](https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/timetodisplay.tsx#L24C3-L24C11) is not used.

I'd like to differentiate TTFDs when we show cached data vs TTFDs when there was no cached data. I was hoping I could use `spanName` to rename `time_to_full_display_cached` for when we used cached data.
Is there a better way to do that? I couldn't see how I could add a tag (e.g. `cached_data`) to that span either.

**Comment by lucas-zimerman** [comment]
Thank you for raising this issue! I will look into the best use case for your situation and get back to you shortly. I don’t have the answer at the moment, but I will check over the next few days.

**Comment by krystofwoldrich** [comment]
Hi @sregg,
you can use `Sentry.startTimeToInitialDisplaySpan()` and `Sentry.startTimeToFullDisplaySpan()` to access the Time to Display spans. These functions let you change the name and add the tags. 

They are public, but do not have documentation at the moment.

**Comment by sregg** [comment]
> Hi [@sregg](https://github.com/sregg), you can use `Sentry.startTimeToInitialDisplaySpan()` and `Sentry.startTimeToFullDisplaySpan()` to access the Time to Display spans. These functions let you change the name and add the tags.
> 
> They are public, but do not have documentation at the moment.

Thanks @krystofwoldrich but I have a hard time understanding how to use this.
Aren't those already used internally by the SDK? What happens if I call them in my own code, would that override the duration?

**Comment by krystofwoldrich** [comment]
Hi @sregg,
no worries.

Yes, these function are also used internally. 

No, the duration is not changed if used together with navigation integration.

--- 

Example usage:

```js
import * as Sentry from '@sentry/react-native';

export function Component() {
  // Navigation Span can only have on TTID span. This function will return the existing TTID span if created by the
  // navigation integration or creates new one. By default the start time is the start of the navigation.
  const ttidSpan = Sentry.startTimeToInitialDisplaySpan({
    name: 'My New Time to Initial Display Span',
    isAutoInstrumented: true, // false by default, false means `<Sentry.TimeToInitialDisplay record={true}>` will be used to
                              // true means we want the span to be ended automatically by the navigation integration
  });

  // Navigation Span can only have on TTFD span. This function will return the existing TTFD span if already created
  // otherwise creates a new one. By default the start time is the start of the TTID span.
  const ttfdSpan = Sentry.startTimeToFullDisplaySpan({
    name: 'My New Time to Full Display Span',
  });

  return (
    <Sentry.TimeToFullDisplay record={true}>
      <View>
        <Text>My Component</Text>
      </View>
    </Sentry.TimeToFullDisplay>
  );
}
```

**Comment by sregg** [comment]
Am I able to query for span attributes in dashboards?
Something like this:
![Image](https://github.com/user-attachments/assets/e1f70f93-d0c6-4e1e-aab8-cf334c0a5025)
