### ISSUE TITLE
Sentry silently fails to add task to gradle if bundleTask.name contains a "-"

### ISSUE THREAD

**Issue by lindroth** [getsentry/sentry-react-native#411]
OS:
- [x]  Windows
- [x]  MacOS
- [x]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.10.0
3.5.2
react-xxxxx@8.0.6 home/me/project
├── babel-cli@6.26.0
├── base-64@0.1.0
├── buffer@5.1.0
├── color@3.0.0
├── i18next@9.1.0
├── immutable@3.8.2
├── moment@2.22.1
├── moment-timezone@0.5.17
├── prop-types@15.6.1
├── react@16.2.0
├── react-native@0.53.0
├── react-native-code-push@5.3.3
├── react-native-device-info@0.12.1
├── react-native-google-analytics@1.3.2
├── react-native-linear-gradient@2.4.0
├── react-native-sentry@0.36.0
├── react-native-vector-icons@4.3.0
├── react-native-view-shot@2.3.0
├── react-navigation@1.5.12
├── react-navigation-redux-helpers@1.0.7
├── react-redux@5.0.7
├── redux@3.7.2
├── redux-persist-transform-immutable@4.3.0
└── reselect@3.0.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```
---
I have following issue:
Sentry silently fails to add task to gradle if bundleTask.name contains a "-"
Description goes here ...
I noticed that get sentry stopped to upload mapping files during the bulid process. After some digging I found that this had started to happen after we changed our outputFileName.

In sentry.gradle there is an regexp that looks like this:
```
  Pattern.compile("bundle([A-Z][A-Za-z0-9]+)JsAndAssets")
```
This fails if the outputFileName contains a "-", this might be okay, but the scary part is that you do not get a warning or a failed build when this happens. The mapping files will just stop to be uploaded to the server. 

**Steps to reproduce:**
Create an app with an "-" in the outputFileName.

**Actual result:**
The sentry gradle task fails to be created and is not run. No mapping files is uploaded to sentry.

**Expected result:**
This should work, or at least the sentry build task should fail with an warning. 

- Result

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
