### ISSUE TITLE
Undefined symbols for architecture x86_64 in xcode 16

### ISSUE THREAD

**Issue by thien0110** [getsentry/sentry-react-native#4110]
### Description

**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.24.3

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

![Image](https://github.com/user-attachments/assets/7dec008e-e943-4333-8e7e-daba308d622f)

**Comment by kahest** [comment]
Please follow the steps in https://github.com/getsentry/sentry-react-native/issues/4095#issuecomment-2358568215 and let us know if that resolved the issue

**Comment by thien0110** [comment]
> Please follow the steps in [#4095 (comment)](https://github.com/getsentry/sentry-react-native/issues/4095#issuecomment-2358568215) and let us know if that resolved the issue

it worked!
thank for your help!
