### ISSUE TITLE
Latest tag in NPM has gone backwards to 5.24.3

### ISSUE THREAD

**Issue by johnf** [getsentry/sentry-react-native#4111]
### Description

I'm sorry for using the blank template, but it's not a typical bug.

I noticed that the latest tag is pointing at 5.24.3. I'm pretty sure it previously pointed at 5.33.0, as that is what I have now (I use yarn upgrade-interactive for upgrades)

I think a backport on the 5.24 branch has caused the latest tag to be updated.

**Comment by kahest** [comment]
@johnf thanks for reporting! We just released [5.33.1](https://github.com/getsentry/sentry-react-native/releases/tag/5.33.1) to address this
