### ISSUE TITLE
App crash when setup sentry I use react native bare with expo plugin (Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf9000000000018 in tid 3258 (pool-9-thread-1))

### ISSUE THREAD

**Issue by wogno** [getsentry/sentry-react-native#4112]
**OS:**
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.75.3

**Are you using Expo?**
- [x ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "https://xxxx8",
  // Set tracesSampleRate to 1.0 to capture 100% of transactions for tracing.
  // We recommend adjusting this value in production.
  tracesSampleRate: 1.0,
  _experiments: {
    // profilesSampleRate is relative to tracesSampleRate.
    // Here, we'll capture profiles for 100% of transactions.
    profilesSampleRate: 1.0,
  },
  // integrations: [
  //   new Sentry.ReactNativeTracing({
  //     routingInstrumentation,
  //   }),
  // ]
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**

[Description]

After integrate sentry with wizrad my android app crash after add sentry init and sentry wrap(App)

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

--------- beginning of crash
09-23 00:01:53.389  3183  3258 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf9000000000018 in tid 3258 (pool-9-thread-1), pid 3183 (com.xxxx.app)
09-23 00:01:54.041  3183  4196 D TrafficStats: tagSocket(166) with statsTag=0xffffffff, statsUid=-1

**Expected result:**

[Expected result]

**Comment by kahest** [comment]
@wogno we need more information to work on this: which versions of `@sentry/react-native` and Expo do you use? Does the crash occur every time, directly at startup? Can you share link to the issue on sentry.io? (you can send it to karl.struggl@sentry.io if you prefer)

**Comment by wogno** [comment]
App crashed at started everytime I decided to uncomment sentry part. 

I use react native 0.75.3 and expo 51. 

Expo is used only for expo updates. 

I just follow documentation without extra code and any error is send to the sentry dashboard.

**Comment by kahest** [comment]
@wogno which version of `@sentry/react-native` (Sentry's React Native SDK) are you using? The current version is 5.33.1, can you try that?

**Comment by wogno** [comment]
My current sentry "@sentry/react-native": "^5.24.3", I will tried 5.33.1 and let you know. For more information new architecture and bridgless are enabled.

**Comment by wogno** [comment]
@kahest Thanks upgrade version to latest, work without any error

**Comment by kahest** [comment]
I'm closing this for now. If anyone else encounters this, please add a reply.
