### ISSUE TITLE
Init sentry after app startup in Expo workflow

### ISSUE THREAD

**Issue by andresmartinezstay** [getsentry/sentry-react-native#4115]
Right now, the sentry SDK is initialized in the JS layer, meaning that crashes happening before the JS layer initialization are not being reported. This makes detecting bugs due to native dependencies hard to track, there should be an option in the config plugin to initialize the SDK in the native side patching the `didFinishLaunchingWithOptions` and `MainApplication.onCreate` calls

**Comment by kahest** [comment]
@andresmartinezstay thanks for getting in touch - this makes a lot of sense and we have https://github.com/getsentry/sentry-react-native/issues/3608 open to improve on this holistically. If you feel your suggestion is not captured in this issue, please feel free to add there. I'm closing this for now (but we might want to re-open and treat it as sub-issue of the other one).
