### ISSUE TITLE
Fix concurrent runs with Sentry Babel transformer

### ISSUE THREAD

**Issue by feidaZhang** [getsentry/sentry-react-native#4121]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.30.0

**`react-native` version:** 0.72.12

**Are you using Expo?**
- [ ]  Yes
- [x]  No

---
**I have the following issue:**

After integrating `withSentryConfig` in the `metro.config.js`, `annotateReactComponents` is true, we found that when building iOS application through Xcode in debug mode, the `.sentry/. defaultBabelTransformerPath` file was first created and then deleted before the build was completed. **However, when loading the JS Bundle, sentry tried to read the file again and threw an error.**

**Actual result:**

![Image](https://github.com/user-attachments/assets/f5ab5ffc-9e97-4c0d-9f10-d9439b95c2dd)

**Expected result:**

no error

**Comment by feidaZhang** [comment]
if i comment this line. There is no error but the file can not be deleted automatically.
```
function withSentryBabelTransformer(config) {
    const defaultBabelTransformerPath = config.transformer && config.transformer.babelTransformerPath;
    utils_1.logger.debug('Default Babel transformer path from `config.transformer`:', defaultBabelTransformerPath);
    if (!defaultBabelTransformerPath) {
        // This has to be console.warn because the options is enabled but won't be used
        // eslint-disable-next-line no-console
        console.warn('`transformer.babelTransformerPath` is undefined.');
        // eslint-disable-next-line no-console
        console.warn('Sentry Babel transformer cannot be used. Not adding it...');
        return config;
    }
    if (defaultBabelTransformerPath) {
        (0, sentryBabelTransformerUtils_1.saveDefaultBabelTransformerPath)(defaultBabelTransformerPath);
        process.on('exit', () => {
             // comment this line
            // (0, sentryBabelTransformerUtils_1.cleanDefaultBabelTransformerPath)();
        });
    }
    return Object.assign(Object.assign({}, config), { transformer: Object.assign(Object.assign({}, config.transformer), { babelTransformerPath: require.resolve('./sentryBabelTransformer') }) });
}
```

**Comment by feidaZhang** [comment]
It's my device info.
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Model Number:	Z11C000BPCH/A
  Chip:	Apple M1

**Comment by feidaZhang** [comment]
> Hello [@feidaZhang](https://github.com/feidaZhang) 👋 thank you for your report and the provided information. I debugged the issue with the reported configuration (SDK version: `5.30.0`, react-native version: `0.72.12`) but wasn't able to reproduce. Could you set the log level to debug: `export SENTRY_LOG_LEVEL=debug` and provide us with some extra logs from metro E.g.
> 
> ```
> Sentry Logger [debug]: Default Babel transformer path from `config.transformer`: [TRANSFORMER_PATH]
> Sentry Logger [debug]: Saved default Babel transformer path
> ...
> Sentry Logger [debug]: Loading default Babel transformer from [TRANSFORMER_PATH]
> Sentry Logger [debug]: Cleaned default Babel transformer path
> ✨  Done in 7.23s.
> ```
> 
> Do you see the [`Cleaned default Babel transformer path`](https://github.com/getsentry/sentry-react-native/blame/5.30.0/src/js/tools/sentryBabelTransformerUtils.ts#L41) before [metro termination](https://github.com/getsentry/sentry-react-native/blob/5.30.0/src/js/tools/metroconfig.ts#L117)?
> 
> We also noticed that the provided screenshot is from the macOS app. Could you confirm if you are building the iOS or macOS app with XCode? Have you made any other customisations in your Xcode setup?

![Image](https://github.com/user-attachments/assets/052de070-580b-457f-b4e6-cdcddfed4a43)
hi, there are logs i got. I built the application with Xcode, i don't think i made some customisations on setup. One of my colleagues said he has no issue with Apple Intel. **However, it happened on Apple M1.**

If i set `annotateReactComponents:false` on metro.config.js, there is no issue also.

**Comment by antonis** [comment]
Thank you for sharing the debug logs @feidaZhang 🙇 
My understanding from the last log ([`Cleaned default Babel transformer path`](https://github.com/getsentry/sentry-react-native/blame/5.30.0/src/js/tools/sentryBabelTransformerUtils.ts#L41)) is that that the [Metro server has stopped](https://github.com/getsentry/sentry-react-native/blob/5.30.0/src/js/tools/metroconfig.ts#L117). Could you share more details on how you start the Metro server and if it is running when the error occurs?

**Comment by feidaZhang** [comment]
@antonis 
yeah, I also noticed [Metro server has stopped](https://github.com/getsentry/sentry-react-native/blob/5.30.0/src/js/tools/metroconfig.ts#L117). 
The metro server is still running and show the errors when it happens.
I tried to start the metro before building using Xcode, I also tried to building the app using Xcode directly.However, I always get the errors.
**Did you build app with Debug executable on Xcode?** I enabled it.

**Comment by krystofwoldrich** [comment]
Hi @feidaZhang,
from the Xcode logs I see you are building debug version of your application, during debug builds Metro is by default not executed, as it's expected to load bundle from the running development server.

But in your case metro is executed, which causes deletion of the file and consequently the error in the development server running outside of Xcode.

Have you changed this behaviour intentionally, otherwise it might indicate indicate an error in the build phase.

**Comment by krystofwoldrich** [comment]
The current impl of `.sentry/.defaultBabelTransformerPath` doesn't work with multiple parallel build/dev server running.

**Comment by krystofwoldrich** [comment]
We can enable multiple parallel build simply just by scoping the `./sentry` using timestamp or unique generated hash.

`./sentry/${timestamp/hash}/.defaultBabelTransformerPath`

**Comment by johnf** [comment]
I've noticed this directory and file started appearing in the last few weeks. Is it fine to add it to `.gitignore`?

**Comment by krystofwoldrich** [comment]
@johnf Yes, can be ignored, it's used for tmp files during the JS bundling process.

**Comment by fediru-gloat** [comment]
Also faced this issue and it's pretty annoying. I just tried to open development build from Expo cli by pressing "i" and it throws an error. It should probably generated in runtime on dev builds if it's missed or if it's missed it shouldn't block app start?

**Comment by krystofwoldrich** [comment]
Hi @fediru-gloat, this will be resolved by https://github.com/getsentry/sentry-react-native/pull/4298
