### ISSUE TITLE
@sentry/browser prototype pollution vulnerability

### ISSUE THREAD

**Issue by daveallie** [getsentry/sentry-react-native#4148]
### Description

The latest version of `@sentry/react-native` package (5.33.1) depends on `@sentry/browser@7.119.0` which has a reported vulnerability: https://github.com/advisories/GHSA-593m-55hh-j8gv

Are there plans to release a patch version of 5.x to include a patched version of `@sentry/browser`? Or will we have to wait for 6.x to get the `@sentry/browser` 8.x to address the vulnerability?

**Comment by krystofwoldrich** [comment]
Hi @daveallie,
thank you for the message,

yes, this will be fixed also in JS v7 and so in RN v5.

JS Release https://github.com/getsentry/sentry-javascript/releases/tag/7.119.1
RN Release will follow shortly
