### ISSUE TITLE
Error captureException(raven-js/src/raven)

### ISSUE THREAD

**Issue by manuhook** [getsentry/sentry-react-native#418]
Hello,

I'm having a lot of this error on android devices only (nothing on ios) :

Error captureException(raven-js/src/raven)
Non-Error exception captured with keys: code, column, data, line, message…

![image](https://user-images.githubusercontent.com/531834/40845551-57cb18c2-65b7-11e8-9e5e-67ea37c529f8.png)

ADDITIONAL DATA
__serialized__ | {"code":"error_not_connected","column":1758,"sourceURL":"index.android.bundle","line":604,"data":{"status":400},"message":"Vous n'êtes pas connecté."}
-- | --

I'm using sentry-react-native 0.36.0

Do you have an idea what's this error means ?

Thank you

**Comment by fsarcanskyvm** [comment]
@manuhook could you fix this? I'm in the same situation and I have no idea why could be happening

**Comment by richardshergold** [comment]
Just started using Sentry and I'm seeing this too

**Comment by HazAT** [comment]
Hey,
Is this the top most frame of your error?
Also, there is an issue with source maps on Android which could lead to reporting the incorrect line number.
Fix for this is here:  https://github.com/react-community/jsc-android-buildscripts

**Comment by KevinStong** [comment]
Seeing this error all over in our react.js project as well... any ideas?

**Comment by sercanov** [comment]
I also having this a lot, eating most of my event quota. 
I suppose it is related with handlePromiseRejection config

<img width="1086" alt="screen shot 2018-11-01 at 10 32 36" src="https://user-images.githubusercontent.com/10291644/47838854-b03cc780-ddc1-11e8-84a6-c0977fefa352.png">

**Comment by augustl** [comment]
This seems to happen to us as well, every time the `handlePromiseRejection` functionality triggers. A lot of our promises are rejected with plan JS errors, not full Error objects.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
