### ISSUE TITLE
6.0.0 release notes have broken import statements

### ISSUE THREAD

**Issue by johnf** [getsentry/sentry-react-native#4190]
### What React Native libraries do you use?

React Navigation, React Native without Frameworks, RN New Architecture, React Native Web

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.0.0

### How does your development environment look like?

N/A

### Sentry.init()

N/A

### Steps to Reproduce

The examples in the GitHub release notes for 6.0.0 have
```js
import Sentry from '@sentry/react-native'
```
this should be
```js
import * as Sentry from '@sentry/react-native'
```

### Expected Result

N/A

### Actual Result

n/A

**Comment by krystofwoldrich** [comment]
Hi @johnf
thank you for the message. 

Fixed at https://github.com/getsentry/sentry-react-native/releases/tag/6.0.0
And https://github.com/getsentry/sentry-react-native/pull/4192
