### ISSUE TITLE
Pod Install Error with 8.39.0

### ISSUE THREAD

**Issue by laynef** [getsentry/sentry-react-native#4213]
### What React Native libraries do you use?

Expo (mobile only)

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

8.39.0

### How does your development environment look like?

@sentry/react-native version: ^6.1.0
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.39.0'

![Image](https://github.com/user-attachments/assets/16a4fc73-c673-45b0-b2e8-50d32918e597)

### Sentry.init()

  Sentry.init({
    dsn: "https://ecd6223aeac5ee0a5fdf14617ba3b2ed@o4507245944569856.ingest.us.sentry.io/4507245958397952",
    tracesSampleRate: 1.0,
    profilesSampleRate: 1.0,
    integrations: [navigationIntegration],
  });

### Steps to Reproduce

Create a new expo project and add sentry for ios and android with the latest version

### Expected Result

It should work and build

### Actual Result

It doesn't build. Complains about a previous version with a pod install error.
`pod repo update` nor `pod install --repo-update` work... 

It's just broken on the new version of Sentry

**Comment by krystofwoldrich** [comment]
Hi @laynef,
thank you for the message,

could you share more details about the `pod repo update` not working?

Does is show any errors?

Have you tried `pod update Sentry`?

**Comment by richardReitz** [comment]
`pod update Sentry/HybridSDK` works for me.

**Comment by krystofwoldrich** [comment]
Thank you for the feedback @richardReitz

@laynef if it's still an issue, please comment here we can reopen this.

**Comment by AryanJ-NYC** [comment]
For anyone running Expo, going back down to 6.0.0 worked for me.
