### ISSUE TITLE
Linking react-native-sentry ios dependency fails

### ISSUE THREAD

**Issue by sfreeman28** [getsentry/sentry-react-native#426]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.9.4
5.6.0
mytours@0.0.1 /Users/sfreeman/workspace/react/mytours
├── @types/react-native-vector-icons@4.6.1
├── @types/react-navigation@2.0.5
├── react@16.3.1
├── react-native@0.55.4
├── react-native-camera@1.1.4
├── react-native-extended-stylesheet@0.8.1
├── react-native-localization@1.0.9
├── react-native-qrcode-scanner@1.0.1
├── react-native-sentry@0.37.1
├── react-native-vector-icons@4.6.0
├── react-navigation@2.3.1
├── react-navigation-material-bottom-tabs@0.2.0
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-saga@0.16.0
└── typescript-fsa-reducers@0.4.5
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

When running `link` I get an error and it fails.

**Steps to reproduce:**
Simple run `react-native link react-native-sentry`

**Actual result:**
```
rnpm-install info Linking react-native-sentry ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: str.replace is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

str.replace is not a function
```

**Expected result:**
For the linking to work successfully

I then tried to manually link (for Android) by following instructions here:
https://docs.sentry.io/clients/react-native/manual-setup/

After making the required changes I run `react-native run-android` and get the following error:
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/sfreeman/workspace/react/mytours/node_modules/react-native-sentry/sentry.gradle' line: 176

* What went wrong:
Execution failed for task ':app:bundleDevDebugJsAndAssets'.
> java.lang.NullPointerException (no error message)
```

One thing that is missing is the manual linking instructions do not say how to generate the `sentry.properties` file. This _may_ be the reason behind by error.

Can someone please help me fix my linking issue, or tell me how to generate the sentry.properties files manually.
Thanks!

**Comment by acomito** [comment]
@sfreeman28 I'm about to undertake adding this package (done it in expo, not in vanilla RN).

Did you ever figure this out? Anything to look out for before I start? Thanks!

**Comment by sfreeman28** [comment]
@acomito I could not figure out my auto linking issue, but it happened for me on other libraries too so I do not think its an issue just with sentry.

I ended up manually linking. If you need to do the same I just needed to create a sentry.properties file with the following content:

```
defaults.url=https://sentry.io/
cli.executable=node_modules/@sentry/cli/bin/sentry-cli
defaults.project=xxxx
defaults.org=xxxx
auth.token=xxxx
```

I will leave this issue open until I can fix my auto linking problem then post a fix here in case it happens to others

**Comment by acomito** [comment]
@sfreeman28 I had a similar error message that ended up being an unmerged line of code in my manifest, similar to this:

https://github.com/facebook/react-native/issues/12216

**Comment by acomito** [comment]
@sfreeman28 Thanks for the tip. did you create sentry.properties at the root level of your project?

**Comment by sfreeman28** [comment]
@acomito I put mine in the android folder. As I have product flavors I also had to name them like
`sentry-flavorA-debug.properties`

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
