### ISSUE TITLE
tvOS - Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_RNSentry"

### ISSUE THREAD

**Issue by ryanvanderpol** [getsentry/sentry-react-native#428]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.1.2
5.6.0
myapp@1.0.5 /Users/admin/Documents/projects/myapp
├── lodash@4.17.10
├── react@16.3.1
├── react-native@0.55.4
├── react-native-keep-awake-tvos@2.0.4
├── react-native-sentry@0.38.0
├── react-redux@5.0.7
├── redux@4.0.0
├── redux-persist@5.10.0
├── redux-thunk@2.3.0
└── shortid@2.2.8

```

---

I've used Sentry successfully in other projects, so I'm pretty sure I've followed all the setup instructions correctly.  When I attempt to build a tvOS target, I receive a build error.  I've tried manually adding libRNSentry.a to the "Link Binary with Libraries" phase but that just results in other errors.

I'm pretty confident this is specific to tvOS targets because if I switch XCode to build my iOS target it works fine (and it seems likely that tvOS has been neglected).

**Steps to reproduce:**
- Create a new React Native project
- Install Sentry per [these instructions](https://docs.sentry.io/clients/react-native/)
- Open XCode (I'm using Version 9.2 (9C40b))
- Change build target to tvOS and run a build

**Actual result:**
- The following build error occurs:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RNSentry", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
```

**Expected result:**
- No build errors

**Comment by HazAT** [comment]
We do not currently have support for tvOS but we will add it in a future version, sorry :|

**Comment by ndillon1** [comment]
@HazAT when will tvOS support be added to react-native-sentry ?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
