### ISSUE TITLE
Failed to resolve plugin for module "@sentry/react-native/expo"

### ISSUE THREAD

**Issue by nawbar23** [getsentry/sentry-react-native#4283]
### What React Native libraries do you use?

Expo (mobile only) (52.0.7)

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.1.0

### How does your development environment look like?

(node:14112) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  Memory: 16.51 GB / 31.69 GB
Binaries:
  Node:
    version: 22.11.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.9.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: ^15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Sentry.init()

Sentry.init({
  dsn: "https://ae458ee624bf9a970fdc32e7634a536b:f43243fb1d8e637a71e7125ca4fa7b22@o4506953980444672.ingest.us.sentry.io/4506953985753088",
  tracesSampleRate: 0.2,
  enabled: !__DEV__,
});

### Steps to Reproduce

1. Run npx expo start --tunnel

### Expected Result

Successful build

### Actual Result

Starting project at xxx
env: load .env.local
env: export SENTRY_AUTH_TOKEN
**PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to xxx**

**Comment by oussamakh96** [comment]
I got the same error

**Comment by kebabmestarn** [comment]
Facing the same issue with trying to upgrade to Expo SDK 52

**Comment by GamingHazard** [comment]
> Facing the same issue with trying to upgrade to Expo SDK 52

as a matter of fact, implimented sentry in my 49 expo SDK and it worked, but i think its just a bug that hasnt yet brrn fixed by sentry

**Comment by oussamakh96** [comment]
Worked only on SDK 51 but I got the error when I upgrade to SDK 52

**Comment by krystofwoldrich** [comment]
Hello everyone,

thank you for letting us know, sadly we have not reproduced this yet,

can you check if the `node_modules/@sentry/react-native/expo.js` exists in your node_modules?

**Comment by GamingHazard** [comment]
When i try installing the @sentry/react-native/expo app, it is displayed as
undefined in my package. Json and the error passists until i edit the app.
Json plugin object and change the @sentry/react-native/expo  to
sentry/react-native then the error wont show up again

**Comment by GamingHazard** [comment]
I think the @sentry/react-native/expo  library has a bug that needs to be
fixed or its just not compatible with the expo-doctor Library

**Comment by henribru** [comment]
I'm having this problem on Windows, but it works fine on Linux in WSL2

**Comment by Ajaymaurya1008** [comment]
I had the same issue on windows, but on Linux and Mac, it works fine

**Comment by nawbar23** [comment]
@krystofwoldrich in my case `node_modules/@sentry/react-native/expo.js` exists
and contains:
`ode_modules/@sentry/react-native/expo.js`

**Comment by jerone** [comment]
Issue created on the Expo repo: https://github.com/expo/expo/issues/33054

**Comment by Abdeldmh** [comment]
Hello, when will it be released please ?

**Comment by krystofwoldrich** [comment]
Thank you @jerone for opening the Expo issue and supplying the repro.

@Abdeldmh The fix was merged in https://github.com/expo/expo/issues/33054 and likely will be in the next Expo SDK hotfix release. 

At the moment you can use `@sentry/react-native` in the `app.json` or use JS/TS app configuration where you can directly import `@sentry/react-native/expo`. But note that in that case `sentry-expo-upload-sourcemaps` won't automatically use the org and project specified.

---

Note: `@sentry/react-native/expo` is not a standalone package, but sub export from `@sentry/react-native`.

**Comment by krystofwoldrich** [comment]
Waiting for release of https://github.com/expo/expo/pull/33106 before closing this issue.

**Comment by krystofwoldrich** [comment]
The changes were released in https://www.npmjs.com/package/expo/v/52.0.9
