### ISSUE TITLE
Not getting all the error info ( error coming from the index bundle )

### ISSUE THREAD

**Issue by Rolando-Barbella** [getsentry/sentry-react-native#431]
OS:
- [x]  MacOS
_Platform:_
- [x]  iOS
---
I just started testing Sentry for my company project ( I'm new to the tool ).

**I have following issue:**
 
I don't see the SDK line error like is shown on the readme image, why I don't get
the original and minified tags? The error seems to come from the bundle index, not the specific JS file like expected.

* We have a paid account ( don't know if that makes a difference) 

<img width="1074" alt="sentry" src="https://user-images.githubusercontent.com/6339809/42090155-22d1cf52-7b98-11e8-9424-cf35be96eb19.png">

- react-native 0.49.0
- sentry-cli 1.32.2 
- react-native-sentry 0.38.1
- [sentry/wizard](url) 0.10.2

```
Sentry.config('https://123@sentry.io/123',{
    captureUnhandledRejections: true
}).install();

```
**Expected result:**
- Get the proper line of the error and file name.

**Comment by zigav** [comment]
I am having the same issue just by calling `Sentry.init()`. Any ideas on how to go about this?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
