### ISSUE TITLE
all unique promise rejection errors belong to a single issue

### ISSUE THREAD

**Issue by n1ru4l** [getsentry/sentry-react-native#433]
OS:
- [x]  Windows
- [x]  MacOS
- [x]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
Not important to bug
```

Config:

```
Sentry.config(SENTRY_DSN, {
    // prettier-ignore
    release: `${VersionNumber.bundleIdentifier}_${VersionNumber.appVersion}_${VersionNumber.buildVersion}`
  }).install()
```

---
I have following issue:

Unhandled Promise rejection Errors with different causes are merged and displayed as a single issue in the Web Interface.

**Steps to reproduce:**

Do multiple Promise Rejections in different parts of the application with different Error Instances/Messages

**Actual result:**

All Events are listed as Promise Rejections Events under a single issue

**Expected result:**

Each unique Promise Rejection with its unique error should be listed as a separate issue with its events

**Comment by HazAT** [comment]
Thanks for reporting this, we are currently in the process of rewriting the base of the SDK and probably not fix this right now. Still, I will leave this issue open to have a reminder but don't expect a fix for this soon :/

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
