### ISSUE TITLE
SENTRY_SKIP_AUTO_RELEASE=true does not seem to work

### ISSUE THREAD

**Issue by PrajTS** [getsentry/sentry-react-native#4339]
### What React Native libraries do you use?

React Navigation, Hermes, Expo (mobile only)

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.3.0

### How does your development environment look like?

System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 127.27 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.4
    path: /private/var/folders/zq/sl_c3rhs01v67lb_6ff_9thr0000gn/T/xfs-f5668e85/node
  Yarn:
    version: 4.5.1
    path: /private/var/folders/zq/sl_c3rhs01v67lb_6ff_9thr0000gn/T/xfs-f5668e85/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.4/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Sentry.init()

Sentry.init({
    dsn: "https://....ingest.us.sentry.io/...",
    attachStacktrace: true,
    tracesSampleRate: 1.0,
  });

### Steps to Reproduce

While creating a local release build, I don't want to automatically upload a build. I'm running the command 
`SENTRY_SKIP_AUTO_RELEASE=true ./gradlew assembleRelease`

The build fails as it still tries to upload the source maps. The SENTRY_AUTH_TOKEN is not set as an environment variable here.

### Expected Result

The task: :app:uploadSentryNativeSymbolsForRelease FAILED should not be executed

### Actual Result

> Task :app:uploadSentryNativeSymbolsForRelease FAILED
  INFO    2024-12-03 00:22:45.627975 +05:30 Loaded file referenced by SENTRY_PROPERTIES (/Users/prajwalts/Documents/delta/delta-frontend/apps/mobile-india/android/sentry.properties)
error: Auth token is required for this request. Please run `sentry-cli login` and try again!

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

FAILURE: Build failed with an exception.

**Comment by krystofwoldrich** [comment]
Hi @PrajTS,
thank you for the message,

the Sentry RN tooling doesn't use `SENTRY_SKIP_AUTO_RELEASE `, please replace it with `SENTRY_DISABLE_AUTO_UPLOAD=true` to skip the source maps and native symbols upload tasks.

For more details visit https://docs.sentry.io/platforms/react-native/sourcemaps/#disable-automatic-upload
