### ISSUE TITLE
setVersion Not Working on iOS or Cannot Call setVersion Early Enough on iOS

### ISSUE THREAD

**Issue by HAMPLENI** [getsentry/sentry-react-native#434]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v6.11.1
3.10.10
/Users/hampleni
└── (empty)
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
    logLevel: SentryLog.Error
}).install()
```

---
I have the following issue:

react-native-sentry@0.31.0

As documented [here](https://docs.sentry.io/clients/react-native/codepush/), I am trying to send the CodePush version to Sentry using the following:

`Sentry.setVersion(update.appVersion + "-codepush:" + update.label);`

It works on Android.

On iOS, I have verified that `update.appVersion + "-codepush:" + update.label` is the correct string.  I do get an error report in Sentry, however for the version it just says "1.7", which I believe is what it would say by default if I did not call `setVersion`.  It also seems that the error report only shows up in the Sentry web app when I relaunch the app after the error occurred.  Perhaps the code leading up to the `setVersion` call hasn't had time to execute before the error is reported to Sentry on app relaunch.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by zmnv** [comment]
Sentry.setVersion now is undefined. WHy?

@HazAT

**Comment by HazAT** [comment]
@zmnv Support of this function has been dropped in the major bump, please use `setRelease` instead

**Comment by elmotan95** [comment]
@HazAT Please update the docs here https://docs.sentry.io/clients/react-native/codepush/
It's still using `setVersion`.

Thanks!
