### ISSUE TITLE
[iOS, Xcode, Codemagic] Failed to find file referenced by SENTRY_PROPERTIES

### ISSUE THREAD

**Issue by abifdhllh** [getsentry/sentry-react-native#4342]
### What React Native libraries do you use?

React Native without Frameworks

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

5.36.0

### How does your development environment look like?

OS: Mac OS Sequoia 15.1.1
Node: 23.3.0
Yarn: 1.22.22
react: 18.2.0
react-native: 0.71.19
hermesEnabled: true
newArchEnabled: false

### Sentry.init()

```js
Sentry.init({
    dsn: Config.SENTRY_DSN,
    tracesSampleRate: 1.0,
    _experiments: {
      profilesSampleRate: 1.0,
    },
    // debug: __DEV__,
    environment: Config.ENVIRONMENT,
    release: DeviceInfo.getVersion(),
    dist: DeviceInfo.getBuildNumber(),
    integrations: [
      new Sentry.ReactNativeTracing({
        routingInstrumentation,
        enableUserInteractionTracing: true,
      }),
    ],
    attachScreenshot: true,
    enabled: isProduction || isStaging,
  });
```

### Steps to Reproduce

This error occurs only when using Codemagic workflow as my CI/CD tools for iOS application but when I build iOS app in my local Mac it run smoothly. Here is the step I ran in Codemagic:

1. Create the `sentry.properties` file to ios folder by running this command

```
echo "$SENTRY_PROPERTIES" > ios/sentry.properties
```

![Image](https://github.com/user-attachments/assets/539c463b-21f9-4b2a-8def-692b1b9aa230)

2. Run npm install
3. Run pod install
4. Build iOS using this command

```
xcode-project build-ipa \
  --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
  --scheme "$XCODE_SCHEME"
```

### Expected Result

In my local the Archive process should success and then the Organizer should be shown

### Actual Result

```
❌  error: sentry-cli - To disable native debug files auto upload, set SENTRY_DISABLE_AUTO_UPLOAD=true in your environment variables. Or to allow failing upload, set SENTRY_ALLOW_FAILURE=true



❌  error: sentry-cli -   WARN    2024-12-04 05:39:33.119800 +00:00 Failed to find file referenced by SENTRY_PROPERTIES (auth.token=censoredtoken



❌  error: An organization ID or slug is required (provide with --org)
```

![Image](https://github.com/user-attachments/assets/8a2da8a3-d444-4d3e-913c-fffa2c623aa3)

**Comment by krystofwoldrich** [comment]
Hi @abifdhllh,
thank you for the message,
I see that are creating the `ios/sentry.properties` file from env called `SENTRY_PROPERTIES`.

Sentry expects the `SENTRY_PROPERTIES` be an alternative path to the properties file. Since in your case this env is filled with the file content the Sentry CLI fails to find the file.

Please rename the `SENTRY_PROPERTIES` env to `MY_APP_PREFIX_SENTRY_PROPERTIES_CONTENT` for example. Let us know if this worked for you.

**Comment by abifdhllh** [comment]
Wow it works! I almost spend all day trying to solve this. Thanks for the help! @krystofwoldrich
