### ISSUE TITLE
Disabling enableCaptureFailedRequests does not work for iOS

### ISSUE THREAD

**Issue by vtoupet** [getsentry/sentry-react-native#4343]
### What React Native libraries do you use?

React Navigation, Hermes

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.3.0

### How does your development environment look like?

System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 438.41 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman:
    version: 2024.09.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.11
    wanted: 0.73.11
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Sentry.init()

Sentry.init({
    dsn: SENTRY_DSN,
    normalizeDepth: 5,
    environment: __DEV__ ? 'debug' : 'production',
    onReady: async ({didCallNativeInit}) =>
      didCallNativeInit ? await addSentryPreprocessor() : undefined,
    enableWatchdogTerminationTracking: false,
    enableCaptureFailedRequests: false,
    enableAppHangTracking: false,
  });

### Steps to Reproduce

1. Build and run for iOS

### Expected Result

Error like `HTTP Client Error with status code: 503` should not be sent to sentry.io

### Actual Result

5xx errors are all sent to sentry.io

I suspect the fact that it is enabled by default on Sentry iOS SDK > 8 is the reason why this is still logged 

In the lib I see this:
```
if (options.enableCaptureFailedRequests) {
        integrations.push(httpClientIntegration());
    }
```

Meaning nothing is done to explicitly disable the option

**Comment by hamzaaftab** [comment]
I think the issue might be here:

https://github.com/getsentry/sentry-react-native/blame/main/packages/core/ios/RNSentry.mm#L218

@krystofwoldrich perhaps it should be

```
sentryOptions.enableCaptureFailedRequests = NO;
```

instead of 

```
sentryOptions.enableCaptureFailedRequests = @NO;
```
