### ISSUE TITLE
setExtraContext can cause repeating fatal exception

### ISSUE THREAD

**Issue by OrLevy23** [getsentry/sentry-react-native#435]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

I've came across a bug in our app where we did Sentry.setExtraContext to string, we are working with typescript and the signature of function is setExtraContext(extra: Object)
according to the signature of the function passing a string is legit but if we do it then we crash the app.
the crash will happen in a lop every time we open the app
when investigating the native logs we see this:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableDictionary addEntriesFromDictionary:]: dictionary argument is not an NSDictionary' which does not help us much.

there are few things you can do here:
Types: 
interface Metadata {
 key: string,
 value: any
}
and never the less we shouldn't crash natively and check if the input is correct or not, note that if we set this userContext we cannot send any logs nor open the app so it's very hard to discover what is the cause

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
