### ISSUE TITLE
Sentry not catching any errors or events for android release variant

### ISSUE THREAD

**Issue by itsyogesh** [getsentry/sentry-react-native#442]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
Pei@0.0.1 /Users/Yogesh/Projects/Pei/pei-mobile
├── axios@0.18.0
├── moment@2.22.2
├── prop-types@15.6.2
├── qs@6.5.2
├── UNMET PEER DEPENDENCY react@16.4.1
├── UNMET PEER DEPENDENCY react-native@0.56.0
├── react-native-animatable@1.3.0
├── react-native-app-intro-slider@0.2.4
├── react-native-background-geolocation@2.12.2
├── react-native-extended-stylesheet@0.8.1
├── react-native-firebase@3.3.1
├── react-native-image-picker@0.26.10
├── react-native-linear-gradient@2.4.0
├── react-native-maps@0.20.1
├── react-native-material-textfield@0.12.0
├── react-native-modal@6.4.0
├── react-native-offline@3.11.0
├── react-native-permissions@1.1.1
├── react-native-phone-input@0.2.1
├── react-native-progress@3.5.0
├── react-native-sentry@0.38.2
├── react-native-shimmer-placeholder@1.0.29
├── react-native-snap-carousel@3.7.2
├── react-native-vector-icons@4.6.0
├── react-navigation@1.5.12
├── react-redux@5.0.7
├── redux@3.7.2
├── redux-devtools-extension@2.13.5
├── redux-enhancer-react-native-appstate@0.3.1
├── redux-persist@5.10.0
├── redux-saga@0.16.0
└── validator@9.4.1

npm ERR! peer dep missing: react@16.0.0, required by react-native-maps@0.20.1
npm ERR! peer dep missing: react-native@0.51.0, required by react-native-maps@0.20.1
npm ERR! missing: react-native-tab-view@github:react-navigation/react-native-tab-view, required by react-navigation@1.5.12
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
   logLevel: SentryLog.Verbose
}).install()
```

---
I have following issue:

I've done the android setup according to the documentation on the sentry website, but my app is not catching any errors. Its not even capturing any messages.

**Steps to reproduce:**
- Step

**Actual result:**

Should capture the crash errors.

**Expected result:**
Not capturing any errors.

**Comment by kerwin1** [comment]
it works for me:
```
Sentry.config('...', {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  handlePromiseRejection: true 
}).install();
```

**Comment by HazAT** [comment]
Can you make sure your `MainApplication.java` looks something like this see: https://docs.sentry.io/clients/react-native/manual-setup/#android
```
import io.sentry.RNSentryPackage;

public class MainApplication extends Application implements ReactApplication {

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new RNSentryPackage()
        );
    }

}
```

**Comment by dawee** [comment]
I have the same issue since I upgraded react-native from 0.54.0 to 0.56.0. `captureMessage` still works but I don't have any error report.

**Comment by HazAT** [comment]
@dawee Do you still remember what your issue was?x

**Comment by evasyuk** [comment]
@itsyogesh have you performed proper setup for Android? I have hypthesis that sentry-android is buggy and fails to send event to sentry once it can not find proguard UUID. will back to you and other 10 issues with the same problem once I would have resolution(will do it within next week)

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
