### ISSUE TITLE
After Sentry installation deployed to itunesstore app crashes (on Android or ios simulator it works fine)

### ISSUE THREAD

**Issue by vnosikov** [getsentry/sentry-react-native#445]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

I added react-native-sentry to my project, following this manual: https://docs.sentry.io/clients/react-native/

Everything works fine on Android and ios emulator. But when I tried to archive an app in xcode I got this error.

```
**React native symbol handling failed**

The Sentry build step failed while running in the background. You can ignore this error or view details to attempt to resolve it. Ignoring it might cause your crashes not to be handled properly.
```

If I click 'Show Details; I get this

```
error: EOF while parsing a value at line 1 column 0
```

I followed the advice from here https://github.com/getsentry/react-native-sentry/issues/135 and edited Build Phases > Upload Debug Symbols so now there is only this line there 

```
export SENTRY_PROPERTIES=sentry.properties
```

The error still persisted. So I decided to ignore it. In this case after I upload the version to Itunesconnect and install it with a TestFlight it crashes immediately on start.

If I run it on a simulator or install it directly an iphone it works fine.

It also works fine on Android.

Could you give me any advice what can be done to make it work on Apple Store too?

**Comment by vnosikov** [comment]
Thanks for your reply.

Yes the local build also crashed. I remember that last week I somehow made it work, but now can't remember how.

My "Bundle React Native code and images" script is

```
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/packager/react-native-xcode.sh -- index.js
```

I don't have index.ios.js file only index.js, so I suppose my problem can be caused by this.

My version of react-native is 0.45.1

**Comment by peacechen** [comment]
Is your app using CodePush?  There was a bug in RN 0.55 that would crash if blob fetch returned an empty value. There was a long and heated discussion about it, and it was supposedly fixed in 0.56, but there are reports that it wasn't.   There is a JS-side safety valve fix which I apply to our builds to ensure that it never crashes due to that.  I'll look that up if it applies to your case.

**Comment by yakisama12** [comment]
@peacechen  can you refer to the discussion about the CodePush bug? i'm also experiencing it in RN 0.56,

**Comment by peacechen** [comment]
I posted a method to patch the JS side of RN to fix the empty blob response crash:
https://github.com/facebook/react-native/issues/18440#issuecomment-389660833

For me, this was triggered by CodePush.  There are other situations that people have found can trigger the bug too.

**Comment by MrHubble** [comment]
@vnosikov did you find a solution for this?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
