### ISSUE TITLE
Does not report crashes

### ISSUE THREAD

**Issue by vovanmix** [getsentry/sentry-react-native#447]
OS:
- MacOS

_Platform:_
- iOS

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.10.0
5.6.0
/Users/xxx/projects/yyy
├── apollo-boost@0.1.6
├── aws-sdk@2.273.1
├── babel-cli@6.26.0
├── babel-eslint@8.2.3
├── babel-plugin-syntax-trailing-function-commas@6.22.0
├── babel-plugin-transform-class-constructor-call@6.24.1
├── babel-plugin-transform-do-expressions@6.22.0
├── babel-plugin-transform-exponentiation-operator@6.24.1
├── babel-plugin-transform-export-extensions@6.22.0
├── babel-plugin-transform-function-bind@6.22.0
├── babel-plugin-transform-inline-environment-variables@0.4.3
├── babel-preset-env@1.7.0
├── babel-preset-expo@4.0.0
├── babel-preset-flow@6.23.0
├── date-fns@1.29.0
├── eslint@4.19.1
├── eslint-config-airbnb@16.1.0
├── eslint-config-prettier@2.9.0
├── eslint-plugin-class-property@1.1.0
├── eslint-plugin-flowtype@2.46.3
├── eslint-plugin-import@2.11.0
├── eslint-plugin-jsx-a11y@6.0.3
├── eslint-plugin-prettier@2.6.0
├── eslint-plugin-react@7.7.0
├── ex-react-native-i18n@0.0.4
├── expo@28.0.0
├── flow-bin@0.67.1
├── formik@0.11.11
├── graphql@0.13.2
├── graphql-tag@2.9.2
├── jest-expo@25.0.0
├── lodash@4.17.10
├── prettier@1.13.0
├── react@16.3.1
├── react-apollo@2.1.4
├── react-native@0.55.4 invalid
├── react-native-actionsheet@2.4.2
├── react-native-iap@1.3.1
├── react-native-image-pan-zoom@2.1.5
├── react-native-mime-types@2.2.1
├── react-native-phone-call@1.0.6
├── react-native-scripts@1.13.1
├── react-native-sentry@0.38.2
├── react-native-swiper-flatlist@1.0.7
├── react-navigation@2.4.1
├── react-test-renderer@16.2.0
├── rn-sliding-up-panel@1.2.1
└── yup@0.25.1
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

Native crashes are not reported. I have a detached expo app, I'm using `react-native-sentry` instead of  `sentry-expo` because it's detached, I did `react-native link react-native-sentry`. Running the app from expo.
When the app crashes on iOS, or when  I do `Sentry.nativeCrash();` in the simulator, nothing gets reported. `Sentry.captureMessage('TEST message');` reports correctly.
It also wan't reporting crashes before I detached expo, with `sentry-expo`.

**Comment by sergeylaptev** [comment]
Yup, the same situation. Installed the latest release (0.38.3). Crashes don't send but custom captured messages shown in the log.

**Comment by HazAT** [comment]
I just tried it and it works.
Please make sure your MainApplication.java looks something like this:
```
...
import io.sentry.RNSentryPackage;
...
public class MainApplication extends Application implements ReactApplication {
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(), new RNSentryPackage()
      );
    }
```

**Comment by vovanmix** [comment]
Thanks for reply! I’ve been trying on iOS, any suggestions what can go
wrong with the configuration for it?

**Comment by HazAT** [comment]
What is the `SDK` section saying on the bottom of your event?

It should look something like this:
![screenshot 2018-07-30 15 36 53](https://user-images.githubusercontent.com/363802/43400595-674c2e1e-940e-11e8-8d0a-49717b156257.png)

**Comment by idris** [comment]
@vovanmix @sergeylaptev did you ever figure this out?  We don't see any crashes in Segment, though JS exceptions and messages work fine.

**Comment by MorcosS** [comment]
Any news about this? I am trying Sentry on both ios and android it triggers only when using `Sentry.captureException()`.
I am using this with:
`"react-native": "0.59.0",
   "react-native-sentry": "^0.42.0",`

**Comment by Sam-Hoult** [comment]
Getting reports from customers of the app crashing and we see nothing on our end.
To make the app crash show up, but we aren't getting anything when the app just drops.

**Comment by NetPumi2** [comment]
+1

**Comment by cinder92** [comment]
same issue here...

**Comment by zivchen** [comment]
Same here
"react-native": "0.59.8",
"react-native-sentry": "^0.42.0",

**Comment by 509dave16** [comment]
+1

**Comment by prof18** [comment]
Same here. As workaround I override the global error handler to include the Sentry log.

```
// Error handler setup
  let originalHandler = ErrorUtils.getGlobalHandler();
  ErrorUtils.setGlobalHandler((error, isFatal) => {
    Sentry.captureException(error);
    originalHandler(error, isFatal);
  });
```

**Comment by terreb** [comment]
@prof18, not working for me. react-native: 0.57.8, react-native-sentry: 0.43.2

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
