### ISSUE TITLE
react-native-sentry is missing interfaces when running under jest

### ISSUE THREAD

**Issue by wontonst** [getsentry/sentry-react-native#455]
OS:
- [ ]  Windows
- [ X ]  MacOS
- [ ]  Linux

_Platform:_
- [ X ]  iOS
- [ X ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.3.0
6.2.0
```

Config:

```
Sentry.config("https://...@sentry.io/...").install()
```

---
I have following issue:

I am testing that my root component works.

```
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
```

In my `App.js`, I install sentry and call `Sentry.setTagsContext`. When running unit tests, the mock that comes with react-native-sentry is lacking some of the interfaces in production, i.e..

```
console.log(Sentry);
    { clearContext: [Function: clearContext],
      setUserContext: [Function: setUserContext],
      config: [Function: config],
      captureMessage: [Function: captureMessage] }
```

Same result on both react-native-sentry v 0.37.1 and 0.38.3

Jest 23.4.1

**Steps to reproduce:**
- Add a call to Sentry.setTagsContext in your root component
- Create a jest test where you import and render the root component

**Actual result:**
`TypeError: _reactNativeSentry.Sentry.setTagsContext is not a function`

**Expected result:**
Test calls mock `setTagsContext` and continues with test

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by markgibaud** [comment]
In your jestSetup.js: 

```
jest.mock('react-native-sentry', () => ({
  Sentry: {
    setTagsContext: jest.fn(),
    setExtraContext: jest.fn(),
    captureBreadcrumb: jest.fn()
  }
}));
```
