### ISSUE TITLE
Release mode exceptions not appearing in issues list, debug mode are (Android)

### ISSUE THREAD

**Issue by dajaffe** [getsentry/sentry-react-native#457]
OS:
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

```
v8.11.1
5.6.0
ReactProject@0.1.0 E:\Users\\Projects\
+-- @ptomasroos/react-native-multi-slider@0.0.14
+-- axios@0.18.0
+-- lodash@4.17.10
+-- moment@2.22.1
+-- prop-types@15.6.1
+-- UNMET PEER DEPENDENCY react@16.3.2
+-- UNMET PEER DEPENDENCY react-native@0.55.2
+-- react-native-app-auth@2.4.1
+-- react-native-collapsible@0.11.3
+-- react-native-console-time-polyfill@0.0.6
+-- react-native-easy-grid@0.1.17
+-- react-native-elements@0.19.1
+-- react-native-flip-toggle-button@1.0.5
+-- react-native-icon-badge@1.1.3
+-- react-native-linear-gradient@2.4.0
+-- react-native-masonry@0.4.7
+-- react-native-material-bottom-navigation@0.9.0
+-- react-native-render-html@3.9.3
+-- react-native-richtext-editor@0.1.14
+-- react-native-sentry@0.38.3
+-- react-native-simple-radio-button@2.7.2
+-- react-native-sortable-list@0.0.22
+-- react-native-star-rating@1.0.9
+-- react-native-swiper@1.5.13
+-- react-native-switch@1.5.0
+-- react-native-switch-pro@0.4.11
+-- react-native-tag-input@0.0.21
+-- react-native-tags@1.2.1
+-- react-native-textinput-effects@0.4.2
+-- react-native-vector-icons@4.6.0
+-- react-native-viewpager@0.2.13
+-- react-native-webview-bridge@0.33.0
+-- react-native-xml2js@1.0.3
+-- react-native-zss-rich-text-editor@1.1.0
+-- UNMET PEER DEPENDENCY react-navigation@1.5.11
+-- react-navigation-redux-helpers@1.0.5
+-- react-navigation-tabs@0.1.0-alpha.6
+-- react-redux@5.0.7
+-- redux@4.0.0
+-- redux-saga@0.16.0
`-- toggle-switch-react-native@0.2.0
```

Config:
I've tried the following variations:
```
Sentry.config('https://...@sentry.io/...', {
  deactivateStacktraceMerging: true,
  logLevel: SentryLog.Verbose,
  // currently sentry is not reporting errors on android using the native module
  disableNativeIntegration: Platform.OS === 'android',
}).install()
```
```
Sentry.config('https://...@sentry.io/...', {
  deactivateStacktraceMerging: false, 
  logLevel: SentryLog.Verbose, 
  disableNativeIntegration: false, 
  handlePromiseRejection: true
}).install()
```
```
Sentry.config('https://...@sentry.io/...', {}).install()
```

---
Dev mode exceptions are successfully uploaded to Sentry, but release mode's are not.

**Steps to reproduce:**
- Add an exception that will be thrown
```
  constructor(props) {
    super(props);
    throw Error('this is release mode');
  }
```
- Release the app
```
./gradlew assembleRelease
```
- Install and run the app.

**Actual result:**
- When running in debug mode, the thrown exception appears in my unresolved issues. When running a release mode APK, the thrown exception does not appear.

**Expected result:**
- The exception while running a released APK to be in my issues list.

**Troubleshooting Steps:**
- Confirmed my MainApplication.java looks like this: https://github.com/getsentry/react-native-sentry/issues/447
- Tried both Sentry config's found https://github.com/getsentry/react-native-sentry/issues/442 and https://github.com/getsentry/react-native-sentry/issues/6 (very bottom)
- ```captureMessage``` in both debug and release modes does show up in my console
- Attached through Android Studio to check logs:
```
08-05 01:03:58.617 24921-24946/? D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.
08-05 01:03:58.619 24921-24946/? D/io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='xxx.MainApplication@370b462' and dsn='Dsn{uri=https://sentry.io/}'
08-05 01:03:58.686 24921-24946/? D/io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/xxx/cache/sentry-buffered-events
08-05 01:03:58.692 24921-24946/? I/react-native-sentry: startWithDsnString 'https://xxx@sentry.io/xxx'
08-05 01:03:58.747 24921-24946/? D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
```

I'm trying to get this working to switch over from using BugSnag, but it's not looking good.

**Comment by HazAT** [comment]
🤔 
this all looks correct, remember, if it's a crash it can take up to one minute until android sends it.
On debug, we send it right away.

**Comment by dajaffe** [comment]
Yep. My crashes on debug were taking about 40 seconds to hit. Still nothing in there for release though with intentional crashes.

**Comment by PoppyAnc** [comment]
Hello, 
Do you still have this issue? 

we are on "react-native-sentry": "^0.42.0",  
we get error reports from ios but not on android (neither debug nor release mode).
If I have disableNativeIntegration: true on debug mode, I get some "Raven transport failed to send: [...]Certificate validation failed". 
When I have disableNativeIntegration: false, nothing happens but no errors appear on Sentry.

Please note that all configuration is double checked and source maps are loaded correctly on Sentry.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
