### ISSUE TITLE
Facing Frequent 504 on upload debug symbols service

### ISSUE THREAD

**Issue by Abdul-Hannan** [getsentry/sentry-react-native#463]
OS:
- [ ]  MacOS

_Platform:_
- [ ]  iOS

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.2
```

Config:

```
    Sentry.config(sentryClientKey).install();
    Sentry.setRelease(releaseVersion);
    Sentry.setDist(versionCode);
    Sentry.setVersion(releaseVersion);
```

---
We have seen increasing number of 504 When script phase execution happens to upload debug symbols

"react-native-sentry": "0.38.2"

**Steps to reproduce:**
- run the following as phase script in iOS build

export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh

**Actual result:**
- The following build commands failed:
	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/vagrant/Library/Developer/Xcode/DerivedData/App-bkkyehhhlqleqvfjfbcylqbifcpe/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Release-iphoneos/App.build/Script-BEC569C85814431085B49BF4.sh

error: API request failed
  caused by: sentry reported an error: unknown error (http status: 504)

**Expected result:**
- Debug symbol should upload fine, can you check whats the failure rate of your service.

**Comment by HazAT** [comment]
Hey, I suppose you are using sentry.io not self-hosted right?

**Comment by Abdul-Hannan** [comment]
Hello @HazAT , yes, sentry.io

**Comment by Abdul-Hannan** [comment]
hello @HazAT , its now frequently giving 500 errors as well

````
      error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object({"detail": String("Internal Error"), "errorId": String("31e170980de54c7a96ae75753fa75fc9")})
````

**Comment by HazAT** [comment]
@Abdul-Hannan This is an issue with sentry.io itself, we are aware of it and working on a bugfix.

**Comment by marcomorain** [comment]
Any updates on this issue? It's affecting my projects too.

**Comment by fabioknoedtbcgdv** [comment]
I am having the same problem using `sentry-cocoa`:

```
[08:59:13]: error: API request failed
[08:59:13]: caused by: sentry reported an error: request failure (http status: 500)
[08:59:13]: Object({"detail": String("Internal Error"), "errorId": String("792ca88861ff4f62ba4854f32143bb21")})
```

**Comment by HazAT** [comment]
@Abdul-Hannan @marcomorain 
We thought we fixed the issue, apparently, we didn't 😞 .
Could you both update `sentry-cli` to the latest version (`1.35.4`) and try again?

Thanks

**Comment by mrceephax** [comment]
Good morning,

I am unfortunately seeing this issue as well. This is the version of sentry i have installed in my application

```"react-native-sentry": "^0.35.4",```

```
$ node -v && npm -v && npm ls --prod --depth=0
v7.5.0
4.1.2
```

**Comment by mitsuhiko** [comment]
This is likely resolved on sentry.io. Please reopen this if it still happens.

**Comment by fabioknoedtbcgdv** [comment]
I just got this error again:

```
[02:42:00]: sentry-cli 1.36.1 installed!
[02:42:00]: Starting sentry-cli...
[02:43:09]: > Found 57 debug information files
[02:43:09]: > Prepared debug information files for upload
[02:43:09]: error: API request failed
[02:43:09]: caused by: sentry reported an error: unknown error (http status: 504)
```

**Comment by mitsuhiko** [comment]
@fabioknoedtbcgdv and this is on sentry.io? Does this happen with `--log-level = debug` too?

**Comment by fabioknoedtbcgdv** [comment]
I haven't tested with `log-level`. I am using `Fastlane` action:
```
    sentry_upload_dsym(
      auth_token: 'TOKEN',
      org_slug: 'labtw***',
      project_slug: 'ios',
      dsym_path:'./Aid****.app.dSYM.zip'
    )
```
Why would the log level change anything?

**Comment by mitsuhiko** [comment]
@fabioknoedtbcgdv it would help us debug the issue. If it only happens predictably then running it again with debug output and sharing it would be great so we can figure it out.

**Comment by fabioknoedtbcgdv** [comment]
@mitsuhiko Running locally (before it was in CircleCI), it doesn't give me any errors, for exactly the same file:

```
[12:01:46]: sentry-cli 1.36.1 installed!
[12:01:46]: Starting sentry-cli...
[12:01:52]: > Found 57 debug information files
[12:01:52]: > Prepared debug information files for upload
[12:01:52]: > Nothing to upload, all files are on the server
[12:01:52]: > No new debug symbols to associate.
[12:01:52]: Successfully uploaded dSYMs!
```

**Comment by tahairfan13** [comment]
Having the same issue, working fine on development, Any updates?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
