### ISSUE TITLE
[Question] Sourcemap Upload Help/Documentation

### ISSUE THREAD

**Issue by EricPKerr** [getsentry/sentry-react-native#469]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

There doesn't seem to be any clear and concise steps to getting sourcemap output automatically uploaded to Sentry with the releases/builds.  I wasn't able to find this on sentry's site either.

Is there any walkthrough on how to do this anywhere?

**Comment by EricPKerr** [comment]
Any help @getsentry? @HazAT @mitsuhiko

**Comment by CarisL** [comment]
Is now the problem solved?

**Comment by EricPKerr** [comment]
@CarisL I don't believe anything has been updated to provide clear steps to uploading a sourcemap to Sentry, so I don't think it's been solved yet.

**Comment by WatsonFungHK** [comment]
I agree with EricPKerr. The document does not giveclear steps for sourcemap instruction

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
