### ISSUE TITLE
0.39 update cause android stop reporting

### ISSUE THREAD

**Issue by freemanUA** [getsentry/sentry-react-native#470]
OS:
- [ ]  Windows
- [ x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`
├── axios@0.17.1
├── babel-preset-expo@4.0.0
├── eslint-config-rallycoding@3.2.0
├── lodash@4.17.4
├── moment@2.20.1
├── native-base@2.7.2
├── prop-types@15.6.0
├── react@16.4.2
├── react-native@0.56.0
├── react-native-android-location-services-dialog-box@2.6.0
├── react-native-app-auth@2.6.0
├── react-native-button@2.2.0
├── react-native-calendars@1.20.0
├── react-native-datepicker@1.6.0
├── react-native-device-info@0.21.5
├── react-native-dimension@1.0.6
├── react-native-elements@0.19.1
├── react-native-fingerprint-scanner@2.2.1
├── react-native-fontawesome@5.7.0
├── react-native-gps-state@0.0.2
├── react-native-image-crop-picker@0.20.0
├── react-native-image-picker@0.26.7
├── react-native-keyboard-aware-scroll-view@0.4.4
├── react-native-keyboard-aware-scrollview@2.0.0
├── react-native-onesignal@3.1.0
├── react-native-permissions@1.1.1
├── react-native-pod@1.10.0
├── react-native-popup-dialog@0.10.46
├── react-native-responsive-ui@1.1.1
├── react-native-router-flux@4.0.1
├── react-native-sentry@0.39.0
├── react-native-splash-screen@3.0.6
├── react-native-swipeout@2.3.3
├── react-native-timeline-listview@0.2.3
├── react-native-timer@1.3.1
├── react-native-vector-icons@5.0.0
├── react-native-view-more-text@2.0.1
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-devtools-extension@2.13.2
├── redux-persist@5.4.0
└── redux-thunk@2.2.0

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:
after updating to 0.39 android doesn't report, ios - ok
Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- no report

**Expected result:**
- report

**Comment by derN3rd** [comment]
Something new here?
We have the same issue. Also we see that the release version isn't reported to sentry in debug builds. With a release build we don't get any native errors and js errors have no release on it, which makes it impossible to track our next update.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
