### ISSUE TITLE
Execution failed for task ':app:bundleMallappReleaseJsAndAssets'.

### ISSUE THREAD

**Issue by songxiaoliang** [getsentry/sentry-react-native#471]
* Where:
Script '/Users/weego_song/weego-app/node_modules/react-native-sentry/sentry.gradle' line: 176

* What went wrong:
Execution failed for task ':app:bundleMallappReleaseJsAndAssets'.
> java.lang.NullPointerException (no error message)

**Comment by jussirantala** [comment]
Has anyone found a solution for this? I'm using gradle 4.4.

**Comment by pardeepsingal** [comment]
Please try to update the auth.token in sentry.properties files for both android and ios.
it works for me.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
