### ISSUE TITLE
package-lock.json out of date

### ISSUE THREAD

**Issue by vovkasm** [getsentry/sentry-react-native#476]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.10.0
6.4.1
react-native-sentry@0.39.0 /Volumes/work/react-native-sentry
├── @sentry/wizard@0.11.1
└── raven-js@3.27.0
```

---
I have following issue:

After checkout I can't work on module as developer. Because `npm ci` command does not work.

**Steps to reproduce:**
- `npm ci` after git checkout

**Actual result:**
```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

**Expected result:**
- command should success

Actually if project devs use yarn, then package-lock.json better to be removed (and added to .gitignore). Or it should be updated :-)

**Comment by vovkasm** [comment]
To be pedantic: all this happens to me at commit 727dca6f7e516191ea646ff9b0ce5c3e9674e4b9

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
