### ISSUE TITLE
Cannot run the application using react-native-sentry 39.0 - due to the deprecated Pod React.

### ISSUE THREAD

**Issue by olegongit** [getsentry/sentry-react-native#478]
OS:
- [ ]  Windows
- [ x]  MacOS
- [ ]  Linux

_Platform:_
- [ x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.3
5.6.0
```

---
I have following issue:

Cannot run the application using react-native-sentry 39.0 - due to the deprecated Pod React.

Description goes here ...

I have upgraded react-native-sentry to the 39.0 version. (my application is originally react-native application, ie not native).

It added the following to my Podfile: `pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'`
I run `pod install`

Now, when I try to run `react-native run-ios`, I get the following output by bundler:
```
Duplicate module name: react-native
  Paths: /PATH_TO_MY_APP/ios/Pods/React/package.json collides with /PATH_TO_MY_APP/node_modules/react-native/package.json
```

As well, you probably know, that pod install says that React pod is deprecated. Which can be confirmed at https://cocoapods.org/pods/React. Question is how to avoid this dependency in a react-native application.

**Comment by hahtml** [comment]
+ 1

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
