### ISSUE TITLE
'Source code was not found...' pops with sourcemaps generated successfully

### ISSUE THREAD

**Issue by junchenjun** [getsentry/sentry-react-native#481]
OS:
- MacOS

_Platform:_
- iOS
- Android

---
I have following issue:

#### I have sourcemaps generated successfully under Artifacts tab in the same release.

![snipaste_2018-09-19_17-44-32](https://user-images.githubusercontent.com/31823768/45745748-187d8280-bc34-11e8-8d6f-bcea7d4ba1ad.png)

#### and the EXCEPTION description are all messy. 

![snipaste_2018-09-19_17-44-07](https://user-images.githubusercontent.com/31823768/45745793-334ff700-bc34-11e8-804d-64f660d8d8f7.png)
![snipaste_2018-09-19_17-53-57](https://user-images.githubusercontent.com/31823768/45746314-8c6c5a80-bc35-11e8-8d96-e60183498db0.png)

#### I am using Expo in my project, and I followed the instruction [https://docs.sentry.io/clients/react-native/expo/](url) very carefully. I am using TypeScript btw.

**Comment by luco** [comment]
+1 on this.

**Comment by HazAT** [comment]
Please make sure that the
`release` and `dist` tag of the event, matches exactly with the `release` & `dist` of the artifact in the release section.
You can find the actual release name in the url when you click on artifacts.
The `dist` can be found beside the file name.

**Comment by HazAT** [comment]
@jaychenjun Can you post a link to an event so I can take a look please?

**Comment by ltankey** [comment]
I'm finding the same thing happening, and am not sure which end it's on (sentry or expo).

My artefacts are uploaded fine and appear to have source maps correctly mapped to the bundles:

```
+-----------------------+--------------+------------------+--------+
| Name                  | Distribution | Source Map       | Size   |
+-----------------------+--------------+------------------+--------+
| ~/main.android.bundle |              | main.android.map | 2.40MB |
| ~/main.android.map    |              |                  | 8.26MB |
| ~/main.ios.bundle     |              | main.ios.map     | 2.41MB |
| ~/main.ios.map        |              |                  | 8.30MB |
+-----------------------+--------------+------------------+--------+
```

This is correctly shown under the release for which I expect these to have been uploaded.

When an issue is received for this release, it correctly shows in Sentry:
![image](https://user-images.githubusercontent.com/5369670/48456334-c790a180-e812-11e8-8b17-4a9b446938c2.png)

However the actual issue shows this:
![image](https://user-images.githubusercontent.com/5369670/48456362-e7c06080-e812-11e8-8b4f-4956faa0f761.png)

With the non-sourcemapped stacktrace:
![image](https://user-images.githubusercontent.com/5369670/48456386-045c9880-e813-11e8-8de1-01637b5abb87.png)

**Comment by hgang** [comment]
+1 on this,
I am facing the same problem.
I uploaded sourcemap files with sentry cli, and distribution was specified. I can see it from release artifacts list. but the actual issue still showing error: 
------------
Source code was not found 
Url :  app:///index.delta

**Comment by shortcarver** [comment]
+1 on this. I have the same problem. Works on sentry's hosted servers, but not on our private server.

**Comment by naytun** [comment]
Same script, works on ios but showing `url: app:///index.delta` not found error

**Comment by shortcarver** [comment]
We solved it on our end. It was failing because the sentry workers did not have access to the sourcemap folder on the primary node, so when we uploaded the sourcemap the worker wasn't able to parse it.

"app:///index.delta" means that the crash happened on a test device connected to the test server. I would not expect the stack traces to be correct in that case.

**Comment by ltankey** [comment]
@shortcarver I think that's right here. Is there anything special about your on-prem setup you had to do? We've got S3 configured and artefacts are finding their way up fine, but it seems sentry still 404s when it tries to resolve them internally.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by ltankey** [comment]
FWIW I think this issue can be potentially caused by invalid filesystem permissions for sourcemaps (for anyone who stumbles upon this in future).

**Comment by shortcarver** [comment]
Yes, that was our problem.

**Comment by chj-damon** [comment]
> Same script, works on ios but showing error on android:
> 
> ```
> Source code was not found: "url: app:///index.delta"
> ```

same here.

**Comment by zmnv** [comment]
On iOS:

Source code was not found
Url app:///main.jsbundle
