### ISSUE TITLE
Android Studio warning - Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by heavyskyl** [getsentry/sentry-react-native#499]
OS:
- [ ]  Windows
- [ X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X ]  Android

---
I have following issue:

Warning in android studio during app build:
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Can you please make small commit and publish new version to npm ?

**Comment by OleksandrKucherenko** [comment]
merged - https://github.com/getsentry/react-native-sentry/pull/518

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
