### ISSUE TITLE
FEATURE REQUEST: User Feedback

### ISSUE THREAD

**Issue by export-mike** [getsentry/sentry-react-native#500]
_Platform:_
- [x]  iOS
- [x]  Android

RavenJS has a useful user-feedback feature to capture more information on how the error occured. This is super useful for internal testing for testers to use as and when errors happen.

expect a new function to be added to render UI to capture details from the user in a text field.

**Comment by voxpelli** [comment]
This would be very helpful.

Being able to collect feedback from an app when the user runs across something that they believe to be a bug, getting interesting state data, a screenshot, maybe even annotated screenshot – that would be very nice

**Comment by export-mike** [comment]
All very possible from the react-native side too.

**Comment by saadq** [comment]
In the mean time, I had been looking at going for an alternative solution which was to call the [user feedback API endpoint](https://docs.sentry.io/api/projects/post-project-user-reports/) directly like so:

```
curl 'https://sentry.io/api/0/projects/saad-quadri/test/user-feedback/' --request 'POST' --header 'Authorization: Bearer <my-auth-token>' --header 'Content-Type: application/json' --data '{"comments":"there is an issue with the app","email":"johnsmith@gmail.com","event_id":"1234abcd","name":"John Smith"}'
```

I thought it had worked because it returned a JSON response like so:

```json
{
  "eventID": "1234abcd",
  "name": "John Smith",
  "event": { "eventID": "1234abcd", "id": null },
  "user": null,
  "dateCreated": "2018-12-26T22:01:40.883Z",
  "issue": null,
  "id": "443876",
  "comments": "there is an issue with the app",
  "email": "johnsmith@gmail.com"
}
```

But it doesn't seem to actually get added to the user feedback :(

<img width="1440" alt="screen shot 2018-12-26 at 5 03 15 pm" src="https://user-images.githubusercontent.com/5678694/50458559-f598f380-0931-11e9-8992-93b5c38fa7fb.png">

I'm sure that it's pointing to the right project and the details are right because error reporting does work:

<img width="1441" alt="screen shot 2018-12-26 at 5 10 04 pm" src="https://user-images.githubusercontent.com/5678694/50458581-0b0e1d80-0932-11e9-8478-fafd3f77807d.png">

Not sure if I'm missing something...

**Comment by naytun** [comment]
@saadq, The reason feedback is not showing in the dashboard is because you need to give actual `event_id` of events in the Sentry, not user defined id.

**Comment by saadq** [comment]
Hey @naytun, thanks for bringing this up. I actually did realize that at some point awhile back, but I forgot to update here. There is a `Sentry.lastEventId()` method that you should be able to call in order to get the last event_id, but it hadn't been working for me (it always returned `null`). 

I opened an issue here for that: https://github.com/getsentry/react-native-sentry/issues/527

I got a reply from one of the maintainers on the proper way to do it, but I hadn't tried it out. If that doesn't work out for you, I can give you the alternative method I used to get it to work, although it was pretty hacky.

**Comment by naytun** [comment]
@saadq, Thank you for the quick feedback and also for the tip. I'll try lastEventId() see I could get it working.

**Comment by naytun** [comment]
@saadq, I can successfully get eventID like this.
```
         //=== Create feedback event in Sentry and get eventID
         Sentry.captureMessage("User Feedback... ");
         Sentry.setEventSentSuccessfully(event => {
            const eventID = Sentry.lastEventId();
        });
```

**Comment by saadq** [comment]
Awesome, glad to see it works!

**Comment by export-mike** [comment]
submit a PR @saadq to report these changes via a new API method? 

it's a start. I doubt many people will be keen to have a sentry looking UI feedback form in their apps anyway.

**Comment by MM-Psiiirus** [comment]
Hi @saadq, so u did a mix of native fetch() and Sentry-js to get it to work?

**Comment by saadq** [comment]
Hey @MM-Psiiirus,

So to get this to work, you basically need to do a POST request to `https://sentry.io/api/0/projects/{your_organization_slug}/{your_project_slug}/user-feedback/`. You need to pass in a [few strings in your request body](https://docs.sentry.io/api/projects/post-project-user-reports/) – the `event_id`, a user's `name`, a user's `email`, and the `comments` provided by the user.

Something like:

```js
let endpoint = 'https://sentry.io/api/0/projects/{your_organization_slug}/{your_project_slug}/user-feedback/'

let params = {
  event_id: ...,
  name: 'John Smith',
  email: 'johnsmith@example.com',
  comments: 'This app sucks'
}

try {
  await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(params)
  })
  console.log('Feedback submitted!')
} catch (err) {
  console.error(err)
}
```

To actually get that `event_id` you need to pass in, look at the comments above. Hope that helps.

---

@export-mike Not exactly sure what you meant by that PR, just to check what exactly are you proposing? Right now with the way I described above, you would just have your own custom form that takes in `name`, `email`, and `comments` as inputs and then pass that data to the user-feedback endpoint as request params.

**Comment by export-mike** [comment]
@saadq add the following: 

```js
function submitFeedback(params){
let endpoint = 'https://sentry.io/api/0/projects/{your_organization_slug}/{your_project_slug}/user-feedback/'

return fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(params)
  })
}
let params = {
  event_id: ...,
  name: 'John Smith',
  email: 'johnsmith@example.com',
  comments: 'This app sucks'
}
Sentry.submitFeedback(params);
``` 

as a new JS function to Sentry

**Comment by jordoh** [comment]
Thanks for the code @saadq - that worked great, but I did need to add an authorization header (using DSN auth, so no secrets are required):
```
"Authorization": `DSN ${ SENTRY_DSN }`
```

**Comment by pybuche** [comment]
Hi! Any update on this? Is this feature will someday be ported to the React Native version?
Thx!

**Comment by Vadorequest** [comment]
Also interested for a react app.

It seems to exist in the https://www.npmjs.com/package/@sentry/browser package, but it doesn't play nicely with Next.js which is a universal app (browser + node)  and requires to apply some dirty tricks like https://github.com/zeit/next.js/blob/canary/examples/with-sentry-simple/next.config.js to use Sentry universally. But even with that I wasn't able to make User Feedback work in Next.

I don't know if react-native has this kind of issues though, may be unrelated. But looking forward a universal Sentry SDK for JS.

**Comment by nihp** [comment]
Shall I able to get user feedback for my react-native ios and Android app. 

Can anyone clarify.

**Comment by nihp** [comment]
>       //=== Create feedback event in Sentry and get eventID
>          Sentry.captureMessage("User Feedback... ");
>          Sentry.setEventSentSuccessfully(event => {
>             const eventID = Sentry.lastEventId();
>         });

I am getting error as  Sentry.lastEventId() is not a function.

**Comment by roth-j** [comment]
Any update on the added function?

**Comment by sammysium** [comment]
i am a little confused; is this feature implemented? Is there a complete or close to complete example please?

**Comment by jennmueng** [comment]
@sammysium No the feature has not been officially implemented yet, but it shouldn't be difficult to manually implement it per app.

As other commenters have pointed out, you can send a POST request to our API endpoint: https://docs.sentry.io/api/projects/submit-user-feedback/

You can get the slugs from opening your project settings, which should have a URL like this:
```
https://sentry.io/settings/{your_organization_slug}/projects/{your_project_slug}/
```
you can access this by going to `Settings -> Projects -> {Project}`.

The API request will need an authentication header: `'Authorization: DSN {your_dsn}'`

**Comment by bruno-garcia** [comment]
We added User Feedback to Android and iOS. To add here now we just need to write an envelope item of type User Feedback. I marked it as up-for-grabs if someone wants to try to add it. The TypeScript API can be done directly here for now. To go on the [JavaScript SDK](http://github.com/getsentry/sentry-javascript) it will require sending it via the JS transport, which we don't use here. Once the API is added to JS, we can remove the one here in favor of that one.

The docs for the feature is here: https://develop.sentry.dev/sdk/features/#user-feedback

**Comment by flogy** [comment]
Would be great to not put this to stale, as there seems to be quite some interest in this feature by many people.

**Comment by bruno-garcia** [comment]
We plan to tackle this one soon

**Comment by stevecode21** [comment]
I would like to add another Idea to this feature request, and it has to do with implementing a way to attach images and videos by the user as Instabug makes. That would be nice, since sometimes we can use these resources for better debugging.

**Comment by mklsk** [comment]
Expressing interest in this feature as well!
