### ISSUE TITLE
Why the app.device is empty?

### ISSUE THREAD

**Issue by xwartz** [getsentry/sentry-react-native#501]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
react-native@0.55.4
react-native-sentry@0.39.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Why the app.device is empty? What is the generation rule for it?

![image](https://user-images.githubusercontent.com/4149827/48392419-4075f780-e746-11e8-86d0-70e6b1de9404.png)

**Steps to reproduce:**
- `Sentry.config(SENTRY_URL).install()`
- `Sentry.captureMessage(message, { level: SentrySeverity.Warning, ...options })`

**Actual result:**
- show app.device

**Expected result:**
- app.device is empty

**Comment by bukhari-flip** [comment]
how did you resolve this? any information?

**Comment by krystofwoldrich** [comment]
@bukhari-flip If you are missing the `app.device` information, please open a new issue with details about your project, RN version, SDK version, and link to an issue at Sentry.io.
