### ISSUE TITLE
setUserContext doesn't work with id (or userID

### ISSUE THREAD

**Issue by ppetrick** [getsentry/sentry-react-native#503]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.1.4
6.4.1
```

Config:
```
Sentry.config('https://...@sentry.io/...',).install()
```
sentry version "1.36.4"
react-native-sentry version "0.39.1"

---
According to the docs (https://docs.sentry.io/enriching-error-data/context/?platform=javascript#capturing-the-user), "id" alone should suffice to recognize a user. However, that's not what I'm seeing. Only when I add a username as well does it recognize the user (I haven't tested with other properties like email).

Additionally, there is a conflict between the docs above, which say to use "id" and the react-native docs (https://docs.sentry.io/clients/react-native/config/), which uses "userID" in the example. Neither case works when used alone.

**Comment by warfrogsdf** [comment]
Very urgent, online, etc.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
