### ISSUE TITLE
captureBreadcrumb - can't see stored data in Sentry issues

### ISSUE THREAD

**Issue by arnsa** [getsentry/sentry-react-native#504]
OS:
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

_Platform:_
- [X ]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.11.0
6.4.1
├── react-native-sentry@0.39.1
```

Config:

```
Sentry.config('myKey').install();
```

---
I have following issue:

It doesn't capture the breadcrumbs on iOS, didn't have an opportunity to test it on Android yet. Here's the code I use for capturing the breadcrumb:

```
Sentry.captureBreadcrumb({
    timestamp: +(new Date()),
    type: 'navigation',
    data: {
      from: 'Profile',
      to: 'Settings',
    },
  });
```

**Comment by HazAT** [comment]
Does the log say anything?
Try removing the `timestamp` key since we add it for you, maybe it's formatted the wrong way.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
