### ISSUE TITLE
android not work,not report error 

### ISSUE THREAD

**Issue by tabfed** [getsentry/sentry-react-native#512]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- []  iOS
- [x]  Android

v10.4.0
6.1.0

├── @sentry/wizard@0.12.1
├── ajv@6.5.0
├── axios@0.18.0
├── core-js@2.5.7
├── dayjs@1.7.7
├── es6-symbol@3.1.1
├── mobx@4.3.0
├── mobx-react@5.2.8
├── prop-types@15.6.2
├── UNMET PEER DEPENDENCY react@16.6.0-alpha.8af6728
├── react-native@0.57.4
├── react-native-gesture-handler@1.0.9
├── react-native-growingio@0.0.1 invalid
├── react-native-image-picker@0.27.1
├── react-native-image-zoom-viewer@2.2.24
├── react-native-linear-gradient@2.4.4
├── react-native-progress-circle@2.0.1
├── react-native-sentry@0.37.1
├── react-native-storage@0.2.3
├── react-native-swiper@1.5.13
├── react-native-tab-view@1.3.1
├── react-navigation@3.0.0

---
I have following issue:

android not work ,not report error ,ios no problem

version:0.37.1~0.40.2 

rn version:0.57.4

**Comment by warfrogsdf** [comment]
me too， ios is ok，but anroid app is bad，when js has error，android app no send error report

**Comment by tabfed** [comment]
> Observing the same issue
> 
> I'm completely following [setup guide](https://docs.sentry.io/clients/react-native/manual-setup/#android) and pretty sure installation goes well (because it fails if my server cannot get sentry for some reason), but it's just doesn't report.

I solved it.install the latest  version，but android error report not in time，maybe next time start app

**Comment by Komalov** [comment]
@tabfed it's not worked out

**Comment by WatsonFungHK** [comment]
> > Observing the same issue
> > I'm completely following [setup guide](https://docs.sentry.io/clients/react-native/manual-setup/#android) and pretty sure installation goes well (because it fails if my server cannot get sentry for some reason), but it's just doesn't report.
> 
> I solved it.install the latest version，but android error report not in time，maybe next time start app
What do you mean by "start app".

I have completely followed the [instruction](https://docs.sentry.io/clients/react-native/manual-setup/#android). Android native crash is still not being reported.

**Comment by WatsonFungHK** [comment]
> @tabfed it's not worked out

neither me. The support on android is dissappointing

**Comment by MaxInMoon** [comment]
In my case, it only worked on Android on a RELEASE build, not in DEV..
I guess that it's due to sourcemaps not being uploaded when running a DEV version, but not sure at all..

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
