### ISSUE TITLE
[android]android app use this module no send error report,when error happen

### ISSUE THREAD

**Issue by warfrogsdf** [getsentry/sentry-react-native#513]
OS:
- [ ]  Windows
- [√ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [√ ]  Android

v10.4.0
6.1.0

opt_react_native@0.0.1 /Users/tab/work/opt_rn
├── @sentry/wizard@0.12.1
├── ajv@6.5.0
├── axios@0.18.0
├── core-js@2.5.7
├── dayjs@1.7.7
├── es6-symbol@3.1.1
├── mobx@4.3.0
├── mobx-react@5.2.8
├── prop-types@15.6.2
├── UNMET PEER DEPENDENCY react@16.6.0-alpha.8af6728
├── react-native@0.57.4
├── react-native-gesture-handler@1.0.9
├── react-native-growingio@0.0.1 invalid
├── react-native-image-picker@0.27.1
├── react-native-image-zoom-viewer@2.2.24
├── react-native-linear-gradient@2.4.4
├── react-native-progress-circle@2.0.1
├── react-native-sentry@0.37.1
├── react-native-storage@0.2.3
├── react-native-swiper@1.5.13
├── react-native-tab-view@1.3.1
├── react-navigation@3.0.0

```
<!-- Replace this -->
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

i install this module，ios app eroor can report to website，but android apps error no report。

**Steps to reproduce:**
- follow recommend steps install this module
-publish app
-but android app can report error，ios app not report, chales no see android app send error report, when error happen

**Actual result:**
- -but android app can report error，ios app not report

**Expected result:**
- android app can report error

**Comment by NelGarbuzova** [comment]
+1

Dependencies
```
"react-native": "0.57.5",
"react-native-sentry": "0.38.2",
```

I config Sentry by this
`Sentry.config('my dsn key').install();`

Sending errors via 
```
Sentry.captureException(err, {
                logger: logger
            });
```
also stoped work.

Everything worked fine, but not now. Few days ago I updated project to RN 0.57.5. Maybe it is some related to issue's causes.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
