### ISSUE TITLE
CodePush version conflicts for set-commits

### ISSUE THREAD

**Issue by dgobaud** [getsentry/sentry-react-native#533]
Following up on this https://github.com/getsentry/react-native-sentry/issues/459

I have Android and iOS apps using CodePush in App Center.

From the above issue yes I see if eg Android is on v1 and iOS is on v2, later when Android gets up to v2 it will upload its artifacts to the existing v2 release which already has the iOS artifacts.

This is definitely a bit confusing/hard to browse in the release list since the original v2 release which is most current for Android could be buried behind a bunch of iOS only releases.

Now the bigger problem I think is what about associating commits? When iOS released I did `releases set-commits auto`.

Now Android is going to release to v2 and run `releases set-commits auto` again on the same release.

It seems you need to:

1. Add the platform string into the release name

2. Allow the release name to be specified in the `react-native appcenter` command.

**Comment by marandaneto** [comment]
@jennmueng how do you usually do it?
looking at https://docs.sentry.io/platforms/react-native/manual-setup/codepush/
you can specify the platform + dist

**Comment by jennmueng** [comment]
@marandaneto @dgobaud You should be able to specify the platform in the dist, will make a documentation note for it.

**Comment by dgobaud** [comment]
@jennmueng where or how exactly?

**Comment by jennmueng** [comment]
@dgobaud 
```javascript
Sentry.init({
  ...
  dist: Platform.OS
})
```

and also set the `dist` when you upload the sourcemaps.

**Comment by dgobaud** [comment]
@jennmueng how do you do it with sourcemap upload? We are doing it with Sentry.init() maybe something was added to support sourcemap upload dist i don't think it did before?

**Comment by jennmueng** [comment]
@dgobaud See the `--dist` in the `sentry-cli react-native appcenter` command here in the last code block: https://docs.sentry.io/platforms/react-native/manual-setup/codepush/#making-releases
