### ISSUE TITLE
Android react-native appcenter puts *s in name

### ISSUE THREAD

**Issue by dgobaud** [getsentry/sentry-react-native#534]
`sentry-cli react-native appcenter --print-release-name ... android build/CodePush` generates a name such as com.passfolio.app.***-codepush:v8

Using the name with the *s in `releases set-commits` and `releases deploys` seems to work though and on the website under releases it has the full name com.passfolio.app.internal-codepush:v8

This does not happen with iOS release `sentry-cli react-native appcenter --print-release-name ... ios build/CodePush`

**Comment by ianjsikes** [comment]
I've encountered the same thing. In the Sentry gradle script that automatically uploads sourcemaps, this is the output:
```
> Task :app:bundleReleaseJsAndAssets_SentryUpload
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release us.client.***.mobile-2.3 distribution 9
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File processing complete
```

My android sourcemaps are not working in Sentry, and idk if this is the cause or just some weird security feature.

**Comment by marandaneto** [comment]
@jennmueng do you know if the release format generated by code push isn't allowed?

**Comment by marandaneto** [comment]
in case the generated names are not accepted, you can use custom `release` and `dist` https://docs.sentry.io/platforms/react-native/sourcemaps/#using-custom-release-and-distribution
