### ISSUE TITLE
[IOS] : Not capture event when build release mode

### ISSUE THREAD

**Issue by minhduc1911983** [getsentry/sentry-react-native#535]
Hi everybody

I working with Sentry for trace javascript exception in React Native app. Everything work very well when i runing debug mode but when i run in release mode then no events capture in Sentry dashboard. Pls help me this problem

Thanks all
Regards

**Comment by sregg** [comment]
I'm seeing the exact same issue. @minhduc1911983 did you find a fix?

**Comment by richardzyx** [comment]
Seeing this same issue on iOS with React Native v55.4

**Comment by HazAT** [comment]
Hey, so in release mode, we do not immediately send the events, instead we store it and either send it on the next app start or next `captureMessage`.
This is just a safety measure to make sure we don't lose events.

We will fix this "bug" in the next major bump that we are currently working on.

**Comment by marcelschulze** [comment]
I did implement it last week and during my testing in debug mode, everything worked fine. Now I saw the first crash on the real production app and I didn't receive any error :/. We already did restart the App multiple times afterwards. Maybe I will try to upgrade to 0.60 react and the new version now.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
