### ISSUE TITLE
React Native link without wizard

### ISSUE THREAD

**Issue by maykonmichel** [getsentry/sentry-react-native#540]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.12.0
6.7.0
react-native-template-ez-devs@0.3.1
├── axios@0.18.0
├── lodash@4.17.11
├── moment@2.24.0
├── prop-types@15.6.2
├── react@16.6.3
├── react-native@0.57.8
├── react-native-firebase@5.2.1
├── react-native-gesture-handler@1.0.15
├── react-native-splash-screen@3.1.1
├── react-native-vector-icons@6.2.0
├── react-navigation@3.1.4
├── react-redux@6.0.0
├── redux@4.0.1
├── redux-actions@2.6.4
├── redux-devtools-extension@2.13.8
├── redux-persist@5.10.0
├── redux-saga@0.16.2
└── reselect@4.0.0
```

Config:

```
No particular configuration
```

---
I have following issue:

Hello,
When I started with Sentry I loved the wizard, it's really amazing!
But I'd like to use it in my [react-native-template-ez-devs](https://www.npmjs.com/package/react-native-template-ez-devs) and the wizard broke it. Could you add an option to not run the wizard when link react-native?

**Steps to reproduce:**
I had removed sentry at 0.1.1 version of my template, but what I did was: 
- react-native init myApp --template ez-devs

**Actual result:**
- react native crashes when linking

**Expected result:**
- Do not link sentry

**Comment by HazAT** [comment]
`yarn sentry-wizard -i reactNative -p ios android`

I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
