### ISSUE TITLE
Android doesn't report errors, iOS is fine

### ISSUE THREAD

**Issue by Komalov** [getsentry/sentry-react-native#541]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

├── @babel/core@7.2.2
├── axios@0.18.0
├── crypto-js@3.1.9-1
├── lodash@4.17.5
├── lottie-react-native@2.5.10
├── metro-react-native-babel-preset@0.51.1
├── mobx@4.8.0
├── mobx-logger@0.7.1
├── mobx-react@5.4.3
├── UNMET PEER DEPENDENCY react@16.7.0
├── react-native@0.57.8
├── react-native-amplitude-analytics@0.2.6
├── react-native-appmetrica@0.1.1
├── react-native-blur@3.2.2
├── react-native-code-push@5.5.2
├── react-native-collapsible@1.3.0
├── react-native-cookies@3.3.0
├── react-native-crypto@2.1.2
├── react-native-device-info@0.25.0
├── react-native-dropdownalert@3.9.1
├── react-native-fbsdk@0.8.0
├── react-native-i18n@2.0.12
├── react-native-iphone-x-helper@1.2.0
├── react-native-keyboard-aware-scroll-view@0.8.0
├── react-native-linear-gradient@2.5.3
├── react-native-markdown-view@1.1.4
├── react-native-notifications@1.2.0
├── react-native-orientation@3.1.3
├── react-native-prompt-android@0.3.3
├── react-native-randombytes@3.5.1
├── react-native-restart@0.0.8
├── react-native-router-flux@4.0.1
├── react-native-sentry@0.40.2
├── react-native-spinkit@1.1.1
├── react-native-swipe-gestures@1.0.2
├── react-native-swiper@1.5.13
├── react-native-text-input-mask@0.8.0
├── react-native-vector-icons@6.1.0
├── react-native-version-number@0.3.4
├── react-native-video@4.3.1
└── react-native-vkontakte-login@0.3.22

Config:

```
Sentry.config('<custom>', {
      deactivateStacktraceMerging: true
}).install()
```

---
I have following issue:

I have used sentry for long time, but then I realised it did not report androids, I haven't even this device family on my project page

![ios only](https://user-images.githubusercontent.com/26224268/52401722-d3bb9080-2adb-11e9-9d21-0415046a68aa.png)
![ios only again](https://user-images.githubusercontent.com/26224268/52401723-d3bb9080-2adb-11e9-83ac-63bac4327e66.png)

**Steps to reproduce:**

I using bitrise for configuring and this is all react-native-sentry related stuff down here

```
:react-native-sentry:preBuild UP-TO-DATE
:react-native-sentry:preReleaseBuild UP-TO-DATE
:react-native-sentry:checkReleaseManifest
:react-native-sentry:processReleaseManifest
:react-native-sentry:compileReleaseAidl
:react-native-sentry:packageReleaseRenderscript NO-SOURCE
Processing react-native sourcemaps for Sentry upload.
:react-native-sentry:compileReleaseRenderscript
:react-native-sentry:generateReleaseResValues
:react-native-sentry:generateReleaseResources
:react-native-sentry:packageReleaseResources
:react-native-sentry:platformAttrExtractor
:react-native-sentry:generateReleaseRFile
:react-native-sentry:generateReleaseBuildConfig
:react-native-sentry:prepareLintJar
:react-native-sentry:generateReleaseSources
:react-native-sentry:javaPreCompileRelease
:react-native-sentry:compileReleaseJavaWithJavacNote: /Users/vagrant/git/node_modules/react-native-sentry/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
:react-native-sentry:processReleaseJavaRes NO-SOURCE
:react-native-sentry:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:react-native-sentry:mergeReleaseShaders
:react-native-sentry:compileReleaseShaders
:react-native-sentry:generateReleaseAssets
:react-native-sentry:packageReleaseAssets
:react-native-sentry:mergeReleaseConsumerProguardFiles
Reading program jar [/Users/vagrant/.gradle/caches/modules-2/files-2.1/io.sentry/sentry-android/1.7.5/11638ecd968ea5766791d9b6525fd166cac37c5c/sentry-android-1.7.5.jar] (filtered)
Reading program jar [/Users/vagrant/.gradle/caches/modules-2/files-2.1/io.sentry/sentry/1.7.5/34a08993cd333b3765eb4ed340be87f9a967c27e/sentry-1.7.5.jar] (filtered)
Reading program jar [/Users/vagrant/git/node_modules/react-native-sentry/android/build/intermediates/intermediate-jars/release/classes.jar] (filtered)
Note: the configuration keeps the entry point 'io.sentry.RNSentryModule { io.sentry.event.Event buildEvent(io.sentry.event.EventBuilder); }', but not the descriptor class 'io.sentry.event.EventBuilder'
Note: the configuration keeps the entry point 'io.sentry.RNSentryModule { void addExceptionInterface(io.sentry.event.EventBuilder,java.lang.String,java.lang.String,com.facebook.react.bridge.ReadableNativeArray); }', but not the descriptor class 'io.sentry.event.EventBuilder'
Note: the configuration keeps the entry point 'io.sentry.RNSentryModule { void setRelease(io.sentry.event.EventBuilder); }', but not the descriptor class 'io.sentry.event.EventBuilder'
  Copying resources from program jar [/Users/vagrant/.gradle/caches/modules-2/files-2.1/io.sentry/sentry-android/1.7.5/11638ecd968ea5766791d9b6525fd166cac37c5c/sentry-android-1.7.5.jar] (filtered)
  Copying resources from program jar [/Users/vagrant/.gradle/caches/modules-2/files-2.1/io.sentry/sentry/1.7.5/34a08993cd333b3765eb4ed340be87f9a967c27e/sentry-1.7.5.jar] (filtered)
  Copying resources from program jar [/Users/vagrant/git/node_modules/react-native-sentry/android/build/intermediates/intermediate-jars/release/classes.jar] (filtered)
:react-native-sentry:compileReleaseNdk NO-SOURCE
:react-native-sentry:mergeReleaseJniLibFolders
:react-native-sentry:transformNativeLibsWithMergeJniLibsForRelease
:react-native-sentry:transformNativeLibsWithStripDebugSymbolForRelease
:react-native-sentry:transformNativeLibsWithIntermediateJniLibsForRelease
:react-native-sentry:extractReleaseAnnotations
:react-native-sentry:transformResourcesWithMergeJavaResForRelease
:react-native-sentry:transformClassesAndResourcesWithSyncLibJarsForRelease
:react-native-sentry:transformNativeLibsWithSyncJniLibsForRelease
:react-native-sentry:bundleRelease
:react-native-sentry:compileReleaseSources
:react-native-sentry:mergeReleaseResources
:react-native-sentry:verifyReleaseResources
:react-native-sentry:assembleRelease
```

If my server shuts down, I cannot build an app because of "Api request failed", what is correct. I am completely following instructions from guide

**Actual result:**
Like I said there is no errors for longer than half a year. I tried to upgrade this few times, as earlier - ios works and android never does.

**Expected result:**
Reporting

I think the problem is somewhere on my side, but I do need some help to point what I do wrong with android configuring

**Comment by WatsonFungHK** [comment]
I have a similar problem as well. Even though I can record js error from android, sentry does not receive native crash (triggered by sentry.nativeCrash()) from android.
Strangely enough, Sentry.isNativeClientAvailable() return true on android.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by DavitVosk** [comment]
Hi all. I am using `@sentry/react-native` and sometimes when the app is crashing on IOS - sentry is not reporting it. What is the problem? Who can assist me with this? Thanks
