### ISSUE TITLE
cannot send native crash from android (simulator)

### ISSUE THREAD

**Issue by WatsonFungHK** [getsentry/sentry-react-native#545]
OS:
- [ ]  Windows
- [Y]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [Y]  Android

v8.11.1
5.6.0
├── @lingui/react@2.7.2
├── appcenter@1.10.0
├── appcenter-analytics@1.10.0
├── appcenter-crashes@1.10.0
├── events@3.0.0
├── mockdate@2.0.2
├── moment@2.23.0
├── react@16.6.1
├── react-native@0.57.5
├── react-native-code-push@5.4.2
├── react-native-fbsdk@0.8.0
├── react-native-firebase@5.1.1
├── react-native-gesture-handler@1.0.15
├── react-native-gifted-chat@0.5.0
├── react-native-google-analytics-bridge@7.0.0
├── react-native-google-signin@1.0.2
├── react-native-sentry@0.41.1
├── react-native-splash-screen@3.1.1
├── react-native-vector-icons@6.1.0
├── react-navigation@3.0.9
├── react-navigation-redux-helpers@2.0.8
├── react-redux@5.1.1
├── redux@4.0.1
├── redux-form@7.4.2
├── redux-logger@3.0.6
├── redux-persist@5.10.0
├── redux-saga@0.16.2
├── styled-components@4.1.3
├── twilio-chat@3.2.0
└── util@0.11.1

---
Native crash on android, which I triggered by Sentry.nativeCrash, could not be delivered to sentry. iOS is fine. Please help fix it

**Steps to reproduce:**
Step 1, put the follow try catch block as an onPress callback
`
       try {
          Sentry.nativeCrash();
        } catch (err) {
          Sentry.captureException(err);
        }
`
Step 2, initiate the app (I did it through simulator)

Step 3, click and wait for a native crash

**Actual result:**
No error is reported if it is on android. iOS is fine

**Expected result:**
Native crash should be reported from both android and iOS

**Comment by WatsonFungHK** [comment]
I have made sure MainApplication.java has the following code

`
import io.sentry.RNSentryPackage;

public class MainApplication extends Application implements ReactApplication {
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNSentryPackage(),
      )
    }
`

**Comment by WatsonFungHK** [comment]
problem solved. android native crash event is only reported from real devices

**Comment by maxammann** [comment]
Is this expected behavior? In my opinion errors from JS and native should be reported in the simulator.

**Comment by alburdette619** [comment]
It seems that on debug, the error is swallowed by the red screen.  The app is not crashing.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
