### ISSUE TITLE
RNSentryModule.captureEvent is ignoring environment

### ISSUE THREAD

**Issue by erlendfh** [getsentry/sentry-react-native#547]
https://github.com/getsentry/react-native-sentry/blob/f0f56e7579d0a0b870ef2a3e01675d74bfc6042c/android/src/main/java/io/sentry/RNSentryModule.java#L216

Somewhere around here I would have expected to find

```
        if (event.hasKey("environment")) {
            eventBuilder.withEnvironment(event.getString("environment"));
        }
```
Has this been left out on purpose or can it just be added?

**Comment by HazAT** [comment]
Probably forgot it, if you go ahead and create a PR for it I would happily merge it :)

**Comment by HazAT** [comment]
This should be fixed.
