### ISSUE TITLE
No crash data sent on 'real' error (not throw new Error)

### ISSUE THREAD

**Issue by bialasik** [getsentry/sentry-react-native#549]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.4
5.6.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
   logLevel: __DEV__ ? SentryLog.Debug : SentryLog.None,
}).install()
```

---
Hello. The app doesn't send a crash event from client when it's real crash (not the `throw new Error` one). It does send errors triggered manually (by throw new Error). Tested on iOS simulator in development mode.

**Steps to reproduce:**
- create some faulty code in the app, but able to build, like someObject.nonExistingField.nonExistingField

**Actual result:**
- I have an error and red screen on Simulator "TypeError: undefined is not an object (evaluating someObject.nonExistingField.nonExistingField) but there's no error reported to Sentry.

**Expected result:**
- error is reported to Sentry and I can see it on the dashboard

**Comment by WatsonFungHK** [comment]
did you try Sentry.nativeCrash() ? what is the result

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
