### ISSUE TITLE
SentryCrashReportStore.c missing #include <time.h>

### ISSUE THREAD

**Issue by arosendorff** [getsentry/sentry-react-native#550]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.12.0
6.4.1

├── @nozbe/watermelondb@0.10.0
├── @nozbe/with-observables@1.0.2
├── axios@0.18.0
├── intl@1.2.5
├── jsc-android@236355.0.0
├── moment@2.23.0
├── UNMET PEER DEPENDENCY react@16.7.0
├── react-intl@2.7.2
├── UNMET PEER DEPENDENCY react-native@0.57.8
├── react-native-animatable@1.3.1
├── react-native-camera-kit@7.3.3
├── react-native-elements@0.19.1
├── react-native-gesture-handler@1.0.15
├── react-native-maps@0.22.1
├── react-native-orientation@3.1.3
├── react-native-sentry@0.42.0
├── UNMET PEER DEPENDENCY react-native-vector-icons@6.1.0
├── react-navigation@3.2.1
├── redux-saga@0.16.2
├── render-if@0.1.1
├── rn-fetch-blob@0.10.15
├── rxjs@6.3.3
└── styled-components@4.1.3

npm ERR! peer dep missing: react@16.6.3, required by react-native@0.57.8
npm ERR! peer dep missing: react-native@^0.56.0, required by @nozbe/watermelondb@0.10.0
npm ERR! peer dep missing: react-native-vector-icons@^4.2.0, required by react-native-elements@0.19.1
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-jsx@5.0.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

When attempting to build my RN application for iOS, I get the following errors:
![screenshot 2019-02-19 at 11 49 58](https://user-images.githubusercontent.com/1186123/53005748-8674e280-343c-11e9-8cea-e264ace879fd.png)

These errors all originate from `SentryCrashReportStore.c` and I have found that adding `#include <time.h>` to that file fixes them. Has anyone else encountered this issue? I am assuming that it usually works fine without requiring that `#include`, so I am not sure why it is required for my build to work.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
