### ISSUE TITLE
trimHeadFrames: Discarded unknown attribute and Source Maps not Applying

### ISSUE THREAD

**Issue by rgbdelta** [getsentry/sentry-react-native#556]
OS:
- [ ]  Windows
- [ x]  MacOS
- [ ]  Linux

_Platform:_
- [ x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.12.0
6.4.1
views@0.0.1 /Users/***/***
├── @terrylinla/react-native-sketch-canvas@0.8.0
├── ios-deploy@1.9.4
├── jwt-decode@2.2.0
├── lodash@4.17.11
├── mobx@4.8.0
├── mobx-react@5.4.3
├── moment@2.23.0
├── navbar-native@1.6.1
├── react@16.6.0-alpha.8af6728
├── react-native@0.57.3
├── react-native-animatable@1.3.1
├── react-native-animated-linear-gradient@1.1.2
├── react-native-firebase@5.2.0
├── react-native-fs@2.13.3
├── react-native-gesture-handler@1.0.12
├── react-native-image-picker@0.27.2
├── react-native-linear-gradient@2.5.3
├── react-native-maps@0.22.1
├── react-native-modal@7.0.2
├── react-native-modal-datetime-picker@6.0.0
├── react-native-permissions@1.1.1
├── react-native-photo-view-ex@1.0.4
├── react-native-qrcode-svg@5.1.1
├── react-native-reanimated@1.0.0-alpha.11
├── react-native-router-flux@4.0.6
├── react-native-sentry@0.42.0
├── react-native-svg@8.0.10
├── react-native-tab-view@1.3.1
├── react-native-vector-icons@6.1.0
├── react-native-view-shot@2.5.0
├── react-navigation@3.3.2
├── react-navigation-stack@1.0.10
├── recyclerlistview@1.3.4
├── rn-fetch-blob@0.10.15
├── rn-placeholder@1.3.2
└── rn-viewpager@1.2.9
```

Config:

```
Sentry.config(environment.SENTRY_DSN).install();
```

---
I have following issue:

![Screen Shot 2019-03-14 at 11 21 15 am](https://user-images.githubusercontent.com/8350240/54322980-5f7c8b80-464b-11e9-81d6-a6bf85e08248.png)
![Screen Shot 2019-03-14 at 11 21 27 am](https://user-images.githubusercontent.com/8350240/54322981-5f7c8b80-464b-11e9-8459-3ea1e9aa1e0a.png)
![Screen Shot 2019-03-14 at 11 27 33 am](https://user-images.githubusercontent.com/8350240/54323190-38728980-464c-11e9-9afd-54c2c2aa3ca4.png)

**Steps to reproduce:**
- Populate index.js with the react native plugin for sentry
- Create a Logger file and initialise sentry
- Run the uploadSourceMaps script to bundle and upload our artifacts
- This  `trimHeadFrames: Discarded unknown attribute` has nothing to do with artifacts it seems because the error is still the same when I delete them all
```
// index.js

import './polyfill';
import { AppRegistry } from 'react-native';
import { App } from './src/App';
import { name as appName } from './app.json';
import Raven from 'raven-js';

require('react-native-sentry/lib/raven-plugin')(Raven);

AppRegistry.registerComponent(appName, () => App);
```

```
// Logger.ts

Sentry.config(environment.SENTRY_DSN).install();

Sentry.setRelease(environment.RELEASE);
Sentry.setTagsContext({
  environment: environment.APP_ENV,
  react: true,
});
```

```
// uploadSourceMaps.sh

SOURCE_MAP_PATH='.dist/main.jsbundle.map'
SOURCE_PATH='.dist/main.jsbundle'

rm -rf .dist/main.jsbundle.map
rm -rf .dist/main.jsbundle
react-native bundle \
  --dev false \
  --entry-file index.js \
  --bundle-output $SOURCE_PATH \
  --sourcemap-output $SOURCE_MAP_PATH

./node_modules/@sentry/cli/sentry-cli \
  --auth-token $SENTRY_AUTH_TOKEN \
  releases \
  --org *** \
  --project *** \
  files $RELEASE \
  upload $SOURCE_PATH "~/main.jsbundle" \

./node_modules/@sentry/cli/sentry-cli \
  --auth-token $SENTRY_AUTH_TOKEN \
  releases \
  --org *** \
  --project *** \
  files $RELEASE \
  upload-sourcemaps $SOURCE_MAP_PATH \
  --rewrite \
  --validate
```

**Actual result:**
- Stack traces aren't source mapped on the Sentry issue
- Sentry issue displayed message `There was 1 error encountered while processing this event` `trimHeadFrames: Discarded unknown attribute`

**Expected result:**
- I expected no errors and I expected my stack trace to be source mapped

**Comment by rmit-s3539777-abgier-avraha** [comment]
Solved:

Turns out my environment tag that I was logging with didn't match the environment of my artifacts. So I just removed that.

```
Sentry.setTagsContext({
  // environment: environment.APP_ENV,
  react: true,
});
```

**Comment by cruzach** [comment]
@rmit-s3539777-abgier-avraha did you ever find out what could be causing the `trimHeadFrames: Discarded unknown attribute`? I'm getting the same message

**Comment by rmit-s3539777-abgier-avraha** [comment]
@cruzach I didn't but does it affect anything for you? My source maps started working after removing the environment property.

**Comment by cruzach** [comment]
Doesn't *seem* to be affecting anything. 

But even then, it's an eye sore so was curious what the root cause might be/how to get rid of it

**Comment by untitaker** [comment]
Hey, this can be safely ignored. This issue only surfaced recently because we implemented stricter payload validation on the server. We will fix this in the next major version of the SDK.

**Comment by cruzach** [comment]
Awesome! That’s great to hear

Out of curiosity- do you have an ETA for the release?

**Comment by untitaker** [comment]
No ETA, but we hope to get it out within the next weeks. Track this PR: https://github.com/getsentry/react-native-sentry/pull/589

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
