### ISSUE TITLE
Duplicate/Invalid releases

### ISSUE THREAD

**Issue by samratshekhar** [getsentry/sentry-react-native#559]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.15.1
6.4.1
├── @sentry/wizard@0.10.3
├── @types/jest@23.0.0
├── @types/react@16.3.16
├── @types/react-native@0.55.17
├── @types/react-test-renderer@16.0.1
├── @types/url-parse@1.4.3
├── accordion-collapse-react-native@0.1.9
├── immutable@3.8.2
├── jslint@0.12.1
├── moment@2.24.0
├── prop-types@15.7.2
├── properties-reader@0.0.16
├── UNMET PEER DEPENDENCY react@16.3.1
├── UNMET PEER DEPENDENCY react-native@0.55.4
├── react-native-bottom-sheet-behavior@1.0.0 (git+https://github.com/org/react-native-bottom-sheet-behavior.git#cf080cad83d9e2457c8d092dba06c401227509ca)
├── react-native-calendars@1.22.0
├── react-native-camera@1.6.4
├── react-native-code-push@5.5.2
├── react-native-contacts-wrapper@0.2.4
├── react-native-i18n@2.0.15
├── react-native-keyboard-aware-scroll-view@0.5.0
├── react-native-linear-gradient@2.5.3
├── react-native-navigation@1.1.493
├── react-native-sentry@0.39.1
├── react-native-simple-gauge@0.1.11
├── react-native-snap-carousel@3.7.5
├── react-native-star-rating@1.1.0
├── react-native-swipeout@2.3.6
├── react-native-switch-selector@1.1.11
├── react-native-text-gradient@0.0.13 (git+https://github.com/org/react-native-text-gradient.git#bab89c079be43d33db23c79d23c06fe4dcff0355)
├── react-native-timer@1.3.4
├── react-native-vector-icons@6.3.0
├── react-native-view-more-text@2.0.1
├── react-redux@5.1.1
├── react-timer-mixin@0.13.4
├── reduce@1.0.1
├── redux@4.0.1
├── redux-logger@3.0.6
├── redux-thunk@2.3.0
└── url-parse@1.4.4

npm ERR! peer dep missing: react@16.2.0, required by accordion-collapse-react-native@0.1.9
npm ERR! peer dep missing: react-native@0.53.0, required by accordion-collapse-react-native@0.1.9
npm ERR! peer dep missing: react-native@>=0.56.0, required by react-native-sentry@0.39.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
	deactivateStacktraceMerging: true,
    disableNativeIntegration: false,
    logLevel: SentryLog.Error,
    handlePromiseRejection: true
}).install()
```

---
I have following issue:

We have a custom release creation and artefact upload mechanism in place. Our releases are generally of the form 
```
com.package-{app_version}@{package_version}
```
This works fine with the following client side code:
```
Sentry.setRelease(`com.package-${appVersion}@${packageVersion}`);
```

But lately, we're noticing few anomalies with our releases, wherein
- There are duplicate releases with no artefacts. The releases made by our CI servers are correct since they have artefacts with valid `dist`. While we are currently clueless as to why redundant releases are being created.
<img width="441" alt="Screenshot 2019-03-15 at 6 59 39 PM" src="https://user-images.githubusercontent.com/25629471/54434538-870b4b00-4754-11e9-9fc8-1822e1063914.png">

- There are totally new releases created with missing `@{package_version}` part in the release name. This is even weirder, since if we assume that `package_version` is empty string while we set release for Sentry on client end, the release will still end with `@` as evident in the string interpolation.
<img width="445" alt="Screenshot 2019-03-15 at 7 02 47 PM" src="https://user-images.githubusercontent.com/25629471/54434773-026cfc80-4755-11e9-8510-facdc5ef1cef.png">

**Steps to reproduce:**
- Step
Issue in release management

**Actual result:**
- Actual
Releases should be unique and dictated by release management and/or setting release in Sentry SDK
**Expected result:**
- Result
Duplicate releases and releases with invalid version

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
