### ISSUE TITLE
How to disable sentry in development ?

### ISSUE THREAD

**Issue by DiksonSamuel** [getsentry/sentry-react-native#562]
**Actual result:**
- Actual
Cannot disable sentry in development
**Expected result:**
- Result
Should there be way to disable sentry in development

**Comment by sryze** [comment]
You can add something like this to your index.js:

```
if (!__DEV__) {
    Sentry.config(...).install();
}
```

**Comment by wouterds** [comment]
At runtime or build time?

**Comment by lucianomlima** [comment]
And for Android projects, in gradle?
[This issue](https://github.com/getsentry/react-native-sentry/issues/234) approach doesn't work.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by nihp** [comment]
I am struggling for 5 days with my build failure. Can anyone know solution for the below.

When I archiving the file it shows the error as
**Continuing in background.**
**Failed to display Xcode notification**


```
Showing All Errors Only
+ [[ ! -f /Users/name/Library/Developer/Xcode/DerivedData/Appp-cperpitadfajoqxnkn/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Appp.app/main.jsbundle ]]

Continuing in background.
Failed to display Xcode notification
  caused by: script error: osascript: no such component "JavaScript".

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.


```
This will produced after quitting my Xcode the upload notification of sentry will shown in my window. After that it showing Continuing in background and shows. Failed to display Xcode notification

**Comment by pranshuchittora** [comment]
Alternatively, setting dsn value based on env can also disable sentry in dev. 

```
dsn : ENV_DEV ? undefined : 'SENTRY_DSN_URI'
```

**Comment by roni-castro** [comment]
According to the [options docs](https://github.com/getsentry/sentry-javascript/blob/8c2aa1b883785ab1ce5f7c8173907f5fcbf39912/packages/types/src/options.ts#L39-L40)\, it suggests setting dns to `undefined`. 
>    * The Dsn used to connect to Sentry and identify the project. If omitted, the
>    * SDK will not send any data to Sentry.
native/issues/4247) and keep sending them
```js
Sentry.init({
  dsn: __DEV__
    ? undefined
    : "YOUR_SENTRY_DSN_URL"
})
```

Be careful with `enabled: !__DEV__`. It currently [keeps sending native errors generated in dev mode](https://github.com/getsentry/sentry-react-native/issues/4247)
