### ISSUE TITLE
[iOS] - Boolean values are not parsed as strings and don't show up in the dashboard

### ISSUE THREAD

**Issue by LuisRizo** [getsentry/sentry-react-native#564]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
❯ node -v && npm -v && npm ls --prod --depth=0
v11.8.0
6.5.0
# The rest is NPM errors... Unrelated
npm ERR! missing: repeat-element@1.1.2, required by braces@1.8.5
npm ERR! missing: fill-range@2.2.3, required by expand-range@1.8.2
npm ERR! missing: is-number@2.1.0, required by fill-range@2.2.3
npm ERR! missing: isobject@2.1.0, required by fill-range@2.2.3
npm ERR! missing: randomatic@1.1.7, required by fill-range@2.2.3
```

react-native-sentry version: 0.38.2
sentry version: 0.1.2

Config:

```
Sentry.config(sentryDSN).install()
```

---
I have following issue:

On iOS, when sending booleans as data to the sentry Breadcrumbs, they don't show up in Sentry.

This is not the case on Android

**Steps to reproduce:**
- Sentry.captureBreadcrumb('action', 'Sending payload', { isAdmin: true})
- Sentry.captureMessage('Sending all logs to Sentry');

**Actual result:**
- The key `isAdmin` shows up in the breadcrumb, but its value is not displayed

**Expected result:**
- The key `isAdming` is followed by `true`

After checking the raw data from our users, I noticed that the boolean value is contained in the raw JSON without the quotation marks. On Android logs, all `true` and `false` booleans are now strings.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
