### ISSUE TITLE
Device info is not sent to the sentry

### ISSUE THREAD

**Issue by dophlin** [getsentry/sentry-react-native#567]
OS:
- [ ]  Windows
- [ X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.10.0
5.6.0
nativeCustomer@0.0.13 /Codes/clients/customer-android
├── appcenter@1.13.0
├── appcenter-analytics@1.13.0
├── appcenter-crashes@1.13.0
├── axios@0.18.0
├── lodash@4.17.11
├── parse@2.1.0
├── react@16.6.1
├── react-native@0.57.7
├── react-native-communications@2.2.1
├── react-native-device-info@0.24.3
├── react-native-fs@2.13.3
├── react-native-gesture-handler@1.0.12
├── react-native-image-picker@0.28.0
├── react-native-image-zoom-viewer@2.2.25
├── react-native-joi@0.0.5
├── react-native-maps@0.22.1
├── react-native-moment-jalaali@0.1.0
├── react-native-paho-mqtt@0.1.1
├── react-native-push-notification@3.1.2
├── react-native-ratings@6.3.0
├── react-native-sentry@0.42.0
├── react-native-simple-radio-button@2.7.3
├── react-native-sound@0.10.12
├── react-native-star-rating@1.1.0
├── react-native-uuid@1.4.9
├── react-native-vector-icons@6.2.0
├── react-navigation@3.0.9
├── react-redux@6.0.0
├── react_native_mqtt@1.3.1
├── redux@4.0.1
├── redux-persist@5.10.0
├── redux-persist-transform-filter@0.0.18
└── redux-thunk@2.3.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {}).install()
```

---
I have the following issue:
I am using the self-hosted sentry and I am using the official document in order to setup sentry for react-native, everything is fine except the device info is not sent to the sentry. This is the JSON file:

`{"id":"31375b1cda8440d5b1cdfd9cb27ea1e0","project":9,"release":null,"dist":null,"platform":"javascript","culprit":"","message":"TheMessage5","datetime":"2019-03-28T06:14:45.000000Z","time_spent":null,"tags":[["logger","javascript"],["sentry:user","id:952"],["level","info"]],"errors":[],"extra":{"session:duration":1091},"fingerprint":["{{ default }}"],"metadata":{"title":"TheMessage5"},"received":1553753685.0,"sdk":{"client_ip":"72.229.28.185","version":"3.27.0","name":"raven-js"},"sentry.interfaces.Breadcrumbs":{"values":[{"category":"Test5","timestamp":1553753754.046,"message":"breadcrumbMessage5","type":"default","data":{"page":"intro"}}]},"sentry.interfaces.Message":{"message":"TheMessage5"},"sentry.interfaces.User":{"username":"952","ip_address":"72.229.28.185","id":"952"},"type":"default","version":"7"}`

**Comment by Sourabh-** [comment]
Did you figure out what was the issue ?

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
