### ISSUE TITLE
Question: what does captureError(error, options) expect as options

### ISSUE THREAD

**Issue by pawelsas** [getsentry/sentry-react-native#571]
Hi,

I hope this is the right place for this question.
I'd like to pass a custom error message to the `captureError` function without triggering `captureMessage`.

I noticed that `captureError` may receive an options object but couldn't find any docs on it. Is it possible to pass my custom message as options?

I use sentry-expo.

Thanks.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
