### ISSUE TITLE
Sentry.setExtraContext sometimes breaks on Android emulator

### ISSUE THREAD

**Issue by raynor85** [getsentry/sentry-react-native#579]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v11.6.0
6.9.0
Fantastec@1.2.6 /Users/ruben/Documents/develop/Fantastec
├── @babel/plugin-transform-react-jsx-source@7.2.0
├── @react-native-community/async-storage@1.2.4
├── @react-native-community/netinfo@1.4.0
├── @sentry/cli@1.41.0
├── aws-amplify@1.1.22
├── axios@0.18.0
├── bad-words-relaxed@1.6.5
├── bulk-require@1.0.1
├── countries-list@2.4.2
├── flux-standard-action@2.0.4
├── formik@1.3.2
├── i18n-js@3.2.1
├── moment@2.22.2
├── query-string@6.5.0
├── UNMET PEER DEPENDENCY react@16.8.6
├── UNMET PEER DEPENDENCY react-native@0.59.3
├── react-native-branch@3.0.0-beta.3
├── react-native-card-flip@1.0.4 invalid
├── react-native-code-push@5.6.0
├── react-native-collapsible@1.4.0
├── react-native-color-matrix-image-filters@5.1.4
├── react-native-config@0.11.5 invalid
├── react-native-device-info@1.4.3
├── react-native-fast-image@5.2.0
├── react-native-firebase@5.2.3
├── react-native-gesture-handler@1.1.0
├── react-native-iap@2.4.4
├── react-native-iphone-x-helper@1.2.0
├── react-native-linear-gradient@2.5.4
├── react-native-localize@1.1.0
├── react-native-mixpanel@1.1.1
├── react-native-modal@9.0.0
├── react-native-modal-datetime-picker@6.1.0
├── react-native-picker-select@4.3.0 invalid
├── react-native-scrollable-tab-view@0.10.0
├── react-native-sensors@5.1.8
├── react-native-sentry@0.42.0
├── react-native-snap-carousel@3.7.5
├── react-native-swipe-list-view@1.5.3
├── react-native-video@4.3.1 invalid
├── react-navigation@3.5.1
├── react-redux@6.0.1
├── redux@4.0.1
├── redux-api-middleware@3.0.1
├── redux-thunk@2.3.0
├── request@2.88.0
└── ts-node@8.0.3

npm ERR! peer dep missing: react@16.8.3, required by react-native@0.59.3
npm ERR! peer dep missing: react-native@^0.49.1, required by react-native-card-flip@1.0.4
npm ERR! peer dep missing: react-native@^0.57.0, required by @react-native-community/async-storage@1.2.4
npm ERR! peer dep missing: react-native@>=0.57 <0.59, required by @react-native-community/netinfo@1.4.0
npm ERR! invalid: react-native-card-flip@1.0.4 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-card-flip
npm ERR! extraneous: prop-types@15.5.10 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-card-flip/node_modules/prop-types
npm ERR! invalid: react-native-config@0.11.5 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-config
npm ERR! invalid: react-native-picker-select@4.3.0 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-picker-select
npm ERR! invalid: react-native-video@4.3.1 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-video
npm ERR! extraneous: keymirror@0.1.1 /Users/ruben/Documents/develop/Fantastec/node_modules/keymirror
npm ERR! extraneous: prop-types@15.6.2 /Users/ruben/Documents/develop/Fantastec/node_modules/react-native-video/node_modules/prop-types
npm ERR! extraneous: shaka-player@2.4.7 /Users/ruben/Documents/develop/Fantastec/node_modules/shaka-player
npm ERR! invalid: xcode@1.0.1-dev /Users/ruben/Documents/develop/Fantastec/node_modules/@sentry/wizard/node_modules/xcode
npm ERR! extraneous: uuid@3.0.1 /Users/ruben/Documents/develop/Fantastec/node_modules/@sentry/wizard/node_modules/uuid
```

Config:

```
Sentry.config('https://47090e2d703b40d78d9e65c9b79c329f@sentry.io/1436813', {}).install();
```

---
I have following issue:

I have a log function called `log` that calls `Sentry.setExtraContext({ customData })` followed by `Sentry.captureException((new Error(errorString), { fingerprint: [errorString] }))` and then `Sentry.setExtraContext({ customData: undefined })`. Most of the time it works ok, but after many logs it happens that sentry start logging on its dashboard exceptions with the same `customData`. Example:

- log('error1', { foo: 'foo' }) // it logs in sentry a row having error name `error1` and additional data `customData: { foo: 'foo' }`
- log('error2', { hello: 'hello' }) // it logs in sentry a row having error name 'error2' and additional data `customData: { foo: 'foo' }` instead of `customData: { hello: 'hello' }`
- when it start happening once, all the other logs always record `customData: { foo: 'foo' }` rather the updated one.

I am sure that `Sentry.setExtraContext` called before `Sentry.captureException` always sets the expected updated `customData`, since I have tested it multiple times. I have experienced it happening on Android emulator, Pixel_API_27, and I wasn't able to replicate it using an iOS simulator. It happens with both a debug build and release build.

**Steps to reproduce:**
- Call the custom function multiple times on an Android emulator

**Actual result:**
- Sometimes `Sentry.setExtraContext({ customData })` seems to break

**Expected result:**
- Every time I call the custom function, `customData` should always be the updated value in the sentry dashboard

**Comment by raynor85** [comment]
I am using `Sentry.captureBreadcrumb({ message: errorString, data: customData })` as a workaround.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
