### ISSUE TITLE
Whats the preferred way to capture ios errors?

### ISSUE THREAD

**Issue by sslash** [getsentry/sentry-react-native#592]
I have a custom native module in iOS that I'd like to add crash reporting to.
How to hook up sentry with cocoa is described here: https://docs.sentry.io/clients/cocoa/, but given that I already initialize Sentry the react-native way in appDelegate, its not clear what is the preferred way to do this? An example for how to do this would be awesome! E.g:

```
// myNativeModule.swift
import Sentry // <-- like this, or via react-native-sentry?

// need to initialize sentry?

func doSomething() {
 do somethingElse() {
   } catch let error {
      Sentry.captureException(error) // correct api?
   }
}

```

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
