### ISSUE TITLE
console.error() logs reports to sentry

### ISSUE THREAD

**Issue by nasmuris** [getsentry/sentry-react-native#597]
Hello,
In our project we have dozens of error reports `captureMessage undefined`. I discovered those are results of calling `console.error()`. Is this intended behavior, if so, is there any possibility to either get correct message or to turn this off and `captureMessage` only where I really want to?
Thanks in advance
using "react-native-sentry": "^0.42.0"
<img width="1054" alt="Snímek obrazovky 2019-06-06 v 17 26 09" src="https://user-images.githubusercontent.com/22944924/59045405-4d903a80-8880-11e9-8d81-a03627c53e99.png">

**Comment by AleksandrZhukov** [comment]
try to use `console.reportErrorsAsExceptions = false;`

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
