### ISSUE TITLE
Crashes not rendering for Android release build.Working in Debug

### ISSUE THREAD

**Issue by himanshug16** [getsentry/sentry-react-native#598]
OS:
  MacOS

_Platform:_
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

I have following issue:

Android Release build not working for Android Release build.It is working in Debug Mode.Not sure what's wrong.Couldn't able to release to Play Store because of the issue.

**Actual result:**
Nothing happens for Release build.

**Expected result:**
It should show JS Crashes on Sentry console when in release mode.

Versions Info: 
 "react-native": "^0.53.3",

"react": ^16.2.0”

"react-native-sentry": "^0.43.1”,

![Screen Shot 2019-06-07 at 3 52 29 PM](https://user-images.githubusercontent.com/32382466/59098133-1af84780-893d-11e9-981f-7562eb133f77.png)
![Screen Shot 2019-06-07 at 3 52 59 PM](https://user-images.githubusercontent.com/32382466/59098140-1fbcfb80-893d-11e9-942d-0185bffade10.png)
@HazAT

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
