### ISSUE TITLE
Sourcemaps not working with latest haul

### ISSUE THREAD

**Issue by yongching** [getsentry/sentry-react-native#599]
OS:
- [x]  MacOS

_Platform:_
- [x]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
├── react@16.8.3
├── react-dom@16.6.1
├── react-hot-loader@4.8.0
├── UNMET PEER DEPENDENCY react-native@0.59.0
└── react-native-sentry@0.43.1

npm ERR! peer dep missing: react-native@^0.57.0, required by haul@1.0.0-rc.15
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
    environment: "dev"
}).install()
```

---
I have following issue:

I'm current using `react-native 0.59.0` & `haul 1.0.0-rc.15` but sentry seems to be not working correctly. I'm expecting it to display the original code where the error was thrown (line 28 in App.js). It happens in both ios & android.

Here's the raw json event: 
https://codeshare.io/2KbjLo

**Steps to reproduce:**
1. git clone https://github.com/yongching/sentry-sourcemap
2. yarn && yarn ioshaul 
3. react-native run-ios / run-android

**Actual result:**
<img width="833" alt="Screenshot 2019-06-09 at 6 32 07 PM" src="https://user-images.githubusercontent.com/10132189/59157912-b3c9c700-8ae5-11e9-9a3e-6aac2701c388.png">

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
