### ISSUE TITLE
Wrong source maps for distribution version

### ISSUE THREAD

**Issue by AleksandrZhukov** [getsentry/sentry-react-native#600]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Config:

```
Sentry.config('https://...@sentry.io/...', {
 logLevel: SentryLog.Debug
}).install()
```

---
I have following issue:

Seems it takes wrong source maps for the new dist version

**Steps to reproduce:**
- create release 1.0 with dist 1
- change some code near the defected code
- create a build with incremented dist version
- run the app and produce the error 
- check stack trace for this error

**Actual result:**
- source maps correspond to build with dist equal 1

**Expected result:**
- source maps correspond to build with dist equal 2

**Comment by HazAT** [comment]
Hey @AleksandrZhukov  👋 😄
Did you upload also the new bundle to sentry with `sentry-cli`?
Also, can you send a link to your account?

**Comment by AleksandrZhukov** [comment]
Hey 🤝 
yes, in Artifacts tab I have 2 builds and 2 source maps for them
https://sentry.io/organizations/gett-sz/releases/?project=1478486

**Comment by AleksandrZhukov** [comment]
Also, I found out that it creates 2 similar issues for one error, but maybe that's something specific for my project

**Comment by AleksandrZhukov** [comment]
@HazAT Hey
one more strange thing with artifacts - I removed my project, created a new one with another name, updated .properties file and the link in sentry config, made first build and upload it to sentry, but in artifacts tab I see builds and source maps from the previous project 😮 
tried to remove this release, but sentry says that I have active issues, though my Issue tab is empty

**Comment by christhegrand** [comment]
I'm seeing something similar with the stack traces Sentry is showing for our iOS app. They are correct for the latest distribution and wrong for older distributions.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
