### ISSUE TITLE
Sourcemaps still get bundled on Android

### ISSUE THREAD

**Issue by romainbraun** [getsentry/sentry-react-native#601]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.14.0
6.4.1
rnSourcemapTest@0.0.1 /Users/romainbraun/dev/rn-sourcemap-test/rnSourcemapTest
├── react@16.8.3
├── react-native@0.59.9
└── react-native-sentry@0.43.1
```

---
**I have the following issue:**

Even though sourcemaps are supposed to be removed from the package, they still get bundled. I believe it worked before 0.41.

It seems like `cliCleanUpTask` in `sentry.gradle` doesn't run.

I've changed `project.tasks.clean.dependsOn cliCleanUpTask` to `bundleTask.finalizedBy cliCleanUpTask` and now the task actually runs:

The sourcemap does get deleted from `android⁩ ▸ ⁨app⁩ ▸ ⁨build⁩ ▸ ⁨generated⁩ ▸ ⁨assets⁩ ▸ ⁨react ▸⁩ release`, but **it is still in the generated apk**.

**Steps to reproduce:**
- `react-native init testProject`
- `yarn add react-native-sentry`
- `./android/gradlew assembleRelease`
- Analyze apk in android studio or change the extension to .zip

**Actual result:**
- Bundle contains index.android.bundle.map

**Expected result:**
- Bundle does not contain index.android.bundle.map

**Comment by manudeep** [comment]
I am also facing the same issue. Because of this, my app size gets increased by ~3MB. Please help.

**Comment by wmonecke** [comment]
> I've changed project.tasks.clean.dependsOn cliCleanUpTask to bundleTask.finalizedBy cliCleanUpTask and now the task actually runs.

Where can I change this?

**Comment by hxkuan** [comment]
the same issue

**Comment by BatDroid** [comment]
i have a similar issue. whenever i add this line to my project. it adds 5mb to my apk size.
`apply from: "../../node_modules/react-native-sentry/sentry.gradle"`

**Comment by HazAT** [comment]
@dkssn Do you mind opening a PR with these changes?

**Comment by HazAT** [comment]
So this change will for sure lang in the new version of the SDK in the next release.
Is it possible for you all to switch to the new SDK?

**Comment by bill-pairaktaridis** [comment]
@HazAT which release would that be?

**Comment by HazAT** [comment]
@bill-pairaktaridis 
`@sentry/react-native` `1.0.6`

**Comment by bill-pairaktaridis** [comment]
After updating my fork of `sentry-expo` to use `"@sentry/react-native": "^1.0.6"`, I'm still getting [native code] with no errors. Any ideas? 

<img width="533" alt="Screenshot 2019-09-24 at 1 17 37 PM" src="https://user-images.githubusercontent.com/1397468/65503548-d08bde00-decd-11e9-9af1-b68c0022a9d1.png">

**Comment by rahamin1** [comment]
Please forgive my ignorance:

Isn't the idea to add sourcemaps to the release build, in order to get meaningful info regarding crashes?
