### ISSUE TITLE
[iOS] Build failed when developing offline

### ISSUE THREAD

**Issue by euharrison** [getsentry/sentry-react-native#602]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v12.2.0
6.9.0
MudeFit@0.0.1 /Users/harrison/Projects/mude-fit-native
├── @react-native-community/async-storage@1.3.4
├── axios@0.18.0
├── base-64@0.1.0
├── i18next@15.0.9
├── lodash@4.17.11
├── moment@2.24.0
├── qs@6.7.0
├── react@16.8.3
├── react-fast-compare@2.0.4
├── react-i18next@10.6.1
├── react-native@0.59.3
├── react-native-datepicker@1.7.2
├── react-native-fs@2.13.3
├── react-native-gesture-handler@1.1.0
├── react-native-iphone-x-helper@1.2.0
├── react-native-linear-gradient@2.5.4
├── react-native-maps@0.24.1
├── react-native-picker-select@6.1.0
├── react-native-sentry@0.43.1
├── react-native-svg@9.3.7
├── react-native-video@4.4.1
├── react-navigation@3.6.1
├── react-redux@6.0.1
├── redux@4.0.1
├── redux-persist@5.10.0
└── redux-thunk@2.3.0
```

Config:

```
if (!__DEV__) {
  Sentry.config(
    '🔒'
  ).install();
}
```

---
I have following issue:

When my computer is offline, I can't build the project to work with iOS Simulator.

Here is the console return
```
info error: 

info API request failed

info   caused by: [6] 
Couldn't resolve host name


info Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MudeFit.xcworkspace

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/harrison/Projects/mude-fit-native/ios/build/MudeFit/Build/Intermediates.noindex/MudeFit.build/Debug-iphonesimulator/MudeFit.build/Script-8C70334A3E7E4D2D950B0495.sh
(1 failure)

```

Here is the `Script-8C70334A3E7E4D2D950B0495.sh` file
```
#!/bin/sh
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

It sounds that can't upload dsym file but it's actually crashing the build, instead of give up.

**Steps to reproduce:**
- Disable the wifi/internet from your computer
- Run a project with `react-native run-ios`

**Actual result:**
- It's result a `BUILD FAILED`

**Expected result:**
- Build working normally to enable development during offline situations. Skip any upload step if it's not working. If it's strict necessary, just crash when it's in release mode.

**Comment by ashavyrin** [comment]
Same issue. I tested my app on my phone and it loads up fine when my connection is offline, so seems this only affects compiling to simulator.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
