### ISSUE TITLE
react-native unlink removes "Bundle React Native code and images"  step

### ISSUE THREAD

**Issue by llostris** [getsentry/sentry-react-native#604]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

When trying to upgrade from 0.39 to any other higher version, I followed the instruction from your page - first unlink, then re-link the library:
```
react-native unlink react-native-sentry
react-native link react-native-sentry
```
Turns out the first step entirely removes "Bundle React Native code and images" step from the project file in Xcode. 

This also occurs on 43.1

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
