### ISSUE TITLE
Sentry adds about 20MB to my app. Sourcemaps get bundled.

### ISSUE THREAD

**Issue by wmonecke** [getsentry/sentry-react-native#606]
After adding sentry to my react native app the .apk went from 25MB to 49MB. Is this to be expected?

**Comment by romainbraun** [comment]
Sourcemaps get bundled, even though they shouldn't. I've raised an issue for Android here https://github.com/getsentry/react-native-sentry/issues/601
And on iOS you can use the solution mentioned in https://github.com/getsentry/react-native-sentry/issues/364

**Comment by wmonecke** [comment]
Ah, thank you!!

**Comment by HazAT** [comment]
This should be fixed, also:

I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by rahamin1** [comment]
Please forgive my ignorance:

Isn't the idea to add sourcemaps to the release build, in order to get meaningful info regarding crashes?
