### ISSUE TITLE
Sentry only report errors without native integration

### ISSUE THREAD

**Issue by igortupini** [getsentry/sentry-react-native#608]
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

---
I have following issue:
Native Integration doesn't seem to work. After installing sentry on my project I cannot make it to work without the `disableNativeIntegration: true` option.

Sentry does not capture errors with native integration. When `disableNativeIntegration` is set to false, neither `Setry.crash()` nor `Sentry.nativeCrash()` is reported by sentry.

**Comment by HazAT** [comment]
Consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
