### ISSUE TITLE
Warning: Async Storage has been extracted from react-native core 

### ISSUE THREAD

**Issue by joan-saum** [getsentry/sentry-react-native#611]
OS:
- [ X ]  MacOS

_Platform:_
- [ X ]  iOS
- [ X ]  Android

Since React native 0.59, the Async Storage module has been moved to its own repo, causing a warning : 

> Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

**Comment by HazAT** [comment]
We released a new version of the SDK `@sentry/react-native` which doesn't use the async storage anymore. 
See for more info: https://github.com/getsentry/sentry-react-native/issues/612
