### ISSUE TITLE
setUserContext vs clearContext

### ISSUE THREAD

**Issue by cihati** [getsentry/sentry-react-native#616]
Relevant issues:
https://github.com/getsentry/sentry-react-native/issues/492
https://github.com/getsentry/sentry-react-native/issues/51

What should be called when a user logs out? What's the difference between `Sentry.clearContext()` and `Sentry.setUserContext({})`?

Also, at https://docs.sentry.io/clients/javascript/#adding-context

> If at any point, the user becomes unauthenticated, you can call Raven.setUserContext() with no arguments to remove their data

Which causes problems (for RN, it needs to be called with the empty map instead of no parameters)

It'd be super useful to update documentation about these.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.


The new package uses the unified API, please refer to the new documentation.
