### ISSUE TITLE
JSON.stringify in raven-plugin crashes on circular references

### ISSUE THREAD

**Issue by NicholasGWK** [getsentry/sentry-react-native#617]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v10.1.0
5.6.0
react-native-sentry: 0.43.2
    raven-js: "3.27.2"
```

---
I have following issue:

Getting a "Converting circular structure to JSON" error due to the JSON.stringify in lib/raven-plugin https://github.com/getsentry/sentry-react-native/blob/4c143caaaee6498fb9f56d049cb624ebe5fe14ae/lib/raven-plugin.js#L261 :). 

A similar issue was fixed here in Raven: https://github.com/getsentry/sentry-javascript/pull/652/files but seems to still be broken in RN.

**Steps to reproduce:**
-Capture an exception with a circular reference

**Actual result:**
<img width="374" alt="Screen Shot 2019-07-10 at 10 16 52 AM" src="https://user-images.githubusercontent.com/6642497/60976555-e2f97100-a2fb-11e9-9b12-cd2b6874d17c.png">

**Expected result:**
-The JSON is stringified safely so circular references don't crash it

Happy to attempt a PR if all that's needed is adding json-stringify-safe or similar (or someone can give me some direction :) )

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
