### ISSUE TITLE
Android issues results in <unlabeled event> (iOS works fine)

### ISSUE THREAD

**Issue by dccarmo** [getsentry/sentry-react-native#618]
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.3
6.7.0
react-native@0.59.5
react-native-sentry@0.43.2
```

Config:

```
Sentry.config('https://...@sentry.io/...', {}).install()
```

---
I noticed that my Android issues are all coming with `<unlabeled event>` instead of the proper error, which ends up grouping them wrongly. The same error (let's say `Sentry.crash()`) on iOS gets reported correctly.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by bitcrumb** [comment]
We're seeing this happening in our Android app as well. On iOS we don't see this <unlabeled event> popping up in Sentry (without any stacktrace attached). ur app is using @sentry/react-native 1.2.1. Doesn't look like 1.2.2 addresses this issue.

@HazAT Just 19 days you commented that you are aware of this bug in this issue: https://github.com/getsentry/sentry-javascript/issues/1271

Is this related to this issue? If so, can this be reopened?

**Comment by beqramo** [comment]
@HazAT I see this issue too on android
