### ISSUE TITLE
ignoreModulesExclude examples?

### ISSUE THREAD

**Issue by bneigher** [getsentry/sentry-react-native#619]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v11.9.0
6.7.0
```

Config:

```
Sentry.config("https://.......@sentry.io/.....", {
    logLevel: SentryLog.Error,
    ignoreModulesExclude: [
      "aws-sdk",
      "aws-amplify",
      "@aws-amplify/pushnotification"
    ]
  }).install();
```
---
I have following issue:

Not a bug, more of a callout to missing documentation.  I am not clear what the contents of `ignoreModulesExclude` should be, the [docs](https://docs.sentry.io/clients/react-native/config/) only give examples of `I18nManager` or `RNSentry` which is great but is this from node_modules? Where can I find the names of valid "modules".

Using the require or import name doesn't seem to work as shown above.

**Steps to reproduce:**
- Use aws-sdk in react-native
- Attempt to log in without a config

**Actual result:**
- Errors are being sent to Sentry from aws-sdk

**Expected result:**
- Errors are NOT sent to Sentry from aws-sdk

**Comment by bneigher** [comment]
word

**Comment by HazAT** [comment]
We dropped this property in the new SDK `@sentry/react-native` it was used for stack trace merging which was disabled by default.
In your case, it doesn't do anything.

If this comes ever back again it will be properly documented.
