### ISSUE TITLE
sentry-cli react-native xcode assumes presence of index.ios.js

### ISSUE THREAD

**Issue by ball-hayden** [getsentry/sentry-react-native#624]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

<details>

<pre>
v12.6.0
6.9.0
mobile@0.0.1 /Users/hayden/development/PlayerData/app/mobile
├── @react-native-community/async-storage@1.5.0
├── @react-native-community/netinfo@3.2.1
├── apollo-cache-persist@0.1.1
├── apollo-link-context@1.0.18
├── apollo-link-state@0.4.2
├── build-url@1.3.3
├── UNMET PEER DEPENDENCY date-fns@2.0.0-beta.2
├── edge-bluetooth-interface@0.0.1 -> /Users/hayden/development/PlayerData/app/edge-bluetooth-interface invalid
├── edge-wifi-interface@0.0.1 -> /Users/hayden/development/PlayerData/app/edge-wifi-interface invalid
├── formik@1.5.7
├── humps@2.0.1
├── js-base64@2.5.1
├── node-forge@0.8.5
├── playerdata-application@0.0.1 -> /Users/hayden/development/PlayerData/app/playerdata-application invalid
├── query-string@6.8.1
├── UNMET PEER DEPENDENCY react@16.8.6
├── react-apollo@2.5.8
├── UNMET PEER DEPENDENCY react-native@0.59.9
├── react-native-cli@2.0.1
├── react-native-config@0.11.7
├── react-native-email-link@1.4.0
├── react-native-fs@2.13.3
├── react-native-keychain@3.1.3
├── react-native-material-bottom-navigation@1.0.4
├── react-native-navigation@2.22.3
├── react-native-network-info@4.0.1
├── react-native-paper@2.16.0
├── react-native-permissions@1.1.1
├── react-native-sentry@0.43.2
├── react-native-svg@9.5.1
├── react-native-vector-icons@6.6.0
├── react-native-version-number@0.3.6
└── ts-optchain@0.1.7

npm ERR! peer dep missing: date-fns@2.0.0-alpha.27, required by @date-io/date-fns@1.3.8
npm ERR! peer dep missing: react@16.8.3, required by react-native@0.59.9
npm ERR! peer dep missing: react-native@^0.41.2, required by edge-bluetooth-interface@0.0.1
npm ERR! peer dep missing: react-native@^0.41.2, required by edge-wifi-interface@0.0.1
npm ERR! invalid: edge-bluetooth-interface@0.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/edge-bluetooth-interface
npm ERR! missing: @babel/runtime@^7.3.1, required by edge-bluetooth-interface@0.0.1
npm ERR! missing: @types/react-native@^0.57.38, required by edge-bluetooth-interface@0.0.1
npm ERR! invalid: edge-wifi-interface@0.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/edge-wifi-interface
npm ERR! invalid: playerdata-application@0.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application
npm ERR! peer dep missing: date-fns@2.0.0-alpha.27, required by @date-io/date-fns@1.3.7
npm ERR! peer dep missing: react@16.8.3, required by react-native@0.59.9
npm ERR! peer dep missing: react-native@^0.41.2, required by edge-bluetooth-interface@0.0.1
npm ERR! peer dep missing: react-native@^0.41.2, required by edge-wifi-interface@0.0.1
npm ERR! peer dep missing: babel-loader@^7.0.0 || ^8.0.0, required by @storybook/react@5.1.8
npm ERR! extraneous: @graphql-codegen/add@1.3.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@graphql-codegen/add
npm ERR! extraneous: @graphql-codegen/cli@1.3.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@graphql-codegen/cli
npm ERR! extraneous: @graphql-codegen/fragment-matcher@1.3.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@graphql-codegen/fragment-matcher
npm ERR! extraneous: @graphql-codegen/typescript-operations@1.3.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@graphql-codegen/typescript-operations
npm ERR! extraneous: @storybook/addon-actions@5.1.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@storybook/addon-actions
npm ERR! extraneous: @storybook/addon-knobs@5.1.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@storybook/addon-knobs
npm ERR! extraneous: @storybook/react@5.1.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@storybook/react
npm ERR! extraneous: @storybook/react-native@5.1.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@storybook/react-native
npm ERR! extraneous: @types/classnames@2.2.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/classnames
npm ERR! extraneous: @types/enzyme@3.9.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/enzyme
npm ERR! extraneous: @types/fetch-mock@7.3.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/fetch-mock
npm ERR! extraneous: @types/graphql@14.2.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/graphql
npm ERR! extraneous: @types/humps@1.1.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/humps
npm ERR! extraneous: @types/jest@24.0.15 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/jest
npm ERR! extraneous: @types/js-base64@2.3.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/js-base64
npm ERR! extraneous: @types/lodash@4.14.134 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/lodash
npm ERR! extraneous: @types/node-forge@0.8.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/node-forge
npm ERR! extraneous: @types/query-string@6.3.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/query-string
npm ERR! extraneous: @types/react-native-permissions@1.1.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/react-native-permissions
npm ERR! extraneous: @types/react-native-vector-icons@6.4.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/react-native-vector-icons
npm ERR! extraneous: @types/react-router-dom@4.3.4 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/react-router-dom
npm ERR! extraneous: @types/storybook__addon-actions@3.4.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/storybook__addon-actions
npm ERR! extraneous: @types/storybook__addon-knobs@5.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/storybook__addon-knobs
npm ERR! extraneous: @types/storybook__react-native@3.0.5 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/storybook__react-native
npm ERR! extraneous: @types/uuid@3.4.4 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@types/uuid
npm ERR! extraneous: @typescript-eslint/eslint-plugin@1.10.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@typescript-eslint/eslint-plugin
npm ERR! extraneous: @typescript-eslint/parser@1.10.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@typescript-eslint/parser
npm ERR! extraneous: apollo-link-schema@1.2.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link-schema
npm ERR! extraneous: canvas@2.5.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/canvas
npm ERR! invalid: edge-bluetooth-interface@0.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/edge-bluetooth-interface
npm ERR! missing: @babel/runtime@^7.3.1, required by edge-bluetooth-interface@0.0.1
npm ERR! missing: @types/react-native@^0.57.38, required by edge-bluetooth-interface@0.0.1
npm ERR! invalid: edge-wifi-interface@0.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/edge-wifi-interface
npm ERR! extraneous: enzyme@3.10.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/enzyme
npm ERR! extraneous: enzyme-adapter-react-16@1.14.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/enzyme-adapter-react-16
npm ERR! extraneous: enzyme-to-json@3.3.5 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/enzyme-to-json
npm ERR! extraneous: eslint@5.16.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint
npm ERR! extraneous: eslint-config-airbnb@17.1.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint-config-airbnb
npm ERR! extraneous: eslint-config-prettier@4.3.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint-config-prettier
npm ERR! extraneous: eslint-plugin-import@2.17.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint-plugin-import
npm ERR! extraneous: eslint-plugin-jsx-a11y@6.2.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint-plugin-jsx-a11y
npm ERR! extraneous: eslint-plugin-react@7.13.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/eslint-plugin-react
npm ERR! extraneous: fetch-mock@7.3.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/fetch-mock
npm ERR! extraneous: husky@2.4.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/husky
npm ERR! extraneous: jest@24.8.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/jest
npm ERR! extraneous: jest-junit@6.4.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/jest-junit
npm ERR! extraneous: lint-staged@8.2.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/lint-staged
npm ERR! extraneous: timekeeper@2.2.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/timekeeper
npm ERR! extraneous: ts-jest@24.0.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/ts-jest
npm ERR! extraneous: @date-io/date-fns@1.3.7 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@date-io/date-fns
npm ERR! extraneous: @material-ui/core@4.1.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@material-ui/core
npm ERR! extraneous: @material-ui/icons@4.2.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@material-ui/icons
npm ERR! extraneous: @material-ui/pickers@3.1.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@material-ui/pickers
npm ERR! extraneous: @material-ui/styles@4.1.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@material-ui/styles
npm ERR! extraneous: @react-native-community/async-storage@1.5.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@react-native-community/async-storage
npm ERR! extraneous: @react-native-community/netinfo@3.2.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/@react-native-community/netinfo
npm ERR! extraneous: apollo-cache@1.3.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-cache
npm ERR! extraneous: apollo-cache-inmemory@1.6.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-cache-inmemory
npm ERR! extraneous: apollo-cache-persist@0.1.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-cache-persist
npm ERR! extraneous: apollo-client@2.6.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-client
npm ERR! extraneous: apollo-link@1.2.12 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link
npm ERR! extraneous: apollo-link-context@1.0.18 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link-context
npm ERR! extraneous: apollo-link-http@1.5.15 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link-http
npm ERR! extraneous: apollo-link-http-common@0.2.14 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link-http-common
npm ERR! extraneous: apollo-link-state@0.4.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-link-state
npm ERR! extraneous: apollo-utilities@1.3.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/apollo-utilities
npm ERR! extraneous: build-url@1.3.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/build-url
npm ERR! extraneous: classnames@2.2.6 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/classnames
npm ERR! extraneous: formik@1.5.7 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/formik
npm ERR! extraneous: graphql@14.4.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/graphql
npm ERR! extraneous: graphql-anywhere@4.2.4 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/graphql-anywhere
npm ERR! extraneous: graphql-tag@2.10.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/graphql-tag
npm ERR! extraneous: history@4.9.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/history
npm ERR! extraneous: humps@2.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/humps
npm ERR! extraneous: js-base64@2.5.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/js-base64
npm ERR! extraneous: lodash@4.17.11 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/lodash
npm ERR! extraneous: mdi-material-ui@6.1.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/mdi-material-ui
npm ERR! extraneous: node-forge@0.8.5 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/node-forge
npm ERR! extraneous: path-to-regexp@3.0.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/path-to-regexp
npm ERR! extraneous: query-string@6.7.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/query-string
npm ERR! extraneous: react-apollo@2.5.8 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-apollo
npm ERR! extraneous: react-art@16.8.6 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-art
npm ERR! extraneous: react-dom@16.8.6 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-dom
npm ERR! extraneous: react-icons@3.7.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-icons
npm ERR! extraneous: react-native-email-link@1.2.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-email-link
npm ERR! extraneous: react-native-fs@2.13.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-fs
npm ERR! extraneous: react-native-keychain@3.1.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-keychain
npm ERR! extraneous: react-native-material-bottom-navigation@1.0.4 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-material-bottom-navigation
npm ERR! extraneous: react-native-navigation@2.22.3 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-navigation
npm ERR! extraneous: react-native-network-info@4.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-network-info
npm ERR! extraneous: react-native-paper@2.16.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-paper
npm ERR! extraneous: react-native-permissions@1.1.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-permissions
npm ERR! extraneous: react-native-svg@9.5.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-svg
npm ERR! extraneous: react-native-vector-icons@6.5.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-vector-icons
npm ERR! extraneous: react-native-version-number@0.3.6 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-version-number
npm ERR! extraneous: react-native-web@0.11.4 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-native-web
npm ERR! extraneous: react-router@5.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-router
npm ERR! extraneous: react-router-dom@5.0.1 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/react-router-dom
npm ERR! extraneous: ts-optchain@0.1.7 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/ts-optchain
npm ERR! extraneous: utility-types@3.7.0 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/utility-types
npm ERR! extraneous: uuid@3.3.2 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/uuid
npm ERR! extraneous: zen-observable@0.8.14 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/zen-observable
npm ERR! extraneous: zen-observable-ts@0.8.19 /Users/hayden/development/PlayerData/app/mobile/node_modules/playerdata-application/node_modules/zen-observable-ts
</pre>

</details>

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

Running `sentry-cli react-native xcode --allow-fetch` tries to fetch from `/index.ios.bundle`.
Where a project has a common entry point (`index.js`), this file may not exist.

**Steps to reproduce:**
- Create a react native project with a common `index.js` entrypoint for both Android and iOS.

**Actual result:**
- An error is produced in the bundler logs, as sentry tries to fetch `/index.ios.bundle`

**Expected result:**
- Sentry tries to fetch `index.bundle`.

The issue is caused by the hardcoded extension here:
https://github.com/getsentry/sentry-cli/blob/227668a9cb118f58342bec803b7eb62cb08a6e2c/src/commands/react_native_xcode.rs#L184-L191

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
