### ISSUE TITLE
how can I configure my application to get proper stacktrace. currently I am getting bundle info and the method name. What I want is filename and method name .      app:///index.bundle?platform=ios&dev=true&minify=false in init$ at line ......

### ISSUE THREAD

**Issue by arughani** [getsentry/sentry-react-native#627]

**Comment by ramonscampos** [comment]
Same here.
I ran the link..
Generate the bundle with this code: 
react-native bundle --platform ios --entry-file ./App.js --bundle-output ./bundles/index.bundle --sourcemap-output ./bundles/index.bundle.map --assets-dest ./bundles/ --dev true

Uploaded with this:
./node_modules/.bin/sentry-cli --auth-token {auth_token} releases -o rcampos -p sentryteste files 2.0 upload-sourcemaps --dist distname--rewrite --validate /Users/ramoncampos/Desktop/sentry/sentryteste/bundles/index.bundle /Users/ramoncampos/Desktop/sentry/sentryteste/bundles/index.bundle.map --url-prefix="~"

Put the release and dist in config like this:
```
Sentry.config(dsn).install();
Sentry.setRelease('2.0');
Sentry.setDist('distname');
```

and besides the reference file is wrong (ReferenceErrorfunctionTest(Users/ramoncampos/Desktop/sentry/sentryteste/node_modules/react-native-sentry/lib/NativeClient)) I can only see the bundle info and method name too. 

I want to see the javascript code with the error.

**Comment by arughani** [comment]
Can sentry work on debug mode?

**Comment by ramonscampos** [comment]
I think so, but here it doesn't work (nothing does). 
I already tried with --dev false and stays the same ;/

**Comment by arughani** [comment]
same here..nothing works. I am not sure where am I going wrong with it. I am using typescript in my application. Is it because of that?

**Comment by HazAT** [comment]
Please use our new beta sdk it works there.
More info: https://github.com/getsentry/sentry-react-native/issues/612
