### ISSUE TITLE
[1.0.0] BETAs with CodePush, JS stack trace no longer symbolicated

### ISSUE THREAD

**Issue by fungilation** [getsentry/sentry-react-native#628]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v12.7.0
6.10.2
wonderswipe@0.0.1 /Users/gfung/Documents/code/wonderswipe
├── @postlight/mercury-parser@2.1.1
├── @react-native-community/async-storage@1.6.1
├── @react-native-community/blur@3.3.1
├── @react-native-community/viewpager@1.1.7
├── @sentry/react-native@1.0.0-beta.4
├── babel-plugin-idx@2.4.0
├── buffer@5.2.1
├── he@1.2.0
├── idx@2.5.6
├── lodash@4.17.15
├── moment@2.24.0
├── moment-timezone@0.5.26
├── node-summary@1.0.1 invalid
├── UNMET PEER DEPENDENCY react@16.8.6
├── UNMET PEER DEPENDENCY react-native@0.60.4
├── react-native-actionsheet@2.4.2
├── react-native-cached-image@1.4.3 invalid
├── react-native-cheerio@1.0.0-rc.4
├── react-native-code-push@5.6.1
├── react-native-custom-tabs@0.1.7
├── react-native-easy-toast@1.2.0
├── react-native-firebase@5.5.6
├── react-native-fit-image@1.5.4
├── react-native-highlight-words@1.0.1
├── react-native-keep-awake@4.0.0
├── react-native-linear-gradient@2.5.6
├── react-native-modal-dropdown@0.6.2 invalid
├── react-native-modalbox@1.7.1
├── react-native-orientation@3.1.3
├── react-native-parallax-scroll-view@0.20.1 invalid
├── react-native-progress@3.6.0
├── react-native-rate@1.1.7
├── react-native-responsive-screen@1.2.2
├── react-native-safari-view@2.1.0
├── react-native-sha256@1.3.6
├── react-native-status-bar-size@0.3.3
├── react-native-swiper@1.5.14
├── react-native-tooltip@5.2.1 invalid
├── react-native-tts@3.0.0
├── react-native-vector-icons@6.6.0
├── react-native-webview@6.3.1
├── react-redux@7.1.0
├── redux@4.0.4
└── redux-thunk@2.3.0
```

Config:

```
Sentry.configureScope(scope => {
  scope.setUser({ userID: firebase.auth().currentUser.uid })
})
...
Sentry.init({ dsn: '[DSN]' })
```

---
I have following issue:

Crash report not symbolicated since RN upgrade 0.59 to 0.60.4, which required updating to 1.0 beta of newly homogenized sentry-react-native. API changes are implemented in app for integration, and run the same cli commands for CodePush + Sentry source map upload, as documented at https://docs.sentry.io/clients/react-native/codepush/

Commands I run in practice on release with CodePush, what worked fine up to sentry-react-native@0.43.2:
```
appcenter codepush release-react -o ../WonderSwipe-bundle -s ../WonderSwipe-bundle/CodePush/main.jsbundle.map -d Production --description "[desc]"
sentry-cli react-native appcenter gfung/WonderSwipe ios ../WonderSwipe-bundle/CodePush
```

**Actual result:**
- See this unsymbolicated crash report, real one after sentry-react-native upgrade from 0.43.2 to 1.0.0-beta.4: https://sentry.io/share/issue/3c596dc8f9934d90b69a1e8d5645129f/

**Expected result:**
- Crash report should have JS stack trace symbolicated

**Comment by fungilation** [comment]
Note that this is with release builds, not debug builds. I see for debug builds, on-device symbolication has been added since beta.5 (which also doesn't apply as my app was released on beta.4)

**Comment by HazAT** [comment]
@fungilation Can you please share the issue link without sharing it, need to full url.

**Comment by fungilation** [comment]
@HazAT https://sentry.io/organizations/zeta-networks-inc/issues/1134788372

**Comment by HazAT** [comment]
Sorry for the late reply, but from what I can tell the specific issue (which no longer exists) didn't have the correct files uploaded in the release.
Please check again and report back if the issue still exists.
