### ISSUE TITLE
'Sentry/Sentry.h' file not found

### ISSUE THREAD

**Issue by ajouve** [getsentry/sentry-react-native#632]
OS:
- [ ]  Windows
- [ x ]  MacOS
- [ ]  Linux

_Platform:_
- [ x ]  iOS
- [ ]  Android

```
"react-native-sentry": "^0.43.2",
"react-native": "0.59.8",
```

---
I have following issue:

When building for IOS, I have the folowing error 'Sentry/Sentry.h' file not found

I tried to link and unlink but does not works

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by marlti7** [comment]
same problem. why close
