### ISSUE TITLE
Help!Dangerous！How to delete sourcemap in ipa ? Don't  change "Bundle React Native code and images" script.

### ISSUE THREAD

**Issue by JetCyC** [getsentry/sentry-react-native#633]
OS:
- [ ]  Windows
- [ 10.14.6]  MacOS
- [ ]  Linux

_Platform:_
- [ 11.4.1]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
<!-- Replace this -->
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
Archive
- Step

**Actual result:**
When  archive  finished , contains sourcemap.  ipa is 3M bigger than before.
- Actual

**Expected result:**
When  archive  finished , delete sourcemap,and sourcemap upload successfull.
- Result

**Comment by meteorra** [comment]
@JetCyC, do you know if it could also cause a problem / rejection when submitting to Apple Store?

**Comment by HazAT** [comment]
Please use the latest version of `@sentry/react-native` this should be fixed there.
