### ISSUE TITLE
Use DSN instead of project name in sentry.properties

### ISSUE THREAD

**Issue by sregg** [getsentry/sentry-react-native#637]
Currently our `sentry.properties` file contains the project name in `defaults.project`.
This is quite brittle as someone can change the project name in sentry.com (true story...)
It be great if we can use the DSN rather than the name for identification.

**Comment by HazAT** [comment]
Cool feature request but it's unlikely we will do this in this form right now.
We were thinking about revamping the `sentry.properties` files in general but this is still in the future.
