### ISSUE TITLE
ios podspec is not compatible with vendored sentry

### ISSUE THREAD

**Issue by mmerickel** [getsentry/sentry-react-native#643]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

---
I have following issue:

Using react-native-sentry @ 0.43.2, the vendored version of `ios/Sentry` (4.2.1) does not match the `RNSentry.podspec` constraint (4.1.3). For now I have to patch the podspec to bump the constraint.

Process-wise it doesn't seem like there's a great story on keeping them updated in lock step. I found #514 about the same issue in the past. On master they are both at 4.4.0 so it was updated at some point recently so a new release is probably in order.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
