### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by boneVidy** [getsentry/sentry-react-native#644]
OS:
- [ ]  Windows
- [√]  MacOS
- [ ]  Linux

_Platform:_
- [√ ]  iOS
- [ √]  Android

Output of `npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.47.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.47.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuweidi/.npm/_logs/2019-08-28T02_15_58_834Z-debug.log`

Description goes here ...

**Steps to reproduce:**
- Step
    run  npm i react-native-sentry -S
**Actual result:**
installation failed
and the output info is `
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sentry/cli@1.47.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sentry/cli@1.47.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuweidi/.npm/_logs/2019-08-28T02_15_58_834Z-debug.log`
**Expected result:**
- Successful installation

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
