### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by xingxinjun** [getsentry/sentry-react-native#645]
OS:
- [x]  MacOS

_Platform:_
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
<!-- Replace this -->
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:
能否支持androidx

Description goes here ...

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by xingxinjun** [comment]
能否支持androidx

**Comment by HazAT** [comment]
Please use `@sentry/react-native` `1.0.0` it has support for Android X.
