### ISSUE TITLE
UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String

### ISSUE THREAD

**Issue by Matthias-Pichler** [getsentry/sentry-react-native#652]
OS:
- [x]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.5

Init Code:

```javascript
Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: process.env.NODE_ENV || 'development'
});
```

---
I have following issue:

As soon as I call init on the Sentry SDK my app crashes with `UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String`. Though this only happens on Android and not on iOS.

This issue was reported in the beta as well: https://github.com/getsentry/sentry-react-native/issues/612#issuecomment-524264131

and #651  also seems related: 

react-native info
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 105.25 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

screenshot:
![image](https://user-images.githubusercontent.com/48183213/64341803-6deba480-cfe9-11e9-9fdf-a81fd6b3a278.png)

stacktrace in logcat:
```
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: Exception in native call
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:141)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:129)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:163)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:209)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
```

**Steps to reproduce:**
- call init on `react-native 0.60.5` with `@sentry/react-native 1.0.4`

**Actual result:**
- App crashes with UnexpectedNativeTypeException

**Expected result:**
- SDK is set up successfully

**Comment by HazAT** [comment]
OK, I know how to fix this error but I want to understand how this happens.
So there is no other place in your codebase where you have any calls to `Sentry.*`?

The error message clearly says that the value of `event.message` is not a string.

**Comment by Matthias-Pichler** [comment]
@HazAT 
Ok thanks for the hint about logLevel.

I removed every call to Sentry in my Application and replaced the init call with just the dsn. Still the same error

**Comment by HazAT** [comment]
I am really curious, the fix is easy, I need to safeguard it like here:
https://github.com/getsentry/sentry-react-native/blob/32c283b0b5e3cb64e28eb5adc6a9b3f1c8578e20/android/src/main/java/io/sentry/RNSentryModule.java#L180-L192

But is it possible for you to inspect the value of `event.getMap('message')`?
I want to know the value so I can understand where this is coming from. If it's from our SDK internally I need to fix this in another place.

**Comment by Matthias-Pichler** [comment]
So it was in fact super interesting what caused this error but totally unrelated to anything discussed here: 
See: https://github.com/getsentry/sentry-react-native/issues/653

**Comment by mikeRChambers610** [comment]
what is the fix....?
