### ISSUE TITLE
iOS build fail: no known class method for selector 'installWithRootView:'

### ISSUE THREAD

**Issue by ericluong** [getsentry/sentry-react-native#657]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.59.10

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

SDK integration is not working with iOS.

**Steps to reproduce:**
```
$ npm install @sentry/react-native --save
$ react-native link @sentry/react-native
$ cd ios && pod install
```

I also had to launch the following command:
```
$ pod repo update
```

**Actual result:**
When building the project, i get this error:
`AppDelegate.m:33:13: no known class method for selector 'installWithRootView:'`

**Expected result:**
There should be no error on build

Thank you!

**Comment by HazAT** [comment]
Did you migrate from an older version of the SDK?
Please remove all references of sentry in AppDeletegate, see 

`Upgrading from react-native-sentry`
https://github.com/getsentry/sentry-react-native/issues/612
