### ISSUE TITLE
Sourcemap Not Working with ExpoKit

### ISSUE THREAD

**Issue by lightninglu10** [getsentry/sentry-react-native#658]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [ ]  `@sentry/react-native`
- [ ]  `react-native-sentry`
- [x]  `sentry-expo`

`react-native` version: 0.59.0

Init Code:

```
Sentry.init({
      dsn: '...',
      enableInExpoDevelopment: true,
      debug: true,
      environment: ENV,
    });
```

---
I have following issue:

Sentry errors do not include the javascript sourcemaps

https://sentry.io/share/issue/8b35f63de3bd4ccb84d2874871fc2b28/

in app.json we have a postpublish hook to upload into sentry, and we can see in our releases page that our sourcemap actually is in sentry.

Whenever an error is shown though, there is no mapping back to JS.

**Comment by lightninglu10** [comment]
So I think the issue is related to one here: https://github.com/expo/sentry-expo/issues/71

It looks like sentry-expo is not automatically setting a release on an event which would cause issues of not linking the proper release to the artifacts.

Would anyone here know anything about this?

**Comment by marandaneto** [comment]
@lightninglu10 do you still run into these issues? there were many fixes related to that, also for expo.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
