### ISSUE TITLE
Source code not found (docker / on-permise)

### ISSUE THREAD

**Issue by eliecharra** [getsentry/sentry-react-native#660]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android 9

SDK:
- [x]  `@sentry/react-native 1.0.4` 
- [ ]  `react-native-sentry`

`react-native` version: 0.59.9

Init Code:

```
Sentry.init({
    dsn: Config.SENTRY_DSN,
});
```

---
I have following issue:

I build an apk with `./gradlew assembleStaging`

During the build, artifacts are uploaded with success :

![image](https://user-images.githubusercontent.com/6154987/64727374-02b63c80-d4d9-11e9-9a16-9553782b79e8.png)

I double checked on sentry, seems OK 

![image](https://user-images.githubusercontent.com/6154987/64726690-76574a00-d4d7-11e9-91a0-481c5a8c4171.png)

My app crash at startup (only on variant staging, I setup sentry to debug this strange behaviour) and I am unable to get a proper stacktrace ...

![image](https://user-images.githubusercontent.com/6154987/64726852-cb935b80-d4d7-11e9-86c1-9557874439dc.png)
![image](https://user-images.githubusercontent.com/6154987/64727204-9cc9b500-d4d8-11e9-88b3-1ce4a164ef26.png)

I've searched some similar issues (there is many).

I double checked release and distribution, everything match between the sentry issue and uploaded release / distrib. There is a `~/index.android.bundle` artifact in  release `com.captotheque-1.0` distrib `3145729` when issue is looking for `app:///index.android.bundle`

I've updated my sentry instance to 9.1.2 but same issue.

I spent 3 hours debugging but I'm out of ideas, am I missing something ?

Thanks for your awesome work !

**Comment by BrendonSled** [comment]
Same issue here with android
![Imgur](https://i.imgur.com/zQTR68z.png)
![Imgur](https://i.imgur.com/fw6kGxk.png)

**Comment by HazAT** [comment]
Are you using on-premise?
If not can you please share a link so I can inspect what's going on?

We know that there a currently some configurations issues when it comes to on-premise, meaning the out of the box config doesn't play well with symbolication + source maps.

**Comment by HazAT** [comment]
For reference:
https://github.com/getsentry/sentry/issues/14680
https://github.com/getsentry/sentry/issues/13326
https://github.com/getsentry/sentry/issues/14461
https://github.com/getsentry/sentry/issues/4168

**Comment by eliecharra** [comment]
@HazAT Yeah it is on-permise.
Just sent you a share link by mail.

**Comment by HazAT** [comment]
@eliecharra I can't debug on-premise issues sorry. For now, I can only tell you to look into the other issues, maybe someone already found a workaround for it :/

**Comment by eliecharra** [comment]
Ok thanks :+1: maybe it is related to docker setup, I'm gonna try https://github.com/getsentry/sentry/issues/4168#issuecomment-341679115

**Comment by eliecharra** [comment]
Finally I make it work, we need to share volume beetween sentry container and worker container, thanks to @jonaskello solution : https://github.com/getsentry/sentry/issues/4168#issuecomment-341679115

After mounting volumes, I also had to remove files entries in database (see https://github.com/getsentry/sentry-cli/issues/141#issuecomment-486268346)

```sql
delete from sentry_releasefile; 
delete from sentry_fileblobindex; 
delete from sentry_fileblob; 
delete from sentry_file;
```

Thanks @HazAT for your suggestions, closing now :+1:

**Comment by meotimdihia** [comment]
@eliecharra Could you share with me how to run these commands?
