### ISSUE TITLE
No connection to Sentry!

### ISSUE THREAD

**Issue by joshuakelly** [getsentry/sentry-react-native#661]
OS:
- [ ]  Windows
- [ X ]  MacOS
- [ ]  Linux

_Platform:_
- [ X ]  iOS
- [ ]  Android

SDK:
- [ X ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- npx react-native init SentryTest
- yarn add @sentry/react-native
- pod install etc...
- Add the Sentry.init({ dsn: xxx, });
- Launch application, all steps say successful and error is thrown but nothing is shown inside of sentry. Also takes quite a whole to boot application.
- Wizard also stuck on "connecting"

**Actual result:**
- No errors logged

**Expected result:**
- Errors logged

**Comment by HazAT** [comment]
Are you using on-premise?

**Comment by joshuakelly** [comment]
> Are you using on-premise (self hosted Sentry) or sentry.io?

sentry.io

**Comment by HazAT** [comment]
That's really odd, I just tried it with the same steps you did and it worked just fine.
Can you enable debug mode and see if there is something?
```js
Sentry.init({
debug: true
});
```

Also, can you debug it in chrome remote console to see what's going on?
How do you throw an error?
I need more input / a repro case.

**Comment by joshuakelly** [comment]
Tried another fresh project and it seems to be working on the last release. Closing.
