### ISSUE TITLE
@ sentry/react-native modal message "could not connect to Sentry native SDK"

### ISSUE THREAD

**Issue by dark4eg** [getsentry/sentry-react-native#662]
OS:
- [ ]  Windows
- [*]  MacOS
- [ ]  Linux

_Platform:_
- [*]  iOS
- [*]  Android

SDK:
- [*]  `@sentry/react-native`: 1.0.5
- [ ]  `react-native-sentry`

`react-native` version: 0.60.4, 0.60.5

Init Code:

```
import * as Sentry from "@sentry/react-native";
 
Sentry.init({
  dsn: "__DSN__" // i'm use __DSN__ = real dsn app
});
 
Sentry.setTag("myTag", "tag-value");
Sentry.setExtra("myExtra", "extra-value");
Sentry.addBreadcrumb({ message: "test" });
 
Sentry.captureMessage("Hello Sentry!");
```

---
I have following issue:
After starting, I see a modal message "Warning, could not connect to Sentry native SDK".
If you do not want to use the native component please pass `enableNative: false` in the options. Visit: https://docs.sentry.io/clients/react-native/ for more details."

Thanks in advance for the answers.
1. Why does the link in the message lead to the documentation for the deprecated project?
2. Why am I referring to this modal message, how do I resolve this issue?
3. What should i use now for react-native 0.60+ sentry-react-native или @sentry/react-native?

**Steps to reproduce:**
- `react-native init AwesomeProject`
- `cd AwesomeProject`
- `npm i`
- `npm install --save @sentry/react-native`  
- in directory `AwesomeProject` run `react-native start`
- run ios and android app

**Comment by HazAT** [comment]
Thanks for pointing out that it guides to the old documentation.
Did you run `pod install` as stated in the docs?
https://docs.sentry.io/platforms/react-native/#linking

**Comment by dark4eg** [comment]
Sorry, iOS build is working.
Build for android showed Modal message.

**Comment by HazAT** [comment]
I just tried a clean project `react-native init project` it worked without issues, I need a reproduction case for this.
Make sure you linked the dependency correctly.

**Comment by nateblog** [comment]
proper linking sorted this out for me by adding

pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

then pod install

"@sentry/react-native": "1.3.1",

**Comment by jamesdunay** [comment]
Anyone find a solution to this? Running into the same issue right now. I've reinstalled all node_modules and walked through the wizard. Tried 'npm link' as well as pod install, neither had any effect. 

Seeing it on both iOS and Android, in addition, interestingly enough, even when i use the flag enableNative:false, I still get the warnings. 

"@sentry/react-native": "^1.4.1",
"react-native": "0.62.2",

**Comment by waqaramjad** [comment]
same issue

**Comment by muriloneo** [comment]
same

**Comment by jennmueng** [comment]
@jamesdunay @muriloneo @waqaramjad Can you try updating to the latest 1.7.0 and see if the issue persists? This just sounds like incorrect installations to me.

**Comment by muriloneo** [comment]
solved with `enableNative: process.env.NODE_ENV == 'development' ? false : true` on init

**Comment by jennmueng** [comment]
> solved with `enableNative: process.env.NODE_ENV == 'development' ? false : true` on init

@muriloneo I highly recommend against doing that as if something is wrong with your installation you would not get notified on development and it could crash your production builds.

**Comment by muriloneo** [comment]
I've removed, reinstalled, tried a lot of things and nothing made it work.

Yesterday was working. The only thing that helped was that.

**Comment by jennmueng** [comment]
@muriloneo Is the issue your seeing a YellowBox that says "Note: Native Sentry SDK is disabled." ?

**Comment by muriloneo** [comment]
No.
An alert box.

![image](https://user-images.githubusercontent.com/16191560/89039185-fb2d9b00-d317-11ea-934d-8d3a64ec7e92.png)

**Comment by jennmueng** [comment]
> No.
> An alert box.
> 
> ![image](https://user-images.githubusercontent.com/16191560/89039185-fb2d9b00-d317-11ea-934d-8d3a64ec7e92.png)

@muriloneo This means that the SDK is not linked correctly, if you enable this in production it would crash the app.

**Comment by muriloneo** [comment]
I'll test relase in a few.

But my installation was perfect yesterday. Today woke up with this error.
As I said, removed, cleaned, reinstalled, wizard (3 times) and nothing. Really don't know what to do.

**Comment by jennmueng** [comment]
@muriloneo  Hmm did it install a newer version in the background or something? But yeah, at the very least I strongly suggest if you want to disable native crash handling to just do `enableNative: false` because the error you have there _**would**_ crash on production.

**Comment by cervebar** [comment]
I have the same issue with   `@sentry/react-native": "^5.0.0",` and RN `0.68.3`. Any ideas?
