### ISSUE TITLE
Native crash not reported on ejected expo app

### ISSUE THREAD

**Issue by clems36** [getsentry/sentry-react-native#663]
OS:
- [x]  MacOS

Platform:
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`: ^1.0.5

`react-native` version: 0.59.8

Init Code:

``` js
Sentry.init({
  dsn: 'https://1acf5ce8efb942a08eb1422bfde04cd2@sentry.io/1402155',
});
Sentry.setRelease(
  `${NativeConfigs.SLUG}@${config.VERSION_STRING}-${
    config.JS_BUNDLE_VERSION
  }`,
);
Sentry.setTags({
  environment: NativeConfigs.ENV,
  releaseChannel: Constants.manifest.releaseChannel,
  expoVersion: Constants.expoVersion,
});
```
Hi. I'm successfully able to report crashes using `Sentry.captureException(error);` but `Sentry.nativeCrash();` does not not report anything on the interface.
I've automatically linked the package using `react-native link @sentry/react-native` which worked fine.
I still went to the "Manual setup" section to see if something went wrong, followed the steps for the Android setup and noticed a difference in my setup. In my `android/app/build.gradle` i don't see `apply from: 'react.gradle'`, instead I have `apply from: 'expo.gradle'` which is, according to this file, based on `react.gradle`. 
So here's what it looks like:
```
apply from: 'expo.gradle'
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"

// WHEN_PREPARING_SHELL_REMOVE_TO_HERE

apply from: "../../node_modules/react-native-unimodules/gradle.groovy"

dependencies {
    implementation project(':@sentry_react-native')
    // implementation "com.android.installreferrer:installreferrer:1.0"
    implementation 'io.intercom.android:intercom-sdk-base:5.+'
    implementation project(':react-native-intercom')
    implementation project(':react-native-config')
    implementation project(':react-native-iap')
    implementation project(':react-native-device-info')
    implementation project(':react-native-restart')

etc etc
```
For the rest of the setup, mine is the same as the manual setup.

I have tried the workaround proposed in [this issue](https://github.com/getsentry/sentry-react-native/issues/447#issuecomment-502128256), unsuccessful.

**Comment by clems36** [comment]
Has anyone encountered this ? @HazAT do you have any clue ?

**Comment by HazAT** [comment]
My honest suggestion is, create a clean new project with `react-native init` and copy your code over 😅 
Upgrading react-native project or ejecting expo projects is a nightmare and never works without issues in my experience.
I can't really guide you in any direction since there can be several issues and most likely most of them are not related to our SDK.
