### ISSUE TITLE
RNSentry.extraUpdated is not a function

### ISSUE THREAD

**Issue by joedivittorio** [getsentry/sentry-react-native#664]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

After updating to the latest release and following the migration guide, our app is crashing on launch.

```
RNSentry.extraUpdated is not a function

<unknown>
    backend.js:27:57
<unknown>
    scope.js:51:20
<unknown>
    scope.js:50:38
<unknown>
    JSTimers.js:250:17
_callTimer
    JSTimers.js:146:6
Object.callTimers
    JSTimers.js:399:6
```

```javascript
scope.addScopeListener(scope => RNSentry.extraUpdated(scope._extra));
```
maybe should be `setExtra()`?

**Comment by karltaylor** [comment]
I am also receiving this error after updating.

Platform: iOS
Versions:
```
"react-native": "0.60.4"
"@sentry/react-native": "^1.0.6"
```

**Comment by joedivittorio** [comment]
@karltaylor not sure if it's related but I updated my project to Swift 5 and no longer started seeing the error. I had a few issues in my project after upgrading to RN 0.60 so I can't confidently say that was the issue.

**Comment by karltaylor** [comment]
Downgrading to `"@sentry/react-native": "1.0.5"` fixed my issue

**Comment by captain-xu** [comment]
same here

**Comment by rdewolff** [comment]
With the recent issues am facing with `@sentry/react-native`, am wondering if the lib is stable for production ?

**Comment by jamesholcomb** [comment]
Maybe unrelated, but...I was using 1.1.0 successfully for several days (local dev and a TestFlight deployment).  I was getting low on disk space, so I ran my usual cleanup script:

````
rm -rf ~/Library/Developer/Xcode/Archives
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Developer/Xcode/iOS Device Logs/
rm -rf ~/Library/Logs/CoreSimulator/
xcrun simctl delete unavailable
yarn cache clean
npm cache clean --force
rm -rf "${HOME}/Library/Caches/CocoaPods"
````

and:
````
sudo rm -rf 'iOS 8.4.simruntime'/
sudo rm -rf 'iOS 9.3.simruntime'/
````

afterwards, all of my iOS 12.4 sims started crashing with the `extraUpdated` error.

Subsequently doing a fresh build and app install fixed the problem.

`react-native 0.59.7`

**Comment by rdewolff** [comment]
Trying your cleanup methode @jamesholcomb

**Comment by HazAT** [comment]
Make sure you correctly relink your native deps, this function changed in iOS/Android.

**Comment by elijahmurray** [comment]
@HazAT With all due respect, I followed the documentation precisely with unlinking `react-native-sentry`, and then proceeding to install `@sentry/react-native` and face this issue.

Can you give us some more context to go on? Steps to troubleshoot?

**Comment by schumannd** [comment]
@elijahmurray did you find out a way to fix this issue?

we experience this when debugging via chrome debugger and using Hermes.
Without having remote debugging enabled we get the error:

TypeError: undefined is not a function, js engine: hermes

**Comment by elijahmurray** [comment]
> @elijahmurray did you find out a way to fix this issue?
> 
> we experience this when debugging via chrome debugger and using Hermes.
> Without having remote debugging enabled we get the error:
> 
> TypeError: undefined is not a function, js engine: hermes
> 
> @joedivittorio can you tell me the steps you took to upgrade your project to swift 5?

Yes, I did get it working. I think for me I needed to manually edit my `yarn.lock` and delete either `react-native-sentry` or `@sentry/react-native`, run `yarn`, and then do the setup instructions/steps for `@sentry/react-native`.

**Comment by AntonioRedondo** [comment]
This is absolutely crashing our app. Still happening on `@sentry/react-native` 1.33.

**Comment by AntonioRedondo** [comment]
Where has this `extraUpdated` function been ever written? We're unable to find it on https://github.com/getsentry/sentry-javascript/search?q=extraUpdated or https://github.com/getsentry/sentry-react-native/search?q=extraUpdated.

**Comment by schumannd** [comment]
@AntonioRedondo same problem. Had to downgrade back to 1.2.2

**Comment by schumannd** [comment]
@AntonioRedondo 

I found the function at `node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:`

public void extraUpdated(ReadableMap extra) {

It gets used here: 

```
node_modules/@sentry/react-native/dist/js/backend.js:                scope.addScopeListener(internalScope => RNSentry.extraUpdated(internalScope._extra));
node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:    public void extraUpdated(ReadableMap extra) {
node_modules/@sentry/react-native/src/js/backend.ts:          RNSentry.extraUpdated((internalScope as any)._extra)
```

**Comment by AntonioRedondo** [comment]
It seems that code was removed on version 1.3.0? https://github.com/getsentry/sentry-react-native/commit/01d646558c9f3aafbbaaf76e521a0a8f57c70725#diff-a04c43b551ffa5dd07c8e783e41c8764L62. Downgrading to 1.1.0 didn't work for us. The problem for us seemed to be an old build on fastlane that it wasn't updated.

**Comment by JackHull** [comment]
Can confirm this bug under the newest version of sentry. This is really bugging me, it's crashing our app in production.

**Comment by nzankich** [comment]
Not sure if this will help anyone else but this happened to my team because we did a code push after bumping that sentry package

**Comment by HazAT** [comment]
This can only happen if your native and JS code are out of sync.
This function has been removed in the major bump, if you codepush update your app without releasing the native part as will this will break.
