### ISSUE TITLE
Running `yarn test` fails when integrating Sentry - SyntaxError: Unexpected token export at import *

### ISSUE THREAD

**Issue by hkellaway** [getsentry/sentry-react-native#668]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.6

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

After setting up Sentry per [the docs](https://docs.sentry.io/platforms/react-native/), running `yarn test` fails. 

More specifically, it fails after running Sentry Wizard. The following error occurs:

```
/MyApp/node_modules/@sentry/react-native/dist/js/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { Severity, Status } from "@sentry/types";
                                                                                         ^^^^^^

SyntaxError: Unexpected token export

  25 | } from 'react-native/Libraries/NewAppScreen';
  26 | 
> 27 | import * as Sentry from '@sentry/react-native';
     | ^
  28 | 
  29 | Sentry.init({ 
  30 |   dsn: 'MY_DSN', 

  at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
  at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
  at Object.<anonymous> (App.js:27:1)
```

**Steps to reproduce:**
Here is a sample project demonstrating the issue along with STRs:

https://github.com/hkellaway/sentry-reactnative-yarntest-error-demo

Generally, the least you have to do to produce this error is to:
* generate a brand new project with `react-native` CLI
* follow the Sentry docs for "Integrating the SDK"
* after the Sentry Wizard step, run `yarn test`

**Actual result:**
`yarn test` fails after setting up Sentry for a React Native project

**Expected result:**
Integrating Sentry should not disrupt `yarn test` for React Native projects

**Comment by HazAT** [comment]
Google spit out this:

https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization

It fixes it for me if I add this to `package.json`:
```js
 "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|react-native-cookies|@sentry/react-native)/)"
    ]
  }
```

**Comment by hkellaway** [comment]
i appreciate you investing & responding despite it not being a Sentry issue, rather a Jest configuration

for others who may encounter this - confirmed this does fix error message

**Comment by naguigui** [comment]
Thank god I found this post.

**Comment by borgogelli** [comment]
The right config for Expo Sdk is
```
"jest": {
  "preset": "jest-expo",
  "transformIgnorePatterns": [
    "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
  ]
}
```
see it at https://docs.expo.io/guides/testing-with-jest/

**Comment by Rehan-05** [comment]
Not working, any solution from above these😒

**Comment by marandaneto** [comment]
Please raise a new issue with more context in case something is not working.
