### ISSUE TITLE
1.X.X missing sampleRate option

### ISSUE THREAD

**Issue by kristfal** [getsentry/sentry-react-native#669]
OS:
- [X]  Windows
- [X]  MacOS
- [X]  Linux

_Platform:_
- [X]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: N/A

I have following issue:

Setting a sampleRate option is no longer possible on the 1.0.0 release. This option was available in 0.39.1 and onwards. See https://github.com/getsentry/sentry-react-native/commit/df2c9eaeafcf72cb733089dd06137bdf4bae642f

This option is very usable for large scale applications where a 100% sample rate is not needed.

**Comment by HazAT** [comment]
Doesn't 
```js
Sentry.init({
...
sampleRate: 0.5
...
}):
```

Work as expected?
