### ISSUE TITLE
The project name '@sentry/react-native' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]

### ISSUE THREAD

**Issue by juhaelee** [getsentry/sentry-react-native#675]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native` (^1.0.6)
- [ ]  `react-native-sentry`

`react-native` version: 0.61.1

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Can't build or clean my android app after manually implementing on android. The error I get is:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@sentry/react-native'.
> The project name '@sentry/react-native' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
```

I suspect this comes from the `settings.gradle` or `build.gradle steps`

**Steps to reproduce:**
- Follow manual step here: https://docs.sentry.io/platforms/react-native/manual-setup/#android

**Actual result:**
- See error in description

**Expected result:**
- For the app to build

**Comment by HazAT** [comment]
I think this is an error in our docs, can you try just to add this 
`apply from: "../../node_modules/@sentry/react-native/sentry.gradle"` ?

**Comment by vdolbilov** [comment]
I had this same issue on 1.0.6, fixed it by doing

`implementation project(':@sentry-react-native')` in `build.gradle` > dependencies and 

```
include ':@sentry-react-native'
project(':@sentry-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@sentry/react-native/android')
```

in `settings.gradle`

**Comment by lobsterkatie** [comment]
Added to the docs in https://github.com/getsentry/sentry-docs/pull/1266.
