### ISSUE TITLE
Allow setting the `dist` of the when uploading sourcemaps.

### ISSUE THREAD

**Issue by dotconnor** [getsentry/sentry-react-native#676]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.1

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Instead of manually specifying a build number in xcode in each build, we generate a new ID during compile time and replace it inline without saving it our `info.plist`. 

**Steps to reproduce:**
- Step

**Actual result:**
- All releases uploaded to sentry have the same distribution, `SVN_REVISION`.

**Expected result:**
- All builds include the correct build number, e.g. 50, 75, 90, and therefor do not match up with what Sentry has.

**Comment by nenjamin2405** [comment]
I have the same request, sometimes the source map uploaded missing the distribution code, then the error `source code was not found app:///index.android.bundle` appears
