### ISSUE TITLE
setUser method on Android doesn't result with full data displayed if objects were passed

### ISSUE THREAD

**Issue by mefjuu** [getsentry/sentry-react-native#677]
_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.4

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
Sentry.setExtras({
    deviceCountry: DeviceInfo.getDeviceCountry(),
    deviceLocale: DeviceInfo.getDeviceLocale(),
});
```

---
Calling `setUser` on Android with some extra data (other than built-in userID and username fields) has no result in Sentry logs. On iOS it's fine though.

**Steps to reproduce:**
```
Sentry.setUser({
        userID: String(id),
        username: name,
        foo: {
            bar: 'a'
        },
});
```

**Comment by crazyjooe** [comment]
Having the same issue. Are there any known workarounds or estimates when this will be fixed?

**Comment by crazyjooe** [comment]
I also noticed that `userID` and `id` resolve differently on Android and iOS. So for now, to get the same behavior on both platforms, I do something like this:

```
const sentryUserID = `${userData.userID}:${userData.companyID}`; 

if (Platform.OS === 'android') {
    Sentry.setUser({
        userID: sentryUserID
    });
} else {
    Sentry.setUser({
        id: sentryUserID,
        userID: userData.userID,
        companyID: userData.companyID
    });
}
```

**Comment by mefjuu** [comment]
@crazyjooe I had to use `Sentry.setExtras()` method to store user's extra data.
