### ISSUE TITLE
EXC_BAD_ACCESS on Sentry.nativeCrash()

### ISSUE THREAD

**Issue by indapublic** [getsentry/sentry-react-native#678]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.6

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 20.59 MB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 25.0.2, 25.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
```

Init Code:

```
Sentry.init({
	dsn: Env.SENTRY_ENDPOINT,
	environment: "production",
	loglevel: LogLevel.Debug,
	attachStacktrace: true,
	debug: true,
	// attachStacktrace: false
	// deactivateStacktraceMerging
})
```

---
I have the following issue:

After execute `Sentry.nativeCrash()` my app is crashed and in Sentry I received:
```
EXC_BAD_ACCESS-[SentryClient crash]
fatal
crash > sharedClient > Attempted to dereference null pointer.
```

Is it expected message?
Is it possible to hide those messages (use by `ignoreErrors` for example)?

I saw many issues with EXC_BAD_ACCESS but no useful information still here.

Thanks

**Comment by HazAT** [comment]
Yes, this is expected to test native crashes.
`ignoreErrors` doesn't work yet for native crashes. `EXC_BAD_ACCESS` it the type of the native crash, always look at the stack trace to figure out where the actual crash happened.
