### ISSUE TITLE
'https-proxy-agent-snyk-fork@*' is not in the npm registry

### ISSUE THREAD

**Issue by bogdancochioras-clarisoft** [getsentry/sentry-react-native#681]
OS:
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

_Platform:_
- [X ]  iOS
- [ X]  Android

SDK:
- [X ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

When I install @sentry/react-native i get the following error:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm ERR! 404 
npm ERR! 404  'https-proxy-agent-snyk-fork@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'proxy-agent'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Steps to reproduce:**
npm install @sentry/react-native@latest --save

**Actual result:**
- Error that the library https-proxy-agent-snyk-fork is missing.

**Expected result:**
- Success

**Comment by Matthias-Pichler** [comment]
same for me https://github.com/getsentry/sentry-react-native/issues/682

**Comment by HazAT** [comment]
We are working on this
ref: https://github.com/snyk/snyk/issues/796

**Comment by HazAT** [comment]
Should be fixed by now, was a problem with snyk

**Comment by rbjoshi** [comment]
I am getting the below error while installing the https-proxy-agent-snyk-fork

> npm ERR! code ENOVERSIONS
> npm ERR! No valid versions available for https-proxy-agent-snyk-fork

> and the log file contains
> 2 info using npm@6.9.0
> 3 info using node@v10.16.2
> 4 verbose npm-session e3c0274ec2b05b1f
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 http fetch GET 304 http://registry.npmjs.org/https-proxy-agent-snyk-fork 135ms (from cache)
> 8 silly fetchPackageMetaData error for https-proxy-agent-snyk-fork@latest No valid versions available for https-proxy-agent-snyk-fork
> 9 timing stage:rollbackFailedOptional Completed in 1ms
> 10 timing stage:runTopLevelLifecycles Completed in 1605ms
> 11 verbose type tag
> 12 verbose stack https-proxy-agent-snyk-fork: No valid versions available for https-proxy-agent-snyk-fork

**Comment by Mauricioft** [comment]
Which solved the issue for me.
`
npm install --global copy
npm install
`

**Comment by Mauricioft** [comment]
Which solved the issue for me.
npm install --global copy
npm install
