### ISSUE TITLE
https-proxy-agent-snyk-fork dependency not found in registry

### ISSUE THREAD

**Issue by Matthias-Pichler** [getsentry/sentry-react-native#682]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.6

Init Code:

```
Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: Config.SENTRY_ENV,
  beforeSend: e => (process.env.NODE_ENV === 'development' ? null : e),
  maxValueLength: 10000
});
```

---
I have following issue:

When running `npm i @sentry/react-native` I get the following message: 

```bash
npm i @sentry/react-native                              [d342314]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/https-proxy-agent-snyk-fork - Not found
npm ERR! 404 
npm ERR! 404  'https-proxy-agent-snyk-fork@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'proxy-agent'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matthias/.npm/_logs/2019-10-04T08_30_03_474Z-debug.log
```
Description goes here ...

This only happens with the newest version 1.0.7

**Steps to reproduce:**
- install the newest version of the package (possibly without access to some internal registry)

**Actual result:**
- npm can't find a package dependency

**Expected result:**
- A normal update to the newest version

**Comment by jpaas** [comment]
Upgrading from 1.0.6 to 1.0.7 gives me this...
```
[1/4] 🔍  Resolving packages...
error "proxy-agent-3.1.0.tgz": Tarball is not in network and can not be located in cache (["/Users/jpaas/Documents/osaaru/rnproject/proxy-agent-3.1.0.tgz","/Users/jpaas/Library/Caches/Yarn/v5/.tmp/1cb65d53db120924735197f89834781e/.yarn-tarball.tgz"])
```

**Comment by bogdancochioras-clarisoft** [comment]
No version of `@sentry/react-native` works, I think there might have been a snyk fork with some security patches that might have been deleted or something, does anyone know a temporary fix? Tried to install with --no-optional but snyk doesn't seem to be optional and I have no idea how to disable it or if disabling it would fix the issue.

**Comment by HazAT** [comment]
We are working on this
ref: https://github.com/snyk/snyk/issues/796

**Comment by bogdancochioras-clarisoft** [comment]
It seems this got resolved on `snyk` side with an update on their side

**Comment by Matthias-Pichler** [comment]
@HazAT can confirm it works now
