### ISSUE TITLE
User Feedback can't be sent on Android

### ISSUE THREAD

**Issue by rdinizz** [getsentry/sentry-react-native#683]
_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [0.43.1]  `react-native-sentry`

`react-native` version: 0.59.10

Init Code:

```
Sentry.config(sentryURL, {
    logLevel: SentryLog.Error
  }).install()
```

---
I have following issue:

On iOS I do a Sentry.captureMessage and then Sentry.setEventSentSuccessfully properly, but on android, the request fails with the following error and Status 400:
```
{
  "event_id": [
    "Ensure this field has no more than 32 characters."
  ]
}
```
Request:
```
curl -X POST  -H "authorization:Bearer+token" -H "content-type:application/json" https://sentry.io/api/0/projects/organization/myApp/user-feedback/ -d '{"event_id":"c90b8e81-1e0a-4a26-88f0-dd28a403a2a9","name":"Fulano","email":"my_email","comments":"Bug"}'
```
Request params:
```
{
  "event_id": "c90b8e81-1e0a-4a26-88f0-dd28a403a2a9",
  "name": "Fulano",
  "email": email,
  "comments": "Bug"
}
```

It seems like the event generated for iOS have the event_id dashes removed(it would be like c90b8e811e0a4a2688f0dd28a403a2a9) having less than 32 characters.
But on Android, it has the dashes and because of that, more than 32 characters.

I can send a custom id to the setEventSentSuccessfully, but the feedback message is not associated with the event, and i believe i should send the same id as the lastEventId, so, sending a custom id is not a solution, unless i could create an event with a custom id and then send the feedback with the same id.

I appreciate any help.

**Comment by Speedy1991** [comment]
Maybe related #691

**Comment by HazAT** [comment]
Please follow this, we will most likely add support for this by providing an API but not a UI.
https://github.com/getsentry/sentry-react-native/issues/500
