### ISSUE TITLE
Correct way to upload sourcemaps with Sentry? 

### ISSUE THREAD

**Issue by karltaylor** [getsentry/sentry-react-native#684]
I am trying to upload my sourcemaps to Sentry and after reading the docs a few times I am still not sure if I am missing something or if something is wrong.

First I bundle my app using the command below.

```bash
react-native bundle platform ios --entry-file index.js --dev false --bundle-output ./ios/main.jsbundle --assets-dest ./ios --sourcemap-output ./ios/main.jsbundle.map
```

And then I upload the sourcemaps:

```bash
node_modules/@sentry/cli/sentry-cli releases files ${RELEASE_NAME} upload-sourcemaps --ext map ./ios
```

Now even though the artifacts are shown in the release, I still do not get context in the UI.

Any help would be greatly appreciated!

"@sentry/react-native": "1.0.5",
"@sentry/cli": "^1.47.2"

**Comment by HazAT** [comment]
Can you link to one of your events plz so I can take a look?

**Comment by karltaylor** [comment]
> Can you link to one of your events plz so I can take a look?

https://sentry.io/organizations/wearesavvy/issues/1256123440/?project=1502818&statsPeriod=14d

I'm wondering if I am not uploading the source files correctly?

**Comment by HazAT** [comment]
So in this example, the event has a `dist: 53` so you also need to define this in the upload of sentry-cli with `--dist 53`.
This will picked up from the build number in the SDK.

Once you upload the artifacts with `--dist` it should work for future crashes, the rest looks fine.

**Comment by chj-damon** [comment]
@HazAT when I'm going to upload sourcemap file, how do I know what the dist is?

**Comment by karltaylor** [comment]
> @HazAT when I'm going to upload sourcemap file, how do I know what the dist is?

@HazAT Correct me if I am wrong but the dist is the build number?
