### ISSUE TITLE
Console Breadcrumbs - Plan to Re-enable?

### ISSUE THREAD

**Issue by cojo** [getsentry/sentry-react-native#685]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.1

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---

It appears that console breadcrumbs were intentionally disabled in the run-up to the 1.0.0 release:
https://github.com/getsentry/sentry-react-native/blob/cc987982650751b98cedb5099ed8117b75208abd/src/js/sdk.ts#L43

We just upgraded as part of our upgrade to 0.61+ and losing this is a pretty big deal for us as customers of Sentry.

Is there a plan to address / fix whatever breakage required hard-disabling these across the board?  If not, can you provide some more detail / context here around how we might investigate / try to workaround this ourselves?

I understand it may not be entirely on the Sentry side of things that the breakage occurred, but it would still be helpful in that case to understand what issue(s) you've filed with the React Native core project and what we should expect here going forwards.

Thanks!

**Steps to reproduce:**
- Upgrade to latest @sentry/react-native from previous react-native-sentry.

**Actual result:**
- Console breadcrumbs are no longer logged.

**Expected result:**
- Console breadcrumbs should continue to be logged as they were previously.

**Comment by dgobaud** [comment]
yes please! bring it back :sob:

**Comment by cojo** [comment]
@HazAT 
Thanks for adding the labels to this - I was wondering if you might be able to provide any additional context to how re-enabling this feature / functionality is currently prioritized on your backlog and what the expected scope is / what the nature of the issue is?

It'd be helpful as we're evaluating Sentry alternatives to know if this is going to be addressed soon or if it is still not formally on the short- / medium-term roadmap.

Thanks!

**Comment by kpheasey** [comment]
We found it was better to create our own Logger and use that to handle the necessary Sentry calls.  Using your own logger, instead of console.log is also going to be more flexible long term.

Here's a gist with the logger we use to avoid red screen on development and create necessary breadcrumbs via regular logging.

https://gist.github.com/kpheasey/c973cebfd739ca3a21d67c03cdd408fa

**Comment by HazAT** [comment]
This PR re-enables it, will release it soooon
https://github.com/getsentry/sentry-react-native/pull/749
