### ISSUE TITLE
Compilation error with version 1.0.8

### ISSUE THREAD

**Issue by Mitch528** [getsentry/sentry-react-native#690]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

---
I have following issue:

Upgrading to @sentry/react-native version 1.0.8 results in a compilation error:

```
> Task :@sentry_react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
902 actionable tasks: 16 executed, 886 up-to-date
/Users/mitch528/repos/Project/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:190: error: incompatible types: String cannot be converted to Type
                    breadcrumbBuilder.setType(breadcrumb.getString("type"));
                                                                  ^
Note: /Users/mitch528/repos/Project/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
```

**Steps to reproduce:**
- Upgrade to version 1.0.8
- Build

**Actual result:**
- Compile fails

**Expected result:**
- Compile succeeds

**Comment by fungilation** [comment]
Same here. Used to build up to 1.0.7. A little more log for debug:

```
/Users/gfung/Documents/code/WonderSwipe/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:190: error: incompatible types: String can
not be converted to Type
                    breadcrumbBuilder.setType(breadcrumb.getString("type"));
                                                                  ^
Note: /Users/gfung/Documents/code/WonderSwipe/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@sentry_react-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by Titozzz** [comment]
https://gist.github.com/Titozzz/837da990bcc0ec9f43cc272b10288671 if anyone needs it. I'll submit a PR in the meantime

**Comment by lobsterkatie** [comment]
Sorry, all - we're aware of this and are working on a fix.

**Comment by lobsterkatie** [comment]
Thanks for @Titozzz for the fix, which we've merged.

**Comment by acollazomayer** [comment]
I have the same problem with version 1.0.9

**Comment by lobsterkatie** [comment]
@acollazomayer - same exact error message? Can you please post whatever output you're seeing if it's different from the OP's?

**Comment by bruscantini** [comment]
> I have the same problem with version 1.0.9

Try using Jetify after using the Android Studio migration tool.
`Make sure your app is AndroidX`
`npm install --save-dev jetifier`
`npx jetify`

**Comment by lobsterkatie** [comment]
Also, @acollazomayer - please try updating the the latest `@sentry/react-native` (`1.3.3` as of this writing) - we moved our android dependency from `sentry-java` to the [new](https://blog.sentry.io/2019/11/25/adding-native-support-to-our-android-sdk) `sentry-android` SDK, which should hopefully eliminate any number of previous problems.
