### ISSUE TITLE
Wrong/Missmatching eventId's

### ISSUE THREAD

**Issue by Speedy1991** [getsentry/sentry-react-native#691]
_Platform:_
- [?]  iOS
- [x ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.1 (unrelated?)

Init Code:

```
Sentry.init({
  dsn: <myDsn>,
  environment: <myEnvironment>,
})
```

---
I have following issue:

Calling `Sentry.getCurrentHub().lastEventId()` gives a missmatching eventId compared to the one on the server.

E.g.:
Client: `8ff0881f2e5346e2a53c2d3982cb8f3a`
Server: `82a139001edf440a8556c1158ed6699f`

Sending feedback to the server with a valid but not existing event creates a 200 response but no feedback on the server.

E.g.:

Created Event on the server has `82a139001edf440a8556c1158ed6699f`
```
    const eventId = Sentry.getCurrentHub().lastEventId()  //8ff0881f2e5346e2a53c2d3982cb8f3a
    const data = {
      comments: message,
      email,
      name,
      event_id: eventId,
    }
    const response = await fetch(SENTRY_FEEDBACK_URL, {
      method: 'POST',
      headers: {
        Authorization: `DSN ${SENTRY_DSN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })
    return response  // 200
```

After digging in the sources for the android code, I found that EventBuilder is missing the `eventId` in the constructor [here](https://github.com/getsentry/sentry-react-native/blob/master/android/src/main/java/io/sentry/RNSentryModule.java#L174) and therefore a random uuid is generated

This patch will fix it:
```
import java.util.UUID;
...

EventBuilder eventBuilder;
if (event.hasKey("event_id")) {
    UUID eventId = UUID.fromString(event.getString("event_id").replaceFirst(
            "(\\p{XDigit}{8})(\\p{XDigit}{4})(\\p{XDigit}{4})(\\p{XDigit}{4})(\\p{XDigit}+)",
            "$1-$2-$3-$4-$5"));
    eventBuilder = new EventBuilder(eventId).withLevel(eventLevel(castEvent));
 } else {
     logger.info("Event has no event_id");
     eventBuilder = new EventBuilder().withLevel(eventLevel(castEvent));
 }
```

Another problem is, that we get the `event_id` in an uuid4 format without `-`, so we need to place them back again to get running Java Code

**Comment by filipef101** [comment]
https://github.com/getsentry/sentry-react-native/pull/706

**Comment by lobsterkatie** [comment]
Thanks, @Speedy1991 and @filipef101!
