### ISSUE TITLE
Context values not getting attached to native crashes

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-react-native#694]
OS:
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

_Platform:_
- [X ]  iOS
- [ ]  Android

SDK:
- [X ]  `@sentry/react-native` 1.0.6
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

**Init Code:**

```
Sentry.init({
  dsn: 'https://xxxxxx@sentry.io/xxxxx',
  environment: 'prod',
  attachStacktrace: true,
  debug: true,
});
Sentry.setRelease('friday');

Sentry.configureScope(scope => {
  scope.setTags({dogs: 'yes', cats: 'maybe'});
  scope.setExtras({things: 'stuff'});
  scope.setUser({id: 26, email: 'maisey@dogsrule.com'});
});
```

---
**I have following issue:**

None of the values set on the scope come through on native crashes.

**Steps to reproduce:**
Add context to scope and trigger a native crash.

**Actual result:**
None of the scope data is displayed:

![image](https://user-images.githubusercontent.com/14812505/66687125-88431e80-ec36-11e9-831b-c0795affee81.png)

[no image of extra data to show here because it doesn't come through]

**Expected result:**
Scope data is added to event, as it is for JS events:

![image](https://user-images.githubusercontent.com/14812505/66687192-b9235380-ec36-11e9-9366-438a996dcc71.png)

![image](https://user-images.githubusercontent.com/14812505/66687806-dc4f0280-ec38-11e9-822a-a60a324e1e1b.png)

**EDIT**: Per @HazAT, this applies to breadcrumbs as well.

**Comment by HazAT** [comment]
To add to this, `scope.setContext` or `Sentry.setContext` also currently doesn't work.

**Comment by anguyen1817** [comment]
I'm experiencing the same issue.

**Comment by halilb** [comment]
This is also a huge problem for us. We can't track any tag data on native crashes.

The data coming from `beforeSend` method is also not sent along with the native crash log.

**Comment by mattijsf** [comment]
Same thing for us. We set the user id on the javascript side like this:

```javascript
Sentry.setUser({ id: AppSettings.deviceLogin })
```

But there is a difference between native errors / js errors:
`Sentry.nativeCrash()` = Missing expected user id 👎 
`Sentry.captureException(new Error("JS Error"))` = User id is present and correct 👍 

 Both these methods are called after `Sentry.init` & `Sentry.setUser`.

I would expect these values / tags to be configured on the native crash handlers as well.

**Comment by mefjuu** [comment]
Do you experience a missing context problem on iOS only? As far as I see the same issue occurs on Android as well.

**Comment by jbolter** [comment]
Any update on this? This makes deciphering native crashes really difficult.

**Comment by benanderman** [comment]
> Any update on this? This makes deciphering native crashes really difficult.

Also wondering; we've held back on updating to `@sentry/react-native` because of this, but that means we're pretty out of date.

**Comment by ulion** [comment]
The context should be unified, the context should also be send to native sdk clearly. +1.

**Comment by nluetteken** [comment]
Same issue here. Would be really helpful to get it fixed.

**Comment by ajouve** [comment]
I am testing the following code after sentry init 

```js
Sentry.setContext('foo','bar');
Sentry.captureException(new Error('Test sentry error'));
```
My context is not displayed 

In `ADDITIONAL DATA` I just have undefined values 

<img width="1097" alt="Screenshot 2020-06-06 at 16 27 37" src="https://user-images.githubusercontent.com/2337492/83946693-bb17d380-a812-11ea-82d1-8e65fa4a7c4a.png">

**Comment by jennmueng** [comment]
> I am testing the following code after sentry init
> 
> ```js
> Sentry.setContext('foo','bar');
> Sentry.captureException(new Error('Test sentry error'));
> ```
> 
> My context is not displayed
> 
> In `ADDITIONAL DATA` I just have undefined values
> 
> <img alt="Screenshot 2020-06-06 at 16 27 37" width="1097" src="https://user-images.githubusercontent.com/2337492/83946693-bb17d380-a812-11ea-82d1-8e65fa4a7c4a.png">

@ajouve `Sentry.setContext` takes an object as a second parameter and not a string:
http://getsentry.github.io/sentry-javascript/classes/hub.scope.html#setcontext

I see that in the docs [here](https://docs.sentry.io/platforms/javascript/) we have mistakenly put a string as an example. Is there anywhere else that you got the info from so we can go fix the documentation? Thanks!
