### ISSUE TITLE
int user id causes "Value for id cannot be cast from double to string" in sendEvent

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-react-native#695]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native` 1.0.9
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

Init Code:

```
Sentry.init({
  dsn: 'https://xxxxxx@sentry.io/xxxxx',
  environment: 'prod',
  attachStacktrace: true,
  debug: true,
});
Sentry.setRelease('friday');

Sentry.configureScope(scope => {
  scope.setTags({dogs: 'yes', cats: 'maybe'});
  scope.setExtras({things: 'stuff'});
  scope.setUser({id: 26, email: 'maisey@dogsrule.com'});
});
```

---
I have following issue:

Setting my user id as an int rather than a string causes `sendEvent` to crash.

**Steps to reproduce:**
See above where I set the user id - it's `26`, not `"26"`, and sending events crashes.

**Actual result:**

![image](https://user-images.githubusercontent.com/14812505/66805123-0e7e8f80-eed9-11e9-8250-d0887908111e.png)

**Expected result:**
Casting is handled gracefully and id comes through as a stringified version of its int value.

**Comment by dapicester** [comment]
I bumped into this too. Casting `id` to String fixed it but I guess this could be done automatically.
