### ISSUE TITLE
error stack trace cannot be linked to sourcemap

### ISSUE THREAD

**Issue by chj-damon** [getsentry/sentry-react-native#696]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [ ]  `@sentry/react-native`
- [x]  `react-native-sentry`

`react-native` version: 0.59.10

Init Code:

```
Sentry.config('https://cb3d19e29ca94867b750e4fb96041fbf@sentry.io/1779787').install();
Sentry.setRelease('com.dataApp-1.0');
Sentry.setDist('1');
```

---
I have following issue:

I've already uploaded bundle file and sourcemap file to sentry, which I can see them in releases/com.dataApp-1.0/Artifacts.
![image](https://user-images.githubusercontent.com/4902684/66817818-e04b8f00-ef6e-11e9-8da0-74be7e0cc169.png)

Then I capture an exception in my code, like this:
```
Sentry.captureException(new Error('4444'));
```
I can see this issue then:
![image](https://user-images.githubusercontent.com/4902684/66817730-c0b46680-ef6e-11e9-957c-952c45f622d0.png)

I noticed that `release` and `dist` can match the releases info.

my question is: why cannot the track trace be linked with the sourcemap so I can get a better information about which line causes this issue, just like this:
![image](https://user-images.githubusercontent.com/4902684/66818008-391b2780-ef6f-11e9-8ea7-f476c069a155.png)

**Steps to reproduce:**
- Step

**Actual result:**
- issue is not linked with sourcemap

**Expected result:**
- issue can be linked with sourcemap so I know the exact line causes this issue

**Comment by chj-damon** [comment]
sorry, I didn't get any further information from the official team.

**Comment by AdriaRios** [comment]
Could you solve it? It seems there are many issues related

**Comment by chj-damon** [comment]
I can't solve it without help. Actually I didn't know what wrong it would be.

**Comment by HazAT** [comment]
Can you update to `@sentry/react-native` and see if the problem is still there?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
