### ISSUE TITLE
Stacktrace is looking for sourcemaps in the wrong location `app:///at index.android.bundle`

### ISSUE THREAD

**Issue by lunks** [getsentry/sentry-react-native#697]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.59.10

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:
I'm using `bundleRelease` as my main gradle task to release Android bundle builds to the Playstore. I'm also using `react-native-v8` as the JS interpreter. My sourcemaps are not being detected due to the bundle URL being different from uploaded.

**Steps to reproduce:**
- Run `bundleRelease`
- Have a crash on the app
- Look at the Stacktrace

**Actual result:**
 
![image](https://user-images.githubusercontent.com/91118/66834587-4d8dfe80-ef34-11e9-813a-686e38c0ea43.png)

The sourcemaps for the specific distribution is listed in the artifact as:

```
~/index.android.bundle
~/index.android.bundle.map
```

**Expected result:**

The stacktrace should be looking at `~/index.android.bundle`, not `app:///at index.android.bundle`.

**Comment by OlivierFreyssinet** [comment]
Same issue here, did anyone find a workaround ?

**Comment by christhegrand** [comment]
Yes, it's a react-native-v8 issue. I asked about this on the Sentry forum sometime back and got an answer which fixed the issue for us: https://forum.sentry.io/t/source-code-was-not-found-when-sourcemaps-available/7685

Here's the code from HazAT that should do the trick:

```
import { RewriteFrames } from "@sentry/integrations";

const rewriteFramesIntegration = new RewriteFrames({
  iteratee: frame => {
    if (frame.filename) {
      frame.filename = frame.filename
        .replace(/^file\:\/\//, "")
        .replace(/^address at /, "")
        .replace(/^.*\/[^\.]+(\.app|CodePush|.*(?=\/))/, "");
 // Add additional regex here to fix the `at` issue

      const appPrefix = "app://";
      // We always want to have a tripple slash
      frame.filename =
        frame.filename.indexOf("/") === 0
          ? `${appPrefix}${frame.filename}`
          : `${appPrefix}/${frame.filename}`;
    }
    return frame;
  }
});

Sentry.init({
  dsn: "your DSN",
  integrations: [rewriteFramesIntegration],
});
```

**Comment by OlivierFreyssinet** [comment]
Wow great, thanks a lot for this @christhegrand ! Now I can safely use react-native-v8 in production 😁
What fixed it for me was adding this line:

**Comment by christhegrand** [comment]
Whoops, I hadn't noticed the snippet I posted was missing the replace call that'll fix this. I just added it.

**Comment by HazAT** [comment]
This seems to be solved, I am closing this.
