### ISSUE TITLE
error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by olegzaitsevwayway** [getsentry/sentry-react-native#698]
OS:
- [ ]  Windows
- [+]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [+]  Android

SDK:
- [ ]  `@sentry/react-native`
- [+]  `react-native-sentry`

`react-native` version: 0.59.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:
error: package android.support.annotation does not exist
error: cannot find symbol class NonNull

Description goes here ...
I have 2 issues while building my app

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by Bang9** [comment]
`npm install --dev jetifier`
