### ISSUE TITLE
Incompresible source code

### ISSUE THREAD

**Issue by nicomontanari** [getsentry/sentry-react-native#699]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [X]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.0.0

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
  environment: DEBUG ? 'staging' : 'production',
});
```

---
I have following issue:
<img width="960" alt="Screenshot 2019-10-17 at 11 45 31" src="https://user-images.githubusercontent.com/15747776/66997939-a5af3700-f0d3-11e9-8701-7f81eb7265f1.png">

**Comment by benlaverriere** [comment]
What react-native version are you using? And do you have [Hermes](https://facebook.github.io/react-native/docs/hermes) enabled as the JS engine for Android? This looks like #649, potentially.

**Comment by nicomontanari** [comment]
@benlaverriere thank you, it's the same issue.
