### ISSUE TITLE
Use Sentry Wizard with RN 0.61.2 and autolinking.

### ISSUE THREAD

**Issue by samitha9125** [getsentry/sentry-react-native#701]
OS:
- [ ]  Windows
- [ ✔ ]  MacOS
- [ ]  Linux

_Platform:_
- [✔ ]  iOS
- [✔ ]  Android

SDK:
- [✔ ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

---
I have following issue:

In sentry react native documentation, it has defined how to invoke sentry wizard with yarn but failed to mention it for npm. So for me, I have to use link command to invoke sentry wizard but since I'm using autolinking, cannot use that either. Please update the documentation with relevant details.

**Comment by HazAT** [comment]
We added it to the docs.
