### ISSUE TITLE
Custom error type are encrypted as 'n'

### ISSUE THREAD

**Issue by zmnv** [getsentry/sentry-react-native#702]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

Environment:
- Production

Selfhosted Sentry 9.1.2

`react-native` version: 0.60.4
`@sentry/react-native` version 1.0.9

Init Code:

```js
Sentry.init({
  dsn: 'https://...@sentry.selfhosted.ninja/...',
  environment: __DEV__ ? 'development' : 'production',
});
```
or

```js
import { ExtraErrorData } from '@sentry/integrations';

Sentry.init({
  dsn: 'https://...@sentry.selfhosted.ninja/...',
   integrations: [
      new ExtraErrorData(),
   ]
});
```

---
**I have following issue:**

I want to use custom error type extends of Error class.
```js
class SuperCustomError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}

...

class Profile extends Component {
...
  componentDidMount() {
    Sentry.captureException(new SuperCustomError('my error'));
  }
...
}
```
but in Sentry I see that error as 'n' type name. 
I see in http response of browser client:
```js
...
metadata: {
  filename: "js/screens/Profile.js"
  function: "SuperCustomError" // << it should be componentDidMount
  type: "n" // <<<<<
  value: "my error"
}
...
```

**Steps to reproduce:**
1. Create custom error class extends of `Error`
2. Build production by `cd android && ./gradlew assembleRelease` without hermes
3. Throw error from any place
4. Go to Sentry admin website and see new event

**Actual result:**

![image](https://user-images.githubusercontent.com/25253501/67246759-08a02580-f468-11e9-9ec1-86fa8cb72fe4.png)

![image](https://user-images.githubusercontent.com/25253501/67244388-413d0080-f462-11e9-8146-059f64cca1a2.png)

**Expected result:**

![image](https://user-images.githubusercontent.com/25253501/67246397-05f10080-f467-11e9-93a6-18744e5d2e08.png)
_(reproduced with chrome dev tools)_

### Questions

1. What am I doing wrong and how to create 'readable' error types?
2. Why Sentry do accent to error class/function part, not the actual function threw error (componenDidMount)?
3. Do I need integrate something else to work with custom error types?

---

PS: Also, when I try `Error.captureStackTrace` app crashes with error '**Error.captureStackTrace is not a function**'. I can't find answer about it in react-native. Does it connected with this issue?

PSS: For install I used yarn sentry-wizzard to autolinking. 
PSS2: Sourcemaps and debug symbol in sentry. There is no errors to load .jsbundle and .map files:
```
Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
```

PSSS: Common JS error like `Error`, `ReferenceError` and other 'standart' types works fine!

```
Sentry.captureException(new Error('New Simple Error'));
```

![image](https://user-images.githubusercontent.com/25253501/67246228-8e22d600-f466-11e9-9b96-7b82d143aa3c.png)

**Comment by zmnv** [comment]
Research results:

1. Error type name

```
class SuperCustomError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}
```

```
 this.name = this.constructor.name;
```

gives encrypted 'n' error type name, but if I do:
```
 this.name = 'MyCustomError';
```
I see MyCustomError error type name in Sentry. This is not so awesome.

2. Error.captureStackTrace is undefined. I see 

I have to heard you use TraceKit. So, how can I do 'pop stack frame' for custom error class wrapper without some magic?

I found this: https://github.com/getsentry/sentry-javascript/blob/22a2a4e42f59fa83052d71ad53c1786f5596d526/packages/browser/src/tracekit.ts#L55

How I can access to change stack frames to remove the unnecessary frames?

**Comment by marandaneto** [comment]
if not using `this.name = this.constructor.name;`, it works, wondering if this is a symbolication issue, I'll check it

**Comment by kamilogorek** [comment]
> How I can change stack frames right to remove the unnecessary frames?

```js
class SuperCustomError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
    this.framesToPop = 2;
  }
}
```

**Comment by marandaneto** [comment]
unfortunately, it's a known limitation of source maps.
you could tho set it in your build tool to not mangle specific names, eg, your custom errors.

**Comment by kamilogorek** [comment]
See https://github.com/facebook/metro/issues/154 and https://forums.expo.dev/t/change-minifierconfig-for-minify-uglify/36460 for how to update `mangle` option in case you want to go that route.
