### ISSUE TITLE
Allow adding --dist option in uploading source map

### ISSUE THREAD

**Issue by nenjamin2405** [getsentry/sentry-react-native#703]
Hi @HazAT, currently I'm facing a problem of `Source code was not found` in Url `app:///index.android.bundle`. I'm using Sentry together with Codepush, after using the command: 

`sentry-cli react-native appcenter --deployment Staging MyAppName android ./build/android/CodePush`

In` the Artifacts tab, `index.android.bundle` and `index.android.bundle.map` were uploaded but the `Distribution` fields are `None`. But my error includes both `release_name` and `dist`, so it cannot map with those artifacts.

So my question is: How can I resolve this? I cannot find --dist as an option in sentry-cli react-native appcenter -h. I already tried to use --dist but it's not a valid option.

_Originally posted by @nenjamin2405 in https://github.com/getsentry/sentry-react-native/issues/612#issuecomment-534402454_

**Comment by lobsterkatie** [comment]
@nenjamin2405 (and anyone else who runs into this) - Currently, your best option is to strip the `dist` value from the event in `beforeSend`:

```
Sentry.init({
  dsn: 'YOUR DSN',
  beforeSend: (event, hint) => {
    delete event.dist;
    return event;
  },
});
```

**Comment by mokoshi** [comment]
I'm facing with a same issue. 
I can see the release artifacts with the same release name as issues have, but the source map is not applied.
The DISTRIBUTION column of the artifact is `None` (and as @nenjamin2405 says there is no option on sentry-cli to set it), so I've stripped the `dist` parameter from the event (referring to @lobsterkatie), but still the source map is not applied.

**Comment by nenjamin2405** [comment]
Hi @lobsterkatie. thanks for your suggestion, but the thing is, whenever I release a new build for both iOS and Android on production, Sentry automatically upload the source map with the `dist` option so if I get rid of the `dist` in all Sentry events then again I cannot map them together, so in summary, there are 2 cases:

1. I initially release the build on Production (without any Codepush at that time), so the source map uploaded will have both version name and dist --> every time user has a problem in the app, Sentry will send the error event with both version and dist so that I can map them together, everything is fine in this case.

2. I refine some javascript code in my app, publish a codepush update, after the codepush command is finished, the sentry-cli uploads new source map, but the source map is missing `dist`, then later on, every user whose app has been updated via Codepush and has issue in the app, the Sentry still send both version and dist as usual, but the codepush source map now doesn't have `dist` --> cannot map

Any idea on this :(

**Comment by asiFarran** [comment]
Any progress on this? We are too are struggling greatly with this issue

**Comment by lobsterkatie** [comment]
@nenjamin2405 - the above should do what you need (and allow you to stop stripping `dist` values in `beforeSend`). Can you please let me know if you're still running into problems?
