### ISSUE TITLE
https-proxy-agent vulnerability

### ISSUE THREAD

**Issue by allisonkbarr** [getsentry/sentry-react-native#705]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.0

---
I have following issue:

The latest release of @sentry/react-native includes a dependency on https-proxy-agent 2.2.1, which has a high severity vulnerability - https://www.npmjs.com/advisories/1184. Per the npm advisory, it should be updated to use 2.2.3 or 3.0.0.

**Steps to reproduce:**
- run `npm audit` to show the vulnerability information

**Actual result:**
- High severity vulnerability alert

**Expected result:**
- No high or critical vulnerabilities

**Comment by antpuleo2586** [comment]
@allisonkbarr I just updated sentry from 1.0.4 to 1.0.9 and fixed this. I also deleted my lock file to fix an issue with another dependency so that might help.

**Comment by HazAT** [comment]
Yeah, please upgrade to the latest version, it should be fixed there.
