### ISSUE TITLE
Crash in release mode when sending test JS / Native Crash

### ISSUE THREAD

**Issue by darekg11** [getsentry/sentry-react-native#708]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

When I am trying to test out Sentry in Release build, my app crashes completely and no issues are registered at Sentry side. I am only able to find following log via logcat:

```
0-26 17:24:02.859  3196  3212 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.util.ReportTools.getUserType(ReportTools.java:86)
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.util.ReportTools.isBetaUser(ReportTools.java:73)
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.util.ReportTools.report(ReportTools.java:58)
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.util.HwUserBehaviourRecord.appExitRecord(HwUserBehaviourRecord.java:65)
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1576)
10-26 17:24:02.859  3196  3212 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-26 17:24:02.859  3196  3212 W System.err:    at android.os.Looper.loop(Looper.java:150)
10-26 17:24:02.859  3196  3212 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)
10-26 17:24:02.859  3196  3212 W System.err:    at com.android.server.ServiceThread.run(ServiceThread.java:46)
10-26 17:24:02.859  3196  3212 E ReportTools: This is not beta user build
```

Running on Android 6.0, Huawei P8 Lite phone  
It worked correctly while in standard, debug build.  
I am also using Hermes if this makes any difference.
**Steps to reproduce:**
- Have 2 buttons that luanches following funtions:
```
const testJs = () => {
	throw new Error('SENTRY EVENT JS')
}

const testNative = () => {
	Sentry.nativeCrash()
}
```
- Build app in Release mode via: `./gradlew --info assembleRelease`
- Install app on device
- Tap either button to send JS Exception or Native Crash

**Actual result:**
- App crashes completely and Sentry does not record any issues at all

**Expected result:**
- App should not crash and Sentry should correctly record test exceptions

**Comment by darekg11** [comment]
It seems that running `react-native link` (even thought I am on RN 0.60.5) and generating `sentry.properties` helped a little bit and now it is correctly sending events, I will close this.

**Comment by aliwaqar981** [comment]
Hi @darekg11, I'm still facing this issue. I tried running react-native link but sentry.properties not created. Can you please help?

**Comment by jennmueng** [comment]
@aliwaqar981 Did you run the sentry wizard and pod install step? 
https://docs.sentry.io/platforms/react-native/#linking

**Comment by aliwaqar981** [comment]
@jennmueng Yes I've done that and realized that sentry.properties is already created in android and ios folder but somehow crashes are not getting reported in release build.
