### ISSUE TITLE
Console integration doesn not work for warn, it works only for log and error

### ISSUE THREAD

**Issue by fdobre** [getsentry/sentry-react-native#710]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

_Platform:_
- [ x]  iOS
- [ ]  Android

SDK:
- [ x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.59.19

Init Code:

```
Sentry.init({
  dsn: SENTRY_CONFIG_KEY,
  release: MOBILE_VERSION_INFO,
  environment: (__DEV__ ? 'development' : 'production'),
  integrations: [new Integrations.CaptureConsole({ levels: ['log', 'warn', 'error'] })],
  maxBreadcrumbs: 50,
});
```

---
I have following issue:

Warn events are not sent to sentry, only the log and error events

Description goes here

Console integration doesn`t not work for warn, it works only for log and error.

**Steps to reproduce:**
- Step
Install     "@sentry/react-native": "^1.0.9",
Run 
```
      console.log('PLATFORM IOS - THIS IS A SENTRY TEST OF LOG');
      console.warn('PLATFORM IOS - THIS IS A SENTRY TEST OF WARNING');
      console.error('PLATFORM IOS - THIS IS A TEST FOR ERROR');
```
in app render method.

**Actual result:**
Only log and error events are sent
- Actual

**Expected result:**
All Events from levels array should be sent.
For web using '@sentry/browser' warn events are sent.

**Comment by 77xi** [comment]
another question why config release manuall ？

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

ps: works on the latest Sentry RN SDK version.
