### ISSUE TITLE
Source code was not found when processing event

### ISSUE THREAD

**Issue by karltaylor** [getsentry/sentry-react-native#712]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

Init Code:

```js
Sentry.init({
  dsn: 'https://<omitted>@sentry.io/1502818',
});
Sentry.setRelease(sentryRelease);
```

---

When I receive an error on Sentry I am getting the following error:

<img width="1111" alt="Screenshot 2019-11-06 at 15 50 19" src="https://user-images.githubusercontent.com/6763109/68313841-2a76ea80-00ad-11ea-9aa4-8b82358a829f.png">

Here are my artifacts:

<img width="1448" alt="Screenshot 2019-11-06 at 15 50 55" src="https://user-images.githubusercontent.com/6763109/68313884-3cf12400-00ad-11ea-9b54-aa89cc5ad4d2.png">

This worked fine running on my device in Release mode, and then throwing an error. 

I have finished the steps in this issue I had previously: https://github.com/getsentry/sentry-react-native/issues/684

[Here is a link](https://sentry.io/organizations/wearesavvy/issues/1306547731/?project=1502818&referrer=slack) to the error in question.

Do I have to use `--rewrite` to match `app:///`?

**Comment by HazAT** [comment]
You need to make sure that both `dist` and `release` of the event match exactly the filename of the artifact.

`~/main.jsbundle` is ok.
