### ISSUE TITLE
Recursion Limit Hit

### ISSUE THREAD

**Issue by lisabaut** [getsentry/sentry-react-native#713]
**OS:**
- [x]  MacOS

**Platform:**
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native`

**react-native version:** 
0.61.2

**Init Code:**

```
import * as Sentry from '@sentry/react-native';

Sentry.init({
  dsn: 'https://...@sentry.io/...',
  debug: true
});
```

---
**I have the following issue:**

When passing a deep nested object with `scope.setExtras` to the local scope like:
```
 Sentry.withScope(scope => {
    scope.setTag('my tag', 'my value');
    scope.setExtras(deepNestedObject); // <-- !
    Sentry.captureMessage('my error message);
});
```

the object's data structure is displayed nicely within the report details view in the Sentry UI below the "Additional Data" section.

Unfortunately it stops showing further key-value pairs below the third nested object level.
Instead each value is displayed with `<recursion limit hit>`.

Within the docs for react native SDK I was not able to find a possibility to increase the display depth for nested objects.

[This issue](https://github.com/getsentry/sentry-react-native/issues/285) does not provide a solution unfortunately.

[This issue](https://github.com/getsentry/sentry-javascript/issues/1964) with a similar topic refers to the Javascript SDK and points to the [Sentry JavaScript docs](https://docs.sentry.io/platforms/javascript/#extraerrordata).

But `Sentry.Integrations.ExtraErrorData` does not exist in the `@sentry/react-native` package

and this code does not work for me in `react-native`:
```
import * as Sentry from '@sentry/react-native';
import * as Integrations from '@sentry/integrations';

Sentry.init({
  dsn: 'https://...@sentry.io/...',
  integrations: [new Integrations.ExtraErrorData({ depth: 10 })],
  debug: true
});
```

## Question:
How can I increase the depth level in `@sentry/react-native` for displaying deep nested objects in the "Additional Data" section?
Thanks.

**Comment by 77xi** [comment]
m

**Comment by 77xi** [comment]
it was well for me ，maybe you have a typo setExtras -> setExtra ?
```
Sentry.withScope(scope => {
    scope.setTag('my tag', 'my value');
    scope.setExtras(deepNestedObject); // <-- !
    Sentry.captureMessage('my error message);
});
```

**Comment by vasilich6107** [comment]
Any news?

**Comment by lobsterkatie** [comment]
The `<recursion limit hit>` comes from the [Java SDK](https://github.com/getsentry/sentry-java/blob/4a7e5b092dbfc90af78962fd4e3c33e34c76c7ea/sentry/src/main/java/io/sentry/marshaller/json/SentryJsonGenerator.java#L26) (which underlies this SDK's Android reporting) and is unfortunately not currently configurable. There's an issue tracking that question [here](https://github.com/getsentry/sentry-java/issues/543).

**Comment by alew97** [comment]
I saw @lobsterkatie 's response on https://github.com/getsentry/sentry-java/issues/543 about RN sentry no longer relying on the Java SDK which defines the max nesting level of 3. However I still don't know how to increase this limit beyond 3. As @lisabaut pointed out in the original post, the `ExtraErrorData` integration does not work in React Native.

any tips from anyone?

**Comment by lobsterkatie** [comment]
@jennmueng You're the most up on the current RN SDK. Do you know which of the wrapped SDKs sets the max depth? If not I can dig into it.

**Comment by jennmueng** [comment]
@lobsterkatie @alew97 It's set on JS, now Android and Cocoa shouldn't touch the nesting depth anymore if I recall correctly. So if you just set `normalizeDepth` it should be good.
