### ISSUE TITLE
Error/Warning about this module using manual linking

### ISSUE THREAD

**Issue by JeremyBradshaw7** [getsentry/sentry-react-native#714]
OS:
- [ ]  Windows
- [-]  MacOS
- [ ]  Linux

_Platform:_
- [-]  iOS
- [-]  Android

SDK:
- [-]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.4

Init Code:

```
Sentry.init({
    dsn: 'https://fae343888...9c3cb856@sentry.io/1240637',
    environment: Config.BUILD
});
```

---
I have following issue:

Upgraded to latest everything but am getting this error/warning on building:

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @sentry/react-native (to unlink run: "react-native unlink @sentry/react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Steps to reproduce:**
Run standard installation instructions against new RN project.

**Actual result:**
Error shown as above, though project actually builds fine.

**Expected result:**
Auto-linking to take care of itself??

**Comment by anka-213** [comment]
I think you are just supposed to unlink manually as the instructions says. As far as I know, that is the standard procedure when upgrading from below 0.60. After that the auto-linking can handle everything by itself.

**Comment by JeremyBradshaw7** [comment]
I did unlink, it still shows the error.

**Comment by HazAT** [comment]
I am not sure how to help, RN can be very tricky to upgrade.
If I create a clean project now everything works just fine.

**Comment by DavidAPears** [comment]
Also have this 

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - @sentry/react-native (to unlink run: "react-native unlink @sentry/react-native")
 ```

Unlinking (as instructed) does nothing, error reoccurs.
