### ISSUE TITLE
Argument 0 of RNSentry.startWithDsnString must not be null

### ISSUE THREAD

**Issue by dmathewwws** [getsentry/sentry-react-native#717]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.0

---
I have following issue:

Upgraded to RN 0.61 and get the following error and sentry events are not sent.

```Argument 0 (NSString) of RNSentry.startWithDsnString must not be null```

my Sentry init code looks like  this:

Sentry.init({
  dsn: 'mycode'
});

**Steps to reproduce:**
- Run app to get error

**Actual result:**
![Simulator Screen Shot - iPhone 8 - 2019-11-10 at 15 48 58](https://user-images.githubusercontent.com/2018931/68552955-c9fbec00-03d1-11ea-8610-1006005b9c75.png)

**Expected result:**
- no error

**Comment by birgernass** [comment]
I had this issue, but in my case it was just a typo. dns instead of dsn.

**Comment by HazAT** [comment]
^ this
Also please consider upgrading to `1.3.0`.
If this is still an issue, feel free to post here again.
