### ISSUE TITLE
'React/RCTBridge.h' file not found 

### ISSUE THREAD

**Issue by adithyareddyZ** [getsentry/sentry-react-native#719]
OS:
- [ ]  Windows
- [*]  MacOS
- [ ]  Linux

_Platform:_
- [ *]  iOS
- [ ]  Android

SDK:
- [ ]  `@sentry/react-native`
- [ *]  `react-native-sentry`

`react-native` version: 0.61.1

<img width="1437" alt="Screenshot 2019-11-19 at 3 21 00 PM" src="https://user-images.githubusercontent.com/49646457/69136400-ca3a6c80-0ae0-11ea-80fe-c1d0c944f8d2.png">

**Comment by HazAT** [comment]
This is a react-native linking issue, see: https://github.com/getsentry/sentry-react-native/issues/395
