### ISSUE TITLE
ExpoKit, native errors

### ISSUE THREAD

**Issue by dreamchasersuon** [getsentry/sentry-react-native#720]
OS:
Ubuntu 18.04.3 LTS 

_Platform:_
Android

SDK:
`@sentry/react-native`

`react-native` version: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Hi guys, I have a problem with ExpoKit and Sentry setup. Found out that not only me stuck with this kind of issue. Hope that someone can point me. The problem is Sentry don't handle **Native Errors**, while **JS Errors** handling works fine.

**Steps to reproduce:**
1. Install minimal expo project: `mkdir expokit-sentry && cd expokit-sentry && expo init`;
2. I choose minimal setup to got fast results: _expo project with navigation_;
3. Ejecting to ExpoKit: `expo eject`;
4. Install Sentry: `yarn add @sentry/react-native` or `npm i --save @sentry/react-native`;
5. Link native dependencies: `react-native link @sentry/react-native`;
6. Run packager: `expo start`;
7. Make build: open Android Studio, then -> Sync Project, then -> Build APK;
8. Install on device and try to run _Fire native error_ and _Fire JS error_ links.

I made a sample project [here](https://github.com/dreamchasersuon/expokit-sentry). 

**Actual result:**
- JS errors handling work fine while Native handling not working at all.

**Expected result:**
- Native errors handling must work with ExpoKit.

**Comment by GleidsonDaniel** [comment]
Same here... Any solution?

**Comment by dreamchasersuon** [comment]
> Same here... Any solution?

Unfortunately, not...

**Comment by GleidsonDaniel** [comment]
> > Same here... Any solution?
> 
> Unfortunately, not...

I was able to make it work by combining with another library: `react-native-exception-handler`

My code:
```
import * as Sentry from '@sentry/react-native';
import {setNativeExceptionHandler} from 'react-native-exception-handler';

export default function sentryInit() {
  if (!__DEV__) {
    Sentry.init({
      dsn: '...',
    });

    setNativeExceptionHandler(exceptionString => {
      Sentry.captureException(exceptionString);
    });
  }
}
```

**Comment by HazAT** [comment]
I am closing this issue in order for that to work, Expo would need to embed our native SDKs in their package. Not sure if this is ever going to happen.
If you want to that you need to eject your project or raise an issue in their tracker.
Cheers

**Comment by GleidsonDaniel** [comment]
ExpoKit is a ejected project...

**Comment by HazAT** [comment]
I am not sure what ExpoKit is doing under the hood but if `@sentry/react-native` is correctly linked in a simple `react-native` project, native tracking works just fine.
So either it's not just an ejected project or linking did fail.
Because if you just start with `react-native init AwesomeProject` then there is no isse.
