### ISSUE TITLE
httpProxy support for RN

### ISSUE THREAD

**Issue by vasilich6107** [getsentry/sentry-react-native#725]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.6.4

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  transportOptions: {
 
        httpProxy: 'http://bridge...'
    },
});
```

---
I have following issue:

`httpProxy` option is not supported.
Is there any estimates to support `httpProxy` in for `react-native`?

**Comment by marandaneto** [comment]
the RN SDK only forward the events to the Native SDKs, so you could technically set the proxy in the Native SDKs.
https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/

Android offers proxy configuration but iOS not, @philipphofmann to confirm

**Comment by marandaneto** [comment]
iOS should be possible via https://github.com/getsentry/sentry-cocoa/blob/40bd7cae3ffb2440e99d610f0a564238f094e721/Sources/Sentry/Public/SentryOptions.h#L243

@brustolin do you know if we can set a proxy using NSURLSessionDelegate?

**Comment by marandaneto** [comment]
we could add the fields to the RN options and sync down to the Native SDKs.

**Comment by brustolin** [comment]
> @brustolin do you know if we can set a proxy using NSURLSessionDelegate?

With `NSURLSessionDelegate` is not possible to configure proxy,
we would have to configure the session using NSURLSessionConfiguration. 

Right now iOS doesn't offer a way to do this.

If we are going to add this option (and I think we should), I suggest adding a callback to let the user configure the session the way it fits them, instead of adding individual options to the SDK.

**Comment by philipphofmann** [comment]
Can you please share the motivation for using a proxy on a mobile app, @vasilich6107?

**Comment by vasilich6107** [comment]
Hi. I do not work on that project so idk anymore)

**Comment by philipphofmann** [comment]
Thanks for the update, @vasilich6107, but do you recall the use case? Just for us to know.
