### ISSUE TITLE
update examples to latest version of this package

### ISSUE THREAD

**Issue by sibelius** [getsentry/sentry-react-native#726]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [x]  `react-native-sentry`

`react-native` version: 0.61.0

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Description goes here ...

How to properly configure sentry on native part?

example is using the old `react-native-sentry` (https://github.com/getsentry/examples/blob/master/react-native/AwesomeProject/package.json#L13)

it should use `@sentry/react-native` instead

**Comment by HazAT** [comment]
Thanks for reminding us, we will soon update our examples to use the latest version.
It's hard to keep up with how fast things are moving in react-native :)
