### ISSUE TITLE
'Sentry/SentryOptions.h' file not found

### ISSUE THREAD

**Issue by hanwenbo** [getsentry/sentry-react-native#728]
OS:
MacOS

_Platform:_
iOS

SDK:
 `@sentry/react-native`

`react-native` version: 0.57.5

    "@sentry/react-native": "^1.2.0",

XCode Error Info
'Sentry/SentryOptions.h' file not found

![image](https://user-images.githubusercontent.com/5869741/70883698-cda51300-200e-11ea-97dd-ac8964288f13.png)

But it does not affect the use

**Comment by 77xi** [comment]
pod install

**Comment by HazAT** [comment]
This must be a linking issue, make sure you run `pod install`.
Worst case remove and readd `@sentry/react-native`
