### ISSUE TITLE
A problem occurred configuring project ':@sentry_react-native' SDK location not found

### ISSUE THREAD

**Issue by akritskiy** [getsentry/sentry-react-native#729]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.59.9

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
})
```

---
I have following issue: I can't start my app on android due to a Sentry exception.

**Steps to reproduce:**

I try to run the app w/ react-native run-android

Build fails.
> A problem occurred configuring project ':@sentry_react-native'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

I go into the android folder and create a local.properties file and paste this in:
sdk.dir=C:/Users/my_name/Library/Android/sdk
This is the location of my Android SDK.

I try again to run the app w/ react-native run-android
> A problem occurred configuring project ':@sentry_react-native'.
> The SDK directory '/Users/my_name/project_path/android/C:/Users/my_name/Library/Android/sdk' does not exist.

**Result:**
The SDK path I provided in local.properties gets concatenated to my project root path, so the app can't find the android SDK and the build fails.

**Expected result:**
App should run since I provided the android SDK path.

**Comment by HazAT** [comment]
Excuse the maybe stupid question, but are you sure this error has to do with our SDK?
What error do you get with running your app without adding our SDK?

**Comment by akritskiy** [comment]
That's a fair question, actually. I'll unlink it and check.

**Comment by akritskiy** [comment]
Okay, I unlinked the SDK and got a similar error, so yeah, good call. Not a stupid question at all.

You can close this. If you have any suggestions, they're welcome. Otherwise, I'll be on my way. :)
