### ISSUE TITLE
Not working on Android 9

### ISSUE THREAD

**Issue by deepak-singh** [getsentry/sentry-react-native#730]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.4

Init Code: 
```
Sentry.init({
  dsn: 'http://self-hosted-sentry',
});
```

---
I have following issue:
No events are caught on ```Android 9``` in a ```release.apk```

Description goes here:
After upgrading ```sentry``` and ```react-native``` to latest in all our projects, we have stopped receiving events/logs in our self hosted sentry portal for all ```Android 9``` phones.

To investigate it further, we created a side project with ```react-native``` and just installed sentry in it. package.json, for dependencies, looks like this:

```
"dependencies": {
    "@sentry/react-native": "^1.2.1",
    "react": "16.9.0",
    "react-native": "0.61.4"
  }
```
 
Initialised sentry in ```App.js``` as in docs and a simple capture message ```Sentry.captureMessage("Hello Sentry!");``` is being sent.
This works fine in ```debug.apk``` on an emulator and also in a connected device with ```Android 9``` but if a ```release.apk``` is made, it doesn't send any events in ```Android 9``` devices.

**Steps to reproduce:**
- Create an app using react-native and install sentry 
- Setup sentry project and add the ```init``` and ```captureMessage``` as in docs, in ```App.js```
- run ```react-native run-android``` and test in a connected device with ```Android 9``` - works fine
- run ```react-native run-android --variant=release```, install the ```release.apk``` - No logs are received.

**Actual result:**
- No Logs/Events are received in Sentry for a ```release.apk```

**Expected result:**
- Logs should be received in Sentry for a ```release.apk```

Do let me know if I can provide you with any other information to debug this.

Thank you!

**Comment by deepak-singh** [comment]
Any update on this?

**Comment by HazAT** [comment]
Hey, I can't reproduce this, tried it again today and it works just fine.

**Comment by wodCZ** [comment]
Android 9 disables HTTP requests by default. See [this answer](https://stackoverflow.com/a/50834600/2078771) for how to allow http requests to your self-hosted Sentry instance. Only use the domain without the protocol in the security config xml.


Create file res/xml/network_security_config.xml -
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">self-hosted-sentry</domain>
    </domain-config>
</network-security-config>
```
AndroidManifest.xml -
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:networkSecurityConfig="@xml/network_security_config"
        ...>
        ...
    </application>
</manifest>
```

**Comment by HazAT** [comment]
Please update to `1.3.0` our SDK works just fine.
Also thank you @wodCZ for this hint.
