### ISSUE TITLE
Inconsistent timestamps for breadcrumbs on Android

### ISSUE THREAD

**Issue by lucassus** [getsentry/sentry-react-native#734]
`react-native` version: 59.10
`@sentry/react-native` version: 1.2.1

Init Code:

```javascript
const BLACKLISTED_HTTP_BREADCRUMB_ENDPOINTS = [
  "https://itunes.apple.com",
  "https://api.segment.io",
  "https://play.google.com"
];

export function init() {
  Sentry.init({
    dsn: SENTRY_DSN,
    environment: __DEV__ ? "development" : "production",
    release: DeviceInfo.getVersion(),
    beforeBreadcrumb
  });
}

const isBlacklisted = url =>
  some(
    BLACKLISTED_HTTP_BREADCRUMB_ENDPOINTS.map(endpoint =>
      url.startsWith(endpoint)
    )
  );

export const beforeBreadcrumb = breadcrumb => {
  if (breadcrumb.category === "xhr" && breadcrumb.type === "http") {
    const url = get(breadcrumb, "data.url");

    if (isBlacklisted(url)) {
      return null;
    }
  }

  return breadcrumb;
};

export function addNavigationBreadcrumb(componentName) {
  Sentry.addBreadcrumb({
    category: "navigation",
    level: Sentry.Severity.Info,
    type: "default",
    message: `Screen ${componentName} appear`,
    timestamp: Date.now(), // TODO: For some reason this is ignored
    data: {
      timestamp: new Date().toUTCString()
    }
  });
}
```

---
I have following issue:

I noticed that on Android all breadcrumbs have almost the same timestamps (the difference is on the milliseconds level). 

![Screenshot 2020-01-03 at 10 59 11](https://user-images.githubusercontent.com/41239/71717414-577b1b80-2e18-11ea-885e-ab77daf8ee27.png)

On the other hand breadcrumbs on iOS are fine:

![Screenshot 2020-01-03 at 11 16 25](https://user-images.githubusercontent.com/41239/71718140-8d210400-2e1a-11ea-832a-88417819ceaf.png)

**Steps to reproduce:**

- Initialize Sentry with `beforeBreadcrumb` callback
- ...and use custom breadcrumbs

**Comment by HazAT** [comment]
Thanks for reporting, will investigate!

**Comment by viernullvier** [comment]
I'm actually seeing the same behaviour **without** having a `beforeBreadcrumb` callback. I've tried to set the `timestamp` for each breadcrumb manually, but this also didn't work.

`react-native`: 0.61.5
`@sentry/react-native`: 1.2.1
Platform: Android
Runtime: Hermes
