### ISSUE TITLE
React Native: Show stack trace from before message is added to queue

### ISSUE THREAD

**Issue by ramirezd42** [getsentry/sentry-react-native#738]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.0.0

Init Code:

```
  Sentry.init({
    dsn: Config.SENTRY_DSN
  });

```

---

In our project when capturing an exception in code that is executed in a callback after the RN bridge, the stack trace only goes as far back as when the message was pulled off the queue. The simplest example would be the response handler for a fetch or xhr request.

In the stacktrace below im using axios to make an API request, ideally I’d like to be able to see the portion of the stack trace from before the message was actually placed on the queue (i.e. the code that lead up to the api request being made).

<img width="829" alt="Screen Shot 2020-01-08 at 6 04 19 PM" src="https://user-images.githubusercontent.com/2200166/72023670-6cedac80-3241-11ea-916f-37747ed5eb13.png">

I’m wondering if this is an issue with my setup or a limitation of the react-native SDK. Is there any other way of manually capturing that stacktrace perhaps?

**Comment by marandaneto** [comment]
it's a limitation of the RN/JS Engine, Sentry captures the available stack trace and its frames
