### ISSUE TITLE
Clarification: How can I know the user feedback for a particular user of my app

### ISSUE THREAD

**Issue by nihp** [getsentry/sentry-react-native#744]
1. I am using sentry to know the bug reports. I need to know about the user feedback for my mobile app.

For eg.) If a crash or user needs to tell feedback for my app, How can I show the in-app feedback screen inside my app?

2. If the usr successfully send a crash report where I can able to see the users feedback

**Comment by HazAT** [comment]
Please follow this, we will most likely add support for this by providing an API but not an UI.
https://github.com/getsentry/sentry-react-native/issues/500
