### ISSUE TITLE
How can I open user feedback popup in my simulator after throws an exception

### ISSUE THREAD

**Issue by nihp** [getsentry/sentry-react-native#745]
OS:
- [ ]  MacOS

_Platform:_
- [ ]  iOS
- [ ]  Android

SDK:
- [ ]  `@sentry/react-native`

`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:
  I tried to open the showReportDialog to send the user feedback. But it fails to open the popup window in my simulator.

**Actual result:**
    It throws an error as "undefined is not a function (near '..Sentry.showReportDialog..')

How the report dialog will opens in my simulator. Can anyone have any example for this in react-native.

I have added the following in my App.js file

```
import * as Sentry from "@sentry/react-native";

Sentry.init({
    dsn: 'DSN',
    beforeSend(event) {
            return event;
    },
 });
var eventId = Sentry.captureMessage('User Feedback', function() {});
Sentry.showReportDialog({
    eventId: eventId,
    title: 'Policies and Procedures Feedback',
        subtitle:
       'Please enter your information to submit feedback for the Policies and Procedures.',
    subtitle2: '',
    labelComments: 'Feedback',
    labelSubmit: 'Submit Feedback',
    // user: { name: this.user.name, email: this.user.email },
});


Sentry.setTag("myTag", "tag-value");
Sentry.setExtra("myExtra", "extra-value");
Sentry.addBreadcrumb({ message: "test" });
//Sentry.setUser({ id: AppSettings.deviceLogin })

//Sentry.nativeCrash();
Sentry.captureMessage("Hello Sentry!");
Sentry.showReportDialog();


```

**Comment by wodCZ** [comment]
I believe the report dialog is not supported in react-native.

**Comment by HazAT** [comment]
Please follow this, we will most likely add support for this by providing an API but not a UI.
https://github.com/getsentry/sentry-react-native/issues/500
