### ISSUE TITLE
Migrating from react-native-sentry to  @sentry/react-native

### ISSUE THREAD

**Issue by shubhamdeol** [getsentry/sentry-react-native#747]
OS:
- [ ]  MacOS

_Platform:_
- [ ]  Android

SDK:
- [ ]  `@sentry/react-native`
`react-native` version: 0.61

I am getting the following error after successfully installing the  @sentry/react-native

```
D8: Program type already present: io.sentry.MapUtil
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Program type already present: io.sentry.MapUtil
```

**Comment by HazAT** [comment]
Hey, please make sure to clean `node_modules` and fix all the imports.
This can only happen if it's included the SDK twice.
