### ISSUE TITLE
Android ignores "enableNativeCrashHandling" flag

### ISSUE THREAD

**Issue by crazyjooe** [getsentry/sentry-react-native#748]
OS:
- [ ]  Windows
- [X ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ X]  Android

SDK:
- [X ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.2

Init Code:

```
Sentry.init({
  enableNative: true,
  enableNativeCrashHandling: false,
  enableNativeNagger: false,
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

We want to use Sentry to report only React Native crashes, as we are already using another tool for Native ones, and we want to keep them separated. 

`enableNativeCrashHandling` key is the one that should control this behavior. It's handled properly in iOS (can be checked by [search](https://github.com/getsentry/sentry-react-native/search?q=enableNativeCrashHandling&unscoped_q=enableNativeCrashHandling), but it seems that it's not handled at all on Android side. After integrating Sentry and making the first release, we started getting Android crash reports as well. This seems like a pretty critical bug at this point, so we have to disable Android integration until it's fixed.

Description goes here ...

**Steps to reproduce:**
- Integrate Sentry and set `enableNative` to `true` and `enableNativeCrashHandling` to `false`. Get Android to crash on native side.

**Actual result:**
- Android native crash is reported to Sentry, even though it's configured to not handle native crashes.

**Expected result:**
- Native crashes are not reported.

**Comment by HazAT** [comment]
Thanks for reporting, we will check and fix it with this PR: https://github.com/getsentry/sentry-react-native/pull/749
