### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by indapublic** [getsentry/sentry-react-native#750]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 1.2.1

Init Code:

```
Sentry.init({
	dsn: __DEV__ ? Env.DEV_SENTRY_ENDPOINT : Env.SENTRY_ENDPOINT,
	environment: "production",
	loglevel: LogLevel.Debug,
	attachStacktrace: true,
	// debug: true,
	// attachStacktrace: false
	// deactivateStacktraceMerging
})
```

---
I have following issue:

When error will be thrown on application (in Simulator or Device) I will see "Source code was not found" error in Sentry panel.
I see that script "Upload Debug Symbols to Sentry" was runned on production build 

**Steps to reproduce:**
- `throw new Error("Test-1")`

**Actual result:**
- 
```
There was 1 error encountered while processing this event
Source code was not found Expand
```

![image](https://user-images.githubusercontent.com/856260/73234561-5ef2d200-41d6-11ea-8280-5f22def5ec5a.png)

**Expected result:**
- No errors in Sentry panel

**Comment by LcsGrz** [comment]
Same issue :c

**Comment by indapublic** [comment]
@LcsGrz If app in release mode that you uploaded Sentry debug symbols during build.
My case about release app

**Comment by wodCZ** [comment]
Can you see the artifacts in the project releases panel? If you can see them, check that you can download them. In my case I had issue with storage on self-hosted Sentry instance, and the debug artifacts were corrupted, which resulted in the same message you're getting.

![image](https://user-images.githubusercontent.com/1174421/74160077-2236ca00-4c1d-11ea-9f9d-85821c18d658.png)

**Comment by indapublic** [comment]
@wodCZ Thanks for response! Artifacts are visible and downloadable. But I see several artifacts with same names. Can be a reason?

![image](https://user-images.githubusercontent.com/856260/74201523-c4a28c00-4cb5-11ea-89d5-13291e39a4be.png)

**Comment by wodCZ** [comment]
@indapublic What's the message when you click expand next to the error "Source code was not found"? Possibly there is a path, something like `app://index.android.bundle` IIRC - it should match one of your artifact's name.

If you're running self-hosted sentry instance, there is an internal Sentry project. There could be some error logged, which could

**Comment by indapublic** [comment]
It's not self-hosted sentry instance.

![image](https://user-images.githubusercontent.com/856260/74289279-5a075400-4d7a-11ea-86c7-dabfd2418859.png)

```
/private/var/containers/Bundle/Application/55A96EBB-7D58-444D-9964-1F04DF1CCFFF/myapp.app/main.jsbundle
```

`main.jsbundle` is presented in artifacts list

**Comment by lobsterkatie** [comment]
@indapublic - having multiple release artifacts with the same name is fine as long as the distribution value is different - files are matched on the combination of name and `dist` value.

That said, it seems like the `RewriteFrames` integration isn't running for you (which would transform that URL into `app:///main.jsbundle`, allowing it to match `~/main.jsbundle`, provided the `dist` values are also a match). Can you share a link to the issue in question?

**Comment by indapublic** [comment]
Hi @lobsterkatie . Thanks for response. [Example](https://sentry.io/organizations/macroactiveio/issues/1511462039)

**Comment by lobsterkatie** [comment]
That event was captured using `1.0.6`.  Back when `1.x` was new I do remember someone having a similar issue, but it hasn't come up since, so I suspect it may have been fixed. Can you please try updating your SDK? Current is `1.3.1`.

**Comment by indapublic** [comment]
Thanks! I will check. Can I see that information (SDK version) in Sentry issues? I have many applications with different versions of SDK integrated, so it can be very helpful

**Comment by lobsterkatie** [comment]
Yup - all the way at the bottom:

![image](https://user-images.githubusercontent.com/14812505/74515715-6bce3000-4f0f-11ea-84b7-a58a29db7b78.png)

We actually have a system which can show a warning if your SDK is out of date, but it turns out the RN SDK isn't included yet. Here's [an issue](https://github.com/getsentry/sentry-react-native/issues/765) tracking getting that added in.

**Comment by ptgamr** [comment]
I've got two errors when an exception appear in Sentry:

![2020-03-02_15:47:20](https://user-images.githubusercontent.com/1619740/75641480-45451e80-5c9d-11ea-8ad2-12c28d62008b.png)

The source map is successfully uploaded for the release and I can see it:

![2020-03-02_15:46:58](https://user-images.githubusercontent.com/1619740/75641504-59891b80-5c9d-11ea-9c2c-3b5dffb4f1f9.png)

And the linking between the source code & the release works: (as you can see there is hover text)
![2020-03-02_15:49:34](https://user-images.githubusercontent.com/1619740/75641543-77568080-5c9d-11ea-8c66-b8110ecbed5c.png)

Sentry server: 8.13.0
@sentry/react-native: 1.3.2
react-native: 0.61.4

**Comment by HazAT** [comment]
@ptgamr Sorry we don't support debugging on-premise installations, there can be so many things configured the wrong way that it's hard to help.
Also, your Sentry installation is really old and will not work with Hermes.

**Comment by petrleocompel** [comment]
Is there actual need to have `dist` property set ? 

`sentry-expo` package and even [expo docs](https://docs.expo.io/versions/latest/guides/using-sentry/) says nothing about that. Even postPublish hook doesnt set it. So my realease has no `dist`.

![image](https://user-images.githubusercontent.com/9423543/77534190-7d084600-6e98-11ea-818e-10bcff3a6e04.png)

But event sent to sentry contains `dist`

![image](https://user-images.githubusercontent.com/9423543/77534385-d3758480-6e98-11ea-9b01-870e1243cdc8.png)

Even with recognized release and corrected `RewriteFrame` (`app:///`) my code is not linked to uploaded source.
  
But [sentry docs](https://docs.sentry.io/platforms/react-native/#setting-release--dist) has `dist` set.

:thinking: Interesting thing is in my code (`Sentry.init`) is `dist` set to `release` but as you can tell in screenshot  is `217`.

-----

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`


SDK version: 1.3.3
`react-native` version: 0.59.8

Are you using Expo?
- [x]  Yes
- [ ]  No

Are you using sentry.io or on-premise?
- [ ]  sentry.io (SaaS)
- [x]  on-premise


Configuration:

```
    Sentry.init({
        dsn: 'https://*****',
        dist: 'release',
        release: Constants.manifest.revisionId,
    });
```

**Comment by lobsterkatie** [comment]
@petrleocompel Are you using the gradle plugin, or are you uploading source maps manually?

**Comment by petrleocompel** [comment]
@lobsterkatie 
I'm using [sentry-expo/upload-sourcemap](https://github.com/expo/sentry-expo/blob/master/upload-sourcemaps.js) so in core it's `sentry-cli`.

Also I pointed that in my comment `Sourcemap upload command:` (which is real command executed by that script) :blush:

**Comment by petrleocompel** [comment]
Mystery kinda solved. 
In my case i needed to add to upload sourcemap `dist` atritbute. And set it in aplication.
`Sentry.setDist(dist)`. 

I would love to know meaing of `dist` attr. 
Could somebody explain or point me to docs about attr `dist`?

I did not set it because `sentry-expo/upload-sourcemap` does not sett it. :confused:

**Comment by ghasemikasra39** [comment]
In my case, I can see that the artifacts are missing:
![Screenshot 2021-09-14 at 11 08 29](https://user-images.githubusercontent.com/24314029/133230113-afbcc2c8-1754-4a74-8fd4-bd6aee19de85.png)
![Screenshot 2021-09-14 at 11 07 21](https://user-images.githubusercontent.com/24314029/133230131-2dd2c593-9566-4e51-82eb-f9878191e22d.png)
![Screenshot 2021-09-14 at 11 05 46](https://user-images.githubusercontent.com/24314029/133230138-51575c44-9fb8-4cca-84f3-dafa14cf0793.png)

I can see that the `dist` and `release` are set correctly in my issues for both Android and ios. Why are the artifacts are missing?

I am using `@sentry/react-native "^3.0.3"` **without** expo on `sentry.io (SaaS)`  on both Android and ios, I am **not** using  custom Release and Distribution, and I am **not**  manually uploading the bundle and source maps.

```javascript
Sentry.init({
  dsn: global.sentryDsn,
  environment: getEnv(),
  normalizeDepth: 10,
});
```

**Comment by jennmueng** [comment]
@ghasemikasra39 Are the custom source map build scripts being disabled somehow?

**Comment by ghasemikasra39** [comment]
> @ghasemikasra39 Are the custom source map build scripts being disabled somehow?

Yes, I removed them. And I upload the artifacts finally. 

I am a bit confused. First of all, this URL (I pointed in the first image) changes based on which file the error is located at, which is weird. Apart from that I had a few questions:

- Q1: Do I **have to** create a build for **TestFlight** for the Source Mapping to work?
- Q2: Can I just install the app on my iPhone via xCode and then manually upload the source maps to Sentry? (this is what I did so far) I mean, does the source mapping works this way?
- Q3: Why I don't see the dist number in **parentheses** in Sentry? (I pointed in the second image) - but when I click on it, I see the numbers in ovals (I pointed to in the third image)
- Q4: Why am I getting those options after the bundle name, i.e. what are these 
`?dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true` that come after `app:///HotNotesTab.bundle`   ?

![Screenshot 2021-09-15 at 17 04 26](https://user-images.githubusercontent.com/24314029/133459776-36b4e3c5-860d-4944-aba1-eb2f1bf72f97.png)


![Screenshot 2021-09-15 at 16 55 36](https://user-images.githubusercontent.com/24314029/133457704-cca6de66-edc5-45a8-853c-9dfd2953b11e.png)

![Screenshot 2021-09-15 at 16 59 34](https://user-images.githubusercontent.com/24314029/133458248-dfd69cf1-3366-47cd-93e1-4f1b785b69ef.png)

I have tested any names for bundles, but no success so far. this is how I am manually uploading the source maps:

```bash
./node_modules/@sentry/cli/bin/sentry-cli releases \
    --project 'my-gmbh' \
    --org 'my-gmbh' \
    files '1.0' \
    upload-sourcemaps \
    --dist 17  \
    --strip-prefix '/Users/kasra/Documents/my-app' \
    --rewrite './ios/my_app/main.jsbundle' './ios/my_app/main.jsbundle.map' \
    --log-level='debug'
```

And this is how I create the bundles:
```bash
npx react-native bundle 
--dev false 
--entry-file 'index.js' 
--bundle-output './ios/my_app/main.jsbundle' 
--sourcemap-output './ios/my_app/main.jsbundle.map' 
--platform ios 
--assets-dest='./ios'

```

**Comment by jennmueng** [comment]
@ghasemikasra39 
1. Sourcemapping on Sentry only works on production builds, in development builds the stack trace should come in unminified. 
2. You just need to run a release builds to get source maps to work, but if you disabled the sourcemap upload script you would need to manually upload the sourcemaps like you're doing right now.
3. In the second image, you're pointing to the release, which can have multiple `dist` values. In the other rows that have the dist in parenthesis, something added the dist values to the release name.
4. The options after the bundle name are because you're running a development build, those are the options sent to the React Native packager.

**Comment by ghasemikasra39** [comment]
> @ghasemikasra39
> 
> 1. Sourcemapping on Sentry only works on production builds, in development builds the stack trace should come in unminified.
> 2. You just need to run a release builds to get source maps to work, but if you disabled the sourcemap upload script you would need to manually upload the sourcemaps like you're doing right now.
> 3. In the second image, you're pointing to the release, which can have multiple `dist` values. In the other rows that have the dist in parenthesis, something added the dist values to the release name.
> 4. The options after the bundle name are because you're running a development build, those are the options sent to the React Native packager.

Creating a release build for TestFlight, everything starts to work. Thank you for your help.

**Comment by bruno-garcia** [comment]
We'll take some of the learnings from here and add to the troubleshooting guide in the docs.
This issue though is resolved and I'll lock it to avoid new threads starting.
