### ISSUE TITLE
Sentry.init() throws an error on init

### ISSUE THREAD

**Issue by georgiik-welldone** [getsentry/sentry-react-native#757]
I'm getting an error on Sentry.init() call.
<img width="490" alt="Screenshot 2020-02-09 at 17 19 10" src="https://user-images.githubusercontent.com/20322794/74105756-dd4d5d80-4b60-11ea-8691-5e20a9ec3576.png">

`OS`: MacOS
`react-native` version: 0.61.5
`@sentry/react-native` version: 1.2.2 (1.2.1, 1.2.0, 1.1.0)

**Comment by HazAT** [comment]
How does your init call look like?

**Comment by georgiik-welldone** [comment]
@HazAT 

```
Sentry.init({
    dsn: `https://${HASH}@sentry.io/${PROJECT_ID}`,
});
```

**Comment by HazAT** [comment]
To be honest, I have no idea what's causing this (looking at your config) but this PR will probably fix it.
We will ship it this week. 

https://github.com/getsentry/sentry-react-native/pull/749

**Comment by georgiik-welldone** [comment]
Thanks, will check it out by the end of this week
