### ISSUE TITLE
Use of "@sentry/integrations" causes unnecessary files being added to the bundle

### ISSUE THREAD

**Issue by grabbou** [getsentry/sentry-react-native#759]
Hey,

First of all, apologies if this is not an issue or not a suitable place to raise it. In this case, feel free to close it and let me know how to follow up.

I am debugging the end bundle of an application that uses Sentry and React Native integration and I have noticed that there are [Angular](https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/angular.ts), [Ember](https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/ember.ts) and [Vue](https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/vue.ts) integrations included in the resulting bundle.

After digging deeper, it looks like they are present in the [entry file of `@sentry/integrations`](https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/index.ts) that is loaded when [we require `RewriteFrames`](https://github.com/getsentry/sentry-react-native/blob/master/src/js/sdk.ts#L7).

Wouldn't it be more suitable to move that function to `@sentry/utils`? I don't find this particularly disturbing, but just figured I'd share this here as it was really surprising to see other frameworks being referenced in the code and find out where they're coming from.

**Comment by HazAT** [comment]
Thanks for reporting, this is definitely not intended.
hmmm that seems odd, we can't move those integrations there but I thought the bundler removes files that are not referenced in the code (treeshaking).
I wonder if it's because of how we import `@sentry/integrations` when I find some time I will try to repro and fix this, if you have any hints in the meantime, please let us know.

**Comment by marandaneto** [comment]
React Native/Metro does not support tree shaking, not sure how we can tackle this.
See https://github.com/facebook/metro/issues/227#issuecomment-583358386

@AbhiPrasad @bruno-garcia @jennmueng ideas?

**Comment by marandaneto** [comment]
@AbhiPrasad opened a PR that may help us out with that, https://github.com/getsentry/sentry-javascript/pull/4434

**Comment by marandaneto** [comment]
There were a few improvements related to bundle size and integrations on the JS SDK, the RN SDK got it for free, please upgrade to the latest version (4.x) and let us know if that helped, thanks.
