### ISSUE TITLE
Source resolution for Android with Hermes and split APKs on v1.3.0

### ISSUE THREAD

**Issue by denissb** [getsentry/sentry-react-native#762]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.0
`react-native` version: 0.61.5

Init Code:
```
  Sentry.init({
    dsn: config.DSN,
    release: `native-app@${VersionNumber.appVersion}`,
    environment: __DEV__ ? 'dev' : 'prod',
  });
```
---
**I have following issue:**
After upgrading to `@sentry/react-native` version 1.3.0 which added support for the hermes engine (and upgraded the android sentry sdk to `io.sentry:sentry-android:2.0.0-rc04`) I have an issue with mapping the correct version to the source bundle. 

After some investigation I found out that the release version for android is now produced differently by using `"${variant.getApplicationId()}@${variant.getVersionName()}+${versionCode}"` instead of `"${variant.getApplicationId()}-${variant.getVersionName()}"` in sentry.gradle
which actually produces several releases for the same app version in the sentry dashboard. So I think the way versionCodes and distribution numbers are being handled needs to be really generic or documented somewhere.

Output of gradle for sentry upload:
```
> Task :app:bundleProdReleaseJsAndAssets_SentryUpload
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release test.app.app@1.0.19412+4213716 distribution 4213716
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
Uploading sourcemaps for release test.app.app@1.0.19412+4213716 distribution 2116564
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
Uploading sourcemaps for release test.app.app@1.0.19412+4213716 distribution 1067988
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
Uploading sourcemaps for release test.app.app@1.0.19412+4213716 distribution 3165140
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map
```
**Example**
Here you can see two different versionCodes created for the same release (as you would expect with an apk split), but one of them has no artefacts.  
![Untitled](https://user-images.githubusercontent.com/2261330/74363794-97480200-4dcb-11ea-87d5-0be29f922aed.png)
![Untitled](https://user-images.githubusercontent.com/2261330/74365473-78973a80-4dce-11ea-98b8-b9808439792b.png)

**Steps to reproduce:**
- Updgrade to 1.3.0
- Enable hermes in your builds
-  Enable apk splits in `app/build.gradle` like:
```
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
```

**Actual result:**
The errors are logged, but the code path is not shown:
![Untitled](https://user-images.githubusercontent.com/2261330/74364230-703e0000-4dcc-11ea-9b53-0261451ec992.png)

**Expected result:**
Source map is located and mapped out correctly, and the error shows the failing code block

**Comment by valeriashpiner** [comment]
@denissb I just opened almost the same issue! Is iOS working for you?

**Comment by denissb** [comment]
@valeriashpiner I saw it, and yes, iOS does seem to work for me, but the release name offcourse does not have a version code, see:
![Untitled](https://user-images.githubusercontent.com/2261330/74368209-7683aa80-4dd3-11ea-82e2-b8b9a93bb15a.png)

**Comment by valeriashpiner** [comment]
@denissb thank you! did you push iOS source maps as usual? 
for example, just to run ios build in release mode?

**Comment by denissb** [comment]
@valeriashpiner Thats correct. Check sentry panel if you actually have the source maps uploaded for the release you are checking. If the bundle is there but sentry still can't see it than are issues might be similar.

**Comment by valeriashpiner** [comment]
@denissb I fixed iOS by uploading source maps manually 😞 
It didn't upload for me in the usual way (release mode through XCode).
For android, I also don't see the source maps even after I upload it manually.

**Comment by HazAT** [comment]
@denissb somehow your event is missing the `release` (there is no tag)
Can you try not to set the `release` in the options

**Comment by HazAT** [comment]
For ios we fixed the issue, patch release fixing this should come today.
@denissb I am a bit confused why you have more releases through ABI splitting
the sentry-cli output says only `test.app.app@1.0.19412+4213716` the rest is depending on the `dist`

I am not saying that there couldn't be a bug somewhere, I just trying to fully understand what is not working.

**Comment by denissb** [comment]
@HazAT 
After removing the release version from init (which we always had)
I get the following releases in the Sentry dashboard:
<img width="1286" alt="Screenshot 2020-02-13 at 11 54 33" src="https://user-images.githubusercontent.com/2261330/74427678-d7ed5d00-4e57-11ea-90f4-e9304901dc5d.png">
The 1.0.19430 (19430) has no artefacts in it.

Please not I am doing the following in my build.gradle to create a version code per variant
```
android {
 //...
    android.applicationVariants.all { variant ->
        // Assigns a different version code for each output APK
        // other than the universal APK.
        variant.outputs.each { output ->
            // Stores the value of ext.abiCodes that is associated with the ABI for this variant.
            def baseAbiVersionCode =
                // Determines the ABI for this variant and returns the mapped value.
                project.ext.abiCodes.get(output.getFilter(OutputFile.ABI))

            // Because abiCodes.get() returns null for ABIs that are not mapped by ext.abiCodes,
            // the following code does not override the version code for universal APKs.
            // However, because we want universal APKs to have the lowest version code,
            // this outcome is desirable.
            if (baseAbiVersionCode != null) {

            // Assigns the new version code to versionCodeOverride, which changes the version code
            // for only the output APK, not for the variant itself. Skipping this step simply
            // causes Gradle to use the value of variant.versionCode for the APK.
            output.versionCodeOverride =
                    baseAbiVersionCode * 1048576 + variant.versionCode
            }
        }
    }
}
```

**Comment by HazAT** [comment]
@denissb can you please post a link to your account or an event so I can take a look.

So having multiple releases per se shouldn't be the problem.
We discussed exactly your case yesterday and noticed that this may be confusing for users.
Does it break in anyway your workflow with having multiple releases? We can think of something how to fix this.

What I am a bit confused about, is where this
![image](https://user-images.githubusercontent.com/363802/74429226-d8d3be00-4e5a-11ea-934f-eabbdb9fd09a.png)
release is coming from?

**Comment by denissb** [comment]
https://sentry.io/organizations/sampension/issues/1510617273/?project=1277898&referrer=slack

**Comment by denissb** [comment]
Here is a link to an existing issue: https://sentry.io/organizations/sampension/issues/1510617273/?project=1277898&referrer=slack

The only problem with multiple versions per release in terms of workflow is that it is confusing because the same issue will appear on different releases if it is a bug in the JS code. (since the codebase is the same). Off-course if something is wrong on the native side it can be more clear if split per abi.

Off-course the main goal now it to get errors reported on both platforms and code paths shown.

**Comment by HazAT** [comment]
@denissb we try not to break the workflow too much by showing the shorter versions in the UI like 
![image](https://user-images.githubusercontent.com/363802/74435615-1ccbc080-4e65-11ea-9b2e-5490f989bc04.png)
while in the background it could be that it's in a different release if you do abi splitting.
What's important is that you upload the sourcemaps for all those different releases so we can use if for symbolication. From what I can see from your initial post, sentry-cli is already doing that correctly.

So besides us just documenting this behavior is there actually something broken right now?

**Comment by denissb** [comment]
Well the issues are being reported for this release: https://sentry.io/organizations/sampension/issues/1510617273/?project=1237684
but it:
1. Has no artefacts uploaded so it does not show code path (maybe same issue as you are fixing for iOS)
2. It tries to use version 1.0.19412 (3165140) but sentry was uploading for test.app.app@1.0.19412+4213716 if you look at gradle output 3165140 was actually one of the distributions, but I am assuming it should be test.app.app@1.0.19412+3165140
(this is confusing since versionCode can be used once and multiple times in case of an bi split)

**Comment by HazAT** [comment]
Do you set the release manually in the code (JS)?

**Comment by denissb** [comment]
For version 1.0.19412 I still did, for version 1.0.19430 I didn't (like you asked in the previous comment)
Issues get reported for **1.0.19430 (19430)**
Releases generated:
<img width="1131" alt="Screenshot 2020-02-13 at 14 17 07" src="https://user-images.githubusercontent.com/2261330/74439253-33294a80-4e6c-11ea-904b-9e3e6da95613.png">
**iOS**
<img width="1157" alt="Screenshot 2020-02-13 at 14 19 17" src="https://user-images.githubusercontent.com/2261330/74439509-a5019400-4e6c-11ea-83a8-354562f6180d.png">
**Android**
<img width="1156" alt="Screenshot 2020-02-13 at 14 21 04" src="https://user-images.githubusercontent.com/2261330/74439407-74215f00-4e6c-11ea-9190-7b47adf47658.png">'
**And a generic one? (which gets reports but has no sources)**
<img width="1157" alt="Screenshot 2020-02-13 at 14 18 58" src="https://user-images.githubusercontent.com/2261330/74439418-797ea980-4e6c-11ea-9035-dbe1272ce5ee.png">

**Comment by HazAT** [comment]
The generic one seems odd I don't understand where this is coming from.

If you see `1.0.19412 (3165140)` the real identifier that we sent is `test.app.app@1.0.19412+3165140`
we only show in the UI the important part. 
But if you see releases like `test.app.app-1.0.19431` this is still the old format that shouldn't exist anymore.

**Comment by denissb** [comment]
I am assuming test.app.app-1.0.19430 comes from iOS because it has main.jsbundle in artefacts.
And as far as iOS goes my setup is pretty standard.

**Comment by HazAT** [comment]
@denissb I will release `1.3.1` soon it should fix this.

**Comment by denissb** [comment]
Great, I will test with that one once it's out. Thanks so far.

**Comment by HazAT** [comment]
`1.3.1` has been released, fixing the iOS issue.
