### ISSUE TITLE
Logs are not shown for android emulator in dashboard.

### ISSUE THREAD

**Issue by harry329** [getsentry/sentry-react-native#763]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [ x]  Android

SDK:
- [ x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: sentry/react-native@1.3.0
`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
Create an app using react-native and install sentry
Setup sentry project and add the init and captureMessage as in docs, in App.js
When I am trying to log error with Android emulator (Pixel2 7.1.1) errors are not getting logged to sentry dashboard, whereas it works fine with iOS simulator.

**Actual result:**
- Only logs for IOS simulator not for android emulator 

**Expected result:**
- Should show logs for iOS and android.

Please let me know if you any more info from my end, thanks.

**Comment by HazAT** [comment]
Do you get any error messages?
Can you enable `debug: true` in the init options and look at logcat to see what's going on.

**Comment by harry329** [comment]
![android_emulator](https://user-images.githubusercontent.com/11696141/74464120-98734080-4e58-11ea-93d8-8bfb1dc4c8f6.png)

Same code works on android real device.

**Comment by grantgeorge** [comment]
I'm also experiencing this issue on the Android emulator.

FWIW - we ejected from expo.. could this be related?

**Comment by marandaneto** [comment]
hey @grantgeorge not sure if it's related to expo.

Could you tell me which exactly Android image were you running with?
It would be useful to know the `ABI` and `Target` (with Google APIs or not), thanks

**Comment by grantgeorge** [comment]
@marandaneto 

![image](https://user-images.githubusercontent.com/4458680/75911123-ecdc6100-5e03-11ea-92df-d67fd4acd583.png)

**Comment by FadiAboMsalam** [comment]
this issue took 2 hours from my time trying to know what is wrong then after running the app on real devices logs are received

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

ps: I ran an emulator on Android and iOS and both have worked.
