### ISSUE TITLE
Android and iOS are handling setUser differently

### ISSUE THREAD

**Issue by crazyjooe** [getsentry/sentry-react-native#766]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.1.62

Init Code:

```
Sentry.init({
  enableNative: true,
  enableNativeCrashHandling: false,
  enableNativeNagger: false,
  dsn: 'https://...@sentry.io/...'
});

Sentry.setUser({
	id: '123',
	userID: '1245',
	companyID: '6789'
});

```

---
I have the following issue:
User data reported from Android looks different in Sentry compared to iOS and shows `unknown` key name instead of parsing passed properties correctly.

**Steps to reproduce:**
- Init sentry and set a user with ID and additional data
- Throw an error on RN side

**Actual result:**
- If happened Android, when looking at error details, all fields except ID are rendered as JSON with `unknown` key. On iOS, all data is rendered as expected.

**Expected result:**
- Both Android and iOS behave the same way and can handle custom user data fields.

**Comment by HazAT** [comment]
As a workaround for now, please stick to the official properties supported by the `User` Object
https://docs.sentry.io/development/sdk-dev/event-payloads/user/
afaik user.data also works which is an object to set `companyID` in
This should fix the issue
