### ISSUE TITLE
Failed to resolve io.sentry:sentry-android:2.0.0-rc04

### ISSUE THREAD

**Issue by anthowm** [getsentry/sentry-react-native#767]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.2.1
`react-native` version: 0.61.4

---
I have following issue:
After move to a branch and rm -rf node_modules and npm I this error appears. I didnt update sentry but now requires io.sentry:sentry-android:2.0.0-rc04 that seems like not exist. I change this manually but my CI/CD is broken.

<img width="764" alt="Screenshot 2020-02-17 at 11 13 56" src="https://user-images.githubusercontent.com/5764698/74644636-daf98d80-5176-11ea-8590-872c9fa0166b.png">

**Steps to reproduce:**
Install sentry

**Actual result:**
- Compile fail

**Expected result:**
- Compile success

Maybe I'm missing something.

**Comment by marandaneto** [comment]
@anthowm thanks for raising this issue.

we are aware of it and working on it right now.
See: https://github.com/getsentry/sentry-android/issues/270

Use one of the workarounds for now and I'll update you as soon as it's released again.

Thanks for understanding.

**Comment by anthowm** [comment]
nice thanks for fast reply.

**Comment by shuvo0074** [comment]
add this to your allprojects dependencies in build.gradle in project:
maven {
            url = "https://dl.bintray.com/getsentry/sentry-android"
        }

**Comment by marandaneto** [comment]
it should be fixed now, please let us know if you find any issues :) thanks for patience!
