### ISSUE TITLE
Source code was not found for both iOS and Android

### ISSUE THREAD

**Issue by crazyjooe** [getsentry/sentry-react-native#769]
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

Platform:
- [ X ]  iOS
- [ X ]  Android

SDK:
- [ X ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.2

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});

Sentry.setRelease('some version');
```

---
I have following issue:

Even though sourcemaps are uploaded and named properly for a release, the same error appears when crash occurs.

Description goes here ...

We upload sourcemaps on our CI like this:

```
  sentry-cli releases new ...
  sentry-cli releases files ... upload-sourcemaps --rewrite --validate --strip-common-prefix --bundle ... --bundle-sourcemap... 
  sentry-cli releases finalize ...
```

Today we noticed that crash reports started showing "Source code not found.." error, even though we didn't change anything in our setup besides upgrading to 1.3.1 from 1.2.x.

Crash examples:

https://sentry.io/organizations/pipedrive-ou/issues/1520092488/?project=1875107 for Android
https://sentry.io/organizations/pipedrive-ou/issues/1514534315/?project=1875107&query=is%3Aunresolved for iOS

**Comment by crazyjooe** [comment]
Any updates/workarounds for this? The only reason we are using Sentry is to have sourcemap support, so it makes little sense if it's not working

**Comment by HazAT** [comment]
@crazyjooe Sorry about that, so we changed how release names are sent in `1.3.0`.
If you manually set releases or invoke `sentry-cli` yourself you need to make sure that the `release` and `dist` 100% align with how you are invoking `sentry-cli`.

A quick glimpse into you two posted issues highlight that there is a release with artifacts but both have not `dist` set while both event sent have a `dist`.
Again, both `release` and `dist` need to match in order for us to be able to use the right source maps.

**Comment by yaroslavnikiforov** [comment]
Hello @HazAT, I have the same issue on iOS and Android. Use `./gradlew assembleRelease` (and `./gradlew bundleRelease`) for Android builds and `xcodebuild` cli for iOS builds. It seems like sourcemaps upload automatically during running these commands. 
<img width="894" alt="Screen Shot 2020-02-24 at 10 01 45 PM" src="https://user-images.githubusercontent.com/42115630/75234929-1f62da00-57c4-11ea-928c-6e93d52702d0.png">
Artifacts are present:
<img width="1195" alt="Screen Shot 2020-02-25 at 11 37 44 AM" src="https://user-images.githubusercontent.com/42115630/75235064-60f38500-57c4-11ea-97ee-c181153597e3.png">
<img width="866" alt="Screen Shot 2020-02-25 at 11 38 08 AM" src="https://user-images.githubusercontent.com/42115630/75235073-6650cf80-57c4-11ea-89be-023862be2b4d.png">
<img width="846" alt="Screen Shot 2020-02-25 at 11 38 34 AM" src="https://user-images.githubusercontent.com/42115630/75235077-68b32980-57c4-11ea-90b3-3906bd3b3316.png">

I followed this installation guide: https://docs.sentry.io/platforms/react-native/
Link to the issue: https://sentry.io/organizations/stroller-ab/issues/1525275501/?project=246038&query=is%3Aunresolved&statsPeriod=14d
Link to the release: https://sentry.io/organizations/stroller-ab/releases/life.stroller.preggers2%401.40.0%2B659/?project=246038&statsPeriod=14d

**Comment by crazyjooe** [comment]
@HazAT thanks for the reply.

We started setting dist as "1" every time and also had to update to 1.3.2 since 1.3.1 crashed on Android, and got sourcemaps back. Pretty weird though that such thing is forced and is not fully explained in the documentation : (

**Comment by yaroslavnikiforov** [comment]
Fixed by passing dist property in Sentry.init() call
<img width="735" alt="Screen Shot 2020-02-25 at 4 53 55 PM" src="https://user-images.githubusercontent.com/42115630/75258631-70d48e80-57ef-11ea-95c3-86ce8d330272.png">
Here release should match with release name and dist should match with Distribution name in Artifacts release tab.

**Comment by mattlin** [comment]
@yaroslavnikiforov  I have the same problem. Can you tell me the version of your @sentry/react-native ?  I try passing dist property in Sentry.init() call ,it does not working for me at  @sentry/react-native 1.3.3 ?

**Comment by yaroslavnikiforov** [comment]
@mattlin I have @sentry/react-native 1.3.2. Make sure that you pass release and dist properties in Sentry.init()
<img width="757" alt="Screen Shot 2020-03-16 at 4 12 48 PM" src="https://user-images.githubusercontent.com/42115630/76766809-3c764180-67a1-11ea-9280-ec5a6ca912cc.png">
And make sure that values you pass are the same as in release description in Sentry
<img width="1194" alt="Screen Shot 2020-03-16 at 4 15 06 PM" src="https://user-images.githubusercontent.com/42115630/76767129-cde5b380-67a1-11ea-9a85-3fc7cf940259.png">

**Comment by mattlin** [comment]
Do you use  @sentry/cli/bin/sentry-cli releases to upload the souce map ? use the '--rewrite' option ? Can you show me your command example of sentry-cli releases ?  @yaroslavnikiforov

**Comment by yaroslavnikiforov** [comment]
@mattlin, I have react-native version > 0.60, so I installed it with `npx sentry-wizard -i reactNative -p ios android`. To create builds I use `./gradlew assembleRelease` and `./gradlew bundleRelease` on Android, and xcodebuild cli on iOS. In such case, source maps upload automatically

**Comment by mattlin** [comment]
@yaroslavnikiforov  Thanks a lot.  I am running self-hosted sentry instance, there is an internal Sentry project. I found some error logged in the projetct #internal.

**Comment by azundo** [comment]
This could be the issue as described in #798 where only one version code (whatever version code happens to be processed last) gets a release. I've posted a workaround that creates a release for every version code here: https://github.com/getsentry/sentry-react-native/issues/798#issuecomment-611873413

**Comment by marandaneto** [comment]
since release and dist must match, is it still an issue?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
