### ISSUE TITLE
Access SDK on native side

### ISSUE THREAD

**Issue by rishabh876** [getsentry/sentry-react-native#771]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 2.0.0
`react-native` version: 1.3.1

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue: I would like to initialise Sentry on the native side.

 I would like to initialise Sentry on the native side before react native context is available. The reason why I am doing this is because I have breadcrumbs and crash reporting happening on native side as well. 
We can enable this, if we change `implementation` with `api` like this in gradle:  
`api 'io.sentry:sentry-android:2.0.0-rc04'`
instead of 
`implementation 'io.sentry:sentry-android:2.0.0-rc04'`

**Steps to reproduce:**
- Add a breadcrumb in MainApplication
- Add sentry initialisation in React Native Side. 
- Run the app. 
- App can not compile because we can't find Sentry Api on native side.

**Actual result:** 
- Unable to access Sentry Android SDK classes in Native module as its module private in this library.

**Expected result:**
- Ideally I should be able to access Sentry on my native side as well.

**Comment by marandaneto** [comment]
Fixed by #776
