### ISSUE TITLE
Android sourcemapOutput detection broken?

### ISSUE THREAD

**Issue by muxe** [getsentry/sentry-react-native#772]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.0
`react-native` version: 0.59.10

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

My bundle is not producing any sourcemaps and then the upload of the sourcemap fails.
I think there is an issue with forcing sourcemap output:
My default bundle command does NOT have a --sourcemap-output in.
It starts here https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L45
Then here https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L212 it tries to get the sourcemapOutput path.
So these lines wont find a sourcemapOutput https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L180-L186 BUT then here 
https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L195-L198 some weird sourcemapOutput is returned.
So the script thinks there was a --sourcemap-output defined and does not force the arg, hence no sourcemap will be generated but it still expects a sourcemap to be there.

Or am I missing something?

**Steps to reproduce:**
- use rn 0.59.10 and sentry 1.3.0

**Actual result:**
- no sourcemap generated

**Expected result:**
- a sourcemap generated

**Comment by muxe** [comment]
https://github.com/getsentry/sentry-react-native/pull/754#issuecomment-588246525

**Comment by xwartz** [comment]
cc @HazAT

**Comment by HazAT** [comment]
Sorry about that, we'll take a look.

**Comment by marandaneto** [comment]
@muxe hey, I've raised a PR #777 could you just copy/paste that part of the code and try this out? thanks :)

**Comment by muxe** [comment]
Thanks. I'll give it a go, but not before monday though.

I am not quite sure, but I think my --bundle-output is set but not the --sourcemap-output.
This should then still return a sourcemapOutput !== null from extractBundleTaskArguments which again leads to no args added here https://github.com/getsentry/sentry-react-native/blob/fix/sourcemaps_folder/sentry.gradle#L220-L224

But as I said this only by looking at code, I would need to run this to see how it behaves.

**Comment by marandaneto** [comment]
@muxe sure :) but I'd say that in your case `--sourcemap-output` is not passed at all, this thing was implemented later than your react-native version `0.59.10`, let me know your findings, thanks.

**Comment by HazAT** [comment]
Fixed by https://github.com/getsentry/sentry-react-native/pull/777

**Comment by amogh-jrules** [comment]
Still facing this issue in 1.3.7

**Comment by marandaneto** [comment]
@amogh-jrules mind filling a bug with all the versioning + logs? thanks :)
