### ISSUE TITLE
Uploaded index.android.bundle has a 0 B size in release artifacts and error stack traces are minified

### ISSUE THREAD

**Issue by agorf** [getsentry/sentry-react-native#778]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.customdomain.com/...'
});
```

---
For some reason, the uploaded release artifact of `index.android.bundle` gets uploaded to our Sentry instance with a size of 0 B. When clicking to download it, its contents are:

```
{"detail": "Internal Error", "errorId": "..."}
```

This happens only with Android. In the same repo, we tried cutting a release with Xcode and both artifacts (`index.android.bundle` and `index.android.bundle.map`) get uploaded successfully.

Not sure if it's the cause, but in error stack traces we don't get anything meaningful like files and source code lines. Instead, everything is minified.

Passing the debug flag to see the Sentry upload requests, all seem OK and the server responds with 200 OK. There are no errors.

Related issue filed against `sentry`: https://github.com/getsentry/sentry/issues/17005

I opened this issue because I don't believe this is a `sentry` but a `sentry-react-native` issue. iOS seems to work fine both in terms of uploaded artifacts as well as meaningful stack traces.

**Comment by HazAT** [comment]
Can you post a link to the issue in Sentry?
Having a 0B file uploaded is expected when you use Hermes bundles.
What's not expected that the code stays minified.

**Comment by agorf** [comment]
@HazAT Hello, thanks for the response.

I have already posted the link to the issue: https://github.com/getsentry/sentry/issues/17005

Unless you mean something else?

The weird thing is the uploaded bundle is not 0 B for iOS. Is this normal?

**Comment by Swatinem** [comment]
> The weird thing is the uploaded bundle is not 0 B for iOS. Is this normal?

yes. The 0B thing is specific to hermes bytecode, which is only relevant for android.

**Comment by agorf** [comment]
> yes. The 0B thing is specific to hermes bytecode, which is only relevant for android.

Cool. I'd be happy to provide any other info necessary or try things out.

**Comment by minderov** [comment]
> Having a 0B file uploaded is expected when you use Hermes bundles

Does that mean it is expected for the content of the file to say "Internal Error"?
```
{"detail": "Internal Error", "errorId": "..."}
```

**Comment by HazAT** [comment]
@minderov Are you using sentry.io or your own instance?

**Comment by agorf** [comment]
I tried on https://sentry.io and I have the same issue: no readable source or file names in stack traces. So this does not seam to be a sentry issue.

Not sure if it helps, but I also tried sending an error in development and I saw some queries that got 404 in my Metro server.

It looks like there's a request for some files `/SplashScreen.js` etc that get 404.

Here are some screenshots:

![Screenshot from 2020-02-26 12-52-14](https://user-images.githubusercontent.com/87479/75338125-e8112d80-5896-11ea-9da3-5791cc7c1cab.png)
![Screenshot from 2020-02-26 12-52-43](https://user-images.githubusercontent.com/87479/75338128-e8a9c400-5896-11ea-8915-ee6e73b6b357.png)

**Comment by agorf** [comment]
Update:

Regarding the comment above, I forgot to update the `sentry.properties` files. Once I did, everything worked like a charm on Sentry.io (I get meaningful stack traces). So it is, indeed an issue with us running an old (9.1.2) Sentry version and not that pointing to master.

**Comment by alex-a-pereira** [comment]
@agorf would you mind explaining what changes needed to be made to `sentry.properties`? I'm hitting the same issue currently

**Comment by agorf** [comment]
@alex-a-pereira IIRC the real culprit was lack of proper support for meaningful stacktraces in the Hermes engine. AFAIK it has since been fixed/implemented by Facebook.

**Comment by alex-a-pereira** [comment]
@agorf appreciate the quick reply! I just re-read your comment, did you mean "forgot to update sentry.properties to point at sentry.io"?? If so that definitely not my issue unfortunately.

I'll send an update here when I solve whatever my issue is, in case anyone else runs into the issue I'm hitting

**Comment by alex-a-pereira** [comment]
@agorf ah gotcha, thanks anyways for the help!

**Comment by alex-a-pereira** [comment]
Just solved my issue, ended up being a configuration issue on our end rather than an issue with sentry/hermes.

We use MS AppCenter to build our RN app for Android, and use the feature to automatically manage incrementing the build number. not 100% sure how it works, but it doesn't modify the `versionCode` written in `android/app/build.gradle`. Our `versionCode` was hardcoded to 2 inside build.gradle, and sentry uses the value inside the file to determine what version the sourcemaps are uploaded for.

for example the app was being built with `build_number == 154` so issues reported to sentry from the sentry-sdk had `release = 1.3.0 (154)`. But sourcemaps were being uploaded for `1.3.0 (2)`, so sentry couldn't find them which makes sense.

Here's the code for the fix:

```groovy
// android/app/build.gradle
// if building in appcenter, use the build id here, otherwise just use 1 because we're building locally
versionCode System.getenv('APPCENTER_BUILD_ID') ? Integer.parseInt(System.getenv('APPCENTER_BUILD_ID')) : 1
```
