### ISSUE TITLE
Android app is crashing on production after installing sentry

### ISSUE THREAD

**Issue by itsyogesh** [getsentry/sentry-react-native#779]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.2
`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:
Android is crashing on production, while it works fine on the debug. I am getting the following issue.
Description goes here ...
Running the app on production is causing the following issue.
![Screenshot_2020-02-24-09-40-48-763_com miui bugreport](https://user-images.githubusercontent.com/1210943/75139389-80ca7080-5712-11ea-9734-014aa4908df8.jpg)

**Steps to reproduce:**
- Step Install sentry app, build production with ./gradlew buildRelease
Running the production app and its crashing.

**Actual result:**
The app is crashing as soon as its opened.

**Expected result:**
It should run normally after installing the app.

**Comment by itsyogesh** [comment]
I tried setting up android as described here, https://sentry.io/for/android/ but it wasn't working. Had to downgrade to 1.2.1 and it's working fine now.

**Comment by xwartz** [comment]
I have the same issue when upgraded the version from 1.3.1 to 1.3.2

**Comment by xwartz** [comment]
cc @HazAT

**Comment by marandaneto** [comment]
@itsyogesh hey, thanks for raising this issue.

if you just run `npx react-native run-android --variant=release` do you get the same issue?

I've tried using RN `0.61.5` and Sentry `1.3.3` and it works fine.
Could you test it using `1.3.3`, please? thanks :)

**Comment by marandaneto** [comment]
@itsyogesh also, the link you should be looking into is https://docs.sentry.io/platforms/react-native/
this link already sets up sentry-android and sentry-cocoa under the hood for you, that might be the problem.

Could you give it a try? thanks.

**Comment by marandaneto** [comment]
hey, @xwartz your issue seems to be different, to be honest.
It's like it didn't do the packaging correctly.

Could you try:
`cd android; ./gradlew clean cleanBuildCache` just to clean the gradle caching.
and `npx react-native run-android` to run via react-native CLI.

Also, have you followed the same steps here? https://docs.sentry.io/platforms/react-native/
What's your RN and sentry-react-native versions? thanks.

**Comment by xwartz** [comment]
@marandaneto  thanks, it works for me

**Comment by HazAT** [comment]
Closing this since @marandaneto provided the correct answer.

**Comment by nicolaelia** [comment]
I had the same issue and `cd android; ./gradlew clean cleanBuildCache` resolved it but I suggest to add this line to the docs https://docs.sentry.io/platforms/react-native/
