### ISSUE TITLE
Broken hermes crash reports on 1.3.0-1.3.3 (Android)

### ISSUE THREAD

**Issue by lukebars** [getsentry/sentry-react-native#781]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 2.0.0
`react-native` version: 0.61.1
`@sentry/react-native` version: 1.3.3

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

I'm having issue that with 1.3.x when running android with hermes enabled, crash reports look to be broken on sentry dashboard.

**Steps to reproduce:**
- Build android release using `./gradlew assembleRelease` with hermes engine enabled.
- Open the app.
- Produce error.
- See crash report on sentry.io

**Actual result:**

[link](https://sentry.io/organizations/uab-kilo-grupe/issues/1470462098/?project=1852677&sort=new)
[shared link](https://sentry.io/share/issue/55deb130ff1d41478cc4c9db20a26db3/)

![image](https://user-images.githubusercontent.com/46403446/75233830-2ee12380-57c2-11ea-8102-053963d35205.png)

![image](https://user-images.githubusercontent.com/46403446/75234194-d2323880-57c2-11ea-95f8-c5e704cb326d.png)

**Expected result:**
- Actual crash source map on sentry.io

My `yarn.lock`

```"@sentry/browser@^5.12.1":
 "@sentry/cli@^1.51.0":
  "@sentry/core@5.12.4", "@sentry/core@^5.12.0":
  "@sentry/hub@5.12.4":
  "@sentry/integrations@^5.12.0":
  "@sentry/minimal@5.12.4":
  "@sentry/react-native@^1.3.2":
  "@sentry/types@5.12.4", "@sentry/types@^5.12.0":
  "@sentry/utils@5.12.4", "@sentry/utils@^5.12.0":
  "@sentry/wizard@^1.1.1":
```

**Comment by marandaneto** [comment]
hey @lukebars thanks for raising this issue.
looking at your yarn file, it seems that you are using sentry `1.3.2`: `"@sentry/react-native@^1.3.2":`
could you update to `v1.3.3` and give it a try? thanks :)

**Comment by lukebars** [comment]
Sorry, that's an old yarn.lock, tried that on v.1.3.3 too before writing final issue, same result

**Comment by marandaneto** [comment]
> Sorry @marandaneto , that's an old yarn.lock, tried that on v.1.3.3 too before writing final issue, same result

no worries, have you tried cleaning caches and doing it again?

eg:
`./gradlew clean cleanBuildCache` -> android dir.
run RN CLI `npx react-native run-android --variant=release` instead of `./gradlew assembleRelease`

Just to be sure it's not caching issues or something related to it, let us know, thanks.

**Comment by lukebars** [comment]
@marandaneto  RN 0.61.5

[https://sentry.io/organizations/uab-kilo-grupe/issues/1533483936/?project=1451694&sort=new](url)
[https://sentry.io/share/issue/03a7747114ea4bbba027d33faec28e7d/](shared url)

Looks like it's the same. Also with 0.61.5 it doesn't build android until i remove the line from react-native link - `apply from: "../../node_modules/@sentry/react-native/sentry.gradle"` from `build.gradle`. After that it doesn't seem to upload the source maps.

```
"@sentry/browser@^5.12.1":
"@sentry/cli@^1.51.0":
"@sentry/core@5.12.5", "@sentry/core@^5.12.0":
"@sentry/hub@5.12.5":
"@sentry/integrations@^5.12.0":
"@sentry/minimal@5.12.5":
"@sentry/react-native@^1.3.3":
"@sentry/types@5.12.4", "@sentry/types@^5.12.0":
"@sentry/utils@5.12.5", "@sentry/utils@^5.12.0":
"@sentry/wizard@^1.1.1":
```

**Comment by marandaneto** [comment]
@lukebars thanks, if you comment/remove this line, for sure it's not gonna upload the source maps.

Let's start from the beginning, could you share the build error? that's new for us, thanks.

**Comment by lukebars** [comment]
@marandaneto 
```
> Task :app:transformClassesAndResourcesWithR8ForRelease FAILED
R8 is the new Android code shrinker. If you experience any issues, please file a bug at
https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
disable R8 by updating gradle.properties with 'android.enableR8=false'.
Current version is: 1.4.94 (build 390954928f0db9c3b888a367f7f128ce3bbfb160 from go/r8bot (luci-r8-ci-archive-0-5g74)).

D8: Program type already present: io.sentry.BuildConfig

FAILURE: Build failed with an exception.```

**Comment by marandaneto** [comment]
> @marandaneto happens only when upgraded to 0.61.5
> 
> ```
> > Task :app:transformClassesAndResourcesWithR8ForRelease FAILED
> R8 is the new Android code shrinker. If you experience any issues, please file a bug at
> https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
> disable R8 by updating gradle.properties with 'android.enableR8=false'.
> Current version is: 1.4.94 (build 390954928f0db9c3b888a367f7f128ce3bbfb160 from go/r8bot (luci-r8-ci-archive-0-5g74)).
> 
> D8: Program type already present: io.sentry.BuildConfig
> 
> FAILURE: Build failed with an exception.
> ```
> 
> **EDIT:**
> 
> Looks like it was `react-native link` what was breaking it. Tried it with `yarn sentry-wizard -i reactNative -p ios android` and it built android successfully.
> 
> Although the crash report looks the same...
> [link](https://sentry.io/organizations/uab-kilo-grupe/issues/1533483936/?sort=new)

The compile error should be because of Java 8 compatibility, see if you have this block in your `app/build.gradle`.

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by HazAT** [comment]
@lukebars Are you using CodePush or something similar by any chance?
The issue you linked looks really odd to a degree where it seems like your native code (java) and javascript code are out of sync.
So using old JS code with new native code.

If your issue looks like this
![image](https://user-images.githubusercontent.com/363802/75466589-b7122500-598a-11ea-9ac4-e8d894b199e8.png)

This stacktrace is the correct javascript stacktrace, but our JS SDK, for whatever reason was not able to pick this crash up.

The uploads of you sources maps and everything else looks correct, so that should be the issue.
It's really just this.

Are you able to reproduce this because it would be really helpful to figure under what constellation this kind of crash is happening?

**Comment by lukebars** [comment]
> > @marandaneto happens only when upgraded to 0.61.5
> > ```
> > > Task :app:transformClassesAndResourcesWithR8ForRelease FAILED
> > R8 is the new Android code shrinker. If you experience any issues, please file a bug at
> > https://issuetracker.google.com, using 'Shrinker (R8)' as component name. You can
> > disable R8 by updating gradle.properties with 'android.enableR8=false'.
> > Current version is: 1.4.94 (build 390954928f0db9c3b888a367f7f128ce3bbfb160 from go/r8bot (luci-r8-ci-archive-0-5g74)).
> > 
> > D8: Program type already present: io.sentry.BuildConfig
> > 
> > FAILURE: Build failed with an exception.
> > ```
> > 
> > 
> > **EDIT:**
> > Looks like it was `react-native link` what was breaking it. Tried it with `yarn sentry-wizard -i reactNative -p ios android` and it built android successfully.
> > Although the crash report looks the same...
> > [link](https://sentry.io/organizations/uab-kilo-grupe/issues/1533483936/?sort=new)
> 
> The compile error should be because of Java 8 compatibility, see if you have this block in your `app/build.gradle`.
> 
> ```
> android {
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> }
> ```

Yes, it's there.



> @lukebars Are you using CodePush or something similar by any chance?
> The issue you linked looks really odd to a degree where it seems like your native code (java) and javascript code are out of sync.
> So using old JS code with new native code.
> 
> If your issue looks like this
> ![image](https://user-images.githubusercontent.com/363802/75466589-b7122500-598a-11ea-9ac4-e8d894b199e8.png)
> 
> This stacktrace is the correct javascript stacktrace, but our JS SDK, for whatever reason was not able to pick this crash up.
> 
> The uploads of you sources maps and everything else looks correct, so that should be the issue.
> It's really just this.
> 
> Are you able to reproduce this because it would be really helpful to figure under what constellation this kind of crash is happening?

Yes, codepush is enabled, but this is straight build compiled for testing new sentry, just out from the `npx react-native run-android --variant=release` oven.  This kind of crash report happens all the time I'm tesing either writing an undefined function or throwing new Error

**Comment by HazAT** [comment]
@lukebars Something must be out of sync, running this on a clean react-native project works just fine.
Not really sure how to help you debug this.

**Comment by lukebars** [comment]
@HazAT @marandaneto it was deprecated sentry DSN that was causing it :)

**Comment by marandaneto** [comment]
@lukebars glad that it worked :)

**Comment by lukebars** [comment]
@marandaneto actually it was bit stranger than that...

this works: 
```
---------------
App.js
---------------
import * as Sentry from '@sentry/react-native';

if (FeatureEnabler.sentry) {
  Sentry.init({
    dsn,
  });
  Sentry.setTags(sentryTags);
}

```

this doesn't: 
```
---------------
App.js
---------------
import { maybeInitSentry } from './apis/sentry';

maybeInitSentry();

---------------
sentry.js
---------------
import * as Sentry from '@sentry/react-native';

export const maybeInitSentry = () => {
  if (FeatureEnabler.sentry) {
    Sentry.init({ dsn });
    Sentry.setTags(sentryTags);
  }
};
```

**Comment by skizzo** [comment]
I'm having the same problem with `@sentry/react-native` version `1.3.7`. Any solutions?

**Comment by riadhriadh** [comment]
unlink  @sentry/react-native
