### ISSUE TITLE
Gradle build failed: Cannot get property 'react' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by tomershohet** [getsentry/sentry-react-native#782]
OS:
- [X ]  Windows
- [ ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [X ]  Android

SDK:
- [ X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.59.9

Gradle details: 
com.android.tools.build:gradle:3.4.2
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

---
I have following issue:

Gradle build failed with an error:
Cannot get property 'react' on extra properties extension as it does not exist

The issue only happen on 1.3.3, Downgrade to @sentry/react-native 1.3.2 solve the issue.
I've tried a couple of time to go back and forth between version 1.3.3 and 1.3.2 - on 1.3.2 it always work and on 1.3.3 always the same error

Thanks you

**Comment by marandaneto** [comment]
hey @tomershohet thanks for raising this issue.

could you update RN to the latest version and try this out again? if not the latest, min `0.60.4` and let us know if it worked, if it does, we'd need to do a fix that makes it retro compatible, thanks.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
