### ISSUE TITLE
Sentry adds permission WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by AdamGerthel** [getsentry/sentry-react-native#783]
Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.4

---
I have following issue:

When building my app which utilises @sentry/react-native, the permission to WRITE_EXTERNAL_STORAGE is being added to my application, according to *manifest-merger-release-report.txt*, which states:

```
ADDED from [:@sentry_react-native] /path-to-my-project/node_modules/@sentry/react-native/android/build/intermediates/library_manifest/release/AndroidManifest.xml:17:13-34
	android:name
ADDED from [:@sentry_react-native] /path-to-my-project/node_modules/@sentry/react-native/android/build/intermediates/library_manifest/release/AndroidManifest.xml:16:13-47
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
```
I recently migrated from Expo where I used expo-sentry, which did *not* cause this permission to be added, so I'm a bit confused, and I don't want to add permissions to my app which I don't use/need. It's not clear to me why Sentry would need this permission.

**Steps to reproduce:**
Build an Android app which includes @sentry/react-native

**Actual result:**
Permission WRITE_EXTERNAL_STORAGE is added

**Expected result:**
Permission WRITE_EXTERNAL_STORAGE is not added

**Comment by HazAT** [comment]
We need that to cache the events in case the phone is offline.
You can opt-out of using native crashes by setting `nativeEnabled: false` but you will lose all native crash handling.

**Comment by AdamGerthel** [comment]
@HazAT Wouldn't it be possible to use AsyncStorage for that? Why would you need to write to *external* storage? AsyncStorage doesn't require permission.

**Comment by HazAT** [comment]
@AdamGerthel Sadly not, it's an external deprecated dependency.

Also looking at it a second time, we never reference `WRITE_EXTERNAL_STORAGE` anywhere in out repo https://github.com/getsentry/sentry-react-native/search?q=WRITE_EXTERNAL_STORAGE&unscoped_q=WRITE_EXTERNAL_STORAGE
Also not in our Android SDK
https://github.com/getsentry/sentry-android/search?q=WRITE_EXTERNAL_STORAGE&unscoped_q=WRITE_EXTERNAL_STORAGE

We only need those two permissions: 
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
So I am not sure where this is coming from.

**Comment by AdamGerthel** [comment]
Ok, I'm removing it by force in my app using:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
```
Since I'm quite confident it won't cause any issues.
