### ISSUE TITLE
iOS crash on launching the app

### ISSUE THREAD

**Issue by BologaMarius** [getsentry/sentry-react-native#785]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [X]  iOS
- [ ]  Android

SDK:
- [X]  `@sentry/react-native`
- []  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [X]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

The issue is not logged in sentry.

Configuration:
I have this in App.tsx
```
Sentry.init({
  dsn: 'https://xxxx@sentry.io/xxxxx'});
```

---
I have following issue:
On iOS, when trying to run the app in release mode the app crashes, even if I don't have any issues in debug mode
 This is the error that I get:

`Started -- Version: 4.4.3
ERROR: SentryCrashReportFixer.c (272): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long
2020-03-02 13:07:48.610 [error][tid:com.facebook.react.JavaScript] TypeError: g.document.addEventListener is not a function. (In 'g.document.addEventListener('click',O('click',y.bind(null,'dom')),!1)', 'g.document.addEventListener' is undefined)
2020-03-02 13:07:48.612 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: g.document.addEventListener is not a function. (In 'g.document.addEventListener('click',O('click',y.bind(null,'dom')),!1)', 'g.document.addEventListener' is undefined)`

To be mentioned, if I don't initialize Sentry the app is running without any problems.
Followed all the installation steps from: https://docs.sentry.io/platforms/react-native/ and/or here https://github.com/getsentry/sentry-react-native 
**Steps to reproduce:**
- Run app in release mode

**Actual result:**
- App crashes on run time 

**Expected result:**
- Application should run without a crash

**Comment by zsiegel** [comment]
We are seeing the same issue. We are running the latest sentry and latest react native just as above.

When we run the app we get the following.

```
2020-03-02 12:38:42.742232-0600 MyAppName[12578:7161056] Sentry Started -- Version: 4.4.3
2020-03-02 12:38:42.744 [error][tid:com.facebook.react.JavaScript] TypeError: g.document.addEventListener is not a function. (In 'g.document.addEventListener('click',O('click',y.bind(null,'dom')),!1)', 'g.document.addEventListener' is undefined)

This error is located at:
    in Unknown
    in RCTView
    in RCTView
    in h
2020-03-02 12:38:42.745 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: g.document.addEventListener is not a function. (In 'g.document.addEventListener('click',O('click',y.bind(null,'dom')),!1)', 'g.document.addEventListener' is undefined)

This error is located at:
    in Unknown
    in RCTView
    in RCTView
    in h
```

We then comment out the `Sentry.init` call and see logs similar to the above comment.

**Comment by HazAT** [comment]
Are you setting anything specific in the scope or something?
This error means `Data too long` something in the event is too long.

We want to fix this issue but we need to know where to get started since just calling `init` doesn't trigger this error so we need a way to reproduce this.

**Comment by marandaneto** [comment]
hey @BologaMarius could you enable `debug` mode and let us know if you get any more useful logs? thanks.
eg:
```
Sentry.init({ 
  dsn: 'https://xxxx@sentry.io/xxxxx', 
  debug: true
});
```

**Comment by BologaMarius** [comment]
@HazAT there is no specific setup in the scope.
* iOS Simulator(but it happens in real device as well)/realease mode
* iOS version 13.3/13.2
* Xcode version 1.3.1/1.2.1
I have setup up as iOS Deployment target 11.0 since is a requirement for one of the other dependencies. Could this affect `sentry`?

@marandaneto I did that, there is no extra info about the issue. Still the same logs.

**Comment by HazAT** [comment]
@BologaMarius I have no idea why this is happening, must be some weird dependency you are using.
Can you try to do this
```
import * as Sentry from "@sentry/react-native";

Sentry.init({
  ...
  integrations: [
    new Sentry.Integrations.Breadcrumbs({
      dom: false
    }),
  ]
});
```

**Comment by Marvedog** [comment]
I have the same issue in debug mode on Android. Otherwise the same configuration as @BologaMarius.

**Comment by rt2zz** [comment]
my workaround was to stub in document.addEventListener 
```
global.document = {
  addEventListener: () => {},
}
```

**Comment by mnekrasov-iss** [comment]
Have the same issue also potentially due to Okta-react-native conflict.
Adding:
`integrations: [
    new Sentry.BrowserIntegrations.Breadcrumbs({
      dom: false
    }),
  ]`

Does not work and results in:
TypeError: undefined is not an object (evaluating 'new Sentry.BrowserIntegrations.Breadcrumbs')

Adding
`global.document = {
  addEventListener: () => {},
}`
Results in 
Error: Can't attach events for entropy collection

Anyone make any progress with this issue?

**Comment by ajp8164** [comment]
I have the same problem - took an hour to track this down to Sentry as I've been adding okta. Glad I found this issue. Adding 
`global.document = { addEventListener: () => {}, }`
worked to avoid the error.

I cross posted to okta [https://github.com/okta/okta-react-native/issues/40](https://github.com/okta/okta-react-native/issues/40)

Really would like to have a fix for this.

**Comment by marandaneto** [comment]
is it still an issue even if using the latest SEntry RN SDK and latest Okta? since the very same issue was reproduced without Sentry https://github.com/okta/okta-react-native/issues/40#issuecomment-761022307 I'm not sure if we can actually tell its Sentry fault, I can't reproduce it.

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
