### ISSUE TITLE
Alternative for setEventSentSuccessfully with @sentry/react-native

### ISSUE THREAD

**Issue by polynatic** [getsentry/sentry-react-native#787]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.0.57.8

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

I have the following issue:

We were previously using `react-native-sentry` `0.43.2`. With this version, we were using `setEventSentSuccessfully` to get the event ID and allow the user to give feedback after a crash, which is also extensively used by our customers and very helpful. Now when upgrading to `1.3.3` this function is not available anymore and I can't find an alternative. Is something like that still possible with `1.3.3`?

**Comment by HazAT** [comment]
You should be able to call `Sentry.getCurrentHub().lastEventId()` to get the last event id.
When it comes to being notified when something was sent, it's a bit more tricky. We don't have this notification anymore, you can use `beforeSend` to know when we send something and send you own notification somewhere and fetch the event id with `Sentry.getCurrentHub().lastEventId()` there.
