### ISSUE TITLE
How to ignore a directory thats isn't react native js code?

### ISSUE THREAD

**Issue by export-mike** [getsentry/sentry-react-native#791]
OS:
- [ ]  Windows
- [ /]  MacOS
- [ ]  Linux

Platform:
- [/ ]  iOS
- [ ]  Android

SDK:
- [/ ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [/ ]  No

Are you using sentry.io or on-premise?
- [ /]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue: I have a js project thats not bundled into the main react-native bundle.
```
nodejs-assets/node_modules
node_modules
src
```
nodejs-assets its for this react-native package: `nodejs-mobile-react-native`

The sentry cli seems to try and access the nodejs-assets directory to sourcemap and do its thing.
```error: IO error for operation on /Users/mike/Library/Developer/Xcode/DerivedData/medapp-dotoiybaitdopucnfocgmpwfgicj/Build/Products/Dev.Debug-iphonesimulator/medapp.app/nodejs-project/node_modules/sqlite3/build/Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: No such file or directory (os error 2)```

**Steps to reproduce:**
- Add a nodejs-assets directory with a node_modules folder install sqlite. it'll break the bundling.

**Actual result:**
- source maps / debug symbols are not uploaded.

**Expected result:**
- a way to ignore the nodejs-assets directory?

**Comment by export-mike** [comment]
I have a workaround but its not ideal.

```
mkdir -p ../../med-app-temp
mv ../nodejs-assets ../../med-app-temp/
export EXTRA_PACKAGER_ARGS=" --max-workers 1"
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode --allow-fetch ../node_modules/react-native/scripts/react-native-xcode.sh
mv ../../med-app-temp/nodejs-assets ../nodejs-assets/
rm -rf ../../med-app-temp
```

**Comment by marandaneto** [comment]
@kamilogorek is there a way to ignore a subfolder? or can we bail out if the files are not useful? maybe this is even already addressed since its an old version.

**Comment by kamilogorek** [comment]
`react-native` command doesnt allow for a specific ignores, only `source-maps` can do that.

**Comment by marandaneto** [comment]
should we move to sentry-cli then as a feature request? is it common enough that more people would benefit from it? otherwise patching the script is enough -> https://github.com/getsentry/sentry-react-native/issues/791#issuecomment-596857720

**Comment by marandaneto** [comment]
Closed in favor of https://github.com/getsentry/sentry-cli/issues/1096
