### ISSUE TITLE
Stack trace displaying gibberish value

### ISSUE THREAD

**Issue by sudsingh438** [getsentry/sentry-react-native#792]
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [ x]  Android

SDK:
- [ x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x ]  No

Are you using sentry.io or on-premise?
- [x ]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
  Sentry.init({
    dsn: 'https://...@sentry.io/...',
    release: xyz,
    dist: versioncode,
    environment: env1,
  });
```

---
I have following issue:
Stacktrace is not getting deobfuscated from the uploaded sourcemap

Description goes here ...
We have hermes enabled project and we have uploaded the source map on the artifacts with proper dist code and release. And during init of Sentry we are also passing the same dist and release name that used during creation. But still when an issue is reported. We are getting gibberish value instead of readable stacktrace.

Link for sentry issue:
https://sentry.io/organizations/ct-filing/issues/1550586960/

<img width="851" alt="Screenshot 2020-03-10 at 8 04 06 PM" src="https://user-images.githubusercontent.com/10254300/76339966-d3b24380-6320-11ea-84b7-57c37d4ade05.png">

sentry cli command used :
```
    sentry-cli --auth-token=#{token} releases --org=#{org} --project=#{project} new #{createVersion}
    sentry-cli --auth-token=#{token} releases --org=#{org} --project=#{project} files #{createVersion} upload #{uploadFile} '~/index.android.bundle' --dist #{version_code}
    sentry-cli --auth-token=#{token} releases --org=#{org} --project=#{project} files #{createVersion} upload-sourcemaps #{sourcemap} --dist #{version_code}
    sentry-cli --auth-token=#{token} upload-proguard --android-manifest #{manifest_path} #{mapping_path} --org=#{org} --project=#{project}
    sentry-cli --auth-token=#{token} releases --org=#{org} --project=#{project} finalize #{createVersion}
```

Also, for the issue reported from native side of android. Stack trace is not de obfuscated. We did upload the proguard files using sentry cli
Link for sentry issue:
https://sentry.io/organizations/ct-filing/issues/1555641049/?project=1880814&sort=new

**Steps to reproduce:**
- Step

**Actual result:**
- Gibberish value instead of stack trace

**Expected result:**
-  Readable stack trace should come

**Comment by HazAT** [comment]
@sudsingh438 Please use our gradle plugin to upload the bundle and sourcemap as described here:  https://docs.sentry.io/platforms/react-native/manual-setup/#android
We do a lot under the hood to make sure you call it with the right arguments and pass the correct source map.
https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L107-L125

The sentry-cli command that's needs to be called is `react-native gradle`

The reason it's not working for you is because we never actually convert the source map correctly.

**Comment by sudhirsinghct** [comment]
Thanks @HazAT for response . Will try the approach you mentioned

**Comment by sudsingh438** [comment]
@HazAT I tried the manual set up for some reason the task 'bundle..JsAndAssets_SentryUpload' task is not being executed. 
Also, I tried to upload the sourcemap manually using https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L107-L125

but the uploaded 'index.android.bundle' size is showing zero on sentry.io where as it has an actual size of 2.6 MB and on enabling the debug mode of sentry-cli I got the following output 

```
[04:36:53]: ▸ Processing react-native sourcemaps for Sentry upload.
[04:36:53]: ▸ INFO    2020-03-15 04:36:53.091742 +05:30   bundle path: /Users/sudhir.singh/Workspace/GitRepo/clearbook/packages/cb-mobile/android/app/build/generated/assets/react/staging/release/index.android.bundle
[04:36:53]: ▸ INFO    2020-03-15 04:36:53.091756 +05:30   sourcemap path: /Users/sudhir.singh/Workspace/GitRepo/clearbook/packages/cb-mobile/android/app/build/generated/sourcemaps/react/staging/release/index.android.bundle.map
**[04:36:53]: ▸ DEBUG   2020-03-15 04:36:53.092331 +05:30 Non-file bundle found**
[04:36:53]: ▸ > Analyzing 2 sources
[04:36:53]: ▸ > Rewriting sources
[04:36:54]: ▸ > Adding source map references
```

Also, I tried to upload it via command mentioned at https://docs.sentry.io/platforms/react-native/sourcemaps/

```
node_modules/@sentry/cli/bin/sentry-cli releases \
    files RELEASE_NAME \
    upload-sourcemaps \
    --dist DISTRIBUTION_NAME \
    --strip-prefix /path/to/project/root \
    --rewrite /path/to/your/files
```

Though both the files got upload but stacktrace didn't get deobfuscated.

**Comment by sudsingh438** [comment]
Thanks @HazAT with react-native gradle,I was able to get the stacktrace working but the file size for index.android.bundle is 0B but I am able to see deobfuscated stack trace. Am I missing something or this is the way it works?

**Comment by HazAT** [comment]
@sudsingh438 This is expected!
We will add a tooltip that this is alright :)

**Comment by HazAT** [comment]
Closing this since it seems to be solved.

**Comment by sudhirsinghct** [comment]
Thanks @HazAT for help
