### ISSUE TITLE
Build failed with continuing in background. Failed to display xcode notification

### ISSUE THREAD

**Issue by nihp** [getsentry/sentry-react-native#793]
Unable to build the app in Xcode. I got the error as 

```
continuing in background.
error: Failed to display Xcode notification
  caused by: script error: osascript: no such component "JavaScript".

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

export variant=normal
    /bin/sh -c /Users/user/Library/Developer/Xcode/DerivedData/App-cpcxnkn/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-AAA15C2C8A4.

```

Note:

It works fine before. One day the notification received after quiting the xcode. So from the next day this issue is raised and showing continuing in background.Failed to display Xcode notification.

The same is working If i run from command line react-native run-ios.
But it failed for Xcode build and archive build

Can anyone help me to resolve this error in my Xcode?

**Comment by nihp** [comment]
@HazAT @lobsterkatie @marandaneto

**Comment by lobsterkatie** [comment]
@nihp Can you please set the environment variable (as suggested in the second paragraph above) and let us know what you get?

**Comment by nihp** [comment]
In debug mode, the app get worked without the script.

But it weird, I have no idea how to fix this further.

It ended with Failed to display xcode notification
`
PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/user/Library/Developer/Xcode/DerivedData/App-cperpitadfajoqfhlycfxnkn/Build/Intermediates.noindex/App/Debug-iphonesimulator/App.build/Script-AAA15C2C8A5D45CAB4FDD904.sh (in target ‘App’ from project ‘App’)
`

**Comment by nihp** [comment]
@lobsterkatie Any updates on this?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by NIDHINgl** [comment]
anybody resolved this issue ?
