### ISSUE TITLE
Lack of information for ApplicationNotResponding errors

### ISSUE THREAD

**Issue by reyalpsirc** [getsentry/sentry-react-native#796]
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.2.1
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

I recently updated one of our production Apps to use the latest `@sentry/react-native` and suddenly started seeing some ANR’s like reported in [#786](https://github.com/getsentry/sentry-react-native/issues/786).
I tried to track down the places where the ANR’s were happening but then noticed the following problems:

1. The ANRs are not showing the user ids set by us on the App side
2. There’s no breadcrumbs to know the steps taken by the user
3. Since all the stacktrace is native and different everytime, I can’t track down where to look on the javascript side for the problems causing the ANR

I believe that the 3rd is actually something expected but not the other 2. Am I missing something in order to have the correct ids also for ANR’s and their breadcrumbs?

**Comment by marandaneto** [comment]
I believe this is related to #694 as we don't enrich the Android events with the JS contexts (breadcrumbs, user...)

**Comment by marandaneto** [comment]
I'll close this issue as duplicated of #694
About the ApplicationNotResponding thing, we'll keep track of it on the original issue #786
