### ISSUE TITLE
use Hermes cannot find sourcemap

### ISSUE THREAD

**Issue by androidlsl** [getsentry/sentry-react-native#802]
OS:
- [ ]  Windows
- [1 ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [ 1]  Android

SDK:
- [1 ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.61.2

Are you using Expo?
- [ ]  Yes
- [1 ]  No

Are you using sentry.io or on-premise?
- [ 1]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Description goes here ...
![image](https://user-images.githubusercontent.com/15903494/77040211-71c59e00-69f2-11ea-8312-08d383f71812.png)

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by HazAT** [comment]
Please paste a link to your issue here.
Also, how does the stacktrace look like?

**Comment by androidlsl** [comment]
The upload based on sentry.io is the private server of the company, so the link cannot be provided

**Comment by androidlsl** [comment]
Is there one that can display the correct source location with Hermes as I configured? Please show me the demo

**Comment by tobi512** [comment]
Hi @androidlsl, 
we just upgraded to Hermes and can confirm that the sourcemap upload works correctly for us. We only see the error you marked when we forget to upload the sourcemap. So most likely, something with your generation and/or upload is wrong.

**Comment by HazAT** [comment]
So for self hosted Sentry you need to use latest master, this doesn't work with old versions.
