### ISSUE TITLE
Customize release name inside sentry.gradle task?

### ISSUE THREAD

**Issue by ptgamr** [getsentry/sentry-react-native#803]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

Platform:
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 0.0.0
`react-native` version: 0.0.0

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Currently, the default release name generated by the gradle task doesn't match up with the event release name --> source map doesn't work.

Is there a way to customize how the `sentry.gradle` task generate the release name? I can't find anything in the docs.

For example I want to add prefix to the release to distinguish between android release & ios releases:

`android-1.1.128` vs `ios-1.1.129`

**Comment by marandaneto** [comment]
latest versions allow doing it via env. var.

```
export SENTRY_RELEASE="my.custom.release@3.0.0"
export SENTRY_DIST="3"
echo $SENTRY_RELEASE
echo $SENTRY_DIST

Sentry.init({ 
  dsn: '...', 
  release: 'my.custom.release@3.0.0',
  dist: '3',
});
```
