### ISSUE TITLE
Sentry log creates new release with incorrect release name

### ISSUE THREAD

**Issue by akrger** [getsentry/sentry-react-native#805]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.3
`react-native` version: 0.61.5

`@sentry/cli`: 1.51.1,

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [ ]  sentry.io (SaaS)
- [x]  on-premise

Configuration:

```
Sentry.init({ dsn: sentryDSN });
Sentry.setTags({ environment });
Sentry.setRelease(`${nativeVersion}-${bundleVersion}`);
```

The release is created by the following command:
```
./node_modules/.bin/sentry-cli releases files ${NATIVE_VERSION}-${BUNDLE_VERSION} upload-sourcemaps --bundle ./release/main.jsbundle --bundle-sourcemap ./release/main.jsbundle.map --rewrite
```

---
I have following issue:

An issue doesn't get logged to the correct release, which should be of following format:
`{VERSION_CODE}-{BUNDLE_VERSION}`
Example: `12-3`

However, if an error is logged to Sentry, a new release gets created with the following format:
`{APPLICATION_ID}@{VERSION_NAME}+{VERSION_CODE}`
Example: com.example.app@1.12+12
The issue then appears only in this incorrect release.

**Comment by sysadminSafefleet** [comment]
Same here, after `Sentry.init({
    dsn        : APP_SENTRY_DSN,
    release  :  VERSION_NAME
})`
I get on Android and iOS following release tag: {APPLICATION_ID}@{VERSION_NAME}+{VERSION_CODE}

**Comment by khyper** [comment]
Same here, after `Sentry.init({
    dsn        : APP_SENTRY_DSN,
    release  :  VERSION_NAME
})`
I get on Android and iOS following release tag: {APPLICATION_ID}@{VERSION_NAME}+{VERSION_CODE}

**Comment by flp** [comment]
`Sentry.init({ release: ... })` didn't work for me, but `Sentry.setRelease()` did

@akrger you can try to add a `beforeSend` to Sentry.init and log the event's release to help debug

**Comment by tunaSandwich** [comment]
I have the exact same issue. Both `Sentry.init({ release: ... })` and `Sentry.setRelease()` don't seem to work for me. Is there any progress on this?

**Comment by tunaSandwich** [comment]
I finally got this to work by setting a value for `dist`.

```
Sentry.init({
  dsn: ...,
  release: ...,
  dist: ..., // <-- need this!!
});
```
