### ISSUE TITLE
Source code was not found when use latest version 

### ISSUE THREAD

**Issue by androidlsl** [getsentry/sentry-react-native#812]
OS:
- [ ]  Windows
- [ ✔️]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [✔️ ]  Android

SDK:
- [ ✔️]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.6
`react-native` version: 0.61.2

Are you using Expo?
- [ ]  Yes
- [ ]  No

Are you using sentry.io or on-premise?
- [ ]  sentry.io (SaaS)
- [✔️ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

![image](https://user-images.githubusercontent.com/15903494/78012978-5eaeb880-7378-11ea-9fb7-9052cd2b642e.png)

Description goes here ...
i use ./gradlew assembleRelease Upload the android package  
**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by HazAT** [comment]
Can you describe what exactly the problem is and what's breaking for you?
I am not able to tell what the issue right now is.

**Comment by androidlsl** [comment]
As on the graph I posted, I uploaded the sourceMap successfully, but the index.bundle file size was 0, resulting in the incorrect code not being located, prompting sourceCode not find.

I use the./gradlew assembleRelease upload packages

**Comment by androidlsl** [comment]
I just wanted to use the hermes engine, but when I changed to the JSC engine I was able to locate the wrong location and it was all normal, so I guess there were some problems with the hermes switch

**Comment by HazAT** [comment]
Ok, I just saw that you are using on-premise, you need to be on the latest master in order for this to work or use sentry.io.
