### ISSUE TITLE
How to set a release name when using the default "sentry-cli reactnative xcode" build phase 

### ISSUE THREAD

**Issue by lwmouneyrac** [getsentry/sentry-react-native#814]
OS:
- [X]  Windows
- [X]  MacOS
- [X]  Linux

Platform:
- [X]  iOS
- [ ]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.43.0
`react-native` version: 1.3.6

Are you using Expo?
- [ ]  Yes
- [X]  No

Are you using sentry.io or on-premise?
- [X]  sentry.io (SaaS)
- [ ]  on-premise

---
I have following issue:

I am trying to set up my project so people can run Sentry from a dev environment, publish on app center and release on AppStoreConnect without having any risk to overwrite/reupload the sourcemap uploaded during production release. 

By default "sentry-cli react-native xcode" creates a release named VERSION_BUILDNUMBER. 

**Steps to reproduce:**
1- Release your app as 1.0 1000 in production
2- later a dev runs the same version in Xcode after doing some local changes - the dev overwrites the prod sourcemap because xcode Sentry build phase produces the same release name.

I don't know how to change the **"sentry-cli react-native Xcode"** build phase so it **accepts custom release name**?

Or maybe I am missing a Sentry **feature allowing to block overwriting a sourcemap**?

**Comment by lwmouneyrac** [comment]
looking at the source code generating the release, the release name seems to be hardcoded:
https://github.com/getsentry/sentry-cli/blob/master/src/commands/react_native_xcode.rs#L266-L295

I don't understand how it could work with the function setRelease() in the SDK. setRelease() can not be used if we use the default Sentry code build phase generated by the wizard (this build phase will be called by a common Fastlane release which is calling xcodebuild)?

**Comment by lwmouneyrac** [comment]
@HazAT I remember you said we should be using "sentry-cli reactnative xcode" instead of "react-native bundle" / "sentry-cli releases upload-sourcemaps" commands (https://github.com/getsentry/sentry-react-native/issues/790#issuecomment-602449313)

Can you explain what are the additional things done by "sentry-cli reactnative xcode" ? 

It does look like that I would need to go back executing both of these commands but I would like to know what I am missing (but maybe I misread "sentry-cli reactnative xcode" the code - that would be better if I could change the release name from the build phase :)).

**Comment by meznaric** [comment]
We are wondering the same thing:

> Can you explain what are the additional things done by "sentry-cli reactnative xcode" ?

**Comment by marandaneto** [comment]
See https://github.com/getsentry/sentry-react-native/issues/914#issuecomment-963244589
