### ISSUE TITLE
No [task]_SentryUpload running in build process

### ISSUE THREAD

**Issue by nguyenhose** [getsentry/sentry-react-native#815]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.6
`react-native` version: 0.60.3

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---

task: MyEnvRelease_SentryUpload wasn't running in my build process. I debugged Sentry.gradle and it go successfully this line with correct arguments.
https://github.com/getsentry/sentry-react-native/blob/b4984c1b0ee7e2e8a7f74eec22411ea4aa90e94e/sentry.gradle#L130

**Steps to reproduce:**
- Using flavor to build a release ( ex: `./gradlew assembleBetaRelease`)

**Actual result:**
- Build Success, no error was prompted
- Sourcemaps was built but no [task]_SentryUpload running in terminal

**Expected result:**
[task]_SentryUpload should be run and upload sourcemaps to sentry

**Comment by nguyenhose** [comment]
Close it because it not relevant to sentry. My case is configure `org.gradle.configureondemand=true` on gradle.properties.

**Comment by ulion** [comment]
Shouldn't this be documented?
