### ISSUE TITLE
How can I disable certain type of errors from receiving. Ex Error: Failed to connect to.cloudfront.net

### ISSUE THREAD

**Issue by shubhamdeol** [getsentry/sentry-react-native#816]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [X]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61

Are you using Expo?
- [X]  Yes
- [ ]  No

Are you using sentry.io or on-premise?
- [X]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

How can I disable receiving errors like these, and what are these errors:

`
Error: Failed to connect to hdashfjkhasfh.cloudfront.net/2600:9000:21c8:e44:1:9ab43:4380:21:443
`

**Comment by marandaneto** [comment]
that comes from your own app, you can filter events like this https://docs.sentry.io/platforms/react-native/configuration/filtering/
