### ISSUE TITLE
Modal Showing Warning could not connect to sentry native sdk.

### ISSUE THREAD

**Issue by shubhams1497** [getsentry/sentry-react-native#819]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.6
`react-native` version: 0.61.2

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [ ]  sentry.io (SaaS)
- [x]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

I have tried sentry-wizard as well as manual setup by official sentry for android and still i am facing a modal box("_warning could not connect to native sdk..._" ) as soon as sentry.init() is called. Although error events are successfully reflected in the sentry.

**Steps to reproduce:**
- as we do sentry.init() is called then a modal is shown.

**Comment by AndreySukhov** [comment]
following this guide helped for me https://github.com/getsentry/sentry-wizard

**Comment by waqaramjad** [comment]
same issue

**Comment by johnhaup** [comment]
I'm getting this as well.

React Native 0.63.2
 @sentry/react-native ^1.7.2

**Comment by jennmueng** [comment]
@johnhaup This usually means either something is incorrectly configured on the native iOS/Android installation of the SDK or it's being run on something like expo where there is no native module present.

**Comment by marandaneto** [comment]
are you still experiencing this issue when using the latest RN SDK? I can't reproduce it
