### ISSUE TITLE
libswiftFoundation.dylib: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mtt87** [getsentry/sentry-react-native#821]
OS:
- [X]  MacOS

Platform:
- [X]  iOS

SDK:
- [X]  `@sentry/react-native`

SDK version: 1.3.7
`react-native` version: 0.62.2

Are you using Expo?
- [X]  No

Are you using sentry.io or on-premise?
- [X]  sentry.io (SaaS)

---
I have following issue:

I've updated RN to 0.62.x and now I'm getting this error 

```
error: IO error for operation on /Library/Developer/Xcode/DerivedData/xxxxx-gtjjktewjbuhurabwjniovbywpqw/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks/libswiftFoundation.dylib: No such file or directory (os error 2)
```
It used to work correctly not sure what happened.
I followed the RN upgrade tool instructions as usual
https://react-native-community.github.io/upgrade-helper/

**Comment by HazAT** [comment]
Sorry, I am not sure if this issue is related to our SDK.
Please provide a clear description of how to reproduce this.
