### ISSUE TITLE
Proguard(R8) mapping not recognized by Sentry

### ISSUE THREAD

**Issue by rozPierog** [getsentry/sentry-react-native#824]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.60.6

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [ ]  sentry.io (SaaS)
- [x]  on-premise

---
I have following issue:
When I enable obfuscation via `proguard-rules.pro` and send mapping to sentry via 
```shell
../node_modules/@sentry/cli/bin/sentry-cli upload-proguard --android-manifest app/build/intermediates/merged_manifests/<app_flavor>/<abi>/AndroidManifest.xml app/build/outputs/mapping/<app_flavor>/mapping.txt
```
sentry-cli is confirming upload but when I check logs on the site it's still in it's obfuscated form. Is there a React-Native plugin way of doing this, or am I missing something important?

**Steps to reproduce:**
- comment out/remove `-dontobfuscate` from `proguard-rules.pro` in your android react native project
- build release version of the app
- upload mapping to sentry using 
```shell
../node_modules/@sentry/cli/bin/sentry-cli upload-proguard --android-manifest app/build/intermediates/merged_manifests/<app_flavor>/<abi>/AndroidManifest.xml app/build/outputs/mapping/<app_flavor>/mapping.txt
```

**Actual result:**
- code on sentry web UI is obfuscated

**Expected result:**
- code should be deobfuscated using mapping provided by developer

**Comment by marandaneto** [comment]
please integrate our Sentry Android Gradle plugin that does the upload of the proguard mapping file and association of the file and event

https://docs.sentry.io/platforms/android/proguard/
