### ISSUE TITLE
Boolean values in breadcrumb data are not displayed (but are stored)

### ISSUE THREAD

**Issue by benlaverriere** [getsentry/sentry-react-native#825]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.6
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: "https://...@sentry.io/...",
  beforeSend(event, hint) {
    const errorMessage = _.get(hint, "originalException.message");
    if (IGNORED_ERROR_MESSAGES.includes(errorMessage)) {
      return null;
    } else {
      return event;
    }
  },
  beforeBreadcrumb(breadcrumb) {
    if (
      _.includes(["xhr", "fetch"], breadcrumb?.category) &&
      breadcrumb?.data?.url === "https://clients3.google.com/generate_204"
    ) {
      return null;
    }

    return breadcrumb;
  }
});
```

---

This sounds similar to #564 (closed as aged) — boolean values in breadcrumb data are not displayed in the Sentry UI, but are present in the event JSON.

Some examples from our account: [this event][e1] versus [this JSON][j1], or [this event][e2] versus [this JSON][j2]. Some sample properties are `isConnected`, `isCasting`, `isInternetReachable`.

Interestingly, once the data gets deeply nested enough that the whole blob is stringified, everything shows up correctly. (See breadcrumbs with `NetInfo` category, `details` key for examples.)

I don't think we're causing this with any of our preprocessing. Is this a known issue on the frontend? Please let me know if I can provide any additional troubleshooting data as well.

[e1]: https://sentry.io/organizations/chirp/discover/zazu:5023abcb9451401babfd3a06af999a35/?display=releases&field=title&field=event.type&field=project&field=user&field=timestamp&name=All+Events&project=1475820&query=message%3A%22Audiobook+Download+Timeout%22+os.name%3AAndroid&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count_unique%28user%29
[j1]: https://sentry.io/api/0/projects/chirp/zazu/events/5023abcb9451401babfd3a06af999a35/json/
[e2]: https://sentry.io/organizations/chirp/discover/zazu:8329e94999fe46d2b58ba500accc170c/?display=releases&field=title&field=event.type&field=project&field=user&field=timestamp&name=All+Events&project=1475820&query=message%3A%22Audiobook+Download+Timeout%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count_unique%28user%29
[j2]: https://sentry.io/api/0/projects/chirp/zazu/events/8329e94999fe46d2b58ba500accc170c/json/

**Comment by kamilogorek** [comment]
Hey @benlaverriere, this issue is tracked here https://github.com/getsentry/sentry/issues/16637 (as it's not SDK issue). Can you ping the assigned person there? Thanks!

**Comment by benlaverriere** [comment]
Ah sorry about that, @kamilogorek! Will do.
