### ISSUE TITLE
No stacktrace sourcemaps with codepush appcenter

### ISSUE THREAD

**Issue by joan-saum** [getsentry/sentry-react-native#827]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.60.6

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
Hi, I know there are few issues about sourcemap with codepush and appcenter but I am not able to make this correctly working.
So this is how I upload my sourcemap for android (It is same for iOS):
```
sentry-cli react-native appcenter \
  --version-name=$(node -pe "require('./package.json').version") \
  --bundle-id=com.app.* \
    app/android android ./build-android ./build-android/CodePush

```
I have the following code in my App:
```
Sentry.setRelease(`com.app.*-${update.appVersion}-codepush:${update.label}`);
```
Everything as describes in the doc: https://docs.sentry.io/platforms/react-native/codepush/

So when I build the app through appcenter, I can see 2 releases name appear on sentry.io (one for android, one for iOS) as 
```
com.app.*-{VersionApp}-codepush:{VersionCodePush}
```
When checking the Artifacts, I can see the sourcemap there, great.

Few minutes after, another release name appear as 
```
"{VersionApp} (1)"
```
When I hover it with the mouse, it display
```
com.sparted.app@{versionApp}+1
```
And I can see in the artifact the sourcemap for the android.

And few minutes after, 2 anothers release name appear as
```
"{VersionApp} (15830384594)"
```
And when I have my mouse over it, it display
```
com.sparted.app@{VersionApp}+1587735939
```
One contain the sourcemap for iOS, the other contain no artifacts.
Not sure what it is going here but ok.

Now, let's give it a try. With both android & iOS, I launch the app and trigger a crash on purpose
The error is correctly show in the issue in sentry.io and I can see the stackTrace, yeah!
 The release of the issue is displayed as
```
com.sparted.*-{VersionApp}-codepush:{VersionCodePush}
```

But now, If I retry to get the same error, another issue appear in sentry.io, without the strackTrace (with android and with iOS).
What is really strange here, is that both issue (the one with stackTrace, the one without) have exactly the same release name.

You can see here the issue with stackTrace: https://sentry.io/share/issue/ff75018724854640a07ec9a52ac2db3c/
Here the issue without: https://sentry.io/share/issue/efdd6846bdc54f419be9a0ac387b18eb/

**Comment by marandaneto** [comment]
@joan-saum have you tried passing `release` and `dist` in the SDK init? the `release` and `dist` must match otherwise source maps wont work
