### ISSUE TITLE
Not reading .env variables from react-native-config

### ISSUE THREAD

**Issue by sofianegargouri** [getsentry/sentry-react-native#831]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.62.2

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
I have following issue:

- I have sentry setup via env variables with react-native-config:

```
SENTRY_DSN=
SENTRY_ORG=
SENTRY_PROJECT=
SENTRY_AUTH_TOKEN=
SENTRY_URL=
```

- react-native-config adds my Sentry env variables in the project.env. If I do `print(project.env)` in the `app/build.gradle`. When I run `(cd android; ENVFILE=.env.production ./gradlew bundleRelease)`

```
Reading env from: .env.production
{SENTRY_DSN=****, SENTRY_ORG=****, SENTRY_PROJECT=****, SENTRY_AUTH_TOKEN=****}
```

**Actual result:**

```
error: An organization slug is required (provide with --org)
```

It works fine if I run:

`export $(egrep -v '^#' .env.production | xargs); (cd android; ENVFILE=.env.production ./gradlew bundleRelease)`

**Expected result:**

Sentry should build correctly

**Comment by xgenem** [comment]
How did it go for you sir @marandaneto ?

**Comment by marandaneto** [comment]
did you setup using the Sentry wizard process? https://docs.sentry.io/platforms/react-native/
maybe @jennmueng can help out here.

**Comment by jennmueng** [comment]
I personally don't have much experience working with gradle build scripts. This is the script that would be run on build time: https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle

It looks like it's expecting a `sentry.properties` file and not reading in environment variables? Feel free to guide me on this or submit a PR.

**Comment by makedirectory** [comment]
I can confirm this occurs on iOS too if you are using multiple .env files. Sentry only wants to read from the main .env file even if another configuration is specified

**Comment by marandaneto** [comment]
afaik sentry tries to read from `sentry.properties` or the system env. var.
if by `react-native-config` you mean https://github.com/luggit/react-native-config we probably don't support it, is it a feature request then?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
