### ISSUE TITLE
Android Source Map after CodePush with Hermes enabled

### ISSUE THREAD

**Issue by zhigang1992** [getsentry/sentry-react-native#832]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: "^1.3.7"
`react-native` version: "0.62.2"

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

https://sentry.io/organizations/tappollo/issues/1637613002/?project=5216652&sort=new

Configuration:

---
I have following issue:

Build for android work fine including source map.

But it stopped working after codepush

![image](https://user-images.githubusercontent.com/1057756/80617265-79a64280-8a74-11ea-87a1-898f3e224d83.png)

Follow the same guide as iOS and iOS works just fine.

source map is there in release artifact, same name as before the codepush.

**Comment by shangyilim-hubble** [comment]
I'm having the same issue with as above. Without codepush, no sourcemap errors are present. After a codepush release and following the guide, the same issue happens to me ask well: https://sentry.io/share/issue/f79ea8ee329f420ab3a79ff10cc836c3/

**Comment by MathieuUrstein** [comment]
I'm having the same problem. It seems like the stack-trace points to an empty file.
![image](https://user-images.githubusercontent.com/3322861/98182221-8b761000-1f05-11eb-9e88-37ec920688a1.png)
![image](https://user-images.githubusercontent.com/3322861/98182278-af395600-1f05-11eb-8da9-28177f4346a6.png)

If you look at your matching release artifacts, does your `index.android.bundle` file also is `0B`?
![image](https://user-images.githubusercontent.com/3322861/98182374-e445a880-1f05-11eb-965d-76ec7e313f00.png)

Seems only to happen when Hermes is enabled.

**Comment by crushy26** [comment]
+1

**Comment by jennmueng** [comment]
See: https://github.com/getsentry/sentry-react-native/issues/1270, closing this and consolidating into the mentioned issue.
