### ISSUE TITLE
Google Play Blocker: Unsafe HostnameVerifier Defined

### ISSUE THREAD

**Issue by subinkrishna** [getsentry/sentry-react-native#833]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.2.1
`react-native` version: 0.61.4

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---

We did a DataTheorem scan of our app and it identified unsafe implementation & HostnameVerifier

> The following classes within the App define an [insecure HostnameVerifier](https://developer.android.com/reference/javax/net/ssl/HostnameVerifier.html#verify(java.lang.String,%20javax.net.ssl.SSLSession))) that disables SSL hostname validation:
> 
> `io.sentry.connection.HttpConnection$1`

Regardless of whether the affected classes are actually used at runtime or not, Google Play is blocking any App that defines such an insecure `HostnameVerifier`, as detailed on  [Google’s support page](https://support.google.com/faqs/answer/7188426) :

> “Beginning March 1, 2017, Google Play will block publishing of any new apps or updates that use an unsafe implementation of HostnameVerifier.”

**Comment by marandaneto** [comment]
dup of getsentry/sentry-java/issues/840
