### ISSUE TITLE
Sentry.Integrations.CaptureConsole is undefined

### ISSUE THREAD

**Issue by bitttttten** [getsentry/sentry-react-native#839]
OS:
- [x ]  MacOS

Platform:
- [x ]  iOS
- [ x]  Android

SDK:
- [x ]  `@sentry/react-native`

SDK version: expo v37
`react-native` version: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz

Are you using Expo?
- [x ]  Yes
- [ ]  No

Are you using sentry.io or on-premise?
- [ x]  sentry.io (SaaS)

Configuration:

```
Sentry.init({
	dsn: "",
	enableInExpoDevelopment: false,
	debug: true,
	integrations: [
		new Sentry.Integrations.CaptureConsole({
			levels: ["log", "warn", "error"],
		}),
	],
})
```

---
I have following issue:

I am trying to log console.error and console.warm to sentry, although from the docs I see that I need to configure integrations as above. Although I get the error:

"CaptureConsole: undefined is not a consrtuctor"

Perhaps this is not the proper way to log console.error messages to Sentry, so it could be my config is totally wrong!

**Expected result:**
That I would be able to log console errors and console warn issues to sentry.

**Comment by GoshaEgorian** [comment]
I have exact the same issue: CaptureConsole is not defined. Also it's not exist in sentry-rn module folder. Was it removed?

**Comment by connorads** [comment]
Do you need to include the [@sentry/integrations](https://www.npmjs.com/package/@sentry/integrations) package?


Example:
`$ yarn add @sentry/integrations`
```
import { CaptureConsole } from "@sentry/integrations";

Sentry.init({
	dsn: "",
	enableInExpoDevelopment: false,
	debug: true,
	integrations: [
		new CaptureConsole({
			levels: ["log", "warn", "error"],
		}),
	],
})
```

**Comment by bitttttten** [comment]
I didn't know it was available on there @connorads !  Thanks :) I will try it out.

**Comment by jennmueng** [comment]
Yes it should be under `@sentry/integrations`. The `Sentry.Integrations` export from `@sentry/react-native` only contains react-native specific integrations. For browser integrations it would be under `Sentry.BrowserIntegrations`. For any other integration you would need `@sentry/integrations`.

**Comment by Sameer-Ijaz** [comment]
Basically Capture Console was depreciated, you might have upgraded your sentry as well. You have to use an alternative approach for it. https://www.youtube.com/watch?v=QmD2S0mBJ9U&feature=youtu.be
