### ISSUE TITLE
task bundleReleaseJsAndAssets_SentryUpload not run.

### ISSUE THREAD

**Issue by ulion** [getsentry/sentry-react-native#841]
OS:
- [ ]  Windows
- [*]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [*]  Android

SDK:
- [*]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: @sentry/react-native: 1.3.7
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [*]  No (but it's installed)

Are you using sentry.io or on-premise?
- [*]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue: bundleReleaseJsAndAssets_SentryUpload not get run. 

Description goes here ...

bundleReleaseJsAndAssets_SentryUpload not get run even it's scheduled run after bundleReleaseJsAndAssets by the finalizedBy code (traced by IntelliJ IDEA so the finalizedBy line did run).
./gradlew tasks can list task bundleReleaseJsAndAssets_SentryUpload, but it's gone when really run ./gradlew assembleRelease
with --info got the "Sentry-CLI arguments" line printed, but when really run those tasks, bundleReleaseJsAndAssets_SentryUpload is missing though bundleReleaseJsAndAssets did run.

so there must be something happened which caused the task created, and hooked, but not finally run. I'm not familar with gradle and android system, so any idea what could cause this?

**Actual result:**
- bundleReleaseJsAndAssets_SentryUpload is not run, source map is not uploaded

**Expected result:**
- bundleReleaseJsAndAssets_SentryUpload is run after bundleReleaseJsAndAssets, and source map uploaded.

**Comment by ericmatte** [comment]
@ulion I had the same problem, and removing `org.gradle.configureondemand=true` in `gradle.properties` fixed it.
https://github.com/getsentry/sentry-react-native/issues/815#issuecomment-610977587

**Comment by ulion** [comment]
@ericmatte Thank you for notify. that's quite a hidden configuration. This should be documented in case user inactivite the upload by accident.

**Comment by pranshuchittora** [comment]
I experienced the same issue today while trying to build android
`FAILED bundleReleaseJsAndAssets_SentryUpload`

running `npx react-native clean` (and selecting all), fixed the issue.
