### ISSUE TITLE
Changing projects does not upload source map anymore

### ISSUE THREAD

**Issue by remigallego** [getsentry/sentry-react-native#843]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [X]  iOS
- [X]  Android

SDK:
- [X]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.62.2

Are you using Expo?
- [ ]  Yes
- [X]  No

Are you using sentry.io or on-premise?
- [X]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I set up Sentry with React Native and everything was fine. 

I had to change the project to use my client's organization, and since then the source maps do not upload anymore. 

I changed the DSN link as well as the sentry.properties file.
After I noticed that I wouldn't get the source maps, I tried to completely reinstall Sentry and run the `npx sentry-wizard` again. This did not help.

With Android, I do not see any `uploadSentry` job when using `./gradlew assembleRelease`.
With iOS, I do see the notifications "Upload debug symbols to Sentry" but nothing is there when I check the Artifacts section on my Sentry Releases section.

Any help appreciated!

**Comment by MahmonirB** [comment]
same issue.
I set up new RN 0.62.2 project.
- Hermes: true
- Code push
but it doesn't upload source map to sentry.

**Comment by tlow92** [comment]
Same Problem. 
Anyone found the reason for that? Happened when updating sentry-react-native. When building development release everything works fine, on release no artifacts get uploaded.

**Comment by marandaneto** [comment]
does it still happen on the latest Sentry RN SDK? I can't reproduce it, if I rebuild android and ios, I see source maps coming thru.
