### ISSUE TITLE
Sentry.nativeCrash() on iOS creates a new release

### ISSUE THREAD

**Issue by piotrmitrega** [getsentry/sentry-react-native#844]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [ ]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

When I trigger Sentry.nativeCrash() on iOS, it automatically creates new release with a format com.example.myapp-1.2.0.

![image](https://user-images.githubusercontent.com/42134731/81557964-23e36b80-938d-11ea-8cdd-6a1095f6c955.png)

I checked and proper version and dist are sent with issue, but it for some reason got assigned to this magically created release. Is this Sentry bug or am I missing something?

**Expected result:**
- Crash should be assigned to existing release `1.2.0 (51)`

**Comment by bruno-garcia** [comment]
It's using the native SDK to capture the error which builds it in a different format.
We're aligning them so they look the same.

**Comment by retyui** [comment]
Any news?

**Comment by retyui** [comment]
Any updates

**Comment by bruno-garcia** [comment]
The release set via JS should flow to the iOS SDK. Are you initializing the iOS SDK separately?
Could you please provide a repro?

**Comment by retyui** [comment]
Just tested on :
- sentry.javascript.react-native@1.9.0
- sentry.cocoa@5.2.2


It works fine, issue can be closed )

**Comment by jennmueng** [comment]
Yeah this issue should've been closed a while ago as we sync the value up as well.
