### ISSUE TITLE
Android stack trace and errors are not displayed 

### ISSUE THREAD

**Issue by Mohamed-Abbas** [getsentry/sentry-react-native#853]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.9

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
[Link to issue](https://sentry.io/organizations/henryhealth/issues/1674743813/?project=5245882)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```
---
**I have following issue:**

Android stack trace not showing up on release and debug builds, i can confirm that source maps files are uploaded, release and distributions matches correctly. For IOS it is working as expected.
  
<img width="840" alt="Screen Shot 2020-05-19 at 12 25 07 PM" src="https://user-images.githubusercontent.com/26598024/82315646-e35aa200-99cb-11ea-977d-c946e69568aa.png">

**Steps to reproduce:**
Add the following code
`setTimeout(() => {
      throw new Error('first error');
    }, 30000);`    
**Actual result:**
stack trace shows Thread Errored

**Expected result:**

stack trace should be available along with source code responsible for the error

**Comment by marandaneto** [comment]
#866

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-react-native/releases/tag/1.4.0
