### ISSUE TITLE
Can you bump android native SDK to 2.1.2?

### ISSUE THREAD

**Issue by farwayer** [getsentry/sentry-react-native#854]
To fix crash on androids with old APIs https://github.com/getsentry/sentry-android/issues/413

**Comment by Ananthakr** [comment]
@marandaneto Will this change be part of next release and when can we expect that?

**Comment by marandaneto** [comment]
@Ananthakr yes, it'll.

Meantime you can upgrade `sentry-android` by yourself, right?

eg `{project}/node_modules/@sentry/react-native/android/build.gradle` and look up for `'io.sentry:sentry-android:{version}'` and bump it.

I don't make releases for `sentry-react-native` but tagging who does.

cc @HazAT

**Comment by marandaneto** [comment]
the newest version is `2.1.3` btw https://github.com/getsentry/sentry-android/releases/tag/2.1.3

**Comment by bruno-garcia** [comment]
#858 was raised. Let's merge that and make a release here.
