### ISSUE TITLE
Invalid location in sourcemap, android, hermes, codepush

### ISSUE THREAD

**Issue by rarira** [getsentry/sentry-react-native#874]
**OS:**
- [ ]  Windows
- [*]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [*]  Android

**SDK:**
- [*]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.9

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [* ]  No

**Are you using sentry.io or on-premise?**
- [*]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/rarira-studio/issues/1687283387/?project=1868470&query=is%3Aunresolved

**Configuration:**

(`@sentry/react-native`)
```
if (!__DEV__) {
  Sentry.init({
    dsn: SENTRY_DSN,
    ignoreErrors: ['No current user', 'not authenticated'],
    debug: true,
    beforeSend: e => {
      if (!e.tags) {
        e.tags = {};
      }
      e.tags['beforeSend'] = 'JS layer';
      return e;
    },
    enableAutoSessionTracking: true,
  });
  Sentry.setRelease(BUNDLE_ID + '@' + VERSION + '+' + BUILD_NUMBER);
  Sentry.setDist(BUILD_NUMBER);
}

      codePush
        .getUpdateMetadata()
        .then(update => {
          if (update) {
            Sentry.setRelease(BUNDLE_ID + '-' + update.appVersion + '-codepush:' + update.label);
          }
        })
        .catch(err => {
          Sentry.setRelease(BUNDLE_ID + '@' + VERSION + '+' + BUILD_NUMBER);
        });
```

---
**I have following issue:**
There is no issue with IOS and android with no codepush update 
but when with codepush updated,
There are 3 artifacts uploaded with the release,
but the size of index.android.bundle is 0B

**Actual result:**

and have error
Invalid location in sourcemap
app:///index.android.bundle

**Expected result:**

[Expected result]

**Comment by ahartzog** [comment]
Also seeing this, just updated to @sentry/react-native 1.4.1 hoping to resolve but still having a 0b index.android.bundle

![image](https://user-images.githubusercontent.com/9828263/83179234-bacf5800-a0ef-11ea-96b8-bcc47266663c.png)

![image](https://user-images.githubusercontent.com/9828263/83179275-ca4ea100-a0ef-11ea-9718-ac7b02d6676a.png)

**Comment by marandaneto** [comment]
@jennmueng would you mind testing this with the latest version when you have some free time? I don't have much experience with code push

**Comment by rarira** [comment]
> @jennmueng would you mind testing this with the latest version when you have some free time? I don't have much experience with code push

I tried with the latest version 1.6.1 but failed with different result
https://sentry.io/share/issue/d155f7425d194f948f7f2ceb08d5da10/

**Comment by shangyilim-hubble** [comment]
I am also having this issue on latest version.
sentry-cli: 1.55.1
@sentry/react-native : "^1.7.1"

Are there any updates?

**Comment by danmaas** [comment]
I am seeing this same "Invalid location in sourcemap" error, sample issue: https://sentry.io/organizations/coreplane-inc/issues/1907865900/?project=1489478

My sourcemaps appear to be uploaded correctly for Hermes + CodePush. Here are the sourcemaps for the release: https://sentry.io/settings/coreplane-inc/projects/badukpop/source-maps/com.coreplane.badukpop.prod-1.20.0-codepush%3Av156/

**Comment by danmaas** [comment]
The above-mentioned fixes worked for me! :)

Basically, in my CodePush release script, between the `appcenter codepush release-react` step and the `sentry-cli react-native appcenter` step, I added these commands:

```
# rename incomplete JavaScript bundle map to .intermediate.map
mv build/CodePush/index.android.bundle.map build/CodePush/index.android.bundle.intermediate.map
# run compose-source-maps.s to merge the incomplete intermediate map with the Hermes map
node node_modules/react-native/scripts/compose-source-maps.js build/CodePush/index.android.bundle.intermediate.map build/CodePush/index.android.bundle.hbc.map -o build/CodePush/index.android.bundle.map
```

**Comment by rarira** [comment]
> The above-mentioned fixes worked for me! :)
> 
> Basically, in my CodePush release script, between the `appcenter codepush release-react` step and the `sentry-cli react-native appcenter` step, I added these commands:
> 
> ```
> # rename incomplete JavaScript bundle map to .intermediate.map
> mv build/CodePush/index.android.bundle.map build/CodePush/index.android.bundle.intermediate.map
> # run compose-source-maps.s to merge the incomplete intermediate map with the Hermes map
> node node_modules/react-native/scripts/compose-source-maps.js build/CodePush/index.android.bundle.intermediate.map build/CodePush/index.android.bundle.hbc.map -o build/CodePush/index.android.bundle.map
> ```

@jennmueng @danmaas it works as expected

**Comment by jennmueng** [comment]
Looks like we can close this then, we'll look into adding this to the official documentation

**Comment by v-anton** [comment]
Hi @ahartzog Have you resolved the issue with 0B index.android.bundle ?
I have the same

**Comment by danmaas** [comment]
Just an update, as of appcenter-cli version 2.10.0 and later, AppCenter now takes care of running compose-source-maps. So the work-around in my comment above is no longer necessary.

**Comment by kopax-polyconseil** [comment]
Hello, we struggle to get proper sourcemap with a similar setup : react native ios and Android, hermes, appcenter. 

Our sourcemaps use the same process as for our hard build and each codepush have a unique release and dist pair.

The manually generated sourcemaps works very well without codepush, but with codepush, it shows wrong line number. 

We are using latest versions of sentry sdk7, and latest version of sentry self hosted. 

Could you please share us how you did successfully configured sourcemaps and code push with sentry ?

What part of the doc did you follow and are the steps to build sourcemaps are different than when doing native hard build ? 

Thanks for sharing.
