### ISSUE TITLE
Is it possible to trace with sentry react native?

### ISSUE THREAD

**Issue by purnadi-winarno** [getsentry/sentry-react-native#878]
is it possible to using trace feature with sentry-react-native?

I've refering to this docs, https://docs.sentry.io/performance/distributed-tracing/?_ga=2.265309519.1743835574.1590125024-728349013.1582691628#javascript

but it causes errors when I have integrations field on Sentry.init

**Comment by marandaneto** [comment]
hey @purnadi-winarno thanks for raising this.

we've never tested on a react-native app, so not sure if it'd work ootb, I'll tag it as a feature request, but please share the error and logs, thanks.

**Comment by barakd** [comment]
I tired to do so, initially it's fails on this line
https://github.com/getsentry/sentry-javascript/blob/c4a5e742fee949140805d9956c8dbc90a0beb299/packages/tracing/src/browser/browsertracing.ts#L235
but a simple if statement is working to get it started.
Afterads I don't have any errors, but wasn't able to get performance events reported to Sentry.

While debugging I can see it is starting the network instrumentations and can see all the events, but it's seems we don't get initial transactions so non of the requests are recorded,
(when there is document the on load triggers the first event I belive)
I wasn't able to figure it out, but if you can point me to any leads I'll be more than happy to keep searching and open a PR.

**Comment by andrewhorst-wellio** [comment]
I am able to get a `transaction` to work, but not child `span`s. 

In `App.tsx` I import the module and then include some NOOP code that makes sure it doesn't get compiled out. Don't actually add the integration--as @barakd writes, this fails when it looks for `document`.
```javascript
import * as Sentry from '@sentry/react-native';
// https://docs.sentry.io/platforms/javascript/performance/#enabling-tracing
// import { Integrations as TracingIntegrations } from '@sentry/tracing';
import { Integrations as TracingIntegrations } from '@sentry/apm';

...
Sentry.init({
      dsn: 'DSN...',
      environment: UltimateConfig.SENTRY_ENVIRONMENT,
      enableAutoSessionTracking: true,
      //integrations: [new TracingIntegrations.BrowserTracing()],
      tracesSampler: (samplingContext) => {
        console.log(samplingContext);
        return 1.0;
      },
      tracesSampleRate: 1.0, //0.25,
    });
try {
  //const _ = TracingIntegrations.BrowserTracing;
  const _ = !TracingIntegrations.Tracing;
  console.log(_);
} catch (e) {
  console.log(e);
  // NOOP
}
```

Then in a functional component, a simple transaction works:
```javascript
import * as SentryB from '@sentry/browser';

const Detail = (...) => {
  useEffect(() => {
    const t: Transaction = SentryB.startTransaction({ name: "TestTransaction" });
    t.finish();
  }, []);

  return ...
};
```
`TestTransaction` is reported in the Discover and Performance sections.

However, adding a childSpan does not work; neither the child nor the transaction is reported:
```javascript
import * as SentryB from '@sentry/browser';

const Detail = (...) => {
  useEffect(() => {
    const t: Transaction = SentryB.startTransaction({ name: "TestTransaction_WithChild" });
    const span = t.startChild({ op: 'TestChild' });
    span.finish();
    t.finish();
  }, []);
};
```

Stepping through, I found one possible problem: 
At https://github.com/facebook/react-native/blob/4409642811c787052e0baeb92e2679a96002c1e3/Libraries/BatchedBridge/MessageQueue.js#L299
it infinitely recurses and eventually silently throws MaxStackDepth Exceeded.
The `spanRecorder` and `transaction` from the child span form a cycle for https://github.com/facebook/react-native/blob/4409642811c787052e0baeb92e2679a96002c1e3/Libraries/BatchedBridge/MessageQueue.js#L271 .
This results in a RN error that the params are not the same size (
https://github.com/facebook/react-native/blob/4409642811c787052e0baeb92e2679a96002c1e3/Libraries/BatchedBridge/MessageQueue.js#L245
and
https://github.com/facebook/react-native/blob/4409642811c787052e0baeb92e2679a96002c1e3/Libraries/BatchedBridge/MessageQueue.js#L246
don't match
https://github.com/facebook/react-native/blob/4409642811c787052e0baeb92e2679a96002c1e3/Libraries/BatchedBridge/MessageQueue.js#L308
)

If I delete childSpan.spanRecorder and childSpan.transaction, the error is resolved. But the transaction and child are still not shown in the Sentry web UI (Discover / Performance).

Transactions do work after this transaction + childSpan call, e.g.
```javascript
const trans0 = SentryB.startTransaction({ name: "Trans0" });
trans0.finish();

const transWithChild = SentryB.startTransaction({ name: "TransWithChild" });
const span = transWithChild.startChild({ op: 'TestChild' });
span.finish();
transWithChild.finish();

const trans1 = SentryB.startTransaction({ name: "Trans1" });
trans1.finish();
```
`Trans0` and `Trans1` are shown in the Sentry web UI, but not `TransWithChild`.

The JSON looks reasonable to me:
```json
"{
  "contexts": {
    "trace": {
      "span_id": "b7c9da95baef0768",
      "trace_id": "f1cd28a005004fe193dafce54f69635a"
    }
  },
  "spans": [],
  "start_timestamp": 1603747096.592968,
  "tags": {},
  "timestamp": 1603747106.2495801,
  "transaction": "Trans0",
  "type": "transaction"
}"
```
vs
```json
"{
  "contexts": {
    "trace": {
      "span_id": "853601d1203a9c46",
      "trace_id": "6e319bd193e9415483e0f55a663b64c2"
    }
  },
  "spans": [
    {
      "op": "TestChild",
      "parent_span_id": "853601d1203a9c46",
      "span_id": "9d86525bff2fc157",
      "start_timestamp": 1603747233.7499478,
      "timestamp": 1603747349.404034,
      "trace_id": "6e319bd193e9415483e0f55a663b64c2"
    }
  ],
  "start_timestamp": 1603747233.1996453,
  "tags": {},
  "timestamp": 1603747366.3492434,
  "transaction": "TransWithChild",
  "type": "transaction"
}"
```


In a React web app, the JSON looks equivalent. Note there is not the `spanRecorder` circular reference problem.
```json
"{
  "contexts": {
    "trace": {
      "span_id": "8993b400b9741115",
      "trace_id": "6be53f10c08347fdaf16ddd89f13eaf5"
    }
  },
  "spans": [],
  "start_timestamp": 1603756107.486299,
  "tags": {},
  "timestamp": 1603756133.299969,
  "transaction": "TestData",
  "type": "transaction"
}"
```
vs
```json
"{
  "contexts": {
    "trace": {
      "span_id": "96bcc932a0028d3d",
      "trace_id": "f8d25ae6c8b74b0cbc017d15652df14f"
    }
  },
  "spans": [
    {
      "op": "child-span",
      "parent_span_id": "96bcc932a0028d3d",
      "span_id": "9ba41a658543dfdc",
      "start_timestamp": 1603756193.880919,
      "timestamp": 1603756236.405469,
      "trace_id": "f8d25ae6c8b74b0cbc017d15652df14f"
    }
  ],
  "start_timestamp": 1603756193.8807442,
  "tags": {},
  "timestamp": 1603756251.1367738,
  "transaction": "ShortTest",
  "type": "transaction"
}"
```
Both are shown in Sentry.

Any suggestions on what else to check?

**Comment by jennmueng** [comment]
@barakd @andrewhorst-wellio The react native SDK `<2.x` won't be able to support tracing as it needed a change on how events are sent and received from the SDK. We've made these changes to support tracing already on the master branch and are waiting on a fix on our backend before we can release `2.x`. We will also officially add tracing/performance support soon.

Let's close this issue and consolidate tracing/performance into a single issue over here: https://github.com/getsentry/sentry-react-native/issues/971
