### ISSUE TITLE
Tag for where crash originated

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-react-native#881]
# Motivation
Currently, it's hard to tell/filter in Sentry where a crash originated. 
Did it occur in JS, iOS/Android or even NDK?

We send already a bunch of tags:
![image](https://user-images.githubusercontent.com/363802/83006518-a1a4a980-a012-11ea-805e-28c336c2697e.png)

One new tag we should add is `crash.origin`
With a few potential values:
`javascript`
`ios`
`android`
`ndk`

to be able to filter events in the Sentry UI for exactly just those crashes.

**Comment by bruno-garcia** [comment]
Two suggestions:

1. not having either `android` or `ndk` but having always `android` and a second tag to mark `ndk`. This way one can filter all Android events (regardless if from Java/NDK).

2. Tag the SDK name instead?

`sentry.javascript.react-native`
`sentry.cocoa`
`sentry.java.android`
`sentry.native`

**Comment by marandaneto** [comment]
liked @bruno-garcia s idea, so one can filter on a high or low level.
tag's name could be `even.origin` instead of `crash.origin` as not every event is a crash.

**Comment by jennmueng** [comment]
I agree with `event.origin` over `crash.origin` and did actually implement that in the commit. Didn't mention it here, my bad.

**Comment by marandaneto** [comment]
@jennmueng can we close this? #890 is released

**Comment by jennmueng** [comment]
Yes!
