### ISSUE TITLE
iOS source map is not linked: "Source code was not found"

### ISSUE THREAD

**Issue by poocart** [getsentry/sentry-react-native#888]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.8

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
const dist = DeviceInfo.getBuildNumber();
const release = `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${dist}`;
Sentry.init({ dsn: SENTRY_DSN, release, dist });
Sentry.setRelease(release);
Sentry.setDist(dist);
Sentry.setTags({ environment: BUILD_TYPE });
```

---
**I have following issue:**

iOS React Native bundled JS source map is uploaded to Sentry during build time, I and it's attached to version specified in `release`, but once crash happens the Sentry report says "Source code was not found" and therefore crash is not linked to any source map even though the report shows that it's linked to the Sentry release that has source map uploaded. Android is totally fine.

**Steps to reproduce:**
- Upload iOS React Native bundled JS source map to Sentry during build time.
- Have a crash.

**Actual result:**

iOS Sentry report doesn't have React Native bundled JS source map linked.

**Expected result:**

iOS Sentry report has React Native bundled JS source map linked.

**Comment by jennmueng** [comment]
@poocart Can you send a screenshot of the artifacts tab of that release? I would like to see if it is set up correctly.

You can do this by going to the "Releases" tab, then clicking on the name of that specific release, then navigate to the "Artifacts" tab.

**Comment by dotconnor** [comment]
Hey I'm also running into this issue. I've noticed that while the CLI does in fact send the artifacts to `sentry.io`, nothing appears under the Artifacts tab.

**Comment by cruzach** [comment]
@jennmueng here's a screenshot (I'm running into the same issue on v2.1.0). You can see that the Android artifacts were uploaded, but no iOS ones:

<img width="1410" alt="Screen Shot 2021-02-20 at 4 31 59 PM" src="https://user-images.githubusercontent.com/35579283/108609069-6cf33200-7399-11eb-9545-002be8d13249.png">

My iOS build's `release` and `distribution` match that release, as well: 
<img width="458" alt="Screen Shot 2021-02-20 at 4 32 06 PM" src="https://user-images.githubusercontent.com/35579283/108609068-6c5a9b80-7399-11eb-8575-3bb823429760.png">

Thanks for taking the time to look into this 🙏

**Comment by marandaneto** [comment]
```
const dist = DeviceInfo.getBuildNumber();
const release = `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${dist}`;
Sentry.init({ dsn: SENTRY_DSN, release, dist });
Sentry.setRelease(release);
Sentry.setDist(dist);
```

the `release` and `dist` of the event and source maps should match otherwise it does not work, the RN SDK already sets and release and dist and also upload source maps automatically, any reason why are you setting custom release and dist on `init` and also calling `Sentry.setRelease` and `Sentry.setDist`? do they match? can you link me to a sentry.io issue? thanks

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
