### ISSUE TITLE
captureException, captureMessage not working on Android

### ISSUE THREAD

**Issue by ZachMayry** [getsentry/sentry-react-native#913]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.2, tried 1.3.7 with no difference

**`react-native` version:** 0.60.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have following issue:**

Android doesn't seem to be reporting javascript errors to sentry.
iOS works just fine.

**Steps to reproduce:**
- Step 1: Create some buttons onPress handlers like so: 
```js
  onTestError = () => {
    Sentry.captureException(new Error('test error'))
    Sentry.captureMessage('hi')
  }

  onTestCrash = () => {
    Sentry.nativeCrash()
  }
...
...
        <Button onPress={this.onTestError} title="Test error" />
        <Button onPress={this.onTestCrash} title="Test crash" />
```
- Step 2: Click button handlers in a release bundle

**Actual result:**
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/12666484/83839287-43865f00-a6c1-11ea-89ba-497aabb6b4b5.png">

**Expected result:**
Should show something like this: (this is what I get with iOS)
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/12666484/83838949-35840e80-a6c0-11ea-9953-88de9cbd51e5.png">

**Comment by marandaneto** [comment]
hey @ZachMayry thanks for raising this

could you enable the `debug` mode and copypasta the logs, please? thanks.

**Comment by ZachMayry** [comment]
Looks like they were coming in after all 
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/12666484/83886576-dd272e00-a70c-11ea-95b4-2cf238b43597.png">

**Comment by williamgurzoni** [comment]
Hello @ZachMayry how did you manage to make it working on Android? I'm having the same problem. Thank you.

**Comment by ZachMayry** [comment]
@williamgurzoni
I believe the messages are stored locally on the device like breadcrumbs. Then when an exception or crash happens, everything is sent to the server. So when you open the exception, you’ll see all the messages.

**Comment by anhquan291** [comment]
I'm facing the same issue. The captureException, captureMessage are only working in useEffect or componentDidMount. With the normal function try catch block, it doesn't work evenwhen I still get the event Id. 
Everything works fine on iOS. Any help please. 
` const enventid = Sentry.captureMessage("Error at Dashboard ");
    console.log("Error at Dashboard", enventid);`
