### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Sentry.captureBreadcrumb')

### ISSUE THREAD

**Issue by nihp** [getsentry/sentry-react-native#923]
I have upgraded to @sentry/react-native latest version with react-native version 0.62.2.

Already I am using react-native-sentry package with react-native version 0.59.9 it works fine.

After the upgrade, I have changed the import alone and run pod install. After bundle success `evaluating '_reactNative.Sentry.captureBreadcrumb'`. How to fix this?

My question is while upgrading sentry from react-native-sentry to @sentry/react-native and with the latest version of RN (0.62.2) shall I need to a setup wizard as mentioned here `yarn sentry-wizard -i reactNative -p ios android` https://docs.sentry.io/platforms/react-native/#linking.

**Comment by jennmueng** [comment]
Hello @nihp, the method has changed to `Sentry.addBreadcrumb(..)` from `Sentry.captureBreadcrumb(..)` among others. You would need to go through your app and update the methods to the latest spec.

**Comment by nihp** [comment]
Can you give any documentation for this for react-native. What are the changes and modification.

**Comment by nihp** [comment]
Changed as addBreadcrumb(). Again getting the same error.
[TypeError: undefined is not an object (evaluating '_reactNative.Sentry.addBreadcrumb')]
![Simulator Screen Shot - iPhone 8 - 2020-06-10 at 10 26 38](https://user-images.githubusercontent.com/36992338/84228524-e3e6e400-ab04-11ea-86ce-57761fd9e5fd.png)

**Comment by nihp** [comment]
Fixed the above by adding the Sentry.addBreadcrumb().
