### ISSUE TITLE
TypeError: k.startWithDsnString

### ISSUE THREAD

**Issue by tilonet** [getsentry/sentry-react-native#924]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.8

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'xy.'
  //NO other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

Only on debug builds on both platforms ios and android get directly on app start TypeError: k.startWithDsnString is not a function
![BugAppStart](https://user-images.githubusercontent.com/25120666/84234264-2e139980-aaf4-11ea-8301-5dff9666d6c4.png)

Tested with emulator/simulator and physical devices and Browserstack devices

**Steps to reproduce:**
- Step 1 build app
- Step 2 start

**Actual result:**

app crash

**Expected result:**

app starts

**Comment by jennmueng** [comment]
Can you please update to the latest `1.4.5` and run the sentry wizard in the install instructions here: https://docs.sentry.io/platforms/react-native/ and let me know if the issue persists?

**Comment by tilonet** [comment]
Thanks for the reply, i did the update and and the wizard succeeded but the issue still exist

**Comment by jennmueng** [comment]
How are you initializing the SDK, can I see the full `Sentry.init` call, and have you tried deleting `node_modules` and doing an install from scratch? What's happening there is its trying to call a function that no longer exists, we removed `startWithDsnString` in `1.4.0`

**Comment by tilonet** [comment]
sorry was a caching problem, the startWithDsnString call still exists in the bundle files.
the update fixed the issue, thank you very much for the fast help

**Comment by yusufdeepwork** [comment]
I get issue again I couldnt find a solution
