### ISSUE TITLE
Source maps missed on iOS/Android with CodePush

### ISSUE THREAD

**Issue by stas-kravchuk** [getsentry/sentry-react-native#928]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.7

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/share/issue/c8f6f53e1a334780b739462f016d22b6/
https://sentry.io/share/issue/2454feed2c504dd898ada7ed16e05847/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
            dsn: config.sentryDsn,
            ignoreErrors: [
                'Non-Error exception captured',
            ],
        })
        codePush.getUpdateMetadata().then(update => {
            if(update) {
                Sentry.setRelease(update.appVersion + '-codepush:' + update.label)
            }
        })
```

---
**I have following issue:**

I'm facing strange behavior with source maps in senty.io dashboard. When I making just a normal production build for Testflight or PlayMarket everything works fine, source maps uploading correctly to sentry and I see correct error location with them. So, without code-push everything works correctly.
But when I'm making code-push release after which I manually upload source-maps to sentry it shows me correct issue location only after first crash but If I close app and open it again if I crash app again on sentry dashboard I receive issue with error `Source code was not found`, see linked issues above.
It's the same issue from same device, with same version of code-push bundle, with same sentry release version but it works only at the first time, after release a code-push but after app restarting issue can't associate itselft with any source-maps in Sentry dashboard.

Also I was trying to upgrade to latest @sentry/react-native version (1.4.5) and this was not helpful.

**Steps to reproduce:**
- Make code-push release with:
```
code-push release-react ProjectOwner/projectName ios/android -d Production -t "$VERSION" --outputDir ./build/CodePush
```
- Upload bundle and source maps to sentry
```
sentry-cli --auth-token=$SENTRY_TOKEN releases --org=$SENTRY_ORG --project=$PROJECT files $RELEASE_NAME upload-sourcemaps --bundle=./build/CodePush/main.jsbundle --bundle-sourcemap=./build/CodePush/main.jsbundle.map
```
or
```
sentry-cli --auth-token=$SENTRY_TOKEN releases --org=$SENTRY_ORG --project=$PROJECT files $RELEASE_NAME upload-sourcemaps --bundle=./build/CodePush/index.android.bundle --bundle-sourcemap=./build/CodePush/index.android.bundle.map
```
- Crash the app and receive issue on sentry dashboard with correct source map
- Close and open app again, crash it, receive same error but with `Source code was not found`

**Actual result:**

`Source code was not found` error

**Expected result:**

See correct source map for each error

**Comment by jennmueng** [comment]
@stas-kravchuk Can you make the sentry.io links public by going here and sharing these links?

<img width="321" alt="Screen Shot 2020-06-15 at 2 23 25 PM" src="https://user-images.githubusercontent.com/30991498/84629025-dde17080-af13-11ea-986d-a6a36bb4363d.png">

**Comment by stas-kravchuk** [comment]
@jennmueng done

**Comment by jennmueng** [comment]
@stas-kravchuk My bad, you would also need to paste the new links generated by the share modal, it would look something like `sentry.io/share/...`

**Comment by stas-kravchuk** [comment]
@jennmueng done

**Comment by jennmueng** [comment]
@stas-kravchuk Ok, can you check and see the events have a `dist` tag? The sourcemap will have to exactly match both the release and the dist set on the event to be symbolicated correctly. You can do that by adding a `--dist` argument to the cli command.
```sh
--dist $DIST

# Example:
--dist 3.0.0.0
```

Also, to make sure with codepush builds the distribution value is matching, you should also use `Sentry.setDist()` in the code.

**Comment by stas-kravchuk** [comment]
@jennmueng We are not setting `--dist` argument manually and we are not doing `Sentry.setDist()` in the code, but seems like both of those events has same `dist` as you can see on screenshots below
<img width="867" alt="Screenshot 2020-06-15 at 12 34 58" src="https://user-images.githubusercontent.com/40563919/84642410-19287300-af05-11ea-9edd-a5daadd84077.png">
<img width="864" alt="Screenshot 2020-06-15 at 12 35 49" src="https://user-images.githubusercontent.com/40563919/84642422-1d549080-af05-11ea-8c22-479940adecbb.png">

**Comment by jennmueng** [comment]
@stas-kravchuk If you go to the releases page, and look at the artifacts for that version, `4.1.1-codepush:v20` does it have a Distribution set? If it doesn't then you will need to set one with the `--dist` argument when uploading the source map.

The dist will need to match exactly with the event's to have the sourcemap be symbolicated.

**Comment by stas-kravchuk** [comment]
@jennmueng I'm on release page and I don't see any `dist` labels even for releases without code-push that works correctly, or `dist` is something that is placed in the brackets?
<img width="1440" alt="Screenshot 2020-06-15 at 13 26 28" src="https://user-images.githubusercontent.com/40563919/84647889-c0f56f00-af0c-11ea-867b-a5bae89975a2.png">

**Comment by jennmueng** [comment]
@stas-kravchuk Click on the name under "Release Version" and navigate to the "Artifacts" tab.

**Comment by stas-kravchuk** [comment]
@jennmueng oh yes, they are actually missed! Thanks, I didn't even know about this page, I will try to make new code-push release and upload source maps with `dist` argument later today and will let you know, thank you a lot :)

**Comment by stas-kravchuk** [comment]
@jennmueng everything works fine now, seems that issue was in missed `--dist` argument in `sentry-cli releases files` and in`Sentry.setDist()`
My problem is solved - thank you :)

**Comment by skizzo** [comment]
Hi,

> @stas-kravchuk Click on the name under "Release Version" and navigate to the "Artifacts" tab.

it seems like this has been changed in the Dashboard, following you instructions I am not able to see whether there is a `dist` label or not. 

![Screenshot 2020-09-19 at 19 45 23](https://user-images.githubusercontent.com/2892572/93685609-d0a6c580-fab0-11ea-8197-1c87c953f435.png)

.. which leads to ..

![Screenshot 2020-09-19 at 19 45 31](https://user-images.githubusercontent.com/2892572/93685610-d3091f80-fab0-11ea-9160-88c31d4889d9.png)

How can I determine whether the `dist` label was set correctly?

**Comment by jennmueng** [comment]
@skizzo They would have this little label with the dist below the filename:
<img width="249" alt="Screen Shot 2020-09-21 at 2 19 05 PM" src="https://user-images.githubusercontent.com/30991498/93740847-7d01bc80-fc15-11ea-9d4f-54d1f7809e18.png">

**Comment by skizzo** [comment]
Ha! Thank you good sir.
