### ISSUE TITLE
Context not being sent

### ISSUE THREAD

**Issue by Legi0n1138** [getsentry/sentry-react-native#937]
**OS:**
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS (haven't checked)
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.0

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/captainai/issues/1727248936/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'superSecretDSNKey'
});
Sentry.setContext('context1', {key1: 'value2'});

Sentry.configureScope(scope => {
    scope.setContext('context2', {key2: 'value2'});
    scope.setExtra('extra', {key3: 'value3'});
});

[some exception triggering code]
```

---
**I have following issue:**

I'm trying to add some custom context to the report. And it's being added to the `event` object, this can be checked by adding logging to `beforeSend` hook:

![image](https://user-images.githubusercontent.com/28903696/84776148-a1cc0f80-afe8-11ea-98d8-18ad5de9cb13.png)

However, the actual context is missing both on the issue page and in the issue json file. The extras, user info, tags, etc are being correctly added.

**Actual result:**

Issues missing custom context

**Expected result:**

Issues have custom context

**Comment by jennmueng** [comment]
Hi, can you paste a link to the raw json, maybe to somewhere like pastebin? We can't access the link to the issue as we don't have access to your organization.

Thanks!

**Comment by Legi0n1138** [comment]
Hey @jennmueng 
Do you mind if I send you the data via email? I want to avoid posting this project's debug data on public forums

**Comment by jennmueng** [comment]
@Legi0n1138 Yes sure, I completely understand. You can send it to jenn@sentry.io

**Comment by Legi0n1138** [comment]
@jennmueng thank you for understanding! Data sent ✔️

**Comment by jennmueng** [comment]
@Legi0n1138 Thanks for the data, I looked into it and found out that on Android we don't support custom keys yet. In the meantime, if you update to the latest version we have a workaround where the context are passed as extras instead so at least you get the information, just not formatted as nicely.

**Comment by Legi0n1138** [comment]
Hey, @jennmueng thank you for the response. Updated to `1.4.5` but for some reason don't see any difference in behavior.
Maybe you could show me a working example?
Also, is it possible to set the context in `beforeSend` on android?

Another thing is: SDK version in JSON output is "1.4.1" (and it was the same way when we were on 1.4.0)

**Comment by jennmueng** [comment]
@Legi0n1138 Hmm as the SDK is showing the wrong version on the JSON output, have you made sure that the SDK on Android was linked and installed correctly? Otherwise, you can look at the `sample` app the this repo, all the scope/contexts in there have been confirmed working.

And yes, you can set the context in the `beforeSend`. You can edit the event passed to the `beforeSend` callback in any way you like and return it.

**Comment by marandaneto** [comment]
@jennmueng this has been fixed, right? should we close it?
https://github.com/getsentry/sentry-react-native/releases/tag/1.5.0
