### ISSUE TITLE
Could not parse Info.plist file on IOS

### ISSUE THREAD

**Issue by diegotsi** [getsentry/sentry-react-native#944]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.5

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

Hi! I follow all instructions to use sentry on react-native but I'm getting this error, that's my debug from Xcode:

```
DEBUG   2020-06-19 11:09:38.235397 -03:00 sentry-cli version: 1.54.0, platform: "darwin", architecture: "x86_64"
  INFO    2020-06-19 11:09:38.236254 -03:00 sentry-cli was invoked with the following command line: "/Users/diego/Desktop/Git/al-khor/node_modules/@sentry/cli/sentry-cli" "--log-level=debug" "upload-dsym"
  INFO    2020-06-19 11:09:38.236710 -03:00 Issuing a command for Organization: juntos-somos-mais-fidelizacao- Project: app-juntos-somos-mais
  DEBUG   2020-06-19 11:09:38.238047 -03:00 error: running update nagger
  DEBUG   2020-06-19 11:09:38.238293 -03:00 skipping update nagger because session is not attended
error: Could not parse Info.plist file
  caused by: InvalidXmlSyntax
  DEBUG   2020-06-19 11:09:38.238746 -03:00 client close; no transport to shut down  (from sentry)
```
I'm using version `1.54.0`

**Steps to reproduce:**
- Following the docs, and configure sentry on react native
- Try to run the app on ios

**Actual result:**
Could not parse Info.plist file

**Expected result:**
Build succesfull

**Comment by jennmueng** [comment]
This looks like you just have an invalid Info.plist, can you please check and make sure everything is correct in there?

**Comment by diegotsi** [comment]
@jennmueng everything is correct, this error is caused by the "Upload debug symbols to sentry" script if I remove this everything works fine.

**Comment by jennmueng** [comment]
Closing this on the basis of being more than a year old with no updates. If the issue still persists, feel free to reopen.
