### ISSUE TITLE
Match release in source maps with events and sessions

### ISSUE THREAD

**Issue by flp** [getsentry/sentry-react-native#947]
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.5.0

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...',
  enableAutoSessionTracking: true,
  // other options
});
Sentry.setRelease('...');
```

---
**I have following issue:**

I provide a custom release name for iOS and Android via `setRelease`, but source maps uploaded by sentry-cli in xcode and sentry.gradle follow a different pattern, and I do not see a way to specify the release in xcode or sentry.gradle.

The goal is to have source maps, events, and sessions all use the same release (one release for ios, one for android) to get insights from sentry release health.

For Android, using the source maps from sentry.gradle is not really an option because we split our android apks by architecture with different versionCode. And sentry.gradle creates one source map per versionCode, but we would like all apks from a build to use the same release in sentry.io

Do you have any recommendation for achieving the goal?

**Steps to reproduce:**
- gradle build or xcode build
- start app and send a Sentry event

**Actual result:**

ios source maps are uploaded to release `bundleId@version+buildNumber`

android source maps are uploaded to releases `appId@version+versionCode`, one for each versionCode

events are tagged with the release specified in `setRelease`

**Expected result:**

Able to specify the release for source maps so that source maps, events, and sessions use the same release, and a single release on sentry.io is created during a build

**Comment by jennmueng** [comment]
You should be able to manually upload a sourcemap to a specified release and distribution with this cli command:
```bash
sentry-cli releases \
    files {RELEASE} \
    upload-sourcemaps\
    --dist {DIST}\
    --validate\
    --rewrite "./build/main.jsbundle" "./build/main.jsbundle.map"
```

**Comment by marandaneto** [comment]
I think we should provide a way of overwriting the release name though, I've tagged as a feature request.

**Comment by flp** [comment]
yup that would be helpful to be able to specify release for sentry's xcode build step and sentry.gradle!

**Comment by flp** [comment]
@jennmueng thanks for that

What about the existing source maps uploaded by the sentry.gradle and xcode build steps?

im no gradle expert, so not entirely sure, but looks like sentry.gradle instruments the react native bundle task

and for xcode the react-native-xcode step is wrapped by sentry-cli

seems like i have two options, either
1. upload the source maps generated by these build steps to a custom release and cleanup any unwanted releases on sentry.io
2. disable the build steps and handle the creation and uploading of source maps 

Would either work?

**Comment by marandaneto** [comment]
@flp both would work, but basically you'd be doing this manually.

this is a very fragile step as it changes quite often either by RN breaking changes, or Gradle, AGP (if Android)...

Btw Gradle only hooks in the build lifecycle and do some stuff, but it also uses sentry-cli internally, so if you know what you are doing, sentry-cli is all you need :)

**Comment by flp** [comment]
Was able to get the bundle and source map files for android and upload them to sentry to a custom release, thanks for the help

For ios it seems more complicated. I dont see the bundle or source map files after the xcode react-native build step. From looking at the sentry-cli source, it looks like sentry-cli is downloading the files from the running metro server. any suggestions for getting these files?

**Comment by jennmueng** [comment]
@flp You can use the `react-native` cli to manually bundle the source maps, for example:
```
react-native bundle --dev false --platform ios --entry-file index.js --bundle-output ./build/main.jsbundle --sourcemap-output ./build/main.jsbundle.map
```

**Comment by flp** [comment]
Won't that result in generating the bundle and source maps twice for ios? once during xcode build, and again to upload to sentry

**Comment by jennmueng** [comment]
Yes but unless you can find the path where Xcode outputs them to, this would work.

**Comment by jennmueng** [comment]
Ok so in the latest version of the SDK, we deprecated `setRelease` and `setDist` and you can set the release in the `Sentry.init` call instead and all the sessions should be correctly attributed to the release. 

You can see an example here: https://docs.sentry.io/platforms/react-native/codepush/
