### ISSUE TITLE
React Native - Source Maps 

### ISSUE THREAD

**Issue by rafalkowalewski** [getsentry/sentry-react-native#951]
**OS:**
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.5.0

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X] sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
https://sentry.io/share/issue/ba3a4fc6d6d4470db24203bf7eadc38d/

**Configuration:**
```
Sentry.init({
  dsn: '__DSN__',
  environment: __DEV__ ? 'development' : (PROD ? 'production' : 'staging'),
  enableAutoSessionTracking: true,
  release: AppInfo.release,
  dist: AppInfo.dist,
});
```

I use hermes.

---
**I have following issue:**

I have decited to post new issue because I probably have tried everything what I have seen on Internet...

The first problem:
I do not know why, but if i not upload manually source maps, then i will not see them on my project. Now i have everything automated so please help mi with the next one.

The second problem:
Like i wrote, I upload source maps by myself by this command after building release version via gitlab pipeline:
./node_modules/@sentry/cli/bin/sentry-cli releases files $PACKAGE_NAME@$CURRENT_VERSION_NAME+$CURRENT_VERSION_CODE upload-sourcemaps --dist $CURRENT_VERSION_CODE --strip-prefix . --rewrite android/app/build/generated/assets/react/release/android.main.bundle android/app/build/generated/assets/react/release/android.main.bundle.map
and the result in console is
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete
Source Map Upload Report
  Minified Scripts
    ~/android.main.bundle (sourcemap at android.main.bundle.map)
  Source Maps
    ~/android.main.bundle.map

and in the Sentry project:
![image](https://user-images.githubusercontent.com/25037064/86540006-9b52f880-bf01-11ea-938f-bf842cdc70cc.png)

but when i open any issue connected with the same release name and dist I get: 
![image](https://user-images.githubusercontent.com/25037064/86539924-ce48bc80-bf00-11ea-8bf3-b41782e5bc82.png)
![image](https://user-images.githubusercontent.com/25037064/86540188-97c07100-bf03-11ea-8776-1d338a4821d6.png)

Can anyone help me with this?

**Comment by williamgurzoni** [comment]
Same problem here

**Comment by jennmueng** [comment]
Hey guys, so the name of the bundle/sourcemap has to match **exactly**. In the stack trace it's `index.android.bundle` while in the artifacts you have it uploaded as `android.main.bundle`. If you can rename the bundle and source map to `index.android.bundle` and `index.android.bundle.map` and reupload them they should work.

**Comment by rafalkowalewski** [comment]
@jennmueng thank you for your reply!
You are right and now I am one step further, but still not there where I want i want to be 😄 

![image](https://user-images.githubusercontent.com/25037064/86608802-4d92ca80-bfab-11ea-87eb-4bf2f025f4fd.png)

I changed name and now I see more than before, but this is still unreadable 😞
Do you have any idea what else should I change?

**Comment by jennmueng** [comment]
> @jennmueng thank you for your reply!
> You are right and now I am one step further, but still not there where I want to be 😄
> 
> ![image](https://user-images.githubusercontent.com/25037064/86608802-4d92ca80-bfab-11ea-87eb-4bf2f025f4fd.png)
> 
> I changed name and now I see more than before, but this is still unreadable 😞
> Do you have any idea what else should I change?

Hmm this looks like a bad source map. Can you try manually bundling the source map with 
```bash
react-native bundle \
  --dev false \
  --platform {PLATFORM} \
  --entry-file index.js \
  --bundle-output ./build/index.android.bundle \
  --sourcemap-output ./build/index.android.bundle.map
```
and uploading that to sentry?

**Comment by rafalkowalewski** [comment]
I do exactly this:
react-native bundle --dev false --platform android --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map
and then:
./node_modules/@sentry/cli/bin/sentry-cli releases files $PACKAGE_NAME@$CURRENT_VERSION_NAME+$CURRENT_VERSION_CODE upload-sourcemaps --dist $CURRENT_VERSION_CODE --strip-prefix . --rewrite ./index.android.bundle ./index.android.bundle.map

**Comment by lucianomlima** [comment]
Same here, only with Android source maps in RN 0.61.5 with Hermes enabled and using Code-Push and `@sentry/react-native` v1.5.0

**Comment by rafalkowalewski** [comment]
@jennmueng do you have any other idea to fix this issue?

**Comment by jennmueng** [comment]
@rafalkowalewski From the screenshots it looks like Sentry still isn't correctly detecting the source maps.. does the error "Source code was not found" still showing at the top?

**Comment by rafalkowalewski** [comment]
There was nothing but I found in the new one something like this - maybe it is connected to that.

![image](https://user-images.githubusercontent.com/25037064/88414755-a650c880-cddd-11ea-8ec8-00a1f212c3ab.png)

**Comment by jennmueng** [comment]
Sorry for the late reply, we've been looking into the timestamp issue for a past couple of days, and I've made an issue specifically for it. However it shouldn't have any effect on sourcemaps.

**Comment by mym0404** [comment]
I am experiencing same thing.
`React Native` : `0.63.2`
`Sentry SDK` : `1.6.3`

Previously, when I upgraded sentry sdk, the source map was uploaded and I could see a well parsed stack trace.
But suddenly, stack trace has been broken.

![image](https://user-images.githubusercontent.com/33388801/89277670-1bdf5300-d680-11ea-937f-93ee67747a05.png)

**Comment by jennmueng** [comment]
@mym0404 Do you have any errors displaying at the top of the issue page where the source map doesn't work?

**Comment by mym0404** [comment]
> @mym0404 Do you have any errors displaying at the top of the issue page where the source map doesn't work?

No just timestamp error is showing

**Comment by jennmueng** [comment]
@mym0404 Can I have the full (not the share) link to the error? I will investigate this.

**Comment by mym0404** [comment]
@jennmueng It is weird. In the same release, some errors in the same platform(android), somethings are parsed with the correct source maps but others not.

One question, at that error invocation time, whether the source maps are already uploaded affects source map parsing? 

Thank you for your attention.

**Comment by jennmueng** [comment]
@mym0404 Yes the source maps need to be present before the error occurs for them to be parsed. We currently don't support processing events after they've been saved to our backend, they're only processed once when they're received.

**Comment by jennmueng** [comment]
@rafalkowalewski I just found out about a prior issue for source maps on Android, it was before I joined Sentry so I had no knowledge of this my apologies. Can you try [this fix](https://github.com/getsentry/sentry-react-native/issues/761#issuecomment-587498344) and see if it solves your issue?

**Comment by rafalkowalewski** [comment]
@jennmueng thank you for your message. I will let you know this/next week if it is work. I am going to release a new production version :)

**Comment by 15matias15** [comment]
Hey @rafalkowalewski were you able to solve the issue? I'm facing the same problem on my project

**Comment by patelnets** [comment]
this worked for me 
`react-native bundle --dev false --platform android --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.map`

`./node_modules/@sentry/cli/bin/sentry-cli releases --org <ORG> --project <PROJECT> files <APPLICATIONID>@<VERSION>+<BUILD> upload-sourcemaps --dist<BUILD> --strip-prefix . --rewrite ./index.android.bundle ./index.android.bundle.map`

Where VERSION is of format 1.4.6
BUILD is like 123
APPLICATIONID is like uk.co.examplecompany.android

**Comment by 15matias15** [comment]
@patelnets do you have Hermes enabled?

**Comment by rafalkowalewski** [comment]
> Hey @rafalkowalewski were you able to solve the issue? I'm facing the same problem on my project

No :( i am still facing with it. I will let you know if i find some solution.

**Comment by 15matias15** [comment]
@rafalkowalewski  thanks, I'll let you know too if I found something

**Comment by jennmueng** [comment]
> > Hey @rafalkowalewski were you able to solve the issue? I'm facing the same problem on my project
> 
> No :( i am still facing with it. I will let you know if i find some solution.

@rafalkowalewski Did the solution on prior issue I sent not work?

**Comment by rafalkowalewski** [comment]
I wanted to tell you it works! :) but I had to modify it a bit and now everything looks pretty good.
Here is my script:

```
mkdir bundle
npm run react-native -- bundle --dev false --platform android --entry-file index.js --assets-dest bundle --bundle-output bundle/index.android.bundle --sourcemap-output bundle/index.android.bundle.map
node_modules/hermes-engine/win64-bin/hermesc -emit-binary -out bundle/index.android.bundle.hbc bundle/index.android.bundle -output-source-map -w
node node_modules/react-native/scripts/compose-source-maps.js bundle/index.android.bundle.map bundle/index.android.bundle.hbc.map -o bundle/index.android.bundle.map
npm run sentry -- releases files $PACKAGE_NAME@$CURRENT_VERSION_NAME+$CURRENT_VERSION_CODE upload-sourcemaps --dist $CURRENT_VERSION_CODE --strip-prefix . --rewrite ./bundle
```

**IMPORTANT INFO:**
select the proper hermes file depending on your system
![image](https://user-images.githubusercontent.com/25037064/93668907-32a30300-fa90-11ea-8448-635971fe6c3f.png)

**Comment by 15matias15** [comment]
@rafalkowalewski  what do you do on `npm run sentry` ?
Are you getting those files too?
![image](https://user-images.githubusercontent.com/41986785/93755857-5dae6380-fc04-11ea-8aea-682e401d30fc.png)

**Comment by rafalkowalewski** [comment]
Oh sorry... i forgot to explain it.
It runs sentry cli. I do not have it globally, so i do it via „npm run” to run it from node_modules.

**Comment by 15matias15** [comment]
@rafalkowalewski thanks. Do you have the same 3 files on your sentry artifacts?

**Comment by rafalkowalewski** [comment]
> @rafalkowalewski thanks. Do you have the same 3 files on your sentry artifacts?

Yes, exactly 😃

**Comment by jennmueng** [comment]
That's great, looks like we can close this?

**Comment by 15matias15** [comment]
@jennmueng I still have one issue, but not related to sentry. We use `mobx` & `mobx-react` to handle the store with `@inject` decorator and we have the next component:
```
@inject (STORE)
<HOC>
--a 2º HOC with another inject--
@inject (STORE)
<2HOC>
<COMPONENT>
</COMPONENT>
</2HOC>
</HOC>
```

I put a `throw new Error()` on the `component` and sentry it's showing me this 
`Error observable(XXX/XXX/react/main/stores/STORE)`
and this as stack trace
![image](https://user-images.githubusercontent.com/41986785/94238938-555e6d00-ff11-11ea-92c5-433c42c971e7.png)


any idea??

**Comment by rafalkowalewski** [comment]
> That's great, looks like we can close this?

Yes :)

**Comment by freemile2ru** [comment]
I still have this issue I have tried everything I can find on the internet but no luck
