### ISSUE TITLE
blacklistUrls and ignoreErrors options not working

### ISSUE THREAD

**Issue by nguyenhose** [getsentry/sentry-react-native#956]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^1.3.7

**`react-native` version:** 0.60.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- []  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({ 
    dsn: Config().SENTRY_LINK,
    release: getRelease(),
    dist: getBuildNumber(),
    blacklistUrls: [
      new RegExp('(http|https)://(xxx|xxx-staging|xxx-dev).xxx.com/api/xxx'),
      new RegExp('https://clients3.google.com/generate_204')
    ],
    ignoreErrors: [
      /\/Network request failed/,
      /\/JSON Parse error/,
      /\/Connection timeout at/,
  ]
  });
```

**Actual result:**

[Actual result]
Error and xhr request url still show up on sentry and breadcum

**Expected result:**

[Expected result]
Should not appear following above regex

**Comment by jennmueng** [comment]
Hello, are you sure the regex you're using is entirely correct? Can you try instead of `/\/Network request failed/` try `/^Network request failed/`. And you would also need to escape the `/` characters in your url expression.
