### ISSUE TITLE
android --variant=release fails INSTALL_FAILED_INVALID_APK: Scanning Failed.: Package base.apk code is missing

### ISSUE THREAD

**Issue by himat** [getsentry/sentry-react-native#959]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** @sentry/react-native 1.6.1

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
This is an issue during building, so there is no sentry issue ticket.

**Configuration:**

(`@sentry/react-native`)
```
     Sentry.init({
         dsn: "https://<my dsn>@o369343.ingest.sentry.io/5328328
 ",
         environment: __DEV__ ? "dev" : "prod",
     });
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
`yarn react-native run-android  --variant=release`
If I run without `--variant=release`, then there is no issue and the app installs on my device.  
I can also do `cd android; ./gradlew bundleRelease` to generate the aab file, and I can then upload that to the google play store and download the app that way with no problem.
But trying to run in the release mode locally does not work after installing sentry react native.

**Actual result:**

Relevant part of the build log where it fails:
```
> Task :app:installRelease
10:25:15 V/ddms: execute: running am get-config
10:25:15 V/ddms: execute 'am get-config' on '3958395758553398' : EOF hit. Read: -1
10:25:15 V/ddms: execute: returning
Installing APK 'app-release.apk' on 'SM-G960U1 - 10' for app:release
10:25:15 D/app-release.apk: Uploading app-release.apk onto device '3958395758553398'
10:25:15 D/Device: Uploading file onto device '3958395758553398'
10:25:15 D/ddms: Reading file permision of /Users/x/Workspace/Web/app-name/android/app/build/outputs/apk/release/app-release.apk as: rw-r--r--
10:25:17 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-release.apk"
10:25:29 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-release.apk"' on '3958395758553398' : EOF hit. Read: -1
10:25:29 V/ddms: execute: returning

> Task :app:installRelease FAILED
875 actionable tasks: 12 executed, 863 up-to-date
Unable to install /Users/x/Workspace/Web/app-dir/android/app/build/outputs/apk/release/app-release.apk
com.android.ddmlib.InstallException: INSTALL_FAILED_INVALID_APK: Scanning Failed.: Package /data/app/com.converge.com-rw57b2RD6PaGmvWY7vNgOw==/base.apk code is missing
        at com.android.ddmlib.Device.installRemotePackage(Device.java:1133)
        at com.android.ddmlib.Device.installPackage(Device.java:963)
        at com.android.ddmlib.Device.installPackage(Device.java:939)
        at com.android.ddmlib.Device.installPackage(Device.java:928)
        at com.android.builder.testing.ConnectedDevice.installPackage(ConnectedDevice.java:126)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:175)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.doTaskAction(InstallVariantTask.java:106)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
```

**Expected result:**

Successful compilation for release.
The release command was working fine before I installed sentry and set it up.
I set it up by running `yarn add @sentry/react-native` and then `yarn sentry-wizard -i reactNative -p ios android`
(additionally, I don't know if this is relevant or just a bug in the docs, but at https://docs.sentry.io/platforms/react-native/ it says that the following file (patch _MainApplication.java_ for Android) should be changed after running the sentry wizard, but it wasn't changed for me)

**Comment by jennmueng** [comment]
@marandaneto Looks like a bad apk is generated because I see an unexpected EOF being hit in the logs. Would you mind looking into this? Thanks.

**Comment by marandaneto** [comment]
@himat hey, do you have `multidex` enabled? what'ss your `minSdkApi`?
Did you try to uninstall the App. from the device/emulator and install it again?
What's your `com.android.tools.build:gradle` version?

If you remove Sentry, does it work or still the same problem? it doesn't look like related to Sentry though.

**Comment by himat** [comment]
I had a colleague run the sentry wizard himself and after just using his generated files, it's all working now.
And interestingly, his sentry wizard did actually generate the `MainApplication.java` changes that my sentry didn't.
