### ISSUE TITLE
'node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by sundariragavan** [getsentry/sentry-react-native#970]
**OS:**
- MacOS

**Platform:**
-  Android

**SDK:**
- [ ]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 0.0.0

**`react-native` version:** 0.60.3.
**Are you using Expo?**
-  No

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

**Comment by jennmueng** [comment]
Please fill in the template and don't leave it empty. Please also give us a description because we have no idea what the problem is or where that error message in the title occurred at all.

**Comment by alexkendall** [comment]
Same exact issue here.

**Comment by marielawhaley** [comment]
Same issue here!
