### ISSUE TITLE
Performance monitoring via APM

### ISSUE THREAD

**Issue by lukebars** [getsentry/sentry-react-native#971]
Hey, I've just read the new [Sentry blog post about performance monitoring](https://blog.sentry.io/2020/07/14/see-slow-faster-with-performance-monitoring) and I was thinking if APM is in future roadmap of RNSentry? Would be a cool feature to have.

**Comment by jennmueng** [comment]
@lukebars It is, going to start work on it very soon!

**Comment by Fr4gger** [comment]
I am just starting with Sentry and just wanted to ask: is performance monitoring ready for React Native? And also, will this work with sentry-expo package installation?

**Comment by artshik** [comment]
@jennmueng - I believe we activated the Performance trial without realizing that it wasn't yet ready for React Native. Would we be able to get an extension on the trial when React Native support gets released, so we can set it up, make sure it fits our needs, and then upgrade if necessary? Or let me know who else I can reach out to about this. Thanks!

**Comment by jennmueng** [comment]
@artshik Yes it should be no issue, you can handle this with our support. One way to do this is you can email support@sentry.io

**Comment by RosieWatson** [comment]
@jennmueng any update on how the performance monitoring is looking for RN? Wondering if there are any updates on the timeline as looking to use it for my app

**Comment by artshik** [comment]
Thanks @jennmueng, I've reached out to support@sentry.io on the email they sent about the trial ending soon.

**Comment by Fr4gger** [comment]
Hey @jennmueng any news regarding the implementation of APM for React Native? Looking forward to implementing this to some projects.

**Comment by paeder** [comment]
@jennmueng Any updates on APM for react native? Any new eta for availability?

**Comment by Fr4gger** [comment]
> @Fr4gger @paeder, we're going to have a major release bump soon, it overhauls a couple of things that we needed for performance. It'll be coming right after the major release is done, and is top priority for the React Native SDK.

Thanks a lot for the update. Looking forward to it!

**Comment by giautm** [comment]
I'm also waiting for this feature. :+1:

**Comment by hvlong** [comment]
Great, I'm also waiting for this feature too.

**Comment by Fr4gger** [comment]
Hey @jennmueng, sorry for the insistence but, are there any updates regarding the implementation of APM for React Native?

**Comment by jennmueng** [comment]
@Fr4gger  We have a PR that will open React Native up to manual instrumentation with examples in the sample app coming up:
https://github.com/getsentry/sentry-react-native/pull/1167
https://github.com/getsentry/sentry-react-native/pull/1168

**Comment by jennmueng** [comment]
Manual tracing instrumentation is out in [2.1.0](https://github.com/getsentry/sentry-react-native/releases/tag/2.1.0). You can now call `Sentry.startTransaction` in React Native.

You can use the guide we have for JS here: https://docs.sentry.io/platforms/javascript/performance/

You will need to define either `tracesSampleRate` or `tracesSampler` but don't use any `BrowserTracing` just yet, we will be implementing auto performance tracing for React Native separately.

**Comment by jennmueng** [comment]
Good news, we've gotten auto performance tracing working! You can keep up through this PR: https://github.com/getsentry/sentry-react-native/pull/1230
