### ISSUE TITLE
Android app force-closes after fresh production build & install, TypeError: k.startWithDsnString is not a function

### ISSUE THREAD

**Issue by pedro-lb** [getsentry/sentry-react-native#972]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.6.2

**`react-native` version:** ~0.61.5

**Are you using Expo?**
- [x]  Yes, but we're ejected, using Bare workflow
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

A new android app force-closes right after installing a freshly generated production apk. 

When trying to open the app again, it works normally.

We've initialized `@sentry/react-native` by following: https://docs.sentry.io/platforms/react-native/#integrating-the-sdk

Note: we're using autolink, so we only ran `yarn sentry-wizard -i reactNative -p ios android`. 

**Steps to reproduce:**
- Generate production apk using Android Studio
- Install on device (wasn't installed before)
- Open app (it crashes)
- Open app again (it works)

**Actual result:**

App crashes

**Expected result:**

App should not crash

**Logcat on error:**

Note: the error below only happens when opening the app for the very first time after installing it. When opening the app again, even after rebooting the device, it does not happen anymore.

```
07-15 12:25:50.218  3402  3481 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-15 12:25:50.218  3402  3481 E AndroidRuntime: Process: app.alltleta, PID: 3402
07-15 12:25:50.218  3402  3481 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: k.startWithDsnString is not a function. (In 'k.startWithDsnString(t.dsn,t)', 'k.startWithDsnString' is undefined), stack:
07-15 12:25:50.218  3402  3481 E AndroidRuntime: N@1081:575
07-15 12:25:50.218  3402  3481 E AndroidRuntime: c@1055:213
07-15 12:25:50.218  3402  3481 E AndroidRuntime: p@1083:356
07-15 12:25:50.218  3402  3481 E AndroidRuntime: initAndBind@1059:196
07-15 12:25:50.218  3402  3481 E AndroidRuntime: init@1085:978
07-15 12:25:50.218  3402  3481 E AndroidRuntime: configureSentry@1027:225
07-15 12:25:50.218  3402  3481 E AndroidRuntime: <unknown>@585:595
07-15 12:25:50.218  3402  3481 E AndroidRuntime: v@2:1474
07-15 12:25:50.218  3402  3481 E AndroidRuntime: <unknown>@6:94
07-15 12:25:50.218  3402  3481 E AndroidRuntime: v@2:1474
07-15 12:25:50.218  3402  3481 E AndroidRuntime: d@2:876
07-15 12:25:50.218  3402  3481 E AndroidRuntime: global code@4278:4
07-15 12:25:50.218  3402  3481 E AndroidRuntime: 
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
07-15 12:25:50.218  3402  3481 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

**Comment by jennmueng** [comment]
@pedro-lb This looks like you have a bad installation somewhere. We removed the `startWithDsnString` method back in [1.4.0](https://github.com/getsentry/sentry-react-native/releases/tag/1.4.0)

**Comment by pedro-lb** [comment]
Not entirely sure on what was causing the issue, but it seems that the new version (1.7.0) fixes it.

Release https://github.com/getsentry/sentry-react-native/releases/tag/1.7.0

Thanks!

**Comment by yusufdeepwork** [comment]
I get same error
