### ISSUE TITLE
'Sentry/Sentry.h' file not found

### ISSUE THREAD

**Issue by a35227** [getsentry/sentry-react-native#975]
**OS:*
- [x]  MacOS

**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.6.1)
**`react-native` version:** 0.57.8

I not use cocoaPod  and it 'Sentry/Sentry.h' file not found

**Comment by jennmueng** [comment]
Is the issue still there? This sounds like just a bad installation and not an issue with the SDK.
