### ISSUE TITLE
The touch component tree got obfuscated names on release build

### ISSUE THREAD

**Issue by stackia** [getsentry/sentry-react-native#976]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.5

**`react-native` version:** 0.63.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/mindhand/issues/1774680261/

**Configuration:**

![image](https://user-images.githubusercontent.com/5107241/87843658-e3522200-c8e8-11ea-9659-07d65dbbdbb5.png)

---
**I have following issue:**

In our production build, we have `<TouchEventBoundry>` enabled but it only logs the obfuscated component names. Our components are almost all functional components with hooks.

Looks like we need to change `metro.config.js` to enable the `keep_fnames` minifier option. I think this should be documented on https://docs.sentry.io/platforms/react-native/touchevents/ .

**Actual result:**

![image](https://user-images.githubusercontent.com/5107241/87843802-08936000-c8ea-11ea-85ed-03c1e685c575.png)

**Expected result:**

Full component name logged.

**Comment by jennmueng** [comment]
A solution for this is to set `displayName`s on the components you want to log, I'll look into seeing if there is a way to disable minifying the function/class names like the metro config you suggested, and will document it. Thanks!
