### ISSUE TITLE
[RN 0.63.1] LogBox should be used instead of YellowBox (WARNING)

### ISSUE THREAD

**Issue by samuk190** [getsentry/sentry-react-native#977]
YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.

Can you please update source to use LogBox instead? 

 Require cycle: node_modules\react-native\Libraries\Network\fetch.js -> node_modules\whatwg-fetch\dist\fetch.umd.js -> node_modules\react-native\Libraries\Network\fetch.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

Please refactor ->  import * as Sentry from '@sentry/react-native';
to 
import {Sentry} from '@sentry/react-native';
to fix this boring warning issue!

**Comment by jennmueng** [comment]
Yep, we're right on it

**Comment by samuk190** [comment]
@jennmueng  thank you sir, I use sentry in my server and it is awesome!
